GoogleChrome/lighthouse

lighthouse-core/fraggle-rock/api.js, lighthouse-core/fraggle-rock/gather/base-gatherer.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/gather/gatherers/accessibility.js, lighthouse-core/test/fraggle-rock/gather/base-gatherer-test.js, types/gatherer.d.ts
**Summary**
Adds the base Fraggle Rock gatherer class that allows transition of gatherers to implement both APIs.
Why a new class instead of the augmenting the old class? Clarity. This approach allows anyone reading a gatherer file to immediately see whether it supports the new modes or not. We'll also be able to know from a type perspective that a gatherer doesn't support the new method, forcing a one-by-one examination of each gatherer as we upgrade them for FR.
ref #11313 
[Design Doc](https://docs.google.com/document/d/1fRCh_NVK82YmIi1Zq8y73_p79d-FdnKsvaxMy0xIpNw/edit#)
=> core(fr): add base gatherer class

lighthouse-core/config/config-helpers.js, lighthouse-core/config/config.js, lighthouse-core/fraggle-rock/config/config.js, lighthouse-core/fraggle-rock/config/default-config.js, lighthouse-core/test/config/config-helpers-test.js, lighthouse-core/test/fraggle-rock/config/config-test.js
**Summary**
Base config logic for the new Fraggle Rock config. It's lots of lines, but mostly a move + adding missing tests. 
- Moves shared logic from `config.js` to `config-helpers.js`
- merge logic
- settings resolution and validation
- gatherer resolution and validation
- Unites some naming and structural discrepancies between the two configs and gatherers/audits
- `merge` was fairly generic when it has some highly specific config logic it it, renamed to `mergeConfigFragment` 
- `resolveThing` is the new nomenclature used for converting from config input to config output (i.e. `thingJson` to `thingDefn`). This was previously some mixture of `requireThing`/`initializeThing`
- `requireThing` is now just the logic to actually require an individual `Thing`
- 
- Creates a new …
=> core(fr): add base config

lighthouse-core/test/chromium-web-tests/README.md
=> docs(chromium-web-tests): add debugging tips

proto/lighthouse-result.proto
small tweak to the proto changes from #11779
the enum isn't actually deprecated..
I would have made two separate Enums, as semantically they're _somewhat_ different.. but, you can't have two enum values that aren't unique.  example:
So sharing the same enum made sense.
Anyway, lots of comments.
=> core(proto): clarify deprecated state of EmulatedFormFactor enum

lighthouse-core/audits/errors-in-console.js, lighthouse-core/test/audits/errors-in-console-test.js
the `.Inspector` [`Network.BlockedReason`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-BlockedReason) indicates it's devtools instrumentation itself that's blocking.  And we see cases where this crops up and is just noise.
fixes https://github.com/GoogleChrome/lighthouse/issues/10198
=> core(errors-in-console): ignore BLOCKED_BY_CLIENT.Inspector errors

lighthouse-core/fraggle-rock/api.js, lighthouse-core/fraggle-rock/config/config.js, lighthouse-core/fraggle-rock/config/filters.js, lighthouse-core/fraggle-rock/config/validation.js, lighthouse-core/runner.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js, lighthouse-core/test/fraggle-rock/config/config-test.js, lighthouse-core/test/fraggle-rock/config/filters-test.js, lighthouse-core/test/fraggle-rock/config/validation-test.js, types/config.d.ts
**Summary**
This completes the core snapshot mode support for Fraggle Rock (further gatherer support pending) by filtering out any audits from a config that don't support the gatherer mode being run. This eliminates the huge mess of errors you'd see in the report when previously running in snapshot mode.
I decided against a property in `settings` because our intention is to always have the entrypoint be different for every entry mode (so there is no benefit to duplicate specification in the config) and the same config is shared between many modes which created potential for confusion if the `gatherMode` value was set to a value that didn't match audits/gatherers defined in the config. Contrast this with `onlyAudits`/`onlyCategories` which has no impact on the entrypoint. 
**Related …
=> core(fr): filter configs by gather mode

lighthouse-core/fraggle-rock/api.js, lighthouse-core/fraggle-rock/config/default-config.js, lighthouse-core/fraggle-rock/gather/base-artifacts.js, lighthouse-core/fraggle-rock/gather/base-gatherer.js, lighthouse-core/fraggle-rock/gather/snapshot-runner.js, lighthouse-core/fraggle-rock/gather/timespan-runner.js, lighthouse-core/gather/gatherers/console-messages.js, lighthouse-core/test/fixtures/fraggle-rock/snapshot-basic/onclick.html, lighthouse-core/test/fraggle-rock/api-test-pptr.js, lighthouse-core/test/fraggle-rock/gather/base-gatherer-test.js, lighthouse-core/test/gather/gatherers/console-messages-test.js, types/gatherer.d.ts
**Summary**
Adds basic timespan support to the Fraggle Rock API.
- Splits `api.js` into `snapshot-runner.js`/`base-artifacts.js`.
- Adds basic timespan flow to `timespan-runner.js`.
- Expands the FRGatherer base class with `beforeTimespan`/`afterTimespan` methods.
- Upgrades `ConsoleMessages` gatherer to support Fraggle Rock (easiest and highest impact timespan-only gatherer).
ref #11313 
loosely dependent on #11941 (though could be rebased against master if really necessary)
=> core(fr): add basic timespan support

lighthouse-core/gather/driver.js, lighthouse-core/lib/page-functions.js, lighthouse-core/test/gather/driver/execution-context-test.js, lighthouse-core/test/lib/page-functions-test.js, types/externs.d.ts
The file was actually in pretty good shape, and only needed three `// @ts-expect-error`s, two of which could be worked around instead (but which approach to take is arguable) and the other error will hopefully be fixed in future tsc updates.
This should give a lot more confidence when making changes to e.g. `nodeDetails` and the like in the future.
=> core: add type checking to page functions

lighthouse-core/config/constants.js, lighthouse-core/fraggle-rock/config/config.js, lighthouse-core/fraggle-rock/config/default-config.js, lighthouse-core/test/fraggle-rock/config/config-test.js, lighthouse-core/test/fraggle-rock/config/filters-test.js, types/config.d.ts
**Summary**
Adds basic navigations to the fraggle rock config. I decided to go ahead and document the complete navigation config object so everyone can see where it's headed and what replaces what even if the properties aren't supported in the navigation prototype yet (see config.d.ts).
**Fraggle Rock Config**
```js
const configJson = {
artifacts: [{id: 'Accessibility', gatherer: 'accessibility'}],
navigations: [{id: 'default', artifacts: ['Accessibility']}],
};
```
**Legacy Config**
```js
const configJson = {
passes: [{passName: 'defaultPass', gatherers: ['accessibility']}],
};
```
ref #11313 
[design doc](https://docs.google.com/document/d/1fRCh_NVK82YmIi1Zq8y73_p79d-FdnKsvaxMy0xIpNw/edit)
=> core(fr): add navigations to config

lighthouse-cli/test/fixtures/seo/seo-tester.html, lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js, lighthouse-core/audits/seo/font-size.js, lighthouse-core/test/audits/seo/font-size-test.js
**Summary**
This PR fixes the bug described in #11606. A description of the root cause is in [this comment][1].
Closes https://github.com/GoogleChrome/lighthouse/issues/11606
[1]: https://github.com/GoogleChrome/lighthouse/issues/11606#issuecomment-757362727
=> core(font-size): handle valueless attributes for inline styles

lighthouse-core/audits/accessibility/aria-command-name.js, lighthouse-core/audits/accessibility/aria-meter-name.js, lighthouse-core/audits/accessibility/aria-progressbar-name.js, lighthouse-core/audits/accessibility/aria-tooltip-name.js, lighthouse-core/audits/accessibility/aria-treeitem-name.js, lighthouse-core/audits/installable-manifest.js, lighthouse-core/lib/i18n/locales/en-US.json, lighthouse-core/lib/i18n/locales/en-XL.json, lighthouse-core/scripts/i18n/collect-strings.js, lighthouse-core/test/audits/installable-manifest-test.js
Our translation pipeline requires each string to be unique after placeholders are removed, or, if there are colliding strings, to have a different `@description` than the duplicates (the unique description is [passed on as the internal `meaning` property](https://github.com/GoogleChrome/lighthouse/blob/9514723a3a77f37f02b57b04e05eb47cf9f4ee7b/lighthouse-core/scripts/i18n/collect-strings.js#L585-L599)).
In the run up to 7.0, we added a few strings that don't follow this rule and so the translation process failed. e.g.
```js
/** Title of an accessibility audit that evaluates if important HTML elements have an accessible name. This title is descriptive of the successful state and is shown to users when no user action is required. */
title: 'ARIA `meter` elements have accessible names',
``` …
=> i18n: prevent strings with identical message and description

lighthouse-core/scripts/legacy-javascript/summary-sizes.txt, lighthouse-core/scripts/test-legacy-javascript.sh
I couldn't determine the revision that caused this to change, every revision I checked out ended up resulting in different results for `core-js-3-preset-env-esmodules` than what was checked in for that revision.
=> tests(legacy-javascript): sync results

proto/lighthouse-result.proto
In LR, the linter often complains about the formatting of this file. I'm backporting the automatic formatting changes that satisfy the linter.
Technically the linter didn't like the 5 instances of trailing whitespace, and the format checker didn't like the non-wrapping text.
So anyway.. both fixed.
-------
and no i don't see a simple way we can compatibly format out here in GH when landing  changes to the file. :/
=> misc(proto): backport proto formatting fixes

lighthouse-core/lib/page-functions.js
**Summary**
tl;dr the newly enabled [timer throttling](https://developer.chrome.com/blog/timer-throttling-in-chrome-88/) messes with our CPU idle check
This should address our timeout issue in DevTools. I'm not sure how to test for this specific issue since I'm sure the reason it wasn't caught to begin with is that asserting certain tests don't timeout is a flaky chromium web test we wouldn't be able to land anyway 😬 
fixes https://github.com/GoogleChrome/lighthouse/issues/11983
=> core: handle timer throttling in DevTools to avoid timeouts

clients/extension/scripts/popup.js, lighthouse-core/gather/fetcher.js, lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js, lighthouse-core/report/html/renderer/category-renderer.js, lighthouse-core/report/html/renderer/dom.js, lighthouse-core/report/html/renderer/logger.js, lighthouse-core/report/html/renderer/report-renderer.js, lighthouse-core/report/html/renderer/report-ui-features.js, lighthouse-treemap/app/src/util.js, lighthouse-viewer/app/src/lighthouse-report-viewer.js, types/externs.d.ts
Follow up to #11526, expands the use of `typed-query-selector` to uses of `querySelector`/`querySelectorAll` outside of uses of `dom.find`/`dom.findAll`. Allows removal of a few more type casts.
=> misc: use typed-query-selector for native querySelector

lighthouse-core/fraggle-rock/api.js, lighthouse-core/fraggle-rock/config/config.js, lighthouse-core/fraggle-rock/gather/navigation-runner.js, lighthouse-core/test/fixtures/fraggle-rock/navigation-basic/index.html, lighthouse-core/test/fraggle-rock/api-test-pptr.js, lighthouse-core/test/fraggle-rock/config/config-test.js, lighthouse-core/test/fraggle-rock/gather/mock-driver.js, lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js, lighthouse-core/test/gather/driver/execution-context-test.js, types/config.d.ts
**Summary**
Adds the basic framework of the navigation runner, the equivalent of `GatherRunner` in Fraggle Rock land. Its structure should be very familiar to anyone who's touched `GatherRunner` before.
It was pretty difficult to come up with a breaking point for a smaller PR, so you'll see plenty of `TODO`s, `it.todo`s and some private variable access, but the full list of what's coming is in https://github.com/GoogleChrome/lighthouse/issues/11313. I don't *think* there's going to be anything super controversial here since it's mostly matching the previous structure.
The one sticking point that come up that will require a bit more ironing out is how `supportedModes: ['navigation']` will be handled since the place we left off in the design doc doesn't feel right now that I've prototyped …
=> core(fr): add navigation runner

package.json
Release test was failing on this step:
https://github.com/GoogleChrome/lighthouse/blob/85331168e3c52ff389f7053386f95556cc03049d/lighthouse-core/scripts/release/test.sh#L41
npm fast:
https://github.com/GoogleChrome/lighthouse/blob/85331168e3c52ff389f7053386f95556cc03049d/package.json#L59
`--emulated-form-factor` is removed as of https://github.com/GoogleChrome/lighthouse/pull/11779
=> misc: fix "fast" npm script

lighthouse-core/fraggle-rock/gather/driver.js, lighthouse-core/fraggle-rock/gather/session.js, lighthouse-core/gather/connections/connection.js, lighthouse-core/gather/driver.js, lighthouse-core/test/fraggle-rock/gather/driver-test.js, lighthouse-core/test/fraggle-rock/gather/session-test.js, types/gatherer.d.ts
**Summary**
Paves the way for devtools log artifact on the new FR driver/session system. This monkeypatches our puppeteer session so we can listen for any protocol event. It's on the agenda to discuss at next sync with their team if they'd be open a PR for an official API, but it's relatively lightweight (and enables backcompat) in the meantime.
ref #11313
=> core(fr): add session.onAnyProtocolMessage listener

lighthouse-core/gather/driver/execution-context.js, lighthouse-core/gather/gatherers/accessibility.js, lighthouse-core/gather/gatherers/cache-contents.js, lighthouse-core/gather/gatherers/console-messages.js, lighthouse-core/gather/gatherers/css-usage.js, lighthouse-core/gather/gatherers/dobetterweb/appcache.js, lighthouse-core/gather/gatherers/dobetterweb/doctype.js, lighthouse-core/gather/gatherers/dobetterweb/domstats.js, lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js, lighthouse-core/gather/gatherers/form-elements.js, lighthouse-core/gather/gatherers/global-listeners.js, lighthouse-core/gather/gatherers/iframe-elements.js, lighthouse-core/gather/gatherers/meta-elements.js, lighthouse-core/gather/gatherers/seo/embedded-content.js, lighthouse-core/gather/gatherers/seo/font-size.js, lighthouse-core/gather/gatherers/seo/robots-txt.js, lighthouse-core/gather/gatherers/seo/tap-targets.js, lighthouse-core/gather/gatherers/viewport-dimensions.js, lighthouse-core/test/config/config-test.js, lighthouse-core/test/gather/driver/execution-context-test.js, lighthouse-core/test/gather/gatherers/seo/font-size-test.js
This migrates the gatherers (14) that only use `afterPass`, the interface already supported by `FRTransitionalContext`, and no `loadData`.
```
CacheContents
Appcache
Doctype
Domstats
PasswordInputsWithPreventedPaste
FormElements
GlobalListeners
IframeElements
MetaElements
EmbeddedContent
FontSize
RobotsTxt
TapTargets
ViewportDimensions
```
ref #11313
=> core(fr): initial gatherer migration for snapshot, navigation

lighthouse-core/lib/page-functions.js, types/externs.d.ts
Fixes an issue with the new typed `querySelector` (just this and #12011, I promise :).
The problem is that the [`typed-query-selector` shim](https://github.com/g-plane/typed-query-selector/blob/823e4b850280dab7192cd0468b8e97c196e9e8ec/shim.d.ts) that adds stricter types to `querySelector`/`querySelectorAll` has a type parameter that's only used in the return type. This is usually recommended against in TypeScript because it means that the contextual type can more often than not _become_ the return type as long as it fits the parameter bounds, rather than the compiler complaining that the return type and the contextual type don't match.
I put more details in https://github.com/g-plane/typed-query-selector/issues/12, but as an example, on master you could currently do
```js
/** @type …
```
=> misc: tighten querySelector types

.github/workflows/issue-assigner.yml
**Summary**
If we're ready to give it a shot this adds a bot to automatically assign issues in a round-robin fashion for initial response :)
=> misc: add issue assigner bot

lighthouse-core/fraggle-rock/config/config.js, lighthouse-core/fraggle-rock/config/validation.js, lighthouse-core/fraggle-rock/gather/base-gatherer.js, lighthouse-core/fraggle-rock/gather/navigation-runner.js, lighthouse-core/fraggle-rock/gather/runner-helpers.js, lighthouse-core/fraggle-rock/gather/snapshot-runner.js, lighthouse-core/fraggle-rock/gather/timespan-runner.js, lighthouse-core/gather/gatherers/seo/tap-targets.js, lighthouse-core/test/fraggle-rock/config/config-test.js, lighthouse-core/test/fraggle-rock/config/validation-test.js, lighthouse-core/test/fraggle-rock/gather/base-gatherer-test.js, lighthouse-core/test/fraggle-rock/gather/mock-driver.js, lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js, lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js, lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js, lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js, types/config.d.ts, types/gatherer.d.ts
**Summary**
Adds config and runner support for artifact dependencies, see #12017 for expected usage examples and discussion. I know this is a monster PR, but it truly is the minimal set of artifact dependency support that is validated, typechecked, and tested (there isn't even a single gatherer that's upgraded for dependency support in here! 🤯). I do think it's rather helpful to see it all come together rather than jump between different related PRs by potential different reviewers, but we do have few options if we want to reduce the line count.
- Split the config support from runner support and just break some types and/or add temporary meaningless types
- Land the timespan/snapshot runner test updates separately
- Land the config validation pieces separately (everything would typecheck …
=> core(fr): add artifact dependency support

lighthouse-cli/bin.js, lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js, lighthouse-cli/test/smokehouse/test-definitions/core-tests.js, lighthouse-core/gather/gatherers/form-elements.js
=> cli: do not set AutofillShowTypePredictions

lighthouse-core/computed/layout-shift-variants.js, lighthouse-core/computed/metrics/cumulative-layout-shift-all-frames.js, lighthouse-core/computed/metrics/cumulative-layout-shift.js, lighthouse-core/lib/lh-error.js, lighthouse-core/test/computed/metrics/cumulative-layout-shift-all-frames-test.js
Follow up to https://github.com/GoogleChrome/lighthouse/pull/12046#discussion_r569866794 and https://github.com/GoogleChrome/lighthouse/pull/12034.
Removes duplicated code which handles the `had_recent_input` flag in layout shift events.
Plan is to merge after #12046 lands.
=> core(cls): refactor CLS and CLS-AF

lighthouse-core/audits/unsized-images.js, lighthouse-core/test/audits/unsized-images-test.js
running kohls i saw these in the unsized-images results..
of course anything that's zero width & height isn't part of the layout (equivalent to display:none) but we hadn't really been checking that.
the boundingRect we have ends up being ideal for this calculation and includes if a parent is hidden or w/e.
sweet.
=> core(unsized-images): skip images that are zero-sized

lighthouse-core/scripts/git3po-rules/land-when-green.yaml
Unstable means all required checks passed, but some un required checks failed. For us, that means code cov (not required) can prevent our `land-when-green` label from working.
Only thing documenting `unstable` I could find: https://github.com/octokit/octokit.net/issues/1763
=> misc(git3po): merge when green for unstable state too

.github/workflows/ci.yml
Possible fix for [codecov issues](https://github.com/GoogleChrome/lighthouse/pull/12076/checks?check_run_id=1875137032#step:11:24). It seems to have some problem with the checkout `fetch-depth`, but `100` seems to fit what it's asking for and https://github.com/codecov/codecov-action/issues/190 has been closed for over a month now.
No reason it needs to go rooting around though, we already know the commit hash.
<details>
<summary>codecov issue screenshot</summary>
</details>
=> misc(ci): increase fetch-depth for codecov SHA

lighthouse-core/audits/seo/tap-targets.js, lighthouse-core/test/results/artifacts/artifacts.json, lighthouse-core/test/results/sample_v2.json
=> core(tap-targets): drop custom node rect creation

.github/workflows/ci.yml, .github/workflows/issue-assigner.yml
seems like github actions stopped supporting the short shas 😞 https://github.com/GoogleChrome/lighthouse/runs/1920862528#step:1:26
=> misc(ci): update GH actions commit SHAs

lighthouse-core/fraggle-rock/config/default-config.js, lighthouse-core/fraggle-rock/config/validation.js, lighthouse-core/fraggle-rock/gather/base-gatherer.js, lighthouse-core/fraggle-rock/gather/navigation-runner.js, lighthouse-core/fraggle-rock/gather/runner-helpers.js, lighthouse-core/gather/driver.js, lighthouse-core/gather/gatherers/trace-compat.js, lighthouse-core/gather/gatherers/trace.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js, lighthouse-core/test/fraggle-rock/config/config-test.js, lighthouse-core/test/fraggle-rock/config/validation-test.js, lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js, lighthouse-core/test/gather/driver-test.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt, types/artifacts.d.ts, types/gatherer.d.ts
**Summary**
The primary goal of this PR is to add the trace gatherer and support performance metrics in Fraggle Rock navigation mode (as well as pave the way for upgrades to support timespan metrics). That change is pretty small, but this triggered a number of other changes.
- Add new `beforeNavigation`/`afterNavigation` methods to distinguish this new category of "navigation-only" gatherers.
- Adjust config validation rules to disallow navigation gatherers from depending on snapshot artifacts.
- Refactor navigation runner to reduce duplication in collection of artifacts of each phase (there are now 5 instead of just 3)
- Refactor default trace categories list to new gatherer, import from legacy driver.
- Add more test coverage for these refactored areas.
**Primary Point of Discussion** …
=> core(fr): add navigation phase + trace gatherer

lighthouse-cli/test/fixtures/byte-efficiency/tester.html, lighthouse-core/audits/unsized-images.js, lighthouse-core/test/audits/unsized-images-test.js
**Summary**
Fixes a rather long-standing incompat with next.js method of image placeholders. See #11631, #12116 for details.
fixes https://github.com/GoogleChrome/lighthouse/issues/11631
ref #12116
=> core(unsized-images): ignore non-network SVGs

lighthouse-core/audits/uses-rel-preload.js, lighthouse-core/lib/network-request.js, lighthouse-core/test/audits/uses-rel-preload-test.js
**Summary**
At some point there was a Chromium change where used preload requests now appear as duplicate requests but with one of the `from*Cache` flags set. This updates Lighthouse logic to be inline with that new pattern.
fixes https://github.com/GoogleChrome/lighthouse/issues/11933
=> core(preload): do not warn for cache loads

lighthouse-core/config/lr-mobile-config.js
Root cause was [this PR](https://github.com/GoogleChrome/lighthouse/pull/11777) combined with this [TS bug](https://github.com/microsoft/TypeScript/issues/42893).
fixes #12113
=> clients(lr): should skip uses-http2 audit for mobile

docs/throttling.md
the link from devtools actually was relinked assuming we rename the docs. (to be correct)
so this part is easy.
=> docs(throttling): retitle devtools panel h2

docs/throttling.md
**Summary**
Fixed typo in documentation
https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md#devtools-lighthouse-panel-throttling
=> docs: fixed typo in documentation throttling.md

lighthouse-core/audits/accessibility/axe-audit.js, lighthouse-core/gather/gatherers/accessibility.js, lighthouse-core/test/audits/accessibility/axe-audit-test.js, lighthouse-core/test/gather/gatherers/accessibility-test.js, lighthouse-core/test/results/artifacts/artifacts.json
with the recent talk about the `accessibility` gatherer, I thought I would bring out this change which I had in another branch but is probably worth it on its own. This gatherer was written in ancient times so does some odd things, and it returns a bunch more stuff than [we have in `artifacts.d.ts`](https://github.com/GoogleChrome/lighthouse/blob/86a5f08a2d2ab08d40e3243ac32b68f39d77bfac/types/artifacts.d.ts#L159-L182), which means it's not usable by audits and so is wasted. `axe-core` also ships with types now, so we should use them :)
The goal is that it should be easier to follow and clearer where every part of the artifact comes from. No smoke test changes.
Can update after #12075 lands.
=> misc: reorganize accessibility gatherer

lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
fixes #12160
There's a better fix that could be had here, but in the interest of time this change maintains the status quo by picking a different gatherer that does throw an error in the test run. Also adds a comment for the next person debugging a problem here.
=> tests(fr): update test artifact

lighthouse-core/audits/errors-in-console.js, lighthouse-core/test/audits/errors-in-console-test.js
fixes #10198
#11901 did the real fix, but didn't notice that #9480 had defined the previously empty `defaultOptions` as a static method and not a getter.
Classic case of unit vs integration tests:
- The [upcoming work on overrides and getters/setters](https://github.com/microsoft/TypeScript/issues/42762) might catch this sort of thing in tsc in the future, but I'm not sure
- One way we could tackle this is exposing a way of "properly" running an audit with all the setup and teardown that `audit-runner` does and using that for all unit tests instead of calling `.audit()` directly. That would take care of context being initialized correctly and it would do the `AuditProduct` -> `AuditResult` transformation so tests could run on the real audit output expected in the LHR.
=> core(errors-in-console): properly define default options

build/build-bundle.js, lighthouse-core/gather/gatherers/accessibility.js, lighthouse-core/lib/proto-preprocessor.js, lighthouse-core/scripts/i18n/collect-strings.js, lighthouse-core/test/results/artifacts/artifacts.json, lighthouse-core/test/results/sample_v2.json, package.json, yarn.lock
minor bump in two deps
- Only minor change from the typescript version bump is that we get to remove three `// @ts-expect-error`s because of improved commonjs handling (https://github.com/microsoft/TypeScript/pull/42655). Otherwise we'll now get the advantage of a few new stricter checks and improved usage of type aliases (see the [TypeScript 4.2 announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/)).
- axe-core update is basically transparent. I re-ran `update:sample-artifacts Accessibility` and after reverting the blob URLs (which randomize on every run) the only change was the version number, so that's great :)
=> deps: update typescript and axe-core to latest

lighthouse-core/test/chromium-web-tests/download-blink-tools.sh, lighthouse-core/test/chromium-web-tests/roll-devtools.sh, lighthouse-core/test/chromium-web-tests/web-test-server.sh, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
=> tests(devtools): fix webserver

third-party/download-content-shell/download-content-shell.js, third-party/download-content-shell/utils.js
Use the github API to fetch the latest commit message from the Chromium mirror.
There's not really any way to get commit info from a remote git repo without cloning, and the Github API seems more likely to be stable long-term than any feed on `googlesource.com`.
We may have to update the branch name to `main` in the github API url when the `chromium/src` migration occurs: https://groups.google.com/a/chromium.org/g/infra-announce/c/-uMWoep7RNA
=> tests(devtools): dynamically fetch chromium version

lighthouse-core/audits/byte-efficiency/unused-javascript.js, lighthouse-treemap/app/index.html, lighthouse-treemap/app/src/main.js, lighthouse-treemap/app/styles/treemap.css, types/treemap.d.ts
ref #11254
https://lighthouse-1gxbe1yl8-googlechrome.vercel.app/gh-pages/treemap/?debug
This adds a "view modes" data structure, which defines how to interpret the data when walking `currentTreemapRoot`. `unused-bytes` is the first view mode, which highlights nodes with especially large amounts of unused bytes, and partitions the treemap based on percentage of total unused bytes on the page.
This only shows unused bytes based on javascript coverage, but there's no reason in the future that we couldn't determine unused bytes of images, css, etc. and plug them into this view mode.
=> misc(treemap): unused-bytes view mode

lighthouse-cli/cli-flags.js, lighthouse-cli/test/cli/cli-flags-test.js
fixes #12246
Unlike [anything that looks like a number](https://github.com/yargs/yargs/blob/b9d6ba32bcce90a24aae38e2cce0e6dc73f44e1b/docs/tricks.md#numbers), things that look like a boolean aren't automatically parsed as one unless set specifically. Setting the `type` on nested properties is [still kind of janky](https://github.com/GoogleChrome/lighthouse/pull/11794/files#r539635508) in yargs, so it's easier to handle in the `coerce` callback.
Also
- adds tests for parsing of all the `screenEmulation` properties
- adds a new option in `cli-flags` so that failure conditions can be tested without yargs logging the errors and calling `process.exit()`. We should have more CLI flag parsing tests, and this should help make that easier.
=> cli: correctly parse screenEmulation boolean flags

lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js
Quick bypass that should unblock https://github.com/GoogleChrome/lighthouse/pull/12255 and the release process.
=> tests(smoke): ignore lantern script attribution in ToT

lighthouse-core/scripts/legacy-javascript/run.js, lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
These test results were changing whenever core-js released a new version. This was overlooked because we don't use yarn.lock to pin these version, but instead manually install the package (since we switch between core-js 2 and 3). Instead, specify what version to install in `run.js`.
I noticed this here: https://github.com/GoogleChrome/lighthouse/pull/12199/checks?check_run_id=2134061233
=> tests(legacy-javascript): pin to specific versions of core-js

lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js
Patch recently landed: https://crrev.com/c/2773125
ToT should be fixed.
Closes https://github.com/GoogleChrome/lighthouse/issues/12262
=> tests(smoke): remove max chrome for lantern script attribution

lighthouse-core/lib/sentry.js
tags are cool, they show up like this in Sentry for a given fingerprinted-error: 
protocolMethod shows up in individual error reports but since it isn't a tag we can't do aggregate analysis.
helps with #6512
=> misc(sentry): tag protocol method

lighthouse-core/audits/seo/hreflang.js
=> core(hreflang): use Audit.makeNodeItem

types/gatherer.d.ts
fix for the problem in https://github.com/GoogleChrome/lighthouse/pull/12274#discussion_r597988531 We could also merge into #12274 instead of master if that's better for anyone.
The problem wasn't detected because the elements of `MetaElements` have all optional properties, so in theory could match any object (like a `DetectedStack`) so long as there weren't any conflicting types (e.g. if somehow there was `content?: string` in `MetaElement` but `content: number` in `DetectedStack`), which there aren't.
Typescript throws in one additional check for protection against accidental cases like this by ensuring that the source and target types have to [have at least one property in common](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#weak-type-detection) when …
=> misc: fix PhaseArtifact type to include Stacks

lighthouse-core/report/html/renderer/element-screenshot-renderer.js, lighthouse-core/report/html/renderer/psi.js, lighthouse-core/report/html/renderer/report-ui-features.js, lighthouse-core/test/report/html/renderer/psi-test.js
Introduces a new `installFeatures` return in `psi.js`, which takes care of installing element screenshots in PSI.
=> clients(psi): support element screenshots

.github/workflows/devtools.yml, third-party/chromium-webtests/README.md, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-block-url.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-clear-data-warning.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-flags-run.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-i18n-run.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-limited-run.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-prevent-run.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run.js
`loadModule` => `loadTestModule`
=> tests(devtools): sync tests

lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
work around #12311 in the smoke tests to fix CI.
Chrome 89 is stable now and `warn-not-offline-capable` may be removed from Chrome 90 in addition to Chrome 91 where it's already removed, so there didn't seem to be any point in gating this behind a `_minChromiumMilestone`.
Leaving the actual `installable-manifest` audit unchanged for now, since if the offline check is turned back on we should get automatically notified when this smoke test fails again :)
=> tests(smoke): temporarily disable offline-warning check

lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js, lighthouse-core/report/html/renderer/dom.js, lighthouse-treemap/app/src/util.js, types/externs.d.ts
fixes #12011
To recap: we need gatherers to deal with svg elements where they overlap in tag names with HTML elements (at least `<a>`, `<script>`, `<style>`, and `<title>`) since real pages contain those elements and those svg elements have different attributes and behavior than their HTML counterparts (causing bugs like #6481). This PR makes `querySelector` include those svg elements by default instead of only including them if no matching HTML element was found.
So now `document.querySelector('a')` returns a value of type `HTMLAnchorElement | SVGAElement` instead of just `HTMLAnchorElement`, and the subsequent code has to identify which of the two it's dealing with before proceeding.
_However_, we also use `querySelector` a lot in the report (usually via `dom.find()`), and it's annoying …
=> misc: include SVG elements by default in typed querySelector

lighthouse-core/gather/driver.js, lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js, lighthouse-core/gather/gatherers/seo/robots-txt.js, lighthouse-core/lib/file-namer.js, lighthouse-core/lib/page-functions.js, lighthouse-core/lib/url-shim.js, lighthouse-core/report/html/renderer/details-renderer.js, lighthouse-core/report/html/renderer/dom.js, lighthouse-core/report/html/renderer/i18n.js, lighthouse-core/report/html/renderer/util.js, lighthouse-core/scripts/generate-bundlephobia-database.js, lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js, lighthouse-core/test/gather/gatherers/dobetterweb/response-compression-test.js, lighthouse-core/test/report/html/renderer/util-test.js, package.json, yarn.lock
Gets rid of the
> `@typescript-eslint/parser@4.16.1" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".`
warning on every `yarn`. It's been working correctly in spite of the peer dep requirement, but our `eslint@^4.19.1` is three years old, the upgrade was pretty painless, and the minor changes needed were reasonable.
=> deps: update eslint to latest

lighthouse-core/report/html/renderer/performance-category-renderer.js, lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
issue for discussion and PR at once: with #11732 tying metrics and opportunities and diagnostics closer together, there are probably more in-depth changes to be made, but it makes sense to at least move budget info after diagnostics in the report.
=> report: move budgets after diagnostics

lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
CLS weighted scores were erroneous and should be fixed in ToT:
https://chromium.googlesource.com/chromium/src/+/042fbfb4cc6a675da0dff4bf3fc08622af42422b
=> tests(smoke): update CLS-AF expectation

lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js, lighthouse-core/lib/asset-saver.js, lighthouse-core/test/lib/asset-saver-test.js, package.json, yarn.lock
It's very nice that the trace that comes out of `-GA` is saved with a trace event per line. Doing some recent work with devtoolsLogs made me really want the same printing style for those.
=> cli(asset-saver): print one devtoolsLog event per line

lighthouse-core/audits/deprecations.js
Temporary fix for #12089 
see also [report: use ::marker by connorjclark · #12267](https://github.com/GoogleChrome/lighthouse/pull/12267)
=> core(deprecations): ignore warning for ::-webkit-details-marker

lighthouse-core/scripts/roll-to-devtools.sh
`front_end/shell.js` doesn't exist anymore.
=> misc: fix path check for roll devtools script

.github/workflows/ci.yml, lighthouse-cli/test/cli/run-test.js
In the spirit of improving flaky tests, `unit-cli` has loooong had a flake based on a Chrome launch sometimes timing out. You know the one:
```
●  process.exit called with "1"
84 | function printConnectionErrorAndExit() {
85 |   console.error('Unable to connect to Chrome');
> 86 |   return process.exit(_RUNTIME_ERROR_CODE);
|                  ^
87 | }
88 | 
89 | /** @return {never} */
at printConnectionErrorAndExit (lighthouse-cli/run.js:86:18)
```
(for example: https://github.com/GoogleChrome/lighthouse/runs/2249363555?check_suite_focus=true)
The issue is that this is more or less a smoke test without any of the functionality we've built into smokehouse to handle dealing with launching and testing with Chrome in a CI environment.
Looking way back, the original point of the test (from …
=> tests: remove flaky Chrome launch from unit-cli

readme.md
Add [Alertdesk](https://www.alertdesk.com/) to the list of integrations in alphabetical order.
Alertdesk is a quality & performance monitoring tool based on Lighthouse.  Run daily quality & performance tests from both Mobile and Desktop and dive into the powerful & intuitive reports.
=> docs(readme): add Alertdesk to the list of integrations

lighthouse-core/fraggle-rock/config/filters.js, lighthouse-core/test/fraggle-rock/config/filters-test.js
**Summary**
Improves the filtering of categories in Fraggle Rock to remove categories that consist only manual audits. This eliminates the UX oddity that you'd run timespan mode and get a `?` score for accessibility category because all its *real* audits were snapshot audits.
ref #11313
=> core(fr): filter out manual-only categories

lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/gather/gatherers/full-page-screenshot.js, lighthouse-core/lib/emulation.js, lighthouse-core/test/gather/fake-driver.js, lighthouse-core/test/gather/gather-runner-test.js, lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js, lighthouse-core/test/test-utils.js
**Summary**
Broken out of #12366, just the emulation shared pieces. We already basically had this split in `lib/emulation.js` so it was just moving the last two methods that put it together :)
ref #11313 #12366
=> core(fr): prepare emulation utilities for shared use

lighthouse-treemap/app/index.html, lighthouse-treemap/app/src/main.js, lighthouse-treemap/app/src/util.js, lighthouse-treemap/app/styles/treemap.css, lighthouse-treemap/types/treemap.d.ts, types/treemap.d.ts
=> misc(treemap): root node selector

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js, lighthouse-core/audits/image-size-responsive.js, lighthouse-core/test/audits/image-size-responsive-test.js, lighthouse-core/test/results/sample_v2.json
**Summary**
Minor change to the responsive images audit (see https://github.com/GoogleChrome/lighthouse/issues/11838).
fixes https://github.com/GoogleChrome/lighthouse/issues/11838
=> core(responsive-images): ignore images larger than viewport

lighthouse-core/fraggle-rock/gather/driver.js, lighthouse-core/gather/driver.js, lighthouse-core/gather/fetcher.js, lighthouse-core/test/fraggle-rock/gather/driver-test.js, lighthouse-core/test/gather/fetcher-test.js, types/gatherer.d.ts
To make the robots.txt gatherer compatible with CSPs we should use the new fetcher. This PR makes fetcher available to FR gatherers.
Related
https://github.com/GoogleChrome/lighthouse/issues/10225
=> core(fr): add fetcher to transitional driver

lighthouse-core/test/chromium-web-tests/README.md
**Summary**
I ran into `ImportError: No module named requests` when trying to run the devtools tests recently
=> docs: add python requests install to webtests

lighthouse-logger/package.json, lighthouse-logger/yarn.lock, yarn.lock
fixes #12439 (but really just for contributors)
See https://github.com/nolanlawson/marky/issues/18 for the issue in node 16 (introduced in https://github.com/nodejs/node/pull/37970).
However as noted by @patrickhulce in https://github.com/GoogleChrome/lighthouse-ci/issues/596#issuecomment-832006808, `lighthouse-logger` currently uses `marky@^1.2.0`, so any downstream project just needs to refresh their deps and they'll pick up 1.2.2.
However, contributors (with a git repo checkout) _are_ subject to our `yarn.lock` files for dependencies, so we do need to update those for us.
=> deps: update marky to latest

lighthouse-core/fraggle-rock/config/default-config.js, lighthouse-core/gather/gatherers/trace-elements.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js, lighthouse-core/test/gather/gatherers/trace-elements-test.js, types/artifacts.d.ts
Adds support for `TraceElements` gatherer in FR.
Ref #11313
=> core(fr): convert trace-elements gatherer

.npmignore, lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js, lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js, lighthouse-cli/test/smokehouse/readme.md, lighthouse-cli/test/smokehouse/report-assert.js, lighthouse-cli/test/smokehouse/smokehouse.js, lighthouse-core/scripts/release/test.sh, package.json, types/smokehouse.d.ts, yarn.lock
follow up to #12415 and #12325
Relatively unimportant improvement given the lack of users of this, but makes the experience of running smoke tests for downstream projects (publisher-ads only?) a lot better. This lets us do our release testing of a pristine packed lighthouse more cleanly too, though (which also acts as a test that we're not breaking testing for downstream projects...).
The changes end up a little tangled to accomplish this, but starting at the entry point:
- expose a `smokehouse` bin script so downstream doesn't have to [reach in to find it](https://github.com/googleads/publisher-ads-lighthouse-plugin/blob/2df6b33bcecda4ef5f4948be3d906511c29ca0ae/lighthouse-plugin-publisher-ads/test/smoke/run-smoke.js#L50). Packages with `lighthouse` as a dep can run it with `yarn …
=> tests: add smokehouse to bin for downstream use

lighthouse-treemap/app/debug.json, lighthouse-treemap/app/src/main.js, lighthouse-treemap/app/src/util.js, lighthouse-treemap/test/util-test.js, types/treemap.d.ts
1) Changed the `stableHasher` function to recycle items, so that colors never run out.
2) I had added a fake jquery duplication to debug.json, but it turns out that there were visible duplicates but they were given `white` because of 1). So I removed the fake duplication.
3) Refactored ViewMode.highlight. I figured this property should be responsible for declaring what color a specific node should be.
ref #11254
=> misc(treemap): fix colors

lighthouse-cli/bin.js
**Summary**
Refactoring
Refactored to destructuring to make it look better
N/A
=> misc(cli): destructure args in import

lighthouse-core/audits/predictive-perf.js, lighthouse-core/report/html/renderer/i18n.js, lighthouse-core/test/audits/predictive-perf-test.js
Due to the kind of weird legacy of the renderer's `i18n.js` (coming from a `util` shared between the report and core), `predictive-perf` ended up using the renderer `i18n` class to do a simple milliseconds format rather than using the i18n pipeline (albeit for a string that no human will see or probably ever needs).
Now, whether or not `predictive-perf` _needs_ a properly localized and formatted milliseconds (instead of just doing rounding and adding `ms` itself locally) is another question, but this is basically free, so I don't think it matters. Either way it allows the renderer `i18n` to not have optional `strings`, which was my original goal with the change, so happy to change if someone feels strongly :)
=> misc: move predictive-perf off renderer i18n

lighthouse-treemap/app/index.html
Just tracking page views for now.
ref #11254
=> misc(treemap): add GA snippet for new property

lighthouse-core/test/audits/installable-manifest-test.js, lighthouse-core/test/audits/is-on-https-test.js, lighthouse-core/test/index-test.js, lighthouse-core/test/runner-test.js, lighthouse-core/test/test-utils.js
Adds an assertion to `expect.toBeDisplayString` that the passed-in value is an `LH.IcuMessage` and not a matching string.
Originally `expect.toBeDisplayString` was intended to support either `string` or `LH.IcuMessage` since most of the localized LHR properties [end up being a union of the two](https://github.com/GoogleChrome/lighthouse/blob/d236a70daf476f2ffa09b30853cb60b3caac79e0/types/audit.d.ts#L72-L88). However, since then, it's clear that our tests always know if a tested property is going to be localizable or not so it's better to be specific. Doing it this way also avoids the potential to assert that a value is a certain string once localized, but miss the fact that it's just the english string that won't be localized (luckily we don't appear to have that problem anywhere).
Also …
=> tests(i18n): only accept IcuMessages in toBeDisplayString

lighthouse-treemap/app/src/main.js, types/treemap.d.ts
=> misc(treemap): highlight treemap node on mouse hover table row

lighthouse-treemap/app/src/main.js, lighthouse-treemap/types/treemap.d.ts
as suggested by brendan
(keypress doesn't catch Escape, but keyup does.)
ref #11254
=> misc(treemap): esc to zoom out

lighthouse-core/fraggle-rock/config/default-config.js, lighthouse-core/fraggle-rock/gather/navigation-runner.js, lighthouse-core/fraggle-rock/gather/runner-helpers.js, lighthouse-core/fraggle-rock/gather/snapshot-runner.js, lighthouse-core/fraggle-rock/gather/timespan-runner.js, lighthouse-core/test/fraggle-rock/gather/mock-driver.js, lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js, lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js, lighthouse-core/test/network-records-to-devtools-log.js, types/artifacts.d.ts, types/externs.d.ts
**Summary**
~~Won't work until #12469 is merged, but~~ this brings fraggle rock up to snuff with gather runner and makes use of all the refactoring over the past month! 🎉 
ref #11313
=> core(fr): align navigation-runner with legacy gather-runner

package.json, yarn.lock
part of #11866. See the [`chrome-launcher` changelog](https://github.com/GoogleChrome/chrome-launcher/releases/tag/v0.14.0) for details.
small victory: retires `mkdirp` and `rimraf` from our prod dependencies 🎉
=> deps: update chrome-launcher to latest

lighthouse-core/report/html/templates.html, lighthouse-viewer/app/src/viewer-ui-features.js, lighthouse-viewer/app/styles/viewer.css
Forgot to update this tool icon in #12392
=> report(viewer): fix gist icon

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap, lighthouse-core/audits/csp-xss.js, lighthouse-core/config/default-config.js, lighthouse-core/config/experimental-config.js, lighthouse-core/lib/i18n/locales/en-US.json, lighthouse-core/lib/i18n/locales/en-XL.json, lighthouse-core/test/results/sample_v2.json, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Updated learn more link to: https://web.dev/strict-csp/
CSP is already enforced on web.dev. Should hold on merging this until [cl/371125171](https://critique-ng.corp.google.com/cl/371125171) lands.
=> core(csp-xss): move to default config

lighthouse-core/audits/metrics/first-contentful-paint-3g.js, lighthouse-core/audits/metrics/first-contentful-paint.js, lighthouse-core/test/audits/metrics/first-contentful-paint-3g-test.js, lighthouse-core/test/audits/metrics/first-contentful-paint-test.js, lighthouse-core/test/report/report-generator-test.js, lighthouse-core/test/results/sample_v2.json
Part of #11866
Updates the FCP score-curve control points to match the latest Lighthouse performance data and to align with other web performance tools.
Our FCP control points were last updated more than three years ago. It's not clear why FCP in HTTP Archive has trended lower over the time since (maybe changes in the sampled URLs?), but they clearly don't match the thresholds we would pick today.
Other tools are also trying to align on a set of FCP thresholds. At one point 1000ms/3000ms was recommended for FCP good/average thresholds (I believe that's what CrUX uses today), but more recent analysis has found the 1000ms to be difficult to be widely achievable, and so the current recommendation for tooling is 1800ms/3000ms.
While in some cases a more easily achievable threshold might be …
=> core: update FCP score curve

lighthouse-core/lib/network-recorder.js
I noticed in DevTools that no source map contents were being used: so no subRows in unused-javascript with module-level coverage, and no bundle in script-treemap-data.
JSBundles had errored `sizes` because `scriptElement.content` was null:
This property is set for external scripts in a post-processing step in ScriptElements:
In DevTools, the OOPIF check filtered out all records because `sessionId` is set even for the main protocol connection. This is due to a complication introduced while adding multi-client support. See https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2607769 for more. I failed to followup on that, and we have no tests touching OOPIF checks in devtools tests, so it went unnoticed.
This PR is a possible workaround/bandaid. I manually verified with …
=> core: fix main session OOPIF checks for devtools

lighthouse-core/report/html/renderer/performance-category-renderer.js, lighthouse-core/report/html/report-styles.css
fixes #12501
I did the same thing as here: https://github.com/GoogleChrome/lighthouse/pull/12495
=> report: make metric filter tab accessible

lighthouse-core/gather/driver/wait-for-condition.js
**Summary**
Buffered flag only works when you use [`type` not, `entryTypes`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/observe). It's not really a regression when we turned it on, because we just fell back to the same behavior as before we added it a few weeks ago, but this will make the fix actually work :) (we never *really* needed buffered either, mostly an extra boost of wait condition correctness in ultrarare cases where entries weren't emitted fast enough)
fixes https://github.com/GoogleChrome/lighthouse/issues/12544
=> core(navigate): only observe longtasks in PerfObserver

lighthouse-core/fraggle-rock/gather/runner-helpers.js, types/gatherer.d.ts
Incorrect behavior when defining multiple dependencies in `FRTransitionalContext`. This was caused by [distributed conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types).
=> core(fr): fix usage of distributed conditional type

lighthouse-core/audits/script-treemap-data.js, lighthouse-core/test/audits/__snapshots__/script-treemap-data-test.js.snap, lighthouse-core/test/audits/script-treemap-data-test.js, lighthouse-treemap/app/debug.json, lighthouse-treemap/app/src/main.js
While testing the treemap button in PSI, I noticed errors b/c of how we drop empty string values in the LHR.
1) `script-treemap-data` wraps the nodes for a bundle in two layers: top is the script src node, second is the sourceRoot node. But sourceRoot can be an empty string/not there, so this resulted in nodes where name was `''`. There's an extra complication w/ the `collapse` functionality, but it isn't relevant to the issue so I won't describe it in detail.
2) I also suspect that sources like `root//b.js` exist and will make annoying extra layers of nodes named `/` or (b/c collapsing) `/b.js`. so I do an extra check in the `.split` forEach to prevent that.
3) Just to be safe, I made the `makeCaption` function not totally kill everything when name is missing.
=> core(script-treemap-data): do not create nodes with blank names

lighthouse-core/report/html/renderer/psi.js, lighthouse-core/report/html/renderer/report-ui-features.js, lighthouse-core/test/report/html/renderer/psi-test.js
=> clients(psi): render treemap button

.github/workflows/devtools.yml, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-flags-run.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run.js
ref https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2902746
=> tests(devtools): sync webtests

lighthouse-core/audits/metrics/total-blocking-time.js, lighthouse-core/test/audits/metrics/total-blocking-time-test.js, lighthouse-core/test/report/report-generator-test.js, lighthouse-core/test/results/sample_v2.json
Part of #11866
Updates the Total Blocking Time control points to be closer to the intended methodology laid out in https://web.dev/performance-scoring/#metric-scores  
In addition, if we were picking entirely new control points, the May 2021 HTTP Archive run gives
HA p08 - 19ms 
HA p25 - 189ms
But we think these as our control points would be too jarring and aggressive for now. Still, there's room to improve, so we're doing a small shift of TBT being scored more strictly.
p10: 200
median: 600
Desktop remains unchanged.
=> core(scoring): update TBT score curve

package.json, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt, yarn.lock
get the [plugin updates](https://github.com/googleads/publisher-ads-lighthouse-plugin/releases) since the last bump in november into 8.0
=> deps: update lighthouse-plugin-publisher-ads to latest

changelog.md, docs/v8-perf-faq.md
see #11866
to merge into #12593
=> docs: in-progress changelog for v8.0

lighthouse-treemap/app/src/main.js, lighthouse-treemap/app/styles/treemap.css
We added this in #12486 but turns out the logic was inverted.
ref #11254
=> misc(treemap): fix node coverage shading

lighthouse-treemap/app/src/main.js, lighthouse-treemap/app/src/util.js
The depth one script nodes have really long names because they are the entire URL of the network resource. We should elide if they share the same origin as the requested URL.
I did this in the Treemap UI instead of `script-treemap-data` because I thought it'd be nice to preserve the property that the names in the LHR are valid URLs.
Also added an `(inline)` tag to make the inline JS node apparent.
https://lighthouse-git-tm-url-elide-googlechrome.vercel.app/gh-pages/treemap/?debug
https://lighthouse-git-tm-url-elide-googlechrome.vercel.app/gh-pages/treemap/?gist=682f30fc539d16905557e8ce092adecf
ref #11254
=> misc(treemap): elide origin from url if same as requestedUrl

lighthouse-cli/test/fixtures/csp.html, lighthouse-cli/test/smokehouse/test-definitions/csp/csp-expectations.js
We were getting failures in g3 because of the port number, which we dynamically change.
=> tests(smoke): relative source map hash

lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
=> tests: fix flaky cache test

lighthouse-treemap/test/treemap-test-pptr.js
followup from https://github.com/GoogleChrome/lighthouse/pull/12603#issuecomment-853288185
i wrote the code that was wrong, so here's my penance.
---
driveby change of port number... no reason it needs to conflict w/ 10200 and i'm always happy to avoid stopping my servers.
=> tests(treemap): add test for node coverage shading

lighthouse-core/fraggle-rock/config/config.js, lighthouse-core/fraggle-rock/config/filters.js, lighthouse-core/fraggle-rock/config/validation.js, lighthouse-core/fraggle-rock/gather/runner-helpers.js, lighthouse-core/test/fraggle-rock/gather/mock-driver.js, lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js, lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js, types/config.d.ts, types/gatherer.d.ts
**Summary**
Fixes the issue raised in https://github.com/GoogleChrome/lighthouse/issues/12619
The type violations were in fact valid and stemmed from my abuse of `Interface<AllPossibleKeys>` to be a substitute for `Interface<Key1> | Interface<Key2> | Interface<Key3>`. I introduced `AnyInterface` types to more accurately reflect when a function accepts or returns *any possible* artifact/gatherer/dependency object instead. This still has the limitation that it doesn't programmatically generate the combinatorial versions, but I haven't bumped into a scenario where the handling differs/matters yet. 
Solves @adamraine 's original point (see screenshot)
fixes https://github.com/GoogleChrome/lighthouse/issues/12619
ref #11313
=> core(fr): more precise AnyFRInterface types

package.json, yarn.lock
connor noticed that when you do arrow-left focus will shift to the parent's caption. definitely wrong and bad. 
fixed here https://github.com/paulirish/webtreemap-cdt/commit/994c901350cf27bb5485489c05cfc469d89ed15d
=> deps(webtreemap): bump to fix focus traversal bug

lighthouse-core/gather/driver/prepare.js, lighthouse-core/gather/fetcher.js, lighthouse-core/lib/emulation.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js, lighthouse-core/test/gather/fetcher-test.js, lighthouse-core/test/lib/emulation-test.js
Fixes https://github.com/GoogleChrome/lighthouse/issues/12631
=> core(fr): fix main-document-content

package.json, yarn.lock
**Summary**
This is an initial "let's go for it" attempt to upgrade `ws` to see what breaks.
Resolves #12637
=> deps: update `ws` to latest

lighthouse-core/test/report/html/renderer/details-renderer-test.js
<details>
<summary>screenshot of the annoying thing we see so frequently when running lh core tests</summary>
</details>
the diff looks odd, but its just putting these tests in a new describe() block with before/afterEach. the tests are untouched, save for indentation.
=> tests(renderer): reduce console output about unknown types

lighthouse-cli/test/smokehouse/test-definitions/csp/csp-expectations.js, lighthouse-core/gather/gatherers/seo/tap-targets.js
Fixes https://github.com/GoogleChrome/lighthouse/issues/11862
Adding the rule using the protocol will create a stylesheet that is not blocked by the CSP.
=> core(tap-targets): add stylesheet over protocol

lighthouse-core/fraggle-rock/config/filters.js, lighthouse-core/test/fraggle-rock/config/filters-test.js, types/audit.d.ts
Implementation of our ideas in https://github.com/GoogleChrome/lighthouse/pull/12595#discussion_r645172157
This feels good to me, but I would be receptive to making `applicableModes` required for two reasons:
- It's more explicit about when the audit will be run.
- It would be helpful to throw an error if the available artifacts don't meet our expectations, instead of silently skipping any audits that have a missing artifact.
=> core(fr): add audit mode filter

lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/test/audits/byte-efficiency/total-byte-weight-test.js, lighthouse-core/test/network-records-to-devtools-log.js
**Summary**
Removes the total byte weight policy that ignored partially downloaded resources (like videos). IMO, this dramatically understates the weight of a page in some cases (see #12664).
The check was added [way back in 2017](https://github.com/GoogleChrome/lighthouse/pull/2023#discussion_r114909191) _by me_ as part of __adding visibility into inflight records__ 🤯 . This was also before we used our own network request class that initializes transferSize that prevents the `undefined` concern that prompted the original.
Nonetheless, I added a test to ensure spirit of the condition is still handled.
closes #12664
=> core(total-byte-weight): count partially finished requests

lighthouse-core/scripts/pptr-run-devtools.js
prevents script from ending early if a LH run errors out in CDT.
=> misc(scripts): error handling for pptr-run-devtools.js

lighthouse-core/gather/gatherers/viewport-dimensions.js, lighthouse-core/test/config/config-test.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js
[Opportunity conversion doc](https://docs.google.com/document/d/1z6Cm4jJmN-1i5S2ryfC1hLPyo46NlW6X8QMXRDqq1_Y/edit?resourcekey=0-r0zHmcvw4Y2Wg4DI96d4KA#)
This is some pretty low-hanging fruit. We are just getting viewport dimensions from the end of the timespan.
Only issue would be if viewport changes during the timespan, but such an event could also affect the dimensions in navigation mode. We could surface a warning if the viewport changes.
=> core(fr): add timespan support to viewport-dimensions

lighthouse-core/lib/network-request.js, lighthouse-core/test/lib/network-request-test.js
**Summary**
Often the HTTPS audit fails because the original URL audited was `http`, so even if it redirects then you still have the original redirect request over HTTP. We can kinda explain why this is desirable (though I'm not really sold it's worth the annoyance), but it's definitely not the case in HSTS internal redirects that happen in the browser, which is the whole point of HSTS. This applies to entire TLDs in some cases (`.app`/`.dev`), so we should handle those cases appropriately.
fixes https://github.com/GoogleChrome/lighthouse/issues/12674
=> core(network-request): consider HSTS redirects secure

lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
This upstreams a change created by the JS web build team.  🔒  http://cl/379821904 THANK YOU to Elena and Jan! 😻
As noted by them:
> **For the `document` resource**: the new transfer size is just outside current bounds of `'2200±100'`
> The transfer size differences appear to be caused by header changes (where with the node14 upgrade, there is an additional header, `Keep-Alive: timeout=5`).
=> tests: tweak variability assertion for load-things transferSize

package.json, yarn.lock
**Summary**
Bumps axe-core to 4.2.3. to fix common fatal bug (see changelog [4.2.2](https://github.com/dequelabs/axe-core/pull/2976/commits) [4.2.3](https://github.com/dequelabs/axe-core/releases/tag/v4.2.3)). No new rules, just bug fixes, so shouldn't interfere with the other ongoing a11y audit work in #12536 #12699 #12700
closes #12705
=> deps(axe-core): upgrade to 4.2.3

lighthouse-core/test/config/config-helpers-test.js, lighthouse-core/test/config/config-test.js, lighthouse-core/test/lib/i18n/i18n-test.js, lighthouse-core/test/lib/i18n/swap-locale-test.js, lighthouse-core/test/test-utils.js, report/test/renderer/i18n-test.js
the node 12 compat checks added to unit tests in #12426 don't work if your Node 12 also happened to be built with `full-icu`, as @victorporof's seems to have been :)
This adds an explicit check for better-than-small ICU support to the existing node 12 checks. As before, we can remove all this when we move to a Node 14 minimum.
=> tests: add explicit small-icu detection for i18n

.npmignore
going through our npm packed files, a few more large ones jumped out that aren't needed for a production run (basically all the files >100KiB that aren't a locale file):
- one of the recipes under `docs/`
- prebuilt json schemas under `sd-validation/`
- our 360KiB (and growing) changelog
npmignoring these saves about 1MiB in our installed package size (package size: 2.5 MB -> 2.2 MB, unpacked size: 12.6 MB -> 11.6 MB).
I never go into an installed package to get docs about that package (I go to `npm` or direct to the repo), but if that is a use case worth preserving we could ignore just `docs/recipes/` and keep the changelog and still get like half of the savings.
=> misc: npmignore larger unnecessary files

lighthouse-core/audits/accessibility/aria-command-name.js, lighthouse-core/audits/accessibility/aria-meter-name.js, lighthouse-core/audits/accessibility/aria-tooltip-name.js, lighthouse-core/audits/accessibility/aria-treeitem-name.js, lighthouse-core/scripts/i18n/collect-strings.js
I started looking into fatal `collect-strings` collisions after https://github.com/GoogleChrome/lighthouse/pull/12697/files#r658831618 when it became clear that that `lighthouse-core/audits/accessibility/aria-progressbar-name.js | description` has been accidentally colliding with `lighthouse-core/audits/accessibility/aria-treeitem-name.js | description` for quite some time and we (and TC) haven't noticed.
It seems like something has changed with collisions. At least from what I can understand from inspecting some of the intermediate files in the pipeline, internally those two strings got deduped into a single message for translation (they share an ID which is hashed from the `message` and `meaning`), then properly duplicated again when dumped into our LHL format. Basically exactly what …
=> i18n: allow strings with duplicate message and descriptions

lighthouse-core/gather/gatherers/trace.js
Signed-off-by: Victor Porof <victorporof@chromium.org>
=> core(config): include additional trace categories

lighthouse-core/audits/server-response-time.js, lighthouse-core/test/audits/server-response-time-test.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js
`server-response-time` already supported timespan mode, this just makes the audit N/A if the main resource is unavailable.
The additional puppeteer revealed many erroneous audits when the timespan is started after page load. Most failures come from a missing main resource, but others may require a follow-up investigation.
=> core(fr): split timespan support for server-response-time

lighthouse-core/audits/seo/canonical.js, lighthouse-core/lib/i18n/locales/en-US.json, lighthouse-core/lib/i18n/locales/en-XL.json, lighthouse-core/test/audits/seo/canonical-test.js
**Summary**
Modified explanationRelative from ```Relative URL ({url})``` to ```Is not an absolute URL ({url})```
Related Issues/PRs
Fixes #12463
Closes #12479
=> core(canonical): proper explanation for url misuse

lighthouse-core/audits/apple-touch-icon.js, lighthouse-core/audits/dobetterweb/geolocation-on-start.js, lighthouse-core/audits/dobetterweb/notification-on-start.js, lighthouse-core/audits/final-screenshot.js, lighthouse-core/audits/font-display.js, lighthouse-core/audits/installable-manifest.js, lighthouse-core/audits/maskable-icon.js, lighthouse-core/audits/metrics.js, lighthouse-core/audits/performance-budget.js, lighthouse-core/audits/screenshot-thumbnails.js, lighthouse-core/audits/seo/canonical.js, lighthouse-core/audits/seo/hreflang.js, lighthouse-core/audits/seo/http-status-code.js, lighthouse-core/audits/seo/is-crawlable.js, lighthouse-core/audits/splash-screen.js, lighthouse-core/audits/themed-omnibox.js, lighthouse-core/computed/resource-summary.js, lighthouse-core/gather/gatherers/script-elements.js, lighthouse-core/gather/gatherers/seo/tap-targets.js, lighthouse-core/gather/gatherers/trace-elements.js, lighthouse-core/test/audits/final-screenshot-test.js, lighthouse-core/test/audits/screenshot-thumbnails-test.js, lighthouse-core/test/audits/seo/http-status-code-test.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js, lighthouse-core/test/gather/gatherers/trace-elements-test.js
**Summary**
Updates several more audits to accurately reflect their supported gather modes. Most of this is restricting the supportedMode to navigation even if the artifacts are available, a few optional notApplicable states, and then minor gatherer fixes too.
The remaining ones are due to...
- `simulate` throttlingMethod still being default in timespan (tracked by #11313)
- Opportunities that haven't been converted yet but are still on the burndown.
- Network analysis failing when there are no network records at all.
ref #11313
=> core(fr): limit scope of audits to applicable modes

lighthouse-cli/test/smokehouse/smokehouse.js
**Summary**
Our tests have been very flaky on ToT lately due to more `PROTOCOL_TIMEOUT` issues. This was exacerbated by our retry logic failing because of server assertions. Basically we forgot to clear network requests in between attempts so even if it passed later, our assertion on the count of requests would fail.
We'll give this a go and see if it helps while I try to repro PROTOCOL_TIMEOUT.
ref #12773
=> tests: don't double count server network requests on retry

build/build-dt-report-resources.js, report/assets/standalone-template.html, report/clients/standalone.js
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3003137
Also move calling the standalone init function to the html file. Current devtools LH integration is evaluating the `report.js` to export things to global scope (see my pending [CL](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2939422/13/front_end/panels/lighthouse/lighthouse.ts) that changes this), so this prevents that function from running in the wrong contexts.
=> tests(devtools): fix after renaming standalone-template.html

lighthouse-core/audits/csp-xss.js, lighthouse-core/test/audits/csp-xss-test.js
Closes https://github.com/GoogleChrome/lighthouse/issues/12777https://github.com/GoogleChrome/lighthouse/issues/12777
=> core(csp-xss): make n/a with empty results

lighthouse-logger/index.js, lighthouse-logger/package.json
**Summary**
Fixes our longstanding disrespect for other packages logging ;) Prefixes all of our log messages with `LH:` so that it does not clobber the other prefixes using the same instance of `debug` (like `puppeteer`). 
Will require immediate followup with a publish and version bump in our own deps.
Note that the impact of this is more limited than it appears because we are using an ancient debug, so most modern packages get their own instance :)
ref #12805 #11313
=> misc: add prefix to lighthouse-logger debug scope

lighthouse-cli/cli-flags.js, lighthouse-cli/run.js, lighthouse-cli/test/cli/bin-test.js, lighthouse-core/fraggle-rock/config/config.js, lighthouse-core/fraggle-rock/gather/navigation-runner.js, lighthouse-core/fraggle-rock/gather/snapshot-runner.js, lighthouse-core/fraggle-rock/gather/timespan-runner.js, lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js, lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js, lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js, types/config.d.ts, types/externs.d.ts
**Summary**
- Exposes the fraggle rock navigation runner on the CLI. 
- Threads through the CLI flag settings overrides to the config.
Happy to add whatever public caveats others think is wise to minimize accidental usage at this stage (currently just `[EXPERIMENTAL]` on the CLI flag). Hopefully this gets us more internal usage, I know I'll be trying it out a bit more :) It's not at complete parity yet, but the basic default usage should be working at this point.
Next steps:
- Properly fix `lighthouse-logger` to avoid stomping on other packages debug #12806
- Reach config filtering feature parity (unlocks smoketests) #12808
- Enable existing smoketests on FR navigation
ref #11313
=> cli(fr): add --fraggle-rock flag

.github/workflows/devtools.yml, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run.js
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2939422 updated CDT LH integration, but GHA cache is holding on to old version. bumping.
EDIT: there was another change (related to tooltips) that requires syncing our tests, so no need to bump cache buster.
=> tests(devtools): sync tests, fix cache action

lighthouse-cli/run.js, package.json, yarn.lock
**Summary**
Removes the wart introduced by #12805 and bumps our use of lighthouse-logger to be prefixed with `LH:`
ref #11313 #12805
=> deps: update lighthouse-logger to 1.3.0

lighthouse-cli/test/smokehouse/frontends/back-compat-util.js, lighthouse-cli/test/smokehouse/frontends/lib.js, lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js, lighthouse-cli/test/smokehouse/lib/concurrent-mapper.js, lighthouse-cli/test/smokehouse/report-assert.js, lighthouse-cli/test/smokehouse/smokehouse.js, lighthouse-cli/test/smokehouse/test-definitions/core-tests.js, types/smokehouse.d.ts
part 1/2 of #11950. Wanted to get in these simplifications before FR started appearing in the smoke tests :)
As discussed in #11950, this flattens the smokehouse testDefn format so there's only a single `expectations` object per smoke test (instead of an array of `expectations` objects). When both PRs have landed, this means e.g. `yarn smoke dbw` will only do a single lighthouse run and assert its results, simplifying the process of re-running a single test, improving the test expectation files, and simplifying smokehouse itself quite a bit without all the nesting and logging only when a whole test id is complete, etc.
This PR is only the changes to smokehouse itself, not the expectation files. We need to provide backwards compatibility for the old format because e.g. pubAds [uses our …
=> tests(smoke): convert to single LH run per test

.github/workflows/smoke.yml, lighthouse-cli/test/smokehouse/frontends/lib.js, lighthouse-cli/test/smokehouse/smokehouse.js, lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js, lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js, lighthouse-cli/test/smokehouse/test-definitions/core-tests.js, lighthouse-cli/test/smokehouse/test-definitions/csp/csp-expectations.js, lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js, lighthouse-cli/test/smokehouse/test-definitions/errors/error-expectations.js, lighthouse-cli/test/smokehouse/test-definitions/forms/form-expectations.js, lighthouse-cli/test/smokehouse/test-definitions/issues/mixed-content.js, lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js, lighthouse-cli/test/smokehouse/test-definitions/legacy-javascript/expectations.js, lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js, lighthouse-cli/test/smokehouse/test-definitions/oopif/oopif-expectations.js, lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics/expectations.js, lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js, lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations.js, lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js, lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa3-expectations.js, lighthouse-cli/test/smokehouse/test-definitions/redirects/expectations.js, lighthouse-cli/test/smokehouse/test-definitions/screenshot/expectations.js, lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js, lighthouse-cli/test/smokehouse/test-definitions/source-maps/expectations.js, lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/expectations.js
part 2/2 of #11950. PR currently based on top of #12818
This splits up our core tests so there's a separate testDefn and ID for every smoke expectation. The splitting up is done here and tentative IDs are chosen, but I wanted some bike shedding input before I tried to put everything in the same format.
For reviewers:
- this is much, _much_ easier to review with [?w=1](https://github.com/GoogleChrome/lighthouse/pull/12819/files?w=1). Lots of indentation changes.
- Most important file is `core-tests.js`, as that's where the test IDs are set.
(I'll be honest: there are a lot of these, and about halfway through this I stopped trying very hard with the names if the tests weren't super obvious how they were different from each other. I'm looking at you `redirects` and `csp` :P Please suggest …
=> tests(smoke): convert core tests to single-expectations format

lighthouse-core/gather/gatherers/global-listeners.js, lighthouse-core/gather/gatherers/js-usage.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js, lighthouse-core/test/gather/gatherers/js-usage-test.js
`JsUsage` was missing some source URL -> script id mappings in timespan mode, so this PR fills in the gaps with empty usages.
I'm concerned that empty usages won't be interpreted the same way as no usages, in which case a new gatherer specifically for source URL -> script id mappings should be considered.
=> core(fr): add snapshot and timespan support to no-unload-listeners audit

lighthouse-core/config/config-helpers.js, lighthouse-core/fraggle-rock/config/config.js, lighthouse-core/fraggle-rock/config/default-config.js, lighthouse-core/test/config/config-helpers-test.js, lighthouse-core/test/fraggle-rock/config/config-test.js
**Summary**
Another piece of FR parity needed for smoketest support, adds config extension support to the FR config. Only the basic use cases of extension+filters and adding a new artifact/navigation/audit/category to the default is supported so far, no newfangled extension logic.
ref #11313
=> core(fr): add config extension support

lighthouse-core/gather/gatherers/trace.js
**Summary**
Let's hope this fixes 🤞  https://github.com/GoogleChrome/lighthouse/issues/12835#issuecomment-891281292
closes https://github.com/GoogleChrome/lighthouse/issues/12835
partially reverts #12692
improves #12837
=> core(traces): disable cpu profiler trace category

lighthouse-core/test/lib/page-functions-test.js
see https://github.com/GoogleChrome/lighthouse/pull/12845#discussion_r681315392
ref #12837
=> tests(page-functions): remove segfault workaround

.eslintignore, .gitignore, report/clients/standalone.js, report/clients/treemap.js, report/clients/viewer.js, tsconfig.json
Forgot to add this folder to the tsconfig during #12690 
Tests remain un-(type-)checked.
=> tests: add report/ to tsconfig

lighthouse-treemap/app/src/main.js, report/clients/psi.js, types/externs.d.ts
embarrassingly slipped through #12013 and not noticed since then because it really only affects the reports (where we usually go through some version of `dom.find()`) and page-functions (where we usually go through the battle-tested `getElementsInDocument`)
=> misc: fix null return on querySelector

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js, lighthouse-core/audits/network-rtt.js, lighthouse-core/audits/network-server-latency.js, lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js, lighthouse-core/test/audits/network-rtt-test.js, lighthouse-core/test/audits/network-server-latency-test.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js
This resolves most of the errors we were seeing for a timespan run after page load.
The solution is to mark all BE audits N/A if there were no network records in timespan mode. Conceptually, this makes some sense since ms savings are calculated from throughput in timespan mode. 
Not all BE audits require network records. It was `LoadSimulator`, used to calculate throughput savings for all BE audits, which requires network records. Instead of always returning N/A, we could get throughput from the settings when using DT or simulated throttling, but not provided throttling. Provided throttling would need to be N/A without network records in timespan mode.
=> core(byte-efficiency): mark n/a if no network records in timespan

.github/workflows/smoke.yml, lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js, lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js, lighthouse-cli/test/smokehouse/smokehouse.js, lighthouse-core/fraggle-rock/config/filters.js, types/smokehouse.d.ts
**Summary**
Adds a fraggle rock mode to our smoke tests and enables a subset of them in CI. Now we have a clean burndown of many of our FR-COMPAT issues too :)
ref #11313
=> tests(fr): add fraggle rock smoke tests

lighthouse-core/gather/gatherers/css-usage.js, lighthouse-core/test/gather/gatherers/css-usage-test.js
`CSS.getStyleSheetText` throws an error if the style sheet was removed. This causes issues in FR timespan mode because style sheets discovered during the timespan can be removed later in the timespan. Example:
```js
const puppeteer = require('puppeteer');
const fs = require('fs');
const open = require('open');
const defaultConfig = require('./lighthouse-core/fraggle-rock/config/default-config.js');
const lighthouse = require('./lighthouse-core/fraggle-rock/api.js');
async function run() {
const browser = await puppeteer.launch({
headless: false,
})
const page = await browser.newPage();
const url = 'https://espn.com';
const config = {
...defaultConfig,
// audits: defaultConfig.audits.filter(a => a === 'byte-efficiency/unminified-css'),
settings: {
output: 'html'
},
};
const run = await …
```
=> core(css-usage): ignore removed stylesheets

lighthouse-treemap/app/styles/treemap.css, lighthouse-viewer/app/index.html, lighthouse-viewer/app/styles/viewer.css
=> clients(viewer): add disclaimer regarding devtools bug

.github/workflows/smoke.yml, lighthouse-core/fraggle-rock/config/config.js, lighthouse-core/test/fraggle-rock/config/config-test.js
**Summary**
Overrides the quiet windows when throttlingMethod isn't simulate and enables the metrics Fraggle Rock smoke tests to prevent regressions.
ref #12861 #11313
=> core(fr): override quiet windows for observed performance

lighthouse-core/audits/critical-request-chains.js, report/renderer/crc-details-renderer.js, types/audit-details.d.ts, types/audit.d.ts, types/config.d.ts, types/global-lh.d.ts
To give an idea of what #12860 would look like, this moves `audit.d.ts` and `audit-details.d.ts` to exports instead of directly writing to `global.LH.*` types, then starts a centralized place to do the global declaration to maintain current type behavior.
Much easier to review with [`?w=1`](https://github.com/GoogleChrome/lighthouse/pull/12870/files?w=1) since there's an indentation change. Also divided into two commits if you want to see the changes to the two files (and associated references) separately.
=> core: convert audit types to modules

types/artifacts.d.ts, types/audit-details.d.ts, types/audit.d.ts, types/budget.d.ts, types/config.d.ts, types/externs.d.ts, types/gatherer.d.ts, types/global-lh.d.ts, types/html-renderer.d.ts, types/i18n.d.ts, types/lhr.d.ts, types/protocol.d.ts, types/smokehouse.d.ts, types/structured-data.d.ts, types/treemap.d.ts
re: #12860
in the style of #12870, converts all the rest of our core `.d.ts` files to local import/export style with a single file for exposing on the global. No changes to js files here. `externs.d.ts` is the only remaining (core) file, left for a follow up because it's messier.
No changes to `.js` files in this one. [`?w=1`](https://github.com/GoogleChrome/lighthouse/pull/12880/files?w=1) to avoid having to wade through all the indentation changes, and the individual file conversions (and their side effects) are split up by commit.
=> core: convert core d.ts files to modules

types/artifacts.d.ts, types/config.d.ts, types/externs.d.ts, types/gatherer.d.ts, types/global-lh.d.ts, types/i18n.d.ts, types/treemap.d.ts
fixes #12860
last follow up to #12870 and #12880.
Externs is a weird grab bag of stuff and should probably be organized further (e.g. type-utility helpers separated from random LH type defs?), but this mostly doesn't do that. The only big moves are moving `LH.Trace`/`LH.TraceEvent`/`LH.DevtoolsLog` over to `artifacts.d.ts` and `LH.Locale` to `i18n.d.ts`.
Everything else is just explicit export and global exposure in `global-lh.d.ts` as in the other two PRs.
Much cleaner review with `?w=1`
=> core: convert externs.d.ts files to modules

package.json
**Summary**
coverage reporter has been changed to `c8` from `nyc`.
=> misc: remove nyc config

build/build-report.js, lighthouse-core/scripts/roll-to-devtools.sh
We need a UMD bundle build of the report for PSI. The ESM bundle doesn't fly there. 
Also note that this build-report file is being adjusted in https://github.com/GoogleChrome/lighthouse/pull/12815/files. I'm assuming this PR here will land first before 12815, and i'll rebase that one.
=> report(build): create UMD bundle build

.github/workflows/smoke.yml, lighthouse-cli/test/smokehouse/report-assert.js, lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js, lighthouse-core/fraggle-rock/config/default-config.js, lighthouse-core/fraggle-rock/gather/runner-helpers.js, lighthouse-core/gather/gatherers/stacks.js, types/smokehouse.d.ts
**Summary**
Achieves parity with legacy runner on Stacks gatherer and FullPageSnapshot gatherer (the two necessary to match results on the dobetterweb smoketest). This also adds the ability to target assertions to the legacy or FR runner in smoketests to account for irreconcilable differences like fewer passes and extra contexts that change the ID of certain artifacts.
ref #12861 #11313
=> core(fr): parity on Stacks and FullPageSnapshot gatherers

lighthouse-core/config/config-helpers.js, lighthouse-core/gather/gatherers/seo/tap-targets.js, lighthouse-core/lib/cdt/SDK.js, lighthouse-core/scripts/i18n/collect-strings.js, lighthouse-viewer/app/src/lighthouse-report-viewer.js, package.json, report/renderer/report-ui-features.js, tsconfig.json, types/config.d.ts, yarn.lock
I was doing an update to 4.3.5 when the 4.4 release candidate came out. The [4.4 perf improvements](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-rc/#perf-improvements) really help with the continuing split up of tsconfigs, so it would be nice to land now.
The fixes needed in existing code are kind of random but are each a reasonable change.
=> deps: update to typescript@4.4.1-rc

lighthouse-core/config/config.js, lighthouse-core/test/config/config-test.js
We already had special handling of f-p-s w/ `onlyCategories` (#11829) but it makes sense to do the same for skipAudits.
fixes #11913 
fixes #12642
=> core(config): keep full-page-screenshot in skipAudits case

build/build-bundle.js, build/build-lightrider-bundles.js, build/build-viewer.js
this also fixes brfs readFileTransform... `readFileSyncTransform` is not an option. Not sure how the PRs that I made introducing this recorded byte savings ... 😄 
fixes #12919
=> misc(build): do not include locales in devtools bundle

report/renderer/report-ui-features.js
This was using the wrong method. The intention was to use postMessage outside devtools.
=> report: use postMessage to open viewer outside devtools

lighthouse-core/scripts/download-chrome.sh
Unblocks CI until the underlying issue of #12942 is fixed
Hopefully we won't have to do this for long.
=> tests(ci): temporarily use a fixed version of ToT Chromium

.eslintrc.js, clients/.eslintrc.js, lighthouse-core/util-commonjs.js, lighthouse-treemap/types/treemap.d.ts, lighthouse-viewer/types/viewer.d.ts, package.json, report/.eslintrc.cjs, report/clients/psi.js, report/clients/standalone.js, report/renderer/details-renderer.js, report/renderer/element-screenshot-renderer.js, report/renderer/logger.js, report/renderer/report-ui-features.js, report/renderer/text-encoding.js, report/renderer/util.js, report/test-assets/faux-psi.js, report/test/renderer/category-renderer-test.js, report/test/renderer/performance-category-renderer-test.js, report/test/renderer/pwa-category-renderer-test.js, report/tsconfig.json, report/types/augment-dom.d.ts, report/types/buffer.d.ts, report/types/html-renderer.d.ts, report/types/report-result.d.ts, tsconfig.json, types/externs.d.ts, types/global-lh.d.ts, types/query-selector.d.ts
Isolates `report/` as a typescript "project" allowing it to live off in its own type world. This allows it to be browser specific and not bring in the entire lighthouse-cli/lighthouse-core/etc world just to type check the report.
Dependencies are simpler and (because of the expanded `-b` mode) more compilation caching occurs which means faster follow-up type checks (e.g. if you're working on core and haven't touched the report, the `yarn tsc -b report/` part will finish in 200ms because the cached `.tmp/tsbuildinfo` file will be newer than all the files in `report/`).
The bulk of this PR is splitting up a few more `d.ts` files for e.g. the parts of `html-renderer.d.ts` that `treemap` and `viewer` need vs the parts they don't.
I'll follow this PR with changes to make `treemap/`, `viewer/`, …
=> report: extract independent report types

lighthouse-viewer/app/src/lighthouse-report-viewer.js, lighthouse-viewer/tsconfig.json, lighthouse-viewer/types/viewer.d.ts, package.json, report/tsconfig.json
builds on #12946 to isolate viewer code.
Going through these files, it feels even more like viewer should move to `report/clients/viewer/` given that it's like 80% report code anyways, but we can take a look at that as part of the #12254 refactors
=> report: isolate viewer type checking

lighthouse-core/scripts/download-chrome.sh
Reverts GoogleChrome/lighthouse#12943
fixes #12942
Unfortunately for the `DevTools / integration` CI check, our clever method of only downloading the content-shell once a day:
https://github.com/GoogleChrome/lighthouse/blob/0b31fe2b6c3ada48ab662ac9ae07e278f552b1c2/third-party/download-content-shell/download-content-shell.js#L74-L76
currently is looking for downloads in the broken URL revision numbers and so will fail if the cached version isn't able to be used. It'll be about 90 more Chromium changes (starting with `913920`) until we're clear of the broken revision numbers.
=> tests(ci): restore ToT Chromium download

flow-report/App.tsx, flow-report/test/App-test.tsx, flow-report/tsconfig.json, flow-report/types/flow-report.d.ts, package.json
fairly straightforward, though a few options here to change now or later, depending on your preferences, @adamraine
=> report: isolate flow-report type checking

build/build-treemap.js, lighthouse-treemap/app/src/main.js, lighthouse-treemap/tsconfig.json, lighthouse-treemap/types/treemap.d.ts, package.json
Last functional piece of the `tsc --build` puzzle (tsconfig cleanup to follow).
The main change here is eliminating the reference to [`LhlMessages`](https://github.com/GoogleChrome/lighthouse/blob/f52048921427cc51e629a75a8f16d2c45407d636/lighthouse-core/lib/i18n/locales.js#L19) which brings in a ton of core files.
The type could be duplicated or moved to a shared `d.ts` file in the lhr types, but following the style of the equivalent `Util.i18n` usage in the main report, the LhlMessages format can be flattened from `Record<LH.Locale, {message: string}>` to `Record<LH.Locale, string>` in the build step that generates the strings, which actually simplifies ingestion in `treemap/app/src/main.js` where it's turning it into that format in the end anyways.
=> report: isolate treemap type checking

lighthouse-core/lib/network-request.js, lighthouse-core/lib/url-shim.js, lighthouse-core/test/audits/byte-efficiency/render-blocking-resources-test.js, lighthouse-core/test/computed/load-simulator-test.js, lighthouse-core/test/computed/resource-summary-test.js, lighthouse-core/test/lib/network-request-test.js, lighthouse-core/test/lib/url-shim-test.js
**Summary**
Closes three holes in our `isNonNetworkRequest` logic:
1. `file` protocol URLs were considered network requests.
2. `filesystem` protocol URLs were considered network requests. (it's [different](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry/filesystem)!)
2. When requests are blocked or otherwise don't receive a response the `protocol` field is left empty and requests weren't identified as non-network.
fixes #12915
=> core(network-request): identify filesystem resources as non-network

build/build-bundle.js
Minor change to relocate the necessary massaging to the CDT bundle. Having it in the minify function makes commenting out that function (to debug CDT with legible code) not possible, forcing you to do a slightly more cumbersome commenting-out of parts of that function. More than that, it simply didn't belong there.
=> misc(build): refactor devtools bundle tweaking

package.json, yarn.lock
with [typescript 4.4 out](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/), updates from the RC to the final release version. Also updates `@typescript-eslint/parser` to get rid of the "not officially supported" warning.
=> deps: update to typescript 4.4.2

flow-report/assets/styles.css, flow-report/jest.config.js, flow-report/src/app.tsx, flow-report/src/util.ts, flow-report/src/wrappers/report-renderer.tsx, flow-report/src/wrappers/report.tsx, flow-report/test/app-test.tsx, flow-report/test/common-test.tsx, flow-report/test/jsdom.ts, flow-report/test/setup/env-setup.ts, flow-report/test/sidebar/flow-test.tsx, flow-report/test/sidebar/sidebar-test.tsx, flow-report/test/summary/summary-test.tsx, flow-report/test/util-test.tsx, flow-report/types/flow-report.d.ts, report/renderer/dom.js
Renders a lighthouse report in the flow report. I intentionally left `ReportUIFeatures` out for this PR.
=> report(flow): embedded lighthouse report

lighthouse-core/audits/seo/http-status-code.js, lighthouse-core/test/audits/seo/http-status-code-test.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js
It's the only (non-manual) audit in timespan SEO, and it would be N/A most of the time.
=> core(http-status-code): navigation only

lighthouse-core/gather/fetcher.js, lighthouse-core/gather/gatherers/seo/robots-txt.js
Temporary fix to allow us to upgrade Chrome in Lightrider/PSI.
ref #12936
=> clients(lightrider): use iframe fetcher

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
The `source` for this console message seems to have changed on the protocol.
=> tests(smoke): fix dbw console error expectation

lighthouse-cli/test/fixtures/robots.txt, lighthouse-cli/test/smokehouse/test-definitions/csp/csp-expectations.js, lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js, lighthouse-core/gather/gatherers/seo/robots-txt.js
=> tests(smoke): check for passing robots-txt

.github/workflows/unit.yml
**Summary**
Fixes our unit tests by avoiding the jest crash in node 16.9.0
see https://github.com/nodejs/node/issues/40030
=> tests: avoid node 16.9.0

flow-report/src/summary/summary.tsx, flow-report/src/util.ts, lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js, lighthouse-core/fraggle-rock/config/config.js, lighthouse-core/fraggle-rock/gather/navigation-runner.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/gather/gatherers/css-usage.js, lighthouse-core/gather/gatherers/js-usage.js, lighthouse-core/gather/gatherers/trace.js, lighthouse-core/lib/emulation.js, lighthouse-core/runner.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js, types/lhr/flow.d.ts
**Summary**
The usage of FR-COMPAT comments morphed over time from a "heads up critical functionality is still missing" to a "here's something we want to eventually accomplish in FR." All but 1 of the existing comments were closer to the latter which I believe is better tracked as items in #11313. I've added all the relevant efforts captured by the current set of comments to that issue and feel we're close enough that future work can continue to be tracked through issues rather than the comments.
@adamraine thoughts?
ref #11313
=> misc: remove all FR-COMPAT todos

lighthouse-cli/test/smokehouse/test-definitions/errors/error-expectations.js, lighthouse-core/fraggle-rock/gather/navigation-runner.js, lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
**Summary**
Preserves traces in the artifacts when page load fails in Fraggle Rock navigation runner. This brings parity to error artifacts for FR.
ref #11313
=> core(fr): preserve traces on failed page load

flow-report/src/summary/summary.tsx, flow-report/src/wrappers/category-score.tsx, lighthouse-core/util-commonjs.js, report/clients/psi.js, report/renderer/category-renderer.js, report/renderer/performance-category-renderer.js, report/renderer/report-renderer.js, report/renderer/util.js, report/test/renderer/category-renderer-test.js, report/types/report-result.d.ts
Addresses https://github.com/GoogleChrome/lighthouse/pull/13009#discussion_r704816820
Plan to merge ~before~ after #13009
=> report: add gatherMode option to category score

report/assets/styles.css, report/assets/templates.html, report/renderer/components.js
First pass at tweaking the metrics table to new design. Just making the value bigger here, and shifting some of the grid stuff. Also, I tossed in a tweak to the mobile version.
=> report: make metric value more prominent in table

lighthouse-core/lib/network-records-from-trace.js
Signed-off-by: Victor Porof <victorporof@google.com>
**Summary**
Fixes a few errors encountered while using the `analyzeTrace` API. The whole `NetworkRecordsMaker` implementation works decently but (as it is known), it requires polish, which is out of the scope of this PR. I just wanted to keep things running.
cc @paulirish
=> Fix errors encountered when auditing various profiles

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js, lighthouse-core/audits/byte-efficiency/uses-responsive-images-snapshot.js, lighthouse-core/audits/dobetterweb/js-libraries.js, lighthouse-core/audits/dobetterweb/uses-http2.js, lighthouse-core/audits/lcp-lazy-loaded.js, lighthouse-core/audits/oopif-iframe-test-audit.js, lighthouse-core/fraggle-rock/config/validation.js, lighthouse-core/lib/i18n/locales/en-US.json, lighthouse-core/lib/i18n/locales/en-XL.json, lighthouse-core/test/audits/dobetterweb/js-libraries-test.js, lighthouse-core/test/config/config-test.js, lighthouse-core/test/fraggle-rock/config/config-test.js, lighthouse-core/test/fraggle-rock/config/validation-test.js, lighthouse-core/test/results/sample_v2.json, lighthouse-core/test/runner-test.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
**Summary**
The failureTitle was defined in this audit but not actually exported on the `meta` doh! This means the error message that the user receives is written backwards 😞  
We had validation for this to prevent such cases, but it only applied when the scoreDisplayMode was *explicit*, so this PR also fixes our validation to fail if the default scoreDisplayMode of binary is used.
Fixes https://github.com/GoogleChrome/lighthouse/issues/13048
=> core(lazy-lcp): fix failureTitle in lcp-lazy-loaded

.github/workflows/smoke.yml, lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
Adds an easier way to split up smoke tests across multiple runners with a `--shard=n/d` flag, which splits the requested tests up into `d` shards and runs the `n`th shard.
This stacks with the existing test selection and `--invert-match` functionality, so e.g. `yarn smoke seo --shard=1/2` will run `seo-passing seo-failing` (out of all the `seo` tests `seo-passing seo-failing seo-status-403 seo-tap-targets`), and similarly `yarn smoke --invert-match forms --shard=1/4` will run the first fourth of all the smoke tests excluding `forms`.
Both FR and the smoke bundle now run almost all of the smoke tests so are taking longer and we may want to split them up, but the `--invert-match` trick won't work to split them up into multiple runners because they need `--invert-match` to disallow certain …
=> tests(smokehouse): add flag for test sharding

lighthouse-core/gather/gatherers/trace.js, lighthouse-core/test/gather/gatherers/trace-test.js
**Summary**
Adds support to the fraggle rock trace collection path to use `additionalTraceCategories`, also adds tests to the trace gatherer.
ref #11313
=> core(fr): support additionalTraceCategories

lighthouse-core/fraggle-rock/gather/timespan-runner.js, lighthouse-core/gather/driver/prepare.js, lighthouse-core/test/fraggle-rock/api-test-pptr.js, lighthouse-core/test/fraggle-rock/gather/mock-driver.js, lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js, lighthouse-core/test/gather/driver/prepare-test.js
**Summary**
Enables device emulation and throttling in timespans by default.
ref #11313
=> core(fr): setup emulation and throttling for timespans

lighthouse-core/index.js, tsconfig.json
The main typescript compilation (from the root `tsconfig.json`) hasn't had `emitDeclarationOnly` turned on because of compilation errors I ran into in #12914 when I initially enabled that. Not having declaration emit was ok, though, because it's a compilation root, not a dependency for any of our other tsconfigs, so it didn't need a `d.ts` emit for anything. The downside is that less of it is cacheable and more has to be re-done on each compile, even if nothing in the core files has changed.
I ran into this problem again in a different context and it turns out it's fairly simple, only a single error (I thought it was the first of many), and it even tells you exactly what you need to do to fix it.
> `Declaration emit for this file requires using private name 'NetworkRecords' from module …
=> core: make main tsc compile cacheable

lighthouse-core/lib/proto-preprocessor.js, proto/lighthouse-result.proto, types/lhr/lhr.d.ts
Turns out we'll need to use swap locale in PSI.
ref: #10148
=> misc(proto): add i18n.icuMessagePaths

report/renderer/report-ui-features.js
see b/195747306
There's a bug that complains when you have this:
```html
<label for="foo">
<input id="foo" type="checkbox">
</label>
```
but ... nesting PLUS for/id is redundant, so we just gotta get rid of one of them.
removing for/id doesnt affect the a11y/tabbing and generally i prefer the nesting solution, so i went with this.
the feature originally landed (in https://github.com/GoogleChrome/lighthouse/pull/6351 ) with both solutions, fwiw. i think it was just being defensive.. didnt hunt for the original reason.
=> report(3p-filter): drop for/id as elements are already nested

lighthouse-core/gather/gatherers/trace.js
The hires trace category was removed and basic `cpu_profiler` cat does the high-resolution sampling by default as of may 2020.
https://bugs.chromium.org/p/chromium/issues/detail?id=1082220
=> core(tracing): remove cpu_profiler.hires

lighthouse-treemap/app/src/main.js
Fix minor typo:
github -> GitHub
=> misc: fix typo in lighthouse-treemap/app/src/main.js

build/build-report.js, package.json, yarn.lock
We previously settled on `@rollup/plugin-typescript@^2.1.0` even though that's pretty old (Jan 2020) because the latest versions were broken with our typescript setup. The rollup error messages were pretty inscrutable and not worth wading through since the old version was working fine (with the latest `tsc` as a peer dep).
https://github.com/GoogleChrome/lighthouse/pull/13072#discussion_r709639872 kind of forces our hand because we want `extends` support in tsconfig files, so we need a more recent plugin. The fix isn't so bad, it just seems like you really really can't use a custom `outDir`. The [readme gets into this a bit](https://github.com/rollup/plugins/tree/53fb18c0c2852598200c547a0b1d745d15b5b487/packages/typescript#declaration-output-with-outputfile), but that workaround didn't …
=> deps: update to latest @rollup/plugin-typescript

flow-report/tsconfig.json, lighthouse-treemap/tsconfig.json, lighthouse-viewer/tsconfig.json, package.json, report/generator/tsconfig.json, report/tsconfig.json, tsconfig-all.json, tsconfig-base.json, tsconfig.json, types/lhr/tsconfig.json
Extracts the shared tsconfiguration into a `tsconfig-base.json` file and has all tsconfig files extend from it. `tsconfig-base.json` also serves as a compilation entry point, so `yarn tsc --build tsconfig-base.json` compiles all the sub-(tsc-)projects.
Final PR to #12870, #12880, #12888, #12909, #12914, #12940, #12940, #12946, #12951, #12952, #12953, #12999, and #13069 sequence :)
#12860 listed some starting goals, but to summarize the point of all this:
- made single declaration points for [global `LH.*` types](https://github.com/GoogleChrome/lighthouse/blob/cb00325d735353437144c78f26c714cc76b9f590/types/global-lh.d.ts) so they'd stop [stomping](https://github.com/GoogleChrome/lighthouse/issues/12860#stomping) on each other
- clustered code so we'd stop duplicating compilation of files …
=> core(tsc): add base tsconfig for config inheritance

.github/workflows/unit.yml
reverts #13012
https://github.com/nodejs/node/issues/40030 was [fixed in 16.9.1](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#2021-09-10-version-1691-current-richardlau), so we can go back to floating against the latest Node 16.
=> tests: restore use of latest node 16 in CI

lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js
**Summary**
Our smokes have been failing because the warning on apple-touch-icon for SVGOMG is missing. The page itself was updated to fix the warning :)
=> tests: update SVGOMG expectations

lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js, lighthouse-core/test/fraggle-rock/scenarios/disconnect-test-pptr.js, lighthouse-core/test/fraggle-rock/scenarios/package.json, lighthouse-core/test/fraggle-rock/scenarios/pptr-test-utils.js
**Summary**
Refactors the lone puppeteer API test for Fraggle Rock to enable easily testing individual integration scenarios. Adds an example of such a scenario, disconnect integration testing (checks that blocked patterns go away after Lighthouse is done).
ref #11313
=> tests: add FR integration scenarios

report/assets/styles.css
g3 import keeps complaining about this css rule; if no one feels strongly, simplest solution is to just get rid of this
=> report: remove smooth scrolling css

lighthouse-viewer/app/src/firebase-auth.js
Fixes #12890
Credentials have been broken for awhile. We lost access to the old project, so I made a new one.
Shouldn't merge this until the Oauth app is transferred out of my name and into `googlechrome` org.
=> clients(viewer): use new firebase credentials

lighthouse-core/fraggle-rock/gather/driver.js, lighthouse-core/gather/driver/navigation.js, lighthouse-core/gather/driver/prepare.js, lighthouse-core/gather/driver/storage.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
**Summary**
Adds a few more status logging to match that of legacy gather runner. The URL log is a *bit* more controversial, and I'm open to removing it, but I think it's helpful to be explicit about where the navigation is starting.
ref #11313
=> core(fr): add parity logging

build/build-report.js, build/build-smokehouse-bundle.js, build/gh-pages-app.js, build/rollup-plugins.js, package.json, yarn.lock
=> misc(build): create rollup-plugins.js helper module

build/build-report.js, lighthouse-core/scripts/build-test-flow-report.js
When I'm working on the standalone report, I don't want to incur whatever wildness is going on with the tsc plugin for the flow report build.
That work for you @adamraine ?
=> report(build): don't build flow if only --standalone is requested

lighthouse-core/lib/stack-packs.js
`require.resolve` just isn't necessary here–we only need to create the same values as the i18n keys (like `node_modules/lighthouse-stack-packs/packs/amp.js`).
=> core(stack-packs): simplify i18n filename lookup

lighthouse-core/fraggle-rock/api.js, lighthouse-core/fraggle-rock/user-flow.js, lighthouse-core/test/fraggle-rock/user-flow-test.js
**Summary**
Some minor usability improvements to the UserFlow API discovered while writing docs in #13134. Two substantive changes + tests:
- Expose `startFlow` at the api.js level.
- Defaults subsequent navigations to *not* reset storage (these aren't cold loads afterall)
ref #11313 https://github.com/GoogleChrome/lighthouse/pull/13134/files#r717982285
=> core(fr): add UserFlow usability improvements

docs/user-flows.md
**Summary**
Adds some user flow documentation and explainers for the different modes. Feedback welcome :)
ref #11313
=> docs: add user flow docs

lighthouse-viewer/app/styles/viewer.css
#13057 removed direct usage of the report styles, which the viewer relied on a bit for styling its initial view
->
=> clients(viewer): add body styles

lighthouse-viewer/app/index.html
undos #12846
Latest Chrome stable is now 94, which has resolved this issue.
=> clients(viewer): remove devtools disclaimer

docs/recipes/auth/package.json, docs/recipes/custom-gatherer-puppeteer/test.sh, docs/recipes/integration-test/docs-jest.config.js, docs/recipes/integration-test/package.json, docs/recipes/package.json, jest.config.js, package.json
kind of a prerequisite to #13148, but useful on its own.
The recipes each need their own `yarn install` run (and it turns out `integration-test` didn't have its `install` run, it was just falling back to the root `jest` and (I believe) the `yarn link`ed `lighthouse`).
As a result it doesn't really make sense to include `docs/recipes/integration-test/example-lh-auth.test.js` in the default jest tests, which ideally should work with just a `git clone ... && yarn && yarn build-all && yarn test`.
This PR breaks it out into its own separate `jest` call, and centralizes the running of the recipe tests to their own `package.json`.
=> tests: centralize running of recipe tests

report/clients/psi.js, report/test/clients/psi-test.js
this is minor followup from #13057
the faux-psi was broken https://lighthouse-orr78rw4f-googlechrome.vercel.app/sample-reports/%E2%8C%A3.psi.xl-accented 
maintaining preparelabdata is kinda terrible so we'll have to call it quits at some point.. 
also i tried writing a test, but since jsdom can't apply styles, i can't test much aside from confirming there's a style tag injected. (seems lame)
=> clients(psi): include global reports styles in legacy psi rendering

build/build-sample-reports.js
fixes a small bug @brendankenny noticed... `sample-reports/⌣.psi.espanol/index.html` wasn't in spanish.
=> misc: ensure psi.espanol sample-report es en espanol

package.json, readme.md
**Summary**
The PR(#13045) converts cli to use esm which also uses named exports for commonjs, this commit just corrects the description in README.
- #13045
=> docs: correct the Node.js version base

lighthouse-core/scripts/pptr-run-devtools.js
1) method name changed, so our sniffing broke
2) check if startLighthouse is called correctly (otherwise mark as an error)
3) print how many urls ran successfully
4) close the page via `finally {` to prevent pages from hanging around on errors
=> misc(scripts): fix run-devtools sniffing, add error checking

flow-report/assets/styles.css, flow-report/src/summary/summary.tsx, flow-report/test/summary/summary-test.tsx
I used a lot of `overflow-x: hidden; text-overflow: elide` to make this work. Adding a minimum text width of 20 characters in a few places prevents the text from disappearing completely.
I thought about sticking the ellipses in the url directly (I guess we still could), but I don't think it's a big deal to let CSS handle to overflow. Even if we wind up hiding the "more important" part of the url, the best option would be for the user to define their own descriptive name.
#11313
=> report(flow): elide step name

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
**Summary**
Appcache warning no longer shows up in deprecations which fails our smoke tests on ToT. Did not remove the appcache marker itself because it's part of #12614
=> tests: update deprecations smoke for M96

flow-report/test/flow-report-pptr-test.ts
Should help prevent issues like https://github.com/GoogleChrome/lighthouse/pull/13280 in the future.
=> report(flow): puppeteer test

jest.config.js
Was causing this error for me locally:
=> tests: ignore .tmp directory in jest modules

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js, lighthouse-core/audits/errors-in-console.js, lighthouse-core/test/audits/errors-in-console-test.js, lighthouse-core/test/results/sample_v2.json
`url` is redundant info, exists in sourceLocation.
=> core(errors-in-console): remove url property from items

lighthouse-core/config/default-config.js, lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, lighthouse-core/test/results/sample_v2.json, report/renderer/performance-category-renderer.js, report/test/renderer/performance-category-renderer-test.js
proposing this for #13328
The order of metrics and audits in default-config has a direct effect on the visual presentation and I've manually adjusted them there previously to affect the displayed result. So I'd rather continue to control it through that means.
This is more simple than and still accomplishes the goals:
* ✅ navigation 6-metric display looks good
* ✅ navigation 6-metric display maintains existing item placement (that has been consistent for 3 years)
* ✅ timespan 2-metric display lays out side-by-side instead of vertically-stacked.
--------------
--------------
=> report: layout metrics naturally 

treemap/app/src/main.js
when there were 0 total bytes JS on a page, treemap will take percentages of that 0 and happily show you 
`https://example.com/ · Resource Bytes: 0 B (NaN%)`
We saw it on example.com, but also noticed by at least [one user](https://twitter.com/drag137/status/1460527535813537793).
The "correct" percentage is arguable but since there's just the one entry on the page 100% seemed more reasonable than 0%, since that just leaves you wondering where the rest of the 0 bytes are :)
Testing is awkward. I could change `debug.json` to include a subnode with 0 total but it seems fiddly (would the test have to click into the subtree to trigger this path?). Add a new pptr test just for this?
fixes #13383
=> report(treemap): correct percentages when 0 bytes JS

build/build-bundle.js, lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js, lighthouse-core/lib/page-functions.js
Rollup was deleting the `for (let j = 0; j < 10000; j++) s += 'a';` line in the benchmark index function, resulting in a value of  500,000+ in bundled results.
=> misc(build): prevent over optimization of computeBenchmarkIndex

report/test/renderer/report-renderer-axe-test.js
This has timed out for me in GHA a few times now.
=> tests: increase timeout for axe test

docs/throttling.md
Unless you read the code snippet that did the actual `npm install @sitespeed.io/throttle` call, you'd get the impression that this was talking about [`throttle` ](https://www.npmjs.com/package/throttle), which is also a throttling package but doesn't do anything that the page is talking about.
As someone familiar with how to install packages from npm, I confidently breezed past the install line and thought the rest was some kind of mistake, not that there was another `throttle` package with an org scope being referred to.
Maybe this is overkill on clarifying, but it also seems fine :)
=> docs(throttling): clarify throttle npm name

.eslintrc.js, lighthouse-core/lib/statistics.js, lighthouse-core/test/lib/statistics-test.js
The numerical accuracy part of #13316, laying the foundation for the rest.
As mentioned there, currently `getLogNormalScore({p10: 200, median: 600}, 200) === 0.8999999314038525`, which is < 0.9, so wouldn't be considered passing, even though 200 is ≥ the p10 threshold and so should be passing. In practice the scores are rounded to two decimal places so this change won't be observable, but if/when we change how the scores are rounded, this will be a problem.
Also, it's just wrong and should be fixed :)
This change ensures that for raw scores (before rounding):
- if `numericValue` is ≤ the `p10` control point, then the audit score will be ≥ 0.9
- if `numericValue` is > the `p10` control point, then the audit score will be < 0.9
- if `numericValue` is ≤ the `median` control point, then the …
=> core: ensure log-normal score is always in correct range

build/build-report-components.js, clients/extension/scripts/popup.js, lighthouse-cli/cli-flags.js, lighthouse-cli/test/smokehouse/test-definitions/redirects/redirects-config.js, lighthouse-core/audits/dobetterweb/js-libraries.js, lighthouse-core/audits/seo/is-crawlable.js, lighthouse-core/audits/third-party-summary.js, lighthouse-core/audits/valid-source-maps.js, lighthouse-core/computed/js-bundles.js, lighthouse-core/fraggle-rock/gather/navigation-runner.js, lighthouse-core/gather/driver/execution-context.js, lighthouse-core/gather/gatherers/full-page-screenshot.js, lighthouse-core/scripts/legacy-javascript/run.js, lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js, lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js, lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js, lighthouse-core/test/gather/driver/navigation-test.js, lighthouse-core/test/gather/gather-runner-test.js, lighthouse-core/test/lib/navigation-error-test.js, package.json, report/renderer/swap-locale-feature.js, types/externs.d.ts, viewer/app/src/github-api.js, yarn.lock
The biggest thing for us is that `as const` [now has an equivalent in jsdoc](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#jsdoc-const-and-type-arg-defaults): `/** @type {const} */ ('provided')`. It's not the best syntax, but pretty much exactly equivalent: `... as Type` is the typescript type assertion, `/** @type {Type} */ (...)` is the jsdoc type assertion. Ideally we can convince them to support `/** @const */` as a shorthand someday.
Other things:
- we needed a fix from typed-query-selector (https://github.com/g-plane/typed-query-selector/pull/20). Updating to get that means we also got support for `:is()` and `: where()` in our typed query selectors :)
- there were a few places where we were able to get rid of some `Promise` workarounds using the new `Awaited` …
=> deps: update to typescript 4.5

build/test/plugins/inline-fs-test.js
When I ran these tests locally I'd get an off-by-11 error in the column expectations for the "supported encoding" test. The warning it emits points to the second arg, but since the first arg is an absolute path this mad the test dependent on where you kept the LH repo.
=> tests: make inline-fs-test not reliant on cwd

build/build-viewer.js, flow-report/api.ts, flow-report/clients/standalone.ts, flow-report/src/app.tsx, flow-report/src/sidebar/flow.tsx, flow-report/src/sidebar/sidebar.tsx, flow-report/src/topbar.tsx, flow-report/src/util.ts, flow-report/test/topbar-test.tsx, flow-report/types/flow-report.d.ts, report/generator/file-namer.js, treemap/types/treemap.d.ts, viewer/app/src/github-api.js, viewer/app/src/lighthouse-report-viewer.js
Ideally want to merge into https://github.com/GoogleChrome/lighthouse/pull/13260 before landing.
Adds "Save as gist" functionality to flow report. Also fixes the flow "Save as html" in the viewer.
=> clients(viewer): save flow as gist

lighthouse-core/runner.js, lighthouse-core/test/results/sample_v2.json
Look at a flow result, I found myself scanning a bit to find out what url a result was for. That made me consider the ordering of the properties in an LHR.
I think it'd be beneficial to human readability of this json to tweak the ordering a bit.
I think this orders the properties in the most informational manner:
- lighthouseVersion
- requestedUrl, finalUrl
- fetchTime
- gatherMode \*
- runtimeError
- runWarnings
\* arguable could go somewhere else
Secondly, I moved `i18n` to be the last item. It being a giant object of strings it kinda makes one gloss over anything that follows. It's also the most meta, making references throughout the rest of the LHR, so delegating it to last place makes some sort of sense to me
=> core: mindfully order properties in the lhr

report/test/clients/bundle-test.js, report/test/renderer/report-ui-features-test.js
This test was logging to stderr about and undefined `HTMLInputElement`. Missed it because the tests still passed.
=> tests: fix undefined HTMLInputElement in bundle-test

lighthouse-core/lib/stack-packs.js, lighthouse-core/scripts/i18n/collect-strings.js, lighthouse-core/test/lib/stack-packs-test.js, package.json, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json, yarn.lock
unfortunately https://github.com/GoogleChrome/lighthouse-stack-packs/pull/66 landed without a semicolon which I had not realized was a requirement for our strings parser. I made a slight adjustment to the regex pattern to work around it.
=> core(stacks): add next.js

lighthouse-cli/test/smokehouse/test-definitions/legacy-javascript/expectations.js, lighthouse-core/audits/byte-efficiency/legacy-javascript.js, lighthouse-core/scripts/legacy-javascript/run.js, lighthouse-core/scripts/legacy-javascript/summary-signals-nomaps.json, lighthouse-core/scripts/legacy-javascript/summary-signals.json, lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
I bumped `core-js` in the verification tool from `3.9.1` to `3.19.1`, which revealed that we must remove the signal for `Object.getOwnPropertyNames` as `esmodules: true` now includes it.
=> core(legacy-javascript): remove Object.getOwnPropertyNames signal

lighthouse-cli/test/smokehouse/frontends/lib.js, lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js, lighthouse-cli/test/smokehouse/smokehouse.js, types/smokehouse.d.ts
=> tests: move sharding higher so smokehouse-bundle can also shard

lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js, package.json, yarn.lock
Closes https://github.com/GoogleChrome/lighthouse/issues/13368
Probably closes https://github.com/GoogleChrome/lighthouse/issues/12039 as well
Looks like this was caused by https://github.com/dequelabs/axe-core/issues/2674 and fixed by https://github.com/dequelabs/axe-core/pull/3172 in https://github.com/dequelabs/axe-core/releases/tag/v4.3.4.
=> deps(axe-core): upgrade to 4.3.5

changelog.md, docs/puppeteer.md, lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js, lighthouse-cli/test/smokehouse/test-definitions/pwa-chromestatus.js
This was recently changed to be just https://chromestatus.com ([no dubs](https://www.youtube.com/watch?v=FrLequ6dUdM))
=> tests(smoke): fix chromestatus url

lighthouse-core/gather/gatherers/seo/font-size.js, lighthouse-core/test/gather/gatherers/seo/font-size-test.js
this is a merge to #13455 
I wanted to add some tests so I pulled in some items from the spec. The regexes now handle uppercase in selectors (meh) and also correctly handles  sibling selectors etc (eg `div+span` gave an incorrect result before because of no whitespace around the `+`. now fixed).
that said, there are plenty of these test cases we still don't handle.   I don't care a lot, but someone could have fun if they wanted. there's probably some stuff to pull from in this npm module [keeganstreet/specificity](https://github.com/keeganstreet/specificity/blob/8757133ddd2ed0163f120900047ff0f92760b536/specificity.js#L22-L52), but it needs to be updated to include todays' `:is()` and `:where()` etc etc.  but IMO it's pretty small ROI
at least the extra test coverage is nice.
=> font-size selector specificity: add slight improvement

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap, lighthouse-core/audits/no-unload-listeners.js, lighthouse-core/config/default-config.js, lighthouse-core/test/results/sample_v2.json, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt
The Chrome bfcache team has determined that unload handlers are the top developer-controllable reason pages aren't able to use the bfcache. The bfcache is by far the fastest way to load a page if navigating by history, so it makes sense to have the audit in the perf category. We discussed this back in https://github.com/GoogleChrome/lighthouse/pull/11085#discussion_r453957792 but punted on the question at the time.
Having it in the perf category also means it will show up in the PSI report, which will reach that many more developers.
Also updates the learn more link to the newer https://web.dev/bfcache article.
=> core: move no-unload-listeners to perf category

lighthouse-core/gather/gatherers/seo/font-size.js, lighthouse-core/test/gather/gatherers/seo/font-size-test.js
Resolves most of https://github.com/GoogleChrome/lighthouse/issues/12001.
=> core(font-size): fix CSS selector regex

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js, lighthouse-core/computed/load-simulator.js, lighthouse-core/lib/dependency-graph/simulator/simulator.js, lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js, lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js, types/gatherer.d.ts
Followup to https://github.com/GoogleChrome/lighthouse/pull/13323
This will use the observed (real) throughput to calculate savings in timespan mode with desktop config (or any config with 0 throughput). Theoretically, any variance in the observed throughput would imply variance in performance for these cases.
=> core(fr): compute timespan saving with observed throughput

lighthouse-cli/test/smokehouse/smokehouse.js
cherry picking just the fix from #13459 just so `yarn build-all` stops logging a big error in the middle of itself :)
=> misc: fix build-smokehouse-bundle build

lighthouse-core/fraggle-rock/config/filters.js, lighthouse-core/test/fraggle-rock/config/filters-test.js
Currently Lighthouse crashes when given a non-existent category for `--only-categories` in FR, either on the CLI with `--fraggle-rock` or in user-flow settings, resulting in `TypeError: Cannot read properties of undefined (reading 'auditRefs')` on [this line](https://github.com/GoogleChrome/lighthouse/blob/10c36d08bed866c79c49c6534de2b4c82a290998/lighthouse-core/fraggle-rock/config/filters.js#L48).
To repro, run  e.g. `lighthouse https://example.com --fraggle-rock --only-categories nope`.
This PR makes it so there's no effect from trying to `--only-categories` a category ID that doesn't exist, which matches classic handling of this situation. FR config handles non-existent `--only-audits` or `--skip-audits` slightly differently than `--only-categories` so already has this behavior, so …
=> core(fr): don't throw on unknown --only-categories value

lighthouse-core/audits/accessibility/object-alt.js, lighthouse-core/scripts/i18n/collect-strings.js, lighthouse-core/test/results/sample_v2.json, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
The `alt` attribute on `<object>` is not recognized as alt text by axe, however the title of the `object-alt` audit implies that it does with md syntax. This PR removes the md syntax.
Related
https://github.com/GoogleChrome/lighthouse/issues/6146
https://github.com/GoogleChrome/lighthouse/issues/11649
https://github.com/GoogleChrome/lighthouse/issues/12528
=> core(object-alt): remove md syntax around "alt"

lighthouse-core/scripts/run-git3po.sh
`npm install` takes a while and has a bunch of side effects... so rather than invoking it (on my machine) every 5 minutes... this'll only do it when we need to.
=> misc(git3po): only install latest git3po if out of date

package.json, yarn.lock
* third-party-web: didn't investigate much but adding new 3p entities, generally. https://github.com/patrickhulce/third-party-web/releases
* robots-parser. some contributed bugfixes and improved spec compliance https://github.com/samclarke/robots-parser/commits/master
* pslist (gets running processes): minimum node version bump. https://github.com/sindresorhus/ps-list/releases
* open: minimum node version bump. also a million WSL fixes. https://github.com/sindresorhus/open/releases?page=2
* lookup-closest-locale: nothing really. https://github.com/format-message/format-message/commits/master/packages/lookup-closest-locale
* jpeg-js: a few bugfixes and avoiding `new Buffer()`: https://github.com/jpeg-js/jpeg-js/releases
=> deps: update various runtime deps

lighthouse-core/scripts/build-devtools.sh, lighthouse-core/scripts/open-devtools.sh, lighthouse-core/scripts/pptr-run-devtools.js, lighthouse-core/test/chromium-web-tests/README.md, lighthouse-core/test/chromium-web-tests/run-web-tests.sh, lighthouse-core/test/chromium-web-tests/setup.sh, lighthouse-core/test/chromium-web-tests/test-locally.sh
Some refactoring/documenting I wanted to do for these scripts.
* Add a lot of file-level comments
* Split out dependency setup from test-locally.sh into its own script
* Run setup.sh in `yarn open-devtools` if running against the default .tmp DevTools checkout
* Split out "roll and build devtools" from `yarn open-devtools`, should be useful for #13456
* SKIP_DOWNLOADS : Add option to skip the content_shell / CDT updates
=> tests: clean up and add comments to cdt layout test scripts

package.json, yarn.lock
These are all from devDeps, so not a big deal, but a lot have built up. There's one remaining, tracked in https://github.com/sindresorhus/cpy/issues/98 (nobody pass a pathological regex while copying over extension files to `dist/`!).
Separated by commit just in case someone cares :)
=> deps: update transitive deps to quiet vulnerability alerts

build/build-bundle.js, package.json, yarn.lock
Long ago (#5293) we substituted `url-shim` for the Node `url` module because `robots-parser` needed `require('url').URL` to give the WHATWG `URL` but the browserify polyfill for `'url'` didn't have `URL` on it. In the meantime, the pubads plugin also started relying on that behavior, importing URL the same way. For some reason, the most popular rollup `'url'` polyfills _still_ don't have `URL` on them, so we've still been shoving `url-shim` in there.
However, there are other things on `url-shim`, and this [can cause issues](https://github.com/GoogleChrome/lighthouse/pull/13519#issuecomment-1006961952) :)
We really only need the slimmest of polyfills for `'url'`, since only the `URL` property is needed, so this PR replaces it with one tiny version.
I also opened PRs in …
=> clients: use minimal 'url' polyfil instead of url-shim

.github/workflows/devtools.yml, lighthouse-core/test/chromium-web-tests/download-devtools.sh, lighthouse-core/test/chromium-web-tests/run-web-tests.sh, lighthouse-core/test/chromium-web-tests/test-locally.sh, lighthouse-core/test/chromium-web-tests/web-test-server.sh
- adds a build job, which rolls LH + builds devtools and uploads to GHA as an artifact
- adds web-tests and sharded smoke test jobs
- uses `restore-keys` for `actions/cache` step, which should speed up build times for cache-misses
cache hit:
cache miss (building off latest cache):
(don't have an example here yet lol)
Building from scratch (no cache used at all):
=> tests: split devtools ci into build, web-tests and smoke jobs 

.github/workflows/devtools.yml, .github/workflows/smoke.yml, .github/workflows/unit.yml
Small job name tweaks. Github actions in status checks are prefaced by their workflow name (e.g. `DevTools / web-tests`) but annoyingly are not prefaced in other contexts (so you get only `web-tests`). This is fine for some things, but I already got confused by the new "Smoke batch 1" and "Smoke batch 2" introduced in #13546.
This renames them to "Smoke DevTools 1" and "Smoke DevTools 2", which will end up with a redundant "DevTools / Smoke DevTools 1" in some contexts, but I couldn't think of another good way to dedupe when it's on its own.
Also renames "Windows" to "Windows smoke" and "Windows unit".
The Github UI choices are kind of unfortunate. Things are still somewhat confusing, but at least differentiated. Super happy to bikeshed :)
=> tests: dedupe some CI job names

third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-clear-data-warning.js, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/resources/lighthouse-storage.html
Should prevent the flakiness in DevTools tests.
=> tests(devtools): ensure WebSQL table is populated

lighthouse-cli/bin.js, lighthouse-cli/test/cli/bin-test.js, package.json, yarn.lock
fixes #13453. see that for rationale.
We'll consider adding it back if we see much evidence that folks are running outdated LH CLI.
=> cli: remove update-notifier

package.json, yarn.lock
https://github.com/yargs/yargs-parser/blob/main/CHANGELOG.md#2025-2021-02-13
No code changes necessary.
Updating to match what yarg's will be from #13590. Separate PR to show that tests still pass / keep other PR simpler.
=> deps(yargs-parser): upgrade to 21.0.0

lighthouse-core/audits/preload-fonts.js, lighthouse-core/audits/preload-lcp-image.js, lighthouse-core/audits/uses-rel-preload.js, lighthouse-core/test/audits/preload-lcp-image-test.js, lighthouse-core/test/results/sample_v2.json, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
disabled in #12661. The bug has since been resolved
re-enabling just this one, saving the other for when we #11960 is closed
=> core(preload-lcp-image): enable audit

build/build-dt-report-resources.js
These files were removed from DevTools. `report-generator.d.ts` is still there.
=> misc(build): remove empty devtools report resources

lighthouse-core/runner.js, lighthouse-core/scripts/update-report-fixtures.js, lighthouse-core/test/results/artifacts/artifacts.json, lighthouse-core/test/results/sample_v2.json
Proposal to fix the timing issues in https://github.com/GoogleChrome/lighthouse/pull/13569.
- Taking a position on https://github.com/GoogleChrome/lighthouse/pull/13569#discussion_r789187162 , `lh:runner:gather` will always reflect the time spent gathering the page, and never the time to load artifacts from disk.
- There will always be a `lh:runner:gather` in `artifacts.Timing`
- Sample artifacts will have unique `startTime` for each timing entry so they aren't deduped in `Runner._getTiming`:
https://github.com/GoogleChrome/lighthouse/blob/62848fb75ff419e6da1d0c103680dc58a1e7f6d9/lighthouse-core/runner.js#L200-L202
=> core(runner): store gather timing on artifacts

lighthouse-cli/test/smokehouse/readme.md, lighthouse-cli/test/smokehouse/report-assert.js, types/smokehouse.d.ts
Landing the smoke test changes separate from https://github.com/GoogleChrome/lighthouse/pull/13569.
=> tests(smoke): test array `_includes` and `lhr.timing`

.github/workflows/issue-assigner.yml
good time to recall that its a standalone workflow and separate from git3po etc.  😀
=> misc: temporarily remove brendan from triage rotation

lighthouse-core/test/audits/accessibility/aria-allowed-attr-test.js, lighthouse-core/test/audits/accessibility/aria-required-attr-test.js, lighthouse-core/test/audits/accessibility/aria-required-children-test.js, lighthouse-core/test/audits/accessibility/aria-required-parent-test.js, lighthouse-core/test/audits/accessibility/aria-roles-test.js, lighthouse-core/test/audits/accessibility/aria-valid-attr-test.js, lighthouse-core/test/audits/accessibility/aria-valid-attr-value-test.js, lighthouse-core/test/audits/accessibility/button-name-test.js, lighthouse-core/test/audits/accessibility/bypass-test.js, lighthouse-core/test/audits/accessibility/color-contrast-test.js, lighthouse-core/test/audits/accessibility/definition-list-test.js, lighthouse-core/test/audits/accessibility/dlitem-test.js, lighthouse-core/test/audits/accessibility/document-title-test.js, lighthouse-core/test/audits/accessibility/frame-title-test.js, lighthouse-core/test/audits/accessibility/html-has-lang-test.js, lighthouse-core/test/audits/accessibility/html-lang-valid-test.js, lighthouse-core/test/audits/accessibility/image-alt-test.js, lighthouse-core/test/audits/accessibility/input-image-alt-test.js, lighthouse-core/test/audits/accessibility/label-test.js, lighthouse-core/test/audits/accessibility/link-name-test.js, lighthouse-core/test/audits/accessibility/list-test.js, lighthouse-core/test/audits/accessibility/listitem-test.js, lighthouse-core/test/audits/accessibility/meta-refresh-test.js, lighthouse-core/test/audits/accessibility/meta-viewport-test.js, lighthouse-core/test/audits/accessibility/object-alt-test.js, lighthouse-core/test/audits/accessibility/tabindex-test.js, lighthouse-core/test/audits/accessibility/td-headers-attr-test.js, lighthouse-core/test/audits/accessibility/th-has-data-cells-test.js, lighthouse-core/test/audits/accessibility/valid-lang-test.js, lighthouse-core/test/audits/accessibility/video-caption-test.js
These tests accidentally regressed in #11474, making every a11y audit test file repeat the same two unit tests (zero nodes and one node). Don't know if these tests are useful, but it was quick to restore them.
=> tests: fix single node a11y tests

report/test/renderer/__snapshots__/report-renderer-axe-test.js.snap, report/test/renderer/report-renderer-axe-test.js
When this result object changes, the delta is way too large to grok (depending on the results). This should help.
=> tests: use simpler assertion in report-renderer-axe-test.js

lighthouse-core/gather/driver/wait-for-condition.js, lighthouse-core/gather/gatherers/full-page-screenshot.js, lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
We don't give the page time to load new resources / perform a layout between changing the viewport and grabbing a screenshot. Sometimes, it would just work, but usually stuff is shifted a lot or many images are not loaded yet.
before
after
=> core(full-page-screenshot): wait for doubleraf, network quiet

flow-report/src/wrappers/report.tsx, report/clients/standalone.js, report/renderer/report-ui-features.js, report/test-assets/faux-psi.js, report/types/report-renderer.d.ts
Deciding to use the dark theme should be left to the embedder, in case it wouldn't mesh with the site theme. We tried to do this with `disableAutoDarkModeAndFireworks` but:
* the name is ambiguous (does it disable dark mode AND fireworks, or just the auto "use dark mode" on fireworks?)
* apparently we wanted the former, but we missed part of it (#13610)
* Forces embedder to drop dark mode support if they simply don't want / can't support the fireworks
This PR:
* deprecates `disableAutoDarkModeAndFireworks`
* adds `disableDarkMode` option (embedders such as DevTools can set this and defer to the DevTools theme system to toggle the dark theme; or they can set it because the site should never be displayed in a dark theme and having just LH be dark would be jarring)
* adds `disableFireworks` …
=> report: add options disableFireworks and disableDarkMode

lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js, types/parse-cache-control/index.d.ts
Closes https://github.com/GoogleChrome/lighthouse/issues/13514
=> core(uses-long-cache-ttl): ignore `stale-while-revalidate`

lighthouse-cli/run.js, lighthouse-core/fraggle-rock/config/config.js, lighthouse-core/fraggle-rock/gather/navigation-runner.js, lighthouse-core/fraggle-rock/gather/snapshot-runner.js, lighthouse-core/fraggle-rock/gather/timespan-runner.js, types/config.d.ts
Part of https://github.com/GoogleChrome/lighthouse/issues/13680
=> core(fr): add `logLevel` to config context

lighthouse-cli/test/fixtures/redirects-self.html, lighthouse-cli/test/smokehouse/core-tests.js, lighthouse-cli/test/smokehouse/test-definitions/redirects-self.js, lighthouse-core/fraggle-rock/gather/navigation-runner.js, lighthouse-core/fraggle-rock/gather/runner-helpers.js, lighthouse-core/fraggle-rock/gather/snapshot-runner.js, lighthouse-core/fraggle-rock/gather/timespan-runner.js, lighthouse-core/test/fraggle-rock/gather/mock-driver.js, lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js, lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js, lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
In legacy navigations `context.url` is the current frame URL and is unaffected by the history API.
However in FR navigations, `context.url` is the result of `page.url()` from Puppeteer and *is* affected by the history API. This can lead to issues in FR navigations where we try and use `context.url` to get the main document, but `context.url` is not the URL used to fetch the main document.
This PR ensures `context.url` reflects the current frame URL without considering any history API calls once we reach the `getArtifact` phase.
-----
Once we deprecate the legacy navigation runner, I think we should deprecate `context.url`. Then we can use `context.baseArtifacts.URL` to get the frame URL and `context.driver.url()` to get the URL affected by history API.
=> core(fr): use frame url in gather context

lighthouse-core/audits/dobetterweb/inspector-issues.js, lighthouse-core/gather/gatherers/inspector-issues.js, lighthouse-core/test/audits/dobetterweb/inspector-issues-test.js, lighthouse-core/test/gather/gatherers/inspector-issues-test.js, lighthouse-core/test/results/artifacts/artifacts.json, package.json, third-party/chromium-synchronization/inspector-issueAdded-types-test.js, types/artifacts.d.ts, yarn.lock
This was renamed on the protocol.
=> core(inspector-issues): update sameSiteCookie to cookie

lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js, lighthouse-cli/test/smokehouse/readme.md, lighthouse-cli/test/smokehouse/report-assert.js, lighthouse-cli/test/smokehouse/smokehouse.js, types/smokehouse.d.ts
=> tests(smoke): add _excludes and _runner

lighthouse-core/audits/script-treemap-data.js, lighthouse-core/test/audits/__snapshots__/script-treemap-data-test.js.snap, lighthouse-core/test/audits/script-treemap-data-test.js, lighthouse-core/test/results/sample_v2.json
in practice I don't think this ever happens, not sure why coverage data would be missing for a script
=> core(script-treemap-data): correct value for size

clients/devtools/devtools-entry.js, clients/devtools/package.json, clients/lightrider/lightrider-entry.js, clients/lightrider/package.json, clients/test/lightrider/lightrider-entry-test.js, clients/test/lightrider/package.json, package.json
ref #12689
manually confirmed to work in LR.
=> clients: convert devtools and lightrider entries to ES modules

build/build-bundle.js, lighthouse-logger/index.js, lighthouse-logger/package.json
ref #12689
This is not a breaking change because only conversions to ESM inside `lighthouse-core` would be.
The only impact is that the `build-bundle` script will see this file as ESM during rollup (FYI: when bundling we use the local copy, but via Node we use the npm pacakge). I have no plans to publish a new version of the npm package, but if we did, that shouldn't be a breaking change for LH consumers either if LH used that new ESM version.
=> core(lighthouse-logger): convert to ES modules

lighthouse-core/test/chromium-web-tests/download-devtools.sh
Fixes the merge issue we were getting in devtools CI build step.
there was an issue with landing a new test file in devtools repo first
https://github.com/GoogleChrome/lighthouse/runs/5591661464?check_suite_focus=true#step:11:52
=> tests: clean devtools repo in CI

.github/workflows/devtools.yml, .github/workflows/smoke.yml
I think this will somewhat reduce the pain that flaky smoke test inflict on landing PRs.
=> tests: increase smoke shards from 2 to 3

lighthouse-core/gather/driver/network-monitor.js, lighthouse-core/test/fixtures/fraggle-rock/navigation-basic/links-to-index.html, lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js, lighthouse-core/test/gather/driver/network-monitor-test.js
This should only affect user-triggered redirects where we backfill `requestedUrl`. I noticed that `Page.frameNavigated` events are not emitted for server redirects, so we must climb the redirect chain to get the initiator request for the navigation.
=> core(network-monitor): resolve server redirects

lighthouse-core/audits/preload-lcp-image.js, lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, lighthouse-core/test/results/sample_v2.json, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
Goal is to help reduce confusion wrt future audit prioritize-lcp-image #13738 
even in isolation, this change is good because the audit explicitly ignores images that are already in the initial HTML
=> core(preload-lcp-image): be specific about when to do this

lighthouse-core/fraggle-rock/gather/runner-helpers.js, lighthouse-core/fraggle-rock/gather/snapshot-runner.js, lighthouse-core/fraggle-rock/gather/timespan-runner.js, lighthouse-core/gather/gatherers/seo/robots-txt.js, lighthouse-core/gather/gatherers/web-app-manifest.js, lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js, lighthouse-core/test/gather/gatherers/css-usage-test.js, types/gatherer.d.ts
=> core: remove `context.url`

lighthouse-core/test/audits/third-party-summary-test.js, lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, package.json, yarn.lock
=> deps: update to third-party-web 0.15.0

package.json, report/test/renderer/__snapshots__/report-renderer-axe-test.js.snap, yarn.lock
Closes https://github.com/GoogleChrome/lighthouse/issues/12432 because the `doc-endnote` role is now deprecated.
https://github.com/dequelabs/axe-core/releases
=> deps(axe-core): upgrade to 4.4.1

docs/user-flows.md
Fixes https://github.com/GoogleChrome/lighthouse/issues/13825
=> docs(user-flows): update api usage

lighthouse-core/lib/tracehouse/trace-processor.js, lighthouse-core/test/create-test-trace.js
Based on the description for https://github.com/GoogleChrome/lighthouse/pull/5917, it seems like we should be ignoring nav starts with falsy document url but the condition doesn't do that.
This fixed the third item in #13847 for me locally.
~Will land after #13844~
=> core(trace-processor): ignore `navigationStart` with falsy document url

.github/workflows/devtools.yml, .github/workflows/smoke.yml
#13792 relied on `${{ strategy.job-total }}` for the count of total shards, but in the smoke tests the `job-total` is 6 from 3 shards * 2 versions of chrome. So we were accidentally testing half the smoke tests (shards 1/6, 2/6, and 3/6). You had to dig into the logs to see the problem, though the three minute completion times were suspicious :)
Also put the shard total in the job name so it's a little more prominent (though the name is still set manually, so there's no guarantee it'll be kept in sync with what's actually running).
=> tests: fix smoke shard total in CI

.github/workflows/devtools.yml
=> tests: fix invalid artifact name for devtools smoke failures

.github/workflows/devtools.yml
We need CI to work, and investigating this further is not a high priority item currently.
ref #13847  #13861
=> tests: temporarily disable oopif-scripts smoke for devtools

.github/workflows/devtools.yml
DevTools / build keeps timing out for me. Yay reliable tools :)
=> tests(devtools): extend yarn timeout

lighthouse-cli/test/smokehouse/readme.md, lighthouse-cli/test/smokehouse/report-assert.js, lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency.js, lighthouse-cli/test/smokehouse/test-definitions/csp-block-all.js, lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js, lighthouse-cli/test/smokehouse/test-definitions/issues-mixed-content.js, lighthouse-cli/test/smokehouse/test-definitions/offline-sw-broken.js, lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics-animations.js, lighthouse-cli/test/smokehouse/test-definitions/perf-frame-metrics.js, lighthouse-cli/test/smokehouse/test-definitions/perf-trace-elements.js, lighthouse-cli/test/smokehouse/version-check-test.js, lighthouse-cli/test/smokehouse/version-check.js, lighthouse-core/audits/deprecations.js, types/smokehouse.d.ts
Two commits here:
1) Add full version string support for the `_minChromium/_maxChromium` properties. Just the milestone number is too coarse to be useful for addressing regressions that have immediately occurred in ToT (but not landed in canary).
2) temporarily ignore smoke failure for deprecations audit, so unblock CI. see #13895
=> tests(smoke): support full chrome version for pruning

lighthouse-core/audits/dobetterweb/doctype.js, lighthouse-core/test/audits/dobetterweb/doctype-test.js, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
The standard specifies that this property is normalized to a lowercased string. https://html.spec.whatwg.org/#doctype-name-state
=> core(doctype): fix mistaken text saying name must be lowercase

lighthouse-core/audits/deprecations.js, lighthouse-core/test/gather/gatherers/inspector-issues-test.js, package.json, yarn.lock
New types used for #13896 but the devtools-protocol package publish was broken. It's since been fixed.
=> deps(devtools-protocol): upgrade to 0.0.995287

lighthouse-cli/cli-flags.js, readme.md
This change replaces all git.io shortlinks in the repo with the fully resolved URL.
[Github has deprecated the git.io link shortening service and will be disabling all links on April 29th](https://github.blog/changelog/2022-04-25-git-io-deprecation/)
=> misc(links): remove git.io shortlinks

lighthouse-core/lib/tracehouse/trace-processor.js, lighthouse-core/test/computed/metrics/cumulative-layout-shift-test.js, lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, lighthouse-core/test/lib/tracehouse/trace-processor-test.js, types/artifacts.d.ts
Part of the responsiveness in timespans implementation.
We've previously relied on `FrameCommittedEvent`s to generate our knowledge of the frame tree, but for traces without navigations (like in a timespan), there typically aren't any `FrameCommittedEvent`s generated because all the frames are already around. As a result, metric events from outside of the main frame wouldn't be included.
`TracingStartedInBrowser` events also have frame tree information, but for a typical navigation the main frame URL will change (from `about:blank` to the test url) and child frames won't be known at all, so that frame tree is useless for cross-frame metrics in navigations.
This PR combines the two sources, starting with the set from `TracingStartedInBrowser` and updating as `FrameCommittedEvent`s come in …
=> core(trace): use tracing-started event for frame tree info

.github/workflows/ci.yml, .github/workflows/unit.yml, clients/test/extension/popup-test-pptr.js, lighthouse-core/scripts/benchmark-plus-extras.js, lighthouse-core/scripts/pptr-run-devtools.js, lighthouse-core/scripts/update-flow-fixtures.js, lighthouse-core/scripts/update-snapshot-sample.js, lighthouse-core/test/fraggle-rock/scenarios/pptr-test-utils.js
If you don't have `CHROME_PATH` set locally, running `api-test-pptr` and `disconnect-test-pptr` fails because a Chrome can't be found for puppeteer to use. Using `chrome-launcher`'s `getChromePath()` will let a Chrome already installed on the system be used, and it still defaults to `CHROME_PATH` if it's set.
=> tests: default to chrome-launcher path

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js
#13895 for background
Currently blocking CI. I guess these two deprecation issues were translated at slightly different times, so now they're both untranslated, the filter introduced in #13896 is taking them both out, and the dbw test is passing with no issues.
=> tests: add temp fix for failing deprecations smoke test

lighthouse-core/test/computed/critical-request-chains-test.js
The helper function `createChainsFromMockRecords` takes a function `setExtrasFn` which modifies the network records made by default. Many tests will modify the urls, but the helper function uses the default url values when building the graph initiators (this is the old code):
This didn't seem to prevent any tests from working, but it was unexpected (I was debugging something by looking at the generated devtools log and found the mismatch of urls here odd).
One test did break from this, and I really don't understand it... so I opted to resolve the breakage by introducing a boolean parameter to this function to recreate the previous bad behavior.
=> tests(crq): call setExtrasFn before using the urls

lighthouse-cli/test/cli/__snapshots__/cli-flags-test.js.snap, lighthouse-cli/test/cli/cli-flags-test.js
fixes #13875
The command to run tests changes depending on how you invoke jest, but is completely irrelevant to `cli-flags` parsing, so it can just be removed.
=> tests: replace $0 in cli-flag snapshots

lighthouse-core/audits/deprecations.js, lighthouse-core/test/audits/deprecations-test.js
This was needed for M97, but that's old enough now. I saw a failure in deprecations smoke test today (unrelated) and I noticed we can delete this now.
=> core(deprecations): drop compat for ConsoleMessages

lighthouse-cli/test/smokehouse/frontends/lib.js, lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js, lighthouse-cli/test/smokehouse/report-assert.js, lighthouse-core/config/config-helpers.js, lighthouse-core/fraggle-rock/gather/base-artifacts.js, lighthouse-core/lib/arbitrary-equality-map.js, lighthouse-core/runner.js, shared/localization/swap-locale.js, tsconfig-base.json
#13695 replaced our individual lodash packages with the whole lodash package, but we relied on treeshaking to keep the bundle small which didn't work because lodash's main module is a big IIFE.
Instead we can import individual modules. In hindsight, that's why lodash stopped publishing individual packages. Because you can just reach in and grab whatever you want.
before: 1705114
after: 1631433
~70KB less
=> deps(lodash): use individual lodash modules to reduce bundle size

viewer/app/src/lighthouse-report-viewer.js
I wanted to look up how often (if at all...) flow reports are used in the viewer, but we don't have the data.
=> clients(viewer): ga event for flow-report

lighthouse-core/test/audits/redirects-test.js, lighthouse-core/test/computed/metrics/cumulative-layout-shift-test.js, lighthouse-core/test/create-test-trace.js, lighthouse-core/test/lib/tracehouse/trace-processor-test.js
While working on #13917 I noticed `create-test-trace` has some very outdated details and wanted to fix them before it all paged out of my brain. There's a much nicer and powerful API possible here, but this PR is just some surface-level fixes to get the generated test traces closer to real traces.
=> tests: update create-test-trace utility

report/renderer/performance-category-renderer.js, report/test/renderer/performance-category-renderer-test.js
Closes https://github.com/GoogleChrome/lighthouse/issues/13929
=> report: hide disclaimer text in timespan

lighthouse-core/audits/accessibility/listitem.js, lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, lighthouse-core/test/results/sample_v2.json, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-navigation-expected.txt, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
**Summary**
Axe-core has been updated to allow listitems to exist inside menu elements, in accordance with the HTML spec. So, this text should be updated since axe-core has been updated to 4.4.x (https://github.com/GoogleChrome/lighthouse/commit/37a1ceb4bb365fc6df470d1cc172760ae03fffa5)
Related to https://github.com/GoogleChrome/web.dev/issues/7802 and https://github.com/GoogleChrome/web.dev/pull/7803 in the web.dev repo.
Menu spec: https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element
Menu on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu
#13926
=> core(listitem): mention li can be contained by a menu

docs/recipes/package.json
We noticed `yarn test-docs` was using old builds of lighthouse, which could only be resolved by running `yarn cache clear`. This PR avoids the problem by not using the global cache folder, instead this test now uses a throwaway folder. also deletes the lock files.
something about using a `.tgz` file as a dependency is caching in an unexpected way 🤷  (just clearing the lock files didn't fix the problem)
=> tests(docs): clear problematic cache

lighthouse-core/test/audits/metrics/experimental-interaction-to-next-paint-test.js, lighthouse-core/test/computed/metrics/responsiveness-test.js
#13295 converted all these tests, but this new audit landed at the same time so missed out.
=> tests: fix unconverted test

lighthouse-core/lib/tracehouse/task-groups.js
M102 will rename UpdateLayerTree to PrePaint. See https://chromium-review.googlesource.com/c/chromium/src/+/3519012
Trace data is the same.
=> core(trace): add PrePaint event, renamed from UpdateLayerTree

lighthouse-core/audits/metrics/experimental-interaction-to-next-paint.js, lighthouse-core/computed/metrics/responsiveness.js, lighthouse-core/test/computed/metrics/responsiveness-test.js, types/artifacts.d.ts
part of #13916
Rather than the responsiveness computed artifact returning just the duration, it now returns the whole trace event, which will allow the attribution audit to use all the other properties on that same event.
Functionality is unchanged.
=> core(responsiveness): use raw trace event

lighthouse-core/audits/bootup-time.js, lighthouse-core/audits/long-tasks.js, lighthouse-core/audits/third-party-summary.js, lighthouse-core/lib/tracehouse/task-summary.js, lighthouse-core/test/lib/tracehouse/task-summary-test.js, tsconfig.json
part of #13916
The responsiveness debugging audit will be the fourth audit using these functions, so it's just about time we spin them off into their own file.
They're not quite `main-thread-task` functions, nor are they just about `task-groups`, so a new file seemed appropriate. I'm not attached to their new location, however, so I'm happy to bikeshed.
=> core: extract BootupTime task summary methods

report/renderer/performance-category-renderer.js, report/test/renderer/performance-category-renderer-test.js
part of #13916
@adamraine convinced me in that issue that we should just use `scoreDisplayMode` `notApplicable` to allow metrics to declare themselves not-applicable, but (unlike all other audits) still be displayed in the report. This allows for "optional" metrics like responsiveness to correctly appear in timespan reports, even if there were no interactions in that timespan.
I still think there's a chance we won't want to eliminate the only way audits can dynamically remove themselves from the report, but that chance seems very slim since we've never done this with a metric before in the four years since metric rendering was changed much, and I think we'll still be able to change our minds without really breaking backwards/forwards compatibility with report rendering.
All that said: how …
=> report: render notApplicable metrics with double dash

lighthouse-core/audits/work-during-interaction.js, lighthouse-core/config/metrics-to-audits.js, lighthouse-core/fraggle-rock/config/default-config.js, lighthouse-core/test/audits/work-during-interaction-test.js, lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-navigation-expected.txt, third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
part of #13916 
Breaks down the tasks occurring during the INP event. Tests are very light, still working on them
Example report: https://lighthouse-ddszazj4j-googlechrome.vercel.app/gh-pages/viewer/?gist=0b9f538660fe83c57c94acb5b6a04be0
=> new_audit: add work-during-interaction diagnostic

lighthouse-core/audits/work-during-interaction.js, lighthouse-core/test/audits/work-during-interaction-test.js, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
Apparently the middle phase of INP got switched from "processing delay" to "processing time" in the [web.dev/inp explainer](https://web.dev/inp/#:~:text=event%20handlers%20execute.-,The%20processing%20time,-%2C%20which%20is%20the), and I've been told that enough time went into discussing the change that Lighthouse should use the same nomenclature to keep things consistent :)
=> misc(inp): switch proccessing "delay" to "time"

clients/extension/scripts/popup.js, flow-report/src/util.ts, lighthouse-cli/test/fixtures/byte-efficiency/tester.html, lighthouse-cli/test/fixtures/delayed-fcp.html, lighthouse-cli/test/fixtures/delayed-lcp.html, lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/fixtures/perf/level-3.js, lighthouse-cli/test/fixtures/perf/preload_tester.js, lighthouse-core/test/fixtures/fraggle-rock/snapshot-basic/onclick.html, lighthouse-core/test/lib/page-functions-test.js, report/renderer/category-renderer.js, report/renderer/crc-details-renderer.js, report/renderer/details-renderer.js, report/renderer/dom.js, report/renderer/element-screenshot-renderer.js, report/renderer/performance-category-renderer.js, report/renderer/pwa-category-renderer.js, report/renderer/report-renderer.js, report/renderer/snippet-renderer.js, treemap/app/src/util.js, viewer/app/src/lighthouse-report-viewer.js
Fixes #13991 
Replaces all .appendChild() occurrences with .append().
=> misc: replace appendChild with append

.github/workflows/smoke.yml
Adds sharding to the FR, bundled and windows smoke tests. This should further reduce the headache of re-running flaky tests, and speed things up a bit.
=> tests(ci): shard all smoke tests

.github/workflows/smoke.yml
~I went out of my way to get a windows cloudtop, and reproduced our windows smoke failures on that, but it only happened the first time. I can't repro anymore 🙃~
I can consistently repro the CI failures on the windows cloudtop.
Theoretically, a bump in the retries will do the same for CI though so let's see what happens...
=> tests(smoke): increase windows retries

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js, lighthouse-cli/test/smokehouse/test-definitions/screenshot.js, lighthouse-core/gather/gatherers/image-elements.js
=> core(image-elements): use execution context isolation

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-core/gather/driver/execution-context.js, lighthouse-core/gather/gatherers/iframe-elements.js, lighthouse-core/gather/gatherers/image-elements.js, lighthouse-core/lib/page-functions.js, lighthouse-core/test/lib/page-functions-test.js, types/externs.d.ts
Fixes #14001.
The issue was due to a conflict with an overridden `HTMLElement.prototype.getBoundingClientRect` present on the page in the bug report. This fix saves a reference to the native function and uses it across.
=> core: save native getBoundingClientRect to avoid overrides

lighthouse-core/test/config/config-helpers-test.js
The test overwrites `process.cwd` but never restores it.
Also, the `process` global is special, being injected into the scope of every module and not necessarily going through the require/import process (so can't be mocked with jest.mock that way unless the module under test explicitly imports it, which we don't). So I removed the usage of `jest.mock`.
=> tests(config-helpers): restore process.cwd after mocking

flow-report/src/topbar.tsx, flow-report/test/topbar-test.tsx
Instead of mocking a module, do dependency injection. This is necessary for #14054 because testdouble loader conflicts with the esm loader necessary for tsx files.
=> tests(topbar): replace module mock with dependency injection

lighthouse-core/gather/gatherers/source-maps.js
Found another [one](https://sentry.io/organizations/google-lighthouse/issues/2666708562/events/dce9189eaa854297aa70e7b972256ec1/?project=174697#exception) from sentry. (btw it looks like theres only 3 actual JS errors in there. and this is 2 out of 3)
`lighthouse https://video.ebscohost.com/results?q=climate%20change -GA`
That page loads [this JS file](https://cmp.osano.com/169lTOSNzFFdw20EN/adcab978-e7bd-469a-a9fd-6fa5f686ea58/osano.js) which references [this map](https://cmp.osano.com/169lTOSNzFFdw20EN/adcab978-e7bd-469a-a9fd-6fa5f686ea58/osano.js.map), which is just a `{}`. It is missing 3 field required by the spec. 
But we werent validating these fields are present, leading to a `Cannot read properties of undefined (reading 'length')` on here: …
=> core(source-maps): throw explicit error when map is missing required fields

lighthouse-core/gather/driver.js
While investigating #13861, I noticed that the legacy runner takes a long time on the oopif-scripts.html smoke fixture. This is because the OOPIF target _hangs forever_, and is never loaded. This was made clear when the second iframe on the test page never rendered any content.
Turns out, we can't do `Network.enable` and await its response if the target is paused.
It _seems_ like the `iframe` specific part of `_handleTargetAttached`  may have always been busted? It's also possible that Chrome CDP internals changed underneath us.
I also added a clarifying comment in `_handleTargetAttached` noting that all that logic is only for OOPIFs.
=> core(driver): fix legacy runner hanging oopifs in some cases

build/build-lightrider-bundles.js
Confirmed working in the LR demo app.
Originally changed to rollup in #13416, but apparently never tested.
=> misc(build): fix lightrider report generator bundle

lighthouse-core/gather/connections/cri.js
Spotted this in the chrome process stderr output:
> `ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb POST to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.`
It's from a month-old CL: https://chromium-review.googlesource.com/c/chromium/src/+/3595822
from what i can tell, this only affects our non-FR launches. (aka `--legacy-navigation`)
=> core(cdp): update HTTP method for /json/new call

lighthouse-core/fraggle-rock/gather/session.js, lighthouse-core/test/fraggle-rock/gather/session-test.js
Added in #11995, we actually don't need this (anymore? maybe something changed? idk). We can listen to the `*` event to listen to all protocol events.
It wasn't meant to stick around according to https://github.com/GoogleChrome/lighthouse/pull/12074/files#r573963923 but shrug.
=> core(fr): do not monkey patch puppeteer session.emit

build/build-report.js
We're in a funny situation, so here's the backstory...
1. we want the swapLocale functionality in PSI
1. our PSI integration story uses the bundle.umd.js + a .d.ts declaration file
* we use report/bundle.esm in devtools and report/bundle.umd in PSI. because reasons.
1. the declaration file is created via `node ./node_modules/.bin/tsc --allowJs --declaration --emitDeclarationOnly ./dist/report/bundle.esm.js` <== the ESM version!
* yes we generate types from the build that we don't use. we can't gen types from the umd one anyway
1. the esm and umd report builds are slightly different and that hasn't mattered much until recently. i shimmed swaplocale/format with `{}` for devtools to save 30kb. 
3. however for the correct type generation we need those to look reasonable
4. thus, this silly PR …
=> clients(psi): expose the swapLocale types

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js, lighthouse-cli/test/smokehouse/test-definitions/screenshot.js
Should fix the CI failures on ToT
---
context: Chrome UserAgent is dropping all but major version information
https://twitter.com/rowan_m/status/1528728452949594113
=> tests(smoke): use major milestone

lighthouse-core/gather/driver/network-monitor.js
Related to #14078. In the legacy driver, we are already handling targets via the [event handlers](https://github.com/GoogleChrome/lighthouse/blob/f0c2f84d5d7cfd7d558582872de9c8d7f666e9dd/lighthouse-core/gather/driver.js#L72) added in the constructor. Let's not complicate things in legacy mode by doing target management in a second place (only the NetworkMonitor is what creates a TargetManager in legacy mode).
=> core(driver): do not use target manager in legacy mode

build/build-lightrider-bundles.js
from my too-late [comment in #14031](https://github.com/GoogleChrome/lighthouse/pull/14031/files#r891701219). We shim `fs` this way for the [standalone report umd bundle](https://github.com/GoogleChrome/lighthouse/blob/e84549bc51672958a48347d31b6476d1863c65d7/build/build-report.js#L126), can do the same thing here. Still a workaround, but a little less finicky.
=> misc(build): shim fs out of lightrider report generator bundle

lighthouse-core/gather/driver/wait-for-condition.js, types/lighthouse-logger/index.d.ts
We do _a lot_ of logging on network events when there is <20 inflight. This can be a lot of string operations that are just done for naught if the logging isn't verbose. so I added a simple check to avoid that.
=> core(driver): guard verbose logic behind log.isVerbose check

lighthouse-core/gather/gatherers/devtools-log.js
This isn't necessary for our runtime, but is very useful for debugging. And the overhead is very small.
Here's the JSON size per domain of all the domains (for a run on the oopif-requests page):
```
Page:      11,529
Network:  660,047
Runtime:      588
Target:       980
Debugger:  14,559
Audits:     2,433
Tracing:  828,424
```
=> core(devtoolslog): include Target and Runtime domains

lighthouse-core/fraggle-rock/gather/driver.js, lighthouse-core/fraggle-rock/gather/session.js, lighthouse-core/gather/driver.js, lighthouse-core/gather/driver/network-monitor.js, lighthouse-core/gather/driver/target-manager.js, lighthouse-core/test/fraggle-rock/gather/mock-driver.js, lighthouse-core/test/fraggle-rock/gather/session-test.js, lighthouse-core/test/gather/driver/target-manager-test.js, types/gatherer.d.ts
Improve understandability of `target-manager` (re: #14078) by moving the `sessionattached` listener into TargetManager itself. There's no functional change, but this means TargetManager is only in the business of creating FRSessions, not interoperating with them, which opens up further flexibility in the future.
=> core: handle sessions inside target-manager

lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
from chat:
replacing strings literally in JS is actually pretty not straightforward. Worse, it will work in like 99% of cases until it doesn't. See:
```js
const replaceWith = 'Dollar: \'$\');';
console.log('REPLACE'.replace('REPLACE', replaceWith));
```
this prints Dollar: '); ... note the missing dollar sign ... because the replace function is "regex-aware" even if the first parameter is not a regex ...
only valid for $' and $`. the others ($0, $1) don't work
so you must do this:
```js
'REPLACE'.replace('REPLACE', () => replaceWith);
```
_____
After auditing all our usages of `String.prototype.replace`, I only found this one instance where it _could_ theoretically be problematic.
=> i18n: replace placeholder using replacer callback

lighthouse-core/gather/gatherers/scripts.js
The gatherer only wants network requests from the main session, and it ends up narrowing down to only handling `Debugger.scriptParsed` events. Rather than listening to the firehose of all events and narrowing to both requirements, it can instead listen just for `Debugger.scriptParsed` directly on the main session.
As the only other consumer of `session.addProtocolMessageListener()` besides `network-monitor`, removing this also makes the refactors for #14078 a bit simpler.
=> core(scripts): narrow to only listen to parsed events

build/changelog-generator/templates/header.hbs, changelog.md
**Summary**
"Full Changelog" links of changelogs are broken since v9.3.0.
* changelog.md
* [9.5.0](https://github.com/GoogleChrome/lighthouse/blob/master/changelog.md#950-2022-03-09)
* [9.4.0](https://github.com/GoogleChrome/lighthouse/blob/master/changelog.md#940-2022-02-16)
* [9.3.1](https://github.com/GoogleChrome/lighthouse/blob/master/changelog.md#931-2022-01-31)
* [9.3.0](https://github.com/GoogleChrome/lighthouse/blob/master/changelog.md#930-2022-01-31)
* GitHub Release pages
* https://github.com/GoogleChrome/lighthouse/releases/tag/v9.6.2
* https://github.com/GoogleChrome/lighthouse/releases/tag/v9.6.1
* https://github.com/GoogleChrome/lighthouse/releases/tag/v9.6.0
* https://github.com/GoogleChrome/lighthouse/releases/tag/v9.5.0
* …
=> misc: fix broken links in changelog

.github/workflows/package-test.yml, .github/workflows/smoke.yml
https://github.com/GoogleChrome/lighthouse/issues/14099
https://github.com/GoogleChrome/lighthouse/pull/14100 made the test more specific which is good, but it also made the test fail more often. This is probably our the same underlying issue as `perf-diagnostics-third-party` so I think we should disable (on FR only) until a CDP solution lands.
=> tests(smoke): disable `oopif-requests`

.github/workflows/package-test.yml, .github/workflows/smoke.yml
I've had enough, `oopif-scripts` can go to. Will bring back as part of https://github.com/GoogleChrome/lighthouse/issues/13861.
=> tests(smoke): disable `oopif-scripts` in FR

lighthouse-core/fraggle-rock/gather/session.js, lighthouse-core/gather/driver/network-monitor.js, lighthouse-core/gather/driver/target-manager.js, lighthouse-core/lib/network-recorder.js, types/protocol.d.ts
Part of #14078
Like with `session` in #14147, moves `NetworkRecorder` and `NetworkMonitor` from having event emitters to being event emitters.
Normally composition is 🥇, but in this case it was just requiring us to declare delegation methods to have equivalent functionality. Technically inheritance now, but functionality is disjoint, so let's just call it a mixin still :)
No functionality or test changes.
=> core: move network recorder and monitor to EventEmitter

lighthouse-cli/test/smokehouse/test-definitions/perf-trace-elements.js, lighthouse-core/audits/preload-lcp-image.js, lighthouse-core/lib/dependency-graph/network-node.js, lighthouse-core/test/audits/preload-lcp-image-test.js, lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
In an effort to better quantify when LCP images should be preloaded (and what kind of performance improvements you'd see), we need richer debugData from the preload-lcp-image audit to query in the next HTTP Archive dataset.
This PR makes the full initiator chain to LCP image available (missing from `critical-request-chains` if any resource in that chain isn't critical), including the initiator type, which is important for assessing how the resource got put into the page at that particular network hop.
Only change is to `debugData`, no visible audit changes.
=> core(preload-lcp-image): enrich debugData

lighthouse-core/scripts/roll-to-devtools.sh, third-party/devtools-tests/README.md, third-party/devtools-tests/e2e/lighthouse/BUILD.gn, third-party/devtools-tests/e2e/resources/lighthouse/BUILD.gn
Unlike with webtests, e2e tests specify each test file in `BUILD.gn` for devtools build system. So we'll need to sync these files otherwise a mismatch in test files will result in build errors / tests not running.
=> tests: sync BUILD.gn files for devtools e2e tests

lighthouse-core/lib/lantern-trace-saver.js
Incidental to #14166. `finishTime` needs to both start at `baseTs` and to be in seconds.
before
after
=> misc(lantern-trace-saver): fix request finishTime

lighthouse-core/scripts/i18n/collect-strings.js
Fixes this error on master:
```
====
Collecting strings from C:\Users\cjamc\code\lighthouse/lighthouse-core
====
Collecting from lighthouse-core/audits/accessibility/accesskeys.js
Waiting for the debugger to disconnect...
node:internal/errors:465
ErrorCaptureStackTrace(err);
^
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
at new NodeError (node:internal/errors:372:5)
at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
at defaultResolve (node:internal/modules/esm/resolve:1200:3)
at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
at …
```
=> i18n: fix collect-strings on windows with pathToFileURL

lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js, lighthouse-cli/test/smokehouse/lighthouse-runners/devtools.js, lighthouse-cli/test/smokehouse/smokehouse.js, lighthouse-core/scripts/pptr-run-devtools.js, types/smokehouse.d.ts
Split out from https://github.com/GoogleChrome/lighthouse/pull/14199 since this should benefit our smokes on macos as well.
See my comments in https://github.com/GoogleChrome/lighthouse/pull/14199#pullrequestreview-1034763811 for the highlights.
=> tests(smoke): use DevTools runner through node directly

docs/user-flows.md
It seems that the representations in the images do not match each other.
**Changes**
- I exchanged images of Timespan and Snapshot in user-flows.md.
=> docs(user-flows): fix the order of the mode thumbnail images

core/computed/main-thread-tasks.js, core/lib/tracehouse/main-thread-tasks.js, core/test/computed/main-thread-tasks-test.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/lib/tracehouse/main-thread-tasks-test.js, core/test/results/sample_v2.json
addresses the first half of #14226, putting the hidden `main-thread-tasks` audit start times on the same timeline as e.g. the hidden `metrics` diagnostic audit timestamps.
After this change there will be tasks with negative start/endTimes returned from `getMainThreadTasks()`. There's no larger effect because no code touches the task start/endTimes except for the hidden `main-thread-tasks` diagnostic audit. All other audits that use `getMainThreadTasks()` just use the task durations.
A full fix for #14226 will (probably) remove any tasks happening before the time origin from those summary audits, but this change has no effect on those audits.
=> core: use trace time origin for main-thread-task time origin

core/audits/network-requests.js, core/test/audits/network-requests-test.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json
Like #14252, this allows comparing two hidden debug audits with slightly different time origins.
The `network-requests` hidden audit uses the first network request start time as time zero, and [emits all network timestamps relative to that point](https://github.com/GoogleChrome/lighthouse/blob/6786a5931903ee2ee63e3c9f9799b6097e999e2d/core/audits/network-requests.js#L51-L52) in the LHR.
This is fine for most purposes, unless you want to compare network request times to metric timestamps, which use navStart as a time origin. navStart and the first networkRequest are usually very close (a few milliseconds...trace events are `navigationStart` and the following `ResourceWillSendRequest` with the same `requestId` as the navStart's `navigationId`), but not simultaneous.
Rather than add the trace …
=> core(network-requests): include starting timestamp as debug data

cli/test/smokehouse/readme.md, cli/test/smokehouse/report-assert-test.js, cli/test/smokehouse/report-assert.js, cli/test/smokehouse/test-definitions/dobetterweb.js, cli/test/smokehouse/test-definitions/screenshot.js
Chrome execution context ids just changed under us again, so instead of adding *another* chrome version case we can change our smoke assertions to be more flexible.
This allows us to check the `Object.entries` of an object using `_includes` and `_excludes`.
=> tests(smoke): check objects against a subset of keys

cli/run.js
https://docs.google.com/document/d/1hEt6q0BlZ1c50UNhm9ejXNKLvcOX8pStspCY6hAKwDI/edit# (can just read the most recent update, pasted below).
> The issue was my Node was built for x64 and when you spawn a process from x64, apparently Apple just assumes that it needs to be translated so it uses its Rosetta tech to do that. In chrome://version I see x86_64 translated when that happens, and get ~10x perf regressions.
______
This PR fixes (well, at least warns about) `yarn smoke perf-preload` on my machine.
For pretty much any CLI invocation – (spawning chrome from my x64 Node install...apparently 14.20 is only distributed as x64 via nvm. arm64 only became a thing sometime in 15.x) – Chrome would get "translated" to some weird hybrid x64->arm64 binary (even tho the Chrome install is already …
=> cli: throw error if running x64 node on mac arm64

third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Couple things need to change upstream, but we'll just handle that on the next roll.
=> tests(devtools): add i18n to e2e navigation test

core/fraggle-rock/replay/stringify-extension.js, core/test/fraggle-rock/replay/__snapshots__/stringify-extension-test.js.snap, core/test/fraggle-rock/scenarios/__snapshots__/stringified-replay-test-pptr.js.snap
Kinda shot myself in the foot by merging #14146 and #14050 at the same time. Anyway unit tests started failing at this should be the fix.
=> core(replay): fix stringify extension

docs/performance-budgets.md
Our docs don't make it clear that budgets can be defined on the config, and they're not just a CLI option.
This should hopefully clear that up for Node API / flow API users.
=> docs(budgets): add example using config

cli/test/fixtures/static-server.js
fixes #14302
not trying to get fancy. these are pretty unique ports.
=> tests: static-server can continue if already running

cli/test/smokehouse/report-assert.js
if LH failed to run and only produced a runtimeError, then this function errors during assertion report creation, and prevents the LHR from being printed.
with this change the LHR will actually be printed when it's seen to fail the assertions.
=> tests(smoke): check lhr.environment exists in version check

build/build-report.js, report/test-assets/faux-psi-template.html, report/test-assets/faux-psi.js, shared/localization/format.js
The key thing here is the tweak in build-report.
The changes in faux-psi is just for a more realistic setup of faux-psi.  These changes aren't critical as i'm basically the only user of this mini webapp. :)
=> clients(psi): expose hasLocale in bundle types

cli/test/smokehouse/test-definitions/perf-trace-elements.js, core/audits/lcp-lazy-loaded.js, core/audits/preload-lcp-image.js, core/gather/gatherers/trace-elements.js, core/test/audits/largest-contentful-paint-element-test.js, core/test/audits/lcp-lazy-loaded-test.js, core/test/audits/preload-lcp-image-test.js, core/test/gather/gatherers/trace-elements-test.js, core/test/results/artifacts/artifacts.json, core/test/results/sample_v2.json, types/artifacts.d.ts
The LCP trace event reports if it was text or an image, which we can use to make tricky image cases easy.
This updates the two LCP image debug audits to use the LCP `type` information to mark themselves `notApplicable` if the LCP was text, even when `ImageElements` says otherwise due to url matching issues (#13338).
The change should be straightforward, but the commits separate the gatherer and audit changes to make it a little easier to review.
=> core(trace-elements): include LCP type in artifact

third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3876583
=> tests(devtools): sync e2e tests

.github/workflows/unit.yml, core/test/runner-test.js, yarn.lock
ref https://github.com/testdouble/testdouble.js/issues/498#issuecomment-1239750218
Restores 16.17+ support #14345 (also, latest 18.x wrt the loader api)
=> deps: update quibble fork to work with new loader api

cli/cli-flags.js, cli/test/cli/cli-flags-test.js
=> cli: error early if --output-path is invalid

core/gather/driver/execution-context.js, core/gather/gatherers/accessibility.js, core/gather/gatherers/anchor-elements.js, core/gather/gatherers/dobetterweb/domstats.js, core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js, core/gather/gatherers/full-page-screenshot.js, core/gather/gatherers/iframe-elements.js, core/gather/gatherers/image-elements.js, core/gather/gatherers/inputs.js, core/gather/gatherers/link-elements.js, core/gather/gatherers/meta-elements.js, core/gather/gatherers/script-elements.js, core/gather/gatherers/seo/embedded-content.js, core/gather/gatherers/seo/tap-targets.js, core/gather/gatherers/trace-elements.js, core/lib/page-functions.js, core/test/gather/driver/execution-context-test.js, core/test/gather/gatherers/accessibility-test.js
All but one of these can be dropped just by using their function directly.
`getNodeDetails` is special because it has a number of other page-functions that must be included to work, which was solved by making its `*String` export wrap those deps (so callers wouldn't have to remember to). Instead, ~I introduce `ExecutionContext.serializeDependencies` and `someFn.dependencies` to do the same.~ we set `toString`
=> core(page-functions): remove all `*String` exports

cli/test/cli/__snapshots__/index-test.js.snap, core/fraggle-rock/config/filters.js
This was a base artifact in legacy mode but it's a normal artifact in FR.
It wasn't being run because no audits depend on it. This PR avoids the audit dependency filter for this artifact.
=> core(fr): always run NetworkUserAgent gatherer

core/runner.js, core/test/runner-test.js
Added in #11509, but undone in #11519
I think it was undone because it was adding unwanted lhr files from runner-test. However... I don't see that happening anymore?
This is very useful because `-GA` gathering takes too long when you just want to iterate on audit code, and it's simple to just look at this lhr.report.json file.
=> core: save lhr to latest-run/ for -A, not just -GA

report/renderer/element-screenshot-renderer.js
=> report: remove extra space from screenshot preview

build/build-report.js, flow-report/src/i18n/i18n.tsx, flow-report/test/flow-report-pptr-test.ts, report/generator/report-generator.js
This regressed in b7658 because the extension in the build script was modified without changing the way the mocked module was being imported.
I added a test to prevent this in the future.
Also, a drive-by fix for the flow report generation when `terser` is not in use (I disabled it while debugging, and was confused when the pptr tests failed to parse the HTML...). The fix is exactly the same for what's done for the standalone report.
=> report(flow): fix ui strings not being bundled

core/audits/accessibility/aria-meter-name.js, core/audits/accessibility/aria-tooltip-name.js, core/lib/i18n/README.md, core/scripts/i18n/collect-strings.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json, core/test/scripts/i18n/collect-strings-test.js, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json, tsconfig.json
There was a collision error when importing the latest strings to TC due to a difference in placeholders in `core/audits/accessibility/aria-meter-name.js | description` and `core/audits/accessibility/aria-tooltip-name.js | description`.
Chain of events:
- #12723 loosened collision restrictions since exact copies of messages aren't treated as collisions, they're deduped and treated as a single message. Notably in that PR I said ["I do have a lingering fear I'm missing something (some placeholder business or something?)"](https://github.com/GoogleChrome/lighthouse/pull/12723#issuecomment-871005403), which was, in fact, the case.
- Previously `aria-meter-name` and `aria-tooltip-name` had the exact same placeholders, so the error wasn't apparent. #14091 changed the Learn More links so they had …
=> i18n: handle string placeholder collisions

core/test/computed/metrics/cumulative-layout-shift-test.js, core/test/computed/metrics/largest-contentful-paint-all-frames-test.js, core/test/config/config-helpers-test.js, core/test/config/config-test.js, core/test/legacy/config/config-test.js
If these statements aren't `awaited`, the result of the promise has no impact on the test.
=> tests: add missing await on promise assertions

core/scripts/benchmark-plus-extras.js, core/scripts/update-flow-fixtures.js, core/test/scenarios/pptr-test-utils.js, types/global-lh.d.ts, types/puppeteer.d.ts
The types between these two packages are independent https://github.com/puppeteer/puppeteer/issues/9018
If we want to support both, we should use the union between them to ensure proper type safety.
Some scripts import puppeteer themselves but use the types in `LH.Puppeteer`. These scripts should now be using the types from whatever puppeteer they pull in.
=> core(types): use union of `puppeteer` and `puppeteer-core`

build/build-bundle.js, build/build-extension.js, build/plugins/inline-fs.js, build/plugins/rollup-plugin-inline-fs.js, build/test/plugins/inline-fs-test.js
I noticed this when I tried to run `yarn build-lr` in a clean checkout, which silently messes up because there is no `dist/report` so the JS inlining fails by simply emitting code that tried to read the file with `fs`. Instead, the plugin should throw a fatal error.
In doing this, I had to skip a case the plugin came across in `node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js`:
=> core(build): inline-fs error if file missing, ignorePaths

cli/test/smokehouse/test-definitions/a11y.js, core/audits/accessibility/bypass.js, core/audits/accessibility/th-has-data-cells.js, core/audits/accessibility/video-caption.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json, report/test/generator/report-generator-test.js, report/test/renderer/category-renderer-test.js
Part of https://github.com/GoogleChrome/lighthouse/issues/14354
=> core: make `bypass`, `th-has-data-cells`, and `video-caption` informative

core/legacy/config/config.js
Closes https://github.com/GoogleChrome/lighthouse/issues/13980
Ref
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3965275
=> core: remove deprecated flags check

core/test/user-flow-test.js, core/user-flow.js, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
Closes https://github.com/GoogleChrome/lighthouse/issues/14049
=> core(user-flow): i18n default names

core/audits/themed-omnibox.js, core/lib/manifest-parser.js, core/test/audits/splash-screen-test.js, core/test/audits/themed-omnibox-test.js, core/test/computed/manifest-values-test.js, core/test/lib/manifest-parser-test.js, package.json, yarn.lock
Fixes #9623
Was about to update the docs too, but it already says what we need it to 😆 
> Note that Lighthouse doesn't test whether the values are valid CSS color values.
=> core(manifest): remove css color verification

core/test/user-flow-test.js, core/user-flow.js, types/user-flow.d.ts
Sorry for the churn, we did have this option before #14388. However, the step flags object would completely override the flow flags even if there were settings defined on the flow flags that were not defined on the step flags.
This PR should handle the flow flags and step flags properly, by merging them together with step specific flags taking precedence.
=> core(user-flow): add base flags option

core/audits/layout-shift-elements.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
Closes https://github.com/GoogleChrome/lighthouse/issues/14462
=> core(layout-shift-elements): add link to documentation

core/user-flow.js
Merged 1s too early
https://github.com/GoogleChrome/lighthouse/pull/14455#discussion_r1001135616
=> core(user-flow): update UIString comments

docs/headless-chrome.md
**Summary**
This is a documentation fix as the xvfb-run command for headless chromium does not currently work.
This PR adds a trailing backslash to a multiline command.  Without the trailing backslash, the command is incomplete when pasted.
Output without the change looks something like this (There are other warnings that can be ignored):
```
/etc/chromium.d/README: line 1: Any: command not found                                                                                      
dpkg-query: no packages found matching bluealsa
[17369:17369:1027/092051.805408:ERROR:component_loader.cc(193)] Failed to parse extension manifest.
[17435:17435:1027/092052.296294:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is egl, ANGLE is …
```
=> docs: fix multiline xvfb-run command

cli/test/smokehouse/test-definitions/dobetterweb.js, core/audits/dobetterweb/dom-size.js, core/test/audits/dobetterweb/dom-size-test.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json
**Summary**
Fixes #14422 
I think this issue was caused by the changes in this [PR](https://github.com/GoogleChrome/lighthouse/pull/11563/files#diff-eea8149074228d97e9a32ada82e224c64e2176fb308133457a789c2fa44acb09R99)
=> core(dom-size): display metric values as integers

core/audits/csp-xss.js, core/test/audits/csp-xss-test.js, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
=> core(csp-xss): prevent meta warning if header CSPs are secure

cli/test/fixtures/max-texture-size.html, cli/test/smokehouse/core-tests.js, cli/test/smokehouse/test-definitions/fps-max.js, core/gather/gatherers/full-page-screenshot.js, core/lib/page-functions.js, core/test/gather/gatherers/full-page-screenshot-test.js
The screenshot was returning an empty string for the data on https://theverge.com
We are not limited by the max texture size (16384 on my macbook; but this is unrelated to Page.captureScreenshot) but we are limited by the [max web size of 16383](https://developers.google.com/speed/webp/faq#:~:text=the%20container%20specification.-,What%20is%20the%20maximum%20size%20a%20WebP%20image%20can%20be,image%20is%2016383%20x%2016383)
=> core(fps): limit height at max webp size

.github/workflows/cron-weekly.yml
This has been failing on `yarn install` lately :P 
also... looked into how we could get notifications on this cron failing and.... it's dumb: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs#:~:text=Notifications%20for%20scheduled%20workflows%20are%20sent%20to%20the%20user%20who%20initially%20created%20the%20workflow can only go to one person!
=> tests: fix node version in weekly cron

core/test/gather/driver/navigation-test.js, core/test/gather/driver/prepare-test.js, core/test/gather/gatherers/dobetterweb/response-compression-test.js, core/test/gather/gatherers/link-elements-test.js, core/test/gather/gatherers/script-elements-test.js, core/test/gather/gatherers/service-worker-test.js, core/test/gather/navigation-runner-test.js, core/test/gather/snapshot-runner-test.js, core/test/gather/timespan-runner-test.js, core/test/legacy/gather/gather-runner-test.js, core/test/runner-test.js, core/test/user-flow-test.js, docs/hacking-tips.md
Alternative to #14216. Instead of moving all our mocks to a separate file, we can err on the side of dynamic imports for everything that might depend on our mocked modules.
Basing this off of #14202 to see if this fixes the unit test issues there.
=> tests: dynamically import all modules when using mocks

build/build-bundle.js
This doesn't do anything anymore.
ref #14535
=> misc(build): remove non-functional package.json shim

cli/test/smokehouse/test-definitions/dobetterweb.js
This started breaking our smokes
=> tests(dbw): ignore `webkitStorageInfo` deprecation in m110

core/audits/byte-efficiency/uses-long-cache-ttl.js, core/audits/critical-request-chains.js, core/audits/is-on-https.js, core/audits/seo/is-crawlable.js, core/audits/user-timings.js
I came across these five remaining audits using `Promise.then` syntax and a long running indentation.
=> core: refactor audits to use async syntax

core/index.js
I think it would be useful to have these two at the top level api.
Ref https://github.com/GoogleChrome/lighthouse/issues/14048
=> core: expose default and desktop configs on `index.js`

proto/README.md
nice job with https://github.com/GoogleChrome/lighthouse/pull/14557 @adamraine 
this should sort out the docs. 
yay so glad for py3 compliance. makes all of this a bit less cranky.
=> docs(proto): update protobuf installation guidance

readme.md
Updates:
- DevTools UI screenshot
- Context for opening IO videos
=> docs(readme): update devtools screenshot, better alt

report/renderer/details-renderer.js, report/renderer/i18n.js
<details>
<summary> deferring table rendering stuff that we are _deferring_ to another PR </summary>
baseline perf of renderReport.. ~140ms JS plus rendering:
after deferring `renderTable`'s impl.. just 70ms of JS before FCP:
</details>
and then 
reusing formatters brings 120ms of table rendering down to 50ms:
that is renderReport being 50% faster!!!!!!!
=> report: reuse numberFormatters for ~50% performance gains

cli/test/smokehouse/lighthouse-runners/devtools.js, core/scripts/build-devtools.sh, core/scripts/open-devtools.sh, core/scripts/pptr-run-devtools.js, core/test/devtools-tests/download-devtools.sh, core/test/devtools-tests/roll-devtools.sh, core/test/devtools-tests/setup.sh
When pointing our build/run scripts to my local devtools checkout, I was surprised/annoyed how it blew out my existing Default build args. So let's use a specifically named build folder for our hacking here. Also made said folder configurable.
drive by: set use_goma if googler
=> misc: change default build folder for devtools gn

core/lib/dependency-graph/base-node.js, core/lib/dependency-graph/network-node.js
we got confused here https://github.com/GoogleChrome/lighthouse/pull/14567#discussion_r1034228708
lantern cpu nodes just use the trace event's `ts` value, which is microseconds. network node is multiplied to match
=> core(lantern): add comment to about node times being in microseconds

core/lib/dependency-graph/simulator/simulator-timing-map.js, core/lib/dependency-graph/simulator/simulator.js, core/lib/dependency-graph/simulator/tcp-connection.js, core/lib/lantern-trace-saver.js, core/test/lib/dependency-graph/simulator/tcp-connection-test.js
Adds network request timing breakdowns to lantern debug traces. When debugging simulator results (e.g. for debugging #14166), it can be really helpful to see time for DNS, connection, to get the first byte back, etc.
Because the changes are kind of thread through four different files, it might be helpful to look at individual commits (some general trace fixes, getting full node timings to the trace saver, and adding new timings to network nodes).
Changes have no effect on simulator functionality or results. Timings available to audits are unchanged, it's only the trace generator that has access to the full node timings.
---
Trace from main:
Trace from this branch:
For reference, the "real" (devtools-throttled) trace:
=> core(lantern): add network timings to debug traces

core/lib/third-party-web.js
I was tracking down why a [recent upgrade of the library](https://github.com/GoogleChrome/lighthouse/pull/14546) was losing one of the recognized entities, and in the process realized we aren't getting several entities that are in `entities.json`.
```javascript
const getEntityMerged = require('third-party-web').getEntity;
const getEntityHTTPArchive = require('third-party-web/httparchive-nostats-subset.js').getEntity;
console.log('result from merged entities: ',
getEntityMerged('https://mnl4bjjsnz-dsn.algolia.net/1/indexes/dev_OFFICE_SCENES/query'))
console.log('result in httparchive entities:',
getEntityHTTPArchive('https://mnl4bjjsnz-dsn.algolia.net/1/indexes/dev_OFFICE_SCENES/query'))
```
With 0.20.2, it outputs:
```shell
result from merged entities:  {
company: 'Algolia',
categories: [ …
```
=> deps: switch third-party-web dataset to entities-nostats subset

.github/workflows/ci.yml, .github/workflows/devtools.yml, .github/workflows/package-test.yml, .github/workflows/smoke.yml, .github/workflows/unit.yml
I remember seeing color output but .. havent seen it for a while.
This env var does flip it back on for mocha, yarn, smokehouse..  
afaik this is [supposed to come for free](https://github.blog/2020-09-23-a-better-logs-experience-with-github-actions/#opening-the-door-to-a-more-colorful-experience), but maybe it broke. shrug.
=> tests(ci): force color output in CI

clients/lightrider/lightrider-entry.js
=> clients(lr): expose computeBenchmarkIndex

core/index.js
Breaking part of #14547
Renames to be done in separate PRs
Ref https://github.com/GoogleChrome/lighthouse/issues/14048
=> core: internalize resolved configs

core/util.cjs, flow-report/test/sidebar/sidebar-test.tsx, report/renderer/util.js, report/test/renderer/util-test.js
=> report: fix wording when screenEmulation disabled

docs/user-flows.md
**Summary**
Updating the docs for User Flow to reflect the current release
- Change flow import path from `import lighthouse from 'lighthouse/core/api.js';` to `import {startFlow} from 'lighthouse/lighthouse-core/fraggle-rock/api.js';`
- remove `startNavigation`/`endNavigation`
- change interactive navigation with `startNavigation`/`endNavigation` to a callback navigation
- change `beginTimepsan` to `startTimespan`
Closes #14603
=> docs: update user-flow.md to reflect current release

core/test/devtools-tests/run-e2e-tests.sh, third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts, third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
Ever since https://github.com/GoogleChrome/lighthouse/pull/14492 our devtools e2e tests have been using the incorrect build folder. So we build DT with our changes but then test whatever DT ships in chrome.
=> tests(devtools): use correct build folder for e2e tests

cli/test/smokehouse/config/exclusions.js, cli/test/smokehouse/test-definitions/dobetterweb.js, core/scripts/pptr-run-devtools.js
Would be nice to have DT smoke coverage of https://github.com/GoogleChrome/lighthouse/pull/14465. Turns out it was pretty easy to get dbw working in the DT smoke runner.
=> tests(devtools): support dbw smoke

core/test/gather/driver/execution-context-test.js, core/test/gather/driver/navigation-test.js, core/test/gather/driver/prepare-test.js, core/test/gather/driver/service-workers-test.js, core/test/gather/driver/wait-for-condition-test.js, core/test/gather/gatherers/css-usage-test.js, core/test/gather/gatherers/image-elements-test.js, core/test/gather/gatherers/inspector-issues-test.js, core/test/gather/gatherers/js-usage-test.js, core/test/gather/gatherers/main-document-content-test.js, core/test/gather/gatherers/source-maps-test.js, core/test/gather/gatherers/trace-elements-test.js, core/test/gather/gatherers/trace-test.js, core/test/gather/session-test.js, core/test/legacy/gather/driver-test.js, core/test/scripts/run-mocha-tests.js, core/test/test-env/mocha-setup.js, flow-report/test/common-test.tsx
Moved all the invocations of `timers` into a scoped context (`describe`, typically).
=> tests: rewrite fake timer usage to reduce isolation

core/gather/gatherers/js-usage.js
Noticed this in JSUsage when using FR.
=> core(js-usage): ignore __puppeteer_evaluation_script__

core/gather/driver/execution-context.js, core/gather/driver/network-monitor.js, core/test/gather/driver/execution-context-test.js, core/test/gather/driver/navigation-test.js, core/test/gather/driver/network-monitor-test.js
https://github.com/GoogleChrome/lighthouse/issues/14662
=> core: replace `Page.getResourceTree` with `Page.getFrameTree`

cli/test/smokehouse/config/exclusions.js
https://github.com/GoogleChrome/lighthouse/issues/14271
This is happening way too much.
=> tests(smoke): disable `lantern-idle-callback-short`

cli/bin.js, cli/test/smokehouse/lighthouse-runners/bundle.js, cli/test/smokehouse/lighthouse-runners/cli.js, cli/test/smokehouse/lighthouse-runners/devtools.js, cli/test/smokehouse/smokehouse.js, core/config/config-helpers.js, core/config/config-plugin.js, core/config/config.js, core/config/validation.js, core/index.js, core/legacy/config/config.js, core/test/config/config-helpers-test.js, core/test/config/config-test.js, core/test/legacy/config/config-test.js, core/test/runner-test.js, core/user-flow.js, types/smokehouse.d.ts
https://github.com/GoogleChrome/lighthouse/pull/14547#issuecomment-1334527580
Type renames to be done in a follow-up.
=> core: use `config` to name every config json

core/util.cjs, report/renderer/util.js, report/test/renderer/util-test.js
=> report(devtools): fix wrong emulation string in meta block

core/gather/gatherers/accessibility.js, core/gather/gatherers/seo/tap-targets.js, core/legacy/gather/driver.js, core/legacy/gather/gather-runner.js, core/test/legacy/gather/fake-driver.js, core/test/legacy/gather/gather-runner-test.js
This functionality was never brought from legacy navs into FR so we should be consistent. Also, preserving the scroll position will at least be *less* destructive during flows (#14336).
Additionally, we don't need to restore the scroll position after *every* gatherer, only tap targets and a11y. [I've noticed some issues when we try to restore the scroll position immediately after the bfcache gatherer in legacy mode](https://github.com/GoogleChrome/lighthouse/actions/runs/3887332794/jobs/6633815689).
Moving the scroll position restoration inside the tap targets and a11y gatherers achieves both of these goals.
=> core(fr): preserve scroll position in gatherers

core/config/default-config.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json, report/renderer/performance-category-renderer.js, report/test/generator/report-generator-test.js, report/test/renderer/performance-category-renderer-test.js
ref #14565
#14586 updated with relevant things to update
Readable summary and FAQ coming.
-----------
=> core(scoring): rebalance perf metric weightings for v10

core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
~We don't know why #14667 passed green, but.. this is broken on main now.~
At the last commit of #14667, this number was 0.99.  In the meantime #14656 updated artifacts and this score went from 0.99 to 0.92.  (But with the new scoring (and new artifacts) the correct score is 0.90).
This snuck through cuz we don't have the 'enforce branch is up to date' setting on.
=> core(scoring): update expected perf score for flow fixtures

core/audits/byte-efficiency/render-blocking-resources.js, core/audits/uses-rel-preconnect.js, core/computed/metrics/lantern-metric.js, core/computed/metrics/metric.js, core/computed/metrics/timing-summary.js, core/computed/processed-navigation.js, core/gather/gatherers/trace-elements.js, core/test/computed/processed-navigation-test.js
(broken out from a larger change for easier review)
I'm generating some `ProcessedNavigation`s and it's really annoying to first make a `ProcessedTrace` every time, then pass that in to get a `ProcessedNavigation`. This change makes it so `ProcessedNavigation` generates its own dependency like a good computed artifact should.
=> core(processed-navigation): computed directly from trace

core/audits/bf-cache.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
https://github.com/GoogleChrome/lighthouse/issues/14586
=> core(bf-cache): link to chrome developer docs

core/runner.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json, proto/lighthouse-result.proto, types/lhr/lhr.d.ts
I did the rename in a branch off #14622; will merge back into branch once we are happy with the name changes.
If the rename looks good, I'll merge back to the branch. Compare with [changes including 14622 here](https://github.com/GoogleChrome/lighthouse/compare/entity-based-3p-reportonly-rename?expand=1).
=> rename entityClassification to entities in LHR.

core/config/metrics-to-audits.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json
Fixes https://github.com/GoogleChrome/lighthouse/issues/14722
=> report: filter `lcp-lazy-loaded` with LCP audits

.eslintrc.cjs, core/lib/page-functions.js
https://eslint.org/docs/latest/rules/no-cond-assign
I lost 30 minutes of debugging to this situation a few months back. (`=` instead of `===` in a conditional.) 
it now haunts me.
it's part of eslint:recommended, but `eslint-config-google` flips it back off: https://github.com/google/eslint-config-google/blob/master/index.js#L37
also.. the google config was archived last month! huh. bummer.
=> misc(lint): enable no-conditional-assignment rule

core/gather/gatherers/full-page-screenshot.js
This change seems to resolve an issue where _sometimes_ LH would produce element screenshots that did not line up (test w/ cnn.com). It was flaky behavior, so it's hard to know for sure if this is truly solved now. Please run a few times yourself. The `list` audit in a11y is what I was checking. If `user-sync` file is downloaded, trash the run and try again.
I ran this patch roughly 20 times with no incident, whereas before I could reproduce this problem at least twice every 5 runs.
=> core(full-page-screenshot): get screenshot, nodes concurrently

cli/test/smokehouse/test-definitions/perf-frame-metrics.js, core/audits/preload-lcp-image.js, core/gather/gatherers/trace-elements.js
Reverts the `s/processedNavigation.largestContentfulPaintEvt/processedNavigation.largestContentfulPaintAllFramesEvt` from #14695 and goes back to getting the LCP element from the main frame. Was not a bug, since that's where the LCP value comes from too.
Also added some comments and assertions to the frames smoke test for the next time I look at these lines and wonder, "wait, why aren't we looking at the all-frames LCP?".
=> core: use main-frame LCP trace element

third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
This was kinda subtle and e2e is flaky again so we missed it. Adding new translated strings corrected one of our e2e expectations.
=> tests(e2e): seek translated view trace button

build/build-lightrider-bundles.js
6c047772832f98b77718aa3cb9fefe877244e982 changed the report generator to es modules, which for _some reason_ results in rollup still including dependencies that had been DCE'd via `rollupPlugins.removeModuleDirCalls`. This PR explicitly shims the unneeded modules.
delta:
```
2,3c2,3
<   typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('module'), require('url'), require('path')) :
<   typeof define === 'function' && define.amd ? define(['exports', 'module', 'url', 'path'], factory) :
---
>   typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
>   typeof define === 'function' && define.amd ? define(['exports'], factory) :
```
Edit: previously: #13416 #14031 #14098 #14258
=> misc(build): shim unneeded deps in lr report generator

core/config/lr-desktop-config.js, core/config/lr-mobile-config.js
There are always failure reasons when testing bf-cache in headless mode. I can repro with Puppeteer so this is not specific to Lighthouse.
=> core(lr): disable bf-cache

cli/test/smokehouse/test-definitions/dobetterweb.js, cli/test/smokehouse/test-definitions/perf-trace-elements.js, core/audits/prioritize-lcp-image.js, core/test/audits/prioritize-lcp-image-test.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json
fixes #14300
As mentioned in #14804, using `graph.traverse()` gets you the shortest path through the dependency graph, which is often not what you want when looking at the resource discovery path to get to the LCP image. For example, if a resource was redirected, [the redirected resource has both the redirect source _and_ the redirect source's initiator as dependencies](https://github.com/GoogleChrome/lighthouse/blob/621e10c21972e94c15e1be7702eebecf1834def3/core/computed/page-dependency-graph.js#L153-L194), so the shortest path will always skip the redirect, which was obviously an important part of the resource's load path.
An alternative is to look at the longest dependency path from the resource to the main document ([critical request chains does …
=> core(prioritize-lcp-image): use request initiators for load path

core/lib/proto-preprocessor.js, core/test/lib/proto-preprocessor-test.js, proto/lighthouse-result.proto
=> misc(proto): add screenEmulation to configSettings

core/lib/network-recorder.js, core/test/lib/network-recorder-test.js, core/test/network-records-to-devtools-log-test.js, core/test/network-records-to-devtools-log.js
Ran into a weird case where a page refreshed itself via JS, Chrome fired and quickly cancelled (in less than a millisecond) a request for the page, then completed an h3 request for it. This _could_ match the description of how Chrome will optimistically make h3 requests in parallel to an h2 request, but AFAIK that should be invisible outside the network stack and we'd be seeing a whole lot more failed requests for any h3 sites if it were observable.
Regardless of the reason, having two requests for the page precede the successful h3 request makes the JS stack initiator URL ambiguous and so an `initiatorRequest` isn't set. A request that failed can't be the initiator, so instead it's one more case that can be ruled out.
---
Unfortunately, requiring `finished` and `failed` to be set exposed …
=> core: don't use failed network requests as potential initiators

docs/user-flows.md
This came up in https://github.com/GoogleChrome/lighthouse/issues/14791, and I've answered this question many times before in other issues/discussions. It's past time we added an official example to our docs.
=> docs(user-flows): add desktop config examples

cli/test/smokehouse/config/exclusions.js, core/scripts/pptr-run-devtools.js
DevTools tests were hanging forever because `primaryPageTarget` has replaced the `mainTarget` function.
=> tests(devtools): use new `primaryPageTarget` function

cli/test/smokehouse/test-definitions/redirects-client-paint-server.js, cli/test/smokehouse/test-definitions/redirects-history-push-state.js, cli/test/smokehouse/test-definitions/redirects-multiple-server.js, cli/test/smokehouse/test-definitions/redirects-scripts.js, cli/test/smokehouse/test-definitions/redirects-single-client.js, cli/test/smokehouse/test-definitions/redirects-single-server.js, core/audits/redirects.js, core/test/audits/redirects-test.js, types/artifacts.d.ts
Pages that do a js redirect to themselves (e.g. found pages doing some janky A/B testing that would reload after doing a sync XHR) were getting no feedback from the `redirects` audit because the audit was matching requests to navStarts by URL. Repeated navStarts to the same URL would always resolve to the first network request, so the audit would say the redirects took 0ms.
Instead, this PR looks at the navStart `navigationId`, which matches network requests' `requestId` for navigation requests.
Also adds redirect assertions to all the `redirect-*` smoke tests, because we don't have great trace fixture coverage of redirect cases, but we do have great smoke test coverage of them.
=> core(redirects): use requestId instead of URL to find requests

viewer/app/index.html, viewer/app/src/lighthouse-report-viewer.js, viewer/app/styles/viewer.css
I've been meaning to add a link to the ci diff tool (aka ci viewer) for a while now. 
* I did that
*  and updated the layout to hopefully be clearer. 
* Also measure.web.dev => PSI. 
* The entire landing div was a click target for selecting a file. I went for a more direct link. I think that's a more clear UI convention.
Before/after:
=> clients(viewer): rework landing with link to lhci diff tool

package.json, yarn.lock
`quibble` got some changes recently which should no longer require us to use my fork.
https://github.com/testdouble/quibble/pull/89
https://github.com/testdouble/quibble/pull/93
=> deps(testdouble): update, move off forked quibble

cli/test/smokehouse/config/exclusions.js
Fixes #14841 
I can't repro the error locally anymore on latest ToT, seems like the issue was resolved even if my bug report wasn't helpful.
Still need to verify on CI though.
=> tests(devtools): reenable `issues-mixed-content`

viewer/app/index.html
I published the lhci diff viewer at [/lighthouse-ci/difftool](https://googlechrome.github.io/lighthouse-ci/difftool/).
It's also still published at /lighthouse-ci/viewer
But I think it's a tad easier to only have one /viewer in our world. ;)
=> clients(viewer): link to diff tool's new URL

core/audits/seo/tap-targets.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
Part of https://github.com/GoogleChrome/lighthouse/issues/14006
I think it's fine to keep the audit description vague about what "have enough space around them" means. We should update the [docs](https://developer.chrome.com/docs/lighthouse/seo/tap-targets/) to remove the 8px note and talk about overlapping areas instead.
Docs PR: https://github.com/GoogleChrome/developer.chrome.com/pull/5590
=> core(tap-targets): update audit description

cli/test/fixtures/seo/seo-tap-targets.html
fixes #13557 
The failure was 
The case was these two elements: (zero width target and passing target)
In taptargets we take each target (eg zero width target) as a rect. then we place a hypothetical 48x48 finger at the center of the rect. Then we see how many pixels of overlap it has with the adjacent target (passing target)
Test said it should be 720 pixels of overlap area, but on a high dpi screen it was 696.  They're both right. 
In hidpi you can have fractional CSS pixels.. so.. a lot of things are 18.5px tall. And that ends up with a very similar but slightly off result in these rect overlap calculations.
Fixing it with a font-size on the body was a guess. I never understood [this whole thing](https://www.aleksandrhovhannisyan.com/blog/62-5-percent-font-size-trick/) but it probably …
=> tests: fix seo-tap-targets in high DPI

core/audits/byte-efficiency/uses-responsive-images-snapshot.js
Fixes https://github.com/GoogleChrome/lighthouse/issues/14888
Navigation mode will ignore CSS images for this audit. I consider this a byproduct of having 2 different implementations. Long term we should find a way to unify these two audits.
=> core(uses-responsive-images-snapshot): ignore CSS images

core/config/lr-mobile-config.js
Closes https://github.com/GoogleChrome/lighthouse/issues/14905
Removing audits completely is usually a breaking change, but this audit is not included in the default config. I'm still ok to defer the complete removal to 11.0 though.
=> clients(lr): remove FCP 3G from config

core/audits/byte-efficiency/byte-efficiency-audit.js, core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
Sometimes enacting an opportunity could actually regress performance and its audit could measure a negative `wastedMs`/`overallSavingsMs`. It turns out `byte-efficiency-audit` doesn't have any guard against this case and gives those results a `score` greater than 1, which triggers an [out-of-range score error](https://github.com/GoogleChrome/lighthouse/blob/90797a1e5fd4e0066a9906408d29e44c1c07b8f1/core/audits/audit.js#L340), and so what should be a passing result turns into an audit error.
This PR caps the `byte-efficiency-audit` score so negative savings still max out at a score of 1 and returns in a valid audit result.
For context, this doesn't happen often, e.g. ~0.09% for `prioritize-lcp-image` in the last HTTP Archive run and similar rates for the other `byte-efficiency-audit`s, but …
=> core: cap byte-efficiency-audit scores to a max of 1

cli/run.js
channel is always 'cli' although we set it to any value
**Summary**
=> cli: fix `--channel` flag

cli/test/fixtures/dobetterweb/dbw_tester.html, cli/test/fixtures/preload.html, cli/test/smokehouse/test-definitions/dobetterweb.js, cli/test/smokehouse/test-definitions/perf-preload.js, core/gather/gatherers/image-elements.js, core/gather/gatherers/link-elements.js, core/test/results/artifacts/artifacts.json, types/artifacts.d.ts, types/internal/node.d.ts
To support #13738, gathers the [`fetchpriority` hint](https://web.dev/priority-hints/) in the ImageElements and LinkElements gatherers. Not used yet, but asserted in smoke tests.
=> core: collect fetchpriority for images and link rel preload

core/audits/installable-manifest.js, third-party/chromium-synchronization/installability-errors-test.js
Unit tests start failing because this was removed.
https://chromium-review.googlesource.com/c/chromium/src/+/4402851
=> core(installability): deprecate scheme support warning

docs/puppeteer.md
In this PR:
Before this change, if someone ran the example, it would result in screenshots cropped to the browser window rather than the emulated viewport.
- #12988
=> docs: update pptr options example

lighthouse-logger/index.js, types/externs.d.ts
**Summary**
There is a missing log level between error and info which is simply `warn` to show just errors and warnings and nothing else. Very small and simple change required to add some better experience.
=> misc(logger): add warn level

core/computed/entity-classification.js, core/test/computed/entity-classification-test.js, report/test/renderer/details-renderer-test.js
Fixes #14996.
Previously, `chrome://` and `chrome-extension://` protocol URLs, as well as URLs that aren't part of devtoolsLogs would fail the audit. This change classifies all unknown as third party and groups them under "Unattributable".
With the _axe_ chrome extension that @adamraine faced an error in #14996, the report now would look like:
=> core(entity-classification): classify unknown urls as "unattributable"

shared/util.js
I was looking at report perf and this regex stood out: 
We already ran into this in #13785 (and fixed by https://github.com/GoogleChrome/lighthouse/pull/13791)
But.. theverge has a non-datauri URL that's 10kb long. and this nasty regex (my fault apparently) really doesn't enjoy working through such a big string.
=> report: avoid really slow regexes for long urls

core/gather/runner-helpers.js, core/test/fixtures/fraggle-rock/artifacts/step0/artifacts.json, core/test/fixtures/fraggle-rock/artifacts/step1/artifacts.json, core/test/fixtures/fraggle-rock/artifacts/step2/artifacts.json, core/test/fixtures/fraggle-rock/artifacts/step3/artifacts.json, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/artifacts/artifacts.json, core/test/results/sample_v2.json
This was just a cosmetic issue before but I noticed that we weren't generating `Timing` artifact entries for the `getArtifact` phase. Legacy navigation mode *was* generating `Timing` entries for `afterPass`.
| Before | After |
| ------ | ------ |
| ![Screenshot 2023-04-27 at 12 37 52 PM](https://user-images.githubusercontent.com/6752989/234973028-4ae1416b-fb49-4f13-90df-66ccaaa20d84.png) | ![Screenshot 2023-04-27 at 12 37 05 PM](https://user-images.githubusercontent.com/6752989/234972843-9d31eee5-62ac-4596-9193-ed6b07cf9f5a.png) |
Related:
https://github.com/GoogleChrome/lighthouse/discussions/14998
=> core: create timing entries for `getArtifact`

core/audits/predictive-perf.js
URL was going through as `undefined` here, but apparently didn't cause an error until #14941 landed (MainResource in the TTFB computed artifact ends up throwing for [lack of a `mainDocumentUrl`](https://github.com/GoogleChrome/lighthouse/blob/ecc76b8a41226f22d132ac37fbce3846e2559747/core/computed/main-resource.js#L23)).
Not noticed because we don't have smoke tests for predictive-perf, but predictive-perf is also not really intended for actually running, just for one-off testing runs 🤷 
Thanks to @benschwarz for reporting
=> core(predictive-perf): add URL as requiredArtifact

core/lib/stack-packs.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/lib/stack-packs-test.js
At some point we put some thought into the order of these stack packs, such that site generators will show up over frameworks like React (given that the advice is likely more relevant). However, we didn't actually make sure the end result of `lhr.stackPacks` is sorted as we thought. The order was implicit from how js-lib-detector detects libraries - we just need to do an actual sort based on our own ordering.
=> core(stack-packs): sort packs in order we defined them

core/gather/driver/wait-for-condition.js, core/test/gather/driver/wait-for-condition-test.js
**Summary**
Add extra warning to show inflight requests if the load timeout is reached.
The reason of this small and simple change is to give the user a better logging experience to know what's wrong.
=> core(driver): warn about remaining inflight requests urls

core/gather/gatherers/inspector-issues.js, core/test/audits/dobetterweb/inspector-issues-test.js, core/test/fixtures/fraggle-rock/artifacts/step0/artifacts.json, core/test/fixtures/fraggle-rock/artifacts/step1/artifacts.json, core/test/fixtures/fraggle-rock/artifacts/step3/artifacts.json, core/test/gather/gatherers/inspector-issues-test.js, core/test/results/artifacts/artifacts.json, third-party/chromium-synchronization/inspector-issueAdded-types-test.js, types/artifacts.d.ts
=> tests: rebaseline inspector issue detail types

core/test/gather/gatherers/accessibility-test.js, core/test/gather/gatherers/cache-contents-test.js, core/test/gather/gatherers/console-messages-test.js, core/test/gather/gatherers/dobetterweb/optimized-images-test.js, core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js, core/test/gather/gatherers/global-listeners-test.js, core/test/gather/gatherers/link-elements-test.js, core/test/gather/gatherers/seo/font-size-test.js, core/test/gather/gatherers/viewport-dimensions-test.js, core/test/network-records-to-devtools-log.js
In the same vein as https://github.com/GoogleChrome/lighthouse/pull/15047
Our tests should avoid testing gatherers via the legacy navigation methods.
Some tests still call `afterPass` for legacy compat reasons. These tests will be removed once the legacy runner is removed.
=> tests: remove most usages of `afterPass`

core/scripts/compare-runs.js, docs/readme.md
Was using this script to collect some traces from a mobile device...
```
node core/scripts/compare-runs.js --name motopower --collect -n 3 --lh-flags='--port 9223 --legacy-navigation --screenEmulation.disabled --throttling.cpuSlowdownMultiplier=1 --throttling-method=provided' --urls https://www.example.com https://www.nyt.com
```
and found that the lhArgs parameter is broken.
Also updated some stuff in readme about testing on mobile. It overlooked disabling network throttling, for some reason.
=> misc(compare-runs): allow for multiple args to lighthouse

core/computed/metrics/cumulative-layout-shift.js, core/gather/gatherers/trace-elements.js, core/test/gather/gatherers/trace-elements-test.js, types/artifacts.d.ts
Fixes https://github.com/GoogleChrome/lighthouse/issues/14919
=> core(trace-elements): use CLS metric event filtering

.eslintignore, .gitignore, lighthouse-logger/package.json
We need to do a patch release to restore cjs since the update today broke some folks downstream.
I packaged this logger and verified that chrome launcher passed all it's tests with it.
=> misc: add cjs path for logger

lighthouse-logger/package.json
https://github.com/GoogleChrome/lighthouse/issues/15085
Old node/npm clients (Node 10) don't support `exports` so the fix in 1.4.1 didn't resolve the issue. We don't support node 10 anymore, but we haven't done a breaking release on `lighthouse-logger` since dropping node 10 support.
`exports` takes precedence over `main` so newer clients will still access the ESM version if they can but old clients can fall back to the CJS version by default.
=> misc: support node 10 in lighthouse-logger

core/scripts/lantern/collect/golden.js, core/scripts/lantern/download-traces.sh
I wanted to experiment with configuring lantern based on the bidx of runs for our 2019 lantern data, but was missing the LHRs in the zips. I added them, might as well make it stick.
=> misc(lantern-collect): add median lhr to golden zip

core/gather/driver/target-manager.js, core/gather/gatherers/global-listeners.js, core/legacy/gather/driver.js, core/test/gather/driver-test.js, core/test/gather/driver/network-monitor-test.js, core/test/gather/driver/target-manager-test.js, core/test/scenarios/api-test-pptr.js, types/gatherer.d.ts
=> core(global-listeners): iterate all execution contexts

package.json, yarn.lock
https://github.com/patrickhulce/third-party-web/releases/tag/v0.21.0
https://github.com/patrickhulce/third-party-web/releases/tag/v0.22.0
Only relevant stuff seems to be new entities. A facade was incorrectly added and then removed.
=> deps: upgrade third-party-web to 0.22.0

report/renderer/category-renderer.js, report/renderer/dom.js, report/test/renderer/dom-test.js
This would be useful for external stack pack contributors.
=> report: append utm query params to stack pack links

core/lib/network-request.js, core/scripts/test-lantern.sh
Adds a comment and removes a conditional that is impossible to be true.
=> core(network-request): simplify recomputeTimesWithResourceTiming

cli/test/smokehouse/test-definitions/dobetterweb.js
Smokerider did not catch the error from #15075 because we have no smoke tests that check `largest-contentful-paint-element` with simulated throttling.
=> tests(smoke): add expectation for lcp-element

proto/lighthouse-result.proto
I picked a package name that seemed reasonable, open to suggestions if there are any preferences
Fixes #15115
=> misc(proto): add package name

readme.md
=> docs(readme): add unit test tips

core/audits/uses-rel-preconnect.js
=> core(uses-rel-preconnect): handle 0 connect start timings

core/lib/dependency-graph/simulator/network-analyzer.js, core/lib/network-request.js, core/test/lib/dependency-graph/simulator/network-analyzer-test.js
Use the value given in the `X-TCPMs` headers to estimate RTT in LR, and the `X-RequestMs` header for server response time.
=> core(network-analyzer): estimate from lrStatistics

third-party/devtools-tests/e2e/lighthouse/devtools-settings_test.ts, third-party/devtools-tests/e2e/lighthouse/navigation_test.ts, third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts, third-party/devtools-tests/e2e/lighthouse/start-view_test.ts, third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4543009
=> tests(devtools): remove parallel modifier from e2e tests

.github/workflows/ci.yml, .github/workflows/devtools.yml, .github/workflows/package-test.yml, .github/workflows/smoke.yml, .github/workflows/unit.yml, core/test/gather/gatherers/accessibility-test.js, docs/recipes/integration-test/example-lh-auth.test.js, flow-report/test/flow-report-pptr-test.ts, report/test/renderer/report-renderer-axe-test.js, treemap/test/treemap-test-pptr.js, viewer/test/viewer-test-pptr.js
Fixes yarn install failures:
https://github.com/GoogleChrome/lighthouse/actions/runs/5282937673/jobs/9558505341?pr=15176
=> tests(ci): skip puppeteer Chrome download

core/lib/lh-error.js, docs/recipes/type-checking/package.json
Fixes https://github.com/GoogleChrome/lighthouse/issues/15186
It's a pretty simple fix, but the `options` param on `Error` was first added in Node 16 which is our minimum node version. If someone encounters a type error like in #15186, is that just a sign that their ts target is too old for us to support?
=> core: support ts targets before es2022

cli/test/smokehouse/test-definitions/perf-preload.js
This audit being zero is a sign of a bug, which is the current behavior in PSI.
=> tests(smoke): expect server-response-time to be greater than 0

package.json, yarn.lock
https://github.com/patrickhulce/third-party-web/releases/tag/v0.23.1
https://github.com/patrickhulce/third-party-web/releases/tag/v0.23.2
https://github.com/patrickhulce/third-party-web/releases/tag/v0.23.3
New facade: https://github.com/karim-mamdouh/ngx-lite-video
Docs just landed: https://github.com/GoogleChrome/developer.chrome.com/issues/6683
=> deps: upgrade third-party-web to 0.23.3

core/audits/unsized-images.js, core/test/audits/unsized-images-test.js
Similar to #15099, we don't really have enough information to calculate the CLS impact of unsized images.
I imagine unsized images are responsible for much more CLS in the wild than non-composited animations, but I don't see us being able to do anything about it in the near future. 0 CLS impact should work fine.
We gave `unsized-images` a higher guidance ranking than `non-composited-animations`, so our sorting algorithm can always place `unsized-images` higher even though their impact scores are always the same.
=> core(unsized-images): add CLS savings as always 0

core/config/validation.js, core/test/config/validation-test.js
Follow up to https://github.com/GoogleChrome/lighthouse/pull/15209
Adds some validation that it is the legacy config but not the new one.
- `skipAudits`/`onlyAudits` is pretty straightforward, we just never added a check for this
- Duplicate artifact id checks is new. In legacy config, we would dedup gatherers but in the new config it's allowed to use the same gatherer for two different artifacts. This PR just verifies that the artifact ids don't overlap.
=> core(config): add more validation from legacy

core/config/config-helpers.js, core/config/filters.js, core/gather/gatherers/seo/font-size.js, core/lib/navigation-error.js, core/test/gather/fetcher-test.js
I did a dry run of removing the legacy runner. These places are using legacy code and/or types but don't need to.
=> core: update residual usages of legacy runner

core/test/gather/driver/execution-context-test.js, core/test/gather/driver/navigation-test.js, core/test/gather/driver/wait-for-condition-test.js, core/test/gather/gatherers/global-listeners-test.js, core/test/gather/gatherers/js-usage-test.js, core/test/gather/gatherers/source-maps-test.js, core/test/gather/gatherers/trace-elements-test.js, core/test/gather/mock-driver.js, core/test/lib/emulation-test.js
Follow up to https://github.com/GoogleChrome/lighthouse/pull/15047
Missed a few usages of legacy driver/connection in tests. This PR also reduces our usage of `mockCommands` directly, instead deferring to the mock `sendCommand`/`on`/`once` functions created on the mock session and mock driver.
#15060
=> tests: remove usages of legacy driver

core/lib/network-recorder.js, core/test/lib/network-recorder-test.js
Investigated some flaky `oopif-requests` failures:
https://github.com/GoogleChrome/lighthouse/actions/runs/5489241604/jobs/10003149170?pr=15231
If a request only has a `Network.requestWillBeSent` event we will still create a request for it, but we were not setting the `sessionTargetType` for that initial request.
=> core(network-recorder): set target type of unfinished request

cli/test/smokehouse/test-definitions/a11y.js
The exact target sizes vary depending on the device. For example, the failing target was 8px by 18px on my macbook.
=> tests(a11y): use regex for target size explanation

core/gather/base-gatherer.js, core/test/config/config-helpers-test.js, core/test/fixtures/valid-custom-gatherer.cjs, core/test/fixtures/valid-custom-gatherer.js
We use the old gatherer class in some config helpers tests. These tests are sticking around after legacy removal and can use the new base gatherer.
=> core: remove unnecessary references to legacy gatherer

core/audits/long-tasks.js, core/test/audits/long-tasks-test.js, core/test/fixtures/fraggle-rock/reports/sample-flow-result.json, core/test/results/sample_v2.json
The `long-tasks` audit lists the 20 longest tasks, attributed to specific URLs when possible. This makes sense in the HTML report, where these 20 are typically representative of the worst behavior, and any more would risk overwhelming any prioritization it provides.
However, when doing analysis using HTTP Archive, you often want _all_ the long tasks, to see where first and third parties are spending time when blocking the main thread. Meanwhile, you often want to see how time was spent during that task (all js? lengthy layout? etc), which today we only provide in aggregate in `mainthread-work-breakdown`, not per task or per URL (`third-party-summary` has yet another summary with slightly different information summed up per third-party URL).
This PR extends the `debugData` associated with …
=> core(long-tasks): add more task information to debugData

cli/test/smokehouse/test-definitions/issues-mixed-content.js
https://www.mixedcontentexamples.com/ is going 403 :/
This new site is linked in https://web.dev/fixing-mixed-content/.
=> tests(issues-mixed-content): use new site for testing

.github/workflows/package-test.yml, .github/workflows/smoke.yml, cli/test/smokehouse/frontends/smokehouse-bin.js, cli/test/smokehouse/lighthouse-runners/bundle.js, cli/test/smokehouse/lighthouse-runners/cli.js, cli/test/smokehouse/lighthouse-runners/devtools.js, cli/test/smokehouse/readme.md, cli/test/smokehouse/report-assert.js, cli/test/smokehouse/smokehouse.js, cli/test/smokehouse/test-definitions/errors-expired-ssl.js, cli/test/smokehouse/test-definitions/errors-infinite-loop.js, cli/test/smokehouse/test-definitions/oopif-scripts.js, clients/devtools/devtools-entry.js, core/scripts/pptr-run-devtools.js, types/internal/smokehouse.d.ts
Part of #15060
I wouldn't consider this breaking unless we're concerned about downstream consumers of smokehouse. Regardless, I expect the next release to be breaking.
=> tests(smoke): drop legacy support

lighthouse-logger/index.js, lighthouse-logger/package.json
We could keep CJS support with rollup the way it currently is. Unfortunately, esbuild doesn't handle the default export the way we want and requires a [workaround with a wrapper file](https://github.com/evanw/esbuild/issues/532#issuecomment-1019392638).
This PR also adds type compilation so we don't need to add an extra `lighthouse-logger.d.ts` in the main Lighthouse repo and also chrome launcher.
#14909
=> misc(logger): add types, remove cjs

readme.md
Add [PageVitals](https://pagevitals.com) to the list of integrations
> PageVitals combines Lighthouse, CrUX and real-user monitoring data to monitor the performance of websites. See how your website performs over time and get alerted if it gets too slow. Drill down and find the real cause of any performance issue. PageVitals is a paid product with a free 14-day trial.
=> docs(readme): add PageVitals to the list of integrations

cli/test/smokehouse/lighthouse-runners/bundle.js, package.json, yarn.lock
Once this and https://github.com/GoogleChrome/lighthouse/pull/15282 land we will only have 1 version of the logger installed.
=> deps: upgrade `chrome-launcher` to 1.0.0

core/gather/gatherers/scripts.js, core/gather/gatherers/source-maps.js, core/test/gather/gatherers/source-maps-test.js
Now that legacy runner is removed, it is possible to use artifacts *other* than DT log and trace as dependencies for other gatherers.
This PR uses `Scripts` as a dependency for `SourceMaps` so we don't have to collect 2 sets of script attached events and the calls to `Debugger.enable`/`Dubugger.disable` won't clobber each other.
=> core(source-maps): use `Scripts` as a dependency

CONTRIBUTING.md, docs/plugins.md, docs/readme.md
https://github.com/GoogleChrome/lighthouse/issues/15306
=> docs: remove references to `devtoolsLogs` and `traces`

core/config/default-config.js, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/results/sample_v2.json, report/test/generator/report-generator-test.js
Closes https://github.com/GoogleChrome/lighthouse/issues/15163
Happy to discuss these weightings. Main goal was to ensure best practices is not green (i.e. <90) if deprecations fail. I also felt that the https audit was important enough in this regard.
Others that could maybe increase weighting IMO:
- `errors-in-console`
- `inspector-issues`
- `no-unload-listeners`
=> core: re-weight best practices

core/scripts/legacy-javascript/package.json, dependabot.yml
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
There is no way to exclude certain subfolders (like legacy-javascript package.json). See https://github.com/dependabot/dependabot-core/issues/4364 . But we could at least move all those deps into devDeps which should exclude them from updates.
=> misc: add dependabot.yml

core/test/network-records-to-devtools-log.js
Our network records will never contain hashes, and so neither should our tests. This tripped me up over in https://github.com/GoogleChrome/lighthouse/pull/14520#discussion_r1019583406
=> tests: do not allow hashes in mock dt log

.github/workflows/unit.yml, core/test/scenarios/api-test-pptr.js, core/test/scenarios/pptr-test-utils.js, core/test/scenarios/start-end-navigation-test-pptr.js, core/test/scripts/run-mocha-tests.js, package.json
Unit failures are only happening in CI, failure artifacts might give us more insight. Retry unit tests 5 times to unblock CI.
CI failures added to backlog: https://github.com/GoogleChrome/lighthouse/issues/15382
=> tests(unit): retry failures and upload failure artifacts

core/index.cjs
Fixes https://github.com/GoogleChrome/lighthouse/issues/15386
=> core: fix `index.cjs` types

core/computed/viewport-meta.js, core/test/computed/viewport-meta-test.js
Fail audit if the viewport's `initial-scale` value is less than 1.
fixes #15266
=> core(viewport-meta): include initial-scale value condition

cli/test/smokehouse/test-definitions/redirects-single-server.js, core/audits/redirects.js, core/test/audits/redirects-test.js
Closes https://github.com/GoogleChrome/lighthouse/issues/14895
=> core(redirects): score only on wasted ms

report/renderer/i18n-formatter.js
We were showing way too much granularity here
let's reduce it to just tenths of whatever byte unit being used
=> misc(treemap): reduce granularity for byte values

core/gather/timespan-runner.js, core/test/gather/timespan-runner-test.js, core/test/scenarios/api-test-pptr.js, core/test/scenarios/pptr-test-utils.js, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
Part of https://github.com/GoogleChrome/lighthouse/issues/14775
=> core(timespan-runner): warn if a navigation is detected

treemap/app/index.html, treemap/app/src/main.js, treemap/types/treemap.d.ts, viewer/app/index.html, viewer/app/src/lighthouse-report-viewer.js, viewer/types/viewer.d.ts
=> misc: remove url hash to avoid gtm hang in treemap, viewer

cli/test/smokehouse/test-definitions/dobetterweb.js
This has been extremely flaky lately. I couldn't find any evidence of an actual issue here, so I think we can afford to me more lenient.
=> tests(dbw): remove upper bound for LCP load start/end

docs/readme.md
**Summary**
This PR fixes the chrome-launcher import in the first example of `docs/README.md`
This is a bugfix.
The module `chrome-launcher` doesn't appear to have a default export. You can test this on a blank node project by:
- Running `npm i chrome-launcher`
- Adding `"type": "module"` to package.json file.
- Writing `import chromeLauncher from 'chrome-launcher';` on an index.js file.
- Running `node index.js`
=> docs(readme): fix chrome-launcher import example

docs/running-at-scale.md
A partner wanted some high level guidance on this topic and I thought it'd make decent sense to have here in the repo.
Any high level thoughts before ya'll tear me apart in the details?
=> docs: add a guide to running Lighthouse at scale

cli/test/smokehouse/test-definitions/a11y.js, package.json, yarn.lock
https://github.com/dequelabs/axe-core/releases/tag/v4.8.1
This fixes a couple typos I spotted in the 4.8.0 release of axe-core. Since `target-size` is a hidden audit and this only affects the explanation message, I don't think it's worth it to do a patch release just for this on our end.
=> deps: upgrade `axe-core` to 4.8.1

docs/plugins.md, docs/recipes/lighthouse-plugin-example/readme.md
* Use `npm / npx` instead of `yarn`
* Use same name for plugin in plugins.md and the recipe
* add missing "type" field in package json
=> docs(plugins): minor corrections

.github/workflows/devtools.yml, cli/test/smokehouse/lighthouse-runners/devtools.js, cli/test/smokehouse/smokehouse.js, core/scripts/pptr-run-devtools.js
A lot of our flaky DevTools smoke failures are timeouts on the protocol command that waits for Lighthouse to finish ([example](https://github.com/GoogleChrome/lighthouse/actions/runs/6190447931/job/16806797771?pr=15201)). After some investigation, I discovered that the Lighthouse run never actually starts in these cases. For whatever reason, clicking the start button just once isn't 100% reliable.
This PR adds a loop that clicks the start button every 100ms until we detect the run has started via JS sniffer.
I also added some code that lets us view a screenshot of the DT frontend when a timeout occurs. This screenshot diagnostic is already used in DT e2e tests, and was super helpful for debugging this problem.
=> tests(devtools): ensure Lighthouse starts in smoke tests

cli/bin.js, core/lib/sentry.js, core/test/lib/sentry-test.js
1. Set useful things from the provided settings as tags, not extra. Only the form are queryable. Channel, form factor, and throttling method
2. Resolve settings from provided config and flags. This is normally only done inside core, but we repeat the same logic inside lib/sentry.js. If it fails, just ignore and fallback to using the provided flags -- core will handle the failure for us.
=> cli(sentry): set useful tags from resolved config

cli/test/fixtures/dobetterweb/dbw_tester.html, cli/test/smokehouse/test-definitions/dobetterweb.js, core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
This was one of the errors caught be sentry. A malformed link tag on https://www.iguaracu.pr.gov.br/index.php?mod=466&idConcurso=9 caused the main document request to be marked as render blocking. This is because an empty `href` attribute on a link tag gets resolved to the main document URL on `el.href`.
Since these malformed links do not actually request anything, they should not be considered render blocking.
=> core(tags-blocking-first-paint): ignore malformed link tags

.github/workflows/cron-weekly.yml
This is our only non-GitHub GHA action that wasn't pinned to a hash.
=> misc(ci): use commit sha for markdown action

.github/dependabot.yml
fixing that occasional error in the dependabot action.  it needed "directory"
i also added a thing to give us PRs when our gh actions deps  are outdated
=> misc: have dependabot check github actions deps

core/scripts/pptr-run-devtools.js, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/results/sample_v2.json
Related to https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4913655
These frontend globals are removed. Luckily we can still access pretty much everything via dynamic import statements
=> tests(devtools): remove usage of frontend globals

.github/dependabot.yml
I've seen this error on prs: https://github.com/GoogleChrome/lighthouse/pull/14915/checks?check_run_id=17444701281
we should use  'npm': https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
(also i SWEAR it told me to use yarn a week ago, but w/e)
=> misc: tweak dependabot ecosystem value

third-party/devtools-tests/e2e/lighthouse/devtools-settings_test.ts, third-party/devtools-tests/e2e/lighthouse/navigation_test.ts, third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts, third-party/devtools-tests/e2e/lighthouse/start-view_test.ts, third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4876325
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4854342
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4219119
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4839434
=> tests(devtools): sync e2e

report/renderer/performance-category-renderer.js
Fixes https://github.com/GoogleChrome/lighthouse/issues/15551
We could implement a `null` case within the explodey gauge, but then we would need a fancy way of displaying an erroneous metric arc which I don't think is worth it. Just showing a normal gauge that already handles this case should be fine.
=> report: use normal gauge if performance score is null

core/scripts/pptr-run-devtools.js
Related https://github.com/GoogleChrome/lighthouse/issues/14083
Protocol timeouts are happening a lot DT smokes for oopifs:
https://github.com/GoogleChrome/lighthouse/actions/runs/6579880151/attempts/2?pr=15554
The root cause is that Lighthouse never sees network quiet, and so Lighthouse waits for `maxWaitForLoad` before continuing.
The problem is that [`oopif-requests` defines `maxWaitForLoad`](https://github.com/GoogleChrome/lighthouse/blob/main/cli/test/smokehouse/test-definitions/oopif-requests.js#L28) to be longer the same a the [default puppeteer timeout of 180s](https://pptr.dev/api/puppeteer.browserconnectoptions/#properties). If Lighthouse spends 180s just waiting for load then the entire run is guaranteed to take longer than 180s. This PR extends the puppeteer timeout to 5 min …
=> tests(devtools): extend protocol timeout for load

core/config/constants.js, core/gather/driver/prepare.js, core/gather/driver/storage.js, core/gather/navigation-runner.js, core/test/fixtures/user-flows/artifacts/step0/artifacts.json, core/test/fixtures/user-flows/artifacts/step1/artifacts.json, core/test/fixtures/user-flows/artifacts/step2/artifacts.json, core/test/fixtures/user-flows/artifacts/step3/artifacts.json, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/gather/driver/prepare-test.js, core/test/gather/driver/storage-test.js, core/test/gather/navigation-runner-test.js, core/test/results/artifacts/artifacts.json, core/test/results/sample_v2.json, report/test-assets/lhr-3.0.0.json, report/test-assets/lhr-4.3.0.json, report/test-assets/lhr-5.0.0.json, report/test-assets/lhr-6.0.0.json, report/test-assets/lhr-8.5.0.json, treemap/app/debug.json, types/lhr/settings.d.ts
**Summary**
This commit adds a new option to the config to allow users to specify which storage types to clear when resetting storage for a URL. This is useful for testing scenarios where you want to clear all storage except for a specific type.
Test plan:
- Added a few unit tests to make sure the option works as expected
closes #15506
=> core: add `clearStorageTypes` option

clients/devtools/devtools-entry.js
Follow up to using new flag from #15494
This enables the flag to ignore fatal error status codes on Devtools by default.
=> clients(devtools): default to ignore fatal errors 

cli/test/smokehouse/test-definitions/dobetterweb.js
Looks like a recently added deprecation:
https://github.com/GoogleChrome/lighthouse/actions/runs/6868498490/job/18679184030?pr=15597
https://developer.chrome.com/articles/deprecating-unload/#:~:text=The%20unload%20event%20will%20be,flags%2F%23deprecate%2Dunload%20flag.
=> tests(dbw): add unload handler deprecation

core/audits/third-party-summary.js, core/test/audits/third-party-summary-test.js, core/test/fixtures/user-flows/reports/sample-flow-result.json
Implements #14737. Removes the "Other resources" ambiguous category.
*  #14737
=> core(third-party-summary): expands the audit to include all urls

core/computed/entity-classification.js, core/computed/resource-summary.js, core/lib/url-utils.js, core/test/lib/url-utils-test.js, package.json, report/renderer/report-ui-features.js, shared/test/util-test.js, shared/util.js, yarn.lock
Addresses #15623.
I took a stab at integrating [PSL](https://publicsuffix.org/list/) into LH, with an optimized dataset. 
Experiments integrating [npm:tldts](https://www.npmjs.com/package/tldts) (MIT licensed) that features a storage-optimized data-set (using Trie), to bring in [public suffix list](https://publicsuffix.org/list/) based root domain classification.
* Splits `Util.getRootDomain` into `UrlUtils.getRootDomain` that depends on PSL, and replaces report-side with entity recognition based. 
* Preserves existing rootDomains with an explicit `Legacy` prefix to be used for rendering pre-10.0 LHRs.
=> core(entity-classification): integrate public-suffix-list into LH

core/lib/url-utils.js, package.json, yarn.lock
Follow up to #15641: `tldts` now [publishes a subset of PSL](https://github.com/remusao/tldts/issues/1881) that excludes private registrations. This PR switches our dep to the ICANN-subset for a further reduced bundle size. 
before:
```
1973708 lighthouse-dt-bundle.js
558636 lighthouse-dt-bundle.js.gz (gzip -6)
```
after:
```
1942761 lighthouse-dt-bundle.js (-30.22 KiB)
547180 lighthouse-dt-bundle.js.gz (-11.19 KiB, gzip -6)
```
=> core(entity-classification): update tldts package to icann subset

core/config/constants.js, core/runner.js, core/test/fixtures/user-flows/artifacts/step0/artifacts.json, core/test/fixtures/user-flows/artifacts/step1/artifacts.json, core/test/fixtures/user-flows/artifacts/step2/artifacts.json, core/test/fixtures/user-flows/artifacts/step3/artifacts.json, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/results/artifacts/artifacts.json, core/test/results/sample_v2.json
standard UA version bump. 
but i also tweaked that "difference found" error text to log out what the difference was...
=> core(emulation): bump chrome UA to m119

cli/test/smokehouse/test-definitions/perf-trace-elements.js, core/audits/layout-shift-elements.js, core/gather/gatherers/trace-elements.js, core/test/audits/layout-shift-elements-test.js, core/test/gather/gatherers/trace-elements-test.js, types/artifacts.d.ts
Follow up to https://github.com/GoogleChrome/lighthouse/pull/15593
With `impactByNodeId` on the CLS computed artifact, we don't need the trace elements `score` field anymore.
=> core(trace-elements): remove element score field

core/audits/layout-shift-elements.js, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/results/sample_v2.json, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
Closes https://github.com/GoogleChrome/lighthouse/issues/15423
Also updates the aggregate row to use the total impact from nodes and not the CLS metric value. This is probably a more meaningful value considering the audit isn't just focused on layout shifts that happened to be captured in the CLS window.
=> core(layout-shift-elements): mention windowing in description

core/audits/metrics/max-potential-fid.js, core/test/results/sample_v2.json, types/artifacts.d.ts
As a first step to evaluating where [Long Animation Frames (LoAF)](https://github.com/w3c/longtasks/blob/main/loaf-explainer.md) will be a better measure of main-thread blocking than long tasks, this PR adds the longest LoAFs (after FCP) by `duration` and `blockingDuration` to the debug data of the `max-potential-fid` hidden audit.
No visible changes. The primary purpose is to have the data in HTTP Archive for querying and comparing to other metrics like MPFID and TBT.
Tests are minimal because we have fairly minimal tests for MPFID in the first place (e.g. no smoke tests). Happy to add more if it seems necessary.
=> core(mpfid): add max LoAFs to debugdata

core/audits/metrics/max-potential-fid.js, core/test/audits/metrics/max-potential-fid-test.js, core/test/results/sample_v2.json
Building on #15684, also logs LoAF startTime/durations in mpfid debugdata to be able to evaluate if a windowed function over LoAFs (e.g. max sum of LoAF blockingDurations in a 5s window) would be useful.
No visible changes. Again the intended purpose is analysis via a source like HTTP Archive.
I also didn't realize how "minimal" "Tests are minimal" was in #15684 because I forgot to add the unit test file to the commit. Whoops! Added in this PR.
=> core(mpfid): add list of loaf durations to debugdata

core/computed/unused-css.js, core/test/audits/byte-efficiency/unused-css-rules-test.js, core/test/audits/largest-contentful-paint-element-test.js, core/test/audits/prioritize-lcp-image-test.js, core/test/computed/lcp-image-record-test.js, core/test/computed/metrics/lcp-breakdown-test.js, core/test/computed/metrics/time-to-first-byte-test.js, core/test/network-records-to-devtools-log.js
following up to https://github.com/GoogleChrome/lighthouse/pull/15640, but doing it for unused-css.
=> core(unused-css): exclude header size for estimating wasted bytes

core/audits/byte-efficiency/render-blocking-resources.js, core/test/audits/byte-efficiency/render-blocking-resources-test.js
Render blocking resources most of the time don't affect the LCP if the LCP is an image. In these cases, we should avoid overestimating the potential LCP savings. If the LCP is an image we set potential savings to 0, else we use our fcp savings.
=> core(render-blocking-resources): reduce metric savings if LCP is an image

core/audits/audit.js, core/test/audits/audit-test.js, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/results/sample_v2.json
This PR prevents us from delivering too much precision in metric savings by rounding the result. It also creates a minimum threshold for metric savings to be nonzero which is important because that is the difference between a score of 1 and 0.5.
~With both of these goals in mind, I decided to just use `Math.floor` instead of `Math.round` but open to other approaches.~
=> core: round metric savings to remove false precision

report/renderer/category-renderer.js
Total driveby, but it felt wrong to cast the result of the only remaining call to `populateAuditValues` :) From the template we know we always want `div.lh-audit`, and adding the `div` makes `dom.find()` know it's returning an `HTMLElement`, not just an `Element`.
But then I also realized with only a single caller of `populateAuditValues` now, we don't need separate `renderAudit`/`populateAuditValues` functions at all anymore (👋  #5136).
=> report: small renderAudit simplification

core/audits/audit.js, core/audits/byte-efficiency/byte-efficiency-audit.js, report/renderer/performance-category-renderer.js, types/audit.d.ts, types/config.d.ts, types/lhr/audit-result.d.ts, types/lhr/lhr.d.ts
Addresses https://github.com/GoogleChrome/lighthouse/pull/15721#discussion_r1442102832. This is really just reshuffling the types so that metrics can define their acronym to be any string, but the audit product still needs to be one of FCP/LCP/TBT/CLS/INP.
Follow up to #15721 and https://github.com/GoogleChrome/lighthouse/pull/15540
=> core: create separate product savings type

cli/test/fixtures/dobetterweb/dbw_tester.html, cli/test/smokehouse/test-definitions/dobetterweb.js, cli/test/smokehouse/test-definitions/seo-failing.js, core/audits/viewport.js, core/computed/viewport-meta.js, core/test/computed/viewport-meta-test.js, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/results/sample_v2.json
I've dipped my toes into #15627 a bit and discovered that reality is even more nuanced than the proposed changes listed there. However, any analysis after the fact is difficult because we don't include the page's actual meta viewport `content` anywhere in the LHR, just whether or not it passed the audit's _current_ mobile viewport checks.
This PR just includes the full viewport string in the audit's debugData.
=> core(viewport): include meta viewport string in debugDetails

cli/test/smokehouse/test-definitions/dobetterweb.js
This has been happening a lot since this condition was added. ~Not entirely sure how this can happen. Maybe there is just higher variance since the sample size for the domain is just 1 request?~ Edit: see https://github.com/GoogleChrome/lighthouse/pull/15729#issuecomment-1877869991
=> tests(dbw): fix server latency flake

docs/readme.md
**Summary**
In the file https://github.com/GoogleChrome/lighthouse/blob/main/docs/readme.md#differences-from-cli-flags is a link in the section "Differences from CLI flags" which points to a commit from over 6 years ago. 
The linked information is outdated. 
I understand that the commit was included in the link because then the highlighting of the lines will work correctly in the future when changes are made to this file. 
This solution is also only a band-aid solution, because if changes are made to the linked file, this link may have to be adapted again. 
The only thing I can think of to solve this permanently would be to move the shared flags to a separate file. But I don't know where this would have to be adjusted and it might also be better as a downstream ticket.
=> docs: update deprecated link to shared flags

core/test/scenarios/__snapshots__/api-test-pptr.js.snap, core/test/test-env/mocha-setup.js
Noticed that snapshot tests were passing where they should be failing in CI (https://github.com/GoogleChrome/lighthouse/pull/15730#discussion_r1442352597)
If a test is retried, the snapshot expectation indices will start where the previous attempt left off. This leads to `jest-snapshot` treating the second attempt as a "new" snapshot which we automatically treat as passing because of the `updateSnapshot: 'new'` setting.
This PR uses `updateSnapshot: 'none'` by default so that CI will never accidentally pass. This means we have to use `-u` to set an initial snapshot for new tests, but that seems like a small price to pay.
However, mocha will only report the *last* failure attempt if a test is retried, which will now by a "snapshot does not exist" failure instead of a helpful snapshot diff. …
=> tests(mocha): fix snapshot expectations in retries

.github/workflows/ci.yml, .github/workflows/smoke.yml, .github/workflows/unit.yml, core/scripts/download-chrome.sh
I noticed in https://github.com/GoogleChrome/lighthouse/pull/15752 that we are not specifying the correct Chrome path in our smoke tests and then the tests revert back to using stable. Luckily it looks like the DevTools smoke tests specify the correct directory so we did not completely lose coverage.
=> tests: fix ToT chrome install path

cli/test/smokehouse/test-definitions/dobetterweb.js
Looks like Chrome has officially pulled the plug on unload handlers. IMO Lighthouse still delivers the correct advice which is flagging the console error for trying to use an unload listener, but not flagging anything in `no-unload-listeners` audit.
Attempting to use an unload listener creates a permission request now that blocks bfcache, but that is marked pending browser support so could change in a future Chrome patch.
We should remove the `no-unload-listeners` audit for 12.0, so https://github.com/GoogleChrome/lighthouse/pull/15752 is probably unnecessary.
=> tests(dbw): update expectations for unload handler removal

core/gather/driver/target-manager.js, core/test/gather/driver/target-manager-test.js
Closes https://github.com/GoogleChrome/lighthouse/issues/15739
If we hit an error attaching to a worker target that shouldn't be a fatal error IMO. We only use worker targets for diagnostic info. This PR emits a warning instead.
=> core(target-manager): warn on errors while attaching to workers

cli/test/smokehouse/test-definitions/dobetterweb.js, cli/test/smokehouse/test-definitions/oopif-scripts.js
This reverts commit 3d27df19160a60f3a1c0dcf26f0563f7ed786f5f / PR https://github.com/GoogleChrome/lighthouse/pull/15765
I guess Chrome backed off the unload handler removal (for now). I also verified this works on Chrome beta (M122).
This PR also updates the version for ScriptElements expectations from https://github.com/GoogleChrome/lighthouse/pull/15601 which is another smoke failure that appeared recently.
=> tests(dbw): revert expectations for unload handler removal

core/gather/gatherers/trace.js
b/325659693
We should add an opt-in setting to DevTools that enables JS samples for power users, but for now just disable by default globally.
=> core(trace): disable JS samples

core/gather/gatherers/devtools-log.js, core/gather/gatherers/trace.js, core/gather/navigation-runner.js, core/test/gather/navigation-runner-test.js
@connorjclark noticed that we are running the `getArtifact` phase of the DT log and trace *twice* during a normal navigation run:
The root cause is that we attempt to get a preview of the `DevtoolsLog` and `Trace` artifacts *before* running through the `getArtifact` phase properly. This doesn't actually cause any problems because the `getArtifact` implementation is idempotent in both cases. However this could theoretically cause problems if that were to change down the line.
This PR adds a separate path for the navigation runner to get it's preview of the DT log and trace so that making changes to `getArtifact` is safer.
=> core(navigation-runner): only run `getArtifact` phase once

core/gather/navigation-runner.js, core/gather/snapshot-runner.js, core/gather/timespan-runner.js
v minor refactor.. split out from latest #11840, but I've wanted it for a long while :) 
hide whitespace changes in the diff.
=> core(gather): gatherFn refactor

core/gather/driver/wait-for-condition.js
Also discovered during the targetcrashed journey (#11840)
=> core(driver): don't await cleanup in PAGE_HUNG case

core/scripts/build-devtools.sh, core/test/devtools-tests/download-devtools.sh, core/test/devtools-tests/roll-devtools.sh
`devtools_skip_typecheck=true` is the only way to really speed up DT builds according to this doc:
https://chromium.googlesource.com/devtools/devtools-frontend/+/main/docs/get_the_code.md#standalone-checkout-build
Validating types is still valuable for each patch, so leaving it on in CI.
One annoying problem is that local builds will spit out a bunch of `[WARNING] Unrecognized target environment "es2022"` warnings for some reason :/
-----
This PR also removes the `use_goma=true` and requisite user email check because it has been removed from non-windows builds as of recently.
=> tests(devtools): skip type checking in local builds

core/scripts/build-devtools.sh, core/test/devtools-tests/download-devtools.sh, core/test/devtools-tests/roll-devtools.sh
According to simon (in chat):
> Release build do some additional bundling with rollup and minification with terser and are the slowest.
Let's use debug builds for local debugging. In theory we could also do debug builds for CI, but I would prefer to play it safe and verify everything we do is compatible with release builds in CI.
Additionally, doesn't look like `devtools_dcheck_always_on` does anything anymore. I couldn't find any usages of this build arg and all the dcheck stuff from [this CL](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2894390) is gone.
=> tests(devtools): use `is_debug = true` for local builds

cli/test/smokehouse/test-definitions/byte-efficiency.js, core/audits/byte-efficiency/byte-efficiency-audit.js, core/audits/byte-efficiency/offscreen-images.js, core/audits/dobetterweb/uses-http2.js, core/test/audits/byte-efficiency/byte-efficiency-audit-test.js, core/test/audits/byte-efficiency/duplicated-javascript-test.js, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/results/sample_v2.json, flow-report/src/summary/category.tsx, flow-report/test/summary/category-test.tsx, types/lhr/audit-details.d.ts
Closes https://github.com/GoogleChrome/lighthouse/issues/15522
This PR also updates several audits that were still using the TTI graph or entire PDG to compute `overallSavingsMs`. Now those audits will just use their LCP savings to fill out `overallSavingsMs` instead.
Also, turns out we were still using `overallSavingsMs` in the flow report to sort audits in the summary page tooltip. Would be nice to use the same sort order as the performance category but that isn't a super high priority. This PR just does a simple sort by score then sort by LCP savings.
=> core: deprecate `overallSavingsMs`

treemap/app/src/main.js, viewer/app/src/lighthouse-report-viewer.js
ref #15884
and crbug.com/331086923 
While this isn't a security problem, we don't need this code to keep popping up in security scanners.
----
i'm open to using [`elem.replaceChildren()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren) instead, if that seems clearer.
=> report: remove use of innerHTML to empty elements

cli/test/smokehouse/test-definitions/a11y.js, core/audits/accessibility/target-size.js, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/results/sample_v2.json, report/test/generator/report-generator-test.js, report/test/renderer/category-renderer-test.js, third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
This audit was informative while it was hidden, but forgot to update that in #15906. We want this audit to be scored.
=> core(target-size): use binary display mode

core/lib/tracehouse/trace-processor.js, core/test/audits/long-tasks-test.js, core/test/audits/mainthread-work-breakdown-test.js, core/test/lib/tracehouse/trace-processor-test.js
Tasks can sometimes be overlapping as of M122: https://crbug.com/329678173
This probably needs a fix for the trace events themselves, but until then we can approximate the correct behavior by cutting of tasks that overlap with the next task.
Ref https://github.com/GoogleChrome/lighthouse/issues/15896
=> core(trace-processor): correct overlapping tasks

.npmignore
This fixes the weird package-test errors we have been getting recently.
Some change in node 18.20.0 appears to have fixed a bug that our .npmignore was relying on.
[Without a leading slash, entries in .npmignore should refer to *any* file/folder with that name in the directory structure.](https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#_ignoring:~:text=%23%20ignore%20all%20files%20in%20any%20directory%20named%20build%0Abuild/) Before 18.20.0 this wasn't happening for some reason.
I attempted to correct as many entires in our .npmignore as I could, and verified that the contents by diffing [old .npmignore & node 18.19] against [new .npmignore & 18.20]
Ref https://github.com/nodejs/node/issues/52382
=> misc: correct .npmignore for node >=18.20

core/audits/layout-shifts.js, core/gather/gatherers/trace-elements.js, core/test/gather/gatherers/trace-elements-test.js
This should alleviate the symptoms of https://github.com/GoogleChrome/lighthouse/issues/15870 and adds some extra sentry instrumentation to help us get to the bottom of this.
=> core(trace-elements): add sentry debugging for `impactedNodes`

cli/test/smokehouse/test-definitions/shift-attribution.js, core/computed/metrics/cumulative-layout-shift.js, core/computed/trace-engine-result.js, package.json, yarn.lock
This upgrade disables iframe root causes because the volume of applicable layout invalidations was creating performance issues https://github.com/GoogleChrome/lighthouse/issues/15869
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5421436
=> deps: upgrade `trace_engine` to 0.0.19

core/lib/lantern/cpu-node.js, core/lib/lantern/metrics/interactive.js, core/lib/lantern/page-dependency-graph.js, core/lib/lantern/simulator/simulator.js, core/test/lib/lantern/page-dependency-graph-test.js
I was investigating the weird CI failures in https://github.com/GoogleChrome/lighthouse/pull/15839. Long story short the CI failure is caused by the same issue in https://github.com/GoogleChrome/lighthouse/issues/15896 where `RunTask` events can sometimes be overlapping.
We fixed this when calculating observed TBT in https://github.com/GoogleChrome/lighthouse/pull/15921, but we did not correct the overlapping tasks in Lantern.
I suspect we may need another PR to address this in `main-thread-tasks.js` as well...
=> core(lantern): correct overlapping tasks in CPU nodes

core/config/filters.js, core/runner.js, types/artifacts.d.ts, types/lhr/lhr.d.ts
https://github.com/GoogleChrome/lighthouse/pull/14075 This hack was added to legacy navigation but never added to the new navigation runner.
It's always empty now, and confirmed with @paulirish that it's not needed anymore so we can just remove it.
=> misc: remove `BenchmarkIndexes` base artifact

viewer/app/index.html, viewer/app/src/lighthouse-report-viewer.js
=> clients(viewer): stop using legacy DOM api

.github/workflows/ci.yml, .github/workflows/cron-weekly.yml, .github/workflows/devtools.yml, .github/workflows/package-test.yml, .github/workflows/publish.yml, .github/workflows/smoke.yml, .github/workflows/unit.yml
**Summary**
CI uses `actions/checkout@v3`, which uses a `deprecated` version of `Node.js`. This pull request updates that action to the latest version.
This pull request fixes #16021.
=> misc(ci): fix deprecated node usage in checkout@v3

core/audits/accessibility/aria-allowed-role.js, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/results/sample_v2.json, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
Closes https://github.com/GoogleChrome/lighthouse/issues/16023
=> core(aria-allowed-role): fix title and description

treemap/test/treemap-test-pptr.js
We're getting a cookie deprecation error coming from gtag.js:
https://support.google.com/tagmanager/thread/288419928/error-failed-to-execute-getvalue-on-cookiedeprecationlabel?hl=en
=> tests(treemap): ignore cookie deprecation error

core/scripts/roll-to-devtools.sh
ref https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5722333
=> misc(build): update README.chromium when rolling devtools

core/audits/third-party-cookies.js, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/results/sample_v2.json, shared/localization/locales/en-US.json, shared/localization/locales/en-XL.json
https://privacysandbox.com/news/privacy-sandbox-update/
=> core(third-party-cookies): update description for 3PCD updates

core/gather/driver/network-monitor.js, core/test/gather/driver/network-monitor-test.js
=> core(network-monitor): treat EventSource as non-critical

build/test/plugins/inline-fs-test.js
https://github.com/GoogleChrome/lighthouse/actions/runs/12023875090/job/33518668413?pr=16257
=> tests(inline-fs): fix error in Node 20

core/config/lr-mobile-config.js
Further analysis indicates that 1.2x might be better than 1.5x in PSI. 1.2x is recommended by https://lighthouse-cpu-throttling-calculator.vercel.app/ but 1.5x was just the high end of the reported range.
=> clients(lr): adjust CPU throttling based on benchmark

cli/test/fixtures/font-size.html, core/gather/gatherers/seo/font-size.js
Fixes https://github.com/GoogleChrome/lighthouse/issues/16234
=> core(font-size): exclude invisible text

docs/releasing.md
- `git push --follow-tags` doesn't work if you are checking out a specific tag (which lighthouse-pristine is after running the `prepare-package.sh`). `git push --tags` is what I have been using.
- Monorail -> Bugganizer issue ID
=> docs: update releasing instructions

readme.md
**Summary**
Adds [Sonā](https://getsona.io/) to the list of Web Perf services
**Related Issues**
#16280
=> docs(readme): add Sonā to the list of Web Perf services

types/lhr/audit-details.d.ts
**Summary**
Type for `node.explanation` was missing from `NodeValue`. I think its only present in accessibility audits.
=> misc(types): add missing type for explanation in NodeValue

cli/test/smokehouse/test-definitions/dobetterweb.js
Reverts the dbw smoke test changes from https://github.com/GoogleChrome/lighthouse/pull/16335
=> tests(dbw): revert unload handler expectations

readme.md
Added the Neodymium test automation tool (MIT licensed) and its support for Lighthouse report and audit value assertions to the README.
This is a small README/documentation update only, just to spread the word which other open-source project integrates Lighthouse.
The wiki of the project that mentions the Lighthouse integration: https://github.com/Xceptance/neodymium/wiki/Reports#lighthouse-report and a blog post with another screenshot: https://blog.xceptance.com/2025/02/11/neodymium-5-1-get-more-done-faster/
Was #16330 because that one was not clean anymore.
=> misc(readme): add link to Neodymium

core/audits/insights/use-cache-insight.js, core/test/fixtures/user-flows/reports/sample-flow-result.json, core/test/results/sample_v2.json
This adds a transfer size column that isn't present in RPP but is present in the `uses-long-cache-ttl` audit. I think it's a good addition here that is hard to add in RPP due to space constraints.
ref https://github.com/GoogleChrome/lighthouse/issues/16323
=> core(insights): implement `use-cache-insight`

core/lib/legacy-javascript/legacy-javascript.js, shared/localization/locales.js, shared/tsconfig.json, tsconfig-base.json, tsconfig.json
With Node 22 as our minimum supported version, we can utilize json modules
This PR relands what was reverted in https://github.com/GoogleChrome/lighthouse/pull/16613
fixes https://github.com/GoogleChrome/lighthouse/issues/16614
=> core: import json as modules

core/scripts/legacy-javascript/examine-latest-run.js
Fix this helper script that pretty-prints the polyfills detected in the latest run.
The mock artifacts was broken.
Also added wasted bytes to the output.
=> misc: fix core/scripts/legacy-javascript/examine-latest-run.js

core/gather/gatherers/trace-elements.js
I noticed that for dbw tester, the dom-size-insight max children field was not getting a node element. There was a node id, but it pointed at the document fragment inside a shadow tree. The TraceElements saw it was not an element node, so it went to the parentElement. But since it's a shadow root, there is no parent element, and thus no node reference was created.
Instead, check if the element is a shadow root. If so, use its host.
=> core(trace-elements): handle shadow roots

cli/test/smokehouse/test-definitions/dobetterweb.js
I accidentally disabled this test even though I fixed it via #16718.
=> tests: re-enable dom-size-insight node smoke test
