lighthouse-core/gather/computed/computed-artifact.js
lighthouse-core/test/gather/computed/computed-artifact-test.js

fixes #2275
opens the door for #2703 to be built on computed artifacts and re-used in other places

feat(computed-artifact): support arbitrarily many inputs

---

lighthouse-core/audits/dobetterweb/uses-http2.js

Invoking `new URL` for each network record was taking an insane amount of time

perf(uses-http2): check protocol first

---

lighthouse-core/index.js

#2507 , There’s a arg checker in cliflags.ts too, but better to throw early instead of starting LH just to throw?

remove duplicate url check in core/index.js

---

.travis.yml
chrome-launcher/chrome-finder.ts

We added priority regexes of `LIGHTHOUSE_CHROMIUM_PATH` and `CHROME_PATH` even when they weren't populated so we got the regex `{(:?)}` which matches everything so the first chrome in the list got hit.
We now do explicit checks to add the regex only if they env params are populated
Fixes #2683

Fix chrome finder on linux & osx

---

lighthouse-core/gather/gather-runner.js

fixes #2612
~Pavel introduced [`Input.setIgnoreInputEvents`](https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-setIgnoreInputEvents) so that the user can't click or interact with the page while it's being audited.~
~It's been [injected into the lighthouse connection](https://github.com/ChromeDevTools/devtools-frontend/blob/f55402717f7f73fdb75b3d33d7587d9e92ab6447/front_end/audits2/Audits2Panel.js#L543-L546) in the devtools case for 2 months now.  And obviously it makes more sense to not have it hacked in there like that. :)~

Gather-runner: Get useragent before emulating

---

chrome-launcher/README.md
chrome-launcher/chrome-launcher.ts
chrome-launcher/test/chrome-launcher-test.ts
chrome-launcher/tsconfig.json

fixes #2594
I've tested flag status by mocha and running test by [chrome-launcher-cli@extension-enable](https://github.com/ragingwind/chrome-launcher-cli/tree/extension-enable) in manually:
```
chrome --app=file:///Users/ragingwind/Workspace/chrome-extension/extended/test/index.html --system-developer-mode --load-ex
tension=/Users/ragingwind/Workspace/chrome-extension/extended/test/extension --enable-extensions
```

launcher: support enabling extension loading (#2594)

---

lighthouse-viewer/app/src/github-api.js

Log the expected URL to prevent confusion.
Fixes #2722 
Because I think if the user then renamed the file to match, it would then give a proper error saying the version is incorrect.

Viewer: log expected URL

---

chrome-launcher/manual-chrome-launcher.js

followup to #2650
After that PR, `--enable-extensions` works for chrome-launcher-cli and `enableExtensions` works for calling `chrome-launcher` from within node.
This PR special cases `--enable-extensions` in `manual-chrome-launcher.js` (similar to `--port`) so that `chrome-debug --enable-extensions` and `yarn chrome -- --enable-extension` will also work.

pass --enable-extensions on from manual-chrome-launcher

---

lighthouse-extension/app/src/lighthouse-background.js

fixes #1177
allows opening the report when Lighthouse was run on an incognito tab.
(if folks hate always opening in a new window, we could try opening in a new window only when run in incognito or something)

open extension's report in new window

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-cli/test/smokehouse/smokehouse.js
lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener.js

fixes #2743
we actually already had the smoketest to catch this but it was updated without catching it in review last time, also fixes a rather humorous smokehouse bug where we said `difference at undefined, found undefined but expected undefined`

fix(anchors-with-no-rel): ignore same origin links

---

readme.md

I noticed that project's README file which contains CLI help is missing CHROME_PATH description that was added during work on #2617 so this PR is about to fix that.

Added CHROME_PATH description from CLI help in README

---

lighthouse-core/audits/dobetterweb/script-blocking-first-paint.js
lighthouse-core/test/audits/dobetterweb/script-blocking-first-paint-test.js

scripts that are injected into the head after first paint are falsely flagged as blocking currently

fix(script-blocking-first-paint): ignore latent resources

---

docs/recipes/custom-audit/searchable-audit.js
lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
lighthouse-core/config/config.js
lighthouse-core/test/config/config-test.js
lighthouse-core/test/fixtures/invalid-audits/missing-audit.js
lighthouse-core/test/fixtures/invalid-audits/missing-category.js
lighthouse-core/test/fixtures/invalid-audits/missing-description.js
lighthouse-core/test/fixtures/invalid-audits/missing-generate-audit-result.js
lighthouse-core/test/fixtures/invalid-audits/missing-help-text.js
lighthouse-core/test/fixtures/invalid-audits/missing-name.js
lighthouse-core/test/fixtures/invalid-audits/missing-required-artifacts.js
lighthouse-core/test/fixtures/invalid-audits/require-error.js
lighthouse-core/test/fixtures/valid-custom-audit.js
lighthouse-core/test/report/v2/renderer/category-renderer-test.js
lighthouse-core/test/runner-test.js

I just got a release blocking bug on the Chromium side because password pasting audit doesn't show any helptext: https://bugs.chromium.org/p/chromium/issues/detail?id=748381
Indeed it's weird to expand a details/summary in the report to see nothing.
I've added that and then decided to throw in this case and the previously implemented failureDescription case.

All audits must specify helpText and failureDescription

---

lighthouse-cli/run.ts
lighthouse-cli/test/cli/run-test.js

Related Issue: https://github.com/GoogleChrome/lighthouse/issues/2753
This PR fixes `--chrome-flags` parsing so that the flags can contain spaces if quoted properly.
- Arguments are now handled by `yargs`

Fix: Basic chrome-flags parsing for embedded quotes

---

lighthouse-core/report/v2/renderer/category-renderer.js
lighthouse-core/report/v2/report-styles.css

based on discussion that lighthouse team members didn't know these things shared the same timescale. :)
lines only draw on hover:

report: draw metric lines over the screenshots.

---

lighthouse-core/audits/first-meaningful-paint.js
lighthouse-core/closure/typedefs/ComputedArtifacts.js
lighthouse-core/gather/computed/trace-of-tab.js
lighthouse-core/test/audits/first-meaningful-paint-test.js
lighthouse-core/test/gather/computed/trace-of-tab-test.js

there's no way to tell from the LH results that `trace-of-tab` fell back to a `firstMeaningfulPaintCandidate` event for the FMP event.  #2420 will generate a Sentry entry for that case, but it would be handy to have it in the report so that e.g. the HTTPArchive data can be queried to get frequency numbers on this as well.
Happy to bikeshed on this and/or change so that it will also work for logging when/if we turn on #2244

add flag to FMP to indicate if it fell back to FMP candidate

---

lighthouse-core/gather/driver.js

followup cleanup to #2473 and #2682

refactor: cleanup unused waitFor properties

---

docs/readme.md

A small Readme change to correct location of lighthouse-logger !

Update lighthouse-logger location in readme

---

.gitignore
chrome-launcher/.npmignore
chrome-launcher/chrome-launcher.ts
chrome-launcher/package.json
chrome-launcher/scripts/format.sh
chrome-launcher/test/check-formatting.sh
chrome-launcher/tsconfig.json
chrome-launcher/yarn.lock

This _should_ fix #2896 and reduce errors caused by different ts versions, ts configs, and ts declaration file versions.
In general, this PR enables the option in chrome-launcher's tsconfig to produce declaration files and updates the .npmignore to ignore `.ts` files.
One additional change was the addition of the `@types/rimraf` package. This had to be done, as the compiler was complaining about exporting a private type.

[chrome-launcher] Publish type definitions instead of source TypeScript files

---

docs/readme.md
lighthouse-cli/cli-flags.ts
lighthouse-core/gather/connections/cri.js
lighthouse-core/index.js
lighthouse-viewer/app/src/github-api.js
readme.md

This issue fulfills the request made in issue #2727. This change should allow for Chrome to be located on a hostname other than `localhost`, as outlined in the issue. It may be noted that I added the hostname parameter to be the second parameter in the constructor so that it does not break any previous implementations of CriConnection.
Additionally, I made a small change that allowed for the yarn tests to be passed. No functionality was changed in this (the second) commit.

Add chrome hostname to CriConnection & eslint fix

---

lighthouse-core/audits/webapp-install-banner.js

Error message is confusing for some users (https://stackoverflow.com/questions/45330087/manifest-start-url-is-not-cached-by-a-service-worker) and technically it's not true. There's check if the start_url is returned, and if not the message that it's not cached is returned. There's possibility for service worker to cache it but not return it and receive this error message.

Clarification of hasOfflineStartUrl rule

---

chrome-launcher/chrome-launcher.ts

This is a fix for https://github.com/GoogleChrome/lighthouse/issues/2797
Currently we add a SIGINT handler for each launched Chrome instance to kill that instance on exit. My change makes it so that we track the list of running Chrome instances. When that list goes from 0 to 1, a SIGINT handler is added which kills all tracked Chrome instances. When that list goes from 1 to 0, the handler is removed.
So there is only ever a maximum of one SIGINT listener, which prevents the EventEmitter memory leak warnings.
I believe that my fix is better than the other one provided in the issue as it allows for you to have more than 10 simultaneously running Chrome instances without an EventEmitter memory leak warning.

Better SIGINT handling in chrome-launcher

---

chrome-launcher/chrome-launcher.ts
chrome-launcher/test/chrome-launcher-test.ts

If an error inside spawnPromise occurs it is being ignored as the async function is passed to new Promise(...) as a regular function.
This leads to the following output if you pass an empty string for chromePath:
```
(node:19352) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Bad argument
(node:19352) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Fix errors inside spawnPromise being ignored

---

lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js

forgot to update #2518 smokehouse expectations for the new last second multiplier change 3x -> 2x

test(smokehouse): adjust unused css expectations

---

lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
lighthouse-core/audits/byte-efficiency/uses-webp-images.js
lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js

Uses the new Audits.getEncodedResponse method to determine the size savings. Time savings varies since the canvas method was more variable than outright slow but some runs went from ~6s to ~500ms. Also enables fast checking of cross-origin images which was previously impossible.

perf(optimized-images): use Audits.getEncodedResponse

---

lighthouse-core/report/v2/renderer/details-renderer.js
lighthouse-core/test/report/v2/renderer/details-renderer-test.js

alternative to #3154
this does unfortunately leave us with `renderUrl` and `renderLink`, but they were different enough that I didn't really want to merge them

report: add LinkDetailsJSON to details renderer

---

lighthouse-core/audits/predictive-perf.js
lighthouse-core/config/fast-config.js
lighthouse-core/gather/computed/dependency-graph/node.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/runner.js
lighthouse-core/test/audits/predictive-perf-test.js
lighthouse-core/test/gather/computed/dependency-graph/node-test.js
lighthouse-core/test/gather/computed/page-dependency-graph-test.js

in the name of FastMode #2703 
The first commit introduces the primary structure of how the estimates will be computed.
* audits/predictive-perf.js - file where a dependency graph is requested, subgraphs will be created and estimates combined
* gather/computed/page-dependency-graph.js - main file responsible for creating dependency graphs and measuring their execution time, heavily leverages the logic of graph nodes found in ./dependency-graph
* gather/computed/dependency-graph/* - folder where different resource/task types will be added
For easier reviewing I've split out the bulk of the logic that was here into three other PRs: #3187  #3162 #3163

feat(predictive-perf): add shell and base audit

---

docs/architecture.md

@rviscomi wrote some nice definitions (in a private doc) so i figured we should import them to the project.

docs: import audit glossary from SEO doc

---

lighthouse-core/audits/predictive-perf.js
lighthouse-core/gather/computed/dependency-graph/estimator/estimator.js
lighthouse-core/gather/computed/dependency-graph/estimator/tcp-connection.js
lighthouse-core/gather/computed/dependency-graph/network-node.js
lighthouse-core/gather/computed/dependency-graph/node.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/test/audits/predictive-perf-test.js
lighthouse-core/test/gather/computed/dependency-graph/estimator/estimator-test.js
lighthouse-core/test/gather/computed/dependency-graph/estimator/tcp-connection-test.js
lighthouse-core/test/gather/computed/dependency-graph/node-test.js
lighthouse-core/test/gather/computed/page-dependency-graph-test.js

~blocked on #2720~
split out from #2720 for easier reviewing

feat(predictive-perf): add network estimation

---

lighthouse-cli/test/fixtures/seo/seo-failure-cases.html
lighthouse-cli/test/fixtures/seo/seo-tester.html
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-cli/test/smokehouse/seo/run-tests.sh
lighthouse-core/config/seo.js
package.json

@kdzwinel FYI
this adds a starting point for SEO audit integration tests. Right now this tests only the two a11y audits that are also being used as SEO audits, but since they're a11y audits they don't have many details to test beyond the score
as new SEO audits get added:
- add audits to the expectations file (obviously :)
- new audits may have a lot more detail in `extendedInfo`/`details` that can be tested ([example](https://github.com/GoogleChrome/lighthouse/blob/a9b02a948b579be1a0667b69627f6d1f831d30ca/lighthouse-cli/test/smokehouse/pwa-expectations.js#L40-L56))
- could add a second html tester file that fails some/all of these audits and asserts proper failure output in those cases

test(smokehouse): add basic smoke test for SEO audits

---

chrome-launcher/test/random-port-test.ts
docs/recipes/gulp/public/index.html
lighthouse-cli/performance-experiment/report/perf-x-report-generator.js
lighthouse-cli/test/fixtures/accessibility/accessibility_tester.html
lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/fixtures/dobetterweb/dbw_partial_a.html
lighthouse-cli/test/fixtures/dobetterweb/dbw_partial_b.html
lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/fixtures/dobetterweb/domtester.html
lighthouse-cli/test/fixtures/offline-ready.html
lighthouse-cli/test/smokehouse/byte-efficiency/run-tests.sh
lighthouse-core/closure/conformance_config.textproto
lighthouse-core/lib/dom-helpers.js
lighthouse-core/test/fixtures/invalid-audits/missing-audit.js
lighthouse-core/test/fixtures/invalid-audits/missing-category.js
lighthouse-core/test/fixtures/invalid-audits/missing-description.js
lighthouse-core/test/fixtures/invalid-audits/missing-generate-audit-result.js
lighthouse-core/test/fixtures/invalid-audits/missing-help-text.js
lighthouse-core/test/fixtures/invalid-audits/missing-meta.js
lighthouse-core/test/fixtures/invalid-audits/missing-name.js
lighthouse-core/test/fixtures/invalid-audits/missing-required-artifacts.js
lighthouse-core/test/fixtures/invalid-audits/require-error.js
lighthouse-core/test/fixtures/invalid-gatherers/missing-after-pass.js
lighthouse-core/test/fixtures/invalid-gatherers/missing-before-pass.js
lighthouse-core/test/fixtures/invalid-gatherers/missing-pass.js
lighthouse-core/test/fixtures/invalid-gatherers/require-error.js
lighthouse-core/test/fixtures/valid-custom-audit.js
lighthouse-core/test/fixtures/valid-custom-gatherer.js
lighthouse-core/test/lib/manifest-parser-test.js

Noticed in https://github.com/GoogleChrome/lighthouse/pull/3267/files#r138413155

Apply small license header to last remaining files

---

lighthouse-core/report/v2/renderer/dom.js
lighthouse-core/test/report/v2/renderer/dom-test.js

encountered in the `td-headers-attr` [`helpText`](https://github.com/GoogleChrome/lighthouse/blob/da9f7893b84851a914b59058202455e1cc072a86/lighthouse-core/audits/accessibility/td-headers-attr.js#L28-L31)
fixes https://bugs.chromium.org/p/chromium/issues/detail?id=762936

fix(report): tame greedy markdown link regex

---

package.json
yarn.lock

fix: Bump axe-core to 2.4.1

---

lighthouse-core/audits/predictive-perf.js
lighthouse-core/gather/computed/dependency-graph/cpu-node.js
lighthouse-core/gather/computed/dependency-graph/estimator/estimator.js
lighthouse-core/gather/computed/dependency-graph/node.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/lib/traces/tracing-processor.js
lighthouse-core/test/audits/predictive-perf-test.js
lighthouse-core/test/gather/computed/dependency-graph/estimator/estimator-test.js
lighthouse-core/test/gather/computed/page-dependency-graph-test.js

in the name of fast mode #2703 
broken out just the CPU estimation portion from #2720

feat(predictive-perf): add CPU estimation

---

.travis.yml

fixes #3338 
Unfortunately https://github.com/ChromeDevTools/devtools-frontend/commit/5e7e9ca0a01c880f5aae5123d3242591a86d8c3c wasn't successful. Something else in `compile_frontend.py` is dependent on the exact output of the compiler and is breaking the build.
In the [Travis bug for this](https://github.com/travis-ci/travis-ci/issues/8408), unsetting the variable is mentioned as working, and though there is a concern that the new default JVM will run out of memory, it appears to work for us so let's go with it for now unless it ends up flaky.
https://github.com/travis-ci/travis-cookbooks/issues/895 suggests Travis may move to using `JAVA_TOOL_OPTIONS` which *won't* get printed to stdout, so we may be able to remove this line again in the future.

fix(travis): unset _JAVA_OPTIONS for compile_frontend.py

---

lighthouse-cli/test/smokehouse/perf/expectations.js

test(smokehouse): add TTFB smoke test

---

.npmignore
CONTRIBUTING.md

since lighthouse-logger is now its own package. Saves a whole 17KB!
Also update CONTRIBUTING on local testing of the npm package due to `npm install <file>` now just creating a symlink (https://github.com/npm/npm/pull/15900) instead of a real install

fix(npm): remove lighthouse-logger/ from npm package

---

lighthouse-core/gather/driver.js

to repro:
```sh
yarn start -- --disable-device-emulation --disable-cpu-throttling --disable-network-throttling "http://example.com" --verbose
```
this will always timeout at 30 waiting for example.com
that's because it fires loadEventFired before page.navigate ever resolves:

Don't wait for Page.navigate's resolution

---

lighthouse-core/audits/predictive-perf.js
lighthouse-core/gather/computed/dependency-graph/estimator/estimator.js
lighthouse-core/gather/computed/dependency-graph/estimator/tcp-connection.js
lighthouse-core/gather/computed/dependency-graph/network-node.js
lighthouse-core/gather/computed/dependency-graph/node.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/test/audits/predictive-perf-test.js
lighthouse-core/test/gather/computed/dependency-graph/estimator/estimator-test.js
lighthouse-core/test/gather/computed/dependency-graph/estimator/tcp-connection-test.js

in the name of fast mode #2703 
blocked on ~#3162~
broken out from #2720 for easier reviewing

fix(predictive-perf): incremental improvements and fixes

---

lighthouse-core/report/v2/report-generator.js
lighthouse-core/test/report/v2/report-generator-test.js

fix(report): prevents unicode newline from breaking the report

---

docs/configuration.md
lighthouse-core/config/plots-config.js

we missed these when updating in #2220, #2473, et al, which leads to lots of null TTCIs in plots runs :S

fix: update plots-config to use newer quiet parameters

---

lighthouse-core/gather/connections/extension.js

falls back to the raw lastError message if we couldn't parse it, hopefully we can get something useful to figure out what's going on with #3468 and related

fix(extension): collect better fallback error message

---

lighthouse-cli/package.json
lighthouse-cli/yarn.lock
package.json
yarn.lock

reverts previous PR to put package in root deps
time to ditch the non-package `package.json`s? :)

fix(deps): add yargs-parser at 7.0.0

---

package.json
yarn.lock

Bump chrome-launcher dep to 0.8.1

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js

test(smokehouse): Passive event listener violation doesn't report on passive:false now

---

package.json

the `yarn lint --silent` now breaks in yarn 1.0 because --silent is being passed to eslint.  before 1.0, it was not passed. (whoops)

fix(eslint): use quiet flag rather than silent

---

lighthouse-core/lib/traces/devtools-timeline-model.js
lighthouse-core/lib/web-inspector.js

1. The changes in web-inspector fix #3509 and the current `yarn test` breakage on master due to changes in #3497
2. The DTM changes handle the silent failure coming from mocha. One alternative to this fix is removing consoleQuieter entirely, which I'm open to. It was introduced to handle cases like https://github.com/paulirish/pwmetrics/issues/3. @brendankenny thoughts?

core(devtools-model): fix missing `Runtime.experiments` object

---

.cz-config.js
package.json
yarn.lock

To use:
`yarn global add commitizen`
`git add ....`
`git cz`
Only necessary for first commit in a branch, to set the PR commit name. (Since we squash) followup commits can be whatever.
----------
Later we can look at getting https://github.com/marionebl/commitlint running in a github commit status bot to check our PR titles.

core: add cz-customizable to establish a commit message convention

---

docs/understanding-results.md
readme.md

docs: add results object explainer

---

lighthouse-core/config/default.js
lighthouse-core/config/perf.json

I noticed that when running the Lighthouse with the `--perf` flag, the top level `score` value in the generated json report is `0` even when the `score` of the `performance` category is higher than `0`. I expected these values to be the same when `performance` is the only category being evaluated.
This pull request simply adds default weights to `performance`, `accessibility`, and `best-practices`. `pwa` already had a weight.
Here's one way I tested this change.
```
git checkout master
/lighthouse-cli/index.js --chrome-flags="--headless --disable-gpu" https://www.github.com --perf  --output=json   --output-path=report.json  && cat report.json | jq '{TopLevelScore:  .score, PerfScore: .reportCategories[].score}'
{
"TopLevelScore": 0,
"PerfScore": 75.94117647058823
}
git checkout …
```

core(config): add category weight to perf config

---

.cz-config.js

konrad discovered that 'new-audit' wasn't being handled correctly
root issue: `conventional-commits-parser` package has `headerPattern: /^(\w*)(?:\(([\w\$\.\-\* ]*)\))?\: (.*)$/,`  and this regex of `(\w*)` doesn't include dashes.
underscore works and kinda looks better anyway, so we'll move to that, ya?

misc(commitizen): new-audit => new_audit

---

lighthouse-core/lib/emulation.js

This protocol method was made redundant in 61.0.3155.0
It's a noop for us now. Trace screenshots are no different.
fixes #2831

core(emulation): remove use of deprecated Emulation.setVisibleSize

---

lighthouse-cli/test/fixtures/a11y/a11y_tester.html
lighthouse-cli/test/smokehouse/a11y/a11y-config.js
lighthouse-cli/test/smokehouse/a11y/expectations.js
lighthouse-cli/test/smokehouse/a11y/run-tests.sh
lighthouse-cli/test/smokehouse/run-all-tests.sh
lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/accessibility.js
lighthouse-core/gather/gatherers/dobetterweb/js-libraries.js
lighthouse-core/test/gather/driver-test.js
package.json

core(driver): use execution context isolation when necessary

---

lighthouse-core/config/default.js

fixes #3521
These audit results will show up in the `audits` object on the LHR, but won't show up in the HTML report as no category includes them. They will be filtered out by any config that subsets the default config because of this, however.
We can add the other SEO audits as they land (probably as long as they don't have substantial cost) and/or make them visible in the report by bringing in the SEO report category if we're ready.
@kdzwinel @rviscomi

core(config): add silent seo audits to default config

---

.github/CODEOWNERS

* https://github.com/blog/2392-introducing-code-owners
* https://help.github.com/articles/about-codeowners/

misc(codereview): add CODEOWNERS file

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/audits/errors-in-console.js
lighthouse-core/config/default.js
lighthouse-core/gather/gatherers/runtime-exceptions.js
lighthouse-core/test/audits/errors-in-console-test.js
lighthouse-core/test/gather/gatherers/runtime-exceptions-test.js

@paulirish @patrickhulce @brendankenny as promised this the 2nd part of the errors-in-console, this should include the js errors now

new_audit(errors-in-console): Added new runtime exceptions

---

lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/lib/dependency-graph/node.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/test/lib/dependency-graph/node-test.js

core(dependency-graph): add cycle sanity check

---

lighthouse-core/gather/computed/critical-request-chains.js
lighthouse-core/test/gather/computed/critical-request-chains-test.js
lighthouse-core/test/runner-test.js

Fixes #3443
It was pretty hard after all to see if a html document was an iframe or not.
I needed this for the preload audit.

core(critical-request-chains): Remove iframe as Critical Request

---

lighthouse-core/test/lib/web-inspector-test.js

reminded by gitter to add test for this :)

tests(web-inspector): add test for setImmediate polyfill

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.js
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js

Fixes broken appveyor tests.
In m64 the multiple shadow root deprecation warning has turned into an error, so `deprecations--` and `errors-in-console++`. However, Travis runs stable while Appveyor runs Canary, so there's no great way to get these two to play along nicely short of just disabling that particular error in `dbw_tester` until m64 hits stable (which is what this does).
I investigated checking the `details.items` strings more directly (something we should probably do more often rather than just checking `length`), which would allow only checking a subset of `items` and ignoring the shadow root error in either list, but since these two audits' results are sorted by the order the error messages are emitted in, they weren't listed in a reliable order and so can't be addressed by …

tests(smokehouse): disable multiple shadow root deprecation test

---

lighthouse-core/gather/gather-runner.js
lighthouse-core/report/v2/renderer/report-renderer.js
lighthouse-core/report/v2/report-styles.css
lighthouse-core/report/v2/templates.html
lighthouse-core/runner.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/report/v2/renderer/report-renderer-test.js
lighthouse-core/test/runner-test.js

Adds a `LighthouseRunWarnings` artifact in `gather-runner` and a `lighthouseRunWarnings` in `runner` (which `LighthouseRunWarnings` is folded into when `gather-runner` is complete) to collect top-level warnings worthy of bringing to the user's attention (e.g. ran in Headless which doesn't support throttling). For now only `gather-runner` and `runner` can add to these, but should be easy to extend if we want to e.g. let gatherers or audits emit warnings they think are worthy of floating to the top. Happy to bikeshed on naming and exact flow of warning strings.
~steals the styling in the HTML report from #2920, but not remotely attached to it :)~
closes #2920 by adding a warning when running in Headless

core: record top-level warnings in LHR and display in report

---

lighthouse-cli/test/smokehouse/redirects/expectations.js
lighthouse-core/audits/dobetterweb/geolocation-on-start.js
lighthouse-core/audits/redirects.js
lighthouse-core/test/audits/redirects-test.js

* The cost of each redirect is shown next to the new/redirected URL rather than initial URL. (Makes more sense to my brain). This also means we now show the final URL in the table, whereas before it wasn't there.
* The very first initial url is shown for completeness. 
* (If there's just 1 redirect we currently pass them. Nothing changes here.)
* All costs of redirects are kept and summed. We don't skip the first one. 
* Even if there's 1 redirect and you pass, we will still show the cost of the redirects to be clear.
* I updated the test cases to be slightly more realistic.
failing with 2 redirects: 
passing with 1 redirect: 
passing with 0 redirects:

report(redirects): reformat results, incl all requests and wasted time,

---

lighthouse-core/audits/image-aspect-ratio.js
lighthouse-core/test/audits/image-aspect-ratio-test.js

I'm pretty confident that the code matches the suggestion in #3716. I made an attempt at a new test, but it isn't correct (passes with and without the new check); suggestions welcome.

core(aspect-ratio): skip aspect ratio audit for svg

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js

core(tags blocking first-paint): exclude script type=module

---

docs/new-audits.md

docs(new-audits.md): Docs on new audits

---

lighthouse-cli/test/fixtures/seo/seo-tester.html
lighthouse-core/gather/gatherers/seo/meta-description.js
lighthouse-core/gather/gatherers/theme-color.js
lighthouse-core/gather/gatherers/viewport.js

core(meta-tag-gatherers): meta tag search should be case-insensitive

---

lighthouse-core/gather/driver.js

closes #3733 
things to consider:
* this might break folks who were running on bad hardware and needed to keep traces small (counter: it currently breaks for plenty of these sites at 30s already)
* scores will change from 0 to ~8 at sites with TTI at 30s

core(driver): increase default timeout to 45s

---

lighthouse-cli/test/fixtures/seo/seo-failure-cases.html
lighthouse-cli/test/fixtures/static-server.js
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/audits/seo/is-crawlable.js
lighthouse-core/config/default.js
lighthouse-core/config/seo.js
lighthouse-core/gather/gatherers/seo/meta-robots.js
lighthouse-core/test/audits/seo/is-crawlable-test.js

Closes #3182
Failing:
Passing:

new_audit(blocked-from-indexing): page is blocked from indexing

---

lighthouse-core/audits/predictive-perf.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/lib/dependency-graph/cpu-node.js
lighthouse-core/test/audits/predictive-perf-test.js

closes #3671 
closes #3593 
Minimal changes required here for converting FMP to FCP, basically just move the time boundary to FCP, removing the CPU layout tasks, and adding in the EvaluateScript tasks of blocking scripts (which really could have been part of FMP prediction too).
I also added redirects support since FCP was more radically impacted by missing redirect support than FMP was. I dug into a lot of the larger error cases (where error was >1s) and at this point small differences should not be used for decision making. 
Some notable examples:
* DevTools throttling limitations and approximation of just adding 600ms delay to everything greatly exaggerates impact of redirects (i.e. 3 redirects = 1.8 s instead of the correct result of ~
* Server response time was measured in seconds …

core(predictive-perf): predict FCP

---

lighthouse-cli/run.ts
lighthouse-cli/test/cli/run-test.js

cli: do not double quote chromeFlags

---

lighthouse-core/report/v2/renderer/report-ui-features.js
lighthouse-core/report/v2/templates.html

report(report-ui-features): Disable auto expansion of print option via report ui

---

docs/understanding-results.md
lighthouse-core/audits/audit.js
lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/consistently-interactive.js
lighthouse-core/audits/critical-request-chains.js
lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/audits/estimated-input-latency.js
lighthouse-core/audits/first-meaningful-paint.js
lighthouse-core/audits/speed-index-metric.js
lighthouse-core/closure/typedefs/Audit.js
lighthouse-core/closure/typedefs/AuditResult.js
lighthouse-core/report/v2/renderer/category-renderer.js
lighthouse-core/report/v2/renderer/report-renderer.js
lighthouse-core/test/audits/dobetterweb/dom-size-test.js
lighthouse-core/test/config/config-test.js

closes #2812 
I'd normally oppose removing this without a major version bump, but the value was almost always an english string like `< 1,000` rather than a number that people likely relied on, we also just removed the similarly useless `category` property without a major bump so blocking this seems inconsistent
I kept the existing target references in dom-size audit since those are explicitly in the description as to why you care and its just for making sense of the data in the cards. Still removed the overall optimalValue display.

core: remove optimalValue

---

lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js

`large.svg` starts loading almost exactly at FI on appveyor, leading to it to be pretty flakey since `offscreen-images` doesn't count images that start loading after FI. This PR just adds an artificial long task to push FI out a few more seconds to deflake things.
So far it's been passing consistently on appveyor over a few loads; will rerun multiple more times.
Also: since the `extendedInfo` is sorted by image size, added more useful expectations using the image file names, which should hopefully make the diff a little clearer for any future errors.

tests(smoke): add long task to byte-efficiency tester to deflake appveyor

---

lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
lighthouse-core/test/audits/dobetterweb/external-anchors-use-rel-noopener-test.js

Fixes #3079 
---
~PS: Happy to close this if @akonchady has another implementation in place already.~ https://github.com/GoogleChrome/lighthouse/issues/3079#issuecomment-336839105

core(audit): Ignore href=javascript:.* for rel=noopener audit

---

CONTRIBUTING.md
build/changelog-generator/index.js
build/changelog-generator/templates/template.hbs

Things that came up while generating latest changelog

misc(changelog): tweaks to changelog template and instructions

---

lighthouse-core/gather/connections/connection.js
lighthouse-core/gather/connections/cri.js
lighthouse-core/gather/driver.js

for assistance when working with puppeteer
ref #3837

core(driver): add driver.wsEndpoint()

---

docs/error-reporting.md
lighthouse-cli/cli-flags.js
lighthouse-cli/sentry-prompt.js

fixes #3854 
* docs clarity around "opt-out" and all that.
* include docs link from --help
* show docs link before providing CLI prompt

docs(error-reporting): improve clarity for opt-out folks

---

lighthouse-cli/sentry-prompt.js

fixes #3873
Lighthouse shouldn't fail when `configstore` hits an `EACCES` error. We also don't want to make a user who can't use `configstore` hit the 20 second timeout every time, so it seems like defaulting to false is the thing to do here.
Seemed better to have this handled within `askPermission` than by the caller. Promise wrapper will get a bit nicer when we can do async/await, but note that it's the `get` and `set` calls that try to access the file, not the `Configstore` constructor, and wrapping the two individually made a bit of a mess.

cli(sentry): handle configstore errors by not enabling error reporting

---

docs/readme.md

explicit port 9222 is required now for this usage

docs: fix mobile device testing example

---

lighthouse-core/lib/sentry.js

Since we have a catch() way back in CLI, it's unlikely we'll actually have an uncaught rejection, but this is insurance anyhow.
[Here's some reported unhandled rejections](https://github.com/GoogleChrome/lighthouse/issues?q=is%3Aissue+%22Unhandled+promise+rejections+are+deprecated%22+sort%3Acreated-desc)
Q: do we want to add any extra metadata to indicate this was unhandled?

misc(error-reporting): report unhandled promise rejections

---

CONTRIBUTING.md
lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
lighthouse-core/gather/computed/trace-of-tab.js
lighthouse-core/gather/connections/connection.js
lighthouse-core/lib/sentry.js
lighthouse-core/runner.js

now that we've had sentry in WPT and the volume shot up this makes some tweaks to make it a little more manageable
* adjusts error levels to more clearly see which are failed audits/which are warnings/which are fatal errors
* adds fingerprint to distinguish different protocol errors
* samples a few known errors that happen *a lot*

misc(error-reporting): tweak sentry levels and ignore list

---

lighthouse-cli/test/fixtures/seo/seo-failure-cases.html
lighthouse-cli/test/fixtures/seo/seo-tester.html
lighthouse-cli/test/fixtures/static-server.js
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/audits/seo/hreflang.js
lighthouse-core/config/default.js
lighthouse-core/config/seo.js
lighthouse-core/gather/gatherers/seo/hreflang.js
lighthouse-core/test/audits/seo/hreflang.js
package.json
yarn.lock

Closes #3177
Failing audit:
Successful audit:

new_audit(hreflang): document has a valid hreflang code

---

lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js

core(vulnerable-libs): add fix for recovering from bad versions

---

package.json
yarn.lock

Remediate security vulnerability in `ws@1.1.2` by updating to recent version. Here is the [security advisory](https://nodesecurity.io/advisories/550). 
closes https://github.com/GoogleChrome/lighthouse/issues/3948

deps: Bump ws to 3.3.2

---

docs/lantern.md

closes #3691 
before rushing off to improve accuracy, the next AI is on @vinamratasingal to draw up document on what we actually want to achieve accuracy with

docs: add lantern accuracy data

---

lighthouse-core/audits/seo/meta-description.js

Update help text meta-description audit to be more consistent with the other audits.

core(help-text): improve help text

---

lighthouse-cli/test/cli/run-test.js
lighthouse-cli/test/fixtures/static-server.js
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/lib/url-shim.js
lighthouse-core/test/lib/url-shim-test.js
package.json
yarn.lock

This is what I was thinking about for #3815. 
wdyt?

tests(smokehouse): adopt URLSearchParams for querystring manipulation

---

lighthouse-core/lib/web-inspector.js

this fixes a conflict when LH runs in the devtools worker:

core(web-inspector): keep all experiments disabled

---

lighthouse-core/audits/critical-request-chains.js

core(critical-request-chains): corrected help text

---

lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/mainthread-work-breakdown.js
lighthouse-core/test/audits/mainthread-work-breakdown-test.js

I noticed and fixed some inconsistencies
* main thread work breakdown was always showing in diagnostics, even if total cost was just 40ms. 
* bootup time audit was saying "is high" but only when  the audit was passing.
* now the failure threshold for the two audits is adjusted. 
- just JS bootup times costing more than 2s, show it. total main thread time costing more than 4s, show that.

report(perf-audits): adjust presentation of runtime cost audits

---

readme.md

The existing wording that was contributed was a bit awkward.
I think this is better, still highlights that it's a paid product by saying there's a free 14-day trial.

docs(readme): Update wording around Calibre being a paid product

---

lighthouse-core/audits/byte-efficiency/uses-webp-images.js

core(uses-webp): tweak text to be more next-gen focused

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
lighthouse-core/test/audits/dobetterweb/external-anchors-use-rel-noopener-test.js

Closes #3714 
Only filter anchor links that start with an http protocol for the `rel=noopener` audit.

core(rel=noopener-audit): Only test http/https links

---

lighthouse-core/gather/gather-runner.js
lighthouse-core/test/gather/gather-runner-test.js

closes #1978 according to feedback in #2461 
converts the assertPageLoaded into a soft failure that just fails every gatherer afterPass
if more than half of all artifacts failed due to page load failure then the error becomes fatal (like the case where you try to audit http://total-junk-hostname).

core(gather-runner): covert assertPageLoaded into soft failure

---

package.json
yarn.lock

one of the juicier bits we get out of this for HTTPArchive https://github.com/johnmichel/Library-Detector-for-Chrome/pull/102 (better react detection :D)

deps: bump js-library-detector

---

lighthouse-viewer/gulpfile.js

now we have both:
* https://googlechrome.github.io/lighthouse/plots/
* https://googlechrome.github.io/lighthouse/viewer/ (updated to 2.7.0!)

misc(viewer): retain /plots/ when deploying new viewer version

---

lighthouse-core/config/default.js

screenshot:
fixes #3599
The attached change already fixes's extension's order:
separately, i'm moving Perf to be first in DevTools' checkboxes. 
----------
Also a driveby fix on PWA's manual audits to match the manual audit text we used for a11y's.

report(categories): performance first, then pwa, then the others

---

lighthouse-core/audits/consistently-interactive.js
lighthouse-core/lib/network-recorder.js
lighthouse-core/test/audits/consistently-interactive-test.js
package.json

core(network-recorder): use findNetworkQuietPeriods for networkIdle

---

lighthouse-core/gather/computed/trace-of-tab.js

@patrickhulce: Add the error message when TracingStartedInPage event is missing. Otherwise the error message would be: Cannot read property 'args' of undefined.
PTAL.

core(trace-of-tab): throw error when TracingStartedInPage event is missing

---

lighthouse-core/gather/connections/extension.js
lighthouse-extension/app/manifest.json
lighthouse-extension/app/manifest_canary.json
lighthouse-extension/app/src/lighthouse-background.js
lighthouse-extension/app/src/lighthouse-ext-background.js
lighthouse-extension/gulpfile.js

Cut-paste job except for:
* `updateBadgeFn` passed as arg into `runLighthouseForConnection`
* `lighthouseIsRunning` is set within the `updateBadgeUI` method now
fixes #2014 (along with #4161)

core(extension): extract a new ext-bg file, splitting extn/devtools usecases

---

lighthouse-core/audits/seo/manual/mobile-friendly.js
lighthouse-core/audits/seo/manual/structured-data.js
lighthouse-core/config/default.js
lighthouse-core/runner.js

Adds two manual SEO audits.
Closes #3119
Closes #3183
Closes #3184

new_audit(seo): manual SEO audits

---

.travis.yml

yarn started issuing this warning for node 7:
> warning You are using Node "7.10.1" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
seems like a good time to cover our bases on 9.

tests(travis): test on Node 9, drop testing on Node 7

---

.gitignore
lighthouse-cli/cli-flags.js
lighthouse-cli/run.js
lighthouse-core/audits/byte-efficiency/unminified-javascript.js
lighthouse-core/config/config.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/gather/gatherers/scripts.js
lighthouse-core/index.js
lighthouse-core/lib/asset-saver.js
lighthouse-core/runner.js
lighthouse-core/test/audits/byte-efficiency/unminified-javascript-test.js
lighthouse-core/test/config/config-test.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/index-test.js
lighthouse-core/test/runner-test.js
lighthouse-core/test/scoring-test.js
lighthouse-extension/gulpfile.js
package.json
typings/externs.d.ts
yarn.lock

fixes #1806
The mystical -GAR feature.  Actually its just -GA for now. 
Here's how this works:
```sh
lighthouse -G http://example.com
lighthouse -A http://example.com
lighthouse -GA http://example.com
```
* `--gather-mode` and `--audit-mode` are the long versions of `-G` and `-A`.
* `config.auditResults` is removed. it was weird.
* assetSaver got a new impl of `saveArtifacts`, and added `loadArtifacts`
* --save-artifacts CLI flag was removed, as it was never really used and makes less sense in -G world. 
-------------------
* Decide if we want to rename these, as "gather" hasn't been really user-visible before. 
* Add `-G=./artifacts-save-path/`
* Add `-A=./artifacts-load-path/`

core(lifecycle): allow gathering & auditing to run separately

---

docs/hacking-tips.md
lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js
lighthouse-core/audits/accessibility/axe-audit.js
lighthouse-core/audits/audit.js
lighthouse-core/gather/gatherers/accessibility.js
lighthouse-core/report/v2/renderer/category-renderer.js
lighthouse-core/report/v2/renderer/report-renderer.js
lighthouse-core/report/v2/report-generator.js
lighthouse-core/scoring.js
lighthouse-core/test/report/v2/renderer/category-renderer-test.js
lighthouse-core/test/results/sample_v2.json
package.json
yarn.lock

This updates the accessibility report so it no longer counts non-applicable tests toward the user's score. Currently lighthouse gives folks an artificial "boost" to their a11y score because aXe was not filtering out tests which matched 0 nodes. That should be fixed in the next release of aXe (https://github.com/dequelabs/axe-core/pull/637).
This PR also updates how the number of passed/failed/notApplicable audits are reported by counting any grouped audits toward the total. Previously it was just counting the number of groups. So even though we have 35 non-manual a11y audits, it looked like we had far fewer. Here's the new look (note the 12 passed, 15 not applicable):

report(a11y): Don't count non-applicable a11y audits toward score

---

readme.md

these CLI options havent been updated in a while. some stale stuff in there. 🍞 
reformatted the large Output examples section for readability. 
Added -G/-A examples.

docs(readme): update CLI opts, output examples, add Lifecycle examples

---

lighthouse-core/audits/seo/font-size.js
lighthouse-core/gather/gatherers/seo/font-size.js
lighthouse-core/test/gather/gatherers/seo/font-size-test.js

Fixes #4184
`WebInspector.CSSStyleDeclaration`s have circular structure making them non-serializable.
I created `SimplifiedStyleDeclaration` type definition to make jsdoc comments more readable.

core(font-size): make font size artifact serializable

---

docs/releasing.md

docs(releasing): document the LH Release Process

---

lighthouse-core/audits/errors-in-console.js
lighthouse-core/test/audits/errors-in-console-test.js

Fixes #4188 
when looking at the [devtools protocol](https://chromedevtools.github.io/devtools-protocol/v8/Runtime/#type-ExceptionDetails). Exeption is an optional property, when not present we should use text.
I also added an extra test to cover this case.

core(errors-in-console): If exception info is not present use exception text

---

lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js

Quick change to vulnerability links so that Snyk can serve up a version of the vuln pages with information specific to the versions Lighthouse found.

report: Update vulnerability links

---

docs/understanding-results.md

little bit of followup on #4052 ;)
cc @robdodson

docs(results): describe audit result's notApplicable/error properties

---

lighthouse-core/audits/screenshot-thumbnails.js
lighthouse-core/gather/gatherers/viewport-dimensions.js

fixes #3884 
fixes https://sentry.io/google-lighthouse/lighthouse/issues/408391251/events/11708246287/
http://side.co is a site that triggers both errors

core(screenshots): fix getParsedImage of null

---

lighthouse-core/test/lib/traces/devtools-timeline-model-test.js
lighthouse-core/test/lib/traces/trace-parser-test.js

fixes https://travis-ci.org/GoogleChrome/lighthouse/jobs/326591475

tests(trace-parser): use fs over require

---

lighthouse-cli/cli-flags.js
lighthouse-cli/printer.js
lighthouse-cli/run.js

This was still hanging around. We can nuke it nowadays.

cli: remove legacy domhtml output

---

package.json
yarn.lock

Upgrade chrome-launcher to 0.10.1.
I wasn't sure why chrome-launcher does not have a `^` in package.json so feel free to decline this PR.

deps(chrome-launcher): Upgrade chrome-launcher

---

lighthouse-core/audits/errors-in-console.js
lighthouse-core/report/v2/renderer/details-renderer.js
lighthouse-core/report/v2/renderer/util.js
lighthouse-core/report/v2/report-styles.css
lighthouse-core/test/audits/errors-in-console-test.js
lighthouse-core/test/lib/url-shim-test.js
lighthouse-core/test/report/v2/renderer/details-renderer-test.js

1. you can see WAY more of the URL because good CSS.
2. meanwhile we're more aggressively eliding non-readable strings in the URL
partial fix for #3827 but its not totally complete.

report: more attractive table/URL rendering

---

lighthouse-cli/test/fixtures/seo/seo-failure-cases.html
lighthouse-cli/test/fixtures/seo/seo-tester.html
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/audits/seo/plugins.js
lighthouse-core/config/default.js
lighthouse-core/gather/gatherers/seo/embedded-content.js
lighthouse-core/gather/gatherers/seo/external-content.js
lighthouse-core/test/audits/seo/plugins.js

Fixes #3180 
Success:
Failure:
As I found out, world of embedding external content is very messy. There are many non-standard ways of embedding that still work (multiplied by the number of different browsers 😵).
My approach here was to focus on documented ways of embedding (docs from adobe, ms, oracle, mdn) and real-life uses on popular sites (video, games, showcases). It should cover most of the real-life uses, but I'm pretty sure there are some false positives and false negatives.
Some notes:
- it's common to do feature detection when embedding such content (esp. for flash with `swfobject.js`, but there is also `silverlight.js` and some code from oracle doing the same for java). We won't be able to detect that unless user has these plugins enabled.
- flash is often embedded as `<object …

new_audit(plugins): avoid plugins

---

lighthouse-core/lib/traces/trace-parser.js
lighthouse-core/scripts/run-mocha.sh
lighthouse-core/test/audits/bootup-time-test.js
lighthouse-core/test/audits/screenshot-thumbnails-test.js
lighthouse-core/test/audits/speed-index-metric-test.js
lighthouse-core/test/gather/computed/dtm-model-test.js
lighthouse-core/test/gather/computed/speedline-test.js
lighthouse-core/test/lib/asset-saver-test.js
lighthouse-core/test/lib/traces/trace-parser-test.js

This should make unexpected hangs more obvious and potentially failing/long tests will fail faster.

tests: remove global timeout, set timeouts individually

---

lighthouse-core/audits/bootup-time.js
lighthouse-core/test/audits/bootup-time-test.js

core(audit): Add 10ms threshold to bootup-time audits

---

docs/readme.md

In the current documentation, the example given does not pass the flags argument to `chromeLauncher.launch` which caused some initial confusion when trying to leverage any of the chromeFlags. It is not intuitive that flags should also be passed into the launch method.

docs: demo flags in example of programmatic use

---

lighthouse-extension/app/src/lighthouse-background.js

Missed this when I did https://github.com/GoogleChrome/lighthouse/pull/4162
But luckily we get to simplify the method in the devtools case.

extension(devtools): restore listenForStatus method for devtools build

---

lighthouse-core/lib/sentry.js

throttles our top remaining sentry errors

misc(sentry): update sampled errors list

---

lighthouse-core/audits/seo/manual/mobile-friendly.js

finalized here: https://github.com/GoogleChrome/lighthouse/issues/4248#issuecomment-358770783
fixes #4248 
i didnt include the sweet auto-URL population as that's a bit involved. Great idea for later though.

core(mobile-friendly): convey MFT covers add'l auditing

---

lighthouse-core/audits/webapp-install-banner.js
lighthouse-core/gather/gatherers/start-url.js
lighthouse-core/test/gather/gatherers/start-url-test.js

core(start-url): switch to plain old fetch

---

package.json

This adds a new yarn script (as discussed in #3953) which simplifies running the custom configuration required for the mixed-content audit.
@paulirish Could you PTAL to see if this is what you had in mind?

cli(yarn): Add mixed-content yarn script

---

lighthouse-cli/test/cli/run-test.js
lighthouse-core/gather/driver.js
package.json

Issue #4395 has the backstory. This PR has a few things going on:
* **primary fix:** wait only 9s load during run-test's roundtrip. No need to wait 45s if there's a problem loading the page.
* **driveby:** remove explicit timeout from istanbul's mocha call. (finishing #4224)
* **moot:** fix `istanbul ignore` statements. as detailed in #4395 they must be standalone (and spelled right). 
As a result of this PR, `yarn coverage` should be 36s faster, and no timeout error in the travis log. However the code coverage stats for the CLI are still incorrect and the roundtrip run is still not truly  successful.
This leads to a followup question: Should we have other success criteria for the run-test.js roundtrip test, like calculating TTI, etc?
Ref #4395 but doesn't close it.

tests(coverage): minimize impact of timeout due to istanbul's instrumentation

---

lighthouse-cli/run.js
lighthouse-core/audits/byte-efficiency/unminified-javascript.js
lighthouse-core/audits/consistently-interactive.js
lighthouse-core/audits/estimated-input-latency.js
lighthouse-core/audits/first-meaningful-paint.js
lighthouse-core/audits/speed-index-metric.js
lighthouse-core/gather/computed/first-interactive.js
lighthouse-core/gather/computed/speedline.js
lighthouse-core/gather/computed/trace-of-tab.js
lighthouse-core/gather/connections/connection.js
lighthouse-core/gather/connections/cri.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/errors.js
lighthouse-core/lib/sentry.js
lighthouse-core/lib/strings.js
lighthouse-core/runner.js
lighthouse-core/test/audits/consistently-interactive-test.js
lighthouse-core/test/gather/computed/first-interactive-test.js
lighthouse-core/test/gather/gather-runner-test.js
typings/externs.d.ts

closes #3598 
pulled the strings from the spreadsheet with some slight consistency modifications

core: centralize error strings

---

lighthouse-core/gather/gatherers/accessibility.js

[A new axe document on performance](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#section-4-performance) suggests safelisting the resultTypes you're interested in. This saves time generating unique selectors (which on mlb.com can take 4s). 
cc @dylanb
This reduces about a 1 second of runtime cost of axe on mlb.com. (13s to 12s with the https://github.com/dequelabs/axe-core/pull/699 PR)

core(a11y): aXe perf: only collect provided resultTypes

---

lighthouse-cli/test/smokehouse/a11y/run-tests.sh
lighthouse-cli/test/smokehouse/byte-efficiency/run-tests.sh
lighthouse-cli/test/smokehouse/dobetterweb/run-tests.sh
lighthouse-cli/test/smokehouse/offline-local/run-tests.sh
lighthouse-cli/test/smokehouse/perf/run-tests.sh
lighthouse-cli/test/smokehouse/redirects/run-tests.sh
lighthouse-cli/test/smokehouse/seo/run-tests.sh
lighthouse-cli/test/smokehouse/tricky-ttci/run-tests.sh
lighthouse-core/scripts/compile-against-devtools.sh
lighthouse-core/scripts/roll-to-devtools.sh
package.json

This isn't required in Yarn 1.0+ or NPM.
And now we kill off this warning:

misc(package): scripts don't require "--" for options to be forwarded

---

lighthouse-core/audits/mixed-content.js

This adds a link to the documentation in the helpText for the new mixed-content audit (#3953). The link should be live once the docs PR (google/WebFundamentals#5758) lands.

core(help-text-fix): Add link to docs for mixed-content audit

---

lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
lighthouse-core/test/gather/gatherers/dobetterweb/response-compression-test.js

I have followed the recommended approach but I am wondering if there is a better way to know the type of the file and if the extensions I added are enough and if not what can I refer to in order to get a full list of extensions.
#4039

core(dbw response compression): Exclude non binary files from auditing

---

lighthouse-core/lib/asset-saver.js

@patrickhulce
This fix that the logged out devtools log string is empty.

core(assets): json stringify devtools log

---

lighthouse-cli/bin.js
lighthouse-cli/cli-flags.js
lighthouse-cli/run.js
lighthouse-core/index.js
typings/externs.d.ts

Per discussion on #4344, it may be simpler to add a flag to lighthouse itself for the mixed content scan configuration rather than trying to do it through yarn/npm (as the yarn/npm invocations get unwieldy very fast).
This is an initial attempt at adding a `--mixed-content` flag that loads the mixed-content.js config if passed (essentially simplifying passing a custom config path to an included configuration file).
@paulirish WDYT?

cli(lighthouse): Add --mixed-content flag for triggering the mixed content audit

---

lighthouse-core/gather/gatherers/fonts.js
lighthouse-core/test/gather/gatherers/fonts-test.js

core(webfonts): Patches fonts gatherer so it doesn't throw an exception

---

lighthouse-cli/test/smokehouse/smokehouse.js

Based on recently having to poke around the output, here's a proposal to improve the readability of failures.
Two before & after examples, taken from recent failures:
changes
* display expected & found on top of eachother
* switch order so found comes next to "full found result"
* serialize objects, including regular expressions. no more `[Object object]`
* formatting

tests(smokehouse): improve smokehouse failure output

---

lighthouse-core/audits/accessibility/link-name.js
lighthouse-core/config/default.js
lighthouse-core/test/fixtures/dbw_tester-perf-results.json
lighthouse-core/test/results/sample_v2.json

misc(spelling): fix discernable to discernible

---

lighthouse-core/gather/gatherers/fonts.js

partial fix to address #4486 and prevent an infinite loop when getting an exception

core(fonts): fix infinite loop

---

lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/audits/byte-efficiency/uses-responsive-images.js

fixes https://github.com/GoogleChrome/lighthouse/issues/3508
previously, images that had dimensions of 0 were listed in both the "Properly size images" audit (uses-responsive-images) and the "Offscreen images" audit (offscreen-images).
This PR changes the name of offscreen to "Non-visible images" and "Properly size images" does not show an image if the area of the image was 0.
@midzer @tomayac @philipwalton @wardpeet does this sound good to you?

core(responsive-images): move images with no dimensions to offscreen audit

---

docs/puppeteer.md

docs(puppeteer.md): examples of combining the two

---

lighthouse-core/gather/computed/main-resource.js
lighthouse-core/test/gather/computed/critical-request-chains-test.js
lighthouse-core/test/gather/computed/main-resource-test.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/runner-test.js

this PR aligns main-resource gatherer logic with final URL logic from driver.js
https://github.com/GoogleChrome/lighthouse/blob/3030b4f0651fc4eb2634600d7cf0dbca43972b32/lighthouse-core/gather/driver.js#L611-L622
Fixes #4454
Fixes #4440

core(main-resource): adjust main resource identification logic

---

lighthouse-cli/test/fixtures/seo/seo-tester.html
lighthouse-core/audits/seo/font-size.js
lighthouse-core/gather/gatherers/seo/font-size.js
lighthouse-core/test/audits/seo/font-size-test.js

Fixes #4448
> Minimum legible font size: 12px (was 16px)
> Minimum percent legibility: 60% (was 75%)

core(font-size): recalibrate the legible font sizes

---

lighthouse-extension/gulpfile.js

broken by #4394 which moved where gatherers are required from, the browserify transform needed to be updated too
thanks to @wardpeet for noticing!

extension: fix issue where gatherers cannot be found

---

docs/readme.md

docs(programmatic): add caveat about removing artifacts

---

lighthouse-core/audits/bootup-time.js

Doc isn't live yet, but should be soon...

report: add docs link to bootup-time audit

---

docs/headless-chrome.md

Prioritizing headless now that it supports emulation.

docs(headless-chrome): switch to prioritize headless

---

lighthouse-core/audits/predictive-perf.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/lib/dependency-graph/network-node.js
lighthouse-core/lib/dependency-graph/simulator/connection-pool.js
lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/lib/dependency-graph/simulator/tcp-connection.js
lighthouse-core/test/audits/predictive-perf-test.js
lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js
lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js

* estimates the observed RTT of each origin and takes this into account when simulating
* estimates the server response time of each origin using *all* available records, instead of just the records involved in the graph (prior behavior responsible for 1st bug in list below)
* ignores observed connectionId from Chrome when simulating and creates its own set of connections instead
* fixes a bug where the pessimistic estimate could be smaller than the optimistic estimate due to different connections being used
* should substantially improve accuracy observed in LR when the connectionIds are all `0`
* reduces absolute estimate error by ~4% across the board (25% error -> 21% error, not 25% -> 24% 😉)
* marginally increases rank correlation on FCP, marginally decreases rank correlation on FMP, …

 core(lantern): improve RTT estimates

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js

core(render-blocking): handle amp-style stylesheets

---

lighthouse-core/audits/accessibility/document-title.js

Since the audit occurs in both the a11y and SEO categories, the new helpText now mentions both. The helpText links to a new reference on d.g.c/web that discusses both the a11y and SEO aspects of the audit. The previously-linked-to aXe doc only mentioned the a11y side. But that aXe doc is itself mentioned in the new reference. I also updated the failureDescription while I was here, since we agreed in group chat that contractions are more in-tune with the Lighthouse voice.
#polish

report(description): update helpText for document.title audit

---

package.json
yarn.lock

There's a number of important performance fixes in the latest axe-core release that will significantly improve the speed of LH (and in many cases allow the accessibility audits to complete successfully for sites with big dom).
Ref: dequelabs/axe-core/issues/696
Ref: dequelabs/axe-core/issues/701
Ref: dequelabs/axe-core/issues/702
Top work, @paulirish 💓

deps(axe-core): update axe-core to latest (beta) release

---

lighthouse-core/audits/seo/is-crawlable.js
lighthouse-core/config/default.js
lighthouse-core/gather/gatherers/seo/robots-txt.js
lighthouse-core/test/audits/seo/is-crawlable-test.js
package.json
yarn.lock

First part of #4356
Extends is-crawlable audit, so that it also verifies robots.txt file (besides meta tag and header).
This change adds a new dependency - [robots-parser](https://github.com/samclarke/robots-parser). It's a lightweight, well tested robots.txt parser with no dependencies.

core(is-crawlable): make sure that page is not blocked by robots.txt file

---

lighthouse-core/audits/audit.js
lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/byte-efficiency/unminified-css.js
lighthouse-core/audits/byte-efficiency/unminified-javascript.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/audits/byte-efficiency/unused-javascript.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
lighthouse-core/audits/byte-efficiency/uses-request-compression.js
lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
lighthouse-core/audits/byte-efficiency/uses-webp-images.js
lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js
lighthouse-core/audits/load-fast-enough-for-pwa.js
lighthouse-core/audits/redirects.js
lighthouse-core/audits/time-to-first-byte.js
lighthouse-core/report/v2/renderer/crc-details-renderer.js
lighthouse-core/report/v2/renderer/details-renderer.js
lighthouse-core/report/v2/renderer/util.js
lighthouse-core/report/v2/report-styles.css
lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
lighthouse-core/test/audits/byte-efficiency/total-byte-weight-test.js
lighthouse-core/test/audits/byte-efficiency/unused-css-rules-test.js
lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
lighthouse-core/test/audits/dobetterweb/link-blocking-first-paint-test.js
lighthouse-core/test/audits/dobetterweb/script-blocking-first-paint-test.js

moves us toward #4614 (and #3115), really helps out using details data
@paulirish did you still want to tackle the rest or is this for me? :) either way should we bring the issue in to ocho and assign it?

core: improved consumption of audit.details

---

CONTRIBUTING.md

The old page was deprecated and gave an automated redirect.

docs(contributing): fix link for closure annotations

---

.appveyor.yml
.travis.yml
lighthouse-extension/package.json
lighthouse-viewer/package.json
package.json

Moving to Node 8 as lowest supported version.
This is a breaking change, and we've already branched the `2.x` branch, as master is now our 3.0. ref #4333 
(Breaking  ecc3d06 out of #4640 for clarity)
fixes #3742

misc: drop support of Node 6

---

lighthouse-core/lib/url-shim.js
lighthouse-extension/gulpfile.js
package.json
yarn.lock

adds type checking to URLShim. removes `whatwg-url` now that Node 8 is required (fixes #1186)
This moves us back to extending `URL`, which was removed in #1407. If anyone can remember *why* we did that  at the timeplease let me know, but for now CLI and extension seem to work fine with this change.

core: make url-shim extend native URL module; add type checking

---

lighthouse-core/scripts/compile-against-devtools.sh

This at least allows you to reproduce the error from #4735 locally on a mac. (BSD sed vs GNU sed strikes again, ugh).
But it doesn't fix the actual error. I'm stumped on that so far.

tests(closure): fix BSD sed calls within compile-devtools

---

lighthouse-core/report/v2/renderer/report-renderer.js

This is most definitely a closure compiler bug. But this reordering fixes #4735

tests(closure): avoid failing closure compilation

---

.eslintrc.js
lighthouse-core/gather/connections/connection.js
lighthouse-core/gather/connections/cri.js
lighthouse-core/gather/connections/extension.js
lighthouse-core/gather/connections/raw.js
lighthouse-core/scoring.js
package.json
tsconfig.json
typings/externs.d.ts
yarn.lock

no significant changes, mostly typings (e.g. `runJsonCommand` returns an object, not a string).
The biggest shifts were just e.g. assuring the compiler we wouldn't emit events after the event emitter was disposed.
For the future, there are a lot of opportunities for better typing on these methods that take a string but return a bunch of different things via TS's conditional types (or plain overloading with string literal arguments)

core: add type checking to connection

---

lighthouse-core/gather/driver.js
lighthouse-core/lib/errors.js
lighthouse-core/lib/strings.js
lighthouse-core/test/gather/driver-test.js

fixes #4258
I was able to repro on all the URLs mentioned in the ticket: 
* https://openvegemap.netlib.re/#zoom=16&lat=48.85659&lon=2.35149
* https://dreamteamtrips.com/
* https://itsroo.com/
* https://anketa.alfabank.ru/land/pil-refin/
`Network.getResponseBody` is taking >5s to respond when provided particular requestIds. But it's quite odd. If i have devtools open at the same time, the devtools frontend can issue the exact same protocol method with the same requestId and it has no problem. (and apparently devtools and CLI also have no problem)
So this is particular to the extension.. sort of.
**Update:** the root bug appears to be an encoding issue in how the extension handles `chrome.debugger` payloads. Below is a bunch of details that supports that argument:
<details>
here's the 4 …

core(driver): add timeout to getRequestContent

---

lighthouse-core/audits/is-on-https.js
lighthouse-core/test/audits/is-on-https-test.js

fixes [crbug.com/810709](https://bugs.chromium.org/p/chromium/issues/detail?id=810709)

core(is-on-https): consider about:* secure

---

lighthouse-core/audits/audit.js
lighthouse-core/gather/gatherers/gatherer.js
tsconfig.json
typings/externs.d.ts

having typing here helps in a number of places and was easy to pull out since they're relatively isolated. This is just the base classes...all the implementing classes are untouched (and unchecked)

core: add type checking to audit and gatherer base classes

---

lighthouse-cli/bin.js
lighthouse-core/audits/audit.js
lighthouse-core/gather/gatherers/gatherer.js
lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/report/v2/renderer/util.js
package.json
tsconfig.json
typings/audit.d.ts
typings/externs.d.ts
typings/gatherer.d.ts
yarn.lock

moves public interfaces of Audit and Gatherer to `audit.d.ts` and `gatherer.d.ts`. This fixes the problem that typedefs on a class (e.g. `Audit`) are only local and aren't actually exposed on that module when required elsewhere.
Also changes the product of `Audit.audit()` to `LH.Audit.Product` from `LH.AuditResult`, which allows `LH.AuditFullResult` (which is actually in the LHR) to just be `LH.Audit.Result`. Happy to bikeshed on these, though :)
Also update to typescript 2.8 (rc) because there's a bug in 2.7 when it wasn't actually checking optional properties when in JS files (not using any new features yet). Can move over to 2.8 when it hits release very soon.

misc(tsc): reorganize and expose external interfaces

---

lighthouse-core/audits/audit.js
lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/mainthread-work-breakdown.js
lighthouse-core/report/v2/renderer/util.js

closes #4521 
I picked the thresholds so that the score turns yellow at whatever the previous threshold was
this also changes the base audit class so that the `failureDescription` is only used if we mark the audit not in green as it was strange to see "JavaScript bootup time is too high: 99"

core: convert diagnostics to numeric scores

---

lighthouse-core/gather/gatherers/dobetterweb/domstats.js

fixes https://sentry.io/google-lighthouse/lighthouse/issues/408582172/ our 6th most common error.
error is "Set is not a constructor" always coming from `elementPathInDOM`

core(domstats): useIsolation within domstats

---

lighthouse-core/gather/gatherers/image-usage.js

fixes https://sentry.io/google-lighthouse/lighthouse/issues/407848291/.. our 4th most common error!
It's reproducible on https://www.habitatetjardin.com/ with this image (https://i.habitatetjardin.com/images/bandefin_jardin.gif), though there's probably another URL that's a tad more minimal.

core(img-usage): handle invalid images within determineNaturalSize

---

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js

tests(smokehouse): adjust byte efficiency CPU multiplier

---

lighthouse-extension/package.json
lighthouse-extension/yarn.lock

without this, #4792 fails in `yarn build-extension`
see https://github.com/substack/astw/pull/14

deps(browserify): update deep transitive dependency to use recent acorn

---

lighthouse-cli/cli-flags.js
lighthouse-core/runner.js
lighthouse-core/test/runner-test.js
readme.md
typings/externs.d.ts

Enable this:
```
lighthouse -G=./cnn_artifacts http://cnn.com
...
lighthouse -A=./cnn_artifacts http://cnn.com
```
Path is resolved via pwd, but absolute paths are allowable, too.

core(runner): add custom folder support to -G/-A

---

package.json
typings/audit.d.ts
typings/externs.d.ts
typings/gatherer.d.ts
yarn.lock

`vscode-chrome-debug-core` has up-to-date type defs for the protocol. Pull those in until https://github.com/ChromeDevTools/devtools-protocol/issues/55 is fixed
This exposes the types on `LH.Crdp.*` (e.g. `LH.Crdp.Network.Response`). Happy to bikeshed.
Once again github is tricked by indentation. Check out [?w=1](https://github.com/GoogleChrome/lighthouse/pull/4816/files?w=1) for a better diff

core(tsc): add type defs for Chrome Remote Debugging Protocol

---

lighthouse-core/audits/seo/is-crawlable.js

Fixes #4818 
It looks like #4616 was created before is-crawlable was merged causing this file to be overlooked. I searched for other similar issues, but found none.

core(is-crawlable): fix empty row in the details table when showing an URL

---

package.json
patches/robots-parser+1.0.2.patch
yarn.lock

I've tried creating a browserify transform that replaces `request('url')` calls with `request('path/to/url-shim.js')`. It worked, but uncovered another issue - robots-parser is using `url.path` that doesn't exists on the web and is deprecated in node. So I decied to go with https://github.com/ds300/patch-package as suggested by @patrickhulce and @wardpeet.
Fixes #4794, but nothing will show up in the details table due to #4818

deps(robots-parser): patch robots-parser to work in both node and browser env

---

lighthouse-core/audits/seo/font-size.js
lighthouse-core/audits/seo/link-text.js

developers.google.com docs for [font-size](https://developers.google.com/web/tools/lighthouse/audits/font-sizes) and [link-text](https://developers.google.com/web/tools/lighthouse/audits/descriptive-link-text) are up, time to update the links!
cc @kaycebasques @rviscomi 
Part of #4355

core(font-size, link-text): update docs links

---

lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js
lighthouse-extension/test/extension-test.js

fixes https://travis-ci.org/paulirish/lighthouse/jobs/356048954#L602
huge 👏 to @paulirish for struggling through layers of docker/extension/puppeteer to get me a devtools log of this happening

core(network-analyzer): more distrustful of chrome connection info

---

lighthouse-core/gather/gatherers/start-url.js
lighthouse-core/test/gather/gatherers/start-url-test.js

(This is a merge into #4710) 
This is reusing the exact same new logic from 4710, just separated a bit.
Only interesting things:
1. using `isReadFailure` boolean to indicate if we should bail and fail before trying a `fetch`
1. added a timeout to make sure we're not waiting forever for a matching network request
1. more comments & jsdoc

core(start-url): reorganize start_url gatherer

---

lighthouse-cli/test/fixtures/manifest.json
lighthouse-cli/test/fixtures/offline-ready.html
lighthouse-cli/test/smokehouse/offline-config.js
lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js
lighthouse-cli/test/smokehouse/pwa-expectations.js
lighthouse-core/gather/gatherers/start-url.js
lighthouse-core/test/gather/gatherers/start-url-test.js

Tests are broken but I want some feedback on this one.
is this a good approach? It seems to work on some urls I've tested but should test more of them
It fixes #2576

core(start_url): fix start_url audit while offline

---

patches/robots-parser+1.0.2.patch

Our new patch leaves out node 6 out in cold:
https://travis-ci.org/GoogleChrome/lighthouse/jobs/357025749#L634
node 6.13 has `require('url').URL` but its a month old and no other node 6 has it. 
so we'll add this backwards-compat support for the rest of node 6's out there.
This PR is for branch2.x only.
Konrad has an upcoming PR to roll latest `robots-parser` (which will now be node 7+ only).
Audience-wise: this patch only matters for our Node 6 (>6.0.0 and [<6.13.0](https://github.com/nodejs/Release/issues/208#issuecomment-364697107)) CLI users

core: add node 6 support to (patched) robots-parser

---

lighthouse-core/report/v2/renderer/report-renderer.js

Needed for https://chromium-review.googlesource.com/#/c/974178/

report: add jsdoc for lhr.artifacts

---

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/load-fast-enough-for-pwa.js
lighthouse-core/config/default.js
lighthouse-core/gather/driver.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/lib/emulation.js
lighthouse-core/lib/sentry.js
lighthouse-core/report/v2/renderer/report-renderer.js
lighthouse-core/report/v2/templates.html
lighthouse-core/runner.js
lighthouse-core/test/gather/driver-test.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js
lighthouse-core/test/report/v2/renderer/report-renderer-test.js
tsconfig.json
typings/externs.d.ts

ok followup to ongoing work for config settings, I had to draw the line somewhere to keep this reasonable size, so in this PR it simply removes the two flags and changes our existing logic to use the throttling object instead.
upcoming PRs will have the 'simulate' throttlingMethod to actually return simulated metrics, but already at this stage you can do awesome stuff like `lighthouse --throttling.requestLatency 2000` 😃 
I started to do the other constants cleanup here, but it started to balloon the PR
closes #4871

core(config): switch to throttling settings object

---

readme.md

Fixes #4899 
Co-authored-by: Michiel van Spaendonck <mvanspaendonck@users.noreply.github.com>

docs: remove dated domhtml reference from README.md

---

lighthouse-core/gather/connections/connection.js
lighthouse-core/gather/connections/extension.js
lighthouse-core/gather/driver.js
lighthouse-core/lib/emulation.js
lighthouse-core/lib/errors.js
lighthouse-core/scripts/extract-crdp-mapping.js
typings/crdp-mapping.d.ts
typings/protocol.d.ts

This PR adds type checking/inference for `Driver.sendCommand` (to go along with typing events in #4886).
Like #4886, this PR has changes to `scripts/extract-crdp-mapping.js` to extract all the protocol commands which are then written to `typings/crdp-mapping.d.ts`. Again, hopefully most of this can be upstreamed into `devtools-protocol`. This time the types need both the options `params` object (if any) associated with the command but also the command's return type (if any).
The other set of changes are in `Driver`, `Connection`, and `ExtensionConnection` (everything else is just minor fixes for any type errors that popped up after all the above changes). This time `sendCommand` is pulled out of the class bodies for stricter typing. Getting the typing correct is a little harder than it …

core(tsc): add type checking to remote protocol commands

---

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/byte-efficiency/unminified-css.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/audits/byte-efficiency/unused-javascript.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/audits/consistently-interactive.js
lighthouse-core/gather/computed/critical-request-chains.js
lighthouse-core/gather/computed/main-resource.js
lighthouse-core/gather/computed/network-records.js
lighthouse-core/gather/computed/network-throughput.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/gather/computed/pushed-requests.js
lighthouse-core/gather/devtools-log.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/gather/gatherers/scripts.js
lighthouse-core/lib/dependency-graph/cpu-node.js
lighthouse-core/lib/dependency-graph/network-node.js
lighthouse-core/lib/dependency-graph/simulator/connection-pool.js
lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/lib/network-recorder.js
typings/externs.d.ts
typings/gatherer.d.ts
typings/web-inspector.d.ts

easy change to add types to `DevtoolsLog` and `NetworkRecorder` since we already have all the crdp event types.
Moved @patrickhulce's existing work on `NetworkRequest` to a `LH.WebInspector` namespace (since that's how we've nested it in our not-actually-type-checking past) and added the additional properties we needed to the interface. 
We can probably continue to add properties as we go (seems ok?), though we do need to be careful about optional properties on the interface because the state we deal with these requests (after passing through NetworkRecorder which requires the full request lifecycle) is quite different than the [initial constructed object](https://github.com/ChromeDevTools/devtools-frontend/blob/cfbe097a93de280bc99ca1cab1689335d5999115/front_end/sdk/NetworkRequest.js#L43-L …

core(tsc): add types for DevtoolsLog and NetworkRecorder

---

lighthouse-core/audits/accessibility/image-alt.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
lighthouse-core/audits/mainthread-work-breakdown.js
lighthouse-core/audits/uses-rel-preload.js
lighthouse-core/test/results/sample_v2.json

This PR fixes typos in `helpText`s:
* missing spaces between some sentences
* missing periods at the end of some sentences

report(helptext): fix typos

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener.js

This fixes #2482 and updates #2485 fixing conflicts.
The added tests were checked with ./lighthouse-cli/test/smokehouse/dobetterweb/run-tests.sh
Not sure why the byte-efficiency test is failing in appveyor, it happened to me too locally, but I haven't made any changes that would affect it from what I can tell.

core(noopener-audit): noreferrer implies noopener

---

lighthouse-core/lib/network-recorder.js

Introduced in #4918, `networkRecorder.once()` calls are being rerouted to `networkRecorder.on()`, which isn't great :)

core(network-recorder): fix typo in once() call on super

---

lighthouse-core/config/fast-config.js

We want a11y and SEO for fast-mode LR on 2.x now that we're not prioritizing PSI-parity speed.

core(fast-config): bring back a11y and SEO categories

---

lighthouse-extension/app/src/lighthouse-background.js

@patrickhulce 
We pass flags like disableDeviceEmulation from lightrider in options.flags, which used to work. It is broken now due to "unify config and CLI settings".
PTAL.
Thanks!

extension: Pass flags from options in runLighthouseForConnection

---

lighthouse-core/audits/audit.js
lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/audits/consistently-interactive.js
lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/audits/estimated-input-latency.js
lighthouse-core/audits/first-interactive.js
lighthouse-core/audits/first-meaningful-paint.js
lighthouse-core/audits/mainthread-work-breakdown.js
lighthouse-core/audits/speed-index-metric.js
lighthouse-core/config/config.js
lighthouse-core/runner.js
lighthouse-core/test/audits/bootup-time-test.js
lighthouse-core/test/audits/byte-efficiency/total-byte-weight-test.js
lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
lighthouse-core/test/audits/consistently-interactive-test.js
lighthouse-core/test/audits/dobetterweb/dom-size-test.js
lighthouse-core/test/audits/estimated-input-latency-test.js
lighthouse-core/test/audits/first-meaningful-paint-test.js
lighthouse-core/test/audits/mainthread-work-breakdown-test.js
lighthouse-core/test/audits/speed-index-metric-test.js
lighthouse-core/test/config/config-test.js
typings/audit.d.ts

core: add default audit options with scoring

---

lighthouse-cli/bin.js
lighthouse-cli/run.js
lighthouse-core/gather/computed/metrics/lantern-consistently-interactive.js
lighthouse-core/gather/computed/metrics/lantern-first-contentful-paint.js
lighthouse-core/gather/computed/metrics/lantern-first-meaningful-paint.js
lighthouse-core/gather/computed/metrics/lantern-metric.js
lighthouse-core/gather/connections/cri.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/index.js
lighthouse-core/lib/emulation.js
lighthouse-core/lib/errors.js
lighthouse-core/runner.js
lighthouse-core/test/gather/gather-runner-test.js
typings/artifacts.d.ts
typings/audit.d.ts
typings/config.d.ts
typings/externs.d.ts
typings/gatherer.d.ts
typings/web-inspector.d.ts

adding types was fairly straightforward.
I did have to async/await two functions: `GatherRunner.afterPass` (to get the compiler to realize all sorts of things aren't `|undefined` by the end of it) and `GatherRunner.collectArtifacts` (to isolate the type switcheroo from a dynamic collection of gatherer results to `LH.Artifacts`), but the translation was fairly mechanical and all existing tests were unchanged. They also look wayyy better than before :)
Also
- split out an `artifacts.d.ts` file to start collecting artifact types
- split out an `config.d.ts` file, not marking a difference between the JSON form that's expected as input to `Config` and the normalized type coming out of the other side (e.g. `LH.Config.PassJson` vs `LH.Config.Pass`). With any luck the second form won't be …

core(tsc): add type checking to gather-runner

---

lighthouse-core/audits/consistently-interactive.js
lighthouse-core/closure/typedefs/ComputedArtifacts.js
lighthouse-core/gather/computed/first-interactive.js
lighthouse-core/gather/computed/metrics/consistently-interactive.js
lighthouse-core/gather/computed/metrics/lantern-consistently-interactive.js
lighthouse-core/gather/computed/metrics/lantern-first-meaningful-paint.js
lighthouse-core/gather/computed/metrics/lantern-metric.js
lighthouse-core/gather/computed/metrics/metric.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/gather/computed/trace-of-tab.js
lighthouse-core/lib/errors.js
lighthouse-core/lib/traces/tracing-processor.js
lighthouse-core/runner.js
lighthouse-core/test/audits/consistently-interactive-test.js
lighthouse-core/test/gather/computed/metrics/consistently-interactive-test.js
typings/artifacts.d.ts
typings/gatherer.d.ts

progress toward #4872, starting with just one to make sure we like how it looks. will follow up with others if this looks good
review timer according to #4934 has this deadline at 4/10 10:05am :)

core(metrics): move TTCI to computed artifact

---

lighthouse-core/audits/first-contentful-paint.js
lighthouse-core/config/default-config.js
lighthouse-core/gather/computed/metrics/consistently-interactive.js
lighthouse-core/gather/computed/metrics/first-contentful-paint.js
lighthouse-core/gather/computed/metrics/metric.js
lighthouse-core/lib/errors.js
lighthouse-core/test/audits/first-contentful-paint-test.js
lighthouse-core/test/gather/computed/metrics/first-contentful-paint-test.js
typings/artifacts.d.ts

core(metrics): add FCP metric

---

.eslintrc.js
lighthouse-core/gather/devtools-log.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/asset-saver.js
lighthouse-core/lib/network-recorder.js
lighthouse-core/lib/traces/pwmetrics-events.js
package.json
typings/artifacts.d.ts
typings/externs.d.ts
typings/gatherer.d.ts
yarn.lock

another step on the way to typing the LHR pipeline, but was self contained enough that I split it out for easier review. Adds types to `asset-saver.js` and a few places changes due to that touch, like e.g. making a type alias for `LH.DevtoolsLog` (instead of (`Array<LH.Protocol.RawEventMessage>` :).
`asset-saver.js` is mostly the same except for indenting, so probably easier to review with [?w=1](https://github.com/GoogleChrome/lighthouse/pull/4949/files?w=1).
With the use of object spread, I moved our minimum node engine to 8.9 (the [first Node 8 LTS release](https://nodejs.org/en/blog/release/v8.9.0/)) and bumped our eslint to support what it calls `ecmaVersion` 2018.

core(tsc): add type checking to asset-saver

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/audits/dobetterweb/uses-http2.js
lighthouse-core/audits/is-on-https.js
lighthouse-core/test/audits/dobetterweb/uses-http2-test.js
lighthouse-core/test/audits/is-on-https-test.js

should fix our recent CI flakes too :)

core: de-dupe URLs in is-on-http, uses-http2

---

lighthouse-cli/test/smokehouse/run-smoke.js

brendan was running into this:
It was a fairly stupid error, but wasn't being caught. 
Lesson learned is that the top-level async invocation always needs a catch. ;)

tests: fix run-smoke handoff of testResults

---

lighthouse-core/scripts/cleanup-LHR-for-diff.js

tests: exclude audit helpText from 'yarn diff:sample-json' assertion

---

lighthouse-core/config/config.js
lighthouse-core/config/constants.js
lighthouse-core/gather/driver.js
lighthouse-core/test/config/config-test.js
typings/config.d.ts
typings/externs.d.ts

alternative to #4958
this brings back -A, it didn't come out quite as clean as I had hoped, but it is typesafe which is kinda nice :)

core(config): clean flags for settings

---

lighthouse-core/audits/audit.js
lighthouse-core/audits/seo/robots-txt.js
lighthouse-core/config/config.js
lighthouse-core/lib/asset-saver.js
lighthouse-core/runner.js
lighthouse-core/scoring.js
lighthouse-core/test/lib/asset-saver-test.js
lighthouse-core/test/runner-test.js
lighthouse-core/test/scoring-test.js
package.json
typings/artifacts.d.ts
typings/audit.d.ts
typings/config.d.ts
typings/lhr.d.ts
typings/result.d.ts
yarn.lock

also adds `result.d.ts` to type the full LHR and adds more types to `config.d.ts` (though it still needs a lot of work in combo with typing `config.js`).

core(tsc): add type checking to runner

---

lighthouse-core/audits/screenshot-thumbnails.js
lighthouse-core/lib/errors.js
lighthouse-core/test/audits/screenshot-thumbnails-test.js

followup fix as promised in #4951 
(easier with https://github.com/GoogleChrome/lighthouse/pull/4965/files?w=1)

core(screenshots): align filmstrip to observed metrics

---

.travis.yml
lighthouse-core/gather/gatherers/dobetterweb/js-libraries.js
lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
lighthouse-core/gather/gatherers/seo/robots-txt.js
lighthouse-core/lib/dom-helpers.js
package.json

Since:
- #4748 moved the smoke test runner to pure js
- `nyc` supports merging code coverage from any tests run in child processes
- `codecov` [supports uploading multiple coverage reports](https://docs.codecov.io/v4.3.6/docs/flags)
it's now easy to add smoke test coverage :)
Run locally with `yarn coverage:smoke` and on codcov you get little `unit`/`smoke` tabs at the top of file views (e.g. [`report-generator.js`](https://codecov.io/gh/GoogleChrome/lighthouse/src/2a9a772fa8bb57ff6b308251789cd0ad58c79355/lighthouse-core/report/v2/report-generator.js)). In codecov you seem to only get those tabs in individual files, both tabs are selected at first by default, and the coverage numbers on the left may be the sum of the two? So the view is a little shaky if you're interested in comparing …

tests(smoke): add smoke test code coverage

---

lighthouse-core/audits/predictive-perf.js
lighthouse-core/gather/computed/first-interactive.js
lighthouse-core/gather/computed/metrics/lantern-first-cpu-idle.js
lighthouse-core/test/gather/computed/metrics/lantern-first-cpu-idle-test.js
typings/artifacts.d.ts

I realized that we can realistically carry over all of our existing metrics in lantern world, and really FCPUI is the only one that I didn't have an impl of yet
this just reuses the graphs and coefficients of TTI combined with the existing algorithm for first interactive that does shortening window size/task clusters/etc
by reusing the graphs and coefficients of TTI we will also always give consistent answers on TTI/TTFCPUI because in the worst case, the start of the quiet window will be the last long task (which is equal to TTI estimate)
accuracy is really quite good, spearman's rho of ~0.82, which is slightly worse than TTI but better than FCP/FMP. MAPE of ~30%, which is nearly identical to TTI absolute error

core(metrics): add first CPU idle lantern metric

---

lighthouse-core/audits/predictive-perf.js
lighthouse-core/gather/computed/metrics/lantern-speed-index.js
lighthouse-core/test/gather/computed/metrics/lantern-speed-index-test.js

closes #4639 
blocked from merging on #4966 
predicts speed index by using the real speed index as the optimistic estimate and a layout-based speed index approximation from the pessimistic TTI graph as the pessimistic estimate
accuracy is decent. probably wouldn't recommend making it a headline metric as-is, but correlates slightly better than FCP (less than TTI/TTFCPUI)
spearman's rho ~.78, MAPE ~47%

core(metrics): add lantern speed index

---

lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/audits/seo/canonical.js
lighthouse-core/test/audits/seo/canonical-test.js

We were failing when multiple canonical links were provided (as suggested by the docs). [John says](https://github.com/GoogleChrome/lighthouse/issues/3178#issuecomment-381181762) that we shound only fail if URLs are different.
Closes #3178

core(canonical): pass when there are multiple identical canonical links

---

lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/gather/gatherers/image-usage.js
lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js

should fix https://twitter.com/dougsillars/status/984786614156189697

core(image-usage): use min of resourceSize/transferSize

---

lighthouse-core/gather/gatherers/seo/canonical.js
lighthouse-core/gather/gatherers/seo/crawlable-links.js
lighthouse-core/gather/gatherers/seo/embedded-content.js
lighthouse-core/gather/gatherers/seo/font-size.js
lighthouse-core/gather/gatherers/seo/hreflang.js
lighthouse-core/gather/gatherers/seo/meta-description.js
lighthouse-core/gather/gatherers/seo/meta-robots.js
lighthouse-core/gather/gatherers/seo/robots-txt.js
tsconfig.json
typings/artifacts.d.ts

except only some basic fixes in font-size for now, because it really likes mutating types and it calls into WebInspector stuff :P
No functional changes.

core(tsc): add type checking to seo gatherers

---

lighthouse-cli/test/smokehouse/run-smoke.js

so #4988 didn't fully fix the issue (https://travis-ci.org/GoogleChrome/lighthouse/jobs/368349837), we're still seeing timeouts for the 2 site batches, a single test seems to take up to 173s, so seems like we need double the time on travis

tests(smokehouse): increase timeout

---

docs/readme.md
docs/throttling.md
lighthouse-cli/cli-flags.js
lighthouse-cli/test/smokehouse/smokehouse.js
package.json
plots/README.md
readme.md

doing some cleanup on the remaining references to the old `disable-X-throttling` flags, we should probably explore an automated way of keeping those flags in sync with our `SettingsJson` typedefs now that all the options are available to CLI
not sure if it's really better to piecemeal update readme like this or do a pass over our docs and re-evaluate if we still want to tell people to be doing things like we are

cli: update documented throttling flags

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html

this causes an issue with the golden lhr diff test if the artifacts are regenerated. Since `update:sample-artifacts` is run with a random port, this request generates an extra error, a resource is missing, etc vs when run with the original 10200 port.
Rather than use port 10200 for `update:sample-artifacts`, this just makes the href fully relative as we now trust the `URL` constructor much more than we used to, and there hasn't been a `new URL()` in `critical-request-chains.js ` for quite some time anyways :)

tests: drop port number from dbw_tester for golden lhr

---

typings/lhr-lite.d.ts

ready for feedback on design/implementation of the design :)

core(lhr): lhr-lite type declaration

---

lighthouse-core/gather/gatherers/fonts.js
package.json
typings/artifacts.d.ts
typings/externs.d.ts
yarn.lock

one of the big @ts-nochecked gatherers

core(tsc): add type checking to fonts gatherer

---

lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
lighthouse-core/gather/gatherers/image-usage.js
lighthouse-core/gather/gatherers/js-usage.js
lighthouse-core/gather/gatherers/start-url.js
typings/artifacts.d.ts
typings/externs.d.ts
typings/web-inspector.d.ts

along with #5018, add types (and descriptions) to all default artifacts
also adds types to `image-usage.js` and `start-url.js`, which were more straightforward than `fonts.js` (which is why that was split out and those aren't)
this leaves `domstats.js`, `tags-blocking-first-paint.js`, and `font-size.js` with `@ts-nocheck` internally, but their output types and API are typed, so it's at least contained within those files. Maybe someday we'll get to them :)

core(tsc): gatherer type-checking cleanup

---

typings/lhr-lite.d.ts

proposal to rename.
Helps to differentiate between the item-level `wastedMs`. Got mixed up between the two just a moment ago. :)

core(lhr): savingsMs, savingsBytes

---

lighthouse-core/gather/computed/metrics/consistently-interactive.js
lighthouse-core/lib/errors.js
lighthouse-core/lib/network-recorder.js
lighthouse-core/test/gather/computed/metrics/consistently-interactive-test.js
typings/web-inspector.d.ts

updates TTI definition based on v1.0 in the [doc](https://docs.google.com/document/d/1yE4YWsusi5wVXrnwhR61j-QyjK9tzENIzfxrCjA1NAk/edit#heading=h.yozfsuqcgpc4)
- use FCP instead of FMP
- ignore non-GET network requests
- ignore failed/unfinished network requests
NOTE: this PR does *not* tweak our decision of when to stop tracing, just the computation for observed TTI
ref #4629 #5008 #4333

core(tti): update ignorable network requests and start point

---

.travis.yml
lighthouse-cli/test/fixtures/static-server.js
lighthouse-viewer/package.json
lighthouse-viewer/test/viewer-test-pptr.js
package.json

As we start major work again on the report, it'd be good to have an easy way to verify we aren't breaking viewer. While viewer does already have compile and (a few) basic unit tests, this PR rips off @wardpeet's hard work from #4640 to make a pptr integration test for viewer as well.
Ideally we'd extract some sort of "use puppeteer to test a live report interface" test and have each individual directory file only in charge of setup and teardown, but I think(?) this is sufficient for now as we have more pressing matters.

tests(viewer): add pptr test for viewer

---

lighthouse-core/audits/byte-efficiency/render-blocking-resources.js

core(render-blocking): address followup feedback

---

lighthouse-cli/run.js
lighthouse-cli/test/cli/run-test.js
lighthouse-core/runner.js

the destructure in `saveResults` broke cases where gatherMode existed runner early with an `undefined` runnerResult
plenty of others ways to solve this. happy to do them, though this seemed like the most non-invasive.
-----
driveby fix: avoid comparing `output` much like gather/auditMode as the `output` is irrelevant to a gather run.

tests: fix cli handling empty runnerResult during gatherMode

---

lighthouse-core/gather/gatherers/fonts.js
package.json
yarn.lock

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25045 landed, so can pull out the TODOs adding support for the `FontFace` props added in the last year.

core(tsc): update for new @types/css-font-loading-module

---

lighthouse-core/audits/audit.js
lighthouse-core/audits/dobetterweb/appcache-manifest.js
lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
lighthouse-core/audits/dobetterweb/geolocation-on-start.js
lighthouse-core/audits/dobetterweb/no-document-write.js
lighthouse-core/audits/dobetterweb/no-mutation-events.js
lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
lighthouse-core/audits/dobetterweb/no-websql.js
lighthouse-core/audits/dobetterweb/notification-on-start.js
lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
lighthouse-core/audits/dobetterweb/uses-http2.js
lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js
lighthouse-core/audits/violation-audit.js
lighthouse-core/lib/event-helpers.js
lighthouse-core/test/lib/event-helpers-test.js
lighthouse-core/test/results/sample_v2.json
package.json
tsconfig.json
typings/audit.d.ts
yarn.lock

the only major cleanups are in the `no-vulnerable-libraries.js.js` (lots of mutations) and `event-helpers.js` (simplified so that the type checker could follow along).
The golden lhr changes are eliminating the duplicate vulnerability listings (because the original library objects are no longer mutated) and taking out the `label` entry on the event listeners since it appears to only be set, not read, and it's just a duplicate of the line/col info anyways.

core(tsc): add type checking to dbw audits

---

lighthouse-core/lib/dependency-graph/network-node.js
lighthouse-core/lib/dependency-graph/simulator/connection-pool.js
lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
lighthouse-core/test/audits/byte-efficiency/render-blocking-resources-test.js
lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js
lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js
typings/web-inspector.d.ts

found a good bug while working on #5070 that's relatively independent
basically if you try to call network analysis before you create a network node from the network record, all the origins will be undefined and so the `additionalRttByOrigin` and `serverResponseTimeByOrigin` are totally useless for the future cached runs that *do* properly create a network node from the network record. We originally did this because calling `new URL()` to get the origin was super expensive and these are somewhat hot paths, while the function call + getter is a bit more expensive, it's still not nearly as bad as `new URL`. Seems OK until it crops up as a bottleneck
this PR reverts the `.origin` dance we do on network records and just uses `.securityOrigin()` on the record, if it becomes a big bottleneck …

core(lantern): use securityOrigin on record

---

lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html

@hwikyounglee asked for two changes. 1) tooltip arrow points to the number. 2) hover background color.
Also made a few changes:
* tooltip doesnt start showing up for 900ms now (instead of 500ms) 
* tooltip trigger boundary is smaller. It matches the gray background (and doesn't extend to the line)
* left/right padding on these boxes so their container extends a little farther than the text. I'll be applying this padding to other elements in the report, as the mocks suggest. see "padding illustration" below.
before and after gif:
<details>
<summary>
padding illustration:
</summary>
</details>

report: tweak tooltips

---

lighthouse-core/audits/webapp-install-banner.js
lighthouse-core/test/audits/webapp-install-banner-test.js
lighthouse-core/test/results/sample_v2.json

it's a response on #4898 to give a better error message when no Service Worker has loaded.
This makes it a bit more clear on what the issues are. Not sure if it's the correct approach though. wdyt @brendankenny 
before:
after:

core(webapp-install): simplify start_url warning when no SW is found

---

lighthouse-core/audits/byte-efficiency/unminified-css.js
lighthouse-core/audits/byte-efficiency/unminified-javascript.js
lighthouse-core/report/html/renderer/details-renderer.js

just bumped into a case where the report failed to render entirely because a value was `null` in the JSON (presumably because the value was `NaN` on the node side and was stringified into `null` by the time it was injected into the renderer)

report(table): handle null cells

---

lighthouse-core/audits/uses-rel-preconnect.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/test/audits/uses-rel-preconnect-test.js
typings/gatherer.d.ts
typings/web-inspector.d.ts

~~blocked on #5071~~
Relatively simple change, approximates the savings using just the TCP handshake time from lantern. The simulator itself doesn't have a notion of preconnect, so we won't estimate savings on a particular metric and bringing in the whole graph isn't necessary.

core(preconnect): use lantern to compute savings

---

lighthouse-extension/package.json
lighthouse-extension/yarn.lock

including all sub-depdendencies, so now `{debug:true}` sourcemap build of the bundle works again.

deps(extension): bump browserify version and sub-deps

---

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/byte-efficiency/efficient-animated-content.js
lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/byte-efficiency/unminified-css.js
lighthouse-core/audits/byte-efficiency/unminified-javascript.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/audits/byte-efficiency/unused-javascript.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
lighthouse-core/audits/byte-efficiency/uses-text-compression.js
lighthouse-core/audits/byte-efficiency/uses-webp-images.js
lighthouse-core/lib/dependency-graph/node.js
lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
lighthouse-core/test/audits/byte-efficiency/efficient-animated-content-test.js
lighthouse-core/test/audits/byte-efficiency/total-byte-weight-test.js
tsconfig.json
typings/audit.d.ts
typings/web-inspector.d.ts

`uses-optimized-images.js` and `uses-webp-images.js` only get the surface treatment for now as I noticed I was lazy typing the `OptimizedImages` in the error case. Fixing that will make their changes really easy.
The only annoying change here is having to explicitly cast `Node` to `NetworkNode` when wanting to access its network record. The cast is somewhat reasonable, but since they already have a readonly `type` property to differentiate, we could make them a discriminated union in the future. That way the compiler knows a node could only be a CPU or network node (+ whatever the future brings), and checking `node.type === 'network'` would establish to it that the following code was dealing with a `NetworkNode`.

core(tsc): add type checking to most byte efficiency audits

---

lighthouse-core/audits/redirects.js
lighthouse-core/test/audits/redirects-test.js
tsconfig.json
typings/artifacts.d.ts

should type-check pending #5072 🌮 
mostly whitespace changes, does the exact same thing as before but using the lantern graphs `startTime` instead of observed

core(redirects): use lantern to compute savings

---

lighthouse-core/config/default-config.js
lighthouse-core/test/results/sample_v2.json

closes #4629 
tweaks the performance score weights according to https://docs.google.com/document/d/1XiKdkLgWul0l40slhkCmQufNdjUiTlq3H_EAjrBH5Cw/edit#
I ran the weights and new thresholds for what we have in HTTPArchive and got the distribution, it's pretty aggressive.
Median: 27
75th Percentile: 43
90th Percentile: 69
95th Percentile: 83
99th Percentile: 98
Roughly 3% of sites get a 90+
Roughly 0.08% of sites get a 100
I'm disappointed new rolling window EIL won't get any credit, but that'll give us time to take a look at the distribution of the new definition and adjust score thresholds without impacting the overall perf score, and this is aggressive enough as it is :)

core(scoring): tweak performance weights

---

docs/scoring.md
lighthouse-core/audits/first-contentful-paint.js
lighthouse-core/audits/first-cpu-idle.js
lighthouse-core/audits/first-meaningful-paint.js
lighthouse-core/audits/interactive.js
lighthouse-core/audits/speed-index.js
lighthouse-core/test/audits/first-meaningful-paint-test.js
lighthouse-core/test/audits/interactive-test.js
lighthouse-core/test/results/sample_v2.json

As we just discussed, the new scoring thresholds based on 50/75 were making the requirements for 99/100 too unachievable. The root issue was that our PODR was not considered with our policy. The new policy instead...
Median === 75th percentile
PODR = 95th percentile
This makes a 100 roughly equal to the 98th percentile and keeps the green/orange boundary of 75 to the ~87th percentile which is pretty close to our old policy. Checkout the new scoring calculator sheet https://docs.google.com/spreadsheets/d/1Cxzhy5ecqJCucdf1M0iOzM8mIxNc7mmx107o5nj38Eo/edit#gid=0 to play around with the values.

core(scoring): loosen metric thresholds

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
lighthouse-core/audits/font-display.js
lighthouse-core/audits/redirects.js
lighthouse-core/lib/dependency-graph/node.js
lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
lighthouse-core/test/results/sample_v2.json
typings/artifacts.d.ts
typings/gatherer.d.ts

closes #5017 
byte efficiency audits will now take max savings on TTI/load
I had to address offscreen images at the same time otherwise they'd start way over-reporting
also contains some drive-by consistency text changes I noticed while testing, opportunity audits are actions for the user to take

core(opportunities): take max of savings on TTI, load

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html

* what the title said
* the report's ❌  and ✅ use standard fail/pass colors
* populateScore no longer sets title/description. Just handles the score gauge.
* removed right column score/icon for informative/manual audits (no more blue '100's)

report: error'd audits get 'Error!' treatment

---

lighthouse-core/config/config.js
lighthouse-core/config/default-config.js
lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/test/results/sample_v2.json
typings/lhr.d.ts

makes the change for manualDescription instead of a manual group
ref #5008 #4333

core(category): add manualDescription

---

lighthouse-core/audits/seo/canonical.js
lighthouse-core/audits/seo/font-size.js
lighthouse-core/audits/seo/hreflang.js
lighthouse-core/audits/seo/http-status-code.js
lighthouse-core/audits/seo/is-crawlable.js
lighthouse-core/audits/seo/link-text.js
lighthouse-core/audits/seo/meta-description.js
lighthouse-core/audits/seo/plugins.js
lighthouse-core/gather/gatherers/seo/font-size.js
lighthouse-core/test/audits/seo/canonical-test.js
lighthouse-core/test/audits/seo/hreflang-test.js
lighthouse-core/test/audits/seo/is-crawlable-test.js
tsconfig.json
typings/artifacts.d.ts
typings/audit.d.ts
typings/http-link-header/index.d.ts
typings/robots-parser/index.d.ts

with this, all of `lighthouse-core/**/*.js` is type checked :) (with carve outs for tests and the html renderer, for now).
The only remaining files this adds are these seo audits and the all-important `empty-stub.js` (which turns out was already type safe! Good job `empty-stub`).

core(tsc): add type checking for seo audits

---

lighthouse-core/test/config/config-test.js

avoids this terribly useless error message:

tests: node 10 compat

---

lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/mainthread-work-breakdown.js
lighthouse-core/audits/uses-rel-preload.js
typings/audit.d.ts

tsc wasn't inferring the correct type for displayValue in #5099 (widening it to just `Array<string | number>` which doesn't fit our requirement that the first element always be a string). It turns out this was because it was losing track of the more specific array type when passing back up the promise chain.
Flattening execution a bit with async/await and it can track the more specific type again :)
Diff is relatively tiny if you look at [?w=1](https://github.com/GoogleChrome/lighthouse/pull/5111/files?w=1)

core(tsc): fancier displayValue type

---

lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/mainthread-work-breakdown.js
lighthouse-core/audits/uses-rel-preload.js
lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
typings/audit.d.ts

e.g.
https://ambiguous-river.surge.sh/cnn.html
https://ambiguous-river.surge.sh/tinyhouse.html
https://ambiguous-river.surge.sh/dbwtester.html
https://ambiguous-river.surge.sh/example.html
https://ambiguous-river.surge.sh/paulirish.html
https://ambiguous-river.surge.sh/cnn.devtools.html
https://ambiguous-river.surge.sh/tinyhouse.devtools.html
https://ambiguous-river.surge.sh/dbwtester.devtools.html
https://ambiguous-river.surge.sh/example.devtools.html
https://ambiguous-river.surge.sh/paulirish.devtools.html
---------------
In a separate PR I will be adjusting the whitespace and alignment of everything.

report: new audit list display, indexes & new icons

---

lighthouse-core/audits/metrics.js
lighthouse-core/lib/traces/pwmetrics-events.js
lighthouse-core/test/audits/metrics-test.js
lighthouse-core/test/results/sample_v2.json

after much ado about nothing and the repeated creation/deletion of summary, we're just making a single item inside details that has all the metrics keyed by name and `Ts`. @paulirish approved of this approach
it means that querying will look like `audits.metrics.details.items[0].firstContentfulPaint`
we'll just commit to not breaking that contract with uber typechecking 🎉 
ref #5008

core(metrics): consumable metrics audit output

---

.travis.yml
lighthouse-core/gather/computed/metrics/lantern-first-contentful-paint.js
lighthouse-core/gather/computed/metrics/lantern-first-meaningful-paint.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/lib/dependency-graph/node.js
lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/test/gather/computed/page-dependency-graph-test.js
lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js

should fix the travis flake we've been seeing on extension tests `cannot find node ID 02u309rjfja0fsdjflajsfd`

core(lantern): never exclude main document from graphs

---

lighthouse-core/closure/closure-type-checking.js
lighthouse-core/closure/typedefs/devtools-externs.js
lighthouse-core/lib/emulation.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/runner.js
lighthouse-core/scripts/cleanup-LHR-for-diff.js
lighthouse-core/test/report/html/renderer/report-renderer-test.js
lighthouse-core/test/report/html/renderer/util-test.js
lighthouse-core/test/results/sample_v2.json
typings/lhr.d.ts

- removes `runtimeConfig` from LHR
- adds `runtimeSettings` to LHR (I'd prefer just `.settings` but doing the rename of that back to something else would have been more challenging, so lmk if other folks feel the same I'd I'll happily change :D)
- moves the emulation description logic to the report renderer
I know that this whole thing is ripe for some refactoring, but we've got a long list to get through and this keeps same functional parity, sooooo
NOTE: closure fixes pending

core(lhr): move runtime config to report, configSettings

---

lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/mainthread-work-breakdown.js
lighthouse-core/test/audits/bootup-time-test.js
lighthouse-core/test/audits/mainthread-work-breakdown-test.js
lighthouse-core/test/results/sample_v2.json

adjusts the main thread work and bootup time audits to work under lantern, just multiplies the amount of thread work in each category by the cpuSlowdownMultiplier
also does some drive-by fixes to bring it in line with the other audits (using type: ms for details, slightly less noisy items output, etc)

core(mainthreadwork): multiply by cpuSlowdownMultiplier

---

lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
lighthouse-core/audits/byte-efficiency/uses-webp-images.js
lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js
typings/artifacts.d.ts

make `OptimizedImages` a discriminated union on `failed` or not. Keeps the artifact type simpler and the use of it really simple in these two audits.
The only remaining `// @ts-nocheck` audit is `mixed-content.js`, which should make refactors a little more easier.

core(tsc): fix OptimizedImages type; type check dep audits

---

lighthouse-core/audits/first-meaningful-paint.js
lighthouse-core/config/default-config.js
lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/report/html/renderer/details-renderer-test.js
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
lighthouse-core/test/results/sample_v2.json
typings/lhr.d.ts

https://disastrous-bears.surge.sh/cnn.html
https://disastrous-bears.surge.sh/dbwtester.html
https://disastrous-bears.surge.sh/errors.html
https://disastrous-bears.surge.sh/example.html
https://disastrous-bears.surge.sh/paulirish.html
https://disastrous-bears.surge.sh/tinyhouse.html
https://disastrous-bears.surge.sh/z.devtools.cnn.html
https://disastrous-bears.surge.sh/z.devtools.dbwtester.html
https://disastrous-bears.surge.sh/z.devtools.errors.html
https://disastrous-bears.surge.sh/z.devtools.example.html
https://disastrous-bears.surge.sh/z.devtools.paulirish.html
https://disastrous-bears.surge.sh/z.devtools.tinyhouse.html

report: final metrics display, icons, whitespace polish

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/crc-details-renderer.js
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
lighthouse-core/test/report/html/renderer/details-renderer-test.js

* remove the collapsible details/summary control entirely.
* new colors.
* make sure we're always max 100% width.
https://venomous-horse.surge.sh/cnn.html
https://venomous-horse.surge.sh/dbwtester.html
https://venomous-horse.surge.sh/errors.html
https://venomous-horse.surge.sh/example.html
https://venomous-horse.surge.sh/paulirish.html
https://venomous-horse.surge.sh/tinyhouse.html
https://venomous-horse.surge.sh/z.devtools.cnn.html
https://venomous-horse.surge.sh/z.devtools.dbwtester.html
https://venomous-horse.surge.sh/z.devtools.errors.html
https://venomous-horse.surge.sh/z.devtools.example.html
https://venomous-horse.surge.sh/z.devtools.paulirish.html
https://venomous-horse.surge.sh/z.devtools.tinyhouse.html

report: new styling for audit details

---

lighthouse-core/gather/computed/metrics/lantern-first-contentful-paint.js
lighthouse-core/gather/computed/metrics/lantern-first-meaningful-paint.js
lighthouse-core/gather/computed/metrics/lantern-interactive.js
lighthouse-core/gather/computed/metrics/lantern-metric.js
lighthouse-core/gather/computed/metrics/lantern-speed-index.js
lighthouse-core/test/audits/first-meaningful-paint-test.js
lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js
lighthouse-core/test/audits/metrics-test.js
lighthouse-core/test/audits/predictive-perf-test.js
lighthouse-core/test/gather/computed/metrics/first-contentful-paint-test.js
lighthouse-core/test/gather/computed/metrics/first-cpu-idle-test.js
lighthouse-core/test/gather/computed/metrics/first-meaningful-paint-test.js
lighthouse-core/test/gather/computed/metrics/interactive-test.js
lighthouse-core/test/gather/computed/metrics/lantern-first-contentful-paint-test.js
lighthouse-core/test/gather/computed/metrics/lantern-first-cpu-idle-test.js
lighthouse-core/test/gather/computed/metrics/lantern-first-meaningful-paint-test.js
lighthouse-core/test/gather/computed/metrics/lantern-interactive-test.js
lighthouse-core/test/gather/computed/metrics/lantern-speed-index-test.js
lighthouse-core/test/gather/computed/metrics/speed-index-test.js
lighthouse-core/test/results/sample_v2.json

This PR updates the lantern coefficients to the values that offer the lowest absolute error of the 9-run accuracy/variance dataset, they haven't ever been updated so the jump is expected. this PR also turns on the `flexibleOrdering` feature for the optimistic estimate which improved accuracy ~5% on FCP/FMP 🎉 
In the ideal case if lantern were perfect, we would expect the optimistic/pessimistic coefficients to both be positive, sum to ~1, and the intercept to be 0. The good news is we've made considerable progress toward this goal for FCP/FMP, intercepts are significantly lower and coefficients are positive and sum to ~1.
Progress is positive on TTI, the coefficients now sum to ~1 instead of ~1.5 and the intercept is roughly the same.
Speed Index is just weird, the optimistic estimate …

core(metrics): update lantern coefficients

---

lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-cli/test/smokehouse/pwa-expectations.js
lighthouse-cli/test/smokehouse/pwa2-expectations.js
lighthouse-cli/test/smokehouse/pwa3-expectations.js
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/audits/audit.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/test/results/sample_v2.json
typings/audit.d.ts

removes extendedInfo from external LHR and updates all smoke expectations/golden LHR.
cleanup for unit tests and audits can follow

core(lhr): remove extendedInfo

---

lighthouse-core/closure/closure-type-checking.js
lighthouse-core/closure/typedefs/element-externs.js
lighthouse-core/report/html/renderer/dom.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/report-renderer-test.js

report(header): new header WIP

---

.gitignore
lighthouse-cli/bin.js
lighthouse-cli/cli-flags.js
lighthouse-cli/printer.js
lighthouse-cli/run.js
lighthouse-cli/test/cli/printer-test.js
lighthouse-core/config/config.js
lighthouse-core/report/report-generator.js
lighthouse-core/test/config/config-test.js
lighthouse-core/test/report/report-generator-test.js
lighthouse-core/test/results/sample_v2.json
lighthouse-core/test/runner-test.js
typings/externs.d.ts

returns support for multiple outputs
I know there's some ugliness in config to get this to work with unified config/CLI settings, but that'll need some good cleanup for type checking soon anyhow
biggest question for 3.0: **do we want to have report/output types be `string|string[]` or `string[]`** 
I did the `|` because it's easier impl wise and won't break common `output: 'html'` case, but it's new functionality anyhow so now's our chance

core(runner): support multiple output modes

---

lighthouse-core/config/config.js
lighthouse-core/config/default-config.js
lighthouse-core/config/full-config.js
lighthouse-core/config/mixed-content-config.js
lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/report-generator.js
lighthouse-core/scoring.js
lighthouse-core/test/config/config-test.js
lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
lighthouse-core/test/report/html/renderer/report-renderer-test.js
lighthouse-core/test/results/sample_v2.json
lighthouse-core/test/runner-test.js
lighthouse-core/test/scoring-test.js
lighthouse-extension/app/src/lighthouse-background.js
lighthouse-extension/app/src/popup.js
lighthouse-extension/test/extension-test.js
lighthouse-viewer/test/viewer-test-pptr.js
typings/config.d.ts
typings/lhr.d.ts

core(lhr): s/audits/auditRefs, s/category.name/category.title/

---

.npmignore
lighthouse-core/config/default-config.js
lighthouse-core/test/results/sample_v2.json
package.json

npmignore was busted since the chrome launcher script got moved, guess that issue we saw was real afterall @paulirish ;)
also reverts an accidental change that snuck in from a bad rebase to the config constants
already published since lighthouse was borked anyhow, but this puts master back in a good state

 3.0.0-alpha.1

---

lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/test/results/sample_v2.json

Hi,
I think we should link to the respective document for excessive DOM size explanation.
Cheers
midzer

report(dom-size): use correct learn more link

---

lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/audits/screenshot-thumbnails.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/templates.html
lighthouse-core/test/audits/screenshot-thumbnails-test.js
lighthouse-core/test/results/sample_v2.json

drive-by I/O polish I noticed while doing demos
* Unused CSS Rules inconsistent name
* minimum filmstrip scale 3s
* minimum opportunity scale of 2s
EDIT: removed the share dropdown fix since ward already put up a PR :D #5185

report: minimum time scale, text tweaks

---

lighthouse-core/report/html/renderer/logger.js
lighthouse-viewer/test/viewer-test-pptr.js
package.json
yarn.lock

`computedStyleMap` in the report fails in the Chromium version that our current version of puppeteer ships with. This revs the version so that we get a more recent Chromium.
Drive by change to viewer and the viewer pptr test so that when there's an in-page error like this, the test can pick it up and print it to console instead of just timing out in `before()` waiting for the report to load.

tests(viewer): upgrade pptr to handle new CSSOM use in the report

---

lighthouse-core/audits/uses-rel-preload.js
lighthouse-core/lib/dependency-graph/network-node.js
lighthouse-core/lib/dependency-graph/node.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/test/audits/uses-rel-preload-test.js
lighthouse-core/test/lib/dependency-graph/node-test.js
lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js

fixes an infinite loop on https://emojityper.com/
attacked from multiple prongs:
* simulator won't try to simulate graphs with cycles
* graphs with *dependency* cycles not just *dependent* cycles are caught
* fix the creation of a cyclic graph in preload audit

core(uses-preload): prevent infinite loop

---

lighthouse-core/audits/audit.js
lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/report-generator.js
lighthouse-core/runner.js
lighthouse-core/test/audits/audit-test.js
lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/results/sample_v2.json
lighthouse-core/test/runner-test.js
typings/audit.d.ts

phase 1 of audit property renames, this PR changes the LHR property names but not the source ones in the audits (we can do that piecemeal if need be since that'll be huge)

core(lhr): audit id, title, description

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-viewer/app/src/lighthouse-report-viewer.js
lighthouse-viewer/app/src/viewer-ui-features.js

1. The 2.x viewer is published to https://googlechrome.github.io/lighthouse/viewer2x/
2. The 3.x viewer will live at https://googlechrome.github.io/lighthouse/viewer/ (but doesn't yet)
3. User opens report in 3.x viewer app (via however: drag, paste, click menu item)
4. The 3.x viewer app notices report isn't v3 and opens another tab with `viewer2x/` and has it render the report.
4. The 3.x viewer attempts to close it's own tab (but this doesn't always work (because user gestures?))
1. The 3.x viewer tells the user what's happening with some toaster notifications.
This also relies on a few commits added to 2.x branch: https://github.com/GoogleChrome/lighthouse/compare/branch2.x...viewer2x-deploy
fixes #5170

misc(viewer): support 3.x and legacy (2.x) reports in viewer

---

readme.md

Hi, we made this library to run Lighthouse on AWS Lambda easily. Headless Chrome (stable desktop releases) is built by https://github.com/joytocode/headless-chrome-builder and tested to ensure working with Lighthouse on Lambda. It would be nice if you could add it to related projects.

docs(readme): add lighthouse-lambda to related projects

---

lighthouse-core/scripts/compile-against-devtools.sh

fwiw here's the current output:
<details>
```
Compiling frontend...
Compiling devtools_compatibility.js...
Verifying JSDoc comments...
/Users/paulirish/code/lighthouse/node_modules/lh-compile-devtools/two-more/almost-there/temp-devtoolsfrontend/front_end/audits2/lighthouse/renderer/util.js:35: ERROR - Type "Array" nullability not marked explicitly with "?" (nullable) or "!" (non-nullable)
* @param {string|Array<string|number>=} displayValue
^
/Users/paulirish/code/lighthouse/node_modules/lh-compile-devtools/two-more/almost-there/temp-devtoolsfrontend/front_end/audits2/lighthouse/renderer/util.js:313: ERROR - Type "LH.Config.Settings" nullability not marked explicitly with "?" (nullable) or "!" (non-nullable)
* @param {LH.Config.Settings} settings
^ …
```

tests(compile): fix broken compile-devtools script

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-viewer/app/src/lighthouse-report-viewer.js
lighthouse-viewer/app/src/viewer-ui-features.js

#5204 used postMessage to open the 2x viewer, but this faces problems with popup blockers.
This PR reverts most of that one, and uses IDB and `location.href = ...` to store and open the 2x report.
The complementary 2.x branch PR to this one is: #5232

misc(viewer): switch to 2x viewer within the same tab

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/scripts/roll-to-devtools.sh
lighthouse-viewer/app/src/github-api.js

1. some `.url` that weren't yet `.finalUrl`
1. a regression from brendan's tsc that nuked a `!`
1. driveby fix for a path in `roll-to-devtools.sh`
fixes #5250

misc(viewer): fix saving as gist

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html

Thx to @hwikyounglee for putting up with me as I was like "OH HECK NO".
Because I enjoyed making this work. :D 
This is dependent on #5136
-----
https://lighthouse-chevrons.now.sh/

report: animated chevrons

---

lighthouse-core/report/html/report-styles.css

This icon was missing because of all the rebasing:

report: restore missing non-applicable icon

---

lighthouse-core/gather/computed/metrics/lantern-metric.js
lighthouse-core/gather/computed/metrics/lantern-speed-index.js
lighthouse-core/lib/dependency-graph/network-node.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/test/audits/first-meaningful-paint-test.js
lighthouse-core/test/audits/metrics-test.js
lighthouse-core/test/audits/predictive-perf-test.js
lighthouse-core/test/gather/computed/metrics/first-contentful-paint-test.js
lighthouse-core/test/gather/computed/metrics/first-meaningful-paint-test.js
lighthouse-core/test/gather/computed/metrics/lantern-first-contentful-paint-test.js
lighthouse-core/test/gather/computed/metrics/lantern-first-meaningful-paint-test.js
lighthouse-core/test/gather/computed/metrics/lantern-speed-index-test.js
lighthouse-core/test/gather/computed/metrics/speed-index-test.js
lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js
typings/web-inspector.d.ts

adds support to lantern for handling network files that were loaded from disk cache instead of network (necessary for working with `--disable-storage-reset` and in DevTools)
this also makes an adjustment to all lantern metrics predicted to be <1s that scales the intercept linearly until 1s. It only affects sites that were predicted to be very fast.
for example a site predicted to have FCP at 500ms
Before: 600 + 500 = 1100
After: 500/1000 * 600 + 500 = 800
for example a site predicted to have FCP at 10ms (for example cached example.com)
Before: 600 + 10 = 610
After: 10/1000 * 600 + 10 = 16
lastly, it adjusts speed index pessimistic estimate to use the pessimistic FCP as the floor rather than the coefficient predicted one. It was similarly unfair to very fast sites to double apply the …

core(lantern): handle disk cache simulation

---

lighthouse-core/gather/computed/metrics/interactive.js
lighthouse-core/lib/network-recorder.js
lighthouse-core/test/gather/network-recorder-test.js

core(network-recorder): handle QUIC requests

---

readme.md

Been working on an open source project using Docker, Grafana, and Prometheus.
Garie uses Lighthouse_CI to gather data and allows users to view report information over a time series.

docs(readme): add Garie to related projects

---

lighthouse-core/scripts/lantern/minify-devtoolslog.js
lighthouse-core/scripts/lantern/minify-trace.js
package.json

does a pretty awesome job of minifying traces from light/medium sites for inclusion, OK job of minifying the devtoolslog
example.com: 526KB -> 28KB, 7KB -> 4KB
paulirish.com: 2.3MB -> 151KB, 147KB -> 47KB
does okish on heavy sites like CNN
cnn.com: 30MB ->3.8MB, 2.9MB -> 1.3MB

misc(scripts): add trace/devtoolslog minification scripts

---

lighthouse-core/gather/connections/extension.js
lighthouse-core/runner.js

Speculative fix for "getCurrentTabURL returned empty string".
Uses Patrick's idea to pick the first tab with a URL. Unclear if there will actually be a tab with a url (maybe there are no other tabs provided since we ask only for the active tabs in the current window) but it won't hurt the current correct cases where the first tab has a URL.
In addition, added more detailed error messages that may give us some hints for what's going on
- log what URL is provided to `runner` that fails the first URL exists check (#1834)
- log the number of tabs found and their IDs if no tab with a URL is found (the ID *might* help if it's [`chrome.tabs.TAB_ID_NONE`](https://developer.chrome.com/extensions/tabs#type-Tab), which is set for "for apps and devtools windows)). I don't see anything else in that …

extension: another speculative fix for getCurrentTabURL; more logging

---

lighthouse-core/lib/url-shim.js
lighthouse-extension/gulpfile.js
lighthouse-extension/test/extension-test.js

extension: expose URL shim

---

.github/ISSUE_TEMPLATE/Bug_report.md

Just created a bug report from the template and it doesn't make sense to use checkboxes for the environment since then it shows up in the issues UI as "progress" toward completion.

misc: remove checkboxes from bug report template

---

lighthouse-viewer/app/src/github-api.js

Right now if you have a gist it'll only consider files `*.lighthouse.report.json`
This is usually OK because when you 'save to gist' it uses this filename. but we can afford to be flexible here

misc(viewer): load *.json if no *.lighthouse.report.json

---

lighthouse-extension/app/src/lighthouse-ext-background.js
lighthouse-extension/app/src/popup.js

fixes #5340 
thanks https://stackoverflow.com/questions/4924615/chrome-extension-force-popup-html-to-close <3
Tested error -> reporting flow and it lg, too.

extension: close the popup once the report has opened

---

lighthouse-core/config/default-config.js
lighthouse-core/test/results/sample_v2.json

adjust the PWA score weights to give more credit to speed/offline, less to adding a manifest/1-line meta
You can play around with how this affects score at [the calculator](https://docs.google.com/spreadsheets/d/1Cxzhy5ecqJCucdf1M0iOzM8mIxNc7mmx107o5nj38Eo/edit#gid=283330180)
Basically... 
Adding manifest alone used to be worth 18, now worth 8
Adding noop service worker used to be worth 9, now worth 4
Adding service worker to make site work offline used to be worth 18, now worth 23
Performance used to be worth 9, now worth 27

core(pwa): adjust score weights

---

lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
lighthouse-core/audits/redirects.js
lighthouse-core/audits/uses-rel-preload.js
lighthouse-core/gather/computed/metrics/lantern-estimated-input-latency.js
lighthouse-core/gather/computed/metrics/lantern-first-cpu-idle.js
lighthouse-core/gather/computed/metrics/lantern-interactive.js
lighthouse-core/gather/computed/metrics/lantern-speed-index.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
typings/gatherer.d.ts

cleans up a lot of the TODOs left based on the internal/external timing discrepancy

core(simulator): improved timing typedef

---

typings/externs.d.ts

**Summary**
Import crdp directly from package.
Fix for using LH types.
If LH installed as dependency, then `vscode-chrome-debug-core` isn't and can't be found via `../node_modules/vscode-chrome-debug-core/lib/crdp/crdp` path. Then I as user adding it manually  to my package.json will be able to use `externs.d.ts` types.

misc(externs): import crdp from root node_modules

---

lighthouse-core/audits/image-aspect-ratio.js
lighthouse-core/test/audits/image-aspect-ratio-test.js

core(image-aspect-ratio): loosen ratio check

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/lib/statistics.js
lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
lighthouse-core/test/audits/redirects-test.js
lighthouse-core/test/lib/statistics-test.js
lighthouse-core/test/results/sample_v2.json

**Summary**
Introduces more granular opportunity scores based on the same old control points as before (but now with linear interpolation). Would help with doing summaries of the performance category and many people are confused by the limited score choices. 
Users not consuming the JSON should be entirely unaffected by this change.
cc @rviscomi

core(opportunities): more granular score

---

lighthouse-extension/app/manifest.json

**Summary**
This should hopefully get some of those seeing emulation protocol errors to update Chrome and get the debugger protocol methods we need.
Stable is m67 now, but that seemed a bit harsh (only happened three days ago), and 66 should be sufficient for our uses.
#5398, #5397, #5395, #5334, #5307, #5305...

extension: update minimum Chrome version to 66

---

lighthouse-core/gather/computed/trace-of-tab.js
lighthouse-core/test/fixtures/traces/threeframes-blank_content_more.json
lighthouse-core/test/gather/computed/trace-of-tab-test.js
typings/externs.d.ts

Since version 67 Chrome uses a new schema to describe page frame tree.
The tree is encoded within TracingStartedInBrowser trace event.
The patch makes lighthouse to support the new event.
Legacy TracingStartedInPage event is going to the removed soon.

core: support traces with TracingStartedInBrowser event

---

lighthouse-core/gather/computed/trace-of-tab.js
lighthouse-core/lib/traces/tracing-processor.js
lighthouse-core/scripts/lantern/minify-trace.js

addresses TODO and cleans up trace-of-tab a bit

misc(scripts): support TracingStartedInBrowser in scripts

---

lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners.js
lighthouse-core/lib/element.js

**Summary**
Catch ```DOM.resolveNode``` errors.
Issue: #2736

core: Handle DOM.resolveNode errors

---

lighthouse-core/audits/uses-rel-preload.js
lighthouse-core/lib/url-shim.js
lighthouse-core/test/audits/uses-rel-preload-test.js
lighthouse-core/test/lib/url-shim-test.js

Fixes nr 1 of #4425 
Restrict results to same-origin (as a rough filter for predictable and unchanging URLs). Same origin as in subdomains and rootdomains.

core(preload): only allow same origin (domain + subdomains)

---

lighthouse-core/lib/asset-saver.js

asset-saver-test.js goes from 12.5s to 7.9s.
cc #2593 #1685

core: faster saveTrace by streaming 500 events at a time

---

lighthouse-cli/cli-flags.js
readme.md

docs: update required chrome version

---

lighthouse-cli/test/smokehouse/pwa-expectations.js
lighthouse-cli/test/smokehouse/pwa2-expectations.js
lighthouse-cli/test/smokehouse/pwa3-expectations.js
lighthouse-core/audits/multi-check-audit.js
lighthouse-core/gather/computed/manifest-values.js
lighthouse-core/test/audits/splash-screen-test.js
lighthouse-core/test/audits/webapp-install-banner-test.js
lighthouse-core/test/results/sample_v2.json
typings/artifacts.d.ts
typings/audit.d.ts

addresses a lot of my TODO's and exposes the PWA items in details with some type checking :)
there's some duplication in the new details output (see golden LHR) if it does make things more consumable. All our tests seem to care about number of failures. We could rewrite them to count newlines in the `.explanation` string and remove parseFailureReason to entirely if folks don't mind :)

core(multi-check): expose manifest checks in details

---

lighthouse-core/gather/gather-runner.js

I was reading through how this file worked, and decided to convert it to async/await as I did. Clears up some dastardly uses of `array.reduce`.

core: convert gather-runner.js to async/await

---

lighthouse-core/audits/accessibility/axe-audit.js
lighthouse-core/test/results/sample_v2.json
typings/artifacts.d.ts

core(a11y): add back html/tags/impact

---

lighthouse-core/audits/user-timings.js
lighthouse-core/test/audits/user-timing-test.js
lighthouse-core/test/results/sample_v2.json
lighthouse-core/test/runner-test.js

core(user-timings): add back startTime

---

lighthouse-core/gather/computed/metrics/lantern-metric.js
lighthouse-core/lib/asset-saver.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/lib/lantern-trace-saver.js
typings/externs.d.ts

note: test failures blocked on #5377
running the CLI with `--save-assets` will now output the optimistic FCP and pessimistic TTI traces that lantern computed, waaaaaaay easier for debugging and whatnot
next steps I'll add labels for the various opportunities so those are easier to debug as well
the code's a bit big for asset-saver so it might make sense to pull it out, but I'm drawing a blank where it should live, straight in lib? next to simulator? what do we call it?

core(simulator): convert node timings to trace

---

lighthouse-core/config/config.js
lighthouse-core/config/constants.js
lighthouse-core/index.js
lighthouse-core/runner.js
lighthouse-core/test/config/config-test.js
lighthouse-extension/app/src/lighthouse-background.js
typings/config.d.ts

Part 1 of 2 to add type checking to `config.js`
This is an attempt to reduce noise around the more major changes by pulling out the trivial type annotations/changes needed without changing any functionality. Some of these types are slightly white lies, but will be correct with part 2.
Main trickiness here is some of the generic functions, like `merge()` and `deepClone()`, but they maintain their earlier behavior (except `deepCloneConfigJson()` is split out), it's mostly just convincing the compiler that they do what they say they do.

core(tsc): add initial trivial type info to config.js

---

lighthouse-extension/yarn.lock
lighthouse-viewer/package.json
lighthouse-viewer/yarn.lock

You can't gulp the extension or viewer using Node 10.4 without a bump to its dependency `natives` (see https://github.com/gulpjs/gulp/issues/2162). This does that.
Drive-by removal of viewer's `tsify`, which hasn't been used in a long time (`yarn` now complains about missing its peer dep  when you `yarn install-all`).

deps: bump gulp's natives dep for node 10.4

---

lighthouse-cli/cli-flags.js
lighthouse-core/runner.js
lighthouse-core/scripts/assert-golden-lhr-unchanged.sh
lighthouse-core/test/results/sample_v2.json
lighthouse-core/test/runner-test.js
package.json

realized in #5493 that requiring a URL in audit mode is silly, this removes that requirement

core(audit-mode): do not require a URL

---

lighthouse-core/gather/gather-runner.js
lighthouse-core/gather/gatherers/gatherer.js
lighthouse-core/test/gather/gather-runner-test.js
typings/artifacts.d.ts
typings/externs.d.ts
typings/gatherer.d.ts

A small refactor of GatherRunner to split the types of the artifacts always provided by LH (`URL`, `fetchTime`, `LighthouseRunWarnings`, etc) from the artifacts provided by gatherers.
This gets rid of the awkward nested arrays around the base artifacts and allows tightening of the types a bit so that gatherers now only return `undefined` or the values of `LH.GathererArtifacts`.
Side effect: with the recent simplification of `passContext`, it seemed to make more sense to add `LighthouseRunWarnings` to the context rather than also pass in `baseArtifacts` to `beforePass`/`pass`/`afterPass`. This has the added benefit of solving how gatherers can raise top-level warnings...they can now just push to `passContext.LighthouseRunWarnings` :)

core: split out BaseArtifacts, those always provided by LH itself

---

readme.md

**Summary**
Add lighthouse-ci to the list of Lighthouse's related projects.

docs(readme): lighthouse-ci

---

lighthouse-core/config/config.js
lighthouse-core/test/config/config-test.js

even with #5481 out of the way, this is still kind of a doozy to review, *but*
- With most of the rest of lighthouse type checked, this involved significantly fewer changes than a few months ago
- With @patrickhulce's work to unify CLI flags and the config and adding defaults for everything, a lot of simplification was already done and more was possible
Main starting change is eliminating `generateNewFilteredConfig()` as kind of an externally-facing API. We have a way of expressing that in the config itself now (`onlyCategories`, etc), so it makes sense to not expose a function for it anymore (and the extension, etc moved on to using `onlyCategories`, etc a while ago).
With that gone, the constructor is really the only entry point, and control flow becomes just a simple tree (ignoring …

core(tsc): refactor and add type checking to config.js

---

lighthouse-core/scripts/lantern/assert-master-lantern-values-unchanged.js
lighthouse-core/scripts/lantern/debug-url.js
lighthouse-core/scripts/lantern/run-once.js
package.json
yarn.lock

so lantern tests have been great canary but not all that helpful for debugging :) the git diff didn't always include the URL you needed to look at, it included a lot of lines that weren't relevant, and didn't give clear priority to the most affected URLs
this makes a few tweaks and adds a debug script
new output of the `assert-*` script:

misc(scripts): more useful lantern debugging output

---

lighthouse-core/audits/first-contentful-paint.js

so slightly embarrassing here, but somehow in the shuffle of metric scoring curves I updated FCP to the wrong value. the calculator spreadsheet, desmos curve, HTTPArchive, and logic from the PODR of FMP all dictate that the FCP one should be 2000, but it's 2900 (like TTI). Oops 😞 
good thing it's still the beta release 😆

core(fcp): fix scoring curve

---

lighthouse-core/config/config.js
lighthouse-core/runner.js
tsconfig.json
typings/config.d.ts

Previously there was the `Config` class (in `config.js`) and the `LH.Config` type (in `config.d.ts`). The `LH.Config` type implemented `LH.Config.Json`, ensuring that any `LH.Config` was also a valid `LH.Config.Json`.
When passing around an instance of `Config` we called it an `LH.Config`, which meant the compiler was enforcing that it implemented both interfaces, but that means two sources of truth for what a "Config" is and indirect errors if those interfaces were violated.
Based on @patrickhulce's idea in #5451 to enforce interfaces until tsc [supports `@implements` tags](https://github.com/Microsoft/TypeScript/issues/17498), we can eliminate the `d.ts` declaration of `LH.Config` and just use the `Config` class directly, just asserting that the object is a valid `LH.Config.Json` near …

core(tsc): use Config class to define Config type

---

lighthouse-core/scripts/cleanup-LHR-for-diff.js

previously we excluded helpText from the differ, but the property name was changed for v3 to `description` that's also how kayce was bitten by the tests this time around accidentally :)

misc(golden-lhr): exclude audit descriptions

---

lighthouse-core/audits/mainthread-work-breakdown.js
lighthouse-core/gather/computed/trace-of-tab.js

**Summary**
Further reducing our dependency on DevTools frontend.
Few notes: there were already tests for stable sorting, I manually did some additional dSE on thornier traces and compared execution time, this one is ~1-5% faster on my hardware than DevTools version, so no real difference perf-wise.
(left the one for mainthread breakdown since, #5533 takes care of it)

core(trace-of-tab): remove DevTools stableSort dependency

---

docs/headless-chrome.md

Following documentation will result in an error when running any `npm` command as it appears like it's not installed along with node
**Summary**
Fixes an issue when following documentation for headless chrome.
Makes docs easier to follow
None that I know of.

docs(headless-chrome): need to install npm

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js

**Summary**
The driver method `evaluateScriptOnNewDocument` was spelled `evalute`. This PR corrects that change across the repo.

core(driver): fix spelling error in driver method

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js

@paulirish bisected the regression to a V8 roll that removed console.timeline, we call this method in our smoke tests so the test script was erroring and not actually executing our intentional failures :)

tests(smoke): remove console.timeline() call

---

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
lighthouse-core/gather/computed/metrics/lantern-estimated-input-latency.js
lighthouse-core/gather/computed/metrics/lantern-first-contentful-paint.js
lighthouse-core/gather/computed/metrics/lantern-first-cpu-idle.js
lighthouse-core/gather/computed/metrics/lantern-first-meaningful-paint.js
lighthouse-core/gather/computed/metrics/lantern-interactive.js
lighthouse-core/gather/computed/metrics/lantern-metric.js
lighthouse-core/gather/computed/metrics/lantern-speed-index.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/lib/dependency-graph/base-node.js
lighthouse-core/lib/dependency-graph/cpu-node.js
lighthouse-core/lib/dependency-graph/network-node.js
lighthouse-core/lib/dependency-graph/node.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/test/gather/computed/page-dependency-graph-test.js
lighthouse-core/test/lib/dependency-graph/base-node-test.js
typings/gatherer.d.ts

@patrickhulce this is what I mentioned a while back (in #5072). The Node type passed around becomes a union of `CPUNode | NetworkNode`, which means things inside e.g. an `if (node.type !== 'network')` block that `node` becomes a `CPUNode` with no cast or anything.
The downsides are
a) naming (but we can tweak) and
b) double casts of `this` within the `Node` class since the compiler doesn't *know* that `this` isn't an incompatible subclass of `Node` (so first cast to `Node`, then cast to `CPUNode | NetworkNode`.

core(tsc): make CPUNode and NetworkNode a discriminated union

---

typings/audit.d.ts

because I keep getting confused about which is which after the change :)
Mostly lifted from https://github.com/GoogleChrome/lighthouse/blob/master/docs/understanding-results.md#audits and `lhr-lite.d.ts`

docs(audit): add jsdoc descriptions to the audit meta properties

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/lib/network-request.js
lighthouse-core/test/gather/driver-test.js
lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js

#5451 changed our network request ID such that many more IDs had the `:redirect` scheme than before, the DT backend has no notion of these fake `<requestId>:redirect` IDs and we always should have been cleansing them to be regular requestIds.

core: convert requestIds before sending to backend

---

lighthouse-cli/test/fixtures/perf/cors-fonts.css
lighthouse-cli/test/fixtures/perf/fonts.html
lighthouse-cli/test/fixtures/static-server.js
lighthouse-cli/test/smokehouse/perf/expectations.js
lighthouse-core/gather/gatherers/fonts.js
lighthouse-core/lib/sentry.js

After our 3.0 release a new high volume error popped up in sentry for the fonts gatherer. Turns out Chrome changed the behavior for CORS `.cssRules` property to throw instead of be `null`.
This adds a smoketest for the CORS font case and fixes that behavior.

core(fonts): handle CORS cssRules

---

changelog.md
docs/releasing.md
lighthouse-core/test/results/sample_v2.json
lighthouse-extension/app/manifest.json
package.json

~This is going to the 3.0.x branch`, only to exclude the jest commit, right now.~
jk. master branch. I dbl-checked the jest commit and feel fine about it rolling into the patch rls.

core: bump to v3.0.1

---

lighthouse-core/scripts/lantern/print-correlations.js

basically a total re-write of the `print-correlations` script, example new output looks like the below and compares the current state to the baseline master state as well! 🎉

misc(scripts): better print-correlations output

---

lighthouse-core/audits/without-javascript.js
lighthouse-core/gather/gatherers/html-without-javascript.js
lighthouse-core/test/audits/without-javascript-test.js
lighthouse-core/test/gather/gatherers/html-without-javascript-test.js
lighthouse-core/test/results/artifacts/artifacts.json
typings/artifacts.d.ts

core(without-javascript): allow noscript pages

---

lighthouse-extension/app/src/popup.js

**Summary**
bugfix
When you run the extension and hit enter immediately afterwards, lighthouse tries to start again which will start on about:blank and fails as it can't get an url from the tab.
https://github.com/GoogleChrome/lighthouse/issues?q=is%3Aissue+Error%3A+Couldn%27t+resolve+current+tab+is%3Aclosed

extension(taburl): extension Error: couldn't resolve current tab

---

lighthouse-core/gather/gatherers/fonts.js

fonts timing out is one of our most popular errors on sentry right now, this bumps the timeout to 5s to give WPT a bit more time to load it (since they're still throttling even in afterPass)

core(fonts): [minor] bump timeout to 5s

---

changelog.md
lighthouse-core/test/results/sample_v2.json
lighthouse-extension/app/manifest.json
package.json

Publishing 3.0.2 to get down our sentry timeouts hopefully, not publishing the extension since it's not a big deal for it.
@paulirish gave his blessing to ship the new audit even though it's just a patch release :)

core: bump to 3.0.2

---

lighthouse-core/lib/emulation.js

core(emulation): use setTouchEmulationEnabled

---

lighthouse-core/audits/bootup-time.js
lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js

**Summary**
Just fixing some changes we missed for resourceType

misc(typings): convert hardcoded strings to networkRequests.TYPES

---

lighthouse-core/audits/byte-efficiency/uses-text-compression.js
lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
lighthouse-core/test/gather/gatherers/dobetterweb/response-compression-test.js
typings/artifacts.d.ts

While testing out 3.0 I noticed quite a few response-compression errors, this will handle partial failure and beacon to sentry without failing the whole audit.

core(response-compression): graceful recovery

---

lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/network-requests.js

core: warn when extensions affected perf

---

lighthouse-core/audits/bootup-time.js
lighthouse-core/runner.js
lighthouse-core/test/runner-test.js
typings/audit.d.ts
typings/gatherer.d.ts

I was thinking about #5666 this morning and realized we shouldn't be altering artifacts in audits. Instead, this exposes a way to push top-level warnings from audits via the `auditContext`, similar to [how gatherers can do so from the `passContext`](https://github.com/GoogleChrome/lighthouse/blob/098d28189ba33f292d4f06824d62116a372aa976/lighthouse-core/gather/gather-runner.js#L411-L412).
happy to bikeshed on anything

core: expose LighthouseRunWarnings on audit context

---

lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/test/audits/dobetterweb/doctype-test.js
lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js

core(optimized-images): support non-standard mime types

---

.travis.yml
lighthouse-core/scripts/i18n/assert-strings-collected.sh
lighthouse-core/scripts/i18n/collect-strings.js
package.json

adds an assertion script to make sure we keep the strings up to date

misc(i18n): add assertion script

---

lighthouse-core/lib/asset-saver.js

For slightly cleaner log retrieval from lightrider

misc(asset-saver): tweak output format of logAssets

---

lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
lighthouse-core/audits/metrics/interactive.js
lighthouse-core/config/default-config.js
lighthouse-core/index.js
lighthouse-core/lib/i18n.js
lighthouse-core/lib/locales/en-US.json
lighthouse-core/lib/locales/en-XA.json
lighthouse-core/lib/locales/index.js
lighthouse-core/runner.js
lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-core/test/audits/metrics/interactive-test.js
lighthouse-core/test/lib/i18n-test.js
lighthouse-core/test/results/sample_v2.json
lighthouse-extension/app/src/lighthouse-background.js
typings/lhr.d.ts

An example of how we might be able to "fix" the strings before shipping the LHR, basically the i18n formatting function just returns a reference to the string to be used which is stored in a map, then at the end before returning, runner asks i18n to replace all the references in the LHR with the string of the appropriate locale. BOOM done! a log is kept of what replacements were made and added to the LHR as `localeLog` so that later the report could be translated again without re-running.

core(i18n): localize strings at end of run

---

lighthouse-core/lib/i18n.js
lighthouse-core/lib/locales/en-US.json
lighthouse-core/lib/locales/en-XA.json
lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/report/html/templates.html
lighthouse-core/runner.js
lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-core/test/lib/i18n-test.js
lighthouse-core/test/results/sample_v2.json
typings/lhr.d.ts

brings i18n strings to the renderer! this tackles most of what we need for performance category. strategy is what was outlined in #5655, strings are located at `lhr.i18n.rendererFormattedStrings` which the renderer uses to replace its own UIStrings in `util.js`
the `${n} audits` is definitely going to be a problem we're going to have to figure out, but for performance it only shows up for the "passed audits" section and none of the others which isn't the worst thing to live without at first if we need to

core(i18n): export rendererFormattedStrings

---

jest.config.js
lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
lighthouse-core/test/audits/critical-request-chains-test.js
lighthouse-core/test/audits/dobetterweb/appcache-manifest-test.js
lighthouse-core/test/audits/dobetterweb/dom-size-test.js
lighthouse-core/test/audits/metrics/estimated-input-latency-test.js
lighthouse-core/test/audits/metrics/first-meaningful-paint-test.js
lighthouse-core/test/audits/metrics/interactive-test.js
lighthouse-core/test/audits/seo/robots-txt-test.js
lighthouse-core/test/audits/user-timing-test.js
lighthouse-core/test/test-utils.js
typings/externs.d.ts

@brendankenny we do this post #5716 ?

tests: better display value tests with i18n

---

lighthouse-core/lib/i18n.js
lighthouse-core/runner.js
lighthouse-core/test/test-utils.js

fixes what @paulirish found in #5726

core(i18n): always use english for logs

---

lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/audits/critical-request-chains.js
lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/audits/font-display.js
lighthouse-core/audits/mainthread-work-breakdown.js
lighthouse-core/audits/time-to-first-byte.js
lighthouse-core/lib/locales/en-US.json
lighthouse-core/lib/locales/en-XA.json
lighthouse-core/scripts/assert-golden-lhr-unchanged.sh
lighthouse-core/test/results/sample_v2.json
package.json

from lightsights discussions. Let the bikeshedding commence!

core: adjust audit titles for consistency

---

lighthouse-core/audits/byte-efficiency/unminified-javascript.js
lighthouse-core/lib/i18n.js
lighthouse-core/lib/locales/en-US.json
lighthouse-core/scripts/i18n/collect-strings.js
package.json
yarn.lock

Adds support for string descriptions and defaulting all failureTitles to one for example
~~blocked on #5716~~

core(i18n): support descriptions

---

readme.md

**Summary**
SpeedCurve just added support for Lighthouse, and we thought it was worth adding to the Lighthouse Integrations section!
Relevant announcement blog post: https://speedcurve.com/blog/lighthouse-scores-now-available/

docs(integrations): Add SpeedCurve to "Lighthouse Integrations"

---

lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/time-to-first-byte.js
lighthouse-core/lib/i18n.js
lighthouse-core/lib/locales/en-US.json

core(i18n): add [ICU Syntax] label to relevant message descriptions

---

lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/time-to-first-byte.js
lighthouse-core/lib/i18n.js
lighthouse-core/lib/locales/en-US.json

First, a word from the docs:
> The industry standard, ICU MessageFormat Syntax, is used to format these messages internally. However, only select parts of that syntax work at Google.
lol thx. So #5736 was a waste and doesn't work. So we'll describe the placeholders this way.

core(i18n): reframe the ICU message descriptions with placeholders

---

lighthouse-core/config/config.js
lighthouse-core/config/constants.js
lighthouse-core/lib/i18n.js
lighthouse-core/runner.js
lighthouse-core/test/config/config-test.js
lighthouse-core/test/lib/i18n-test.js
lighthouse-core/test/lib/locales/index-test.js
lighthouse-extension/app/src/lighthouse-background.js
package.json
tsconfig.json
typings/externs.d.ts
typings/lookup-closest-locale/index.d.ts
yarn.lock

cf. #5719
Sets up locale fallbacks, using the pretty common method of pruning on the last `-` until some prefix of the original locale is found, falling back to the default locale if no match is found.
Also adds a test to make sure that for any locale we set we also have a fallback for that language. So if e.g. we had `pt-BR` but not `pt-PT` for some reason, we'll be guaranteed to have `pt` to fall back to. Looking at our (eventual) list of supported languages, we shouldn't have to do any artificial mappings to support this like I'm doing in this PR.
Since locale is part of `config.settings`, it makes sense to initialize and check it in `Config`, so this moves it there. This allows removing some of the optional uses that had defaults coming from a few different places depending on the …

core(i18n): add locale fallbacks when language not supported

---

lighthouse-cli/test/fixtures/seo/seo-tester.html
lighthouse-core/gather/driver.js

**Summary**
Bugfix: fixes websites overriding URL variable with something custom
When running `node  lighthouse-cli/index.js https://www.dailyo.in -G --verbose --devtools.throttling=provided` you get the following output:
```
Sat, 28 Jul 2018 11:14:27 GMT method <= browser OK:verbose Runtime.evaluate {"result":{"type":"object","value":[{"err":{"message":"URL is not a constructor","stack":"TypeError: URL is not a constructor\n    at matches.forE
Sat, 28 Jul 2018 11:14:27 GMT method <= browser OK:verbose Runtime.evaluate {"result":{"type":"object","value":[{"err":{"message":"URL is not a constructor","stack":"TypeError: URL is not a constructor\n    at matches.forE
```
#5701

core(non native url): fail test when url is not a native implementation

---

lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/report/html/renderer/util-test.js

another piece of #5719, localize the numbers according to the locale specified in the LHR
note the 0,3 s

report(i18n): use LHR locale for toLocaleString

---

lighthouse-core/audits/accessibility/manual/interactive-element-affordance.js
lighthouse-core/config/default-config.js
lighthouse-core/test/results/sample_v2.json

**Summary**
Add new a11y manual audit for interactive element affordance
New feature
Forgetting to provide affordances for links and buttons is a common web accessibility issue that is often overlooked because it is a manual check. In preparation for adding this audit, I already added corresponding documentation to the Google Web Fundamentals "[How To Do an Accessibility Review](https://developers.google.com/web/fundamentals/accessibility/how-to-review#interactive_elements_like_links_and_buttons_should_indicate_their_purpose_and_state)" page.   https://github.com/google/WebFundamentals/pull/6384
https://github.com/GoogleChrome/lighthouse/issues/5667

new_audit: add a11y manual audit for interactive element affordance

---

lighthouse-core/lib/locales/en-US.json
lighthouse-core/lib/locales/en-XA.json
lighthouse-core/report/html/renderer/crc-details-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
lighthouse-core/test/results/sample_v2.json

A lot of the text is actually just the path and origin of each request so there wasn't actually that much here.

report(i18n): localize CRC renderer strings

---

lighthouse-core/lib/locales/en-US.json
lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-core/test/results/sample_v2.json

the messages come back from TC sorted, so we should keep things sorted originally. 
(i'll fix the conflicts when landing)

core(i18n): sort the ICU messages when saved

---

jest.config.js

since CI uses custom `*:ci` npm scripts that have `--coverage` included, i'm not sure why we defaulted to coverage collected in the config.

tests(jest): disable coverage collection by default

---

lighthouse-core/runner.js
lighthouse-extension/app/src/lighthouse-background.js
lighthouse-extension/app/src/lighthouse-ext-background.js
lighthouse-extension/app/src/popup.js

disclaimer: This is a breaking change for our integrations with them so all the clients must also update for this to work.
So I'm okay with delaying this PR for a bit.
------
This simplifies how we were juggling "options" coming in from extension/devtools/LR. Basically we were passing around an `options` object in the 2 -background files and all we cared about was its `flags` property. And in the case of LR, 2 other props came in on `options` and eventually are delivered into `Runner.run`, despite our typing.
reviewers: 
runner.js only has a rename. boring.
the background files have all the good stuff.

extension: refactor option/flag passing (breaking change)

---

lighthouse-cli/test/cli/run-test.js
lighthouse-core/audits/redirects.js
lighthouse-core/index.js
lighthouse-core/runner.js
lighthouse-core/test/config/default-config-test.js
lighthouse-core/test/results/sample_v2.json

fixes #5778
seems like this was accidentally left out of #5296 and we didn't catch it.
but the real question is: where should this test go?

core(redirects): update to modern opportunity details type

---

lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/user-timings.js
lighthouse-core/lib/locales/en-US.json

also a driveby fix for b/112186129

core(i18n): add strings for user timing entries table

---

lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/psi.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/report/html/renderer/psi-test.js
lighthouse-core/test/report/html/renderer/util-test.js
typings/html-renderer.d.ts

and move `getFinalScreenshot` from `Util` to `PSI`
fixes #5803

report: add PSI.prepareLabData()

---

lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html

This is the lighthouse side of some work for Lightsights.
- 2 columns squeeze to 1. rename column classes to be more general]
- drop the left padding on audit details always. even when we're in a wide viewport
- updated icons for metrics & diagnostics
- filmstrip responsiveness
- top nav score headers dont squish so much anymore.
- a few other small things
https://bitter-care.surge.sh/cnn.html
https://bitter-care.surge.sh/z.devtools.cnn.html
This plus some more PSI styles gives the.. Lightsights report: 
https://goto.google.com/anxlo (🔒 googlers only)

report: responsive styles

---

lighthouse-core/report/html/renderer/psi.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/test/report/html/renderer/psi-test.js
typings/html-renderer.d.ts

requested by PSI
[ignore whitespace](https://github.com/GoogleChrome/lighthouse/compare/preparefn?w=1) in the diff.

report: expose prepareLabData directly as a fn

---

lighthouse-core/lib/emulation.js

Quick cleanup. Trying out updates for driver et al based on protocol types in https://github.com/ChromeDevTools/devtools-protocol/pull/113, I noticed some old-looking stuff in `emulation.js`. `Driver` is only needed for its type, all config setting values are set by this point using `constants.js`, not the ones in this file, etc

core(tsc): update types in emulation.js

---

lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js

Per [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), _"Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]"_. `cache-control` is defined as comma separated list, and as reported in #5742 this case is not handled correctly resulting in misreported files.
This PR fixes that denoted case within `uses-long-cache-ttl.js` and adds a test to verify this going forward.
Resolves #5742

core(byte-efficiency): combine multiple cache-control headers if found

---

lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/report/html/renderer/util-test.js

For harmony with PSI thresholds.
note that `Util.PASS_THRESHOLD` also affects when [`title` vs `failureTitle` is selected for an audit](https://github.com/GoogleChrome/lighthouse/blob/049af195ab33d40718e6fe39a278de1c2ec07ec5/lighthouse-core/audits/audit.js#L192-L196)
@paulirish

report: make red/orange/green score color thresholds tougher

---

lighthouse-core/audits/byte-efficiency/efficient-animated-content.js
lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/byte-efficiency/unminified-css.js
lighthouse-core/audits/byte-efficiency/unminified-javascript.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/audits/byte-efficiency/unused-javascript.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
lighthouse-core/audits/byte-efficiency/uses-text-compression.js
lighthouse-core/audits/byte-efficiency/uses-webp-images.js

fixes a bug where running this cmd emits 'cannot read traceEvents of undefined':
```sh
lighthouse -A --only-audits=uses-optimized-images  http://cnn.com
```
these audits don't _require_ it for the audit necessarily, but lantern is used for the savings calculation and thus we need the trace to build the dependencyGraph.
this seems more straightforward than dealing with the inheritance of `audit.meta.requiredArtifacts[]`

core: all ByteEfficiency audits require a trace

---

lighthouse-core/audits/metrics/first-contentful-paint.js
lighthouse-core/lib/locales/en-US.json
lighthouse-core/test/results/sample_v2.json

- Replaces `First contentful paint` with `First Contentful Paint`, which is how it's formatted in the [Paint Timing spec](https://w3c.github.io/paint-timing/).
- Links to our new reference doc.

docs: link FCP audit description to lighthouse docs

---

lighthouse-cli/bin.js
lighthouse-cli/cli-flags.js
lighthouse-cli/printer.js
lighthouse-cli/run.js
lighthouse-cli/sentry-prompt.js
lighthouse-cli/test/cli/run-test.js
lighthouse-core/config/config.js
lighthouse-core/index.js
lighthouse-extension/app/src/popup.js
typings/externs.d.ts

I've had a few TODOs sprinkled in the code to `fix Flags type`. I'm not exactly sure what I meant by that, but this PR makes sure our uses of `Flags` are all correct and gets to remove two places (`index.js` and `popup.js`) where we were coercing empty objects into Flags.
We allowed empty objects as flags there, and now the type system actually verifies that that's completely acceptable :)
We already had `LH.Flags` vs `LH.SharedFlagsSettings` (all properties shared by `LH.Flags` and `LH.Config.Settings`), and now I've added another level with `LH.Flags` vs `LH.CliFlags` (all properties *in addition* to `LH.Flags` that control just CLI functionality). This is another step in making `Flags` a little easier to reason about, because once they reach core, all those CLI flags aren't visible …

cli(tsc): make LH.Flags type correct and consistent

---

lighthouse-cli/bin.js
lighthouse-cli/cli-flags.js
typings/externs.d.ts

fix for https://github.com/GoogleChrome/lighthouse/pull/5849#discussion_r210955229
@patrickhulce

cli: enableErrorReporting must be undefined by default

---

lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/gather/computed/critical-request-chains.js
lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
lighthouse-core/lib/network-request.js

After adding `SelfMap` in #5849, went through all our uses of `Record<>` to see if we actually meant that the keys need to be mapped to themselves. This is the only case I could find.
Unfortunately that meant that some other types needed to be widened to accommodate this, but good to have the type of `RESOURCE_TYPES.Fetch` be `'Fetch'` and not `'XHR'|'Fetch'|'EventSource'|'Script'|...` :)

core(tsc): NetworkRequest.RESOURCE_TYPES type fix

---

lighthouse-core/config/default-config.js
lighthouse-core/config/full-config.js
lighthouse-core/config/mixed-content-config.js
lighthouse-core/config/perf-config.js
lighthouse-core/config/plots-config.js
typings/config.d.ts

This was flagged testing the typescript nightly against the current code base. `LH.Config.Category.description` and `LH.Config.Group.description` should both be optional [as they are in the LHR](https://github.com/GoogleChrome/lighthouse/blob/d1031575f3f79d7bedbe0f8d5e45a51e16189853/typings/lhr.d.ts#L60), and `LH.Config.Category.manualDescription` should also exist.
Also adds type annotations to the files themselves so that they're checked directly, rather than indirectly through their use in `config.js`.

core(tsc): type check config files

---

lighthouse-core/audits/mainthread-work-breakdown.js
lighthouse-core/lib/task-groups.js

Another change anticipating typescript 3.1nightly. Default index signatures are going away in JS ([my fault](https://github.com/Microsoft/TypeScript/pull/25996#issuecomment-408284828) :), so we'll need to migrate anything relying on that to either fully defined objects or explicit index signatures. We use those in a lot of places, so I thought I'd start now :)
Here `TaskGroupIds` just becomes the object's signature.

core(tsc): add explicit index signature in mainthread-work-breakdown

---

lighthouse-core/report/html/renderer/psi.js

@paulirish 
Since re-running was happening in the same page, `<style>` elements for the old report div were being removed but not added to the new report div (since they were flagged as already added).
Now, `prepareLabData()` always resets the attribute flag that marks `<style>`s as used, so styles will always be included in the returned element. As long as the entire div from a previous call to `prepareLabData()` has been removed this should be fine.

report(psi): reset template styles on every call of prepareLabData

---

lighthouse-cli/bin.js
lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/audits/user-timings.js
lighthouse-core/gather/computed/metrics/lantern-metric.js
lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/lib/i18n.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/runner.js
lighthouse-core/scoring.js
lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js
lighthouse-extension/app/src/lighthouse-ext-background.js

part of #5873
No real theme here, just scattered fixes where none needed major interventions. Resolves 23 errors when using `typescript@next`.
The other side of some of these fixes is going explicitly `any` or `ts-ignore`, but it didn't seem worth losing refactoring, intellisense, etc for most of these

core(tsc): remove more reliance on implicit index signatures

---

.cz-config.js

Seems better to have all that separated from `Core` in the changelog.

i18n: add i18n 'type' for prlint

---

lighthouse-core/gather/computed/metrics/metric.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/lib/traces/tracing-processor.js
lighthouse-core/test/gather/computed/metrics/first-meaningful-paint-test.js
lighthouse-core/test/gather/computed/page-dependency-graph-test.js

We were throwing on no toplevel events but only in the observed case, this PR adds the check in more places so we should fail all metrics all things that rely on the page dependency graph if there are no toplevel events.

core(tracing-processor): throw on no top level events

---

lighthouse-core/config/default-config.js
lighthouse-core/scripts/i18n/assert-strings-collected.sh

fix `module.exports` ordering issue introduced by #5858
Also makes the `i18n:checks` test fail if `collect-strings.js` throws an error

core: fix defaultConfig UIStrings and exit code for test

---

lighthouse-core/lib/errors.js

another part of #5873
apologies for the extra line breaks :) it was a lot easier to do it this way, and this file changes so rarely the new (slight) redundancy seems fine

core(tsc): don't use index signature in LHErrors

---

lighthouse-core/gather/computed/load-simulator.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js

part of #5873 (only `DetailsItem` remaining now...)
These two were causing a lot of errors so I put off looking into them, but turns out the fixes were so simple that I should have just included them in the earlier grab bag PR :)

core(tsc): don't rely on index signatures in load-simulator/simulator.js

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/page-functions.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/runner.js
lighthouse-core/scripts/benchmark.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/results/artifacts/artifacts.json
lighthouse-core/test/results/sample_v2.json
package.json
typings/artifacts.d.ts
typings/lhr.d.ts

**Summary**
Before we can start automatically adjusting throttling settings, we need to be collecting and detecting more environment information. This PR adds a `environment` property (proposed name) to the LHR that will contain the host machine information, detected device class, perhaps more network diagnostic information, etc.
Right now it has 3 properties
- `hostUserAgent` - This is just a copy of the lhr.userAgent property for now (assumed we can deprecate and remove in v4), the User Agent of the version of Chrome that Lighthouse is using.
- `networkUserAgent` - This is the user agent that was sent over the network to the site. It's been frequently requested and confused with the `hostUserAgent` so makes sense to provide both.
- `benchmarkIndex` - This is the ULTRADUMB™ benchmark …

core(lhr): expose environment info

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.js
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js

appveyor has been failing to find enough passive event listener failures. turns out there's a field trial to make wheel listeners passive by default too :) https://crbug.com/626196 (thanks @brendankenny for hunting the bug down!)

tests(smokehouse): update passive listener expectations

---

lighthouse-core/lib/network-request.js
lighthouse-extension/app/src/lighthouse-ext-background.js
typings/node.d.ts

**Summary**
In LR's case we don't have real transfer size, we just have the header of original content length. I went with the `isLightRider` global var for a few reasons.
1. It's the clearest way to ensure this hack does not ever impact our other channels.
2. It's a convenient way to track progress through the life of a network request (transferSize is updated multiple places and we need to reset this a couple times.
3. I have a feeling this won't be the last time LR has some subtle difference that needs to be accounted for.
sizes now look good with the traces/devtoolslog paul provided
fixes #5839

core(network): handle LR transferSize

---

lighthouse-core/audits/uses-rel-preload.js
lighthouse-core/test/audits/uses-rel-preload-test.js

Leftover cleanup from Lantern changes that happened while the preload PR was ongoing. Just removes the dependency on the CRC computed artifact, so that CRC can move to be based on the graph much more easily.

core(preload): remove CRC dependency

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.js

master is failing again because of another canary change, `createShadowRoot` is going to be removed in M73, so I just swapped it for one of our other deprecations

tests(dbw): remove createShadowRoot call

---

lighthouse-logger/index.js
lighthouse-logger/package.json
lighthouse-logger/yarn.lock
typings/lighthouse-logger/index.d.ts

In order to land #3745, we need logger to be published with the new functionality. This is just the `lighthouse-logger` portion of #3745 with a version bump to `1.1.0`

misc(logger): add time/timeEnd methods

---

readme.md

Hi again :)
**Summary**
Improve `readme.md` about potential Chrome connection issues while using `lighthouse-cli` and fix flags for node DevTools  debugging command.
Just a minor documentation improvement.
I think it's useful to make those additions more accessible. Might be frustrating for newbies to look it up.
Info from https://github.com/GoogleChrome/lighthouse/issues/2726#issuecomment-358287258

docs(readme): mention chrome-flags troubleshooting in getting started

---

lighthouse-core/audits/metrics/first-contentful-paint.js
lighthouse-core/gather/computed/trace-of-tab.js
lighthouse-core/test/fixtures/traces/preactjs.com_ts_of_undefined.json
typings/externs.d.ts

**Summary**
The underlying issue in #3838 is that we use the navstart of a navigation that is immediately cancelled and never takes place. Thus, we end up looking for all of our events of importance in the wrong timeframe.
The redirect comment (https://github.com/GoogleChrome/lighthouse/issues/3838#issuecomment-377514597) got me thinking about the correct navstart to be using though, and it seems like we should be capturing that performance hit and warning folks that they have multiple navigations. I wrote out a nice long argument for why we should do this, but I couldn't even convince myself it was the right thing to do since we'll break many existing customers that are ignorant of client-side redirects today.
Instead I've installed a quick fix that ignores navigations to targets that …

core(trace-of-tab): only use navstart of chrome/http documents

---

lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-viewer/app/src/drag-and-drop.js
lighthouse-viewer/app/src/lighthouse-report-viewer.js
lighthouse-viewer/app/src/main.js
package.json
yarn.lock

As mentioned in https://github.com/GoogleChrome/lighthouse/pull/5836#issuecomment-417763577, in order to update to the new protocol definitions and the rest of the improvements in #5836 we need to be running typescript 3.1.
Luckily the work in #5873 means that the remaining change is small, just dealing with some kind of annoying extra strictness in dom methods (e.g. handling that [technically `document.head` can be null](https://html.spec.whatwg.org/multipage/dom.html#dom-document-head)...just not in practice).

core(tsc): update to ts 3.1 for new protocol defs

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js

appveyor dbw smoke tests are failing because we now have an additional deprecation firing in Canary: HTML Imports :)
~(will switch to `>=3` to account for running Chrome stable on Travis after the Travis tests fail so I can verify that they fail :)~

tests(smokehouse): update expectations for HTML Imports deprecation

---

lighthouse-core/gather/gather-runner.js

Hi all :)
**Summary**
What this change does: always clear browser cache for reqested URL after successfull lighthouse run.
See issue below. Besides, it's always good advice to free resources in computing after specific task is done properly.
https://github.com/GoogleChrome/lighthouse/issues/4889
I'm off for now. Support on this PR is welcome :)
Cheers
midzer

core(gather-runner): call clearDataForOrigin on teardown

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/accessibility.js
lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener.js
lighthouse-core/gather/gatherers/dobetterweb/domstats.js
lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js
lighthouse-core/gather/gatherers/image-usage.js
lighthouse-core/gather/gatherers/seo/crawlable-links.js
lighthouse-core/gather/gatherers/seo/embedded-content.js
lighthouse-core/lib/page-functions.js

**Summary**
Export all functions in lib page-functions directly as string
Minor coding style i would say
Prettier code due not cluttering implementation files with multiple toString() calls
https://github.com/GoogleChrome/lighthouse/issues/5870

core: export any page-functions as string

---

docs/scoring.md

…ails
**Summary**
Adds a note to the docs about a small issue in PWA scoring with ```simplehttp2server``` package.
This is a docs change.
It's required because it has been causing some issues and they are not being documented as known issues.
#1217 
#5910

docs(scoring): http2 redirect PWA score issue

---

lighthouse-core/runner.js
lighthouse-core/test/runner-test.js

repro:
```sh
lighthouse http://paulirish.com --preset-perf -G
lighthouse http://paulirish.com --preset-perf -A
Error: Cannot run audit mode on different URL
```

core: normalize URL before checking equality

---

lighthouse-core/audits/screenshot-thumbnails.js

**Summary**
Improve caching logic for already existing thumbnail data to skip unnecessary (expensive) function calls
Should result in better performance on complete LH run. Did not measure though :|
More performance without overengineering is a good thing :)
https://github.com/GoogleChrome/lighthouse/issues/5957

core(screenshot-thumbnails): improve caching

---

docs/headless-chrome.md

Looks like the `chromium-browser` package was replaced with `chromium`

docs(example): Require Node 8 and apt install chromium

---

docs/headless-chrome.md

Not sure if this is the best place to include this snippet, but other's may run into this need as a headless setup.

docs(gist): example script to post report as gist

---

docs/scoring.md
lighthouse-core/report/html/templates.html

Release 3.1 updated the threshold from 0.75 to 0.9 for green in the report but the score legend wasn't updated.
Very small update to bring the score legend inline with the new threshold.

report: update score legend to match new threshold

---

lighthouse-core/audits/uses-rel-preconnect.js
lighthouse-core/audits/uses-rel-preload.js
lighthouse-core/test/results/sample_v2.json

**Summary**
For preconnect and preload audit potential savings of 0ms should not show
improve user experience
Dont show unncessary info
https://github.com/GoogleChrome/lighthouse/issues/5956

audit(preconnect, preload): dont show zero ms savings

---

readme.md

Created this project a while ago so people can brag about their Lighthouse score with shiny shields.io badges.
Related issue: https://github.com/GoogleChrome/lighthouse/issues/2005

docs(readme): add lh-badges to related projects

---

lighthouse-core/report/html/renderer/report-ui-features.js

**Summary**
Replace Typed OM's `element.getComputedStyle()` with CSSOM `window.getComputedStyle()`
Typed OM is not widely supported yet. Our delivered JS should work properly in all major browsers
https://developers.google.com/web/updates/2018/03/cssom#computed
fixes #5966
Yeah, this replacement looks a bit hacky. But I've not found a more elegant way

report(html): replace Typed OM getComputedStyle() with CSSOM equivalent

---

lighthouse-cli/bin.js
lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
lighthouse-core/gather/computed/trace-of-tab.js
lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
lighthouse-core/gather/gatherers/fonts.js
lighthouse-core/lib/arbitrary-equality-map.js
lighthouse-core/lib/i18n.js
lighthouse-core/lib/locales/index.js
lighthouse-core/lib/sentry.js
lighthouse-core/runner.js
lighthouse-viewer/app/src/lighthouse-report-viewer.js
package.json
yarn.lock

long-standing TODO.
Also fixes #5971

core(tsc): add type checking to sentry usage

---

lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js

`Util.showAsPassed()` now default compares to `RATINGS.PASS.minScore`; updated the perf-category render tests to check against the added `PASS_THRESHOLD` const. Resolves #5959 
*With PR*
*Without PR*

report(util): ✅ audits should be in Passed Audits

---

lighthouse-core/report/html/report-styles.css

**Summary**
Right now there is some inconsistency in our report on (mainly `<detail>`) elements who can be collapsed.  Mouse `cursor: pointer` should be set in CSS to indicate whether element is clickable
A minor bugfix. More testing is highly appreciated as I cannot be sure to cover every relevant element
Improve general user experience
https://github.com/GoogleChrome/lighthouse/issues/5958

core(report): fix cursor behaviour

---

docs/recipes/custom-audit/package.json

**Summary**
This PR fixes the Custom audit recipe under docs as the code was updated to use the v3 API but `package.json` wasn't.

docs(recipes): fix custom-audit recipe

---

readme.md

Sponsored by GoDaddy. We use this service to monitor thousands of new or modified websites every day.
https://github.com/godaddy/lighthouse4u

docs: lighthouse as a service

---

package.json
yarn.lock

changelog
* `35842ba4` fix: ignore stdio on `which` call (#121)
* `f126c3a0` fix: reject promise on failed kill() (#112)
* `5ee0fde2` Set custom error codes for all errors.
* `841bdf3f` Fix picking CHROME_PATH priority over other matches.
* `6b10d748` Fix Travis CI build: GCE for chrome bug (#87)
* `d4aa8295` Fix readme's default logLevel (#85)
* `5be71243` Type improvements (#102)
* `dd5fdd49` Stricter typing for logLevel (#105)
* `c9394cf7` Fix README typo: booelan ==> boolean (#104)
* Update chrome-flags-for-tools.md

deps: chrome-launcher to 0.10.4

---

lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/lh-error.js
lighthouse-core/lib/network-request.js
lighthouse-core/test/gather/gather-runner-test.js
typings/lhr.d.ts

Adds a pageLoadError for 400/500 http status codes. Fixes #4082; depends on #6014 (see https://github.com/GoogleChrome/lighthouse/commit/dcb468ab16ce71f0566fbca46e7ec41b604ad365 for actual diff).
[Example Report](https://googlechrome.github.io/lighthouse/viewer/?gist=4295b586ef6b9724aea0825ae1a8836d)
Good:
- catches the error
- warns user at the top of the report that it happened and they should fix their URL
- issues `runtimeError`
Less good:
- redundant with the `http-status-code` SEO audit (#3311). That audit successfully marks the page as 404ing (or whatever), but all the other audits around it are marked as `Error!` (since no gatherers in that pass return an artifact), so it's pretty much lost in the noise
- the [SEO 403 smokehouse …

core(gather-runner): include error status codes in pageLoadError

---

package.json

We're over by 0.3KB now. 
So this can is getting kicked. 👟🥫👉🛣

misc: bump bundlesize threshold a little more

---

lighthouse-core/audits/accessibility/axe-audit.js
lighthouse-core/gather/driver.js

**Summary**
This changes the Tracing.start protocol command to use the `ReportEvents` transferMode instead of `ReturnAsStream`.  This makes the trace gathering much faster, as observed in some automated run timings:
| URL | ReturnAsStream | ReportEvents | Difference |
|---|---|---|---|
| http://cnn.com | 3410ms | 1202ms | (2208ms) |
|http://paulirish.com| 174ms | 87ms | (~86ms) |
Note: timings are averages of 5 seperate runs with each method.
fixes #5968
closes #5939
Based on code in [old driver implementation](https://github.com/GoogleChrome/lighthouse/blame/0e8982ab037d928a37d8dddd00aa7f1e913f5414/helpers/browser/driver.js)

core(driver): deliver trace as events rather than a stream

---

lighthouse-core/lib/i18n.js

The regex we use for checking if there are strings in the LHR that need to be replaced with their localized version can be really slow against giant strings. Adding a pre-pass with a fast regex is one easy approach to speeding this up without changing our ID format or being too particular about the file paths we allow.
In a trace from the issues we're seeing in #6067, time for localization and report generation goes from ~3500ms to ~33ms.
Even time for localization in the much smaller artifacts in `yarn update:sample-json` goes from 150ms to 22ms :)

i18n: speed up replacement regex

---

lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/gather/gatherers/dobetterweb/domstats.js
lighthouse-core/lib/locales/en-US.json
lighthouse-core/lib/page-functions.js
lighthouse-core/test/audits/dobetterweb/dom-size-test.js
lighthouse-core/test/lib/page-functions-test.js
lighthouse-core/test/results/sample_v2.json

**Summary**
Reformatted the dom-size output table.  Converted the table to be more row-centric vs column centric.  See issue #5220 for discussion and screenshots.  Some CSS changes required from #6049 to format the `code` snippets and the left alignment of the text.
fixes: #5220 
requires: #6049

core(audit): make dom-size table prettier

---

lighthouse-core/lib/network-recorder.js
lighthouse-core/test/lib/network-recorder-test.js

**Summary**
root requests inside frames never fire a `loadingFinished` devtools event, we'll use the presence of a response as the criteria for finished instead.
#6067

core(network-recorder): consider iframe responses finished

---

lighthouse-core/report/html/report-styles.css

**Summary**
It aligns our columns & headings correctly.
This is how it looks:
https://codepen.io/wardpeet/full/zJyMGx
#6049

fix(report): align table headings & columns left & right

---

lighthouse-core/audits/manifest-short-name-length.js
lighthouse-core/audits/multi-check-audit.js
lighthouse-core/audits/splash-screen.js
lighthouse-core/audits/themed-omnibox.js
lighthouse-core/audits/webapp-install-banner.js
lighthouse-core/gather/computed/manifest-values.js
lighthouse-core/gather/computed/new-computed-artifact.js
lighthouse-core/lib/arbitrary-equality-map.js
lighthouse-core/runner.js
lighthouse-core/test/audits/manifest-short-name-length-test.js
lighthouse-core/test/audits/splash-screen-test.js
lighthouse-core/test/audits/themed-omnibox-test.js
lighthouse-core/test/audits/webapp-install-banner-test.js
lighthouse-core/test/gather/computed/manifest-values-test.js
tsconfig.json
typings/artifacts.d.ts
typings/audit.d.ts
typings/externs.d.ts

Proof of concept of moving computed artifacts off of the `artifacts` object passed into audits and just use regular `require('./path/to/computed-artifact.js')` to use them.
Starts with a really simple computed artifact, `manifest-values.js`, which doesn't need to request any computed artifacts itself, nor does any computed artifact request it, but it is non-trivial and required in four audits. The computed artifact cache is now part of `LH.Audit.Context`, and audits need to pass in the cache rather than it being created and bound behind the scenes.
Nice thing about this approach is non-converted computed artifacts can continue to function as-is and we can convert them one by one (or in bunches) rather than in one massive, unreadable PR.
There are a few things we lose without the …

core: initial refactor of computedArtifact import/caching

---

lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/lh-error.js
lighthouse-core/lib/strings.js
lighthouse-core/runner.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/runner-test.js

fixes #6071
- runtimeWarnings and runtimeError both use the same message for page load errors
- no longer throw on > 50% of audits failing (top level `runtimeError` and individual audit errors now take care of warning the user in that case)
- Show error `friendlyMessage` in HTML report's warning box (`runWarnings`)
bonus: no longer have a big red `GatherRunner:error FAILED_DOCUMENT_REQUEST` error log on the pageLoadError we expect in the offline pass when a page doesn't support offline :) @exterkamp

core: smooth rough edges of pageLoadError display and reporting

---

lighthouse-core/audits/themed-omnibox.js
lighthouse-core/lib/manifest-parser.js
lighthouse-core/lib/web-inspector.js
lighthouse-core/test/lib/web-inspector-test.js
package.json
typings/cssstyle/index.d.ts
yarn.lock

Another bit of WebInspector removed. Uses the CSS value parser (just to check if a string is a valid CSS color) from https://github.com/jsakas/CSSStyleDeclaration/blob/master/lib/parsers.js instead of the one in WebInspector.
bundle size is down another 1.4KB on top of #6090 after gzip :)

core: use cssstyle to parse CSS colors instead of WebInspector

---

lighthouse-core/audits/seo/font-size.js
lighthouse-core/lib/network-recorder.js
lighthouse-core/lib/web-inspector.js
lighthouse-core/test/audits/seo/font-size-test.js

inspired by @patrickhulce's comment in https://github.com/GoogleChrome/lighthouse/pull/5946#issuecomment-423608200, took a look at some of our current uses of WebInspector and found some that could be trivially removed.

core: remove some trivial uses of WebInspector

---

lighthouse-core/gather/driver.js

**Summary**
Added an undefined check for driver results to catch an undefined result coming back from the Protocol, which shouldn't happen, but we check anyway to catch if it does.
[Relevant Protocol](https://chromedevtools.github.io/devtools-protocol/tot/Runtime#method-evaluate)
addresses: #6026

core(driver): add check to make sure Runtime.evaluate result exists

---

lighthouse-core/gather/gatherers/seo/font-size.js
lighthouse-core/lib/web-inspector.js
package.json
yarn.lock

Update is easy now :) Fulfills the dream of #1535, though the problems it would have fixed back then don't exist anymore.
Hopefully this update will make it easier for whoever takes that last webinspector step, either completely isolating the WebInspector global pollution (cc @castilloandres) or reimplementing the font functionality in Lighthouse. With the updates to the fontend, the first should be quite a bit easier and the second should at least be at least a little easier to follow since the implementation will match current DevTools.

core: update chrome-devtools-frontend to latest

---

lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js
lighthouse-core/test/results/sample_v2.json

setting up snyk to do some nice highlighting on their side
| before | after |
|-|-|
| ![image](https://user-images.githubusercontent.com/39191/45932830-6b5a8100-bf37-11e8-89ea-0ec2b86a2c8a.png) | ![image](https://user-images.githubusercontent.com/39191/45932835-8200d800-bf37-11e8-8ffb-b384e0e55254.png) | 
pretty sweet.
cc @aviadatsnyk

report(vulnerable-jslibs): tweak snyk link for highlighted matches

---

package.json
yarn.lock

changes: https://github.com/johnmichel/Library-Detector-for-Chrome/compare/v4.3.1...v5.1.0
most notably: 
* better detection for react
* new detections added for preact/workbox/amp

deps: js-library-detector@5.1.0

---

lighthouse-cli/cli-flags.js
lighthouse-core/config/constants.js
lighthouse-core/config/lr-desktop-config.js
lighthouse-core/gather/driver.js
lighthouse-core/lib/emulation.js
lighthouse-core/lib/sentry.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/report/html/renderer/util-test.js
lighthouse-core/test/results/sample_v2.json
readme.md
typings/externs.d.ts

**Summary**
Introduces a new `emulatedFormFactor` enum to settings to eventually replace `disableDeviceEmulation` which is still respected. `emulatedFormFactor` defaults to `mobile` but can be one of `mobile`, `desktop`, or `none`. `none` is equivalent to setting `disableDeviceEmulation` to `true`.
closes #6092

core: add emulatedFormFactor setting

---

lighthouse-core/report/html/renderer/performance-category-renderer.js

Right now, "Values are estimated and may vary" is shown twice in the PSI case.

report(psi): remove redundant varience disclaimer

---

.npmignore
docs/releasing.md
lighthouse-cli/test/fixtures/static-server.js
package.json

_update_: see https://github.com/GoogleChrome/lighthouse/pull/5345#issuecomment-424825309

docs(releasing): minor updates

---

lighthouse-core/gather/computed/metrics/lantern-interactive.js
lighthouse-core/lib/file-namer.js
lighthouse-core/lib/i18n/locales.js
lighthouse-core/report/report-generator.js
lighthouse-core/scripts/update-report-fixtures.js
lighthouse-viewer/app/src/firebase-auth.js
lighthouse-viewer/app/src/github-api.js
lighthouse-viewer/app/src/lighthouse-report-viewer.js
lighthouse-viewer/app/src/viewer-ui-features.js
package.json
typings/externs.d.ts
yarn.lock

Typescript 3.1 is out, time to move off a nightly version and to the official release :)
Also removed a few outdated `@ts-ignore` comments.

deps: update to tsc 3.1.1

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/gather/gatherers/dobetterweb/js-libraries.js

#6102 bumped our version of js-library-detector, but included in that latest version is the first async detector function, so we need to await the result (otherwise it always passes since the promise is truthy regardless of how it's resolved).
Arguably fixes #6125, as any other work will probably have to be upstream.

core: await js-libraries detection

---

lighthouse-core/test/lib/minification-estimator-test.js
package.json
yarn.lock

tests: add angular test for JS minification

---

lighthouse-core/audits/final-screenshot.js
lighthouse-core/audits/manifest-short-name-length.js
lighthouse-core/audits/splash-screen.js
lighthouse-core/audits/themed-omnibox.js
lighthouse-core/audits/webapp-install-banner.js
lighthouse-core/gather/computed/new-computed-artifact.js
lighthouse-core/gather/computed/screenshots.js
lighthouse-core/runner.js
lighthouse-core/test/audits/final-screenshot-test.js
lighthouse-core/test/gather/computed/manifest-values-test.js
lighthouse-core/test/gather/computed/screenshots-test.js
typings/artifacts.d.ts

#5907 didn't quite work because computed artifacts need to call each other, so need access to the `context` to pass it on to the next computed artifact :)
Since that's now explicit, flipped the order of the parameters so it's `compute_(inputArtifacts, context)`, which matches the interface for `audit.audit()` (not sure why I did it the other way before). About 3/4 of this PR is flipping the order for `manifest-values` from #5907.
Also updated `screenshots.js` to this new format.

core(computed): fix new computed artifact interface

---

lighthouse-extension/app/src/lighthouse-ext-background.js

Was a bit of a hack introduced back in cl/180501824

extension(lr): skip early emulation now that lr-desktop is defined

---

lighthouse-core/lib/network-recorder.js
lighthouse-core/lib/network-request.js
lighthouse-core/test/lib/network-recorder-test.js

**Summary**
Adds `isValid` property to a NetworkRequest and ignores invalid requests when making the list of records to surface to rest of application.
fixes: #6145

core(network): handle invalid NetworkRequests

---

.npmignore

Issues: #6150
**Summary**
Solves #6150

chore: 🤖 add back lighthouse-core scripts to npm package

---

lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js
lighthouse-core/test/results/sample_v2.json

**Summary**
This change adds utm parameters in the url to snyk.
#6165 is the same as this PR, only this one fixed the tests and is CLA-compatible (email issue)

core(audit): add utm parameters when calling snyk

---

lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/test/audits/byte-efficiency/offscreen-images-test.js

fixes: #5955 
**Summary**
Makes it so that when TTI derivation throws an error, the offscreen-image audit will fallback to using EndOfTab trace for cutoff instead of erroring out.

core: make offscreen-images audit work without TTI

---

lighthouse-core/test/audits/byte-efficiency/total-byte-weight-test.js
lighthouse-core/test/audits/byte-efficiency/unused-css-rules-test.js
lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
lighthouse-core/test/audits/critical-request-chains-test.js
lighthouse-core/test/audits/dobetterweb/uses-http2-test.js
lighthouse-core/test/audits/font-display-test.js
lighthouse-core/test/audits/is-on-https-test.js
lighthouse-core/test/audits/mixed-content-test.js
lighthouse-core/test/audits/network-requests-test.js
lighthouse-core/test/audits/redirects-test.js
lighthouse-core/test/audits/seo/http-status-code-test.js
lighthouse-core/test/audits/uses-rel-preconnect-test.js
lighthouse-core/test/audits/uses-rel-preload-test.js
lighthouse-core/test/gather/computed/main-resource-test.js
lighthouse-core/test/network-records-to-devtools-log.js

This came up while refactoring computed artifacts and I've separated it to keep the PRs simpler. Since we'll be requiring files normally, we can't just inject `requestNetworkRecords` into tests anymore (at least not as easily).
We have a lot of places that we want to pass in example/simplified `networkRecords`, however our core artifact for network activity is the `devtoolsLog`. This PR adds a simple test utility that will create a `devtoolsLog` that, when passed back into `NetworkRecorder`, will create `networkRecords` with all the same properties.
Very simple records can be passed in (good for tests! e.g. just `[{url: 'https://example.com}]`) and the rest of the needed properties will be filled in with reasonable-ish defaults.
I've gone through all the existing tests that were mocking …

tests: add networkRecord-to-devtoolsLog mocking utility

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

**Summary**
Added Safari support!  Main areas of focus were:
- fixing tables
- fixing header sticky-scrolling
- fixing scroll > 100% making LH icon scale too large

report: add html report viewing support for safari

---

docs/throttling.md
lighthouse-core/audits/load-fast-enough-for-pwa.js
lighthouse-core/audits/predictive-perf.js
lighthouse-core/config/constants.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/audits/byte-efficiency/render-blocking-resources-test.js
lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js
lighthouse-core/test/results/sample_v2.json
readme.md

Good summary copied from @paulirish below:
> The goal of a good mobile throttling preset is never to accurately reflect the conditions of a cellular telecommunications system. It's to reflect the conditions that real users experience.
> The preset here attempts to capture latency/throughput of ~80 percentile observed connection data from the wild. As people globally acquire faster connections, this preset should be updated to keep pace.
> Right now, we have no changes to make in the latency/throughput numbers.
> However given the recent adoption of 4G, this preset actually now captures a 4G experience moreso than a 3G experience.
--------------------------------------------
We don't actually reference 3G in *that* many places, I think this effort will be mostly about docs and how we talk …

report: reframe Fast 3G as Slow 4G

---

lighthouse-core/gather/gatherers/accessibility.js

**Summary**
Disable axe audits:
table-fake-caption
td-has-header
marquee
diff can be found here
https://www.diffchecker.com/1S1zqgRH
```
axeResult.violations.map(x => x.id).concat(axeResult.inapplicable.map(x => x.id)).concat(axeResult.incomplete.map(x => x.id)).concat(axeResult.passes.map(x => x.id))
```
#6169

fix(axe): disable unused audits

---

lighthouse-core/test/audits/byte-efficiency/offscreen-images-test.js
lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js
lighthouse-core/test/audits/redirects-test.js
lighthouse-core/test/audits/uses-rel-preload-test.js
lighthouse-core/test/create-test-trace.js
lighthouse-core/test/network-records-to-devtools-log.js

other half #6195. This PR adds a simple trace creator to easily create test traces that match the needed characteristics. Right now it accepts timestamps for navStart and the end of the trace, and then a set of timestamps and durations for top-level tasks (but the options can easily be expanded).
The allows easy replacement of a bunch of computed artifact mocks relying on a specific TTI or just needed a dummy trace so the computed artifacts don't throw while another aspect of the audit is being tested.
Some of these are a little more sensitive to future changes than what was found in #6195, but we do get a bit more robustness in that these files now test with real computed artifacts rather than just testing the quality of our mocks (which can be particularly risky when testing just simple …

tests: add test trace creator

---

lighthouse-core/test/audits/critical-request-chains-test.js
lighthouse-core/test/audits/metrics/speed-index-test.js
lighthouse-core/test/audits/screenshot-thumbnails-test.js
lighthouse-core/test/audits/seo/canonical-test.js
lighthouse-core/test/audits/seo/hreflang-test.js
lighthouse-core/test/audits/seo/is-crawlable-test.js
lighthouse-core/test/audits/time-to-first-byte-test.js
lighthouse-core/test/audits/uses-rel-preconnect-test.js
lighthouse-core/test/network-records-to-devtools-log.js

Follow up to #6171, using the `networkRecordsToDevtoolsLog` utility and passing in the resulting devtoolsLog instead of mocking network records directly. Also removed some other low hanging `request*()` mocks in these files.
Sorry for the test noise :)

tests: remove more mock computed artifacts

---

lighthouse-core/audits/critical-request-chains.js
lighthouse-core/report/html/renderer/crc-details-renderer.js
lighthouse-core/test/results/sample_v2.json
typings/audit.d.ts

**Summary**
Removes empty children object from the crc details LHR.  This will allow the proto struct to parse the crc details object 1:1.
#6183

core(critical-request-chain): remove empty children from LHR

---

package.json
yarn.lock

grabs [a few](https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+milestone%3A%22TypeScript+3.1.2%22+label%3A%22fixed%22+) [bug fixes](https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+milestone%3A%22TypeScript+3.1.3%22+label%3A%22fixed%22+).
Biggest improvement (well, restoring the status quo before 3.1 :): if you "use workspace version" of tsc in your editor, you should see improved completion suggestions.

deps: update typescript to latest patch release

---

lighthouse-core/lib/icons.js
lighthouse-core/test/lib/icons-test.js

**Summary**
Makes the icon pngSizedAtLeast function check the file extension _only if there is no typehint_ like Chrome does.
fixes: #6208

core(icons): defer to manifest-icon type hint for image type

---

docs/new-audits.md

there was some nonsense in here about the "full config". But I also wanted to prioritize defining what it looks like in the report.

docs(new-audits): revise issue template

---

lighthouse-core/gather/driver.js
lighthouse-core/lib/task-groups.js

After #6117 allowed us to remove `toplevel`, I had a feeling we could remove more, like `loading` or `benchmark` trace categories.
Tried some things and... we can! It knocks another 20% off the trace size. :)
Details follow..
-------------------
I started by auditing all the trace events I can tell we care about. And I grabbed the category they're currently traced with in Chromium:
<details>
Trace events _required_ by Lighthouse and their assigned categories
| trace event name | categories |
|-|-|
| ActivateLayerTree | disabled-by-default-devtools.timeline.frame |
| Animation | blink.animations,devtools.timeline,benchmark,rail |
| BlinkGCMarking | _(not used anymore, removing)_ |
| CompositeLayers | disabled-by-default-devtools.timeline |
| domContentLoadedEventEnd | …

core(driver): reduce required traceCategories again

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/traces/tracing-processor.js
lighthouse-core/test/gather/driver-test.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js
typings/gatherer.d.ts

Backstory in #3596. 
Results: cnn.com's trace goes from 69M to 47M.
--
* Using `Browser.getVersion` and parsing out the chrome milestone. We can augment this pattern later for `isMobile` and `os` like @patrickhulce suggested.
* I made a lil sendCommand mock response helper in driver-test. There are similar stubs for `on()` and `once()`. 
* we now default to the new `disabled-by-default-lighthouse` category and fallback to 'toplevel', as @brendankenny very wisely suggested
* ideally i'd like to drop the `SCHEDULABLE_TASK_TITLE` possibilities from _FOUR_ down to 2. But it requires updating a lot of fixture data. So we can do that in a followup.

core(driver): request smaller trace in m71+

---

lighthouse-extension/app/src/popup.js

**Summary**
I think someone's already mentioned this but we don't need to prompt folks to file bugs for this one.

extension: stop report bug prompt for file:// urls

---

lighthouse-core/report/html/report-styles.css

**Summary**
Fixes the report hover bug on report.
demo:
http://wardpeet-filestorage.surge.sh/lh-store/pr-6288/report.html
#5796

fix(report): fix tooltip hover animation

---

lighthouse-core/lib/sentry.js

**Summary**
WDYT about this @brendankenny ?
closes #5994

misc: only allow 1 error from each audit/gatherer

---

lighthouse-core/lib/lh-error.js

This is an actual log from LR:
> `LHError: UNKNOWN_ERROR Unknown error encountered with message 'Protocol error (Tracing.start): [object Object]'`
The true origin is most likely... (_drumroll..._)
> [**Tracing is already started**](https://cs.chromium.org/chromium/src/content/browser/devtools/protocol/tracing_handler.cc?l=379&rcl=6c1d24539cea713814a538600c5f298f0d7d1e25)
Our best friend. 👨‍❤️‍👨
----------
As to why this PR makes sense.. Well... I can't really explain why `message` here is sometimes an object (and otherwise a string)... but the log above seems to indicate that's precisely what's happening. Could be the flu shot making me crazy though. 🤷‍♂️

core(driver): stringify protocol error messages

---

lighthouse-core/lib/lh-error.js

The fix actually belong in a nearly-identical line of code in the Lightrider connection class. :)

Revert "core(driver): stringify protocol error messages (#6302)"

---

lighthouse-core/gather/driver.js

On LR I'm seeing a lot of errors to do with handleJavaScriptDialog. The error response is typically this:
> {"error":{"code":-32602,"message":"No dialog is showing"},
For whatever reason, on LR, this error will reject starting inside the connection and then terminate the entire run.
The comment about intentionally unhandled comes from here: https://github.com/GoogleChrome/lighthouse/pull/2106#discussion_r114204201 which seems irrelevant at this point. I don't see why we wouldn't catch this.
closes #2402 
ref #2141

core(driver): recover from rejection on handleJavaScriptDialog

---

lighthouse-core/lib/sentry.js
lighthouse-core/test/lib/sentry-test.js

**Summary**
adds a few basic tests for the sentry functionality
#6215

tests: add basic sentry tests

---

lighthouse-core/lib/proto-preprocessor.js
lighthouse-core/test/lib/proto-preprocessor-test.js

**Summary**
Adds configSettings.output processing.
preprocessing for: #6309

misc(proto): adjust configSetting.output in preprocessor

---

lighthouse-core/lib/page-functions.js
lighthouse-core/runner.js
proto/lighthouse-result.proto
proto/sample_v2_round_trip.json

**Summary**
Benchmark index is actually a double!  Not an int!
fixes: #6331

misc(proto): convert int32's into DoubleValue in proto

---

.github/CODEOWNERS
proto/lighthouse-result.proto

**Summary**
Changed default LighthouseError enum to `UNDEFINED` and added proto/ to the CODEOWNERS.

misc(proto): made default LighthouseError enum 'UNDEFINED'

---

lighthouse-cli/cli-flags.js
readme.md

cli(docs): update docs for --output-path re: multiple output types

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/lh-error.js
lighthouse-core/lib/strings.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js
typings/gatherer.d.ts

After encountering an SSL error, some commands to the Network/Page domains either took awhile to timeout, or hung forever (only seemed to happen for `ERR_CERT_SYMANTEC_LEGACY`). You can see this at https://ilkayuyarkaba.av.tr/tag/istifaya-zorlanan-iscinin-kidem-tazminati (use canary).
If one of the passes generates an SSL error, just bail. A report is generated with a useful error message at the top.
Fixes #6287.

core: bail if encounter insecure ssl cert, to avoid hanging forever

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-core/gather/driver.js
lighthouse-core/lib/page-functions.js

**Summary**
HTMLElement.prototype.matches was being overriden (by userland code), so we now store the native implementation at `HTMLElement.prototype.__matches` and use that instead.
Not sure how to make a test for this. If you use the sample HTML provided in the associated ticket, you'll see that the error no longer occurs.
Fixes #5934

core: save native HTMLElement.prototype.matches function

---

lighthouse-core/gather/gather-runner.js
lighthouse-core/gather/gatherers/gatherer.js
lighthouse-core/runner.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/runner-test.js

core: remove recoverOrThrow / err.fatal

---

.travis.yml

Node 10 is rapidly approaching LTS. We should be running our tests on Node 8 and 10, not 8 and 9 :)

 tests: run node 10 on Travis

---

lighthouse-core/audits/image-aspect-ratio.js
lighthouse-core/test/audits/image-aspect-ratio-test.js

fixes incorrect aspect ratio bug if the image is 1x1 pixel by filtering the image less than 5 * 5
pixels dimension
#6290

core(fix): fix incorrect aspect ratio bug if the image is 1x1 pixel

---

lighthouse-core/test/lib/i18n/locales-test.js

Some recent ICU update (maybe in [Node 10.7](https://nodejs.org/en/blog/release/v10.7.0/)?) now acts upon the [recommended deprecation of some locale codes](https://www.unicode.org/cldr/charts/latest/supplemental/aliases.html) (namely, `in` -> `id` and `iw` -> `he`), and so we have a failure on a test checking that all our supported locales use canonical codes in more recent versions of Node.
For now we still support the deprecated codes with explicit aliases in `locales.js` because existing versions of Node won't do that extra canonicalization step, so this PR updates the test to recognize both the old and new behavior.

i18n: update test for new canonical locale codes

---

readme.md

**Summary**
This PR ads a new related project into Lighthouse called Lighthouse-github-reporter. More info on the issue.
https://github.com/GoogleChrome/lighthouse/issues/6097

docs(readme): Add new related project, lighthouse-github-reporter

---

proto/lighthouse-result.proto

**Summary**
Fixed comment linting in proto + added a LR hook.

misc(proto): fix linting and add LR hook

---

proto/lighthouse-result.proto

**Summary**
Missed tab offset for timing :cry: 
It's really fixed now...

misc(proto): align proto whitespace

---

.eslintrc.js
lighthouse-core/audits/uses-rel-preconnect.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/gather/gatherers/dobetterweb/domstats.js
lighthouse-core/lib/page-functions.js
lighthouse-logger/index.js

based on this: https://github.com/GoogleChrome/lighthouse/pull/6286#pullrequestreview-167563083 :)
It's surprising we don't enforce spacing around ternary operators, etc already. Enabled the [eslint rule](https://eslint.org/docs/rules/space-infix-ops) to enforce it. The few places where we were breaking seem like things we would normally correct anyways, so it seems reasonable to leave it enforced.

misc: enforce linting for infix-op spacing

---

lighthouse-core/scripts/lantern/run-once.js

**Summary**
easier if the path is resolved against, cwd instead of relative to scripts directory, the only usage in our codebase of run-once already fully resolves the path anyway.
#6378

misc: lantern script path resolution fix

---

lighthouse-logger/index.js
lighthouse-logger/package.json

misc(logger): isVerbose(), getTimeEntries()

---

lighthouse-core/audits/load-fast-enough-for-pwa.js
lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js

**Summary**
~In load-fast-enough-for-PWA the interactive when "provided" + mobile throttling is defaulted to force a simulated TTI, not the provided TTI (as shown in the top as the true TTI).  @brendankenny remembers this being purposeful, but it does make inconsistent numbers.  @patrickhulce do you have some context?~
Instead, will provide clearer explanation for why the TTIs might be different.
**TODO:** 
If we do want to revert to this pass through of settings we need to update a test in `lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js`
fixes: #6284

core(audits): clarify diff between load-fast-enough-for-pwa's TTI and perf TTI

---

package.json
proto/README.md

adds proto roundtrip update to `yarn update:sample-json` and updates `build-proto` to `build-proto-roundtrip`
(this is (1) and (2) of #6405)

misc: simplify proto npm scripts

---

lighthouse-core/gather/driver.js

core: increase Page.navigate timeout

---

lighthouse-core/lib/proto-preprocessor.js
lighthouse-core/scripts/cleanup-LHR-for-diff.js
lighthouse-core/test/report/proto-test.js
lighthouse-core/test/results/sample_v2.json
proto/lighthouse-result.proto
proto/sample_v2_round_trip.json

No more excluding items from the golden LHR.

test: use predictable numbers in golden LHR

---

lighthouse-core/lib/proto-preprocessor.js
lighthouse-core/test/lib/proto-preprocessor-test.js
proto/lighthouse-result.proto
proto/sample_v2_round_trip.json

**Summary**
Remove many of the configSettings from the proto definition.
moves #6202 along
fixes: #6309 (by deleting it from the proto)
closes: #6403

misc(proto): reduce proto configSettings to minimum needed

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-cli/test/smokehouse/pwa-expectations.js
lighthouse-cli/test/smokehouse/pwa2-expectations.js
lighthouse-cli/test/smokehouse/pwa3-expectations.js
lighthouse-core/audits/multi-check-audit.js
lighthouse-core/audits/offline-start-url.js
lighthouse-core/audits/webapp-install-banner.js
lighthouse-core/config/default-config.js
lighthouse-core/gather/gatherers/start-url.js
lighthouse-core/lib/manifest-parser.js
lighthouse-core/test/audits/offline-start-url-test.js
lighthouse-core/test/audits/webapp-install-banner-test.js
lighthouse-core/test/gather/gatherers/start-url-test.js
lighthouse-core/test/lib/manifest-parser-test.js
lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

Part of reorganization of the PWA category (#6395).
This splits the `start_url` offline check out of `webapp-install-banner.js` and into its own audit.
Based on top of #6396, so you may want to look at the diff between the two: https://github.com/GoogleChrome/lighthouse/compare/pwacat...start_url

new_audit: offline-start-url

---

changelog.md
clients/extension/manifest.json
docs/releasing.md
lighthouse-core/test/results/sample_v2.json
lighthouse-viewer/app/src/lighthouse-report-viewer.js
package.json
proto/sample_v2_round_trip.json

4.0.0-alpha.0

---

lighthouse-core/report/html/report-styles.css

**Summary**
Small CSS changes requested by psi to the report.  Very minimal visual impact. 
Left is old.  Right is new proposed.

report(css): make performance category more compact

---

lighthouse-core/config/config.js

**Summary**
On my machine 90% of the non-requireing time spent in config:init was just validating the categories. Simple conversion of this `.find` to a map eliminated ~60ms.
#6442

core(config): faster category validation

---

lighthouse-core/lib/url-shim.js
lighthouse-core/test/lib/url-shim-test.js

core(lib): add chrome-extension to URL allowedProtocols and add test

---

build/build-viewer.js
package.json
yarn.lock

fix bug introduced by #6426
Our version of the `gh-pages` npm package was really old, but I brought over the exact same version as before because it was working so why risk it. However, #6426 also tried to use `dest` from the docs (which wasn't supported in the old version) and it tried to promisify the whole thing. That should have worked (error-first callback as the last argument), but it looks like there was some incompatibility.
This PR
- updates the `gh-pages` package
- wraps `ghPages.publish` in an explicit promise
- adds a nicer `gh-pages` branch commit message than `Updates`, with the lighthouse version number in it
It took [two test commits and a revert](https://github.com/GoogleChrome/lighthouse/commits/gh-pages), but verified that it is working and deploying now :)

misc: fix viewer deploy

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/config/constants.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/test/gather/gather-runner-test.js
typings/config.d.ts

**Summary**
I'll want to put this through the DZL wringer and maybe someone sanity check this with the DevTools folks, but it seems like we should be able to just wait for the frameNavigated event instead of 300ms all the time.
On my machine it drives down about:blank times from...
300ms -> 200ms
300ms -> 16ms
300ms -> 14ms
If this gets cursory 👍 I'll remove references to blankDuration elsewhere, or we can keep it but just update the minimum to be 0
#6442

core(driver): wait for Page.frameNavigated for about:blank

---

lighthouse-core/report/html/report-styles.css

report: fix summary rendering in FF

---

lighthouse-core/report/html/renderer/details-renderer.js

**Summary**
Seo font-size audit has a 'Legible Text' value in an url column. Inside the report we run `new URL('Legible Text');` which throws an error in all browsers. We catch it by checking e.name is typeError. Edge just throws an Error with Invalid Argument as a message. We now support both.
#6444

fix(report): edge Invalid argument error

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/test/report/html/renderer/category-renderer-test.js

This makes the process of grouping under failed/passing/manual/notApplicable and then again under audit groups a lot easier to understand. It also sets the stage for making a new `pwa-category-renderer.js` (where they aren't split into failed/passing/etc) much easier.
Before the renderer was mixing up levels of failed/passing/notApplicable and audit groups, putting those states inside groups, then ending up rendering the opposite way (groups inside failed/passing/notApplicable). Manual audits were handled separately, even though it's just another of these states.
Instead, this new code sorts by state, then renders groups in each of them. The code is just a little shorter (longer with new tests), but it's hopefully easier to follow.
Importantly, this makes for an easy interface for …

report: refactor rendering of top-level failed/passing/etc sections

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js

working on #6395
The PWA category renderer needs to add custom icons to its groups (like the performance renderer does), but to do so without creating each group itself or grossly reaching into things, this PR sets it up by adding a class name to each group based on the group's id in the config (`.lh-audit-group--${groupId}`, modelled after the existing `lh-audit-group--metrics`, `lh-audit-group--opportunities`, etc).
To not collide with anything, the clump names need to move off a mishmash of class names (`lh-failed-audits`, `lh-audit-group--manual`, etc). So we'll just double down on "clump" for those :)
This PR also removes `lh-audit-group--unadorned` since "unadorned" is not a group name and it's somewhat ambiguous what should fall into that class, but that leaves a bit of a mess with …

report: rename clump classes; give classes to all audit groups

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/audits/themed-omnibox.js
lighthouse-core/audits/works-offline.js
lighthouse-core/config/default-config.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

Requested renames from #6395
- Going with "PWA Optimized" for the third group for now (see ongoing discussion in https://github.com/GoogleChrome/lighthouse/issues/6395#issuecomment-436420337)
- Updated "Address bar matches brand colors" to "Sets an address-bar theme color"
- Updated "Responds with a 200 when offline" to "Current page does not respond with a 200 when offline"
These are the replacements previously discussed. Note that we can keep tweaking after this, this just gets us to the state of the doc.

core(pwa): audit and report group renames

---

lighthouse-core/config/default-config.js
lighthouse-core/report/html/renderer/pwa-category-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/report/html/renderer/pwa-category-renderer-test.js
lighthouse-core/test/report/html/renderer/report-renderer-test.js
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

part of #6395
When all the audits in a PWA category group are passing, the icon goes from grayscale to color to indicate its badge (score gauge is still unstyled).

report(pwa): give badges to groups with all passing audits

---

lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/report/html/renderer/report-renderer-test.js
lighthouse-core/test/report/html/renderer/util-test.js

(temporarily) fixes #6540
Adds a check to `Util.prepareReportResult` to convert any `scoreDisplayMode` of `'not_applicable'` to `'not-applicable'` since the API is currently returning the first variant but the report renderer only understands the second.
Ideally we'll fix this at the API level (or, booooo, change the official LH value to the underscored version), but this fix is easier to deploy for now.
See #6371 and #6201 for background.
cc @exterkamp @ebidel

report: handle underscored not_applicable scoreDisplayMode

---

lighthouse-core/config/lr-desktop-config.js
lighthouse-core/config/lr-mobile-config.js

clients: skip h2 audit in LR

---

lighthouse-cli/run.js
lighthouse-cli/test/fixtures/infinite-loop.html
lighthouse-cli/test/smokehouse/error-config.js
lighthouse-cli/test/smokehouse/error-expectations.js
lighthouse-cli/test/smokehouse/run-smoke.js
lighthouse-cli/test/smokehouse/smokehouse.js
lighthouse-core/gather/driver.js
lighthouse-core/lib/lh-error.js
lighthouse-core/lib/strings.js
proto/lighthouse-result.proto

**Summary**
I've spent way too much time waffling back and forth on how to handle this, so I thought I'd just put it up for discussion. This PR throws a fatal error if, after our maxWaitForLoad is reached, the page doesn't seem to respond.
Right now this basically gets us earlier exit than trying to do all the gathering and not much else. I agree with @brendankenny that it's a bit dangerous to try to kill JavaScript and continue. If we do anything else I think it might be alternative 1, but still feels risky.
Alternatives:
- Wait for maxWaitForLoad, kill JavaScript, wait and see if page is still hung, then either fatally throw or try to continue
- Wait for maxWaitForLoad, kill JavaScript, and try to continue right away
- Continuously check if page is hung, kill JavaScript as soon as we …

core: throw fatally on page hang

---

lighthouse-core/gather/gather-runner.js

I _think_ we want to throw on security issues before we consider pageLoadError situations. wdyt?

core(driver): assert securityIssues before getPageLoadError

---

lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/lh-error.js
lighthouse-core/lib/strings.js
lighthouse-core/test/gather/gather-runner-test.js
proto/lighthouse-result.proto

Seeing a lot of these errors. I think we want to expose them to the user individually.

core(gather): define new DNS failure LH Error

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/templates.html

**Summary**
fixes the dropdown overlap between score container in safari.
demo:
http://wardpeet-filestorage.surge.sh/lh-store/pr-6546/report.html
#6510

report(safari): fix dropdown overlap translateZ

---

lighthouse-core/report/html/renderer/pwa-category-renderer.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/pwa-category-renderer-test.js
lighthouse-core/test/report/html/renderer/report-renderer-test.js

Part of #6395
~A bit hacked together, but it works. Work in earlier PRs keeps the hackiness fairly well contained, though, and it should be easy to revise what's in this initial draft.~
Currently

report: add PWA category badge gauge

---

lighthouse-cli/run.js

to fix the behavior brendan pointed out here: 
https://github.com/GoogleChrome/lighthouse/pull/6387#pullrequestreview-168541267

clients: exit CLI on unhandledRejection

---

lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/report-styles.css

While we figure out #6568, fixes @patrickhulce's https://github.com/GoogleChrome/lighthouse/issues/6568#issuecomment-438911350
The `Opportunities` group icon was being given to the old-style `lh-audit-group--opportunities` css class, but the Opportunities group under `Passed` had the new-style `lh-audit-group--load-opportunities` (`lh-audit-group--` + `groupId`).
This PR just standardizes on the new style of class name.
Before:
After:

report: give passed-opportunities group an icon

---

lighthouse-core/report/html/html-report-assets.js

Fixes viewer bundle size inflation introduced by #6593. The `details-element-polyfill` was accidentally being inlined as a base64-encoded Buffer and then having `toString()` called on it.
The string version is smaller, and we don't also need `Buffer` browserified in :)

report: import <detail> polyfill as string, not Buffer

---

lighthouse-core/computed/computed-artifact.js
lighthouse-core/lib/arbitrary-equality-map.js
lighthouse-core/test/computed/computed-artifact-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

split off from #6618
- log timing was added at the same time that #6204 updated computed artifacts, so timing info hasn't actually been collected for computed artifacts (timing was still accounted for in the audits that called them, though). This PR adds timing to the new version.
- #6204 messed up and was using strict equality testing for the computed artifact cache, not deep equality. Computed artifacts that take a bare artifact (e.g. `trace-of-tab`) had no issue with this and cached correctly. Any computed artifact that take a more complicated input (e.g. all the metrics) always found keys to be unequal, and so reran their computations every time they were called. This was especially bad in the lantern metrics, which tend to call each other a lot and benefit a good deal from caching. …

core(computed-artifacts): fix cache and add perf timing

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-cli/test/smokehouse/offline-config.js
lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js
lighthouse-cli/test/smokehouse/pwa-expectations.js
lighthouse-cli/test/smokehouse/pwa2-expectations.js
lighthouse-cli/test/smokehouse/pwa3-expectations.js
lighthouse-core/audits/installable-manifest.js
lighthouse-core/audits/multi-check-audit.js
lighthouse-core/computed/manifest-values.js
lighthouse-core/config/default-config.js
lighthouse-core/test/audits/installable-manifest-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json
types/artifacts.d.ts
types/audit.d.ts

Part of #6395 
Updates `webapp-install-banner` to be the new `installable-manifest` audit. SW detection was already deleted from here, so this mostly just updates the `id` and `title` and tightens some tests/removes some useless stuff.

core: rename webapp-install-banner audit to installable-manifest

---

lighthouse-cli/test/fixtures/offline-ready-sw.js
lighthouse-cli/test/fixtures/offline-ready.html
lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js

**Summary**
Curious what types of late service worker we don't catch. I saw @paulirish's comment that it's just calling `.register` but I was skeptical based on the other reports. I should not have been skeptical it lives up, and this just adds a smoketest to prove it. We wait for delays in loading the service worker script itself and delays in the install event too.
https://github.com/GoogleChrome/lighthouse/issues/2924#issuecomment-332989460
#5527

tests: add smoketest for slow service worker

---

lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/renderer/dom.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/renderer/report-ui-features.js

This is a little silly, but there's a small quality of life improvement, it closes an old TODO, and it eliminates a decent number of type assertions.
Bases the created element type on the tag name passed in, so e.g. `DOM.createElement('a')` returns an `HTMLAnchorElement`, not just a generic `Element`. If the tag is unknown, falls back to just `HTMLElement`, which is close enough to correct for us today.
Uses the [same tag-name-to-element-type map that tsc uses for `document.createElement`](https://github.com/Microsoft/TypeScript/blob/3e4c5c95abd515eb9713b881d27ab3a93cc00461/lib/lib.dom.d.ts#L4263-L4270), just with a union for the `HTMLElement` fallback instead of the function overload they use (and since `DOM.createElement` calls `document.createElement` internally, this type is checked …

report(tsc): infer createElement type from tag name

---

lighthouse-core/report/html/templates.html

part of #6395
@exterkamp noticed that a report completing just the PWA `Optimized` group was getting a blank gray badge gauge.
This fixes it to get the proper N/A gauge as specced.

report: fix pwa-optimized badge gauge

---

lighthouse-core/lib/url-shim.js
lighthouse-core/test/audits/uses-rel-preload-test.js

**Summary**
What kind of change does this PR introduce?
Don't regard an `intent:` request as key request
Is this a bugfix, feature, refactoring, build related change, etc?
Issue been tagged as bug. So bugfix :)
Link any documentation or information that would help understand this change
I'm unsure whether my change/addition goes in the right direction, as I cannot find more detailed information about `intent` protocol/requests
closes https://github.com/GoogleChrome/lighthouse/issues/6660
Cheers
midzer

core(url-shim): add intent protocol to NON_NETWORK_PROTOCOLS

---

lighthouse-core/gather/gatherers/accessibility.js
lighthouse-core/lib/page-functions.js
lighthouse-core/test/lib/page-functions-test.js

**Summary**
Splitting up [this PR](https://github.com/GoogleChrome/lighthouse/pull/5846) into more digestible bits. 
This PR just contains some page function tweaks, and a new function to get an element selector that we can show to the user.
Tap targets ticket: https://github.com/GoogleChrome/lighthouse/issues/4358

core: page function updates relating to upcoming tap targets audit

---

lighthouse-core/lib/minification-estimator.js
lighthouse-core/test/lib/minification-estimator-test.js

**Summary**
The minification estimator heuristics weren't accounting for regex character classes properly which meant that it could leave a regex prematurely.
fixes #6744

core(minification): properly handle regex character classes

---

lighthouse-core/report/html/report-styles.css

part of #6395
Widens the vertical margins around group header summaries to match the specced design (see discussion starting with https://github.com/GoogleChrome/lighthouse/issues/6395#issuecomment-439259634).
Before:
After:
Things are a little spread out for e.g. the a11y groups:
but it's not egregious

report: larger vertical margins for audit-group summaries

---

lighthouse-core/audits/service-worker.js
lighthouse-core/test/audits/service-worker-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

part of #6395
Adds a check to the `service-worker` audit to verify that the `start_url` is within the SW's scope.
This joins the #6609 check that the page itself is in scope. As with that check, this is mostly useful when first setting up the SW or someone accidently alters the scope somehow. The explanation for this audit will help with debugging other failures (e.g. offline).

core(service-worker): check that start_url is within SW's scope

---

lighthouse-core/gather/gatherers/image-usage.js

**Summary**
It is bugfix.
There is good check [Displays Images With Incorrect Aspect Ratio](https://developers.google.com/web/tools/lighthouse/audits/aspect-ratio). However, this check is not needed when  image has css property [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) different than `fill`. Values `cover` and `contain` already prevent this check. This PR makes values `scale-down` and `none` also prevent this check.
Appropriate links:
https://developers.google.com/web/tools/lighthouse/audits/aspect-ratio
https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
#6760

core(gather): fix usesObjectFit property for ImageElement

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/pwa-category-renderer.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/test/report/html/renderer/pwa-category-renderer-test.js

last item in #6395!
Adds a tooltip as discussed in https://github.com/GoogleChrome/lighthouse/issues/6395#issuecomment-439562286 and comments below that.
Was a little more work than expected because we needed `categoryGroups` piped through to get their titles, but not too bad since they were mostly already nearby.

report(pwa): add tooltip to badge gauge

---

build/build-viewer.js
clients/extension/scripts/popup.js
lighthouse-core/audits/critical-request-chains.js
lighthouse-core/lib/dependency-graph/base-node.js
lighthouse-viewer/app/src/drag-and-drop.js
lighthouse-viewer/app/src/viewer-ui-features.js
package.json
yarn.lock

typescript 3.2 is out!
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-32
Not a whole lot new for us. Main thing is that `Function.prototype.bind()` (and `call()` and `apply()`) are now strictly typed. Fortunately all our uses of `bind()` (mostly event listeners) seem to have been correct, so...good job us :)
There are a few other things that we'll benefit passively from going forward (see release notes). I'm excited that [`null` and `undefined` are now valid union discriminators](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#non-unit-types-as-union-discriminants). I'm fairly certain we have a few places in the code where we awkwardly work around this not working in the past, but I can't remember where they are so we'll just update …

deps: update to tsc 3.2.2

---

.github/ISSUE_TEMPLATE/Bug_report.md

**Summary**
Add text requesting issue filers to test Accessibility issues upstream with axe first 
It will reduce people submitting Lighthouse Accessibility issues that are actually belong upstream with axe. 
https://github.com/GoogleChrome/lighthouse/issues/6737

misc(github): ask people to test a11y issues upstream first

---

lighthouse-core/lib/dependency-graph/base-node.js

In LR we collect and report all our errors. This one causes our metrics to get a little funky since it changes every time.
Does this work for you, @patrickhulce.
Also i imagine you want a few URLs that can reproduce this?
b/120845363

core(lantern): drop node id from error message

---

lighthouse-core/gather/driver.js

**Summary**
As of #6347 driver's `sendCommand` can reject its Promise if the underlying protocol command times out.  This new rejection path isn't handled in some invocations of sendCommand leading to unhandled promise rejections.  This would present as us "missing" a PROTOCOL_TIMEOUT in LR, leading to the graceful resolve fix push; however, upon investigation, the cause of missing those timeouts was the timeouts causing an unhandled promise rejection which freaks out LR!  
This should catch all unhandled promise rejections as of right now.  I did a lot of testing to try to track down unhandled promise rejection, but I might have missed some, so if you find any lmk.
- makes #6671 irrelevant
- #6336 doesn't fix this, but it does help LR's story and removes the need …

core(driver): handle promise rejections from sendCommand

---

lighthouse-core/audits/font-display.js
lighthouse-core/test/audits/font-display-test.js

**Summary**
Font URLs were incorrectly being resolved relative to the document instead of relative to the stylesheet they were in. This wasn't really caught since so many are declared absolutely or the stylesheet is in the same directory, so it didn't matter.
I've added a test and fallback scenario for this that preserves the current behavior if we don't have stylesheet information (inline sheets for example). 
fixes #6781

core(fonts): resolve URLs relative to stylesheet

---

lighthouse-core/computed/page-dependency-graph.js
lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/lib/network-request.js
lighthouse-core/test/computed/page-dependency-graph-test.js
lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js
lighthouse-core/test/lib/network-recorder-test.js

**Summary**
In LR, the `timing` object can be defined but have no valid data (`requestTime: 0, receiveHeadersEnd: -1`). This was unexpected and was causing problems later on down the chain for lantern. 
Masking the problem was the fact that the `rootNode` of the lantern graph was trying to pick the earliest network request but was breaking ties by choosing the *last* network record in the array. When the requestTimes were `0`, it just ended up picking the last one and losing the real root node. This PR also adds some sanity checks around that to make sure we'd fail earlier about those unexpected cases.
fixes #6378

core: handle invalid network timing data

---

lighthouse-core/lib/i18n/en-US.json
lighthouse-core/lib/lh-error.js
lighthouse-core/runner.js
lighthouse-core/test/results/sample_v2.json
lighthouse-core/test/runner-test.js
proto/sample_v2_round_trip.json

**Summary**
Audit errors were adding the message code to the end of the errorMessage with parens which was destroying the ICU replacement.  This adds `defaultProperties` to easier facilitate mutliple LHErrors using the same UIString to replace and use their own defaults that are constant per error.
fixes: #6804

i18n: localize audit error strings

---

lighthouse-core/audits/load-fast-enough-for-pwa.js
lighthouse-core/audits/seo/font-size.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/lib/i18n/i18n.js
lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js
lighthouse-core/test/audits/seo/font-size-test.js
lighthouse-core/test/lib/i18n/i18n-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json
types/audit.d.ts

**Summary**
Convert displayValue to be a `string` value only instead of `[string, <string | number> ]` for consistency.  Also converted the only 2 audits that still use the old displayValue array format.
- font-size
- load-fast-enough-for-pwa
fixes: #6200

core(displayvalue): change displayValue to be string only

---

clients/extension/scripts/extension-entry.js

No change in behavior.
I noticed that this function was typed to return a runner result, but it never does. It would be useful for #6831 if it actually did.

extension: return runnerResult

---

lighthouse-cli/test/fixtures/perf/level-2.js
lighthouse-cli/test/fixtures/perf/preload_tester.js
lighthouse-cli/test/fixtures/preload.html
lighthouse-cli/test/smokehouse/perf/expectations.js
lighthouse-core/audits/uses-rel-preload.js
lighthouse-core/lib/i18n/en-US.json

**Summary**
We are ignoring URLs to suggest based on what URLs were ever preloaded. This can lead to silent failures where there was a preload request but it wasn't used so the request was reissued. This adds a warning a-la #6694 
ref #6417

core(preload): warn when duplicate requests issued

---

lighthouse-core/config/default-config.js
lighthouse-core/test/results/sample_v2.json

**Summary**
Move PWA section to the end of the report to match its order on the top level score gauges.
half fix for #6837

core(config): reorder categories to match new gauge order

---

lighthouse-cli/test/smokehouse/smokehouse.js

`errorCode` wasn't being asserted for smoke tests. with this code, it will be. fin.
only effects the `errors` smoke tests

tests(smoke): assert errorCode in expectations

---

docs/scoring.md

**Summary**
`consistently interactive` -> `time to interactive`

docs: Update reference of tti

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html

Transition from full width to >500px
minimum width without horizontal scroll (400px):
minimum width without horizontal scroll (1 category):
fixes #6645

report: support narrow screens

---

lighthouse-cli/test/fixtures/static-server.js
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/lib/url-shim.js

Originally added to `url-shim` back in #3941 (pre Node 8 minimum) when we needed the `whatwg-url` lib for it.
Noticed this while reviewing #6874, which had a fix for the type of `URLSearchParams` to unconfuse tsc about our browser/node union. However, #4712 dropped the `whatwg-url` require, and we only ever use `URLSearchParams` on the Node side anyways, so might as well require it locally instead of adding complexity to fix the complexity we don't use :)

tests(smokehouse): use native node URLSearchParams

---

lighthouse-core/lib/dependency-graph/simulator/connection-pool.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js

**Summary**
while investigating #6893 I noticed there was a crazy amount of time spent in graph simulation due to the 1200+ network requests they fire. Turns out most of this was just spent on just 2 `.sort` calls. One of which we don't even need sort, it's just a `max` and the other can be easily solved by maintaining an extra copy of the nodes that's sorted.
It shouldn't impact accuracy either.
**This reduced total auditing time from 17.2 s to 7.8 s**
#6893

core(lantern): remove unnecessary sort calls

---

docs/understanding-results.md
lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/audits/audit.js
lighthouse-core/lib/proto-preprocessor.js
lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/pwa-category-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/audits/audit-test.js
lighthouse-core/test/lib/proto-preprocessor-test.js
lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/report/html/renderer/report-renderer-test.js
lighthouse-core/test/report/html/renderer/util-test.js
lighthouse-core/test/results/sample_v2.json
lighthouse-core/test/scoring-test.js
proto/lighthouse-result.proto
proto/sample_v2_round_trip.json
types/audit.d.ts
types/lhr-lite.d.ts

**Summary**
Change not-applicable to notApplicable.  This will allow the LHR and protoLHR to use to same value instead of converting it in preprocessing.
Unfortunately since we can't ignore old LHRs that use 'not-applicable' or 'not_applicable' the processors, proto, and renderer need to accommodate those values.
fixes: #6201

core: change 'not-applicable' to 'notApplicable'

---

lighthouse-core/config/config.js
lighthouse-core/runner.js
lighthouse-core/test/config/config-test.js

Some superficial clean up within Config (split off from the plugins PR to keep it simpler).
- `configPath` was really confusing for resolving relative paths of audits and gatherers until I realized it was actually `configDir` that was being passed into these methods. Renamed to that.
- `resolvePlugin()` renamed to `resolveModule` since it's used to find the paths of gatherers, audits, and (soon) plugins. Also moved to `Config` (from `Runner`) since it's only used in there.
- `getDisplayString` was renamed to `getPrintString` in the original PR (#6107) but the test description wasn't updated. Updated.

misc: clean up local names within Config

---

.appveyor.yml
lighthouse-cli/test/fixtures/delayed-fcp.html
lighthouse-cli/test/smokehouse/run-smoke.js
lighthouse-cli/test/smokehouse/tricky-metrics/expectations.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js

**Summary**
We don't actually wait for an FCP, and it seems like we should. There could be a lot more to this story of making our `waitForFullyLoaded` match TTI conditions as close as possible, but this is a good start.
**Fully Loaded Conditions After This PR**
```
all [load, FCP, network quiet] --> CPU quiet --> done
```
**Potential Easy Alternative**
```
all [FCP, load] --> network quiet --> CPU quiet --> done
```
**Real TTI Conditions**
```
FCP --> simultaneous network + CPU quiet --> done
```
closes #6941

core(driver): waitForFCP when tracing

---

lighthouse-cli/cli-flags.js
lighthouse-core/lib/emulation.js
lighthouse-core/test/fixtures/artifacts/perflog/artifacts.json
lighthouse-core/test/results/artifacts/artifacts.json
lighthouse-core/test/runner-test.js
readme.md

**Summary**
I'll bite and try to adjust this.  I just changed the emulation heights to 660.  I wasn't sure if `height` should be 732 and then `screenHeight` should be 660 or the other way around?  [Docs](https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-setDeviceMetricsOverride) didn't explain which was which, so I just made them both 660 for now.
When changing the emulated device in the frontend it only sends a screenWidth and screenHeight with width & height set to 0:
Note the 660 is derived on the frontend from: 732px - 24px (top bar) - 48px (bottom bar) = 660px
fixes: #6615

misc(emulation): Use Nexus 5X emulation real screen size

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/pwa-category-renderer.js
lighthouse-core/report/html/templates.html

works on top of #6930
@paulirish this is how far I think the simplification can go.
Gets rid of all `expandable` true/false business, groups and clumps that are `<divs>` and others that are `<details>`, etc. Clumps still use the group class names, but no longer use `renderAuditGroup` to make themselves.

report: clean up more clump/group/expandable crossover noise

---

lighthouse-core/lib/traces/pwmetrics-events.js

My brain was tired yesterday afternoon so I did some non-essential zen type checking on one of the few remaining `// @ts-nocheck` files (only four more after this :).
This file is only ever called from `asset-saver.js` and the interface remains unchanged. Removed some of the defensiveness that was needed before #5101 made the `metrics.js` output flat and more dependable (that's what the TODO was referencing).

core(tsc): add type checking to pwmetrics-events

---

readme.md

**Summary**
Add [Speedrank](https://speedrank.app) to the list of integrations in alphabetical order.
Speedrank monitors the performance of your website in the background. It displays Lighthouse reports in time and delivers recommendations for improvement. Speedrank is a paid product with 14-day-trial.

docs(readme): add Speedrank to the list of integrations

---

lighthouse-core/test/report/html/renderer/category-renderer-test.js

This was an old test we made the test runner skip because of changing architecture at one point, but it turns out we don't really have another test of the grouping of failing audits, which is kind of important. This restores the test :)
TMI:
I mentioned it in https://github.com/GoogleChrome/lighthouse/issues/5327#issuecomment-429466664, linked to making sure audits with warnings are shown; which is kind of weird given the test contents. I *think* the connection (in my head?) was that we previously marked audits with warnings as failures to make sure they showed up by default, but that all changed when we added groups for all categories in #4278. 
However [the conversation at the time](https://github.com/GoogleChrome/lighthouse/issues/4093#issuecomment-358491941) was about the "X failed …

report: restore old, disabled failed grouping test

---

lighthouse-core/lib/i18n/en-US.json
lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/results/sample_v2.json
proto/lighthouse-result.proto
proto/sample_v2_round_trip.json

report: New audit clump for audits with warnings (#5327)

---

lighthouse-core/computed/metrics/lantern-metric.js
lighthouse-core/computed/metrics/lantern-speed-index.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/test/computed/metrics/__snapshots__/lantern-speed-index-test.js.snap
lighthouse-core/test/computed/metrics/lantern-speed-index-test.js

**Summary**
This PR makes it possible to scale the lantern coefficients based on the throttling settings. Previously the desktop LR preset was giving *too* pessimistic estimates on Speed Index because of the hardcoded `1.4x` multiplier on the observed speed index.
Key Example Fix (facebook.com)
**Before**
**After**
fixes #6971

core(speedindex): scale coefficients according to throttling

---

build/build-extension.js
changelog.md
lighthouse-viewer/app/src/lighthouse-report-viewer.js

These came up in the process of pushing 4.0.
For the extension, using `archiver.glob` with an absolute path nests the extension directory within a recreation of the absolute path of directories leading up to it within the zip file. Kind of amazing that that still works as an extension, but weird to ship it that way. Switching to `archiver.directory()` allows `dist/extension/` to be the root of the zip file.
The viewer comment changes are just to assure the next release that both 3x and 4x results are handled by the current viewer.
I also updated the changelog with the "Breaking changes" section I added to the 4.0 release notes.

misc: fix extension package path and viewer comments

---

readme.md

Add [DebugBear](https://www.debugbear.com/) to the list of integrations in alphabetical order.
DebugBear is a website monitoring tool based on Lighthouse. See how your scores and metrics changed over time, with a focus on understanding what caused each change. DebugBear is a paid product with a free 30-day trial.

docs(readme): Add DebugBear to the list of integrations

---

lighthouse-core/gather/driver.js

core: use async/await in evaluateAsync

---

lighthouse-cli/test/smokehouse/byte-config.js
lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
lighthouse-core/audits/content-width.js
lighthouse-core/config/config.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/gather/gatherers/link-elements.js
lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/lib/network-recorder.js
lighthouse-core/lib/network-request.js
lighthouse-core/runner.js
lighthouse-core/scripts/assert-golden-lhr-unchanged.sh

**Summary**
Cleans up my TODOs with github issues so they're more visible and easier to prioritize.

misc: replace TODOs with github issue links

---

lighthouse-core/report/html/renderer/report-renderer.js

This was a hotfix applied to the 4.0.0 devtools roll. Now adding here.

core(renderer): do not attempt fireworks for devtools

---

lighthouse-core/gather/gatherers/seo/tap-targets.js

**Summary**
2 lines in tap-targets were being browserified with trailing white space which fails on the LR bundler.  So just remove those lines.

misc(tap-targets): remove lines with trailing whitespace

---

lighthouse-core/audits/metrics/first-contentful-paint-3g.js
lighthouse-core/lib/i18n/en-US.json

**Summary**
Drop the `require.resolve`to find the i18n strings in exchange for an inlined `UIStrings` so that browserify can find them and the audit can be run in Lightrider.

core(fcp-3g): remove unused i18n for LR compatibility

---

lighthouse-core/report/html/templates.html

- `.lh-metadata__results` with text ellipsis needs "overflow:hidden"
This is related the comment.:) thanks: @exterkamp
https://github.com/GoogleChrome/lighthouse/pull/6833#pullrequestreview-186692186

report: audits metadata results style

---

lighthouse-core/audits/seo/tap-targets.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-core/test/audits/seo/tap-targets-test.js
lighthouse-core/test/results/sample_v2.json

i18n for [tap targets audit](https://github.com/GoogleChrome/lighthouse/pull/5846).

i18n: tap targets

---

lighthouse-core/audits/seo/tap-targets.js
lighthouse-core/lib/rect-helpers.js
lighthouse-core/test/lib/rect-helpers-test.js

Optimize the tap-targets audit for pages with a large number of tap targets. Many pages don't hit a problem, but searching for the [longest wikipedia pages](https://en.wikipedia.org/wiki/Special:LongPages) found https://en.wikipedia.org/wiki/List_of_2017_albums, which takes 18s to process in the current audit. That might seem kind of unreasonable as a test, but as we've discovered from some of our axe timeouts, people do indeed make and then test pages with giganto tables of links.
Some results:
**avclub**
before: 87.30 ms
after: 10.80 ms
[**https://github.com/GoogleChrome/lighthouse/pull/5846**](https://github.com/GoogleChrome/lighthouse/pull/5846)
before: 99.22 ms
after: 22.86 ms
**https://en.wikipedia.org/wiki/List_of_2017_albums**
before: 18,772.44 ms
after: 502.01 ms
(numbers updated …

core: optimize tap-targets audit

---

lighthouse-core/audits/audit.js
lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/byte-efficiency/efficient-animated-content.js
lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
lighthouse-core/audits/byte-efficiency/unminified-css.js
lighthouse-core/audits/byte-efficiency/unminified-javascript.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
lighthouse-core/audits/byte-efficiency/uses-text-compression.js
lighthouse-core/audits/byte-efficiency/uses-webp-images.js
lighthouse-core/audits/redirects.js
lighthouse-core/audits/time-to-first-byte.js
lighthouse-core/audits/uses-rel-preconnect.js
lighthouse-core/audits/uses-rel-preload.js
lighthouse-core/report/html/renderer/crc-details-renderer.js
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
types/audit-details.d.ts
types/audit.d.ts
types/lhr-lite.d.ts
types/lhr.d.ts

wading through #6999 makes it clear that our `details` type situation is approaching untenable :)
This starts us off, unifying several top-level details types under `LH.Audit.Details`. There are no functional changes, just types, so this is just describing what we're already doing in a slightly different way (hopefully better).
This is the cleanest set of things I could find to do before starting to need code changes, so we'll build from here :)
Happy to bikeshed on names

core(tsc): begin clean up of audit details types

---

lighthouse-core/computed/network-analysis.js
lighthouse-core/test/computed/network-analysis-test.js

**Summary**
This has no impact on anything other than the new diagnostic audit. In network analysis there could be partial data missing. Before we would set the value as `NaN` and simulator would fallback to using `0`. Instead of letting the consumer fallback, this just explicit falls back so our `maxRtt` doesn't wind up to be `null` in the diagnostic audit.
#7052

core(networkanalysis): set additional RTT to 0 not NaN

---

CONTRIBUTING.md

**Summary**
Fixes spelling mistakes in Contributing.md -
- `mutliple` 🡺 `multiple`
- `expliticly` 🡺 `explicitly`

docs(contributing.md): fix typos

---

docs/variability.md
readme.md

**Summary**
First stage of our war on variance: Basic documentation in our repo. 
Adds a new document discussing sources of variance and links to additional resources.

docs(variability): add dedicated variance doc

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js

core: suppress protocol timeout for app manifest bug in LR

---

lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
types/parse-cache-control/index.d.ts

**Summary**
Fixes the typo in our cache audit that was looking for `must-validate` instead of `must-revalidate`

core(cache-headers): fix typo in must-revalidate

---

lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
lighthouse-core/test/audits/byte-efficiency/unused-css-rules-test.js

**Summary**
Our assumed compression ratio for GZIP was pretty far off for CSS. This updates our compression ratios to be more realistic.
closes #7180

core(byte-efficiency): use more optimistic GZIP ratios

---

lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

v8 sort [became stable in 7.0](https://v8.dev/blog/array-sort), which landed in Node 11.
This isn't a problem in most of our codebase (we've ensured sorting is already stable where we really need it to be), but our `sample_v2.json` diff test relies on the exact order of arrays and includes two audits with `details` table entries that share the same exact attributes except URL query strings. As a result, they sort differently in pre- and post- Node 11, so the diff test is broken in e.g. Node 10 if the file itself was written by Node 11.
Since this doesn't affect results at all--just positioning within tables if the attributes we cared about were already exactly equal--this adds a simple string sort fallback to the two breaking audits. This also seemed like a much simpler solution than …

core: give sort fallback for broken test details in node 11

---

lighthouse-core/audits/font-display.js
lighthouse-core/test/audits/font-display-test.js

**Summary**
One of the reasons people seem to be getting false failures is our semicolon. Thanks to @Diklla for pointing this out!
#6628

core(font-display): more accurately follow CSS spec

---

lighthouse-core/test/gather/gatherers/seo/font-size-test.js

**Summary**
In #7197 I realized I had introduced the only non-volatile snapshot usage into the codebase. @brendankenny I felt bad, so here we go :)

tests: covert only non-volatile snapshot usage

---

.travis.yml

Add latest node to the travis config.
Kept the version rate limiting from before for PRs (not after merge to master), though it would be nice to drop it. Maybe if we switch CI providers :)
related: #7215

tests: run node 11 in CI

---

lighthouse-core/test/gather/driver-test.js

**tl;dr - for EASIER REVIEWING just look at https://github.com/GoogleChrome/lighthouse/pull/7212/commits/877264306c5351120c3a79c69f4e2609a6a62d80**
**Summary**
It's no secret that driver tests have been somewhat of a mess for a long-time. Driver is one of the most critical pieces of Lighthouse logic and yet adding tests has always been intimidating and somewhat unconvincing that things are working. This PR is a first step in an attempt to change that.
**The Changes**
- Organizes all the tests by the method. Already much easier to see where we have coverage and where we're lacking.
- Minor renaming of driverStub -> driver. The driver here is a real driver, its the connection and sendCommand functions that are stubs.
- Moves to a more readable format where each method stubs the …

tests: re-organize driver tests by method

---

lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
It's a bit confusing that the unused CSS is probably dead CSS that's completely unused. We'll save that distinction for the help text and make the title a little more aggressive.
closes #6588

core(unused-css): change title Defer -> Remove

---

lighthouse-cli/test/smokehouse/smokehouse.js

tests(smokehouse): fail on finalUrl/errorCode mismatches

---

lighthouse-core/test/gather/driver-test.js

**Summary**
Phase 2 of 3 of driver-test re-org. This eliminates `sendCommandStubOld` and moves all the tests over to fake timers.
Last step is to replace `createOnceStub` with a similar mock function implementation and flesh out the gotoURL tests
#7212

tests: driver test re-org phase 2

---

readme.md

Add [Fluxguard](https://fluxguard.com) to the list of integrations in alphabetical order.
> Fluxguard provides website DOM change monitoring orchestrated with Google Puppeteer, and audited by Lighthouse. Fluxguard is a freemium product, with monthly monitoring of up to 75 pages for free.

docs(readme): Add Fluxguard to the list of integrations

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-cli/test/fixtures/a11y/a11y_tester.html
lighthouse-cli/test/smokehouse/a11y/expectations.js
lighthouse-core/audits/accessibility/accesskeys.js
lighthouse-core/config/default-config.js
lighthouse-core/gather/gatherers/accessibility.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Improve the categorization of accessibility audits.
- Note: Also enables the `accesskeys` audit which was accidentally turned off in [a previous PR](https://github.com/GoogleChrome/lighthouse/pull/7020/files#diff-427cb962a42ed8d3463f1a773c2f4cc8L9).
fixes #7019

report: reorganize a11y audit groups

---

lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/test/report/html/renderer/details-renderer-test.js
types/audit-details.d.ts
types/audit.d.ts

Uses the new audit details types from #7177 in `DetailsRenderer`, finally deleting all those super old (and confusing) typedefs. Internal functionality is changed, but the generated DOM should be exactly the same.
Majority of the PR is tests because `details-renderer-test.js` was really really light before this :)
Main things were
- finally completing an old TODO to merge `opportunity` and `table` rendering (since they're both really tables). This required a `_getCanonicalizedTableHeadings` method because they have different `heading` formats (which we can hopefully fix next breaking version).
- deleting a bunch of cases from the `DetailsRenderer.render()` switch statement reflecting the [`audit-details.d.ts`](https://github.com/GoogleChrome/lighthouse/blob/c79e3579cbcf214f29680a463be7162e …

report(details-renderer): use new details types

---

lighthouse-core/test/gather/driver-test.js

**Summary**
Final part of driver test reorg. Adds more coverage for gotoURL, the original point of this. Also convinced me that all the logic associated with `gotoURL` should be its own `NavigationManager` or something since this was crazy amount of work for still lots of coverage to go 😆

tests: refactor driver, more gotoURL tests

---

lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/report-ui-features.js

Removes a few leftover `TODO`s and `@ts-ignore`s and removed the middle man on some of the details types being wrapped in an object and then immediately unwrapped again.
With this PR the `LH.Audit.Details` fix process should be finished.

core(tsc): polish switch to new audit-details types
