GoogleChrome/lighthouse

package.json
readme.md

add missing dep and typo in CLI example

make readme example run

---

package.json
test/bigrig_tests.js

Split unit tests into their own npm script.

---

helpers/network-recorder.js

network-recorder: update reference locations

---

extension/README.md

extension readme: deploy instructions

---

extension/app/popup.html
extension/app/scripts.babel/app.js
extension/app/scripts.babel/pwa-check.js

Makes testing async; runs automatically when popup clicked.

---

extension/README.md
extension/app/manifest.json
extension/gulpfile.babel.js
extension/package.json

Extension publishing: gulp tasks copy all critical assets into dist.

---

extension/app/popup.html
extension/gulpfile.babel.js

It's related to https://github.com/yeoman/generator-chrome-extension/issues/158. It worked finely when I tested with this version. how about this approach to copy css?

Update style copy task

---

auditor.js
audits/manifest/background-color.js
audits/manifest/exists.js
audits/manifest/icons-192.js
audits/manifest/icons.js
audits/manifest/name.js
audits/manifest/short-name.js
audits/manifest/start-url.js
audits/manifest/theme-color.js
extension/app/scripts.babel/pwa-check.js
gatherer.js
gatherers/manifest.js
gatherers/url.js
index.js

Fixes Manifest and makes A/G static.

---

extension/app/_locales/en/messages.json
extension/app/manifest.json

Fixes #53. My bad.
PTAL @samccone

Fixes localization error.

---

cli.js
index.js
package.json
readme.md

Starting simple. 
Next flags to add are `--save` and `--debug`

Introduce CLI with flags

---

audits/manifest/background-color.js
package.json
test/audits/manifest/background-color.js

* Fix a loose contract in the audit.
* Add test coverage for the audit.

Background color test sketch 🌽

---

audits/performance/first-meaningful-paint.js
metrics/performance/first-meaningful-paint.js
test/audits/performance/first-meaningful-paint.js
test/audits/performance/trace-10000ms.json
test/audits/performance/trace-1000ms.json
test/audits/performance/trace-3000ms.json
test/audits/performance/trace-500ms.json

Review plz @samccone (I built on your existing PR)

Makes test for FMP; tweaks logic in audit; fixes FMP metric

---

helpers/manifest-parser.js
test/manifest-parser-tests.js

switch manifest-parser tests to use assert

---

audits/security/is-on-https.js
test/audits/manifest/background-color.js
test/audits/manifest/exists.js
test/audits/manifest/icons-192.js
test/audits/manifest/icons.js
test/audits/manifest/name.js
test/audits/manifest/short-name.js
test/audits/manifest/start-url.js
test/audits/manifest/theme-color.js
test/audits/mobile-friendly/viewport.js
test/audits/performance/first-meaningful-paint.js
test/audits/security/is-on-https.js

Adds tests for security and viewport.

---

aggregator.js
aggregators/aggregate.js
aggregators/is-performant/index.js
aggregators/is-secure/index.js
aggregators/will-get-add-to-homescreen-prompt/add-to-homescreen.js
aggregators/will-get-add-to-homescreen-prompt/index.js
aggregators/will-get-add-to-homescreen-prompt/mobile-friendly.js
aggregators/will-get-add-to-homescreen-prompt/works-offline.js
audits/audit.js
audits/manifest/background-color.js
audits/manifest/exists.js
audits/manifest/icons-192.js
audits/manifest/icons.js
audits/manifest/name.js
audits/manifest/short-name.js
audits/manifest/start-url.js
audits/manifest/theme-color.js
audits/mobile-friendly/viewport.js
audits/offline/service-worker.js
audits/performance/first-meaningful-paint.js
audits/security/is-on-https.js
cli.js
extension/app/scripts.babel/pwa-check.js
extension/app/styles/lighthouse.css
index.js
package.json
test/aggregators/aggregate.js
test/aggregators/aggregators.js
test/audits/audits.js

Makes the output more inline with what matters to a user, e.g. 'Will get an Add to Homescreen prompt'
:boom: 
PTAL @paulirish - I think this matches what we discussed. Also note that the `will-get-add-to-homescreen-prompt` is a kind-of "composite aggregation", which should aid testing.

Adds aggregation

---

cli.js
helpers/browser/driver.js
readme.md

changes:
* pretty-print is default for using at cmd line
* `--json` is an option, and we format it a tad.
* `--quiet` to silence all logging

CLI output improvements

---

.travis.yml

> This should resolve the travis CI failure around new syntax :sparkles:

Run travis only on node "node"

---

package.json
readme.md

I think it would be in consistence with other scripts

Using npm script to launch chrome

---

extension/gulpfile.babel.js
gatherers/manifest.js
helpers/browser/driver.js
helpers/extension/driver.js

This also fixes the Chrome extension since it was broken for a bit.

Extension protocol extends default driver.

---

cli.js
cli/printer.js
package.json

* also fix broken npm start script :a: :heavy_plus_sign:

Clean up CLI output and formatter

---

cli.js
package.json

Do not run if node version older than 5.0

---

aggregators/omnibox-is-themed/index.js

just a small docs addition. fixes #25

theme-color: documenting requirements detail

---

readme.md

@brendankenny I just took your last comment in #61 and formatted it a bit.

readme: docs for audit return value

---

extension/app/popup.html
extension/app/styles/lighthouse.css

Adds banner to header.

---

extension/package.json

extension: Add missing dep.

---

.travis.yml

Just a tad more coverage for the extension. 
Would break if the babel, browserify pipeline has a problem.

Travis: confirm the extension can build

---

audits/offline/works-offline.js
gatherers/offline.js
index.js

Add offline gather / audit

---

aggregators/aggregate.js
aggregators/can-load-offline/index.js
aggregators/is-performant/index.js
aggregators/is-secure/index.js
aggregators/is-sized-for-mobile-screen/index.js
aggregators/launches-with-splash-screen/index.js
aggregators/omnibox-is-themed/index.js
aggregators/will-get-add-to-homescreen-prompt/index.js
closure/closure-type-checking.js
closure/typedefs/Aggregation.js
closure/typedefs/Artifacts.js

rebased and last tweaks for #123
Closes #123

Adds closure annotations to aggregators.

---

extension/app/scripts.babel/app.js
extension/app/scripts.babel/background.js
extension/app/scripts.babel/pwa-check.js
extension/gulpfile.babel.js
index.js
runner.js

Extension improvements && centralization efforts.

---

gatherers/manifest.js

+ Fixes erroManifest call when there is no manifest file found

Fix errorManifest call

---

gatherers/service-worker.js

Fixup service worker detection test

---

gatherers/manifest.js

Tested and works on all the sites [here](https://github.com/GoogleChrome/lighthouse/pull/154#issue-146857859)

Make browser get the manifest with xhr

---

helpers/browser/driver.js

This call led to a good 4 hours of debugging on why offline doesn't working.
:cry:

Driver: remove Network.disable()

---

gatherers/offline.js
gatherers/service-worker.js

Fixes #163 :arrow_right: depends on #165
See each commit for details.
-----
:warning: Please **do not** squash when merging, as each of these commits are atomic in nature and squashing will mash together two unrelated things.  :warning:

Service worker test improvements.

---

helpers/browser/driver.js

Don't disconnect on trace retrieval timeout (legacy from code from before driver.js), and keep the trace retrieval more encapsulated in general.
In addition, there was a bug where successful trace retrieval wasn't clearing the timeout, but the bug occurred when another gather took too long and hit the timeout and `disconnect` was called.
---
Fixes
https://github.com/GoogleChrome/lighthouse/issues/172

simplify driver trace logic

---

gatherers/offline.js

a wise man once said not to use fetch

🐨 Migrate to XMLHttpRequest instead of fetch

---

audits/performance/first-meaningful-paint.js
cli.js
closure/third_party/DevtoolsTimelineModel.js
helpers/browser/driver.js
helpers/emulation.js
metrics/performance/first-meaningful-paint.js
test/audits/manifest/short-name-length.js
test/audits/performance/trace-10000ms.json
test/audits/performance/trace-1000ms.json
test/audits/performance/trace-3000ms.json
test/audits/performance/trace-500ms.json

firstMeaningfulPaint metric fixes

---

extension/app/manifest.json

Adds minimum Chrome version; fixes #177

---

helpers/browser/driver.js

Checks the current page history for reload / navigate.

---

helpers/browser/driver.js
helpers/extension/driver.js

Add logging to extension driver.

---

gather-scheduler.js
helpers/browser/driver.js

Restores SW forced update.

---

helpers/browser/driver.js

Fixes #188. @paulirish As discussed.

Makes CRI create a new tab before launch.

---

extension/app/scripts.babel/background.js
gatherers/service-worker.js
helpers/browser/driver.js
helpers/extension/driver.js
helpers/network-recorder.js
runner.js

These are just some things that have been bothering me for a while. Feel free to disagree :)

Minor clean ups

---

audits/manifest/short-name-length.js
audits/performance/first-meaningful-paint.js
extension/app/scripts.babel/background.js
extension/gulpfile.babel.js
extension/package.json

Three small things:
1. Update some wording in the UI
2. Show raw values in the extension UI (theme-color and FMP)
3. disable sourcemaps for extension since they don't work and just makes debugging harder so far.

UI Wording & Raw Values

---

readme.md

seems you managed to nab the "lighthouse" name, so might as well...

GoogleChrome/lighthouse -> lighthouse

---

aggregators/is-sized-for-mobile-screen/index.js
audits/mobile-friendly/display.js
runner.js

Fixed the nit so we can land it. Fixes #208

Finishes up 208

---

.travis.yml
audits/mobile-friendly/display.js
gather-scheduler.js
gatherers/gather.js
gatherers/offline.js
gatherers/service-worker.js
helpers/browser/driver.js
package.json
run-smoke-tests.sh
test/download-chrome.sh
test/fixtures/online-only.html

https://travis-ci.org/GoogleChrome/lighthouse/jobs/122697303#L1114
^ Interesting... looks like we are not picking up the service worker at all ... curious if anyone has insight here... could it be due to the revert of the force update I did? Is something else going on? 
---
Looks like the force update of service worker API changed a bit today
https://travis-ci.org/GoogleChrome/lighthouse/jobs/122689130#L2606
Which is causing the test to fail until I reverted the commit that enabled this behavior

add smoke tests + fix service worker tests

---

cli.js
extension/gulpfile.babel.js
gather-scheduler.js

This one is quick and could be better, but captures the immediate need of looking at this asset.  The more complete effort in #35 with subsume this, surely.
```
lighthouse https://pwa.theodoreb.net/ --save-trace
```
creates a file named: `lh-pwa.theodoreb.net_4-13-2016 3-28-07 PM.trace.json`

--save-trace flag

---

extension/app/scripts.babel/report.js

Going to automerge because this is broken.

Fixes extension report bug.

---

gather-scheduler.js
helpers/browser/driver.js

Removes WAIT_FOR_LOADED from Driver.

---

gather-scheduler.js

fixes #220 
or does it?
P.S. github is terrible at diffs

improve readability of scheduler

---

cli.js
cli/printer.js

also, add back header with tested url to pretty print output
fixes #233

only log printer if not printing to stdout

---

readme.md

Reverts GoogleChrome/lighthouse#205

Revert "GoogleChrome/lighthouse -> lighthouse"

---

test/cli/printer.js

easy fix: read file as utf8
fixes #240

Fix printer test

---

aggregators/is-accessible/index.js
audits/accessibility/aria-valid-attr.js
closure/typedefs/Accessibility.js
gatherers/accessibility.js
package.json
runner.js

Needs brfs for the extension, but I'm waiting on #206 for that.

Adds an a11y check.

---

src/aggregators/is-accessible/index.js
src/audits/accessibility/aria-valid-attr.js
src/gatherers/accessibility.js

Going to do a @paulirish and assume everyone already loves these fixes 👍

Fixes a11y review notes.

---

test/cli/printer.js

Changes printer test.

---

src/scheduler.js

also add about:blank information to reloadPage comment

remove errant whitespace, fix the build

---

extension/gulpfile.js

A leftover from the great folder refactor.

Fix gulp watch

---

.travis.yml

travis: use trusty instead of precise

---

src/gatherers/accessibility.js
src/gatherers/manifest.js
src/lib/drivers/cri.js
src/lib/drivers/driver.js
src/lib/drivers/extension.js

Adds async evaluation to driver.

---

extension/gulpfile.js

Includes pages in build step

---

src/audits/offline/works-offline.js
src/gatherers/offline.js

Fixes #266 - @samccone figured you were super busy with stuff, and I was getting wacky results from the existing test so I thought I'd just get it sorted. Hope that's okay.

Makes offline test use evaluateAsync

---

cli/index.js
module/index.js
package.json
src/module.js

Adds module support.

---

closure/typedefs/AuditResult.js
src/audits/accessibility/aria-valid-attr.js
src/audits/audit.js
src/audits/html/meta-theme-color.js
src/audits/manifest/background-color.js
src/audits/manifest/exists.js
src/audits/manifest/icons-min-144.js
src/audits/manifest/icons-min-192.js
src/audits/manifest/name.js
src/audits/manifest/short-name-length.js
src/audits/manifest/short-name.js
src/audits/manifest/start-url.js
src/audits/manifest/theme-color.js
src/audits/mobile-friendly/display.js
src/audits/mobile-friendly/viewport.js
src/audits/offline/service-worker.js
src/audits/offline/works-offline.js
src/audits/performance/first-meaningful-paint.js
src/audits/performance/speed-index-metric.js
src/audits/security/is-on-https.js

Updates audits to use an object for generateAuditResult

---

module/index.js
src/scheduler.js
test/module/index.js

Small fix to stop obscure input and opening and leaving a tab open.

Module tests

---

cli/index.js
cli/printer.js

* provides the options for the `--output` flag
* ~~introduces `--json` shorthand flag~~

Improve CLI flags output

---

report/scripts/lighthouse-report.js
report/styles/report.css
report/templates/report.html

Adds toggle to report

---

package.json

+ Fix for these files https://www.diffchecker.com/s0oxzqmy

Fix unit test watch npm command

---

src/scheduler.js

Because it wasn't actually working :P

Fixes http redirect test

---

src/gatherers/https.js

Now uses `driver.getSecurityState()`.

Upgrades HTTPS audit

---

report/styles/report.css
report/templates/report.html
src/aggregators/aggregate.js
src/aggregators/best-practices/index.js
src/aggregators/can-load-offline/index.js
src/aggregators/is-performant/index.js

Adds coming soon

---

report/templates/report.html
src/aggregators/best-practices/index.js
src/audits/accessibility/aria-allowed-attr.js
src/audits/accessibility/color-contrast.js
src/audits/accessibility/image-alt.js
src/audits/accessibility/label.js
src/audits/accessibility/tabindex.js
src/lighthouse.js

Adds more a11y audits

---

.eslintignore

*Correct* use of eslintignore :)

---

src/aggregators/is-performant/index.js
src/lighthouse.js

issue for tracking input readiness in #336

disable input readiness audit until correct

---

scripts/launch-chrome.sh

Fixed at #io16 with @paulirish and @samccone 😇

Fixes #311

---

src/audits/performance/first-meaningful-paint.js

Handle existence of multiple frames in the trace (#354)

---

src/audits/accessibility/aria-allowed-attr.js
src/audits/accessibility/aria-valid-attr.js
src/audits/accessibility/color-contrast.js
src/audits/accessibility/image-alt.js
src/audits/accessibility/label.js
src/audits/accessibility/tabindex.js
src/audits/audit.js
src/audits/html/meta-theme-color.js
src/audits/manifest/background-color.js
src/audits/manifest/exists.js
src/audits/manifest/icons-min-144.js
src/audits/manifest/icons-min-192.js
src/audits/manifest/name.js
src/audits/manifest/short-name-length.js
src/audits/manifest/short-name.js
src/audits/manifest/start-url.js
src/audits/manifest/theme-color.js
src/audits/mobile-friendly/display.js
src/audits/mobile-friendly/viewport.js
src/audits/offline/service-worker.js
src/audits/offline/works-offline.js
src/audits/performance/critical-request-chains.js
src/audits/performance/first-meaningful-paint.js
src/audits/performance/input-readiness-metric.js
src/audits/performance/speed-index-metric.js
src/audits/security/is-on-https.js
src/audits/security/redirects-http.js
test/src/audits/audits.js

@brendankenny We should've kept this consistent internally, esp if @paulirish is planning on flattening these to a meta getter.

Changes required artifacts to a getter

---

src/aggregators/aggregate.js
test/src/aggregators/aggregate.js

Aggregator contributesToScore lives a layer up

---

src/lighthouse.js

Log the whitelisted and skipped audits.

---

src/gatherers/accessibility.js
src/gatherers/critical-request-chains.js
src/gatherers/html.js
src/gatherers/viewport.js
test/src/gatherers/accessibility.js
test/src/gatherers/critical-request-chains.js
test/src/gatherers/html.js
test/src/gatherers/viewport.js

This should bring us over 80% coverage.

Yet more tests

---

test/src/audits/performance/first-meaningful-paint.js
test/src/audits/performance/screenshots.js
test/src/audits/performance/speed-index-metric.js
test/src/gatherers/screenshots.js

Add tests for fMP and screenshots.

---

src/lib/asset-saver.js

Adds istanbul ignore to Asset Saver

---

extension/app/manifest.json
formatters/partials/accessibility.html

use details/summary elements for revealing our loud a11y node details

---

report/templates/report.html
src/audits/performance/first-meaningful-paint.js
src/audits/performance/input-readiness-metric.js
src/audits/performance/speed-index-metric.js
test/src/audits/performance/first-meaningful-paint.js

some cleanup of the report as well:

optimalvalues should reflect point of diminishing returns. 

---

closure/typedefs/Artifacts.js
closure/typedefs/ServiceWorkerArtifact.js
src/audits/offline/service-worker.js
src/gatherers/service-worker.js
src/lib/drivers/driver.js
test/src/audits/offline/service-worker.js
test/src/gatherers/service-worker.js

went in to fix a few closure warnings, but `versions` (plural) on the artifact and it being an array of either one or no values drove me a little crazy, so minor fixup to hopefully make it cleaner

simplify service worker gatherer and artifact format

---

lighthouse-core/runner.js

Audit filtering

---

lighthouse-core/lib/asset-saver.js

Fixes prepareAssets

---

lighthouse-cli/index.js
package.json

Moved meow to yargs.
I used variables because it looked better than chaining but perhaps you rather have chaining :)
Should fix #428

Setting up yargs instead of meow

---

lighthouse-core/core.js
lighthouse-core/index.js
lighthouse-core/package.json
lighthouse-core/test/index.js
readme.md

And document the crap out of it

Move module/index.js to the lighthouse-core root

---

lighthouse-core/driver/gatherers/critical-request-chains.js
lighthouse-core/test/driver/gatherers/critical-request-chains.js

We exclude them from our critical req chains

Favicons are not critical resources

---

package.json

Semver CLI dependency fix.

---

lighthouse-cli/scripts/run-smoke-tests.sh
lighthouse-cli/test/fixtures/online-only.html

simplify bash branching for node --harmony

---

readme.md

The text could probably be better.. but it's a starting point.

readme: docs for config & trace-processor usage

---

lighthouse-core/audits/first-meaningful-paint.js
lighthouse-core/audits/time-to-interactive.js
lighthouse-core/config/index.js
lighthouse-core/test/config/index.js
lighthouse-core/test/fixtures/traces/trace-user-timings-no-tracingstartedinpage.json

Traces that are passed in through the config file are cleaned to handle duplicate/missing TracingStartedInPage events.

---

lighthouse-extension/app/popup.html
lighthouse-extension/app/src/lighthouse-background.js
lighthouse-extension/app/src/popup.js
lighthouse-extension/app/styles/lighthouse.css

Need some feedback on this.
Perhaps I need to create a few test for the extension? To check some logic.
See #525 
---
_(paulirish edit): i replaced still image with animated gif. ;)_

Added audit configurations to extension

---

lighthouse-core/gather/gather-runner.js

overwrite loadData only when configured to do so

---

lighthouse-core/runner.js

Mostly to improve logging and attribution of costs.
Before: 
After:

Run audits sequentially.

---

readme.md

README: remove outdated install instructions

---

lighthouse-core/audits/cache-start-url.js

cache start url audit is Alpha

---

lighthouse-core/gather/gatherers/manifest.js
lighthouse-core/test/gather/gatherers/manifest.js

Fixes #295.
PTAL @brendankenny @paulirish

Moves from XHR to DevTools Protocol for manifest retrieval

---

lighthouse-core/scripts/launch-chrome.sh

launch-chrome: inform user about Chrome launch. refactor & cleanup.

---

lighthouse-cli/index.js
readme.md

resolve cli config-path argument relative to cwd

---

readme.md

readme: instructions for lighthouse on mobile devices

---

lighthouse-core/gather/drivers/driver.js

Add netlog to get detailed network activity.

---

.travis.yml
lighthouse-cli/ask.js
lighthouse-cli/chrome-finder.js
lighthouse-cli/chrome-launcher.js
lighthouse-cli/index.js
package.json

#349 
+ ~~Rebased the old branch~~
+ ~~Works only for OSX now~~
--- 
+ flag `--select-chrome` to choose from chrome installation when multiple are found
+ ~~flag `--no-launch-chrome` to disable chrome launch~~
+ flag `--skip-autolaunch` to disable chrome launch

Launch chrome as a part of Lighthouse CLI

---

lighthouse-core/gather/drivers/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/runner.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/lib/drivers/driver-test.js
lighthouse-core/test/runner-test.js

Use clearDataForOrigin instead of forceUpdateServiceWorkers

---

lighthouse-cli/chrome-launcher.js

CLI: waiting for "browser". checkmark => green

---

lighthouse-cli/chrome-launcher.js
lighthouse-cli/index.js

[CLI] Fix SIGINT handling

---

lighthouse-core/report/styles/report.css

R: @brendankenny @paulirish
Fixes:

Fallback font for url heading

---

lighthouse-cli/printer.js
lighthouse-cli/scripts/run-smoke-tests.sh

Before and after:
closeup: 
partially fixes #596

CLI reporter formatting

---

lighthouse-core/test/audits/dobetterweb/appcache-manifest-test.js

R: @brendankenny @GoogleChrome/lighthouse

DWB: audit test for appcache manifest

---

package.json

R: @brendankenny @paulirish
For ease of use:
`npm run dbw http://webdbg.com/test/appcache/` (a site that uses appcache)
`npm run dbw http://html5demos.com/database-rollback` (a site that uses websql)

Add `npm run dbw`

---

lighthouse-core/gather/drivers/driver.js
lighthouse-core/gather/gather-runner.js

Also do a tiny bit of option default refactoring.

Enable passing in a custom pauseAfterLoad option.

---

lighthouse-core/closure/closure-type-checking.js

@ebidel this will fix your closure error in #700

loosen path requirement for closure formatter replacement

---

lighthouse-core/config/dobetterweb.json

Update DBW message

---

lighthouse-core/gather/drivers/cri.js
lighthouse-core/gather/drivers/driver.js
lighthouse-core/lib/network-recorder.js

fixes #627 
It becomes a little convoluted with the three promises, event listeners, and timeouts, but hopefully this makes it so you can at least reason about them. Happy to entertain other ways to organize.

adds idle network condition for driver to consider page loaded

---

lighthouse-cli/index.js
lighthouse-core/lib/network-recorder.js
lighthouse-core/lib/web-inspector.js
package.json

In here's an downstream fix that addresses a ghostrider + lighthouse bug where we werent grabbing screenshots:
https://github.com/GoogleChrome/lighthouse/issues/577#issuecomment-240510686
fixes #577

bump chrome-devtools-frontend module

---

lighthouse-core/gather/gatherers/http-redirect.js
lighthouse-core/test/gather/gatherers/http-redirect-test.js

Started looking into one of the unhandled promise rejections in our unit tests that node is helpfully warning us about now.
Turns out this one was telling us that the http-redirect gatherer was still attempting to change its artifact even after its timeout fired. I rearranged the gatherer and fixed the last two tests, which due to their `.then().catch()` setup won't fail in the face of promise rejection.

handle all promise paths from http redirect gatherer

---

lighthouse-core/gather/gatherers/https.js
lighthouse-core/test/gather/gatherers/https-test.js

similar to #729, catches unhandled rejection if the security state actually returned *after* the timeout in the HTTPS gatherer and caused an error when it did
(also added a test to make sure if security state returns after the timeout but *doesn't* cause an error it can't change the artifact)

handle unhandled rejection in https gatherer

---

lighthouse-core/report/styles/report.css
lighthouse-core/report/templates/report.html

Minor aesthetic PR. :)
Before and after:
and before and after:

HTML Report: tighter vertical whitespace

---

lighthouse-core/audits/dobetterweb/uses-http2.js
lighthouse-core/test/audits/dobetterweb/uses-http2-test.js

R: @brendankenny @paulirish @paullewis

DBW: fix pluralization of "resources"

---

lighthouse-cli/chrome-finder.js

Adding standard Google Chrome support on MacOS

---

lighthouse-extension/app/src/lighthouse-background.js
lighthouse-extension/app/src/popup.js

Reviewers, here is the diff: https://github.com/pavelfeldman/lighthouse/compare/connection_2...pavelfeldman:extension_worker

Make lighthouse-background.js webworker-friendly

---

lighthouse-core/gather/drivers/driver.js

R: @paulirish @samccone @pavelfeldman

Fixes #808

---

.travis.yml

re: #814 
should be an even more in-depth net for regressions. Note that it does add 30-45 more seconds to test time on Travis

run smokehouse PWA tests in CI

---

.eslintignore
.gitignore
lighthouse-cli/ask.ts
lighthouse-cli/bin.ts
lighthouse-cli/chrome-finder.ts
lighthouse-cli/chrome-launcher.ts
lighthouse-cli/commands/list-audits.ts
lighthouse-cli/package.json
lighthouse-cli/printer.ts
lighthouse-cli/tsconfig.json
lighthouse-cli/types/types.ts
readme.md

1. enforce no implicit any
2. add a note about compiling the TS before deving

Improvements around typescript

---

package.json

R: @brendankenny @paulirish @GoogleChrome/lighthouse

DBW: update cli flags

---

lighthouse-cli/index.js

Provide a meaningful error on master precompile.

---

readme.md

Add DBW to readme

---

lighthouse-cli/bin.ts
lighthouse-core/lib/log.js

sparked from the conversation in #879 
R=@shakyshane

handle --quiet as silent

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.js
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-cli/test/smokehouse/dobetterweb/run-tests.sh
package.json

R: @brendankenny  @paulirish @samccone

Add DBW to smoke tests. Fixes #814

---

lighthouse-core/gather/connections/connection.js
lighthouse-core/gather/driver.js

fixes #894 
followup from #861

Ignore DOM.disable error

---

lighthouse-core/audits/without-javascript.js
lighthouse-core/closure/typedefs/Artifacts.js
lighthouse-core/gather/connections/connection.js
lighthouse-core/gather/gatherers/html-without-javascript.js
lighthouse-core/test/audits/without-javascript-test.js
lighthouse-core/test/gather/gatherers/html-without-javascript-test.js

handle error case from htmlwithoutjs gatherer and audit

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.js
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js

Update DBW smoketests

---

lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners.js

Code cleanup

---

lighthouse-core/audits/aria-allowed-attr.js
lighthouse-core/audits/aria-valid-attr.js
lighthouse-core/audits/audit.js
lighthouse-core/audits/color-contrast.js
lighthouse-core/audits/image-alt.js
lighthouse-core/audits/label.js
lighthouse-core/audits/tabindex.js
lighthouse-core/test/audits/aria-valid-attr-test.js

fixes #920 
This PR adds a guard around the violations property on the Accessibility object. 
EDIT: tests failed because I didn't build the lighthouse-cli, all tests pass now 👍

Fixes .find on undefined violations object #920

---

lighthouse-core/config/config.js
lighthouse-extension/app/src/lighthouse-background.js

fixes #921 
There was confusion between an audit's name (`myaudit.meta.name`) and the path name used in the config file. The extension was filtering path names by audit names, which happened to work with the core audits until the DBW tests were added to core. The assertion added in #914 caught this for us.
We now do a proper `Map` lookup from audit path names to audit names, then filter out audits that shouldn't run by name. The other changes are exposing the audit loader on `Config` and  a few other places that touch this code, clarifying the difference between variables representing names vs paths.

properly filter extension audits to run by name

---

lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js

Update event listener audit desc: event listeners are no longer page level

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_partial_a.html
lighthouse-cli/test/fixtures/dobetterweb/dbw_partial_b.html
lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-core/gather/gatherers/dobetterweb/links-blocking-first-paint.js
lighthouse-core/test/gather/gatherers/dobetterweb/links-blocking-first-paint-test.js

Addresses #962
@ebidel @brendankenny

fix: blocking link async and time unit bugs

---

lighthouse-cli/chrome-launcher.ts

give parameter type

---

lighthouse-core/gather/gatherers/dobetterweb/geolocation-on-start.js

catch driver errors in geolocation gatherer

---

lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners.js

fix: correct error value for event listener gatherer

---

lighthouse-core/gather/connections/extension.js
lighthouse-extension/app/src/popup.js

extension: better error message if user attempts to audit the Chrome Web Store

---

lighthouse-core/audits/dobetterweb/geolocation-on-start.js
lighthouse-core/audits/dobetterweb/no-console-time.js
lighthouse-core/audits/dobetterweb/no-datenow.js
lighthouse-core/audits/dobetterweb/no-document-write.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/dobetterweb/console-time-usage.js
lighthouse-core/gather/gatherers/dobetterweb/datenow.js
lighthouse-core/gather/gatherers/dobetterweb/document-write.js
lighthouse-core/gather/gatherers/dobetterweb/geolocation-on-start.js
lighthouse-core/test/audits/dobetterweb/geolocation-on-start-test.js
lighthouse-core/test/audits/dobetterweb/no-console-time-test.js
lighthouse-core/test/audits/dobetterweb/no-datenow-test.js
lighthouse-core/test/audits/dobetterweb/no-document-write-test.js

Fixes #1031. https://github.com/GoogleChrome/lighthouse/issues/941 will keen up the duplication.

Throws error when collectUsage resolves to something other than an array

---

lighthouse-core/audits/manifest-icons-min-144.js
lighthouse-core/audits/manifest-icons-min-192.js
lighthouse-core/test/audits/icons-test.js

Fixes #1040 - makes "manifest found icons..." message displayValues. Happy 🦃 📅 !!!

---

lighthouse-cli/test/fixtures/sample.json
lighthouse-core/audits/dobetterweb/appcache-manifest.js
lighthouse-core/audits/dobetterweb/no-websql.js
lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js
lighthouse-core/test/results/sample.json

DBW - Be consistent with "use"

---

lighthouse-core/report/report-generator.js

R: @brendankenny @patrickhulce @paulirish 
Fixes #1056

Report: deal with unsupported timezones. Fixes #1056

---

lighthouse-core/report/report-generator.js

R: @patrickhulce @brendankenny @paulirish 
Before:
Now:

Fix score coloring. Fixes #1061

---

lighthouse-core/report/report-generator.js

R: all
Double down fix for https://github.com/GoogleChrome/lighthouse/issues/1056

Fixes #1084

---

lighthouse-core/config/default.json

R: all
Open to naming of this new section, but I kind of liked something playful. Fixes #1017.

Report: add fancy stuff suggestions section

---

lighthouse-cli/chrome-finder.ts

Works on ubuntu but need to look into some other distro's

Use desktop files to get to chrome installs

---

lighthouse-viewer/app/index.html
lighthouse-viewer/app/src/lighthouse-report-viewer.js

Viewer: add analytics

---

lighthouse-cli/chrome-launcher.ts

Should fix #1001 so far tmp files get deleted on my windows

Make rimraf async for windows

---

lighthouse-core/report/styles/report.css
lighthouse-core/report/templates/report-template.html
lighthouse-viewer/app/src/lighthouse-report-viewer.js

R: all
BTW, the copy APIs are bizarre!!!!
Fixes https://github.com/GoogleChrome/lighthouse/issues/1125

Viewer: Adds copy to clipboard. Fixes #1125.

---

lighthouse-viewer/app/styles/viewer.css

R: @paulirish 
This fixes some layering issues with the new sticky pos header. Also keeps the butter bar at the top of the page when the report is scrolled.

z-index fixes for position fixed header

---

lighthouse-core/report/styles/report.css

R: all
Greatly reduces the paint flashes when scrolling the report.

Reduce paint work on report scroll

---

lighthouse-core/report/styles/report.css
lighthouse-core/report/templates/report-template.html
lighthouse-viewer/app/index.html
lighthouse-viewer/app/styles/viewer.css

R: all
The meta viewport changes are needed to make responsiveness place nice. Otherwise, the text scales below 1.0 depending on the device width.
Before: 
After: 
Also put some instructions on the viewer as part of making it responsive:

Report: mobile friendly, responsive goodness. Fixes #1107

---

lighthouse-viewer/app/index.html
lighthouse-viewer/gulpfile.js
lighthouse-viewer/package.json

R: @patrickhulce @brendankenny @paulirish 
Part of https://github.com/GoogleChrome/lighthouse/issues/1108

Viewer: concat css

---

.travis.yml
lighthouse-viewer/.eslintrc.js
lighthouse-viewer/gulpfile.js
lighthouse-viewer/package.json
lighthouse-viewer/yarn.lock

R: all
This ignores some unneeded modules from the bundle.

Viewer: ignore some node modules. Slims down bundle.

---

readme.md

README: LH viewer and update screenshot

---

lighthouse-viewer/app/src/lighthouse-report-viewer.js

R: all
Ga event when users drag and drop a new report to view or hit the file input.

Viewer: ga event for drag and drop or file upload new report

---

lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
lighthouse-core/audits/dobetterweb/geolocation-on-start.js
lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js
lighthouse-core/audits/dobetterweb/no-console-time.js
lighthouse-core/audits/dobetterweb/no-datenow.js
lighthouse-core/audits/dobetterweb/no-document-write.js
lighthouse-core/audits/dobetterweb/no-mutation-events.js
lighthouse-core/audits/dobetterweb/no-old-flexbox.js
lighthouse-core/audits/dobetterweb/no-websql.js
lighthouse-core/audits/dobetterweb/notification-on-start.js
lighthouse-core/audits/dobetterweb/script-blocking-first-paint.js
lighthouse-core/audits/dobetterweb/uses-http2.js
lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js

add links to dbw docs

---

lighthouse-core/report/styles/report.css
lighthouse-viewer/app/styles/viewer.css

R: all
I _deeply_ care about printing reports...so I fixed us.
Before:
After:

Better print stylesheet

---

lighthouse-core/report/report-generator.js
lighthouse-core/report/styles/report.css
lighthouse-core/report/templates/report-template.html
lighthouse-core/test/report/report-test.js
lighthouse-viewer/app/src/lighthouse-report-viewer.js

R: @paulirish @brendankenny @patrickhulce 
Consolidates the print button and adds a "export as" dropdown. Fixes #1054.
The regular report will still have the old school print button.

Viewer: export button

---

lighthouse-core/audits/content-width.js
lighthouse-core/audits/critical-request-chains.js
lighthouse-core/audits/estimated-input-latency.js
lighthouse-core/audits/first-meaningful-paint.js
lighthouse-core/audits/is-on-https.js
lighthouse-core/audits/redirects-http.js
lighthouse-core/audits/service-worker.js
lighthouse-core/audits/speed-index-metric.js
lighthouse-core/audits/time-to-interactive.js
lighthouse-core/audits/user-timings.js
lighthouse-core/audits/viewport.js
lighthouse-core/audits/without-javascript.js
lighthouse-core/audits/works-offline.js

Remove noreferrer from links

---

lighthouse-core/audits/dobetterweb/no-console-time.js
lighthouse-core/audits/dobetterweb/no-datenow.js
lighthouse-core/audits/dobetterweb/no-mutation-events.js
lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js
lighthouse-core/lib/url-shim.js
lighthouse-core/test/audits/dobetterweb/no-mutation-events-test.js
lighthouse-core/test/audits/dobetterweb/uses-passive-event-listeners-test.js
lighthouse-core/test/lib/url-shim-test.js

More consistently handles host matching of URLs coming from userland.
Addresses #1331

Fix: More URL failures

---

lighthouse-extension/app/manifest.json
package.json

Uploaded to CWS:
Published to NPM:

bumping to 1.4.0

---

CONTRIBUTING.md

I think this accounts for most of the release tasks.
Made it rather copypasteable, rather than too heavy on prose.
Feel free to edit the PR directly. :)

Add release plan to contribution guide

---

.eslintrc.js
lighthouse-core/test/audits/critical-request-chains-test.js
lighthouse-core/test/lib/style-helpers-test.js

Enable ESLint's indent rule.

---

lighthouse-core/audits/dobetterweb/uses-http2.js
lighthouse-core/test/audits/dobetterweb/uses-http2-test.js

fix(audit): change messaging for uses-h2 audit

---

lighthouse-cli/test/smokehouse/pwa-expectations.js

site currently down, breaking our tests

temporarily disable polymer shop in smokehouse

---

lighthouse-cli/test/smokehouse/pwa-expectations.js

Reverts GoogleChrome/lighthouse#1491

re-enable polymer shop in smokehouse

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/audits/dobetterweb/no-mutation-events.js
lighthouse-core/test/audits/dobetterweb/no-mutation-events-test.js

Move no mutation events audit to table formatter

---

lighthouse-core/audits/unused-css-rules.js
lighthouse-core/test/audits/unused-css-rules-test.js

fix(unused-css-rules): ignore missing stylesheets

---

lighthouse-core/test/lib/url-shim-test.js

followup to #1319
(also correctly nests the `getDisplayName` tests under the `'URL Shim'` tests, so may need to use [`?w=1`](https://github.com/GoogleChrome/lighthouse/pull/1566/files?w=1) to cut down on the diff noise)

add tests for url-shim's equalWithExcludedFragments

---

lighthouse-core/formatters/partials/table.html

R: @ebidel 
fixes #1621
**Before:**
**After:**

fix: table formatter flex direction

---

lighthouse-core/report/styles/report.css
lighthouse-extension/app/styles/lighthouse-loading.css
lighthouse-extension/app/styles/lighthouse.css
lighthouse-viewer/app/styles/viewer.css

* use lowercase hex colors
* use numeric font-weight values
* remove units from zero

Minor CSS consistency changes:

---

lighthouse-cli/test/smokehouse/pwa-expectations.js

R: all
Fixes #1653
I can file a bug to remember to re-enable it.

Temp disable Shop in smoketests

---

lighthouse-core/gather/connections/connection.js
lighthouse-core/gather/devtools-log.js
lighthouse-core/gather/driver.js
lighthouse-core/test/gather/devtools-log-test.js

addresses comments in https://github.com/GoogleChrome/lighthouse/pull/1665#issuecomment-278229228

refactor: devtools log

---

readme.md

`yarn install --dev lighthouse` should be `yarn add --dev lighthouse`

Minor fix for README

---

readme.md

docs: fix readme example

---

lighthouse-core/report/handlebar-helpers.js
lighthouse-core/report/styles/report.css
lighthouse-core/report/templates/report-template.html
lighthouse-core/test/report/handlebar-helpers-test.js

Expand audits when score is not perfect

---

lighthouse-core/audits/deprecations.js

Fixes #1792

---

lighthouse-core/report/styles/report.css

Sup @robdodson 
Also when score is average.

Use ! for aggregation icon when some audits dont pass

---

lighthouse-core/test/audits/byte-efficiency/total-byte-weight-test.js

somehow forgot to add this file with the original PR

test: add test for TotalByteWeight

---

lighthouse-cli/test/smokehouse/pwa-expectations.js

addressing the smokehouse flake that's hitting us on travis

test: Fix chromestatus smokehouse flake.

---

lighthouse-core/report/report-generator.js

fix(ReportGenerator): use formatter for audit partial

---

readme.md

This covers #1102 by adding the suggested links to the readme.

Add related projects section

---

yarn.lock

in #1752 we updated package.json but the yarn lock wasn't updated.
This updates it. :)

upload yarn.lock after precompiled templates PR

---

lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/lib/url-shim.js
lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js
lighthouse-core/test/lib/url-shim-test.js

feat(uses-optimized-images): add support for CORS images

---

lighthouse-cli/ask.ts
lighthouse-cli/chrome-launcher.ts
lighthouse-cli/printer.ts
lighthouse-cli/tsconfig.json

Should `AuditResult` be removed from types as well?

remove unused variables

---

.npmignore

Also, ignores more files and folders like:
* gulp/
* lighthouse-cli/test/
* gulpfile.js
* .editorconfig
* .eslintignore
* .eslintrc.js
* latest.artifacts.log

.npmignore more dev-only things

---

readme.md

Thx to @brendankenny and @patrickhulce

Add doc for testing site with authentication

---

lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
lighthouse-core/config/default.json

fix: disable unused css rules (1.6 branch)

---

lighthouse-cli/test/cli/printer-test.js
lighthouse-core/lib/url-shim.js
lighthouse-core/test/lib/url-shim-test.js

fix(url-shim): do not elide short names with preserveHost

---

lighthouse-cli/types/types.ts

Some small improvements for cli types.
Also we wanna reuse types form LH in pwmetrics and right now we have to extends it -https://github.com/paulirish/pwmetrics/blob/master/types/types.ts#L5-L15,  but I hope there no objections to have it here :)

Improve types for cli

---

lighthouse-core/report/v2/report-generator.js
lighthouse-core/report/v2/report-renderer.js
lighthouse-core/report/v2/report-template.html
lighthouse-core/test/report/v2/report-generator-test.js

fix: DOM report injection loopholes

---

lighthouse-core/report/v2/report-generator.js

this code will probably die soon but anyway this helped me. :)

better names for scores.

---

lighthouse-core/lib/url-shim.js
lighthouse-core/test/lib/url-shim-test.js

fix: do not throw when checking URL equality

---

package.json

We have a lot of different file extensions now :)

feat: add npm run clean

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/runner.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js

Capturing userAgent string which includes browser version & OS info.
Fixes https://github.com/GoogleChrome/lighthouse/issues/1927

Add user agent to lighthouse report

---

lighthouse-core/report/v2/renderer/details-renderer.js
lighthouse-core/report/v2/renderer/report-renderer.js
lighthouse-core/report/v2/report-styles.css
lighthouse-core/report/v2/templates.html
lighthouse-core/test/report/v2/renderer/details-renderer-test.js
lighthouse-core/test/report/v2/renderer/dom-test.js
lighthouse-core/test/report/v2/renderer/report-renderer-test.js

broken out from https://github.com/GoogleChrome/lighthouse/pull/1997#discussion_r111293896
gotta be kind to those 🖐

report. classnames go 'lighthouse-' to 'lh-'

---

lighthouse-core/test/report/v2/renderer/report-renderer-test.js

fix failing tests. 
followup from #1997

tests: followup fix for passingfailed

---

lighthouse-core/scripts/roll-to-devtools.sh
package.json

small helper script.. really only useful for me.

add script to roll LH to devtools.

---

lighthouse-core/report/v2/renderer/report-renderer.js
lighthouse-core/test/report/v2/renderer/report-renderer-test.js

Skip the passing-audit section if none passed.

---

lighthouse-core/test/gather/computed/speedline-test.js
package.json
yarn.lock

get all the goodness of https://github.com/pmdartus/speedline/pull/42

fix: bump speedline to fix perceptual speed index

---

lighthouse-core/report/v2/renderer/category-renderer.js
lighthouse-core/report/v2/renderer/report-renderer.js
lighthouse-core/report/v2/report-styles.css
lighthouse-core/test/report/v2/renderer/category-renderer-test.js

Report v2: add back debugString

---

lighthouse-core/audits/webapp-install-banner.js
lighthouse-core/config/default.json
lighthouse-core/test/results/sample.json
lighthouse-core/test/results/sample_v2.json

This fixes https://github.com/GoogleChrome/lighthouse/issues/2035

Update outdated link for "Web App Install Banners" article #2035

---

lighthouse-core/report/v2/report-styles.css
lighthouse-core/report/v2/report-template.html

R: @paulirish 
Fixes https://github.com/GoogleChrome/lighthouse/issues/2075

Scope styles to prevent collisions with Devtools UI

---

lighthouse-core/report/v2/report-styles.css

quick fix for the strange numbers running down the side :)

fix: increase text-indent for score

---

lighthouse-core/scripts/compile-against-devtools.sh
lighthouse-core/scripts/roll-to-devtools.sh
package.json
readme.md

Add script to compile renderer against TOT devtools frontend

---

.travis.yml

Output:
* https://travis-ci.org/GoogleChrome/lighthouse/jobs/227773873#L606
* https://travis-ci.org/GoogleChrome/lighthouse/jobs/227773872#L607

Travis: assert renderer can compile against devtools

---

lighthouse-core/scripts/restart-travis-builds.rb

Return of the build timeout script, but for our screenshot failures, too.
Usage instructions are in the file.
```sh
❯ ruby lighthouse-core/scripts/restart-travis-builds.rb
Logged in travis id: paulirish
😱  Build 6881 errored 38 minutes ago. Looking at jobs...
👺  Job 6881.2 failed because of screenshots
Restarting job 6881.2
😱  Build 6877 errored 16 hours ago. Looking at jobs...
😱  Build 6870 errored 16 hours ago. Looking at jobs...
👺  Job 6870.1 failed because of screenshots
Restarting job 6870.1
👺  Job 6870.2 failed because of screenshots
Restarting job 6870.2
😱  Build 6868 errored 16 hours ago. Looking at jobs...
😱  Build 6865 errored 16 hours ago. Looking at jobs...
👺  Job 6865.2 failed because of screenshots
```

Travis: restart builds on travis that failed due to screenshots.

---

lighthouse-core/report/v2/renderer/category-renderer.js
lighthouse-core/report/v2/report-styles.css
lighthouse-core/report/v2/templates.html
lighthouse-core/test/report/v2/renderer/report-renderer-test.js

since the devtools folks will be picking up next week figured I'd throw up what I had locally before they start. it wasn't a ton of work lost if we just close this

feat: new audit styles

---

lighthouse-core/report/v2/templates.html

Make sure export button is on screen for smaller viewports

---

lighthouse-core/report/v2/renderer/category-renderer.js
lighthouse-core/test/report/v2/renderer/category-renderer-test.js

fixes #2169 
we kind of want to be intentionally vague here since we don't guarantee anything in particular improves by that amount. I'll also be moving through here in a bit to address the other component of that issue by splitting these into "definitely do" and moving the more aggresive/opinionated ones into "Diagnostics"

report: add tooltips to sparklines

---

lighthouse-core/report/v2/renderer/category-renderer.js

cf. https://github.com/GoogleChrome/lighthouse/pull/2140#discussion_r115093860

refactor: render audits outside of renderAuditGroup

---

lighthouse-cli/index.js
lighthouse-core/config/default.js

As it says on the tin
cc #2192
---
also including a driveby fix for this:

Disable TTFB audit temporarily for stability.

---

lighthouse-core/report/v2/renderer/category-renderer.js
lighthouse-core/test/report/v2/renderer/category-renderer-test.js

Fixes https://github.com/GoogleChrome/lighthouse/issues/2193

fix: render perf hint debugString

---

lighthouse-core/gather/computed/critical-request-chains.js

test: make travis green again

---

lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js

prevent failures like: https://travis-ci.org/GoogleChrome/lighthouse/jobs/230550942

test: disable byte efficiency score assertions

---

lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/test/audits/time-to-firstbyte-test.js
lighthouse-core/test/config/config-test.js
lighthouse-core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js

followup to https://github.com/GoogleChrome/lighthouse/pull/2160#discussion_r115565739
also fixes some failing tests introduced by #2160 and TTFB

followup: makes tests pass

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js

test: re-enable blocking links smoke test

---

lighthouse-core/audits/user-timings.js
lighthouse-core/test/audits/user-timing-test.js
lighthouse-core/test/runner-test.js

feat(report): add user timings table

---

plots/index.html
plots/metrics-per-site.html

Plots: add topnav to result pages

---

readme.md

Also removes calc'ing overall score based on old aggregations.

README: fix launched chrome example

---

lighthouse-core/audits/dobetterweb/no-mutation-events.js
lighthouse-core/report/v2/report-styles.css
lighthouse-core/test/audits/dobetterweb/no-mutation-events-test.js

Think this is the last one left.

Add details to mutation events audit

---

lighthouse-core/audits/load-fast-enough-for-pwa.js
lighthouse-core/lib/url-shim.js
lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js
lighthouse-core/test/lib/url-shim-test.js

closes #2267 
This doesn't actually seem as critical now due to #2238, but confirmed this fixes the issue for https://shop.polymer-project.org/ from master before #2238

fix: reduce flakiness of LoadFast4Pwa

---

lighthouse-core/report/v2/renderer/category-renderer.js
lighthouse-core/report/v2/renderer/report-ui-features.js
lighthouse-core/report/v2/report-styles.css
lighthouse-core/test/report/v2/renderer/category-renderer-test.js

easier to support devtools and narrowness as class-based instead of media queries
cc @paulirish

fix: various styling fixes for devtools and narrow

---

plots/measure.js

#2246 left this out. #2183 already has this fix, but we may not review it until next week.

give port to plots for new chromelauncher

---

lighthouse-core/audits/load-fast-enough-for-pwa.js

fix(loadfast4pwa): ignore requests with startTime < issueTime

---

lighthouse-extension/app/manifest.json
package.json

Eric and Brendan are doing their right _right now_. So how about we do it.
we do it live.  :D 
WDYT??!?!?

Tag and ship Lighthouse 2.0

---

lighthouse-core/audits/consistently-interactive.js
lighthouse-core/audits/estimated-input-latency.js
lighthouse-core/audits/first-interactive.js
lighthouse-core/audits/first-meaningful-paint.js
lighthouse-core/report/v2/renderer/category-renderer.js
lighthouse-core/report/v2/renderer/util.js
lighthouse-core/test/audits/consistently-interactive-test.js
lighthouse-core/test/audits/estimated-input-latency-test.js
lighthouse-core/test/audits/first-meaningful-paint-test.js

polish: consistent metric display values

---

.travis.yml

Addresses #2224 
Total run time seems slower, but it is containerized /shrug Up to you guys

Switch to containerized Trusty

---

package.json

revise package.json script to the correct folder

---

lighthouse-core/audits/manifest-short-name-length.js

found via https://codecov.io/gh/GoogleChrome/lighthouse/tree/75a861bf04339faad5bdbbf860577640972e55c4/lighthouse-core/audits
and mentioned by brendan back here https://github.com/GoogleChrome/lighthouse/pull/1847#discussion_r108309561

chore(short-name-length-audit): remove dead code

---

docs/headless-chrome.md
docs/readme.md

Update headless Chrome docs

---

chrome-launcher/package.json
lighthouse-cli/package.json
lighthouse-cli/test/cli/index-test.js
lighthouse-cli/yarn.lock
lighthouse-core/scripts/generate-combined-coverage.sh

Fixes #2546 
The test changes work around an interesting childprocess issue with nyc: https://github.com/istanbuljs/nyc/issues/470

Report coverage from CLI tests

---

readme.md

cc @kuychaco @kevinsawicki -- btw this app is great! Fast too. 
A few people had asked for exactly this, so I'm happy to point them towards lightcrawler. 
Let us know if there's anything we can do to help.
cheers

docs (readme): add lightcrawler to projects

---

docs/headless-chrome.md

Fixes https://github.com/GoogleChrome/lighthouse/issues/2614

docs: headless doc was missing flag

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js

yo dawg @brendankenny I heard you like things in `setupDriver`

fix(driver): move performance observer registration to setupDriver

---

lighthouse-core/gather/gatherers/dobetterweb/domstats.js

fix(domstats): enable DOM domain

---

lighthouse-core/test/report/v2/renderer/format-helpers-test.js

Fixes #2648
patch from @ev1stensberg ! :)

test(format-helpers): TZ independent check

---

.travis.yml
package.json
yarn.lock

fixes #1690
This should be reporting via Commit Status API, too..

add bundlesize to track our build size

---

chrome-launcher/chrome-finder.ts

test(chrome-launcher): fix clang-format error

---

docs/configuration.md
lighthouse-core/config/fast-config.js

fixes https://github.com/GoogleChrome/lighthouse/pull/2702#discussion_r127792548

docs(config): add explanations for gatherers property

---

lighthouse-core/audits/cache-start-url.js
lighthouse-core/audits/service-worker.js
lighthouse-core/audits/webapp-install-banner.js
lighthouse-core/test/audits/service-worker-test.js
lighthouse-core/test/audits/webapp-install-banner-test.js
lighthouse-core/test/gather/gatherers/service-worker-test.js

According to https://github.com/w3c/ServiceWorker/issues/705 it's 'service worker'

Spelling fix

---

lighthouse-core/report/v2/renderer/category-renderer.js
lighthouse-core/report/v2/report-styles.css

fix(report): proper arrow state and consistent capitalization

---

lighthouse-core/gather/gather-runner.js
lighthouse-core/test/gather/gather-runner-test.js

We say "timeout reached" even when no timeout was reached but the page failed for other reasons.
Discovered this when poking around #2784

Refactor error throwing from assertPageLoaded

---

chrome-launcher/LICENSE

add license file to launcher package.

---

package.json
yarn.lock

Lighthouse treats "shrink-to-fit" property in meta-tag "viewport" as invalid

---

lighthouse-core/report/v2/renderer/report-ui-features.js

Close export dropdown when printing

---

chrome-launcher/chrome-finder.ts

This adds support for Chromium on Ubuntu, openSUSE and others

Add support for Chromium on Linux

---

chrome-launcher/changelog.md

docs: add changelog to launcher

---

chrome-launcher/flags.ts

via https://github.com/GoogleChrome/puppeteer/issues/350

launcher: mute any audio

---

lighthouse-core/config/seo.js
lighthouse-core/report/v2/templates.html

Descriptions are still WIP but this just establishes the basic scaffolding of the category. It will reuse as many existing audits as possible and after a design review I'll add new custom SEO audits.
Also makes a small CSS change to center the category labels.

SEO audit category

---

package.json
yarn.lock

**What**:
Upgrading bundlesize to 0.13.2
**Why**:
This update adds a better UI for multiple files: https://github.com/siddharthkp/bundlesize/issues/55#issuecomment-315567994
**How**:
Update version in `package.json` and `yarn.lock`

Upgrade bundlesize to 0.13.2 #285

---

lighthouse-core/config/fast-config.js

fix(fast-mode): config adjustments

---

docs/throttling.md
readme.md

* Explanation of current status of our throttling
* And guide for using better throttling.

Add throttling guide to docs/

---

package.json
yarn.lock

Bump axe to 2.4.0

---

readme.md

The Audits panel was added in Chrome 60: https://developers.google.com/web/updates/2017/05/devtools-release-notes

Lighthouse is in Chrome 60

---

.travis.yml
package.json
yarn.lock

The real fix is a permissions issue documented here: https://github.com/siddharthkp/bundlesize/issues/148
this is some cleanup.
Also removing a 3s sleep since it doesn't appear to be necessary.

re-enable bundlesize reporting

---

CONTRIBUTING.md

Hello I would just like to add a couple words to the description.

fixing some grammatical errors

---

lighthouse-core/gather/computed/main-resource.js

fix(mainResource) typo in variable name

---

lighthouse-core/audits/time-to-first-byte.js

fix(ttfb): remove duplicate ms

---

lighthouse-core/config/default.js

I noticed all of the descriptions are the same so I did a pass to make them more meaningful.

Improve descriptions for a11y audits

---

readme.md

Add [Treo](https://treo.sh/) to the list of integration in alphabetical order.
---
Treo is Lighthouse as a Service. Moving Lighthouse to the cloud it enables new use cases like regression testing and custom locations & networks.
It's a new project and I would be happy to hear a feedback from Lighthouse community.
Special thanks for all Lighthouse contributors and congratulations with v2.5 release!

Add Treo to the list of integrations

---

docs/bug-labels.md

Added documentation around our bug triaging process and bug labels.

docs(bug-labels.md): Create bug-labels.md

---

docs/bug-labels.md

Updating bug labels based on Patrick's feedback.

docs(bug-labels.md): Updating bug labels

---

docs/bug-labels.md

Per label change, updating "good first bug" to "good first issue"

docs(bug-labels): Updating "good first bug"

---

lighthouse-core/audits/load-fast-enough-for-pwa.js

http://www.grammarbook.com/punctuation/semicolons.asp
_Noticed this during the ChromeDevSummit talk this morning._

core: fix minor grammatical error

---

lighthouse-core/audits/image-aspect-ratio.js

report(image-aspect-ratio): fix audit description

---

lighthouse-core/lib/sentry.js

as reported [here](https://github.com/GoogleChrome/lighthouse/pull/3886#issuecomment-347321395) , there's a better way

misc(error-reporting): report unhandled promise rejections, take 2

---

.github/CODEOWNERS

@brendankenny is AFK for a little while, hanging with JGK. 
So this'll remove the reviewer expectation on pending PRs.  
Super happy to revert this whenever ready.

misc(codeowners): represent brendan's leave

---

lighthouse-core/gather/gather-runner.js
lighthouse-core/test/gather/gather-runner-test.js

Fixes https://github.com/GoogleChrome/lighthouse/issues/4018

report(warnings): correct headless chrome UA check

---

lighthouse-core/audits/estimated-input-latency.js

core(estimated-input-latency): remove target reference

---

lighthouse-core/lib/asset-saver.js
lighthouse-extension/app/src/lighthouse-background.js

@paulirish 
Some minor fix for typo and a bug that filterOutArtifacts executes before logAssets.
PTAL.
Thanks!

core(asset-saver): minor fix for logAssets

---

docs/configuration.md
docs/readme.md
lighthouse-core/config/default.js
lighthouse-core/test/fixtures/dbw_tester-perf-results.json
lighthouse-core/test/results/sample_v2.json

fixes #4169 
I also changed a few test fixture files (and some docs). They don't really need to change, but might as well.

report: change 'app' => 'web app'

---

docs/releasing.md

addressing @vinamratasingal's feedback in #4201 
fixes #3579

docs(releasing): update release policy

---

lighthouse-extension/app/styles/lighthouse.css

Fixes: https://github.com/GoogleChrome/lighthouse/issues/4262

extension: Fix scrollbar from showing on Options page

---

lighthouse-core/audits/byte-efficiency/unminified-javascript.js
lighthouse-core/test/audits/byte-efficiency/unminified-javascript-test.js

core(unminified-js): add tolerant option to esprima

---

lighthouse-core/test/audits/viewport-test.js
package.json
yarn.lock

deps: bump metaviewport-parser to 0.2.0

---

.travis.yml

Travis has new features. Much easier to only run specific tasks for a specific branch.
I also disabled the yarn install from the travis script

misc(travis): Run node 6.9.1 as only process for PRs

---

lighthouse-core/gather/connections/extension.js

our previous bugs here have just involved telling people to try again, so let's stop telling people to file one :)

extension: change resolve current tab msg

---

.appveyor.yml

followup to #4370 
The UI screenshot i posted doesnt do anything. [Config is required.](https://help.appveyor.com/discussions/problems/5602-branches-to-build-is-not-working)

misc(appveyor): only run tests against master and PRs

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/http-redirect.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gatherers/http-redirect-test.js

core(http-redirect): drop use of getSecurityState() to gain Android support

---

lighthouse-core/audits/seo/canonical.js

link to rel=canonical reference

---

.github/CODEOWNERS

This reverts commit b72dffefab4e691c528713a08088102b15dc2379.

misc(codeowners): revert brendan's leave

---

lighthouse-core/audits/network-requests.js

PSI folks need resource type too

core(network-requests): add resource type

---

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/predictive-perf.js
lighthouse-core/gather/computed/computed-artifact.js
lighthouse-core/gather/computed/page-dependency-graph.js
lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
lighthouse-core/test/gather/computed/computed-artifact-test.js
lighthouse-core/test/gather/computed/page-dependency-graph-test.js

landing first hopefully non-controversial part of #4676

core(computed-artifact): remove requiredNumberOfArtifacts

---

lighthouse-core/report/v2/renderer/category-renderer.js
lighthouse-core/report/v2/renderer/report-renderer.js
lighthouse-core/report/v2/renderer/util.js
lighthouse-core/test/report/v2/renderer/category-renderer-test.js
lighthouse-core/test/report/v2/renderer/format-helpers-test.js
lighthouse-core/test/report/v2/renderer/performance-category-renderer-test.js
lighthouse-core/test/report/v2/renderer/report-renderer-test.js

some stuff looked a bit wonky after the awesome bonanza of greatness 🐴 🐎 🎉 
before
after

report(scores): make sure scores are represented out of 100

---

lighthouse-core/test/config/config-test.js

tests(config): add expand and merge test

---

lighthouse-extension/package.json
lighthouse-extension/yarn.lock

opens the flood gates for async/await, fixes build error for #4766 😃

deps(browserify): bump browserify for async/await

---

lighthouse-core/lib/emulation.js

overdue. :)
i'm also open to updating the Android version. wdyt?

core(emulation): update Chrome userAgent to 66

---

lighthouse-extension/app/src/popup.js
lighthouse-extension/app/styles/lighthouse.css

extension(popup): log an excerpt of the Gatherer list

---

changelog.md
lighthouse-extension/app/manifest.json
lighthouse-extension/app/src/popup.js
lighthouse-extension/app/styles/lighthouse.css
package.json

this all stays on the `branch2.x` branch

misc: tag 2.9.2 release

---

lighthouse-extension/test/extension-test.js

I brought the pptr extension smoketest back to 2.x branch as it's a nice assurance. But node 6 doesn't like the pretty async await. This was a 10 minute transpile and it looks p decent. 
wdyt?
for 2.x branch only

tests: transpile extension test for node 6

---

lighthouse-core/lib/asset-saver.js
lighthouse-extension/gulpfile.js
lighthouse-extension/package.json
lighthouse-extension/yarn.lock
package.json
yarn.lock

fixes #4952 (turns out babel also needed to be updated)

extension(compilation): add object rest/spread support

---

lighthouse-core/gather/computed/critical-request-chains.js
lighthouse-core/test/gather/computed/critical-request-chains-test.js
lighthouse-core/test/results/sample_v2.json

Fixes #4702 by removing preloaded assets from Critical Request Chains.

core(critical-request-chains): remove preloaded assets from crc

---

lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/report/v2/renderer/util.js
lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
lighthouse-core/test/report/v2/renderer/util-test.js
lighthouse-core/test/results/sample_v2.json

noticed the displays strings broken while looking at #5009

report(util): fix formatDuration, add tests

---

readme.md

docs(readme): Bye Bye Greta

---

lighthouse-core/report/html/renderer/report-renderer.js

repro
lighthouse --only-categories=pwa http://caltrainschedule.io -GA

report: only appendScoreScale to scoreHeader if it exists

---

package.json

tests: bump bundlesize threshold

---

docs/report.md

protected master branch, @brendankenny.. thanks. <3

docs(report): minor fix of markdown link

---

.appveyor.yml
lighthouse-cli/test/fixtures/tricky-tti.html
lighthouse-cli/test/smokehouse/run-smoke.js

hopefully to avoid too many manual restarts from NO_NAVSTART and PWA

tests(smokehouse): retry failed tests

---

lighthouse-extension/app/popup.html
lighthouse-extension/app/src/lighthouse-ext-background.js
lighthouse-extension/app/src/popup.js
lighthouse-extension/app/styles/lighthouse.css

extension: add checkbox for using Lantern/DevTools throttling

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html

should fix #5167 #5168 
Thanks for reporting @ebidel 💪 !

report(stacking-context): fix stacking contexts of elements in header

---

lighthouse-core/report/v2/renderer/report-renderer.js
lighthouse-viewer/app/src/lighthouse-report-viewer.js
lighthouse-viewer/gulpfile.js

misc(viewer): publish 2.x viewer to /viewer2x on ghpages

---

lighthouse-core/config/plots-config.js

Improves plots-config, fixes #5292

misc(plots): extend default config

---

lighthouse-extension/app/src/popup.js
lighthouse-extension/package.json
lighthouse-extension/test/popup-test.js

**Summary**
The extension is broken by 92728c9725318cffd14a5918b83be084b88661fd when adding type checking.
:white_check_mark: Integration tests added for popup.html
:ambulance: fix popup js errors so it works again

extension(popup): integration test for popup

---

lighthouse-core/gather/computed/main-resource.js
lighthouse-core/test/gather/computed/main-resource-test.js

core(main-resource): work with hash URLs

---

lighthouse-core/runner.js

core: [minor] migrate remaining .description -> .title

---

docs/recipes/custom-audit/custom-config.js
docs/recipes/custom-audit/searchable-audit.js

**Summary**
Update custom-audit example as latest version changed the api so custom-audit is currently broken.

docs(custom-audit): update custom-audit to 3.0.0 api

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md

**Summary**
Less needless text in our templates, thassal.

docs: [minor] issue template tweaks

---

lighthouse-core/audits/byte-efficiency/unused-css-rules.js

LMK if `report:` is the correct commit tag to use...

report: link to our own "unused css" reference doc

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/crc-details-renderer.js
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/renderer/dom.js
lighthouse-core/report/html/renderer/logger.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/report-template.html
lighthouse-core/report/html/templates.html

[skip ci]
Because they asked nicely.

report: adopt 80-char line-length license

---

lighthouse-docker/Dockerfile
lighthouse-docker/headful/Dockerfile
lighthouse-docker/headful/entrypoint.sh
lighthouse-docker/package.json
lighthouse-docker/server.js

Fixes requests from reviewers.
FYI: @ebidel

misc(lighthouse-docker): Fix metadata

---

docs/puppeteer.md

docs(puppeteer): remove appMode

---

lighthouse-docker/docker.package.json
lighthouse-docker/package.json
lighthouse-docker/server.js

Updating the PR #4864 as per reviewers comments.
+ Removing repeated code from server.js
+ separating package.json for the use inside and outside docker container

misc(docker): DRY up server.js, seperate two package.json

---

lighthouse-core/audits/deprecations.js
lighthouse-core/test/results/sample_v2.json

**Summary**
Fix typo in summary re deprecated APIs.

bug: fix grocers apostrophe typo (API's v APIs)

---

lighthouse-core/runner.js

**Summary**
Adds locale to override list in normalized settings, allowing the user to change the locale of the outputted report.
fixes: #6079

core(audit): added locale to override list for normalized settings

---

package.json
yarn.lock

rolls in this fix: https://github.com/GoogleChrome/chrome-launcher/pull/121

deps: chrome-launcher@0.10.5

---

lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-extension/app/src/lighthouse-background.js

1. match score scale order to LS. (green, orange, red)
2. negative margin of metrics is now scaled against circle-size, which is the intent. 
3. expose lh-background methods appropriately in a worker

misc: tweaks for devtools client

---

CONTRIBUTING.md

docs(contributing.md): consistent capitalization

---

yarn.lock

misc: add integrity data to yarn.lock

---

AUTHORS

docs: typo fix

---

yarn.lock

can't explain why this popped up separately. but it did.

misc(yarn): update lockfile for micromatch

---

package.json
yarn.lock

**Summary**
Paul said so 😄 
#6480

deps: update puppeteer to version 1.10.0

---

lighthouse-core/gather/driver.js

core: increase default protocol timeout to 10s

---

lighthouse-core/gather/driver.js

until we research what it really should be.

core: increase protocol timeout to 30s

---

changelog.md
lighthouse-core/test/results/sample_v2.json
package.json
proto/sample_v2_round_trip.json

4.0.0-alpha.1

---

clients/extension/manifest.json

accidentally left out of #6567

misc: bump extension version

---

lighthouse-cli/cli-flags.js

docs: use HTTPS link to bit.ly/chrome-flags

---

readme.md

**Summary**
New users may not be sure which way they should install/run lighthouse. I added some basic info to the README about the different installation options to help users understand the differences.

docs(readme): added simple guidance on install options

---

package.json
yarn.lock

two bug fixes for aria attributes: https://github.com/javan/details-element-polyfill/releases/tag/2.2.0

deps: details-element-polyfill@2.2.0

---

lighthouse-core/report/html/report-styles.css

report(bug): fix margin on score gauge wrappers

---

lighthouse-core/audits/metrics.js
lighthouse-core/test/audits/metrics-test.js

This one's for you @benschwarz

core(metrics): do not fail if TTI fails

---

lighthouse-core/test/audits/seo/canonical-test.js

covers an extra case that @brendankenny and i discussed while reviewing https://github.com/GoogleChrome/lighthouse/pull/6860/files#diff-14d8658f7122f6404900585e27a2466cR33

core(seo): add rel=canonical test for auditing a domain root

---

readme.md

Added a react lighthouse viewer npm module to the related projects list.
**Summary**
Updated Documentation.
Added a useful integration with React.
https://github.com/blencorp/react-lighthouse-viewer/blob/master/README.md

docs: Added a react lighthouse viewer

---

lighthouse-core/gather/gatherers/dobetterweb/appcache.js

misc: fix typo in comment

---

lighthouse-core/lib/emulation.js

potential improvement for cl/235073833
> Just some basic stuff to help improve keeping the UA that LR uses in sync. right now its hardcoded in LR.. but with this we can at least use an import script to keep them in sync.

misc: export UA strings from emulation.js

---

lighthouse-core/audits/load-fast-enough-for-pwa.js
lighthouse-core/audits/seo/canonical.js
lighthouse-core/audits/seo/font-size.js
lighthouse-core/audits/seo/robots-txt.js
lighthouse-core/lib/i18n/en-US.json

**Summary**
Follow up to #6860, which contained some ICU processing errors.  Turns out `[ICU Syntax]` needs to be used more sparingly to be valid 😜

i18n: ICU syntax correction

---

lighthouse-core/audits/metrics/max-potential-fid.js
lighthouse-core/lib/i18n/en-US.json

this description was accidentally referring to EIL.

i18n: fix max potential FID description

---

lighthouse-core/test/runner-test.js
package.json
yarn.lock

**Summary**
Switches our last sinon usages to jest.spyOn, thanks @brendankenny for pointing this out!

tests: switch to jest.spyOn

---

package.json
yarn.lock

stealing from #7418 and @patrickhulce 
🤞🤞

deps: update nyc to latest

---

lighthouse-core/report/html/report-styles.css

Workaround for chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=942097

renderer: fix PWA badge flicker

---

package.json
yarn.lock

misc(chore): remove old dep postinstall-prepare

---

lighthouse-core/audits/font-display.js
lighthouse-core/test/audits/font-display-test.js

**Summary**
It doesn't really make sense to flag these as our concern doesn't really apply. It's also difficult to find where it's included (inspired by #7674)
#7674

core(font-display): ignore data URLs

---

lighthouse-core/computed/main-thread-tasks.js
lighthouse-core/test/computed/main-thread-tasks-test.js

**Summary**
Treats `'B'` events without a corresponding `'E'` as if they ended at the time of trace end.
#7691

core(main-thread-tasks): handle last task not finishing

---

lighthouse-core/lib/i18n/locales/hi.json

**Summary**
Follow up to #7720.

i18n: Hindi for seo and axe

---

lighthouse-core/lib/i18n/locales/hi.json

**Summary**
Automated i18n import.

i18n: minor Hindi corrections

---

proto/lighthouse-result.proto

**Summary**
Adds stack packs to the proto via a new message and a repeated field to the LHR.

misc: added stack pack proto definition

---

readme.md

**Summary**
> What kind of change does this PR introduce?
This simply updates copy to reflect the free product Foo now offers.
- #8035

docs(readme): Foo integration update to reflect new free product

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/config/default-config.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Seems like a good change to sweep in with breaking changes of a major version :)
fixes #8393

core(seo): add image alt to SEO category

---

lighthouse-core/audits/accessibility/listitem.js

Very simple update to comment.
Looks like it was just a copy-paste error.

misc: add correct listitem.js @fileoverview

---

build/build-dt-report-resources.js

awaiting https://chromium-review.googlesource.com/c/chromium/src/+/1584569
Fixes #8525

clients(devtools): remove ascii encoded requirement

---

lighthouse-core/report/html/renderer/report-ui-features.js

report(redesign): smooth scroll on category gauge click

---

lighthouse-core/report/html/templates.html

report(redesign): tweak plugin badge offset

---

lighthouse-core/report/html/renderer/psi.js

**Summary**
The new PSI report needs a score scale passed to it! :smile:

clients(psi): pass score scale to psi

---

lighthouse-core/report/html/report-styles.css

**Summary**
Dark mode seemed a bit high in contrast to me, and made me not really like it.  These are a few nits that make it more _subtle_ and put together to me.

report(redesign): make dark mode details less intense

---

lighthouse-core/lib/i18n/locales/ta.json

**Summary**
Not a moment to early, tamil :india: :sri_lanka: is translated for stack packs, dom size, and SEO groups!

i18n: import tamil translation

---

lighthouse-core/computed/metrics/cumulative-long-queuing-delay.js

**Summary**
I broke master by merging #8956 when I didn't notice #8975 was merged and depended on one of those files.

misc: update tracing-processor require

---

package.json

misc: yarn static-server

---

yarn.lock

fixes some security alert noise

deps: update outdated transitive deps

---

lighthouse-core/lib/url-shim.js

misc: add note about global.URL in node 10

---

lighthouse-core/lib/i18n/locales/es-419.json
lighthouse-core/lib/i18n/locales/fr.json
lighthouse-core/lib/i18n/locales/id.json
lighthouse-core/lib/i18n/locales/zh-TW.json

**Summary**
Minor corrections to 🇪🇸, 🇫🇷, 🇮🇩, and 🇨🇳.

i18n: corrections for es-419, fr, id, zh-TW

---

package.json
yarn.lock

**Summary**
Many thanks to @finom for removing the deprecated package warning! 🎉 
closes #8420

deps: update jsonlint-mod to 1.7.5

---

yarn.lock

these are in deep jest deps, so not really an issue, but it gets the github UI to shut up.
And hey, only one version of `set-value` around now, what a victory :)

deps: update transitive deps

---

readme.md

docs(readme): update link to authenticated docs

---

docs/scoring.md

docs: update scoring calculator link to v5

---

readme.md

**Summary**
This PR adds the [Gradle Lighthouse Plugin](https://github.com/Cognifide/gradle-lighthouse-plugin) to the list of related projects.
The PR also updates the hyphen used for the **Garie** entry to match with the other hyphens used in that list.

docs(related-projects): add the gradle lighthouse plugin

---

readme.md

**Summary**
Documentation update to add [`lighthouse-check-action`](https://github.com/foo-software/lighthouse-check-action) and [`lighthouse-check-orb`](https://circleci.com/orbs/registry/orb/foo-software/lighthouse-check) to the "Related Projects" section of `README.md`.

docs(readme): add Lighthouse Check to related projects

---

lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/audits/dobetterweb/dom-size-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

just following the path we decided immediately after we [found a super beautiful color to paint that shed](https://github.com/GoogleChrome/lighthouse/pull/9690). 😢
fixes #9725 
closes #9690

misc: rewrite dom-size description

---

lighthouse-core/audits/errors-in-console.js

Per https://github.com/GoogleChrome/lighthouse/pull/9480#discussion_r334190722

misc: warn on use of unrecognized audit options

---

lighthouse-core/scripts/i18n/assert-strings-collected.sh

fixes https://github.com/GoogleChrome/lighthouse/pull/9846#issuecomment-542447233
> parse the english strings for markdown links / code snippets, and ensure each language has the same number
- `collect-strings.js`:
- collects all UIStrings and brings them into `en-US.json` (and `en-XL.json`)
- checks all other language files and deletes any strings with replacements that don't match the newly collected strings
https://github.com/GoogleChrome/lighthouse/blob/21c8d2f4f3d0bfc63e22d96bdaac73dad71019fd/lighthouse-core/scripts/i18n/prune-obsolete-lhl-messages.js#L108-L111
- `yarn i18n:checks` runs `collect-strings.js`, then
- fails if the first bullet point above reveals a diff.
This PR asserts the second `collect-strings.js` bullet point by failing if there's a diff anywhere in the `locales/` …

i18n: add localized-file matching replacements check

---

lighthouse-core/scripts/roll-to-devtools.sh

misc: update location for devtools roll script

---

lighthouse-core/scripts/dogfood-lhci.sh

misc(lhci): build-dir => staticDistDir

---

lighthouse-core/scripts/dogfood-lhci.sh

**Summary**
Prevents future breaking changes and publishes from breaking us ala #9951

misc: fix lhci to 0.3.x

---

lighthouse-core/scripts/lantern/collect/collect.js
lighthouse-core/scripts/lantern/collect/common.js
lighthouse-core/scripts/lantern/collect/gcp-create-and-run.sh
lighthouse-core/scripts/lantern/collect/gcp-run.sh
lighthouse-core/scripts/lantern/collect/gcp-setup.sh

**Summary**
A few tweaks along with the GCP collection scripts

patrick's tweaks to lantern collection script

---

readme.md

**Summary**
Adds [auto-lighthouse](https://github.com/TGiles/auto-lighthouse) to the list of related projects. [Lightcrawler](https://github.com/github/lightcrawler) appeared to be unmaintained when I tried to use it. Because of this, I wanted to add my contribution to those looking for a similar tool.
There are no related issues/PRs AFAIK.

docs: add auto-lighthouse entry to 'related projects'

---

readme.md

Updated the Calibre description to describe what it does and how long the trial is.

docs(readme): Updated Calibre description

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-core/audits/is-on-https.js
lighthouse-core/test/audits/is-on-https-test.js

**Summary**
add filesystem to secure schemes, exclude from HTTPS check
fixes: #9996

core(is-on-https): add filesystem to secure schemes

---

lighthouse-core/test/gather/driver-test.js

see https://github.com/GoogleChrome/lighthouse/pull/10123/files/acdb2aeab81ddba0e880d8b187abcecb2171a6fb#r360177474

tests(driver): fix sendCommand timeout tests

---

lighthouse-core/audits/seo/is-crawlable.js
lighthouse-core/test/audits/seo/is-crawlable-test.js

audits(is-crawlable): line number for blocking directive in robots.txt

---

lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
lighthouse-cli/test/smokehouse/test-definitions/mixed-content/mixed-content-expectations.js

tests(smokehouse): mixed-content

---

lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
lighthouse-cli/test/smokehouse/test-definitions/oopif/oopif-expectations.js
lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations-details.js
lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations.js
lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js
lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa3-expectations.js

tests(smokehouse): type all the expectation modules

---

docs/readme.md

**Summary**
Fixes a typo in the documentation readme.

docs: fix typo in docs/readme.md

---

lighthouse-cli/cli-flags.js
lighthouse-cli/run.js
lighthouse-cli/test/cli/bin-test.js
types/externs.d.ts

fixes #3946
no test b/c this is trivial and there didn't seem to be a good way to test `run.js` `getDebuggableChrome`

cli: --chrome-ignore-default-flags

---

docs/authenticated-pages.md
docs/recipes/auth/README.md
docs/recipes/auth/example-lh-auth.js
docs/recipes/integration-test/example-lh-auth.test.js

docs(auth): use --disable-storage-reset for chrome-debug

---

lighthouse-core/scripts/lantern/run-once.js
lighthouse-core/scripts/test-lantern.sh

**Summary**
Prevent build failures on master like https://travis-ci.org/GoogleChrome/lighthouse/builds/635044859#L1591

misc: add predictive perf to lantern test set

---

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/computed/critical-request-chains.js
lighthouse-core/computed/resource-summary.js
lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/lib/network-request.js
package.json
yarn.lock

making these prs smaller: https://github.com/GoogleChrome/lighthouse/pull/10123/ / https://github.com/GoogleChrome/lighthouse/pull/10168

deps(devtools-protocol): upgrade to 0.0.729809

---

lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
lighthouse-core/audits/byte-efficiency/unminified-css.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/computed/unused-css.js
lighthouse-core/test/audits/byte-efficiency/unused-css-rules-test.js
lighthouse-core/test/computed/unused-css-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

core: move unused-css to computed artifact

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/report-styles.css

fix https://github.com/GoogleChrome/lighthouse/issues/9710
before
after

report: align audit warnings

---

package.json

misc: bump bundlesize threshold for LR

---

.github/CODEOWNERS

this also makes sense.  just following suggestions from support. :)
ref #10274 #10265

misc: tweak CODEOWNERS to finish codereview assignment setup 

---

readme.md

readme is a little long so i think a TOC would help.
I started with `command npx markdown-toc readme.md`  but then hand-edited it a lil bit.
but mostly this PR is just a test of the review assignment. 🤞 🤞 🤞

docs(readme): add a table of contents

---

lighthouse-viewer/app/styles/viewer.css

fixes https://github.com/GoogleChrome/lighthouse/issues/10010

viewer(css): adding grayscale & wait cursor while loading

---

lighthouse-core/scripts/legacy-javascript/examine-latest-run.js

**Summary**
Script that made checking up on polyfills much easier.
Example Output
#10303

misc: add script for examining polyfills

---

lighthouse-core/scripts/git3po-rules/pr-assignee.yaml

**Summary**
Turns "requested a review" into "assigned to" + label, I've been running this manually every now and then already :)

misc: add git3po script for PR assignee

---

lighthouse-core/scripts/roll-to-devtools.sh

1. the dt folder moved
2. also i renamed things CL: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2044605

devtools: update roll script to print correct command for tests

---

yarn.lock

changelog: https://github.com/puppeteer/puppeteer/releases/tag/v1.20.0
really this change doesnt matter much but hopefully codereview assignment works now......

deps: pptr to 1.20.0

---

readme.md

**Summary**
Update features and trial period for [PageSpeed Green](https://pagespeed.green/) in Lighthouse Integrations section.
There are no related issues/PRs

docs(readme): update PageSpeed Green in related projects

---

lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/expectations.js
lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/no-throttling-config.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/test/gather/driver-test.js

addressing https://github.com/GoogleChrome/lighthouse/pull/10505#pullrequestreview-382947778

misc: rename ForFCP to ForFcp

---

package.json
yarn.lock

cc: @jburger424 
we should have shipped this version but failed to upgrade to latest before landing the initial PR. this will land w/ 6.0 in CDT.

deps: upgrade publisher ads

---

lighthouse-core/audits/byte-efficiency/efficient-animated-content.js
lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/byte-efficiency/unminified-css.js
lighthouse-core/audits/byte-efficiency/unminified-javascript.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/audits/byte-efficiency/unused-javascript.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
lighthouse-core/audits/byte-efficiency/uses-text-compression.js
lighthouse-core/audits/byte-efficiency/uses-webp-images.js
lighthouse-core/audits/third-party-summary.js
lighthouse-core/lib/i18n/i18n.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

report: specify transfer or resource size for columns

---

docs/performance-budgets.md
readme.md

https://github.com/GoogleChrome/lighthouse/issues/10540

docs: add explainer on performance budgets

---

lighthouse-cli/cli-flags.js

cli: experimental preset

---

readme.md

docs(readme): add seo guard entry to integrations

---

lighthouse-viewer/README.md
lighthouse-viewer/app/src/github-api.js
lighthouse-viewer/app/src/lighthouse-report-viewer.js

Hello,
This PR adds the ability to load Lighthouse Viewer content from a JSON.

report(viewer): add option for loading from JSON

---

readme.md

**Summary**
How on earth was "lighthouse architecture" in our FAQs but these two weren't? 😆 
https://github.com/GoogleChrome/lighthouse/issues/10629
https://github.com/GoogleChrome/lighthouse/issues/10628
and about a billion others I'm tired of answering...

docs(readme): add variability and throttling to FAQ

---

lighthouse-core/report/report-generator.js
lighthouse-core/test/report/report-generator-test.js

**Summary**
Pushing back against CSV as a thing is more work than making it better :)
closes #10654

core(report-generator): add url to CSV output

---

package.json
yarn.lock

deps: upgrade chrome-launcher@0.13.1

---

docs/scoring.md

**Summary**
- As a developer reading through the docs, I found one page to be rough around the edges, and wanted to contribute the tech-writer side of my brain to making it smoother to grok.
- N/A

docs(scoring): update and refine scoring.md

---

lighthouse-core/scripts/lantern/collect/gcp-create-and-run.sh
lighthouse-core/scripts/lantern/collect/gcp-run.sh

1. `--zone` is needed, else gcloud complains
1. `user@instance` is a thing
1. `xvfb-run ...` is simpler

misc(lantern-collect): update gcp scripts

---

docs/scoring.md

awaiting https://github.com/GoogleChrome/web.dev/pull/2574

docs(scoring): drop performance bit and update the rest

---

readme.md

**Summary**
Just a small typo fix in the READ.me

docs(readme): fix small typo

---

lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/computed/critical-request-chains.js

core: assert.strict doesn't work in bundles

---

readme.md

**Summary**
Add [Wattspeed](https://wattspeed.com/) tool to the list of Lighthouse Integrations - Free subcategory.
This addresses #10744

misc: add Wattspeed to the integrations list 

---

lighthouse-core/report/html/report-styles.css

i think it snuck in via #10636

misc: drop trailing whitespace in css

---

.mailmap

mailmap mailmap 🎶 
mailmap mailmap 🎶 
all the commits 🎶
from me and you 🎶
under a single 🎶
name 🎶
_____
`git shortlog -sne` is now (git log and friends are all updated too):
(edit: redacted for email privacy. look at edit history to see)

misc: .mailmap

---

package.json
yarn.lock

two small fixes
https://github.com/GoogleChrome/chrome-launcher/releases/tag/v0.13.2

deps: upgrade chrome-launcher@0.13.2

---

lighthouse-core/test/results/sample_v2.json
third-party/snyk/snapshot.json

Force an update after snyk fixed the upperbounds :)
see: https://github.com/GoogleChrome/lighthouse/pull/10708#discussion_r424240291
thanks @lirantal !

deps(snyk): update snyk snapshot

---

changelog.md

This was drafted by @brendankenny and is preliminary.  
I'm expecting another PR, but wanted to have something in place.

misc(changelog): update for latest version

---

lighthouse-core/scripts/dogfood-lhci.sh

**Summary**
I filed issues on everyones repos to update but our own 😆

deps: update to lhci 0.4.0

---

readme.md

adjusted the sort and taxonomy using my proprietary formula of 11 herbs and spices

docs(readme): update integrations section

---

readme.md

**Summary**
Added PageWatch to the Lighthouse to the integrations section.
N/A

docs(readme):  add PageWatch to the integrations section

---

docs/readme.md
lighthouse-core/scripts/release/test.sh

https://github.com/GoogleChrome/lighthouse/issues/5269#issuecomment-467974452 has a ton of likes, so i thought we should just adopt it as the canonical recipe.

docs(readme): update programmatic usage recipe

---

lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js
lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
lighthouse-core/audits/byte-efficiency/unused-javascript.js
lighthouse-core/test/audits/byte-efficiency/unused-javascript-test.js

The threshold is too low.
Background: https://github.com/ampproject/amphtml/issues/28638

core(unused-javascript): increase threshold to 20KiB

---

.github/workflows/ci.yml

Use `--debug` so log output is printed.
would have helped for #10906

tests(smoke): use --debug in github action

---

lighthouse-core/audits/resource-summary.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json

**Summary**
Updates the "Learn more" link in the budgets audit to avoid a redirect.

report: update link for budgets audit

---

lighthouse-core/audits/byte-efficiency/duplicated-javascript.js
lighthouse-core/audits/byte-efficiency/unused-javascript.js
lighthouse-core/audits/legacy-javascript.js
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/test/report/html/renderer/details-renderer-test.js
types/audit-details.d.ts

misc: rename subHeading to subItemsHeading

---

.travis.yml
package.json
yarn.lock

#10472 hasn't moved, and `bundlesize` continues to randomly fail builds and not be useful, so buh bye.

deps: remove bundlesize

---

lighthouse-core/gather/fetcher.js

Plugs a few more of the holes that were hard to communicate via review.

core(fetcher): plug more fetcher dangling promise leaks

---

types/audit.d.ts

misc: remove last extendedInfo in LH.Audit.Product

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/config/default-config.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XA.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json

**Summary**
This PR fixes #11058 
#11058

core(config): remove typo in a11y tables lists group

---

readme.md

**Summary**
- Edited **readme.md**
- Added new product (Screpy) to the list of integrations

docs(readme): add Screpy to the list of integrations

---

lighthouse-cli/run.js

**Summary**
CLI waits for the timeout before exiting which is annoying :) Thanks to @chosak for chasing this down! 🎉 
| Before | After |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/2301202/88692649-eeb10480-d0c3-11ea-838a-17d745c01807.png) | ![image](https://user-images.githubusercontent.com/2301202/88692594-de008e80-d0c3-11ea-9389-373c6a328fbc.png) |
fixes https://github.com/GoogleChrome/lighthouse/issues/11153

cli: clearTimeout for faster exit

---

lighthouse-core/scripts/cleanup-vuln-snapshot.js
third-party/snyk/snapshot.json

**Summary**
Prevent certain noop changes described in https://github.com/GoogleChrome/lighthouse/pull/11144#discussion_r465713835
#11144

deps(snyk): update script to prune <0.0.0 and update snapshot

---

docs/releasing.md
lighthouse-core/lib/tracehouse/main-thread-tasks.js
lighthouse-core/lib/tracehouse/trace-processor.js
lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js
lighthouse-core/test/report/html/renderer/psi-test.js

simple change, and no meaning was lost.
https://gist.github.com/seanmhanson/fe370c2d8bd2b3228680e38899baf5cc

misc: rephrase comments to be more inclusive

---

lighthouse-core/scripts/gcp-collection/README.md
lighthouse-core/scripts/gcp-collection/fleet-create-directories.js
lighthouse-core/scripts/gcp-collection/fleet-create.sh
lighthouse-core/scripts/gcp-collection/fleet-status.sh
lighthouse-core/scripts/gcp-collection/run.sh

**Summary**
I'll leave this to you @connorjclark to tweak as you wanted, but this is the model that fit well in https://github.com/patrickhulce/dzl-lighthouse/tree/master/cwv/collection

misc: add gcp fleet creation scripts

---

docs/new-audits.md

**Summary**
Codifying up what we discussed previously in https://github.com/GoogleChrome/lighthouse/issues/11266. Feel free to correct any misunderstandings I think I've already had one conversation with @connorjclark where we left with a different understanding of the agreement :)
closes https://github.com/GoogleChrome/lighthouse/issues/11266

docs: add audit naming guide

---

package.json
yarn.lock

Upgrade plugin to latest version.

deps: lighthouse-plugin-publisher-ads@1.2.0

---

readme.md

This PR updates the README.md adding lighthouse based project I'm maintaining.
**[site-audit-seo](https://github.com/viasite/site-audit-seo)** - CLI tool for SEO site audit, crawl site, lighthouse each page. Output to console and tables in csv, xlsx, json, web or Google Drive.
site-audit-seo report demo - https://viasite.github.io/site-audit-seo-viewer/?url=https://site-audit.viasite.ru/reports/blog.popstas.ru-lighthouse.json

docs(readme): add related project: site-audit-seo

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/trace-elements.js
lighthouse-core/test/gather/gatherers/trace-elements-test.js

Fixes https://github.com/GoogleChrome/lighthouse/issues/11297

core(trace-elements): do not break on unresolvable node id

---

lighthouse-core/test/chromium-web-tests/download-depot-tools.sh
lighthouse-core/test/chromium-web-tests/download-devtools.sh
lighthouse-core/test/chromium-web-tests/test-locally.sh
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt

**Summary**
Updates the expectations for a green master after a bad merge and a few fixes to get the scripts working locally.

tests(devtools): script improvements and rebaseline

---

lighthouse-core/test/chromium-web-tests/run-web-tests.sh

#11331 broke the script for PYTHON_PATH.

misc: fix run-web-tests.sh

---

docs/releasing.md

It was 1 day before previously, but that's a tight window to make branch point if something must be fixed.
Adding @adamraine and @Beytoven as release managers.

docs(releasing): align 2 days before branch. update managers

---

build/build-bundle.js
lighthouse-core/config/config-helpers.js

cc @jburger424 
Verified to work in LR.

misc(build): include publisher ads plugin in lightrider bundle

---

docs/variability.md

some revisions I came up with after helping a Googler do this.

docs(variability): expand on lighthouse-ci usage

---

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-core/audits/is-on-https.js
lighthouse-core/test/audits/is-on-https-test.js
lighthouse-core/test/results/sample_v2.json

Fixes https://github.com/GoogleChrome/lighthouse/issues/11076

core(is-on-https): remove <M84 codepaths

---

lighthouse-core/lib/minification-estimator.js
lighthouse-core/test/lib/minification-estimator-test.js

Fixes https://github.com/GoogleChrome/lighthouse/issues/11295

core(minification-estimator): minify nested template literals in JavaScript

---

.gitattributes
lighthouse-core/lib/i18n/locales/ar.json

ref https://medium.com/@clarkbw/managing-generated-files-in-github-1f1989c09dfd

misc: hide locale files by default in PRs

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

IMO this guy deserved it: https://twitter.com/peruvianidol/status/1288839520272683009

report: let fireworks eligibility ignore PWA category

---

yarn.lock

see: https://github.com/GoogleChrome/lighthouse/pull/11441#issuecomment-693699747

deps: update transitive lodash

---

types/audit.d.ts

misc: tweak typescript jsdoc for list format

---

package.json
yarn.lock

**Summary**
Update `third-party-web` to [0.12.2](https://github.com/patrickhulce/third-party-web/releases/tag/v0.12.2).
https://github.com/patrickhulce/third-party-web/issues/88

deps: update third-party-web

---

types/artifacts.d.ts

This shouldn't have been public.

misc: make FormElements not a public artifact

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/config/default-config.js
lighthouse-core/config/experimental-config.js
lighthouse-core/test/results/sample_v2.json
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt

core(large-javascript-libraries): move to experimental

---

.github/workflows/devtools.yml
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-clear-data-warning-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-clear-data-warning.js
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/resources/lighthouse-storage.html

Imports devtools web test for the important data warning.
Devtools change: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2385182
Related https://github.com/GoogleChrome/lighthouse/pull/11438

tests: add devtools test for important data warning

---

lighthouse-core/lib/dependency-graph/base-node.js

ref https://github.com/GoogleChrome/lighthouse/pull/11612#issuecomment-723363238

core(lantern): traverse generator method

---

lighthouse-viewer/app/src/lighthouse-report-viewer.js

feature idea from @connorjclark

clients(viewer): extract the LHR from PSI json

---

package.json
yarn.lock

fixes #11673
bumps @wardpeet's brfs+transform fork with https://github.com/wardpeet/brfs/pull/1

deps: update brfs to fix build in node 15

---

readme.md

**Summary**
> What kind of change does this PR introduce?
Add integration for: [Apdex](https://apdex.co)
Apdex uses Lighthouse for website performance monitoring.
Thank you!

docs(readme): Apdex integration

---

lighthouse-core/scripts/print-contributors.js
lighthouse-core/scripts/release/prepare-commit.sh

misc(release): print-contributors.js script

---

lighthouse-core/config/config.js

I think this should have been in #11366
Tested by building the bundle in lightrider before and after this change.

misc(build): fix bundling publisher ads plugin in Lightrider

---

lighthouse-core/audits/full-page-screenshot.js
lighthouse-core/gather/gatherers/full-page-screenshot.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/test/test-utils.js
types/audit-details.d.ts

Based off feedback from @brendankenny in #11536

core(full-page-screenshot): simplify details shape

---

lighthouse-core/gather/gather-runner.js
lighthouse-core/test/gather/gather-runner-test.js

Precursor to #11745
https://github.com/GoogleChrome/lighthouse/pull/11745#discussion_r537794950

core(gather-runner): remove <M82 compat for InstallabilityErrors

---

lighthouse-core/test/chromium-web-tests/download-devtools.sh

tests: clear changes in tmp devtools checkout

---

lighthouse-core/audits/dobetterweb/uses-http2.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json

core(uses-http2): remove mention of push

---

lighthouse-core/scripts/gcp-collection/fleet-status.sh
lighthouse-core/scripts/gcp-collection/run.sh

**Summary**
Minor improvement to GCP collection scripts for log-based analysis.
Used for https://github.com/GoogleChrome/lighthouse/issues/11814.

misc: add log files to GCP run results

---

package.json

accidentally changed this in https://github.com/GoogleChrome/lighthouse/pull/11770/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R42

tests: revert mistaken change to yarn unit-core

---

lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics/expectations.js
lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
lighthouse-cli/test/smokehouse/test-definitions/screenshot/expectations.js

helping @jazyan with the LH7 roll to LR and we ran into a few interesting smokerider failures.
details in the comments
----------
ref our favorite cls-elements flake: #10877 #11426 #11341

tests(smoke): tweak expectations based on feedback from LR

---

lighthouse-core/lib/page-functions.js
lighthouse-core/test/lib/page-functions-test.js

core: alias element.currentSrc to element.src in node snippet

---

lighthouse-core/gather/gatherers/accessibility.js
lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/results/artifacts/artifacts.json
lighthouse-core/test/results/sample_v2.json
package.json
types/artifacts.d.ts
yarn.lock

1) rebaseline the accessibility sample artifact
2) upgrade to 4.1.2
~Do not squash.~

deps(axe-core): upgrade to 4.1.2

---

lighthouse-core/audits/metrics/largest-contentful-paint.js
lighthouse-core/audits/no-unload-listeners.js
lighthouse-core/audits/preload-fonts.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json

I just changed the Learn More to Learn more, to match the other metrics.

misc: fixed typos More => more

---

third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-block-url-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-block-url.js
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run.js
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-flags-run.js
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run.js
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/resources/lighthouse-basic.css
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/resources/lighthouse-basic.html

these were accidentally blown out (cuz never synced back to LH repo..) by https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2650244

tests: sync devtools tests

---

.github/workflows/issue-assigner.yml

misc: remove patrickhulce from issue assigner

---

.github/workflows/issue-assigner.yml

**Summary**
Adding myself back to issue assignment :)
reverts #12220

misc: add patrickhulce back to issue assignment

---

docs/architecture.md

Described things this way when trying to make things more tangible for Jerome.  Seems aiight

docs(architecture): augment gathering & artifacts a bit

---

.github/workflows/ci.yml

**Summary**
I know we talked about doing this but I couldn't find the PR of pulling the trigger, and I just ran into this 3 times in a row, so 🤞 that this fixes it :D

misc(ci): increase yarn network timeout

---

lighthouse-treemap/app/index.html
lighthouse-treemap/app/src/main.js

ref #11254
this info is already in the All view mode button

misc(treemap): remove byte size from title

---

lighthouse-core/report/html/renderer/i18n.js

misc(treemap): use 0.1 for default granularity

---

package.json
yarn.lock

misc(treemap): upgrade to 3.2.0 for keyboard navigation

---

lighthouse-treemap/app/index.html
lighthouse-treemap/app/src/main.js
lighthouse-treemap/app/styles/treemap.css

misc(treemap): tweak styles for mobile

---

lighthouse-treemap/app/src/main.js

misc(treemap): update colors on enter keypress

---

proto/lighthouse-result.proto

misc(proto): backport proto formatting fixes

---

lighthouse-core/report/html/renderer/report-ui-features.js

#12570 added this functionality but had some typos/bad logic.

report: fix addButton for provided container element

---

docs/v8-perf-faq.md
lighthouse-core/lib/lh-error.js
lighthouse-core/report/html/readme.md
lighthouse-core/report/html/renderer/util.js
proto/README.md
proto/lighthouse-result.proto
readme.md

g3 has some linters which flag our miscapitalization of github and a mispelling.
also updates to one of the FAQ answers that i worked on with patrick and elizabeth

misc: fix typos and update faq answer

---

lighthouse-core/audits/csp-xss.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json

New link: https://web.dev/csp-xss/
Changes are merged in web.dev https://github.com/GoogleChrome/web.dev/pull/5510
We can merge once the updates are deployed.

core(csp-xss): update learn more link

---

lighthouse-core/audits/installable-manifest.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json

Fixes https://github.com/GoogleChrome/lighthouse/issues/12677

core(installable-manifest): align descriptions with applicatons panel

---

clients/devtools-report-assets.js
lighthouse-core/audits/autocomplete.js
lighthouse-core/audits/dobetterweb/inspector-issues.js
lighthouse-core/audits/installable-manifest.js
lighthouse-core/lib/minify-trace.js
lighthouse-core/lib/url-shim.js
lighthouse-core/scripts/pptr-run-devtools.js
lighthouse-core/test/chromium-web-tests/README.md
third-party/chromium-synchronization/installability-errors-test.js

fixes https://github.com/GoogleChrome/lighthouse/issues/12756

core: reference chromium main instead of master

---

package.json
yarn.lock

deps(csp-evaluator): upgrade to exactly 1.0.4

---

readme.md

Add [SpeedVitals](https://speedvitals.com/) to the list of integrations
> SpeedVitals is a Lighthouse powered tool to measure Web Vitals across multiple devices and locations. It has various features like Layout Shift Visualization, Waterfall Chart, Field Data and Resource Graphs.

docs(readme): add SpeedVitals to the list of integrations

---

report/renderer/dom.js
report/test/renderer/dom-test.js

ref #12868
___
Commit with message:
```
Co-authored-by: André Van Dal <me@andrevandal.dev>
```

report(dom): handle undefined link url from proto roundtrip

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/config/default-config.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json

**Summary**
Updates our SEO category description to tone down its comprehensiveness and remind the user about CWV.
closes #12768

report: reword SEO category description

---

.github/workflows/smoke.yml
lighthouse-cli/test/smokehouse/test-definitions/screenshot/expectations.js

**Summary**
Updates the screenshot smoketest to support both legacy and FR modes.
ref #12861 #11313

tests(fr): convert screenshot expectations

---

docs/hacking-tips.md

gotta put these links somewhere slightly more useful…

docs(hacking): add links to buildtracker/pr-tracking

---

docs/recipes/auth/README.md

docs(auth): add missing build step in README

---

lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js

tests(smoke): print command to rerun failures

---

lighthouse-core/fraggle-rock/gather/session.js
lighthouse-core/test/fraggle-rock/gather/session-test.js

**Summary**
Adds protocol timeout support to Fraggle Rock session.
ref #12861 #11313

core(fr): add protocol timeout to session

---

report/test/renderer/dom-test.js

tests(dom): fix node 16 createObjectURL bug

---

changelog.md

Typo fix
Change: Contriubutors -> contributors

docs(changelog): fix typo in changelog.md

---

readme.md

Add [Peyk](https://peyk.com) to the list of integrations in alphabetical order.
> Peyk is a website change detection & monitoring service with the power of an advanced correlation system and a variety of modules. Peyk can track websites cookies, network requests, technologies, local & session storage, lighthouse audits, and many more besides visual tracking. Peyk is offered via free and paid plans.

docs(readme): add Peyk to the list of integrations

---

build/build-smokehouse-bundle.js
package.json

esm wasn't happenin' over in google3 land

clients(lr): bundle smokehouse as commonjs

---

flow-report/assets/styles.css
flow-report/src/app.tsx
flow-report/src/icons.tsx
flow-report/src/topbar.tsx

report(flow): topbar

---

lighthouse-viewer/app/src/firebase-auth.js

Noticed bug with deploy of new firebase credentials: on visit with pre-existing token (but old fb auth), deeplink could result in a 403 from gh saying "you should use an authenticated request!"
what happens is that i have a access token, but no firebase auth, so `_ready` never sets `_authToken`, and the deep link then doesn't make an authenticated api request even though it could because we have it and tokens are forever
This change:
* removes `_firebaseUser` (not needed
* if we have an access token, just use it (no need to query firebase auth state)
* fixes deeplink ratelimit bug
* should allow users who have already auth'd with original credentials to use their current access token (they are forever) without re-authing.

clients(viewer): use access token regardless of firebase auth

---

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-core/audits/deprecations.js
lighthouse-core/gather/gatherers/inspector-issues.js
lighthouse-core/test/audits/deprecations-test.js
lighthouse-core/test/gather/gatherers/inspector-issues-test.js
lighthouse-core/test/results/artifacts/artifacts.json
lighthouse-core/test/results/sample_v2.json
package.json
third-party/chromium-synchronization/inspector-issueAdded-types-test.js
types/artifacts.d.ts
types/lhr/audit-details.d.ts
yarn.lock

This will fix dbw smoke test.
courtesy of https://bugs.chromium.org/p/chromium/issues/detail?id=1248484

core(deprecations): use inspector issues

---

build/build-dt-report-resources.js
clients/devtools-report-assets.js

https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3283799 must land first.

clients(devtools): remove report.css

---

report/renderer/report-ui-features.js

see https://github.com/GoogleChrome/lighthouse/pull/13407#issuecomment-975963837

report: remove margin when saving html in standalone report

---

docs/user-flows.md

Closes https://github.com/GoogleChrome/lighthouse/issues/13414

docs: example to save flow as json

---

report/test/renderer/report-renderer-axe-test.js

our friendly neighborhood 100-200s test.  finally ported to pptr.
instead of taking 60-150s it takes 10s. 😁

report: port axe test to pptr

---

lighthouse-core/test/chromium-web-tests/roll-devtools.sh

tests: fix devtools build command

---

lighthouse-core/gather/driver/execution-context.js
lighthouse-core/test/gather/driver/execution-context-test.js
types/externs.d.ts

core: cache fetch to avoid bad polyfills

---

lighthouse-core/gather/gatherers/inspector-issues.js
lighthouse-core/test/audits/dobetterweb/inspector-issues-test.js
lighthouse-core/test/gather/gatherers/inspector-issues-test.js
lighthouse-core/test/results/artifacts/artifacts.json
package.json
third-party/chromium-synchronization/inspector-issueAdded-types-test.js
types/artifacts.d.ts
yarn.lock

this was removed https://source.chromium.org/chromium/chromium/src/+/d357b7f15489b1ee731971f78193aa1c42ce0ed8

core(inspector-issue): remove wasmCrossOriginModuleSharingIssue

---

lighthouse-cli/test/cli/__snapshots__/cli-flags-test.js.snap
lighthouse-cli/test/cli/cli-flags-test.js

This is a really sensitive bit of code, so let's have some snapshots.
Will help greatly for #13590

tests: add snapshot tests for cli-flags.js

---

report/renderer/report-ui-features.js

Apparently we forgot to do the "and fireworks" part of this flag.

report: disable fireworks with flag

---

build/build-dt-report-resources.js

Recent changes to DT renamed these files, was causing issues in CI
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3428452

tests(devtools): update report resource names

---

lighthouse-cli/test/fixtures/simple-page.html
lighthouse-cli/test/smokehouse/core-tests.js
lighthouse-cli/test/smokehouse/report-assert.js
lighthouse-cli/test/smokehouse/test-definitions/timing.js
lighthouse-core/runner.js
types/smokehouse.d.ts

Should be the last addition to https://github.com/GoogleChrome/lighthouse/pull/13569
Creates a new `_includes` smoke test helper to check for a subset of an array.

tests: timing smoke test

---

report/assets/templates.html
report/renderer/components.js

https://github.com/GoogleChrome/lighthouse/issues/12563

report: fix fireworks

---

lighthouse-cli/test/smokehouse/test-definitions/forms-autocomplete.js
lighthouse-core/gather/gatherers/inputs.js
lighthouse-core/scripts/legacy-javascript/create-polyfill-size-estimation.js
lighthouse-core/test/results/artifacts/artifacts.json
types/artifacts.d.ts

core(inputs): fix typo in artifact

---

lighthouse-core/scripts/pptr-run-devtools.js

Should fix the DT smoke failures in CI

tests(devtools): update Lighthouse sniffer for smokes

---

.github/workflows/devtools.yml

should prevent network timeouts

tests(devtools): add yarn install timeout

---

.github/workflows/devtools.yml
lighthouse-core/test/chromium-web-tests/download-devtools.sh

Gonna see if this fixes our recent CI issues

tests(devtools): bump cache

---

.github/workflows/devtools.yml
lighthouse-core/test/chromium-web-tests/README.md
lighthouse-core/test/chromium-web-tests/blink-tools.patch
lighthouse-core/test/chromium-web-tests/download-blink-tools.sh
lighthouse-core/test/chromium-web-tests/web-test-server.sh

blink tests were converted to p3 just a few weeks ago

tests: upgrade devtools web tests deps, use python3

---

build/build-sample-reports.js
lighthouse-core/fraggle-rock/gather/base-artifacts.js
lighthouse-core/fraggle-rock/gather/navigation-runner.js
lighthouse-core/fraggle-rock/gather/snapshot-runner.js
lighthouse-core/fraggle-rock/gather/timespan-runner.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/driver/navigation.js
lighthouse-core/gather/driver/network-monitor.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/scripts/legacy-javascript/run.js
lighthouse-core/scripts/update-flow-fixtures.js
lighthouse-core/test/fixtures/fraggle-rock/snapshot-basic/onclick.html
lighthouse-core/test/fraggle-rock/gather/base-artifacts-test.js
lighthouse-core/test/fraggle-rock/gather/mock-driver.js
lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
lighthouse-core/test/fraggle-rock/user-flow-test.js
lighthouse-core/test/gather/driver/navigation-test.js
lighthouse-core/test/gather/driver/network-monitor-test.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/test-utils.js
types/artifacts.d.ts
types/gatherer.d.ts

core: expand URL artifact

---

lighthouse-core/computed/page-dependency-graph.js
lighthouse-core/fraggle-rock/gather/base-artifacts.js
lighthouse-core/fraggle-rock/gather/navigation-runner.js
lighthouse-core/fraggle-rock/gather/snapshot-runner.js
lighthouse-core/fraggle-rock/gather/timespan-runner.js
lighthouse-core/runner.js
lighthouse-core/scripts/compare-runs.js
lighthouse-core/test/fraggle-rock/gather/base-artifacts-test.js
lighthouse-core/test/fraggle-rock/gather/mock-driver.js
lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
lighthouse-core/test/fraggle-rock/user-flow-test.js
report/generator/report-generator.js
report/renderer/open-tab.js
treemap/app/debug.json
treemap/app/src/main.js
treemap/test/treemap-test-pptr.js
types/artifacts.d.ts
types/lhr/lhr.d.ts
types/lhr/treemap.d.ts

core: make `requestedUrl` optional

---

.github/workflows/issue-assigner.yml

misc: add brendan back to triage rotation

---

lighthouse-cli/test/fixtures/oopif-scripts.html

tests: fix flaky isPositionFixed check in oopif-scripts

---

lighthouse-core/lib/stack-packs.js
lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
lighthouse-core/test/lib/stack-packs-test.js
package.json
shared/localization/locales/en-US.json
shared/localization/locales/en-XL.json
yarn.lock

This gets us Nuxt.js plus a few new strings for next.js

deps(lighthouse-stack-packs): upgrade to 1.8.1

---

build/build-sample-reports.js
lighthouse-core/fraggle-rock/gather/navigation-runner.js
lighthouse-core/index.js
types/config.d.ts

Fixes https://github.com/GoogleChrome/lighthouse/issues/13863

core: fix build-sample-reports

---

package.json
yarn.lock

Includes new facade for freshworks. I tried it out on this site:
https://www.freshworks.com/live-chat-software/

deps: upgrade third-party-web

---

lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency.js
lighthouse-cli/test/smokehouse/test-definitions/csp-block-all.js
lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js
lighthouse-cli/test/smokehouse/test-definitions/issues-mixed-content.js
lighthouse-cli/test/smokehouse/test-definitions/offline-sw-broken.js
lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics-animations.js
lighthouse-cli/test/smokehouse/test-definitions/perf-frame-metrics.js
lighthouse-cli/test/smokehouse/test-definitions/perf-trace-elements.js

tests(smoke): remove old chrome version checks

---

third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-block-url-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-clear-data-warning-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-flags-run-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-i18n-run-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-limited-run-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-prevent-run-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-navigation-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt

Recent CL landed that changed the order of categories.

tests: rebaseline webtests

---

lighthouse-core/lib/stack-packs.js
lighthouse-core/test/lib/stack-packs-test.js
package.json
yarn.lock

deps(js-library-detector): upgrade to 6.5.0

---

lighthouse-core/fraggle-rock/config/default-config.js

Fixes https://github.com/GoogleChrome/lighthouse/issues/13983

core(fps): run at the end of timespan/snapshot

---

docs/architecture.md

🔒 [Google Doc](http://go/fr-nav-default): part of our docs update list

docs(architecture): update to reflect FR changes

---

.github/workflows/devtools.yml
.github/workflows/package-test.yml
.github/workflows/smoke.yml

Unblocks CI while we investigate the issue in Chrome https://github.com/GoogleChrome/lighthouse/issues/14093

tests: disable `perf-diagnostics-third-party` for FR

---

lighthouse-core/test/lib/asset-saver-test.js

tests(asset-saver): use .tmp instead of pwd for temp file

---

flow-report/test/common-test.tsx
flow-report/test/setup/env-setup.ts
flow-report/tsconfig.json

Minor PR to avoid doing a `@ts-ignore` in a couple places.

misc: include used files in flow-report tsconfig

---

lighthouse-core/lib/i18n/i18n.js

This should fix windows CI re: sample-json

i18n: fix i18n filename path on windows

---

package.json
yarn.lock

deps(jpeg-js): upgrade to 0.4.4

---

.npmignore

Fixes https://github.com/GoogleChrome/lighthouse/issues/14222
Should add to https://github.com/GoogleChrome/lighthouse/pull/14232

misc: keep scripts package.json in npm

---

lighthouse-core/config/default-config.js
lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
lighthouse-core/test/results/sample_v2.json
shared/localization/locales/en-US.json
shared/localization/locales/en-XL.json

**Summary**
Bug fix for broken link. Updates the link to the PWA checklist found in the lighthouse report.

misc: fix broken link for PWA checklist

---

build/build-lightrider-bundles.js
build/build-smokehouse-bundle.js
build/rollup-plugins.js

Couple things were broken with the Smokerider roll.

misc(build): fix smokerider bundles

---

package.json
yarn.lock

Fixes https://github.com/GoogleChrome/lighthouse/issues/13164

deps: upgrade csp-evaluator

---

core/scripts/pptr-run-devtools.js

As discussed in #14280, we modified the DT code to easily accept a custom config when injected:
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3827986

tests(devtools): inject custom config directly

---

core/lib/cdt/generated/SourceMap.js
core/lib/deprecations-strings.js
core/lib/network-request.js
core/scripts/i18n/collect-strings.js
package.json
shared/localization/locales/en-US.json
shared/localization/locales/en-XL.json
yarn.lock

Fixes https://github.com/GoogleChrome/lighthouse/issues/14284

deps: update to latest CDT packages

---

docs/releasing.md
package.json
report/renderer/open-tab.js
treemap/README.md
viewer/README.md

another wildly important (lol) PR.  This has been bugging me for a while.... as 8000 is so rife with conflicts. 
Also.. nice that 7333 spells TREE. (sort of)

misc: use a unique local port for the treemap

---

build/package.json
cli/package.json
clients/devtools/package.json
clients/package.json
core/package.json
core/scripts/package.json
core/test/fixtures/config/lighthouse-plugin-config-helper/plugin-config-helper.js
core/test/package.json
esm-utils.js
flow-report/package.json
report/package.json
treemap/package.json
viewer/package.json

misc: remove transitionary ES module package.json files

---

core/fraggle-rock/gather/navigation-runner.js
core/fraggle-rock/gather/runner-helpers.js
core/fraggle-rock/gather/snapshot-runner.js
core/fraggle-rock/gather/timespan-runner.js
core/test/fraggle-rock/gather/navigation-runner-test.js
core/test/fraggle-rock/gather/runner-helpers-test.js
types/gatherer.d.ts

Splitting out this work from https://github.com/GoogleChrome/lighthouse/pull/13940.

core(fr): add page to context

---

third-party/devtools-tests/e2e/lighthouse/BUILD.gn
third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
third-party/devtools-tests/e2e/resources/lighthouse/hello.html

https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3885495

tests(devtools): sync e2e

---

yarn.lock

just ran `yarn` on master to make this PR.
from #14391 i think.

deps: re-sync yarn.lock file

---

third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
third-party/devtools-tests/e2e/resources/lighthouse/BUILD.gn
third-party/devtools-tests/e2e/resources/lighthouse/hello.html
third-party/devtools-tests/e2e/resources/lighthouse/sw.js

https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3930940
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3943210
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3943528
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3943213
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3946304
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3957614

tests(devtools): sync e2e tests

---

docs/user-flows.md

Docs changes for https://github.com/GoogleChrome/lighthouse/pull/14531
Merging into `10-docs-staging`

docs(user-flows): use new api location

---

core/scripts/update-flow-fixtures.js
core/test/fixtures/fraggle-rock/reports/sample-flow-result.json

Connor noticed a readonly error when updating timing data https://github.com/GoogleChrome/lighthouse/pull/14576#discussion_r1041410874

tests: fix timings in update-flow-fixtures.js

---

changelog.md

Trivial PR, just grabbing the changelog docs from branch-9

docs(changelog): add 9.6.x release notes

---

core/lib/bfcache-strings.js
core/lib/cdt/generated/SourceMap.js
core/lib/deprecations-strings.js
package.json
shared/localization/locales/en-US.json
shared/localization/locales/en-XL.json
yarn.lock

deps: update to latest chrome-devtools-frontend

---

docs/configuration.md

docs(config): add plugins property

---

core/config/config.js
core/config/filters.js
core/config/validation.js
core/gather/base-artifacts.js
core/gather/navigation-runner.js
core/index.js
core/legacy/config/config.js
core/runner.js
core/test/config/filters-test.js
core/test/gather/navigation-runner-test.js
core/test/legacy/config/config-test.js
core/test/legacy/gather/gather-runner-test.js
core/test/runner-test.js
types/config.d.ts
types/gatherer.d.ts

https://github.com/GoogleChrome/lighthouse/pull/14547#issuecomment-1334527580

core: rename resolved config types

---

core/config/default-config.js
core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
core/test/results/sample_v2.json
report/test/generator/report-generator-test.js

core(no-unload-listeners): move to best practices

---

cli/test/smokehouse/test-definitions/metrics-tricky-tti.js

https://bugs.chromium.org/p/chromium/issues/detail?id=1413830

tests(metrics-tricky-tti): disable for M112

---

core/gather/navigation-runner.js

Fixes https://github.com/GoogleChrome/lighthouse/issues/14769

core: disconnect Puppeteer when started by Lighthouse

---

changelog.md

i was too slow. 
nothing massive in here. the changlog is a beaut.

docs(changelog): minor v10 edits

---

core/audits/dobetterweb/paste-preventing-inputs.js
core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
core/test/results/sample_v2.json
shared/localization/locales/en-US.json
shared/localization/locales/en-XL.json

Rephrased according to translator comments.

core(paste-preventing-inputs): rephrase description

---

docs/recipes/type-checking/package.json
types/artifacts.d.ts

core(types): fix error when using module resolution "node"

---

core/audits/bf-cache.js
core/test/audits/bf-cache-test.js

This was an area of confusion from CPQ chat with Rick

core(bf-cache): count failures based on affected frames

---

proto/lighthouse-result.proto

misc(proto): bump next id

---

build/build-bundle.js
package.json
yarn.lock

Changes to bundle sizes are negligible.

clients(bundled): include soft navigation plugin

---

cli/bin.js
cli/test/fixtures/dobetterweb/dbw_tester.html
core/audits/audit.js
core/lib/i18n/i18n.js
core/lib/network-request.js
core/scripts/pptr-run-devtools.js
core/scripts/roll-to-devtools.sh
core/test/legacy/gather/gather-runner-test.js
report/test/renderer/details-renderer-test.js
types/artifacts.d.ts

a g3 linter caught this. I hardly care, but.. one less linter warning..

misc: fix typos of overridden

---

core/lib/tracehouse/trace-processor.js
core/test/lib/tracehouse/trace-processor-test.js

Fixes https://github.com/GoogleChrome/lighthouse/issues/14893

core(trace-processor): support single process trace

---

core/audits/dobetterweb/doctype.js
core/test/audits/dobetterweb/doctype-test.js

Closes https://github.com/GoogleChrome/lighthouse/issues/14916

core(doctype): handle optional trace correctly

---

core/scripts/pptr-run-devtools.js

Updates in https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4406840 broke this

tests(devtools): fix config for testing

---

cli/test/fixtures/seo/seo-tap-targets.html
proto/lighthouse-result.proto

had to fix this downstream in LR
driveby fix on a typo too

misc(proto): fix case in entities fields

---

package.json
yarn.lock

Fixes https://github.com/GoogleChrome/lighthouse/issues/14934

deps: upgrade `http-link-header`

---

core/runner.js
core/test/runner-test.js

Fixes https://github.com/GoogleChrome/lighthouse/issues/14922

core(runner): handle erroneous screenshot

---

package.json
yarn.lock

Note: byte-efficiency ToT is only failing because of unrelated bug https://bugs.chromium.org/p/chromium/issues/detail?id=1434190

deps(chrome-launcher): update to 0.15.2

---

core/lib/url-utils.js
core/test/lib/url-utils-test.js

core: classify extension urls as non-network

---

core/audits/seo/crawlable-anchors.js
core/gather/gatherers/anchor-elements.js
core/test/audits/seo/crawlable-anchors-test.js
types/artifacts.d.ts

Closes https://github.com/GoogleChrome/lighthouse/issues/12030

core(crawlable-anchors): allow elements acting as anchors

---

lighthouse-logger/package.json

Need to release https://github.com/GoogleChrome/lighthouse/pull/14964

misc: bump `lighthouse-logger` to v1.4.0

---

cli/test/smokehouse/test-definitions/a11y.js
package.json
yarn.lock

https://github.com/dequelabs/axe-core/releases/tag/v4.7.1
Should be just bug fixes.

deps: upgrade axe-core to 4.7.1

---

.github/workflows/smoke.yml

Fixes dbw smoke for Windows, see #15160

tests(ci): bump node to fix windows latency failure

---

package.json
yarn.lock

https://github.com/dequelabs/axe-core/releases/tag/v4.7.2

deps: upgrade axe-core to 4.7.2

---

package.json
yarn.lock

https://github.com/patrickhulce/third-party-web/releases/tag/v0.23.0

deps: upgrade third-party-web to 0.23.0

---

core/lib/stack-packs.js
core/test/lib/stack-packs-test.js
package.json
shared/localization/locales/en-US.json
shared/localization/locales/en-XL.json
yarn.lock

https://github.com/GoogleChrome/lighthouse-stack-packs/pull/91
Verified this works, see unused js audit: https://googlechrome.github.io/lighthouse/viewer/?gist=d2ccd2a91908937dc4ce40311a869aae

core(stacks): add wix

---

docs/plugins.md

**Summary**
- Fix Syntax error in document code blocks

docs(plugins): fix syntax typos

---

build/build-sample-reports.js
core/config/filters.js
core/gather/base-artifacts.js
core/gather/navigation-runner.js
core/gather/runner-helpers.js
core/lib/asset-saver.js
core/runner.js
core/test/gather/base-artifacts-test.js
core/test/gather/mock-driver.js
core/test/gather/navigation-runner-test.js
core/test/gather/runner-helpers-test.js
types/artifacts.d.ts
types/gatherer.d.ts
types/lh.d.ts

Part of https://github.com/GoogleChrome/lighthouse/issues/15060

core: remove legacy artifacts types

---

lighthouse-logger/package.json

We get a warning message if this isn't present

misc: add main path to logger

---

core/audits/largest-contentful-paint-element.js
core/test/audits/largest-contentful-paint-element-test.js

https://github.com/GoogleChrome/lighthouse/issues/15075

core(lcp-element): gracefully handle error in phase table

---

docs/configuration.md
docs/readme.md
docs/recipes/custom-audit/readme.md

https://github.com/GoogleChrome/lighthouse/issues/15060

docs: remove legacy navigation

---

core/audits/seo/crawlable-anchors.js
core/test/audits/seo/crawlable-anchors-test.js

core(crawlable-anchors): consider empty `rawHref` crawlable

---

readme.md

**Summary**
Sugary readme fix
N/A

misc(readme): use note for Node version callout

---

package.json
yarn.lock

https://github.com/patrickhulce/third-party-web/releases/tag/v0.24.0
https://github.com/patrickhulce/third-party-web/releases/tag/v0.23.4

deps: upgrade `third-party-web` to 0.24.0

---

cli/test/smokehouse/test-definitions/dobetterweb.js

This has been very flaky with Chrome ToT lately.

tests(dbw): increase wasted ms threshold

---

package.json
shared/localization/locales/en-US.json
shared/localization/locales/en-XL.json
yarn.lock

https://github.com/GoogleChrome/lighthouse-stack-packs/pull/99

deps: upgrade `lighthouse-stack-packs` to 1.12.1

---

cli/test/smokehouse/test-definitions/oopif-scripts.js
core/test/scenarios/api-test-pptr.js

These changes are expected in M121: https://bugs.chromium.org/p/chromium/issues/detail?id=1501148#c1

core: fix worker request expectations for M121

---

treemap/app/index.html
treemap/types/treemap.d.ts

misc(treemap): remove unused firebase

---

package.json
yarn.lock

https://github.com/patrickhulce/third-party-web/releases/tag/v0.24.1

deps: upgrade `third-party-web` to 0.24.1

---

docs/user-flows.md

Closes https://github.com/GoogleChrome/lighthouse/issues/15607
I verified this example works locally.

docs(user-flows): update complete flow example

---

build/build-bundle.js

misc(build): set line limit to 1000

---

package.json
yarn.lock

https://github.com/dequelabs/axe-core/releases/tag/v4.8.4

deps: upgrade `axe-core` to 4.8.4

---

readme.md

Add [DeploymentHawk](https://deploymenthawk.com) to the list of integrations:
> DeploymentHawk is an automated site auditing tool powered by Lighthouse. Effortlessly catch performance, accessibility, and SEO issues before they impact your users. DeploymentHawk is a paid product with a free 7-day trial.

docs(readme): add DeploymentHawk to the list of integrations

---

changelog.md

misc: merge changelog from branch-11

---

package.json
yarn.lock

deps: upgrade `tldts-icann` to 6.1.16

---

core/lib/bf-cache-strings.js
shared/localization/locales/en-US.json
shared/localization/locales/en-XL.json

This is the downstream fix of crbug.com/340606787

misc(strings): fix WebAuthetication typo 

---

package.json
yarn.lock

https://github.com/dequelabs/axe-core/releases/tag/v4.9.1

deps: upgrade `axe-core` to 4.9.1

---

package.json
yarn.lock

https://github.com/patrickhulce/third-party-web/releases/tag/v0.24.3

deps: upgrade `third-party-web` to 0.24.3

---

readme.md

**Summary**
They look to no longer be a company [as website is 404](https://alertdesk.com/), [github repo](https://github.com/alertdesk) is empty.
Original PR adding them: https://github.com/GoogleChrome/lighthouse/pull/12356
FYI @kasperadk who added in that.

misc: remove alertdesk from README

---

package.json
yarn.lock

https://github.com/patrickhulce/third-party-web/releases/tag/v0.24.4
https://github.com/patrickhulce/third-party-web/releases/tag/v0.24.5

deps: upgrade `third-party-web` to 0.24.5

---

core/config/lr-mobile-config.js

Closes https://github.com/GoogleChrome/lighthouse/issues/16201

clients(lr): set CPU throttling based on benchmark

---

core/computed/trace-engine-result.js

Closes https://github.com/GoogleChrome/lighthouse/issues/16111

core(trace-engine): re-enable invalidations handler

---

core/scripts/pptr-run-devtools.js

https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/6157257

tests(devtools): fix error in smoke tests with DT throttling

---

package.json
yarn.lock

deps: upgrade deps

---

core/audits/server-response-time.js
core/test/audits/server-response-time-test.js
core/test/create-test-trace.js
core/test/fixtures/user-flows/reports/sample-flow-result.json
core/test/results/sample_v2.json
types/artifacts.d.ts

Chilling for a bit, want to update trace processor first with https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/7004563 to prevent the change in response time.

core(server-response-time): defer to Document Lantency insight

---

cli/test/smokehouse/config/exclusions.js
cli/test/smokehouse/core-tests.js
cli/test/smokehouse/test-definitions/csp-block.js

tests: re-enable csp block smoke test, make less restrictive
