GoogleChrome/lighthouse

lighthouse-core/test/audits/themed-omnibox-test.js
lighthouse-core/test/lib/manifest-parser-test.js
package.json
yarn.lock

90% of this is tests :)
(`manifest-parser.js` had no existing tests for its color parsing)
(*edit: unit tests. It does have integration tests through `themed-omnibox`, `splash-screen`, et al.*)
fixes #7139

deps: update cssstyle to parse more named colors, CSS4 colors

---

lighthouse-core/lib/emulation.js

**Summary**
Adds 'Chrome-Lighthouse' to the UA for mobile and desktop so that Lighthouse and PSI have strongly consistent UAs.
Will come to PSI and web.dev on next update.
addresses: #7140

core(driver): add ' Chrome-Lighthouse' to useragent

---

lighthouse-cli/test/fixtures/byte-efficiency/gzip.html
lighthouse-cli/test/fixtures/static-server.js
lighthouse-cli/test/smokehouse/byte-config.js
lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js

Assert that gzip savings are correctly being provided by the browser for LH to use.
Regression test for when a version of headless Chrome was giving weird `dataReceivedEvent` values in the face of gzipped resources (see [this doc](https://docs.google.com/document/d/1FcvF1kKtWuKh2OLXXkTsBuh7qq9f6PxmA-JWcre1wFo/edit) (private to Googlers) for more).
Related: #7284

tests(smokehouse): gzip test to assert transfer and resource sizes

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/image-elements.js
lighthouse-core/test/gather/driver-test.js
types/artifacts.d.ts

**Summary**
Caps our time spent fetching natural size information in `ImageElements` gatherer.
Aside, this got me thinking that we really need artifact smoketests. The current logic is covered by existing smoketests, but it'd be a lot more comfortable to make changes to gatherers with lots of `evaluateAsync` if we could easily add gatherer smoketests.
closes https://github.com/GoogleChrome/lighthouse/issues/7273

core(image-elements): cap natural size fetch time

---

lighthouse-cli/test/fixtures/tricky-main-thread-consumer.js
lighthouse-cli/test/fixtures/tricky-main-thread-library.js
lighthouse-cli/test/fixtures/tricky-main-thread.html
lighthouse-cli/test/smokehouse/tricky-metrics/expectations.js
lighthouse-core/audits/bootup-time.js
lighthouse-core/computed/main-thread-tasks.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/test/audits/bootup-time-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
There are a couple things going on here all sparked by #7005. This bootup time audit is somewhat inconsistent because it's pulling double duty as two different things.
1. It flags the amount of time spent loading due to script execution.
2. It flags the CPU time hogged by the responsible script URL.
These are different because a script can force a layout. It's not fair to say the layout time was "script execution" necessarily because it was the browser doing the work, but it's also not fair to ignore the cost of layouts from third party scripts when saying "these are your problem scripts". Any ideas to solve this problem are welcome :)
Now on to the PR changes...
1. Script executions that are the result of a setTimeout are now assigned to the script that installed the timer …

core(bootup-time): better attribution

---

lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
lighthouse-cli/test/smokehouse/smokehouse.js

test(smokehouse): +/- operator

---

lighthouse-core/audits/seo/font-size.js
lighthouse-core/audits/seo/tap-targets.js
lighthouse-core/audits/viewport.js
lighthouse-core/computed/viewport-meta.js
lighthouse-core/test/audits/seo/font-size-test.js
lighthouse-core/test/audits/seo/tap-targets-test.js
lighthouse-core/test/audits/viewport-test.js
lighthouse-core/test/computed/viewport-meta-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json
types/artifacts.d.ts

**Summary**
Get the viewport info from a ViewportMeta computed artifact, instead of the font size and tap target audits calling the viewport audit.
Involves making the three audits involved async because computed artifacts are async.
@brendankenny also mentioned including a `notApplicable` property in the artifact result, for when Lighthouse is run in desktop mode. I've not done that for now, but will consider it when [adding the `isMobile` artifact](https://github.com/GoogleChrome/lighthouse/issues/7043) or [adding `notApplicable` logic to tap targets](https://github.com/GoogleChrome/lighthouse/issues/6687).
Closes https://github.com/GoogleChrome/lighthouse/issues/7084

core(viewport): create ViewportMeta computed artifact

---

lighthouse-cli/run.js

while we wait for the fix for https://crbug.com/936272 and/or in chrome-launcher, this change at least writes the report to disk before waiting for Chrome to close.
Also removes the `unhandledRejection` listener when done (fixing the `MaxListenersExceededWarning` for @Hoten) and converts`runLighthouse` to use async/await, as the ancient promise business in there was inscrutable. I think there's still more to improve here, both bikeshedding and file organization (e.g. `handleError` should maybe be in `bin.js`, not in here); happy for more ideas or leaving all that for yet another day.

cli: write report in runLighthouse before quitting Chrome

---

lighthouse-core/config/config-plugin.js
lighthouse-core/test/config/__snapshots__/config-plugin-test.js.snap
lighthouse-core/test/config/config-plugin-test.js
lighthouse-core/test/config/config-test.js
lighthouse-core/test/fixtures/config-plugins/lighthouse-plugin-simple/plugin-simple.js
types/config.d.ts

**Summary**
Allow for plugin to add custom groups and assign custom to plugin auditRefs. 
Modify tests to verify groups added and assigned properly.
#6959
#6070

core: add group support for plugins

---

docs/configuration.md
docs/readme.md
lighthouse-cli/cli-flags.js
readme.md

**Summary**
Added improvements to the docs around configuring Lighthouse. I recently found some aspects of the existing docs confusing or lack. See https://github.com/GoogleChrome/lighthouse/issues/7344 for discussion.
This PR makes the following docs changes:
- ~~Adds `lr-desktop` and `lr-mobile` to the list of choices available with the `--preset` CLI flag~~
- Adds warning about the `--preset` flag being ignored if the `--config-path` flag is provided
- Adds an example config file reference for the `--config-path`  CLI flag so user knows config format
- Adds a configuration section with example in a more prominent place in the additional docs readme
- Adds note about the limitations of the `extends` property and how to use presets programmatically
- Adds links to newer presets available …

docs: improve docs around preset configuration and using the Node module

---

types/externs.d.ts

converts them to `/** */` style so they appear on hover in vscode, etc

misc: use jsdoc-style comments on Flags properties

---

docs/throttling.md
types/externs.d.ts

**Summary**
Throttling rate is in kilobits not kilobytes.
LH uses a bandwidth of 1638kbps/1.6mpbs by default, so we should recommend using that with comcast too.

docs: fix throttling rate comment and tweak comcast bandwidth

---

lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/audits/seo/tap-targets.js
lighthouse-core/test/audits/seo/tap-targets-test.js

**Summary**
Right now if the audit score is above 90 the tap targets audit doesn't fail even if there are overlap failures. That way it's hard to identify what's dragging the SEO score down. So if there are failures we should cap the score at 89.
Closes https://github.com/GoogleChrome/lighthouse/issues/7338

core(tap targets): make tap targets failures more visible

---

lighthouse-core/audits/content-width.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/test/audits/content-width-test.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/results/artifacts/artifacts.json
types/artifacts.d.ts

**Summary**
Extract the logic for this from the `content-width` audit so we can use it for other audits.
@patrickhulce I know we were talking about an `Environment` artifact to wrap these two properties, but since there are already other environment-related properties directly on `baseArtifacts` I just added them there.
Closes https://github.com/GoogleChrome/lighthouse/issues/7043

core(base-artifacts): add FormFactorIsMobile base artifact

---

lighthouse-core/audits/seo/font-size.js
lighthouse-core/audits/seo/tap-targets.js
lighthouse-core/test/audits/seo/font-size-test.js
lighthouse-core/test/audits/seo/tap-targets-test.js

**Summary**
These two audits aren't important to desktop SEO, so we should disable them there.
Closes https://github.com/GoogleChrome/lighthouse/issues/6687

core(tap-targets): disable font size and tap targets audit on desktop

---

readme.md

**Summary**
Adds Lighthouse Keeper to the related projects section in the readme.
Related to #7396

docs(readme): add lighthouse-keeper to integrations

---

.travis.yml

I noticed this in the travis logs:
Fixing this might speed up travis by ~55s..

misc: clean node_modules/.cache before travis builds its cache

---

lighthouse-core/audits/seo/link-text.js

**Summary**
lint link-text is great!! I think that it will more wonderful if it supports multiple languages.
I added Japanese easily. But I think this should be separate file, and that various people should be involved in editing.
Please let the opinion. 
thanks.

core(seo): support japanese in link-text audit

---

lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
lighthouse-core/audits/byte-efficiency/uses-webp-images.js
lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/test/audits/byte-efficiency/uses-optimized-images-test.js
lighthouse-core/test/audits/byte-efficiency/uses-webp-images-test.js
lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js
types/artifacts.d.ts

**Summary**
We cap execution of our OptimizedImage gatherer at 5s and estimate the savings on all the images we didn't get to.
I know it got big, but it's really just the capping + all the consequences of capping + tests.
closes #7173

core(optimized-images): cap execution to 5 seconds

---

lighthouse-core/report/html/renderer/dom.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/pwa-category-renderer.js

misc: various spelling fixes

---

readme.md

Corrected all grammatical errors and punctuations.
**Summary**

docs: correct punctuations in README.md

---

lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js

Fixes issue identified in https://github.com/GoogleChrome/lighthouse/pull/7392/files#r262967099
Up until now we've been missing 3 vulns for bootstrap that had more than one semver range.
But aside from 4.0.0-alpha, these versions [had been flagged](https://github.com/GoogleChrome/lighthouse/blob/d93bdf35f467957a11a31aa48456d63373e08ad7/third-party/snyk/snapshot.json#L31) with another vuln, so we really hadn't been missing out on any coverage..  :)

core(vuln-libs): match against all semver ranges provided by snyk

---

lighthouse-core/audits/image-aspect-ratio.js
lighthouse-core/test/audits/image-aspect-ratio-test.js

**Summary**
We just don't have reliable ways of doing this for CSS background images, it's not worth the distrust this brings. See #7487 and https://twitter.com/_Caleb_R/status/1106204173048139776
closes #7487

core(image-aspect-ratio): ignore css background images

---

lighthouse-core/gather/gather-runner.js

**Summary**
Happens when running lighthouse on insecure pages:
```
lighthouse https://wrong.host.badssl.com/
```
I also sometimes get this error (like one in 10 times or so).

core(logging): Don't log when closing already closed page

---

lighthouse-cli/test/fixtures/seo/seo-tap-targets.html
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/gather/gatherers/seo/tap-targets.js

**Summary**
Whether sticky elements overlap depends on the current scroll position, so we should exclude them like we do with position absolute and fixed.
Pointed out here: https://github.com/GoogleChrome/lighthouse/issues/7365#issuecomment-474095920

core(tap-targets): exclude sticky elements from tap targets audit

---

lighthouse-cli/test/fixtures/static-server.js

Files served through GAE with no Content-Type get assigned `text/html`. This caused some image resources to not get checked in the `image-aspect-ratio` and `efficient-animated-content` audits in Smokerider.

tests(smokehouse): set Content-Type for images served by static-server.js

---

lighthouse-cli/test/smokehouse/tricky-metrics/expectations.js
package.json

I don't tend to look at the appveyor tests too closely now that they are so flakey, but apparently our viewer filter has been ignored and so it defaults to re-running *all* our tests. As if it weren't slow enough already! 😭 
Turns out it wasn't quoted like the others, so this *should* fix it.

misc: fix unit-viewer command for windows

---

lighthouse-cli/test/fixtures/oopif.html
lighthouse-cli/test/smokehouse/oopif-expectations.js
lighthouse-core/gather/driver.js
lighthouse-core/lib/network-recorder.js
lighthouse-core/test/gather/driver-test.js
lighthouse-core/test/lib/network-recorder-test.js

**Summary**
OK, OOPIF fixes attempt 479 :)
The good news: this is now 100% contained in driver.js and should work in all our environments 🎉 
The bad news: it's kinda ugly to look at and reason about (we have to do nested Target.sendMessageToTarget calls and unpack nested receiveMessageFromTarget messages)
#7517 #7566 also #6922 #6337 #6078

core(oopif): attach to all descendants

---

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/load-fast-enough-for-pwa.js
lighthouse-core/audits/seo/font-size.js
lighthouse-core/audits/user-timings.js
lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/report/html/renderer/util-test.js
types/audit.d.ts

#6767 finally put to bed the non-`string` version of `displayValue`, but we forgot to remove `Util.formatDisplayValue`, which was always returning on the first two lines of the function (either identity or `''` :)

misc: remove obsolete Util.formatDisplayValue

---

lighthouse-core/lib/url-shim.js

back in https://github.com/GoogleChrome/lighthouse/pull/5065#discussion_r190330586 i wanted to add a comment mentioning PSL because it's the name of this thing.
anyway, that's it.
cc @patrickhulce as i noticed you do the same sorta thing in https://github.com/patrickhulce/third-party-web/blob/master/lib/index.js#L5

docs(url-shim): add comment about public suffix lst

---

lighthouse-core/audits/font-display.js
lighthouse-core/test/audits/font-display-test.js

**Summary**
Apparently leftover `\r` characters destroy our match statement later on so we should remove them before trying to find our `@font-face` declarations.
#7708

core(font-display): handle carriage returns

---

lighthouse-core/audits/main-thread-tasks.js
lighthouse-core/test/audits/main-thread-tasks-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Typo in the `main-thread-tasks` audit, I didn't get around to surfacing this yet, so it shouldn't have hurt anything. I think I was originally going for first inner child of toplevel task so we'd actually have a type, but then again I wasn't using the results yet, so 🤷‍♂️ 
#7700

core(main-thread-tasks): use toplevel tasks in main thread audit

---

lighthouse-core/lib/dependency-graph/base-node.js
lighthouse-core/test/lib/dependency-graph/base-node-test.js

While starting work on robust TTI, there were some things that were a little hard to follow as I was stepping through graphs. Tried to make them a bit clearer in code and comments while keeping everything working the same.
@patrickhulce let me know if this feels like too much change for change's sake and I can scale it back :)

misc: drive-by code cleanup in BaseNode

---

lighthouse-core/gather/gatherers/image-elements.js

the comment is out of date.
getBoundingClientRect  used to return a ClientRect which stringified to {}
but [as of july 2017](https://bugs.chromium.org/p/chromium/issues/detail?id=719246#c20), it returns a DOMRect, which stringifies fine.
Still, we dont want all the props, so we'll keep the basic functionality here.
this change is so minor. sorry for the noise.
credit to @brendankenny who brought this up

misc(gather): update comment re: ClientRect copying

---

lighthouse-cli/test/smokehouse/perf/expectations.js
lighthouse-cli/test/smokehouse/seo/expectations.js

These were the simple ones - the ones that an equivalent assertion on `score` was possible. One that seemed to not assert anything really.
#6199

test(smoke): remove trivial uses of rawValue from expectations

---

lighthouse-core/runner.js

Reduces LHR size by ~4KB. That was ~1% of the LHR I tested it with.
#7160

core: truncate measure timings to hundredths

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
lighthouse-core/gather/gatherers/scripts.js
lighthouse-core/lib/network-recorder.js
lighthouse-core/lib/network-request.js
lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js
lighthouse-core/test/gather/gatherers/dobetterweb/response-compression-test.js
lighthouse-core/test/lib/network-recorder-test.js
types/protocol.d.ts

**Summary**
Some cleanup now that we're in an OOPIF world. Because they are different targets the commands will fail for these records and generated a lot of log noise. Nothing is changed functionality-wise from before we enabled OOPIFs, and I think a discussion of whether we should surface these in the report is a separate topic. For now, we skip them.
#6922 #7608

core(oopifs): skip OOPIF network records in some gatherers

---

lighthouse-core/computed/network-analysis.js
lighthouse-core/computed/page-dependency-graph.js
lighthouse-core/lib/dependency-graph/simulator/connection-pool.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js
lighthouse-core/test/lib/dependency-graph/simulator/connection-pool-test.js
types/artifacts.d.ts

another one I accumulated while stepping through the simulator. Feel free to reject anything @patrickhulce :)
1) remove `records` from `LH.Artifacts.NetworkAnalysis`. The caller of the computed artifact has to already have them to get the `NetworkAnalysis`, and we never use them on any instance of the type anyways.
2) early return in `PageDependencyGraph.linkNetworkNodes()` for the common case where there were no redirects of a particular record
3) split `ConnectionPool.acquire()` into the case where a connection is needed to fetch a record and the case where a connection is already fetching a record.
This seems ok as a place where the generality hasn't proven necessary...we only call `acquire()` in three places, and the two done that return assigned connections already explicitly call …

misc: simplifications in simulator/connection-pool

---

lighthouse-core/computed/main-thread-tasks.js
lighthouse-core/test/computed/main-thread-tasks-test.js

**Summary**
There were some extra cases where we weren't throwing on nonsensical trace event structures. This PR adds some coverage for those cases.
https://github.com/GoogleChrome/lighthouse/issues/7764#issuecomment-479325992

tests: better fatal trace logic error coverage

---

lighthouse-core/computed/network-analysis.js
lighthouse-core/lib/dependency-graph/simulator/connection-pool.js
lighthouse-core/lib/dependency-graph/simulator/dns-cache.js
lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/test/lib/dependency-graph/simulator/connection-pool-test.js
lighthouse-core/test/lib/dependency-graph/simulator/dns-cache-test.js

No issues, just for documentation and ease of cross referencing.
Where the only caller(s) passed in definitely defined arguments, also made the properties required (I think this only happened for the `ConnectionPool` and `DNSCache` constructors).

misc: specify types for some dependency-graph options objects

---

readme.md

**Summary**
> What kind of change does this PR introduce?
Adds an integration: [Foo](https://www.foo.software).
Thanks in advance 🙇

docs(readme): Foo integration

---

lighthouse-cli/test/fixtures/static-server.js

tests(smokehouse): set Content-Type for webp images served by static-server.js

---

types/lhr.d.ts

was starting work on a public `d.ts` file and come across this unused type. The public `d.ts` file is a lot more work than I'm prepared to take on for it at the moment, but wanted to flush this before I forgot :)

misc: remove unused typedef

---

lighthouse-core/lib/network-request.js
lighthouse-core/test/lib/network-request-test.js

@exterkamp (when merged it'll become part of #7888) 
tests are mostly of the form:
- use `networkRecordsToDevtoolsLog` to generate devtools logs from network records to be tested
- turn on (or don't) `global.isLightrider`
- use `NetworkRecord.recordsFromLogs` to get back network records just as LH normally parses them (with LR changes from headers if applicable)
- use `expect()` for assertions (even though `expect(x).toBe(y)` is really ugly :) so we can use `expect(record).toMatchObject(originalReq)` when no changes from headers should have been made

tests: generate devtoolsLogs for network-request-test.js tests

---

lighthouse-core/lib/network-request.js
lighthouse-core/test/lib/network-request-test.js

**Summary**
Follow up to #7888 which now actually applies those LR timings.
Call out if I forgot to re-add anything.

clients(lr): apply Lightrider timings to NetworkRequests

---

stack-packs/packs/wordpress.js

**Summary**
Adds links for search results + more to Wordpress stack pack audits
@wardpeet @paulirish 
#7243

feat(stack-packs): adds links to some wordpress stack strings

---

.appveyor.yml
.travis.yml
docs/headless-chrome.md
lighthouse-cli/run.js
lighthouse-core/gather/connections/cri.js
lighthouse-core/lib/asset-saver.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/lib/lh-error.js
lighthouse-core/scripts/update-report-fixtures.js
package.json
proto/lighthouse-result.proto
readme.md
types/externs.d.ts
yarn.lock

misc: drop support for Node before 10.13 (LTS)

---

readme.md

docs: Remove link to archived lighthouse-security project

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/gather/gatherers/dobetterweb/domstats.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/test/audits/dobetterweb/dom-size-test.js
lighthouse-core/test/results/artifacts/artifacts.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json
types/artifacts.d.ts

Hi :)
**Summary**
Respect only nodes within `<body>` for dom-size calculation audit
This has been tagged as bug, but it appears it's more like an adjustment how calculation of DOM size is done
More accurate results whether there are too many DOM elements which might result in bad performance for layouting and rendering
https://github.com/GoogleChrome/lighthouse/issues/6806
Have a nice day
midzer

core(dom-size): collect only body nodes for DOM stats

---

lighthouse-cli/test/smokehouse/a11y/expectations.js
lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-cli/test/smokehouse/error-expectations.js
lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js
lighthouse-cli/test/smokehouse/oopif-expectations.js
lighthouse-cli/test/smokehouse/perf/expectations.js
lighthouse-cli/test/smokehouse/perf/lantern-expectations.js
lighthouse-cli/test/smokehouse/pwa-expectations.js
lighthouse-cli/test/smokehouse/pwa2-expectations.js
lighthouse-cli/test/smokehouse/pwa3-expectations.js
lighthouse-cli/test/smokehouse/redirects/expectations.js
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-cli/test/smokehouse/smoke-test-dfns.js
lighthouse-cli/test/smokehouse/smokehouse-report.js
lighthouse-cli/test/smokehouse/smokehouse.js
lighthouse-cli/test/smokehouse/tricky-metrics/expectations.js
types/smokehouse.d.ts

**Summary**
We'd [like to](https://github.com/GoogleChrome/lighthouse/pull/7778#discussion_r271847241) make assertions against the artifacts in the smoke tests.
- Wrap existing expectations in `lhr` top level object
- Add support for having `artifacts` expectations in addition to `lhr`

tests: support artifact assertions in smoke tests

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js

I broke the build with #8044 :)
One of the rare times that the auto merge was successful and yielded valid javascript but broke the code's logic by taking what was a top-level audit assertion (new since the branch point) and leaving it at the top level after the merge, while #8044 had nested all the other assertions one layer deeper.
(the reason I wasn't able to see the failure locally was because travis was merging with master before testing and I was just checking the branch).

misc: fix bad auto-merge

---

build/build-bundle.js
lighthouse-core/audits/dobetterweb/js-libraries.js
lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/stack-collector.js
lighthouse-core/lib/stack-packs.js
lighthouse-core/runner.js
lighthouse-core/test/audits/dobetterweb/js-libraries-test.js
lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js
lighthouse-core/test/fixtures/artifacts/empty-artifacts/artifacts.json
lighthouse-core/test/fixtures/artifacts/perflog/artifacts.json
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/runner-test.js
package.json
stack-packs/index.js
stack-packs/package.json
stack-packs/stack-packs.d.ts
types/artifacts.d.ts
types/html-renderer.d.ts
types/lhr.d.ts
yarn.lock

changes:
- clean up of some of the jsdocs for stack pack types and properties in various `d.ts` files
- made `artifacts.Stacks` always defined (just init with a `[]`, get to remove the null checks). makes sense cause it's an array (so no results can just be an empty array) and it's a base artifact, so really should always be defined
- moved `lib/gatherer-stacks.js` to `lib/stack-collector.js` after discussing names with @paulirish. Happy to bikeshed more tho :)
- added types to `js-library-detector` output (in `stack-collector.js`), and settled on normalizing its various combinations of `undefined` and `null` for missing output to just using `undefined` once it becomes an artifact.
- while fixing `js-library-detector` noticed our incorrect async `Object.entries().forEach()`, which gives …

core: adjustments to stack-pack comments and types

---

.build-for-now.sh
lighthouse-core/scripts/build-report-for-autodeployment.js
lighthouse-core/scripts/build-report-to-dist.js
now.json

As described in #8159. :)
Jeffy enabled Now for us in this org. Thx!
Each deployment URL is unique. But there are also living URL aliases that represent each branch (including master):
* This PR (branch `nowjson`) is `lighthouse-git-nowjson.googlechrome.now.sh`
* The pattern ([documented here](https://zeit.co/docs/v2/domains-and-aliases/aliasing-a-deployment/#git-staging-aliases)) is `lighthouse-git-<branch name>.googlechrome.now.sh`. I don't believe we can change this.
* Master is `lighthouse.googlechrome.now.sh`
The .sh has to be in the project root for the now builder to be reasonable. Ideally I would have liked it to be in lighthouse-core/scripts, but so it goes.
ref #8159

misc(ci): build report and deploy to now.sh on every commit

---

lighthouse-core/report/html/report-template.html

Providing a hook in case one uses the report-generator from a webapp (after DCL has fired).

report: extract init() function from report-template

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/smokehouse/byte-config.js
lighthouse-core/config/default-config.js

**Summary**
I broke offscreen images when I moved the image-elements gatherer down below accessibility in https://github.com/GoogleChrome/lighthouse/pull/7030.
This PR adds a smoketest to capture this and moves axe to the bottom with a comment.
broken in #7030
fixes #8211

core: always run axe last

---

lighthouse-core/report/html/templates.html

**Summary**
This PR fixes #8110 where a div was missing.
This change was needed in favour of beautified exported reports where e.g. prettier printed an error because of that missing closing tag.
Related PR: https://github.com/GoogleChrome/lighthouse/pull/8128
Related Issue: #8110

report: add missing </div>

---

lighthouse-cli/cli-flags.js

**Summary**
This is tiny bugfix: 
* `save-assets` help still refers to screenshot but they are no longer saved.
https://github.com/GoogleChrome/lighthouse/pull/6066

cli(help): Fix save-assets help

---

lighthouse-core/scripts/build-report-for-autodeployment.js
lighthouse-core/scripts/cleanup-LHR-for-diff.js
lighthouse-core/test/config/default-config-test.js
lighthouse-core/test/results/artifacts/artifacts.json
lighthouse-core/test/results/sample_v2.json
lighthouse-viewer/test/viewer-test-pptr.js
proto/sample_v2_round_trip.json
types/artifacts.d.ts

I started writing a test that needed the `settings` on the artifacts that generate `sample_v2.json` and I noticed they weren't there. Did a little housecleaning on the easy to update artifacts (deleting `EventListeners` and `WebSQL`, finally adding `RobotsTxt` and `TapTargets`), though at some point (maybe for v5) we should still do a whole-hog update of the artifacts, trace, and devtools log.
At that point, surprisingly `sample_v2.json` still wasn't a valid `LH.Result`, which isn't super important but is kind of annoying. To fix we just had to
- not delete `lhr.configSettings.auditMode` in the cleanup script (just hardcoded to `true` to sidestep the travis issue mentioned in the comment in that file) and
- `Artifacts.MeasureEntry` (which makes up the `Timing` artifact) needed to not …

misc: update sample_v2 artifacts

---

lighthouse-core/audits/seo/link-text.js

I have added a couple of translations for the [Links Do Not Have Descriptive Text](https://developers.google.com/web/tools/lighthouse/audits/descriptive-link-text) audit in Spanish.
Note that in Spanish there is this symbol: `´`. People forget to write it so we may take into account these errors, let me know your opinion.
#5322 but in Spanish

core(seo): support spanish in link-text audit

---

lighthouse-core/audits/accessibility/axe-audit.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/audits/diagnostics.js
lighthouse-core/audits/metrics.js
lighthouse-core/audits/multi-check-audit.js
lighthouse-core/audits/predictive-perf.js
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/test/report/html/renderer/details-renderer-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json
types/audit-details.d.ts

**Summary**
All the data here is essentially used for debugging, so `debugData` seems fair.
`metrics` audit is probably the one exception where I'd expect folks to be explicitly relying on this for presentation, so I'm not sure what to do there. OTOH I also don't feel particularly strongly it needs to be renamed away from `diagnostics` since neither of them describe how it's being used in `metrics` :)
No issue was filed specifically, so it can't be closed yet! ;)
#7752

core: rename diagnostics to debugData

---

lighthouse-core/computed/critical-request-chains.js
lighthouse-core/test/computed/critical-request-chains-test.js

**Summary**
Fixes 302 iframes inside a page marked as critical requests
#6675

fix(audit): iframe with redirect shouldn't be marked as critical

---

lighthouse-core/gather/driver.js
lighthouse-core/test/gather/driver-test.js

**Summary**
Currently no `http` site seems to be auditable by the extension in Canary. AFAICT, Chrome has started to fire security state `insecure` events, but not over the websocket protocol for some reason, just chrome.debugger... 😕 
It *seems* like we should be able to just do the security check if the scheme is cryptographic and ignore it if it wasn't cryptographic? There are some other properties in the object that look promising (`displayedInsecureContentStyle === 'insecure'` maybe?), but want @Hoten 's take since he's our resident security state expert :)
**Event we get for bad ssl site**
**Event we get for http site**

core(driver): only fail security state if scheme is not cryptographic

---

lighthouse-core/audits/seo/hreflang.js
lighthouse-core/gather/gatherers/accessibility.js
package.json
yarn.lock

has two perf boosts: https://github.com/dequelabs/axe-core/releases/tag/v3.2.0
3.2.0 introduced rules [`aria-hidden-focus`](https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus) and [`form-field-multiple-labels`](https://dequeuniversity.com/rules/axe/3.2/form-field-multiple-labels) which are tagged wcag2a (which means we'll run them now).
The hidden-focus rule scares me a bit, implementation-wise, so I'm hesitant to include that in our results. The multiple-labels rule looks straightfoward.
@robdodson @marcysutton do yall have feelings on this?
fixes #7496
fixes #7355

deps: axe-core@3.2.2

---

lighthouse-core/config/default-config.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/test/results/sample_v2.json

**Summary**
SEO group titles and descriptions weren't translated!

i18n: update seo group titles and descriptions

---

lighthouse-core/report/html/report-styles.css

report(redesign): remove icons from non-pwa group headings

---

lighthouse-core/computed/page-dependency-graph.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/test/computed/page-dependency-graph-test.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js

**Summary**
Initiator information can fallback to `parser` in cases when elements were added inside a microtask/Promise chain. This hurts the fidelity of the lantern graph.
Even though async stacks are enabled by default in stable Chrome now in v8 (https://v8.dev/blog/v8-release-73), it doesn't apply to the initiator information we get from Chrome which still requires explicitly setting the async stack depth.
I would love to get this in for 5.0 as it enables a lot of performance accuracy improvements and better attribution for bootup-time/third-party-web
fixes #5494 
closes #3375

core: enable async stacks

---

lighthouse-core/gather/driver.js

This was the issue behind `/offline-ready?slow` failing in Smokerider with `service-worker.score = 0`.
The smoketest mimics a SW that takes 5s to register by delaying the request for the `.js` by 5s\*. Outgoing connections trip up LR w/ re: to fetching the manifest, as we saw before with long-polling, and this delay was causing the manifest fetch to fail.
By setting this timeout to x seconds, we are effectively saying "in LR, allow requests to take up to x seconds before giving up on the manifest". We don't want x to be too large, or we will get nothing (LR timeout). x shouldn't be too small either, but I'm not sure how to evaluate what it should be. 10 seconds seems closer than 3 seconds for a threshold where we start giving up on things.
It's unclear if any long request can cause this - …

clients(lr): increase Page.getAppManifest timeout to 10s

---

clients/lightrider/lightrider-entry.js
docs/recipes/gulp/gulpfile.js
docs/understanding-results.md
lighthouse-cli/test/cli/run-test.js
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-cli/test/smokehouse/perf/expectations.js
lighthouse-cli/test/smokehouse/perf/lantern-expectations.js
lighthouse-cli/test/smokehouse/redirects/expectations.js
lighthouse-cli/test/smokehouse/tricky-metrics/expectations.js
lighthouse-core/audits/audit.js
lighthouse-core/lib/proto-preprocessor.js
lighthouse-core/test/lib/manifest-parser-test.js
lighthouse-core/test/lib/proto-preprocessor-test.js
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
lighthouse-core/test/results/sample_v2.json
lighthouse-core/test/runner-test.js
lighthouse-core/test/scoring-test.js
proto/lighthouse-result.proto
proto/sample_v2_round_trip.json
types/audit.d.ts

part 2 of apparently 3 for #6199
Following #8343, this now renames the public `rawValue` on `LH.Audit.Result` to `numericValue`. We have very few places we rely on this except the smoke tests, so it's an easy change and a better place to bikeshed on `numericValue` and the public interface than the next PR :)
The last PR will be renaming the variable internal to audits/audit tests.

core: replace rawValue with numericValue in audit result

---

lighthouse-cli/cli-flags.js
lighthouse-cli/test/cli/bin-test.js
readme.md

cli: document that CSV is output to file

---

lighthouse-core/report/html/report-styles.css

**Summary**
Super minor fix for error state icon in metrics. It's not in our fixtures so here's the before/after.
**Before**
**After**

report: use border-box for psuedoelements

---

lighthouse-cli/bin.js

**Summary**
Adding small deprecation message for disableDeviceEmulation flag.
For more info chat with @patrickhulce 😄 
https://github.com/GoogleChrome/lighthouse/pull/8289#issuecomment-483693944

core: add deprecation message for disable-device-emulation flag

---

lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/test/report/html/renderer/report-renderer-test.js

report(redesign): order gauges - default, pwa, plugins

---

lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html

report(redesign): misc whitespace and color changes

---

.travis.yml
lighthouse-core/gather/connections/cri.js

**Summary**
Should fix travis and give us better error messages when Chrome crashes unexpectedly.
Previously we only handled connection errors after we reached our timeout when we should be handling them as soon as we try to connect in case Chrome crashes unexpectedly.
#7534

misc: handle connection errors even before the timeout

---

lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/report-renderer-test.js
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

#8185
sticky header w/ mini gauges
...appears when scrolling past score scale
...current category in view is underlined

report(redesign): add sticky scores header

---

lighthouse-core/lib/i18n/en-US.json
lighthouse-core/lib/lh-error.js
lighthouse-core/test/gather/driver-test.js

**Summary**
The error message for INSECURE_DOCUMENT_REQUEST, while correct, definitely takes the browser perspective on these issues rather than what I expect a user might think. When I hear "invalid credentials" as a user, I'm thinking there's some auth issue and it's a 403 or something. Really 90% of the time these are certificate issues and feels like we can rephrase a bit (source: made-up-stats.com).
It's not as big a deal here in `lh-error` where we give them the real message too compared to the extension, so I won't die on this hill if others disagree like I would over there :)
Came up in #8294 while seeing our copy of these messages over in the extension.

core: reword insecure error message

---

lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html

report(redesign): adjust score scale to match new design

---

build/build-dt-report-resources.js

Was tripped up by https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/report/html/report-styles.css#L738

clients(devtools): escape assets based on filetype

---

lighthouse-core/scripts/update-report-fixtures.js
lighthouse-core/test/report/proto-test.js
package.json
proto/lighthouse-result.proto
proto/sample_v2_round_trip.json
types/lhr.d.ts

recently we (I) have asked a few PRs to update a subset of example artifacts and then `sample_v2.json`. However if you try to run `yarn update:sample-artifacts` and then `yarn update:sample-json`, you'll notice there are a few errors preventing you from actually doing that :)
This PR
- fixes the `throttling-method` mismatch between the `-G` and the `-A` by switching `-G` to `devtools` to match `-A`
- adds the optional `gather` boolean to the proto `Timing` entry interface so that gatherer entries, when reimported with `-A`, will still result in a proto-able LHR at the end.
I'm not sure how often that will come up in practice for PSI, but it's possible, and with `false`/`undefined` as the default, it's zero overhead when there are no `gather` props (as there aren't in the current …

core: fix sample_v2 generation, proto errors

---

lighthouse-core/config/config.js
types/config.d.ts

We missed this simplification while doing the flags/settings unification stuff.
We needed `extraHeaders` to be a more specific type for configJson settings at some point, but it's now the same type as on the base `SharedFlagsSettings`, so `LH.Config.Json['settings']` can just be `SharedFlagsSettings`, as you'd pretty much expect.

misc: simplify LH.Config settings types

---

lighthouse-core/report/html/templates.html

#8185
Tested in Safari and FF. Not sure what the root issue was, but `position: relative` is all that was needed.

report(redesign): fix browser compatability issues

---

lighthouse-core/audits/font-display.js
lighthouse-core/test/audits/font-display-test.js

**Summary**
Apparently `/*# sourceURL=custom-url.css */` sets the `sourceURL` in DevTools to whatever the attribute was, so we should handle that case.
fixes #8534

core(font-display): do not use invalid sourceURLs

---

lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html

report(redesign): various whitespace adjustments (DRAFT)

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/report/html/renderer/util-test.js
types/html-renderer.d.ts

Not sure if I can convince everyone we should make this change :) Note that it's contained entirely within the report renderer, so there will be no effect on core, PSI, etc.
In `prepareReportResult` we smoosh a few things to make report rendering easier, like writing a `LH.Audit.Result` to the relevant `LH.Result.AuditRef` and, most recently, writing `LH.ReportResult.StackPackDescription` to the relevant `LH.Audit.Result`.
This PR makes it so *both* `LH.Audit.Result` and `LH.ReportResult.StackPackDescription` are written to the auditRef.
On the con side: it makes a certain amount of sense to match stack packs to auditResults as they have a 1:1 match, while there may be multiple auditRefs to a single audit (and thus a stack pack).
*However*:
- we should be minimizing and isolating the …

report: augment auditRef, not result, with stackPack ref

---

lighthouse-core/report/html/report-styles.css

report(redesign): hide sparkline in mobile

---

lighthouse-core/lib/i18n/en-US.json
lighthouse-core/lib/i18n/i18n.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

report(redesign): remove units from table columns

---

lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/renderer/snippet-renderer.js
lighthouse-core/report/html/templates.html

**Summary**
Caught by common-typos again.  And we would've gotten away with it too!
Fixing seperately in g3 for :hourglass: sake.

misc(chore): Common Typos

---

lighthouse-core/computed/resource-summary.js
lighthouse-core/test/computed/resource-summary-test.js
types/budget.d.ts

**Summary**
#8675, #8427, #8709, #8708,#8522, #8539

lightwallet: add 'computed/resource-summary'

---

lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/audits/font-display.js
lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

I noticed this blob url in our caching audit.
Doesn't make much sense. :)

core: filter out blob urls more often

---

lighthouse-core/config/budget.js
lighthouse-core/test/config/budget-test.js
lighthouse-core/test/config/config-test.js

@khempenius @patrickhulce 
This is my proposal for slightly stricter checking of the budgets file, primarily by assuming nothing about the type when it comes into `budget.js` so that we can get a little more verification by the compiler that we're checking the types well.
There are also a few places where the type checks have been tightened and some more tests have been added.
Even though this now returns a totally new budget object instead of just validating in place, it does have the same issue as in #8675 where *in practice* it's just validating in place because it throws on any input that isn't valid. Renaming to reflect that as suggested in https://github.com/GoogleChrome/lighthouse/pull/8675#discussion_r279401765 makes a lot of sense to me, though not creating the object on the fly …

core(lightwallet): stricter verification of budget types

---

lighthouse-core/lib/network-request.js
lighthouse-core/test/lib/network-request-test.js

This reverts commit ca1731aba7df31b16f68abc0de23f9fffac38efd, which _may have_, _slightly_, _kinda_, messed up some performance data.  Or whatever, I mean you never know.

clients(lr): revert Lightrider timings applied to NetworkRequests

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/audits/metrics/max-potential-fid.js
lighthouse-core/config/default-config.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Promotes Max Potential FID to the spot of EIL, moves EIL to JSON only.
> @patrickhulce: oh we're def making that happen for v5? 😀
> @paulirish: ya
It's difficult to analyze our thresholds because the HTTPArchive data we have on max potential FID will all by impacted by the missing microtask data bug (see #8379), but MPFID differentiates **MUCH* better than than EIL, they feel about right, and its still not a scored metric anyway...
**Ventiles**
```sql
SELECT
APPROX_QUANTILES(CAST(JSON_EXTRACT_SCALAR(report, '$.audits.max-potential-fid.rawValue') as FLOAT64),
20) as mpfid,
APPROX_QUANTILES(CAST(JSON_EXTRACT_SCALAR(report, '$.audits.estimated-input-latency.rawValue') as FLOAT64),
20) as eil
FROM
httparchive.lighthouse.2019_03_01_mobile
```
picks up the …

core: replace EIL with MP-FID

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/report/html/renderer/category-renderer-test.js

lightwallet: Use gray circles & font for informative audits

---

lighthouse-core/scripts/update-report-fixtures.js
lighthouse-core/test/results/artifacts/artifacts.json

#8427 manually added a budget to the sample artifacts. This PR changes `update-report-fixtures.js` to add a budget to the run so that it will always be in the sample artifacts when it's updated in the future.
Originally discussed in https://github.com/GoogleChrome/lighthouse/pull/8427#discussion_r277925455.
I just copied the budget added in #8427. The property order changes in the `artifacts.json` file because this is the order that `budget.js` initializes things.

core(lightwallet): add budget to sample artifacts config

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
lighthouse-core/audits/byte-efficiency/unminified-css.js
lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
lighthouse-core/audits/byte-efficiency/uses-webp-images.js
lighthouse-core/audits/metrics/estimated-input-latency.js
lighthouse-core/audits/metrics/first-cpu-idle.js
lighthouse-core/audits/metrics/first-meaningful-paint.js
lighthouse-core/audits/metrics/max-potential-fid.js
lighthouse-core/audits/seo/canonical.js
lighthouse-core/audits/seo/font-size.js
lighthouse-core/audits/seo/is-crawlable.js
lighthouse-core/audits/seo/tap-targets.js
lighthouse-core/audits/viewport.js
lighthouse-core/computed/viewport-meta.js
lighthouse-core/runner.js
lighthouse-core/test/computed/viewport-meta-test.js
lighthouse-core/test/fixtures/artifacts/alphabet-artifacts/artifacts.json
lighthouse-core/test/runner-test.js

**Summary**
One more breaking change I want to get in we discussed in the meeting that I misunderstood and thought was already on someone's plate :) 
**an audit can only use its `requiredArtifacts`**
With plugins it feels like folks aren't going to remember to use `requiredArtifacts` and if we ever want to enforce it, seems like we need to do it now.
This also fixes the dozen or so audits that were cheating :)

core(runner): audits can only use requiredArtifacts

---

lighthouse-core/lib/rect-helpers.js
lighthouse-core/lib/tappable-rects.js

**Summary**
- we renamed `getBoundingRectWithMinimimSize` to `getBoundingRectWithPadding` but the arg was still called `minimumSize`
- `getBoundingRect` can just call through to `getBoundingRectWithPadding` instead of having its own logic

core(rect-helpers): make getBoundingRect take an array of rectangles

---

proto/sample_v2_round_trip.json

just ran `yarn update:sample-json` on master and this is the diff i got. 
curious if everyone else has the same changes?

misc: fix roundtrip

---

package.json
proto/sample_v2_round_trip.json
proto/scripts/json_roundtrip_via_proto.py
readme.md

kind of a follow up to #8815
This
- adds a note to our readme that if you're going to be touching audits you'll likely need protobuf installed (so that `yarn update:sample-json` can run successfully)
- adds a more explicit error message if `yarn update:sample-json` fails on the proto step to install protobuf
- trims trailing whitespace from `proto/sample_v2_round_trip.json`. We've had a decent amount of churn from PRs that have needed to manually edit the file and have had whitespace automatically (or manually) trimmed. Hopefully this reduces future noise

misc(proto): remove trailing whitespace; add contributing messages

---

lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/report/html/renderer/details-renderer-test.js
lighthouse-core/test/report/html/renderer/util-test.js
lighthouse-viewer/app/src/lighthouse-report-viewer.js

fixes #8598
In addition to the `diagnostic` -> `debug` update that needed to be done, #8299 also meant we needed to update the <5.0 filmstrip screenshots to be able to render in the report.
Tested LHRs back to 3.1, everything is 👍 .
*However*: turns out even the 3.1 viewer isn't compatible with 3.0 LHRs because of the i18n switch. Not sure what we want to do about that, though at least 5.0 isn't a regression on this front :)
https://googlechrome.github.io/lighthouse/viewer/?gist=86d005fa4297bdefacd01b7228ab47fa

report: make v5 renderer compatible with v3 and v4 LHRs

---

lighthouse-cli/test/smokehouse/perf/expectations.js
lighthouse-cli/test/smokehouse/perf/lantern-expectations.js
lighthouse-cli/test/smokehouse/tricky-metrics/expectations.js

**Summary**
Converts some smoke metric assertions to assert on numericValue instead of just score. Some folks find this more readable as to the intention of the smoke test (https://github.com/GoogleChrome/lighthouse/pull/8379#issuecomment-488563344), others feel that there's no harm in including both (https://github.com/GoogleChrome/lighthouse/pull/8805#discussion_r280561086).

 tests: convert smoke metric assertions to numericValue

---

package.json

Prevents churn from unintended changes caused by version differences. See https://github.com/GoogleChrome/lighthouse/pull/8857#discussion_r281004034

misc(proto): assert libprotoc version

---

lighthouse-core/test/report/proto-test.js
package.json

follow up to #8863 and https://github.com/GoogleChrome/lighthouse/pull/8857#discussion_r281034929
Something was fixed between protobuf 3.6.1 and 3.7.1 that handled the `details.summary` type when the value was just an empty `{}`. 3.6.1 round tripped it as `null`, 3.7.1 correctly round trips it as `{}`.
The round trip test wasn't catching the issue because `{}` was the `summary` expectation and `{}` matches basically everything with `toMatchObject`. The round trip is good enough for audit results now that we can just do the deep, strict `toEqual` instead.

misc(proto): require protobuf 3.7.1, add stricter audit details test

---

lighthouse-core/scripts/assert-golden-lhr-unchanged.sh
lighthouse-core/scripts/update-report-fixtures.js
lighthouse-core/test/report/html/renderer/report-renderer-test.js
lighthouse-core/test/results/sample-config.js
lighthouse-core/test/results/sample_v2.json
package.json
proto/sample_v2_round_trip.json

#8427 added a budget to the sample artifacts, but because the `-A` step in `yarn update:sample-json` was run without the same config, the budget didn't make its way into the golden `sample_v2.json`.
This PR *actually* solves the original problem and gets a budget all the way into the final JSON :)
This will make things like #8708 easier to review because it'll actually be in the deployed report.
I just picked budget numbers. Happy to haggle.

tests(lightwallet): add budget to golden LHR

---

lighthouse-core/report/html/templates.html

**Summary**
Removes na-line from when gauge has optimized + one other badge.
old | new
fixes: #8856

report: no na-line with single badge

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

report(redesign): don't init sticky header features for single category reports

---

lighthouse-core/report/html/report-styles.css

**Summary**
* Remove metrics horizontal padding
* Set group headers explicitly to font-weight 700 (bold -> 700 is a no-op)

report(redesign): metrics padding, font weights

---

docs/plugins.md

Full name is currently "Publisher Ads Audits for Lighthouse", but the "for Lighthouse" bit seems redundant here. Also changed repository name.

docs: rename Google AdSpeed Insights to Publisher Ads Audits

---

lighthouse-cli/test/smokehouse/perf/perf-config.js
lighthouse-core/config/budget.js
lighthouse-core/test/results/sample-config.js
lighthouse-core/test/results/sample_v2.json
types/budget.d.ts

metric timing isn't actually budgetable yet, but we shouldn't tell folks that EIL will be budgetable.

core(performance-budget): add MP-FID as budget metric

---

lighthouse-core/config/budget.js
lighthouse-core/test/config/budget-test.js

core(budget): throw error on duplicate budget types

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

Resolves https://github.com/GoogleChrome/lighthouse/issues/8955

report: hide 3rd party filter checkbox if all rows are 3rd party

---

readme.md

Was excited with the new release of budgets within lighthouse. I added a new tool that uses Docker to create an image with chrome and lighthouse that allows developers to easily set budgets.

docs(readme): add performance-budgets to related projects

---

.travis.yml

fixes #2455
according to https://github.com/GoogleChrome/lighthouse/issues/2455#issuecomment-448001733, this is all that's needed to fix :)
I left the `package.json` entry and `lighthouse-core/scripts/compile-against-devtools.sh`, but I can also delete those if we don't plan on running them ever again

tests: remove compile-devtools on travis

---

lighthouse-core/scripts/roll-to-devtools.sh

b/c I keep forgetting to do it myself.

client(devtools): update version in tests on lh roll

---

lighthouse-core/lib/minify-devtoolslog.js
lighthouse-core/lib/minify-trace.js
lighthouse-core/scripts/lantern/minify-devtoolslog.js
lighthouse-core/scripts/lantern/minify-trace.js
lighthouse-core/test/lib/minify-devtoolslog-test.js
lighthouse-core/test/lib/minify-trace-test.js

**Summary**
Our trace minification logic got out of sync with some of our lantern improvements of the past few months. This PR fixes that, refactors it to a lib, and adds some tests while we're at it so it won't get out of sync again.
closes #8949

misc: update minify trace logic to date

---

lighthouse-cli/test/smokehouse/a11y/expectations.js
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/audits/accessibility/axe-audit.js
lighthouse-core/audits/seo/tap-targets.js
lighthouse-core/gather/gatherers/accessibility.js
lighthouse-core/gather/gatherers/seo/tap-targets.js
lighthouse-core/lib/page-functions.js
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/lib/page-functions-test.js
lighthouse-core/test/results/artifacts/artifacts.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json
types/artifacts.d.ts
types/audit-details.d.ts

**Summary**
Collect a human-readable title for each node and display it above the snippet.
https://github.com/GoogleChrome/lighthouse/issues/6683

core(report): show nodeLabel for DOM nodes in addition to snippet

---

lighthouse-core/report/html/renderer/psi.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
lighthouse-core/test/report/html/renderer/pwa-category-renderer-test.js
lighthouse-core/test/report/html/renderer/report-renderer-test.js
types/html-renderer.d.ts

`Util.prepareReportResult` smooshes audit results onto audit refs, but it also creates a bonus array of the report categories via `Object.values()`. We barely use these and [we all agree they're technical debt](https://github.com/GoogleChrome/lighthouse/blob/0b96e7af1a73e34e84b6a17e5a69f1d77a12698a/lighthouse-core/report/html/renderer/util.js#L55), so this is an easy removal.
As a bonus, this PR clears up all the many places we're calling `.find()` on that array to find a particular category, when the original `categories` is already indexed by category id :)
(noticed while cleaning up `prepareReportResult` in #8822, but punted until after I/O)

misc: remove unneeded reportCategories from LH.ReportResult

---

lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/stack-collector.js
lighthouse-core/test/gather/gather-runner-test.js
types/gatherer.d.ts

This is a refactor of `gather-runner.js` to
1) more clearly say what it's doing. The big outline at the top shouldn't be necessary; you should be able to just read `run()` (and now `runPass()`) to get an overview. `GatherRunner.beforePass`, `pass`, and `afterPass` now *only* call those methods on gatherers and it's a lot easier to see where things like recording a trace starts and stops.
2) make it easier to handle error cases. The code should be able to express what we're trying to do: at certain points (as the page is loading, after the page is done, between passes, etc) we need to check for errors, and then depending on the type of error take one of several actions (continue (allowing what gatherers can run to run), return error artifacts, don't run any more passes, cancel the entire …

core: refactor gather-runner

---

clients/lightrider/lightrider-entry.js
lighthouse-core/lib/asset-saver.js

This enables logging from PSI.
Maybe we should log all the artifacts too?
Tests awaiting feedback.
Note: this PR is building on [this](https://groups.google.com/a/google.com/forum/#!searchin/lightrider-eng/assets%7Csort:date/lightrider-eng/GZneqL21Kas/qtfhkVdDBgAJ) (Googlers only).

clients(lr): insert assets in lhr for logging purposes

---

docs/throttling.md
lighthouse-core/gather/gather-runner.js
lighthouse-core/runner.js

Looked back at the blame, was interested to see if these steps were named differently before.
Evaluating: https://github.com/GoogleChrome/lighthouse/blame/558a26f8661565caebcbba085b26bf028a89c283/lighthouse-core/runner.js#L94
Retrieving: https://github.com/GoogleChrome/lighthouse/blame/2a4d99c93794b883c70acbe24c332aa658e3a455/lighthouse-core/gather/gather-runner.js#L149
The answer is no :)

core(logging): change log messages for gathering and trace retrieval

---

lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
lighthouse-core/gather/gatherers/image-elements.js
lighthouse-core/test/audits/byte-efficiency/uses-responsive-images-test.js

**Summary**
We previously had some broken logic to address spritesheets in CSS for our responsive images but it has several flaws. I think we should just drop it and ignore CSS background images in our responsive image audit.
Here's why:
1. It didn't work (#8927). This one is obviously fixable but I don't think we should for the other reasons below :)
6. Doing responsive images in CSS is far more difficult and typically less impactful than responsive images in HTML. i.e. the opportunity to effort ratio is much lower here than other areas we should be wanting to spend time fixing things.
7.  A false negative is better than a false positive.
4. It fails to account for additional usages of the sprites that might be hidden on interaction (thought to be original cause of #8927).
5. It …

core(image-elements): drop spritesheet logic

---

lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-core/scripts/build-report-for-autodeployment.js

renderer: fix word break issue for display text, move metric disclaimer

---

lighthouse-core/report/html/report-styles.css

report(redesign): two rows for filmstrip on mobile

---

readme.md

**Summary**
This PR adds the link to [lighthouse-plugin-field-performance](https://github.com/treosh/lighthouse-plugin-field-performance). 
It also defines a new category in README, since I'm not sure where to add it, and according to the [npm search](https://www.npmjs.com/search?q=lighthouse+plugin) this is the first Lighthouse plugin ([pub-ads-lighthouse-plugin](https://github.com/googleads/pub-ads-lighthouse-plugin) is not published yet).
I hope that in the future, this category will contain more plugins, and possibly stack-packs. 
**Quick plugin overview**

docs(readme): add lighthouse-plugin-field-performance

---

lighthouse-core/test/report/html/renderer/category-renderer-test.js
lighthouse-core/test/report/proto-test.js
lighthouse-core/test/results/artifacts/artifacts.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Update out of date a11y data. Thought it might be related to https://github.com/GoogleChrome/lighthouse/pull/8823, but that PR did update the the artifacts – not sure what changes these are.
Also, when running `npm run update:sample-json` on master you get the `summary: null` sample change, which broke the proto tests. Some of the tests already had a `beforeAll` that fixed that, so moved that beforeAll to be top-level.

tests: update a11y artifacts

---

docs/plugins.md

Followup to #9049.. linking here will be useful for prospective plugin authors :)
--------
Also...  
@alekseykulikov @denar90 I was hoping to get some feedback from you guys on writing a plugin.. It looks like there were some rough edges and I think we could improve docs and perhaps some APIs to make it more straightforward for the next plugin :)
What did you notice? What was annoying? What was hard to figure out? What could we document better? :)

docs(plugins): add link to field-performance plugin

---

lighthouse-core/config/default-config.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/test/gather/driver-test.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js

Reverts GoogleChrome/lighthouse#8625
will need to be rearranged to account for #8964

misc(fix master): tmp revert of scroll position in #8625

---

lighthouse-core/report/html/report-styles.css
lighthouse-core/scripts/roll-to-devtools.sh

The text score (eg "69") inside the gauge has had a slightly odd position. 
Now its position is exactly in the half, due to a line-height: 0;
And the font-size is dynamically determined based off the circle size.

report: make gauge font size and positioning dynamic

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js

This was disabled here: #2437
Let's see what happens in Travis these days.
fixes #2423

tests(smoke): re-enable dialog prompt

---

lighthouse-core/lib/page-functions.js

this makes it ~20% faster.
to benchmark...
1. go to https://en.wikipedia.org/w/index.php?title=List_of_2017_albums&oldid=881381189
1. evaluate the getNodePath function
1. evaluate this:
```js
els = Array.from(document.querySelectorAll('*')); 
console.time('hi'); 
els.forEach(getNodePath); 
console.timeEnd('hi');
```

core(perf): speed up getNodePath

---

lighthouse-core/runner.js

**Summary**
PerformanceEntries in Lightrider (and the extension) had no names and no entryTypes.  This manifested as a 0 `timing.total` in the API as well.  
@brendankenny found that browser PerformanceEntry objects do not spread, but in Node they do b/c of the marky lib.  So, simple fix to explicitly call out the `name` and `entryType` fields when parsing the entries.  This will also populate the missing `lh:runner:run` entry to fill in `timing.total`.
fixes: #8638

core(runner): fix missing timing properties in the browser

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

report: show fireworks only if all core categories score 100

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

See https://github.com/GoogleChrome/lighthouse/issues/9019#issuecomment-494961806

report: show metric descriptions by default when errors exist

---

lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/report-renderer-test.js
lighthouse-viewer/tsconfig.json
package.json
yarn.lock

devtools: enable sticky header, top bar, and report ui features

---

lighthouse-core/report/html/renderer/report-ui-features.js

Currently, if DevTools is using the light theme and the OS is configured to use dark, our media query check causes the report to be dark. Nothing else in DevTools uses a similar media query, so perhaps we should skip this feature for consistency.

devtools: do not query system preferences for dark mode

---

lighthouse-core/scripts/release/prepare-commit.sh

This matches expectation in `lighthouse-core/scripts/release/prepare-package.sh`.

misc: release script should commit with format vx.y.z

---

package.json
yarn.lock

bundlesize has been having a bunch of issues in CI lately, and now there's a moderate security alert in one of its deps, so let's try bumping it to latest.
Unfortunately it brings in a rather heavyweight dep itself in a native brotli encoding library, but development seems to be picking back up again (https://github.com/siddharthkp/bundlesize/issues/306) and that'll soon be optional if the node version has native brotli support.
Also added budgets for the other bundles as they vary quite a bit in size due to things included or not included in them.

deps: update bundlesize, add more budgets

---

lighthouse-core/lib/manifest-parser.js
lighthouse-core/test/lib/manifest-parser-test.js

**Summary**
A manifest can be fetched over a `blob:` URL but all of its URLs will be invalid. Handle the case where we have invalid URLs and add a toplevel manifest warning when it's bloby
closes #9087

core(manifest-parser): handle blob manifests

---

readme.md

**Summary**
Adds the Gimbal integration to the readme

docs(readme): Add gimbal integration

---

readme.md

**Summary**
Noticed after #9083 that our related projects list wasn't alphabetized like our other integration lists.

docs(readme): alphabetize related projects

---

lighthouse-cli/cli-flags.js
lighthouse-cli/test/cli/cli-flags-test.js
lighthouse-cli/test/fixtures/cli-flags-path.json
lighthouse-cli/test/fixtures/cli-settings-path.json
readme.md

**Summary**
In order to easily accept an LH settings object over in Lighthouse CI, we need a way to easily passthrough the object. This can be done with config today but you miss out on some nice features like being able to use `--budgets-path`, set the `--output-path`, etc. 
This is a low-cost way to enable consumers of the LH CLI that run in a child process programmatic access to all our CLI flags without manually (and error-pronely) constructing an argument list.

core(cli): accept flags from path

---

yarn.lock

so I stop getting security alerts :) bonus: dedupe to one version.
https://www.npmjs.com/advisories/813

deps: bump transitive dep js-yaml

---

lighthouse-cli/test/smokehouse/error-config.js
lighthouse-cli/test/smokehouse/error-expectations.js
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-cli/test/smokehouse/smokehouse-report.js
lighthouse-cli/test/smokehouse/smokehouse.js
lighthouse-core/lib/asset-saver.js
lighthouse-core/runner.js
lighthouse-core/scripts/update-report-fixtures.js
types/smokehouse.d.ts

follow up to #9121 and part of the discussion from #8865. Adds two additional checks to smokehouse:
- if Lighthouse exits with a non-zero exit code the lhr must have a `runtimeError` (or if there's a `runtimeError` it must have had a non-zero exit code). This just double checks the change in https://github.com/GoogleChrome/lighthouse/commit/ff4f486298b5ac1db583a85bfc8a45c9689de5fb#diff-8035764042a5861297234f1e1b922ca7R221 (and should always be 👍)
- if there's a `runtimeError` in the run's LHR there *must* be a `runtimeError` in the expectations (slightly more strict than usual where something left out of the expectations isn't tested). We're asking everyone to keep an eye on `runtimeError` to spot problems, so our tests should be expecting them if one is in there :)
Since we weren't …

tests(smokehouse): always assert lhr.runtimeError

---

lighthouse-core/config/default-config.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/test/gather/driver-test.js
lighthouse-core/test/gather/fake-driver.js
lighthouse-core/test/gather/gather-runner-test.js

Reland of #8625 (reverted in #9059)

core(gather-runner): always reset scroll position

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/lib/page-functions.js
lighthouse-core/test/lib/page-functions-test.js

**Summary**
This PR fixes the  #9048 issue .
It is a bug fix.

core(page-functions): don't try to clone a ShadowRoot

---

lighthouse-core/report/html/report-styles.css

I ran this to determine what variables are unused (I verified each):
```
echo 'text-font-family
monospace-font-family
body-background-color
body-text-color
body-font-size
body-line-height
subheader-font-size
subheader-line-height
subheader-color
header-bg-color
header-font-size
header-line-height
title-font-size
title-line-height
caption-font-size
caption-line-height
default-padding
section-padding
section-indent
audit-group-indent
audit-item-gap
audit-indent
text-indent
expandable-indent
secondary-text-color
informative-color
medium-75-gray
medium-50-gray
medium-100-gray
warning-color
report-secondary-border-color
metric-timeline-rule-color
display-value-gray
report-width
report-min-width
report-width-half
report-header-height
report-header-color
navitem-font-size
navitem-line-height …
```

report: remove unused css vars

---

lighthouse-core/audits/network-requests.js
lighthouse-core/audits/performance-budget.js
lighthouse-core/audits/resource-summary.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/lib/i18n/i18n.js
lighthouse-core/test/results/sample_v2.json

**Summary**
Noticed this when snooping around for i18n stuff.
fixes: #9126

i18n: perf-budget and res-summary column headers

---

readme.md

**Summary**
Adds [`lighthouse-persist`](https://github.com/foo-software/lighthouse-persist) to the "Related Projects" section. `lighthouse-persist` is an open-source project that runs Lighthouse, provides result data and uploads an HTML report to a user's AWS S3 account.

docs(readme): related project: lighthouse-persist

---

lighthouse-core/report/html/templates.html

report: make tools menu focus-able

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/report-styles.css

report: only print light theme

---

lighthouse-core/report/html/renderer/pwa-category-renderer.js
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/pwa-category-renderer-test.js

fixes #9139
SVG elements in a `<defs>` block need to have globally unique IDs when trying to reference them in a `<use>` or as a fill or you're going to have a bad time as styling gets more complicated (see issue for details). Rather than getting rid of the references (growing the file size) or deduping the `<defs>` in the page (requiring significant rework of our "ask for a gauge, get a gauge element" interface for `renderScoreGauge` and the call chain that proceeds it), this PR adds a unique suffix to SVG IDs to make sure they don't collide (apparently a [common technique in some SVG libraries](https://stackoverflow.com/a/52269819/1084691)?).
I was going to add this onto `Util`, but we don't currently touch the DOM anywhere in there (and don't have jsdom set up for the tests for it), so …

report: ensure SVG elements in <defs> have unique ids

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/templates.html

alternative fix to #9167
Putting the sticky-header highlighter in the first gauge was a nice way to get it positioned correctly on load and a good transform origin to translate from on scroll, but it ends up a little weird since it's fundamentally part of the sticky header, not a single gauge.
Moving it out of the gauge, though, I couldn't find a way to get an absolutely positioned element to be aligned with the first gauge using flexbox. CSS grid makes this really easy, though, so switched the sticky header to using that.

report: position sticky-header highlighter with css grid

---

build/build-dt-report-resources.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/templates.html

Chromium changes: https://chromium-review.googlesource.com/c/chromium/src/+/1651062
See #9134

report(devtools): enable report features

---

lighthouse-core/report/html/report-styles.css

repro: click on the gauges in the topnav and expect a reasonable scroll position after click.
the 161px magic number was for the old report and is definitely dead now.

report: update permalink calculations for correct hash nav scroll position

---

readme.md

This is an example using lighthouse+jest to test not just a single network profile, but also to use puppeteer/cdp network emulation in conjunction with WPT network profiles to give more testing surface. I've been using this example the last six or so months to help some orgs get into the webperf side and move them to CI-based lighthouse (small steps).

docs(readme): related project: lighthouse-jest-example

---

readme.md

**Summary**
Older example with mocha doesn't work with current lighthouse version (older example is based on v1). This is the updated example repository link with a working example of lighthouse tests with mocha and chai.
**Is this a bugfix, feature, refactoring, build related change, etc?**
This is a documentation related change.
**Describe the need for this change**
Older example doesn't work since it is based on an older version of lighthouse and is no longer maintained.
None.

docs(readme): update lighthouse-mocha-example repo and description

---

lighthouse-core/audits/font-display.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/test/audits/font-display-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
In font-display, sometimes we just don't get the content of stylesheets for whatever reason. When this happens we falsely flag fonts as not having `font-display` values when they do, we just can't see them.
This PR inverts the logic in the audit to limit false positives. Instead of finding a set of passing URLs and failing everything else, we find the set of failing URLs directly. 
addresses user-facing concerns of #8493

core(font-display): limit false positives

---

lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/templates.html

Two easy fixes from aXe. Neither of these were getting good labels in a screen reader (including the actual `<label> for the metrics toggle, which had no text).
There was also a warning about tables with column headers but only empty cells in the column (https://dequeuniversity.com/rules/axe/3.2/th-has-data-cells), but from discussions I've found out there, AFAICT screen readers actually handle that case pretty well (e.g. VoiceOver says "empty"), so I don't think that actually needs fixing in the report.

report: add aria-labels to tools button and metric toggle

---

docs/understanding-results.md

**Summary**
Changes documentation based on issue raised (#8901)
Documentation bug
Updated the type for 'score'
fixes https://github.com/GoogleChrome/lighthouse/issues/8901

docs: change score type from 'string' to 'number'

---

lighthouse-core/test/gather/gather-runner-test.js

noticed a bunch of places in `gather-runner-test.js` using old and outdated arguments. `config` where they aren't needed, `url` instead of `requestedUrl`, etc. Cleans those up :)
In theory most of these aren't touched by the particular code path they pass through (hence passing tests), but makes for a very confusing copy/paste experience when trying to add new tests to the file.
Didn't touch async/await or anything to keep test changes easy to review.

tests: clean up crufty gather-runner tests

---

lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/test/gather/gather-runner-test.js

part of https://github.com/GoogleChrome/lighthouse/pull/8865#issuecomment-497507618
#9176 turned a load that ends up on a Chrome interstitial (e.g. `INSECURE_DOCUMENT_REQUEST`) into a runtime error to let the user know that the page they were testing had a major problem and was never actually loaded for the test. Currently, however, all the artifacts in that errored pass are returned as errors *except* the devtoolsLog and trace, which end up in a kind of weird state where they're actually tracing the load of the interstitial, not any useful page.
If the load ends up just going to the interstitial, the metrics all end up as `NO_NAVSTART` errors, but if there was somehow a navigation (e.g. a URL redirects to a page with a bad cert), you'll end up with some nice metrics for the interstitial …

core(gather-runner): don't save trace on pass with pageLoadError

---

lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html

ahhhh `report-styles.css`. isn't she beautiful (now)?
Don't squash - the first commit has a few renames I missed.

report: logically order css variables

---

docs/understanding-results.md

inspired by #9225.. here's a few more.
Didn't mention these properties: `lhr.environment`, `lhr.stackPacks`, `lhr.i18n`... but otherwise I believe the rest is up to date.

docs: update understanding-results.md

---

lighthouse-core/computed/trace-of-tab.js
lighthouse-core/lib/tracehouse/trace-processor.js
lighthouse-core/test/lib/tracehouse/trace-processor-test.js

**Summary**
One of the only changes made to tracium that needs to be ported back, part of the larger plan specified in #8956. 
#8956

core(tracehouse): allow missing FCP

---

lighthouse-core/report/html/renderer/crc-details-renderer.js
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js

1. reuse renderTextUrl instead of maintaining separate functionality inside the CRC. The pattern of passing in the `detailsRenderer` was first used in snippetRenderer, so I figured why not.
1. only text-decorate the linky part.

report: allow CRC to use renderTextUrl

---

readme.md

**Summary**
Adds [Exthouse](https://github.com/treosh/exthouse) - web extension analyzer that provides a report about web extension impact on web performance.
**Quick overview**:

docs(readme): add Exthouse - ext perf analyzer

---

package.json
yarn.lock

There's a security vulnerability in a transitive dep of commitizen which doesn't currently have a fixed version.
Buuuut, I don't think anyone here actually uses commitizen? And even if they do, all the docs I can find instruct that it should be installed globally, and we don't provide an npm script to access the version in node_modules, so not sure why we have it in here anyways.
If anyone does use it when writing commits, that use case isn't broken since `cz-customizable` and the `package.json` config entry are still around, so will work as is if you have `commitizen` installed globally.
(also, `yarn changelog` isn't affected by this as `commitizen` is only the *writing* side of things and `conventional-changelog` doesn't depend on it to read commit messages)

deps: remove commitizen as local dep

---

lighthouse-cli/test/smokehouse/error-config.js
lighthouse-cli/test/smokehouse/error-expectations.js
lighthouse-cli/test/smokehouse/smokehouse-report.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/runner.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/runner-test.js
types/artifacts.d.ts

*for some background, see conversation (and all the links from it) starting in https://github.com/GoogleChrome/lighthouse/pull/8865#issuecomment-497481383*
This proposal is to disconnect `pageLoadError` from artifact errors:
- add `PageLoadError` as a base artifact, populated if there was an error for that gathering run, otherwise null
- artifacts will be `undefined` in the pass that had the pageLoadError (just like all the artifacts from passes after that one, since we bail on gathering after a pageLoadError after #8866/#9121).
- as a result, audits that depend on those artifacts will move from `"Required x gatherer encountered an error"` errors to `"Required x gatherer did not run"` errors, which is arguably more correct (for artifacts collected in `afterPass`) and doesn't suggest to …

core(gather-runner): add PageLoadError base artifact

---

lighthouse-core/report/html/report-styles.css

https://chromium-review.googlesource.com/c/chromium/src/+/1651062/14/third_party/blink/renderer/devtools/front_end/audits/AuditsReportRenderer.js#b34

clients(devtools): unset overflow in print

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/third-party-summary.js
lighthouse-core/config/default-config.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/test/audits/third-party-summary-test.js
lighthouse-core/test/report/html/renderer/details-renderer-test.js
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
lighthouse-core/test/results/sample_v2.json
package.json
proto/sample_v2_round_trip.json
types/audit-details.d.ts
yarn.lock

**Summary**
Shines the light on third party impact!! Starting small with just a diagnostic audit that says "here are the ones you're using." I'd love to get more aggressive and in the users' face about alternatives/rankings/stats etc at some point, but this seems pretty decent start.
I'm using the `httparchive-no-stats` subset of the `third-party-web` dataset. It only includes the origins we actually observed in `HTTPArchive` and deletes the stats to cut down on bundle size impact (weighs in at 65KB compared to 202KB).
This is what it looks like for The Verge 😮 
(and another 10 more got cutoff)

new_audit: add third party entity summary

---

.gitignore

**Summary**
Add .idea folder into .gitignore file 
this change for WebStorm developer to ignore .idea folder in their local env.
For Webstorm user, the idea keep ask commit ./idea folder if not ignore it. same idea for `.vscode`

misc: add .idea folder to .gitignore file 

---

lighthouse-cli/test/fixtures/perf/perf-budgets/load-things.html
lighthouse-cli/test/smokehouse/perf/expectations.js

this smoke test wasn't reading the correct parameter off ArrayBuffer. nor was the class correct for the stylesheet to apply, so now that it does I updated the font expectation to comply
trivial and silly, i know

misc: fix typo in performance-budget smoke test

---

lighthouse-core/config/config.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/lib/lh-error.js
lighthouse-core/runner.js
lighthouse-core/test/config/config-test.js

as mentioned in https://github.com/GoogleChrome/lighthouse/pull/8865#pullrequestreview-243000692, when there is a pageLoadError you get a *ton* of logging, 2x every audit. #9236 moved that logging from "Required x gatherer encountered an error" to "Required x gatherer did not run", but you still get a lot of it.
This PR
- halves the logging (in the end, it didn't feel right to completely remove the warnings)
- the easiest way to do that was to i18n the "required x gatherer" error strings
- adds a new validation check to Config to separate the cases of `"a gatherer didn't run due to an error"` and `"a gatherer didn't run due to not being included in the config"`. Currently those cases are logged the exact same way, and not until the whole LH run has completed, which sucks if you just …

core(config): assert all audit requiredArtifacts will be gathered

---

lighthouse-core/runner.js
lighthouse-core/test/runner-test.js

when we're checking required artifacts before running an audit, we assert that the default trace exists if the audit needs a trace, but we only assert that the top-level `devtoolsLogs` artifact exists (it always does since it's a base artifact), not if any logs on it exist (they might not if there was a pageLoadError).
As a result, while nearly everyone in an error report will have `"Required {Artifact} gatherer did not run."` error string, a few audits that rely only on the devtoolsLog will have the lovely `"Cannot read property 'forEach' of undefined"` error string instead.
This adds a check for devtoolsLog just like the trace check.

misc(runner): add assertion for devtoolsLog as requiredArtifact

---

lighthouse-core/lib/file-namer.js

**Summary**
This fixes a [warning from lgtm](https://lgtm.com/projects/g/GoogleChrome/lighthouse/snapshot/1cdbc90f2af7cdb0c3f0894dac1fccdb44c1b30c/files/lighthouse-core/lib/file-namer.js?sort=name&dir=ASC&mode=heatmap)

misc: remove duplicate colon from regex

---

lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/i18n/i18n.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/lib/i18n/i18n-test.js

another tiny one, apologies for the spam :)
Right now when you hit a pageLoadError you get a logged message like
`GatherRunner:error lighthouse-core/lib/lh-error.js | pageLoadFailedInsecure # 0 https://expired.badssl.com/ +3ms`
This gets the full string for it.
fixes #8944

misc: localize logged GatherRunner error

---

lighthouse-core/report/html/report-styles.css

Before:
See #9270
After:
Note, I merged #9272 into this changeset b/c the grid styles here require that the score icon is always present and visible.

report: use css grid for metrics

---

lighthouse-core/report/html/renderer/crc-details-renderer.js
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
lighthouse-core/test/report/html/renderer/details-renderer-test.js
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

URLs in tables and in the critical request chain details are now clickable.
NYT: https://misc-hoten.surge.sh/www.nytimes.com_2019-06-17_11-40-25.report.html
See #5443

report: make urls clickable

---

lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/scripts/build-report-for-autodeployment.js

will aid in looking at some of @connorjclark's recent PRs.

misc(build): create error-y LHR for the deploy

---

lighthouse-core/report/html/templates.html

Did a quick overview of our SVGs to see if [@tomayac's advice on currentColor](https://web.dev/prefers-color-scheme/) might apply anywhere. I didn't find any, but I did find this small thing. The chevron stroke is handled in the CSS.

report: remove unnecessary attribute in svg

---

build/build-bundle.js
package.json
yarn.lock

source maps were broken b/c of https://github.com/browserify/brfs/pull/90
also made `debug` bundle mode more convenient.

deps(brfs): upgrade to 2.0.2 to resolve source map debug issue

---

lighthouse-core/index.js
lighthouse-core/runner.js
lighthouse-core/test/index-test.js
lighthouse-core/test/runner-test.js

fixes #8944
The `INVALID_URL` error wasn't getting localized because it's thrown before entering `Runner`, where errors are localized.
I thought about introducing i18n into this file, but it turns out we *also* check the url in `Runner` (when we normalize it), so this combines the checks there.
The downside is extra work gets done before checking the URL and throwing, but since it was already happening (e.g. in the CLI) after launching Chrome, etc, the only extra work is creating a `Config`, which is pretty fast.
In addition, none of the unit tests that were supposed to be checking this were checking it. They all asserted that *some* error was being thrown, and it just so happens that other errors were being thrown, so the assertions were passing 🤷‍♀ . Fixed those.

core: localize invalid URL error message

---

lighthouse-core/scripts/build-report-for-autodeployment.js

a few tweaks, based on user feedback:
1. put en-us first
1. get devtools report variants out of the way
1. more [smiles](http://shapecatcher.com/unicode/info/8995)

misc(build): adjust deployment filenames

---

lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
lighthouse-cli/test/smokehouse/error-expectations.js
lighthouse-cli/test/smokehouse/smokehouse-report.js

Extracted from https://github.com/GoogleChrome/lighthouse/pull/9248#discussion_r296821666
Proposal to change arrays in expectations to this behavior:
```
{
expected: []
}
passes: []
fails: literally anything else
------------------------------
{
expected: [1, 2, 3]
}
passes: [1, 2, 3]
fails: literally anything else
------------------------------
{
expected: {length: 2}
}
passes: [1, 2] [1, 3] [x, y] {length: 2}
fails: [] [1] [1, 2, 3]
------------------------------
{
expected: {0: 'a', 1: 'b'}
}
passes: ['a', 'b'] ['a', 'b', 'blah']
fails: ['b', 'a']
------------------------------
{
expected: {0: 'a', 1: 'b', length: 3}
}
passes: ['a', 'b', *]
fails: ['a', 'b']
```

tests(smokehouse): assert on expected array length

---

lighthouse-core/scripts/manual-chrome-launcher.js
package.json
yarn.lock

notable commits:
* `448a1d48` chrome-finder: Add support for MacOS Catalina (https://github.com/GoogleChrome/chrome-launcher/pull/149)
* `55b891bb` deps(is-wsl): add support for WSL 2; drop Node 6 (https://github.com/GoogleChrome/chrome-launcher/pull/152/)
fixes #9279

deps: chrome-launcher@0.11.1

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

report: show disabled checkbox when all/no urls are third-party

---

lighthouse-core/gather/gatherers/dobetterweb/domstats.js

fixes #8725
The issue was that domstats starts with a 0 as the max number of children seen as the base case, an empty `<body>` has 0 children (which isn't more than 0), and so `parentWithMostChildren` stayed as `null`.
Instead we start with a -1 so that there will always be at least `<body>` in there. Could have also gone with a `>=` check, but that changes it so `parentWithMostChildren` is the last one seen if there are ties, which would sort of be a breaking change. This seemed better (and more the original intent, I guess).

core(domstats): support an empty html body

---

lighthouse-cli/test/smokehouse/a11y/expectations.js
lighthouse-core/gather/gatherers/accessibility.js
package.json
yarn.lock

**Summary**
Updates axe-core to version just released [2019-07-08](https://github.com/dequelabs/axe-core/releases/tag/v3.3.0). 
Notable changes:
- [API](https://github.com/dequelabs/axe-core/commit/84094a1) for synchronous run might be interesting for us to look into since IIRC there was a lot of time spent in async control passing we don't really need. 
- Some big [perf wins](https://github.com/dequelabs/axe-core/commit/a84431a)
- A few new rules we might want to add audits for (aria-input-field-label, aria-toggle-field-label)
- Lots of bug fixes
closes https://github.com/GoogleChrome/lighthouse/issues/9337, see https://github.com/dequelabs/axe-core/issues/1597#issuecomment-509790954

deps: axe-core@3.3.0

---

clients/devtools-report-assets.js
lighthouse-core/scripts/roll-to-devtools.sh

Current canary errors when saving as HTML. Issue is with how DevTools is bundled. Read comments for more.
Associated chromium change: https://chromium-review.googlesource.com/c/chromium/src/+/1696348
Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=979131

clients(devtools): audits2 -> audits1 and defer reading resources

---

lighthouse-core/computed/network-analysis.js
lighthouse-core/config/config.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/lantern-trace-saver.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/runner.js
lighthouse-core/scripts/update-report-fixtures.js
lighthouse-viewer/app/src/lighthouse-report-viewer.js
package.json
types/externs.d.ts
yarn.lock

unblocks #9267, maybe others?
3.4 crashed on our code base due to out of control unionings. 3.5 introduced a limit to union construction, but the underlying error just morphed into "Expression produces a union type that is too complex to represent" :)
The main cause was https://github.com/microsoft/TypeScript/pull/30769, improving soundness of assigning to an object with enumerated keys (e.g. our artifacts object, where the error was occurring). 
The problem is that tsc doesn't have a notion of a type being a single member of a union (e.g. when looping over the artifact keys, inside the loop it sees the union of all artifact keys, not a single key within that union). So while that change improved soundness, our unsound (due to tsc's limitations, but, notably, still correct) assignments to …

deps: update to typescript 3.5.3

---

.travis.yml
package.json

thanks to @wardpeet and @patrickhulce for telling me about this flag :)
Trivial change to give a CI failure if any `yarn.lock` changes weren't committed (happened in #9267 but tests were green)

tests: run CI with a frozen yarn.lock

---

lighthouse-core/lib/i18n/README.md

@exterkamp deserves credit for writing this.
I've just spent some time reorganizing it and editing things.
Figured we'd just land this separate to keep the review separate from shane's great placeholders PR (#9114).

docs: add i18n overview & authoring documentation

---

lighthouse-core/audits/seo/font-size.js

1. Run LH on http://m.sands-style.com/interviews-features (mobile)
```
node lighthouse-cli http://www.sands-style.com/ --only-audits=font-size
```
Or via DevTools.
`font-size` will have an `Unknown` (10px).
It should not say `Unknown`.
I was curious when this audit resulted in `Unknown`, so I queried httparchive:
```sql
CREATE TEMP FUNCTION extractSources(itemsJson STRING)
RETURNS ARRAY<STRING>
LANGUAGE js AS """
let items = JSON.parse(itemsJson);
if (!Array.isArray(items)) return [];
return JSON.parse(itemsJson).map(x=>x.source);
"""; 
SELECT COUNTIF(source = 'Unknown') UNKNOWN,
COUNTIF(source = 'User Agent Stylesheet') USER_AGENT,
COUNTIF(source = 'dynamic') DYNAMIC,
COUNTIF(true) TOTAL
FROM (
SELECT source
FROM (
SELECT extractSources(JSON_EXTRACT(report, …
```

core(font-size): comment why source = Other happens

---

lighthouse-cli/test/fixtures/seo/seo-tester-styles.css
lighthouse-cli/test/fixtures/seo/seo-tester.html
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-core/audits/seo/font-size.js

split off of #9354
1) For inline styles, the stylesheet's startColumn was always being added to the rule's column. However, this is only valid if the stylesheet and the rule begin on the same line in the HTML.
2) For inline styles with a sourceURL magic comment, the line/column was relative to the HTML file. I've changed it to be relative to the beginning of the style tag, as if it were its own file.
3) Lines are 1-indexed, but columns are 0-indexed. All columns were off by one.
before:
after:
```
node lighthouse-cli/ http://misc-hoten.surge.sh/lh-ui-location-font-size/ --only-audits=font-size --view
```

audits(font-size): calculate accurate line/column for inline styles

---

lighthouse-core/lib/i18n/i18n.js
lighthouse-core/test/lib/i18n/i18n-test.js

**Summary**
Add test for a missing ICU replacement value when gettingFormatted.  Removed early exit from _preprocessMessageValues  and added a default so that when sending no replacement object the function will still fire.
fixes: #9383

tests(i18n): no ICU value given to preprocess

---

lighthouse-core/audits/network-server-latency.js
lighthouse-core/test/audits/network-server-latency-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
This fixes a typo for `network-server-latency`, which has currently `serverReponseTime` instead of `serverResponseTime` (and maybe cause bugs when trying to get some values out of the JSON).

core: fix serverResponseTime typo in network-server-latency

---

.travis.yml
lighthouse-core/test/lib/i18n/locales-test.js
yarn.lock

Node 12.6 is now calling `'mo'` deprecated and gives `'ro'` as the canonical version for me. `mo` is already an alias of `ro`, so that seems fine, but the canonical locale test needs to account for this or it will fail.
Also:
- adds Node 12 to travis testing
- updates yarn.lock to account for `is-wsl` change, missed due to a combo of #9267 and #9339 (chrome-launcher moved to `2.1.0` but `open` still requires `1.1.0`)

tests(i18n): update canonical locale test for node 12

---

docs/architecture.md
docs/understanding-results.md
docs/variability.md
readme.md

**Summary**
This PR fixes some typos as the followings:
- `were` -> `was` (docs/understanding-results.md)
- `mask` -> `masks` (docs/variability.md)
- `failing  audit` -> `failing audit` (docs/architecture.md)
N/A

docs: fix typo

---

lighthouse-core/lib/asset-saver.js
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/lib/lh-error.js
lighthouse-core/test/lib/asset-saver-test.js
lighthouse-core/test/runner-test.js

fixes #4984
> Internally [gatherer errors are] real Errors, so they get serialized as `{}` :( This will obviously be an issue as errors won't show up in the `-A` stage. Presumably there will still be errors when audits try to use those artifacts, just not the ones you'd want to tell what's going on.
> It would be nice to continue to use real Errors, so we should support saving and restoring errors in asset-saver if possible.
This is done through using a `JSON.stringify()` [replacer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter) and a `JSON.parse()` [reviver](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Using_the_reviver_parameter).
It would be possible to do the …

core: support saving and loading error artifacts

---

lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js

see https://github.com/GoogleChrome/lighthouse/issues/8409#issuecomment-485009237
> Since we ship to places we can't necessarily quickly update (e.g. DevTools), I wonder if we should have a LH test that fails if the database has * or >=X, and require it be corrected to <= some hardcoded version (presumably the latest available release), even if that version is still vulnerable.
>
> The theory would be: if a new, still vulnerable version of the library comes out after that LH release, then it's better to have a false negative (given that there's no fix available anyways and there are other sources (github, npm, greenkeeper, etc) that will warn folks) than it is to have up to 12 weeks of a false positive (if a new, non-vulnerable version comes out) which would annoy folks and encourage them …

tests(snyk): assert upper bounds

---

lighthouse-core/report/html/templates.html

**Summary**
Add role="heading" with aria-level="2" to the report category gauges so
screen readers can easily identify and navigate the report using headings.
Level 2 was chosen because [Accessibility Insights recommends against
multiple level 1 headings in the same section of a document][1].
***Screenshot of gauges in the devtools accessibility tree***
***Screenshot of NVDA Element List***
This meets the following WCAG 2.1 success criteria
1.3.1 Info and Relationships https://www.w3.org/WAI/WCAG21/quickref/#info-and-relationships
2.4.10 Section Headings https://www.w3.org/WAI/WCAG21/quickref/#section-headings
#7575
[1]: https://github.com/microsoft/accessibility-insights-web/blob/900c301e/src/content/adhoc/headings/guidance.tsx#L45-L54

report(accessibility): add heading role to report category gauges

---

lighthouse-core/scripts/build-report-for-autodeployment.js
now.json

trying this out to see if now deployment will work with a different directory than default (`dist/`) so they're all nested in `dist/now/`

misc: nest deployed-report directory

---

lighthouse-core/test/audits/seo/font-size-test.js

tests(font-size): assert on source

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/audits/metrics.js
lighthouse-core/audits/metrics/total-blocking-time.js
lighthouse-core/computed/metrics/lantern-total-blocking-time.js
lighthouse-core/computed/metrics/total-blocking-time.js
lighthouse-core/config/default-config.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
lighthouse-core/test/audits/metrics/total-blocking-time-test.js
lighthouse-core/test/computed/metrics/total-blocking-time-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

This PR cleans up Total Blocking Time code in lighthouse. It
- changes the name from CLQD -> TBT as decided by the [bikeshedding doc](https://docs.google.com/document/d/1SaYGOCy4_wEEoa0N_gNb1PyOxnZgSvuu_r52WhRYFKQ/edit#).
- Changes the definition of blocking time to be anything after first 50ms of a task, as opposed to anything before last 50ms. People [found](https://docs.google.com/a/google.com/document/d/1atjVa5eOuh1pGd0d5j3axDvj0jewN3FZZFESonnwu8A/edit?disco=AAAADQT1Gm8) the previous definition confusing, and this detail would change the value of the metric only by a maximum of 50ms, so the simplicity is worth it. 
- Has properly i18n-ed UI strings.

core(tbt): Clean up total blocking time code

---

lighthouse-cli/test/smokehouse/a11y/expectations.js

`yarn smoke a11y` fails in `color-contrast` on the Mac because the font size is different than Linux and the stricter expectations introduced in #8961 work on Linux :)
This loosens up the requirement, which is fine because this is just the explanation string, not what the audit was testing.

tests: relax contrast font size expectation

---

lighthouse-core/audits/seo/font-size.js
lighthouse-core/lib/i18n/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/audits/seo/font-size-test.js

report: fix explanation rendering

---

lighthouse-core/gather/gatherers/seo/font-size.js
lighthouse-core/test/gather/gatherers/seo/font-size-test.js

`Attributes` is a [type](https://github.com/GoogleChrome/lighthouse/blob/f968ee94ed539da4046c4e26e65fe3d2990a5554/types/artifacts.d.ts#L250) for `cssRule` in the `font-size` artifact.
The audit checks for it [here](https://github.com/GoogleChrome/lighthouse/blob/f968ee94ed539da4046c4e26e65fe3d2990a5554/lighthouse-core/audits/seo/font-size.js#L129).
However, the gatherer never returned a rule of type `Attributes`. Instead, it was returning no `cssRule` (that property is optional) - which was fine because the audit handles it in the same way.
First thought was to just remove `Attributes` from the type property. But then I saw it was pretty simple to change the gatherer to be correct.
But ... it doesn't really convey much more information - just makes it more explicit - so I could go either …

core(font-size): gather style declaration of type Attributes

---

lighthouse-core/audits/dobetterweb/appcache-manifest.js
lighthouse-core/audits/seo/canonical.js
lighthouse-core/lib/i18n/i18n.js
lighthouse-core/lib/i18n/locales.js
lighthouse-core/lib/i18n/swap-locale.js
lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-core/test/scripts/i18n/collect-strings-test.js

Follow up to #9114 
- renaming typedefs to align with CTC and LHL as defined in the [readme](https://github.com/GoogleChrome/lighthouse/blob/0cf90aa34708c539058e68c5692e838020419cd8/lighthouse-core/lib/i18n/README.md#terminology)
- fixing some placeholder `undefined` nonsense by tsc (https://github.com/GoogleChrome/lighthouse/pull/9114#discussion_r306576574)
- finishing up the suggestion from https://github.com/GoogleChrome/lighthouse/pull/8755#discussion_r280968989 and making sure all our instances of icu replacement values are typed as `Record<string, string|number>` since that's all we accept

i18n: align type names with docs

---

lighthouse-core/audits/seo/link-text.js

**Summary**
Add Portuguese translations for the [Links Do Not Have Descriptive Text](https://developers.google.com/web/tools/lighthouse/audits/descriptive-link-text)
Note that in Portuguese there is this symbol: ´. People forget to write it so we may take into account these errors, let me know your opinion.
feature, since adding new words to the test
Portuguese is one of the top 10 languages used on the internet [ref1](https://en.wikipedia.org/wiki/Languages_used_on_the_Internet)
[translated words for non-portuguese speakers](https://translate.google.com.br/#view=home&op=translate&sl=pt&tl=en&text=clique%20aqui%0Air%0Ain%C3%ADcio%0Ainicio%0Air%0Amais%0Amais%20informa%C3%A7%C3%A3o%0Amais%20informa%C3%A7%C3%B5es%0Aveja%20mais%0Amais)
#7547 #5322

core(seo): support portuguese in link-text audit

---

lighthouse-core/test/report/html/renderer/report-renderer-test.js

**Summary**
Add a test to run axe-core validation on the output of a sample report,
any violations are logged as the assert failure message.
Example Failure Output:
Axe-core is slow so I needed to bump the timeout to 10 seconds.

tests(report): add axe-core validation of report output

---

lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/test/audits/byte-efficiency/unused-css-rules-test.js

**Summary**
Bumping the allowable limit to 10KB of unused CSS per file per discussion in https://github.com/GoogleChrome/lighthouse/issues/9353#issue-466944871. Should have minimal impact on displayed results since the 8KB difference would be unlikely to significantly impact any metrics to appear in the first place.
closes https://github.com/GoogleChrome/lighthouse/issues/9353

core(unused-css): allow up to 10KB of unused CSS per file

---

lighthouse-cli/cli-flags.js
readme.md

**Summary**
Small doc tweak to fix #9209 by listing the valid categories in an example

doc(cli): list valid categories

---

.appveyor.yml

**Summary**
Just trying something out, appveyor builds have started failing ~50% of the time lately.

misc: retry cli tests up to 3 times in appveyor

---

package.json
yarn.lock

0.11.1 was opening an extra tab. Bump minimum required version to 0.11.2.
related: https://github.com/GoogleChrome/chrome-launcher/pull/162

deps(chrome-launcher): update to 0.11.2

---

lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/templates.html

This modifies UI in the topbar to
- Show a tooltip when the URL is hovered
- Truncate the URL from the end via CSS, based on available space
- Round Lighthouse icon in the topbar used to shrink due to flexbox, and disappear.  Now, it doesn't flex so it should maintain its size.
Screenshot: https://imgur.com/a/2DQ5RmV
Issue: https://github.com/GoogleChrome/lighthouse/issues/9142
Associated Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=971585

report(topbar): fix overflowing url

---

readme.md

Fix broken plugin example link

fix(link): Update broken plugin example link

---

lighthouse-core/report/html/renderer/dom.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-core/test/report/html/renderer/dom-test.js
lighthouse-core/test/report/html/renderer/util-test.js
lighthouse-core/test/scripts/i18n/collect-strings-test.js

duplicated markdown parsing in `dom.js` for the report and `collect-strings.js` for adding placeholders for ctc files (which will eventually be reconstituted and then passed through `dom.js` methods) is a little risky, so the first commit here makes them share a splitting implementation in `util.js`.
There are no changes to the collected locale strings or the existing `dom` and `collect-strings` unit tests.
...but then I couldn't resist making an interface that's easier to understand (no more mysterious empty string for `preambleText` but `undefined` for `linkText` and `linkHref`). This is isolated to the second commit, so if it seems excessive I can drop it :)

misc: share markdown parsing in collect-strings and the report

---

lighthouse-core/scripts/roll-to-devtools.sh

Trivial change. Using the current suggest command, the html file added in https://chromium-review.googlesource.com/c/chromium/src/+/1743411 is run as a test (when it's actually just a fixture).

clients(devtools): update test command to run only .js files

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/config/constants.js
lighthouse-core/config/lr-desktop-config.js
lighthouse-core/config/lr-mobile-config.js
lighthouse-core/test/results/artifacts/artifacts.json
lighthouse-core/test/results/sample_v2.json

**Summary**
This PR increases the default maxWaitForFcp to 30s while leaving it 15s in LR configs. The original reason we made the limit so low was to avoid timeouts in LR. My gut says this aggressive value in DevTools/CLI is what is causing such a strong uptick in NO_FCP reports. Anecdotally the last 3 filed issues were all pages that took ~20-25 seconds to first paint for me locally, not ones that didn't paint at all.

core(constants): increase default maxWaitForFcp

---

lighthouse-core/lib/i18n/locales.js

handy link I wanted to have even handier.

i18n: add link to cldr parentLocales

---

package.json
yarn.lock

[changelog](https://github.com/javan/details-element-polyfill/releases):
* Fix testing for support in hidden documents  (from adspeed team)
* Fix typo-induced error in Safari 9
* Fix that the toggle event incorrectly bubbled 
* Lower specificity of `<summary>` styles

deps: details-element-polyfill@2.4.0

---

lighthouse-core/audits/seo/canonical.js
lighthouse-core/audits/seo/font-size.js
lighthouse-core/audits/seo/hreflang.js
lighthouse-core/audits/seo/http-status-code.js
lighthouse-core/audits/seo/is-crawlable.js
lighthouse-core/audits/seo/link-text.js
lighthouse-core/audits/seo/manual/structured-data.js
lighthouse-core/audits/seo/meta-description.js
lighthouse-core/audits/seo/plugins.js
lighthouse-core/audits/seo/robots-txt.js
lighthouse-core/audits/seo/tap-targets.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Points "Learn more" links in SEO audits to relevant web.dev guides.
* `viewport.js` handled in #9539 
**Note**
The **robots.txt is not valid** audit didn't have a "Learn more" link, so I added one.

core(audits): Point SEO audit links to web.dev

---

build/build-viewer.js
lighthouse-viewer/app/src/main.js
package.json
yarn.lock

clients(viewer): remove polyfills

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/templates.html
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

**Summary**
This improves the accessibility of the report dropdown by adding ARIA attributes and interactive behavior in-line with the [WCAG menu button pattern][1], specifically the [navigation menu button][2].
***Screenshot of NVDA speech view + the dropdown***
***Screenshot of button accessibility tree***
***Screenshot of menu item accessibility tree***
***Gif of keyboard interactions***
This will meet WCAG success criteria [1.3.1 Info and Relationship][3] and [4.1.2 Name, Role, Value][4]
https://github.com/GoogleChrome/lighthouse/issues/9183
[1]: https://www.w3.org/TR/2019/NOTE-wai-aria-practices-1.1-20190207/#menubutton
[2]: https://www.w3.org/TR/2019/NOTE-wai-aria-practices-1.1-20190207/examples/menu-button/menu-button-links.html
[3]: …

report(accessibility): make dropdown match ARIA action menu button pattern

---

lighthouse-core/lib/proto-preprocessor.js
proto/sample_v2_round_trip.json

**Summary**
`channel` never made the roundtrip!  And 'lr' got lost in the process.

clients(proto): don't filter channel from configSettings

---

lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

**Summary**
[As requested][1], this change refactors the reports drop down into its own class because it has grown to support the ARIA action menu pattern in #9433.
The new DropDown class is responsible for UI interactions with the action button and menu, including keydown handlers on the document to close the drop down on `ESC`.
The ReportUIFeatures class is still responsible for performing actions when a user activates a link in the drop down menu.
#9433
[1]: https://github.com/GoogleChrome/lighthouse/pull/9433#pullrequestreview-275209725

report(refactor): Move drop down logic into a separate class

---

lighthouse-core/audits/seo/robots-txt.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json

**Summary**
Minor fix from translators.

i18n: capitalize robots.txt displayValue 

---

lighthouse-core/audits/uses-rel-preconnect.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Translators asked if this should be translated, and it shouldn't because they are technical terms and not really localizable.

i18n: add code spans to uses-rel-preconnect description

---

lighthouse-core/lib/i18n/i18n.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/lib/i18n/swap-locale-test.js
lighthouse-core/test/report/html/renderer/util-test.js

fixes part of #7238 (second bullet point)
**tl;dr** better Intl polyfill guard and switch our Util number formatters to use `Intl` methods. No change to ICU message formatters.
Our current polyfill relies only on browserify build ignoring `intl`, which means we're polyfilling even on node that has `full-icu`. But if we base it just on if `Intl` and (e.g.) `Intl.NumberFormat` are defined we won't get locales on `system-icu` or `small-icu` where those are defined but only (usually) a single locale is supported.
Instead, we can use the approach suggested by [`intl-locales-supported`](https://www.npmjs.com/package/intl-locales-supported) and check if all our needed locales are supported and polyfilling if not. If we take that literally, though, we'll still polyfill because for some reason …

core(i18n): improve Intl polyfill and use it in Util

---

lighthouse-cli/test/fixtures/badssl-iframe.html
lighthouse-cli/test/smokehouse/error-expectations.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/test/gather/gather-runner-test.js

**Summary**
Several folks have reported that it's unexpected/undesirable for LH to fail when iframes fail with an interstitial, this loosens our logic to only fail when the *mainRecord* fails with an interstitial. Our usual caveats about client-side/JS redirects not working will now apply here too.
fixes #9562

core(gather-runner): only fail for mainRecord interstitials

---

lighthouse-core/audits/accessibility/td-headers-attr.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Translators were confused by these titles, and looking into it, they don't seem to make sense.  This should be more accurate to the audit itself.
[Deque Link](https://dequeuniversity.com/rules/axe/3.2/td-headers-attr)

a11y: rewrite td-headers-attr titles

---

proto/lighthouse-result.proto

**Summary**
There are new, more strict proto linters now.  These hooks allow us to import easier.  And enforce the 80 char limit on our file here.

proto: update import hooks, obey line length

---

build/build-viewer.js
lighthouse-viewer/README.md
package.json
yarn.lock

**Summary**
I'm replacing uglify-es with terser to minify our viewer.js. Terser has been the successor to uglify-es as it's not actively maintained anymore.
Fixes #9558

chore(lighthouse-viewer): replace deprecated uglify-es with terser

---

yarn.lock

**Summary**
I've spent a few hours cleaning up all duplicates of yarn.lock to make this repo a little bite nicer and smaller.
Just kidding I used an awesome tool from atlassian called [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate). It automatically cleans up yarn.lock.

chore: deduplicate yarn.lock dependencies

---

yarn.lock

after syncing to #9600, when I run `yarn` locally I get these changes to the `yarn.lock` file. Maybe an artifact of the yarn-deduplicate tool?
The changes seem fine (they don't appear to be depended on by anything), but if others aren't seeing this in their local install I can dig in more to see why these came up.

misc: trim missed yarn.lock cruft

---

lighthouse-core/audits/third-party-summary.js
lighthouse-core/lib/i18n/i18n.js
lighthouse-core/lib/lh-error.js
lighthouse-core/test/lib/i18n/i18n-test.js
lighthouse-core/test/results/sample_v2.json

we have a check that all arguments in an ICU message have values passed into our i18n functions; this PR adds a check that all the values passed in have a place to be used in the ICU message. This is useful when strings change since we have no type checking that our localized strings match the values being passed in for replacement.
I was originally going to include this in #9570, but ran into a ton of errors in our unit tests. Turns out this is just because `LHError` always includes `errorCode` in the replacement values so you don't have to write `'NO_FCP'` three times just to get a `NO_FCP` error. I added a comment to remind the next person about `errorCode`.
This condition currently only happens in one place (the change in #9486 removing `itemCount`), but removing `itemCount` reveals a …

core(i18n): throw on excess placeholder replacement values

---

lighthouse-core/audits/accessibility/aria-required-children.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
More feedback from translators.  Rewriting aria-required-children titles, I found this title super confusing without some more explanation of it.  The translators got really confused since it becomes more like "Elements with MARKDOWN that require specific children MARKDOWNs, are present"
Hopefully this is more clear.
[web.dev link](https://web.dev/aria-required-children/)
[aria list, which requires children listitem (good example)](https://www.w3.org/TR/wai-aria-1.1/#list)

i18n: rewrite aria-required-children titles

---

lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
lighthouse-core/scripts/i18n/prune-obsolete-lhl-messages.js
lighthouse-core/test/scripts/i18n/bake-ctc-to-lhl-test.js

**Summary**
This fixes 2 issues:
1. tc/ adds more plural paths for other languages (1, # -expand to-> 1, #, zero, few, two, etc.) and when it does this it copies the placeholders, so multiple placeholders are copied. This change performs a global replace for ICU values to replace all instances of a placeholder.
2. The pruning script used `require` which does not reload a file if it is modified in the same process, which is what happens when you `collect-strings`.  So we need to reload it to pick up changes in the lhl from an import. (thanks @patrickhulce)

i18n: fix import scripts

---

lighthouse-core/report/html/report-styles.css

Removing fix from #7512: not needed anymore for stable Chrome.

report: remove PWA badge flicker workaround for Chrome

---

lighthouse-core/index.js
lighthouse-core/lib/i18n/i18n.js
lighthouse-core/test/lib/i18n/i18n-test.js

see [Audits Panel Localization Design](https://docs.google.com/document/d/1jnt3BqKB-4q3AE94UWFA0Gqspx8Sd_jivlB7gQMlmfk/edit)
This method enables us to "install" new locale strings into our i18n string lookup.
Unrelated, but I added a few more tests to getFormatted as a driveby.

i18n: add registerLocaleData() method

---

lighthouse-core/audits/deprecations.js
lighthouse-core/audits/errors-in-console.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

we shouldn't render sentences or paragraphs in monospace. not very readable.
before
after

report: don't use unnessary monospace

---

lighthouse-core/scripts/roll-to-devtools.sh

Preparing for this to land: 
https://chromium-review.googlesource.com/c/chromium/src/+/1784959
the only real change here is 51-56. the rest is refactors.

misc(build): include locale files in devtools roll

---

lighthouse-core/audits/dobetterweb/no-document-write.js

this resulted from some back-n-forth with @mfriesenhahn

docs(audits): distinguish document.write() audit from intervention

---

.travis.yml

**Summary**
traced the master failures of installing latest chrome stable to this bug https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627
just need to update dpkg before install chrome

tests: migrate travis to xenial for modern Chrome support

---

lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/report/html/renderer/details-renderer-test.js

We currently throw on unknown details types. This means that any new details type is a breaking change.
So instead, let's just show the data with a warning message.

report: unknown details type

---

docs/recipes/lighthouse-plugin-example/package.json
docs/recipes/lighthouse-plugin-example/readme.md

**Summary**
- Update plugin recipe lighthouse peer dependency to a version that supports plugins. 
- Update lighthouse plugin recipe run command.
https://github.com/zkat/npx/issues/215 captures the issue with the npx command

docs(plugins): update recipe example's lighthouse peer dependency version

---

.eslintrc.js
lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js

bug from this change: https://github.com/GoogleChrome/lighthouse/pull/5006
the path was mistranslated
i also expanded the console expectations to be an explicit array, because `{length: x}` is smoky garbage for debugging

tests(smokehouse): fix unintentional 404. remove max-len rule for expectations

---

lighthouse-core/lib/i18n/i18n.js
lighthouse-core/test/lib/i18n/i18n-test.js

fixes the crasher part of #9684
The issue was that we were `JSON.parse(JSON.stringify(values))`ing to make sure we weren't modifying the original ICU replacement values, but both `Infinity` and `NaN` get converted to `null` when stringified, which then fails the check that we're only replacing numeric placeholders with numbers.
Instead, this copies over the values one by one to a new object, formatting if needed. Also smushes `_preformatValues` and `_processParsedElements` together because the first was mostly just calling the second, but the first had a way better name.

i18n: treat Infinity and NaN as numeric values

---

lighthouse-core/scripts/roll-to-devtools.sh

the rebase command does it anyway
@paulirish tried to tell me this was weird but i didnt listen.

clients(devtools): remove version replacement for expectations

---

lighthouse-core/lib/network-recorder.js

The `NetworkRecorder.recordsFromLogs` performance described [here](https://github.com/GoogleChrome/lighthouse/pull/9491#discussion_r321531671) was pretty bad, the vast majority of time spent in `findNetworkQuietPeriods`. Something like 1380ms spent on this is especially bad because it happens three times in a typical LH run: once [right before `GatherRunner.afterPass` ](https://github.com/GoogleChrome/lighthouse/blob/52cb0c904648be2f3395f2791b13844d7fac4d58/lighthouse-core/gather/gather-runner.js#L300), once in a computed artifact for the first audit that requests networkRecords for the defaultPass, and once spread over the run of `pass()` where `NetworkRecorder` is essentially running `recordsFromLogs` as protocol events come in. That 3x becomes 6x if e.g. there's a valid offline site …

core(network-recorder): optimize network idle detection

---

readme.md

**Summary**
* Adds one of my projects using lighthouse to the documentation
* some small fixes to the docs layout
fixes #9701

docs: add lighthouse-monitor, minor adjust list layout

---

lighthouse-cli/test/smokehouse/error-expectations.js
lighthouse-cli/test/smokehouse/seo/expectations.js
lighthouse-cli/test/smokehouse/smokehouse-report.js
types/smokehouse.d.ts

Add `lhr.runWarnings` to the expectation checker. If not defined, the checker expects nothing to be there (like `runtimeError`).

tests(smokehouse): check runWarnings

---

docs/throttling.md
docs/variability.md

Add some links to more information on the DebugBear blog, since Paul suggested that might be useful.

docs: add links to more info about throttling and variability

---

lighthouse-core/audits/apple-touch-icon.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Links the apple-touch-icon audit `description` to the web.dev article we recently wrote on the topic.

core(audits): link apple-touch-icon audit to web.dev

---

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
lighthouse-core/test/audits/byte-efficiency/unused-css-rules-test.js

**Summary**
Described by brendan already in https://github.com/GoogleChrome/lighthouse/issues/9684#issuecomment-532381611
fixes https://github.com/GoogleChrome/lighthouse/issues/9684 (and https://github.com/GoogleChrome/lighthouse/issues/9614 which started this for me 😄 )

core(unused-css-rules): no more inifinity savings

---

lighthouse-core/scripts/dogfood-lhci.sh

**Summary**
We can't fail on unrecognized variables and check for them at the same time :)

misc: support unset variables in lhci dogfood script

---

readme.md

**Summary**
This PR adds [Lighthouse CI Action](https://github.com/treosh/lighthouse-ci-action) to the list of related projects.

docs(related-project): add lighthouse-ci-action

---

lighthouse-core/test/report/html/renderer/report-renderer-test.js

#9555 made it so `utm_medium=channel` was added to web.dev links in addition to devsite links (and added a markdown link creation test for it), but it didn't update this secret `report-renderer` test, which has been skating by because it only required 20 devsite links with a `utm_medium` search param to be in the sample report.
That's about to start failing, so updated the test to account for the new docs origin.

tests: update report-wide utm_medium check for web.dev

---

lighthouse-core/lib/network-recorder.js
lighthouse-core/test/lib/network-recorder-test.js

#5256 added a workaround for #5254, where many QUIC requests never got a final `LoadingFinished` or `LoadingFailed` event, so we were treating them as forever open, we never reached network quiet, and so we always hit the LH load timeout. The workaround was to check if the request was over QUIC and if there was end timing information, calling that "finished".
We broke this workaround *I think* when we finally dropped our direct dependence on devtools-frontend and [wrote our own `NetworkRequest`](https://github.com/GoogleChrome/lighthouse/pull/5451). 
[`NetworkRequest._recomputeTimesWithResourceTiming`](https://github.com/GoogleChrome/lighthouse/blob/6ff02e42f7083b25c1a4b9869478419864c12c5b/lighthouse-core/lib/network-request.js#L324-L334) takes in some preliminary timing information that …

core(network-recorder): remove quic-request-finished workaround

---

build/build-dt-report-resources.js
clients/devtools-report-assets.js

These references will be properly namespace-scoped once [1] is
submitted.
[1]: https://polymer2-chromium-review.googlesource.com/c/chromium/src/+/1829708

clients(devtools): update references to Runtime.cachedResources

---

lighthouse-core/scripts/test-lantern.sh

noticed in CI that `yarn test-lantern` can fail while downloading the data.
Can repro locally if you attempt to download enough times.
it's not a zip. It's sometimes an html file:
So just repeat a few times (5? sure.) until it works, so CI is happy.

tests(lantern): attempt to download test set a few times

---

.gitignore
lighthouse-core/scripts/compare-timings.js
lighthouse-core/scripts/timings.js

For example usages, see #9712 and #9713

misc: timings script

---

docs/configuration.md
docs/readme.md

docs: update stale references to audits

---

lighthouse-core/scripts/compare-timings.js

For a script called `compare-timings.js`, it really didn't do much comparing :p
this is p. cool b/c you don't have to know before hand the specific measures that will change or look at every entry. Just look at the first few to see the biggest changes.

scripts: compare-timings.js --compare

---

lighthouse-core/lib/tracehouse/main-thread-tasks.js
lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js

**Summary**
Addresses one of the 3 remaining cases for `Fatal trace logic error - child cannot end after parent` error.
#7764

core(tracehouse): allow nested trace events without an end

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/templates.html

1) some fireworks css that is not used.
2) old options menu used JS, new one does not.

report: remove some dead code

---

lighthouse-core/audits/seo/link-text.js

**Summary**
Add Korean translations for the [Links Do Not Have Descriptive Text](https://developers.google.com/web/tools/lighthouse/audits/descriptive-link-text).
[translated words for non-korean speakers](https://translate.google.co.kr/?hl=ko#view=home&op=translate&sl=ko&tl=en&text=여기%0A여기를%20클릭%0A클릭%0A링크%0A자세히%0A자세히%20보기%0A계속%0A이동%0A전체%20보기)
#7547 #5322 #9446

core(seo): support korean in link-text audit

---

lighthouse-core/lib/i18n/README.md

**Summary**
I noticed, upon reviewing the l10n plan for DevTools, that we never mention our divergence from `message.json` format (read: "meanings").

docs(i18n): add 'meaning' to i18n README

---

readme.md

**Summary**
I'd like to update the README documentation to list another CLI tool that has been built with Lighthouse to detect JS libs and their vulnerabilities:

docs(related-projects): add the is-website-vulnerable CLI tool

---

docs/releasing.md
lighthouse-core/scripts/release/test.sh

another iteration of trying to streamline this thing :)

misc: more releasing tweaks

---

lighthouse-core/gather/gatherers/image-elements.js

This url is quite slow to run: https://www.selfridges.com/US/en/cat/womens/newin/
On the CLI, the ImageElements gatherer can take 25-30 seconds to run.
Turns out that gatherer finds ~2000 images, however 99% of them are country flag DOM elements with a css background using the exact same sprite image. 
----------
While we have added [that smart only-do-the-50-most-important-network-images check](https://github.com/GoogleChrome/lighthouse/pull/7274)... we don't handle the case of multiple background images pointing to the same asset that's within the top 50.
But now we do. :)

core(image-elements): cache naturalSize results

---

.travis.yml

We retry cli smoke tests in CI, but didn't do the same for the new bundle smoke tests. Quick and dirty way is to just retry a few times in the CI invocation. better solution may come later (internal to firehouse) but should wait for w/e refactors that may come its way soon.

test(build): attempt bundle test three times in CI

---

build/build-lightrider-bundles.js
build/build-utils.js
build/build-viewer.js
package.json
yarn.lock

cont. #9596 (I meant to just update that PR, but apparently I don't know how to push to a PR branch ...)
I updated @wardpeet's work with master, and also minified the assets for the LR report generator. I verified the report still works with a terser pass (if we rely on function or class names, we'd have to pass special flags, but it seems we don't for the report).
Can confirm this saves a lot of bytes.
`dist/lightrider/report-generator-bundle.js` 247 KB -> 152 KB (38%)
`dist/viewer/src/viewer.js` 309 KB -> 213 KB (31%) (done in #9596)

misc(build): minify report javascript for lightrider report generator

---

lighthouse-core/gather/driver.js

extracted from #9605 / #9650
repro by messing up the expression:
before:
after:

core(driver): fix error handling for Runtime.evaluate

---

lighthouse-core/gather/driver.js
lighthouse-core/lib/lh-element.js
lighthouse-core/test/gather/driver-test.js
lighthouse-core/test/lib/lh-element-test.js

While checking out the ts 3.7 beta, this typing mistake became apparent. We use the global `Element` type declaration (dom lib) where we really want our `lib/element.js`. Renaming to `LHElement` is a simple solution to this name clash.
the error was uncovered likely thanks to changes required for this bugfix: https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/ "Local and Imported Type Declarations Now Conflict"

core: rename Element to LHElement

---

lighthouse-core/lib/tracehouse/main-thread-tasks.js
lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js

**Summary**
Addresses one of the 3 remaining cases for `Fatal trace logic error - child cannot end after parent` error.
#7764, depends on #9785

core(tracehouse): allow child to start <1ms before parent

---

package.json
yarn.lock

**Summary**
Updates to latest version of 3p web that fixes a DOS regex issue.
closes #9848

deps: update third-party-web to 0.11.0

---

lighthouse-cli/test/smokehouse/smokehouse.js

If you don't run LH in the root directory, this breaks.
Also, the `test.sh` release script doesn't have a `.tmp` folder, so this breaks there too.
I plan on following up later with a centralized place to make temporary files (we do this in a few different places).

test(smokehouse): fix tmp dir usage

---

lighthouse-core/audits/metrics/total-blocking-time.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Links the Total Blocking Time report UI to its documentation on web.dev.

core(audits): Link to Total Blocking Time documentation

---

lighthouse-core/scripts/dogfood-lhci.sh

**Summary**
lhci now has a built-in static server we can use that does compression and other sensible things, we should also be getting status checks for LHCI when it runs

misc: upgrade lhci dogfood script

---

lighthouse-core/audits/metrics/max-potential-fid.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Links the mpFID description in the Lighthouse report UI to the shiny new mpFID doc that we just merged on web.dev. https://web.dev/lighthouse-max-potential-fid isn't live yet but should be in a day or 2.
https://github.com/GoogleChrome/web.dev/pull/1688

core(audits): link mpFID description to web.dev's mpFID doc

---

lighthouse-core/computed/metrics/largest-contentful-paint.js
lighthouse-core/lib/tracehouse/trace-processor.js

i confirmed lcp was added in 78
(the [commit](https://chromium.googlesource.com/chromium/src/+/e7a0a11a0e6fbc429fe1daa82ed93724b3a5fd13) landed as r687032, which i dropped into the _Find Releases_ tool at https://omahaproxy.appspot.com/)
Just documenting that since it comes up a lot.

misc: add note about LCP required chrome version

---

lighthouse-core/audits/performance-budget.js
lighthouse-core/config/budget.js
lighthouse-core/test/audits/performance-budget-test.js
lighthouse-core/test/config/budget-test.js

**Summary**
- Moves the logic for determining the matching budget to `budget.js`. In a subsequent PR, the `'performance-budget'` audit will be split into `'resource-budget'` and `'timing-budget`', so this refactor allows the logic to be re-used across both audits.
- Minor fix: Use deep copy instead of shallow copy when finding matching budget.

core(lightwallet): refactor budget matching logic

---

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
lighthouse-core/lib/stack-collector.js
package.json
yarn.lock

core(stacks): match against js-lib-detector with id property

---

package.json
yarn.lock

changes:
* `66a5e226` flags: add new --disable flags to reduce noise and disable backgrounding ([#170](https://github.com/GoogleChrome/chrome-launcher/pull/170))
- --disable-component-extensions-with-background-pages
- --disable-backgrounding-occluded-windows
- --disable-renderer-backgrounding
- --disable-background-timer-throttling
* `c4890ee3` feat: expose public interface for locating Chrome installations ([#177](https://github.com/GoogleChrome/chrome-launcher/pull/177))
- `Launcher.getInstallations()` returns an array of paths to available Chrome binaries
* `a5ccaa4e` deps: update assorted dependencies ([#175](https://github.com/GoogleChrome/chrome-launcher/pull/175))
* `e67a10df` --disable-translation is now --disable-features=TranslateUI …

deps: bump chrome-launcher to 0.12.0

---

lighthouse-core/lib/i18n/i18n.js

This is a temporary change to silence excessive warnings displayed when running with a plugin using i18n. This will be reverted in https://github.com/GoogleChrome/lighthouse/pull/9799.

i18n: Use log.verbose for outdated strings warning

---

lighthouse-core/lib/lh-error.js

fixes #9882
We could probably revisit how these protocol errors are generated because this function predates all of the i18n work and most of LHError handling, but this is the easy fix for now.
All of [the LHErrors that have patterns to match](https://github.com/GoogleChrome/lighthouse/blob/91531d689f4a5f15fb310aaf8e22b4822ce1edf5/lighthouse-core/lib/lh-error.js#L314-L332) use the [same message](https://github.com/GoogleChrome/lighthouse/blob/91531d689f4a5f15fb310aaf8e22b4822ce1edf5/lighthouse-core/lib/lh-error.js#L46-L47), which doesn't have any replacements, so these arguments can safely be removed.

core: fix icu error thrown while throwing protocol error

---

docs/configuration.md
docs/readme.md
lighthouse-cli/cli-flags.js
lighthouse-cli/test/cli/bin-test.js
lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-config.js
lighthouse-core/config/config.js
lighthouse-core/test/config/config-test.js
types/config.d.ts

**Summary**
per request in https://github.com/GoogleChrome/lighthouse/pull/9854#discussion_r342924896 this deletes the full config now that js coverage is part of default. we haven't had anything else to add to the full config in its 2 year existence, so seems pretty safe to remove

core: delete full config

---

docs/devtools-throttling-deprecation.md
docs/throttling.md

This doc will added via a link next to the throttling option in DevTools.
CL: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/1885347

docs: devtools throttling deprecation notice

---

lighthouse-core/gather/gatherers/seo/font-size.js

core(font-size): don't allow a deleted node to fail gatherer

---

build/build-bundle.js
clients/devtools-entry.js
lighthouse-core/config/config-helpers.js
lighthouse-core/config/config.js

Rolling this patch (combined with #9377) is confirmed to work in DevTools.
Basically, just expose plugin modules by their regular, normalized paths (sans any relative path components or `node_modules`). Then directly `require` plugins if we are in devtools (skip the custom resolving we do).
@brendankenny to figure out if this is the best approach :)

bundling pubads for devtools

---

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-core/config/config.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/scripts/build-report-for-autodeployment.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/results/artifacts/artifacts.json
types/artifacts.d.ts

Extracted from #9911.
Needed for #9713

core: add new base artifact, HostFormFactor

---

clients/extension/scripts/popup.js

fixes bug where only the initial settings object was used. user input didn't affect the current session

clients(extension): use new settings when form updates

---

lighthouse-core/report/html/templates.html

**Summary**
Bugfix
change `.lh-sticky-header`'s position `sticky` to `fixed`.
#9141

report: fix flicker in normal case report

---

lighthouse-cli/bin.js
lighthouse-cli/test/cli/cli-flags-test.js
lighthouse-cli/test/fixtures/cli-flags-path.json

**Summary**
The wart that was our string/object coercing of `extraHeaders` had a bug :) this allows the object form to be passed in too
fixes https://github.com/GoogleChrome/lighthouse/issues/9961

cli: allow extraHeaders as object

---

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-core/gather/gatherers/meta-elements.js
lighthouse-core/test/results/artifacts/artifacts.json
types/artifacts.d.ts

**Summary**
The MetaElements artifacts contains now also de meta element attribute `property`. Now only the `name` attribute was present. The `property` attribute is often use by Open Graph meta tags. More information about `property`: https://stackoverflow.com/questions/22350105/whats-the-difference-between-meta-name-and-meta-property 
Fixes #9964

core(artifacts): add property attribute to MetaElements

---

clients/devtools-entry.js

To support LH localization in DevTools, this PR splits `runLighthouseInWorker` into two functions and expose them to the audits worker. The first function is `setUpWorkerConnection` which sets up and returns the connection that allows the worker to make an xhr request to the LH locale file. The second function is `runLighthouse`, which processes the configs to run lighthouse and returns the report.

clients(devtools): split up runLighthouseInWorker and expose to worker

---

readme.md

**Summary**
Add [PageSpeed Green](https://pagespeed.green) to Lighthouse Integrations section.
There are no related issues/PRs

docs(readme): add PageSpeed Green to to related projects

---

docs/plugins.md

In advance of community plugins beta launch, this change ensures that all examples are featured in our documentation and we are up to date. This will be referenced by at least one FAQ about existing plugins. This just makes the list comprehensive.

docs: update plugin list to include all examples

---

docs/plugins.md
docs/recipes/lighthouse-plugin-example/readme.md
lighthouse-core/config/config-helpers.js
lighthouse-core/test/config/config-test.js

followup from #9997 which recommended NODE_ENV but meant to recommend NODE_PATH.
Also some error message formatting
-------------
closes #9950 #9948

docs(plugins): update plugin developer docs wrt NODE_PATH

---

build/readme.md

@connorjclark  wrote most of this: https://gist.github.com/connorjclark/c0592ee4c2fcf888a708dbfc62da6ecc
it's quite useful so i think we should capture it in the repo

docs: add readme for build/

---

lighthouse-core/test/lib/minification-estimator-test.js
yarn.lock

fixes a security vuln warning on the repo.
angular is included only for this test.  landed in https://github.com/GoogleChrome/lighthouse/pull/6138

deps(angular): update patch version of angular fixture

---

lighthouse-core/audits/metrics/max-potential-fid.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

this is a nit.
MPFID has the longest description and is the only one to make mention of the unit the metric presented in - which is understandable, since all the other are seconds and this is the outlier. But I don't think it's necessary, given that we display the units with the measure.

core(max-potential-first-input-delay): shorten description

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/report/html/templates.html

I noticed that with the rounded [linecap](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap), the arc visually extends farther than it really should.
So here's the proper adjustment. After this change, the arc shortens up a little bit on both ends.
partial fix of #9803
----------------
**UPDATE.** I tweaked the math.. the arcs now go halfway between the two cases above.
GIF of before and after (updated):

report: adjust score's arc length accounting for rounded linecap

---

lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/report/html/renderer/details-renderer-test.js
types/audit-details.d.ts
types/audit.d.ts

If a header defines a `mutli: { key: string}` property, the renderer will render each value in `item[key]` within the same column of that row. All other properties (besides label - it doesn't apply) can be set for this "multi header" - anything not set defaults to the outer `heading`.
Note: Originally there was a toplevel `multi: {}` object, which contained all the keys that could be arrays. Turns out that allowing any property of a audit product item to be an array does not complicate the renderer as much as I thought it would, so I removed it.
With this PR, nothing yet uses this feature. To see it in use, see the `bundle-analysis` branch (#10064)
```
return {
items,
headings: [
{key: 'url', valueType: 'url', multi: {key: 'sources', valueType: 'code'}, label: …
```

report(details-renderer): support sub-rows within a table

---

lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/gather/gatherers/image-elements.js
lighthouse-core/test/audits/byte-efficiency/offscreen-images-test.js
types/artifacts.d.ts

**Summary**
Native lazy-loading was recently introduced in Chrome 76. This PR excludes images with a specified 'loading' attribute ('lazy' and 'eager', 'auto' TBD) from the 'defer offscreen images' check. 
See https://web.dev/native-lazy-loading/ for more details about the loading attribute. 
fixes: #10053

core(offscreen-images): pass images with 'loading' attribute

---

lighthouse-core/lib/stack-collector.js

Isolate `stack-collector`.
fixes #10065

gatherers(stack-collector): use isolation

---

readme.md

**Summary**
Adds a bullet to the `Paid / Tiered` section of `readme` for [Automated Lighthouse Check](https://www.automated-lighthouse-check.com/).

docs(readme):  automated-lighthouse-check.com - paid / tiered

---

lighthouse-core/test/computed/speedline-test.js

This test is flaky on appveyor. And we already have a test for computed-artifact's caching (see computed-artifact-test).

tests(speedline): remove flaky test

---

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-core/audits/dobetterweb/js-libraries.js
lighthouse-core/test/audits/dobetterweb/js-libraries-test.js
lighthouse-core/test/results/artifacts/artifacts.json
lighthouse-core/test/results/sample_v2.json
package.json
proto/sample_v2_round_trip.json
yarn.lock

Fixes #9881
Don't think we need to put a `secondary` (or w/e) property in `js-library-detector`. A naming convention for the id is sufficient imo.

core(js-libraries): hide fast path items from table, put all in debugData

---

lighthouse-cli/cli-flags.js
lighthouse-cli/test/cli/run-test.js

`--output json,html` was meant to work, but `yargs.choices` was preventing that.

cli: fix csv for --output

---

docs/releasing.md
lighthouse-core/scripts/release/prepare-commit.sh

misc: release script push tag

---

lighthouse-core/test/report/html/renderer/report-ui-features-test.js

**Summary**
Problem: the tools button test suite fails when run in isolation, for example:
```bash
$ npx jest lighthouse-core/test/report/html/renderer/report-ui-features-test.js -t="tools button"
...
Test Suites: 1 failed, 1 total
Tests:       15 failed, 15 total
```
Root cause: The tools button test suite setup calls ReportUiFeatures.initFeatures
which has an implicit prerequisite on ReportRenderer.renderReport.
The prerequisite was coincidentally being met when other test suites in
the file invoked the render test helper function.
Solution: Invoke the render test helper function in the tools button suite setup.
#9433

tests(report-ui-features): fix tools button suite to pass isolated run

---

lighthouse-core/test/report/html/renderer/report-ui-features-test.js

**Summary**
Add two test cases to the _getNextSelectableNode suite missed in my original PR
- empty list
- list of 1
#9433

tests(report-ui-features): add empty list and single item test cases

---

lighthouse-core/gather/gather-runner.js

@exterkamp and I wanted to query how long each pass takes, but we are missing the requisite timing measures.

core: measure time for GatherRunner.runPass

---

lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
lighthouse-core/computed/resource-summary.js
lighthouse-core/test/computed/resource-summary-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

core(resource-summary): ignore /favicon.ico

---

docs/scoring.md

Changes links to correct v5 destinations.
**Summary**
Typos in docs. The previous links went to a spreadsheet that was only a link to this new version. This updates the url and skips a step.

docs(scoring.md): Updates links to use new spreadsheet

---

lighthouse-core/report/html/templates.html

**Summary**
***Problem***
Print displays the tools drop down menu, rendering behind the category
headings.
*****Screenshot of menu rendered in report print preview*****
***Root cause***
The drop down menu is made hidden by the CSS `visibility: hidden` and
toggled to `visibility: visible` when displayed to users and the print
media does not support this property (citation needed).
***Solution***
Use `display: none` for the `print` media query to hide it (print media
does not support drop drop interactions).
*****Screenshot of menu hidden in report print preview*****

report: fix ghost menu in print

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

**Summary**
The report drop down menu does not close when the escape key
is pressed in the devtools.
***Gif of bug: menu does not close when escape key is pressed and console opens***
This creates a challenge for customer relying on the keyboard that wish
to dismiss the drop down.
This also does not align with the experience of the WAI ARIA practice
navigation menu button example [1].
The escape key event is captured and not propagated by the
devtools to toggle the console drawer.
Close the menu when focus moves out of the menu.
This better aligns the menu with the Navigation menu button example for
which its interaction design is based on [1].
**Code Change**
* Add a menu focus out handler to close the drop down menu
* Unfortunately JSDOM does not support focusout events so JSDOM …

report: close drop down menu when focus is lost

---

lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations.js
lighthouse-cli/test/smokehouse/test-definitions/redirects/expectations.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/gather/fake-driver.js
types/smokehouse.d.ts

core: warn if document was redirected

---

lighthouse-core/audits/seo/link-text.js

Adding the English keywords:
- `information`
- `more info`
- `more information`
- `read more`
- `see more`
And common Swedish terms used as link text (Google Translate links provided if you wish to confirm the meaning of the words):
- [`här`](https://translate.google.com/#view=home&op=translate&sl=sv&tl=en&text=h%C3%A4r)
-  [`klicka här`](https://translate.google.com/#view=home&op=translate&sl=sv&tl=en&text=klicka%20h%C3%A4r)
-  [`läs mer`](https://translate.google.com/#view=home&op=translate&sl=sv&tl=en&text=l%C3%A4s%20mer)
-  [`mer`](https://translate.google.com/#view=home&op=translate&sl=sv&tl=en&text=mer)
-  [`mer info`](https://translate.google.com/#view=home&op=translate&sl=sv&tl=en&text=mer%20info)
-  [`mer information`](https://translate.google.com/#view=home&op=translate&sl=sv&tl= …

core(audits): Add more keywords to blocklist

---

lighthouse-core/test/gather/gather-runner-test.js

**Summary**
Master was accidentally broken by some fast merging conflicts that were git-detectable conflicts.

tests: avoid redirect in failureMode warn test

---

lighthouse-core/audits/metrics/largest-contentful-paint.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
Updates the LCP `description` to point to https://web.dev/lighthouse-largest-contentful-paint
https://github.com/GoogleChrome/web.dev/pull/1639

core(largest-contentful-paint): update docs link

---

lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
lighthouse-core/test/gather/gather-runner-test.js

This change makes sense in isolation, but in particular I'm doing this to avoid an unnecessary modification to this smoke test expectation for LR (transfer sizes are different b/c response headers). I changed resource size too just b/c there's no need to be so specific.

tests(smokehouse): make bytes gzip size checks less restrictive

---

lighthouse-cli/test/fixtures/manifest.json
lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations-details.js
lighthouse-core/audits/installable-manifest.js
lighthouse-core/computed/manifest-values.js
lighthouse-core/test/audits/installable-manifest-test.js
types/artifacts.d.ts

core(installable-manifest): icon requirement 192px -> 144px

---

.appveyor.yml
.npmignore
build/build-pack.sh
docs/recipes/auth/package.json
docs/recipes/integration-test/package.json
package.json

For some reason the current setup for the doc integration tests, which has been working for months now, is now the root cause of an awful infinitely recursive dependency. `yarn test-docs` never finishes.
Instead, let's pack lighthouse and use the resultant tar file directly. This is much closer to what would get published to npm (there is still room for including more files than expected vs. the actual process, since we aren't in a pristine folder).

build: use npm pack'd lighthouse in doc integrations

---

readme.md

okay i think these are reproducible and good.
i'm not sure when they changed the format that results in [this empty object to null change](https://github.com/GoogleChrome/lighthouse/pull/10242/commits/4a32b15f6c6e8cc5e8ddc61c7f1f936717f0e37a), but it was between 3.7.1 and 3.11.2.

docs: add protobuf install directions

---

readme.md

**Summary**
Added link and description for [Siteimprove Performance](https://siteimprove.com/en/performance/) product, which uses Lighthouse.
__Note:__ I am employed at Siteimprove. If there are special guidelines we need to follow in these descriptions, please inform.

docs(readme): Add siteimprove to integrations section

---

lighthouse-core/audits/accessibility/axe-audit.js

**Summary**
Change #10072 used the `Audit.generateErrorAuditResult` function to generate a return value, but this return value is of type `LH.Audit.Result`, when the caller is expecting `LH.Audit.Product`.
Since the returned value we expect is a relatively simple type, here we construct the relevant fields (`score`, `errorMessage`) directly instead.
https://github.com/GoogleChrome/lighthouse/pull/10072

tests(audits): Return type correction (LH.Audit.Result -> LH.Audit.Product)

---

package.json
yarn.lock

hopefully fixing the spam in our CI output.

deps: bundlesize to 0.18.0

---

lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
package.json
yarn.lock

**Summary**
Updates `axe-core==3.4.1` following its release on 2019-12-18 ([release tag](https://github.com/dequelabs/axe-core/releases/tag/v3.4.1)).

deps: update axe-core to 3.4.1

---

.github/CODEOWNERS

funnily enough, github support informs me that codeowners is required for the codereview rotation to work. :p
ref #10265

misc: add CODEOWNERS to finish codereview assignment setup

---

docs/authenticated-pages.md
docs/puppeteer.md

docs: tweaks to auth + pptr docs

---

lighthouse-core/computed/page-dependency-graph.js
lighthouse-core/lib/dependency-graph/base-node.js
lighthouse-core/test/computed/page-dependency-graph-test.js
lighthouse-core/test/lib/dependency-graph/base-node-test.js

**Summary**
Prevents fatal "Invalid cycle detected" error from happening when a timer was installed and fired in the same task (which shouldn't be possible but c'est la vie)
fixes #10098

core(lantern): do not create self-dependencies via timers

---

lighthouse-core/audits/uses-rel-preconnect.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/audits/uses-rel-preconnect-test.js

core(uses-rel-preconnect): warn on 3+ preconnects

---

lighthouse-core/lib/stack-collector.js
lighthouse-core/test/lib/stack-collector-test.js

**Summary**
Magento version is a number not a string from library detector
https://github.com/johnmichel/Library-Detector-for-Chrome/blob/357a4d49c6a177ca7df853160e270cd77beb7140/library/libraries.js#L1585-L1595
closes #10294

core(stacks): handle numeric version from library detector

---

lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
lighthouse-core/audits/uses-rel-preconnect.js
lighthouse-core/test/audits/uses-rel-preconnect-test.js

**Summary**
https://github.com/GoogleChrome/lighthouse/pull/9903 added a warning when you went over 2 preconnect links but we didn't stop suggesting them at 2 leading to an odd UX of us telling you to add more but then warning when you do.
https://github.com/GoogleChrome/lighthouse/pull/9903
https://github.com/GoogleChrome/lighthouse/issues/10292

core(preconnect): pass without warning at 2 links

---

lighthouse-core/config/source-maps-config.js

This will allow landing source map stuff without things being 100% ready to enable by default (such as some styling concerns re: `subRows`, which many source map audits use, and the CORS issue #9459)
Used by: https://github.com/GoogleChrome/lighthouse/pull/10312 https://github.com/GoogleChrome/lighthouse/pull/10313 https://github.com/GoogleChrome/lighthouse/pull/10314 #10090

core: add temporary config for source map features

---

lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
lighthouse-core/computed/manifest-values.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/test/audits/installable-manifest-test.js
lighthouse-core/test/computed/manifest-values-test.js
lighthouse-core/test/gather/gather-runner-test.js
package.json
types/artifacts.d.ts
yarn.lock

Fixes https://github.com/GoogleChrome/lighthouse/issues/10318

core: support old version of Page.getInstallabilityErrors

---

lighthouse-core/config/experimental-config.js

The config made in #10311 is too restrained. A config for experiments is really what I'd want. #10303 legacy-javascript would be one such audit, along with all the source map stuff meant for the previous config.
Something like this is useful IMO because adding a line in the default-config to test a nonstandard audit (and then remembering to delete that line) is annoying. for example: when we had `unused-javascript` not in the default config.

core: experimental config

---

lighthouse-core/config/config.js
lighthouse-core/runner.js
lighthouse-core/test/config/config-test.js
lighthouse-core/test/runner-test.js
types/audit.d.ts

optionalArtifacts allow an audit to request an artifact that may enhance the analysis, but isn't necessary to get useful information. Intended for artifacts that are experimental (SourceMaps), or expensive shouldn't be required (also, maybe SourceMaps).
Changed the terminology inside `config.js` to use `requestedArtifacts`. The warning messages were already using it, so it fits well :)
see also: #10090

core: audit.meta.__internalOptionalArtifacts

---

lighthouse-viewer/app/styles/viewer.css

Moved `pointer-events:none` from the parent wrapper for the loading screen; added it to the child instead, so that the parent retains cursor interactivity and the `cursor:wait` is correctly shown - fixes #10010

viewer(css): cursor:wait indicator no longer blocked by pointer-events: none

---

commitlint.config.js

some rules are now deprecated. and i loosened the subject-case one since that fought with us a bit.
https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md
https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md#subject-case

misc: update commitlint config to latest, loosen subject-case

---

.appveyor.yml
package.json

**Summary**
Noodling around with the appveyor build failures noticed [here](https://github.com/GoogleChrome/lighthouse/pull/9924#issuecomment-579330026).
This PR will become a build-related fix, if & when the root cause is discovered and a fix determined.
While entirely separate to the `lighthouse` project and codebase, a similar `7z.exe` non-zero exit code was returned after https://github.com/phenomic/phenomic/pull/1005 was merged (build logs [here](https://ci.appveyor.com/project/MoOx/phenomic/build/3480)).

build: fix appveyor cache failures

---

clients/devtools-entry.js
lighthouse-core/config/constants.js
lighthouse-core/config/lr-desktop-config.js

fixes #10315
I was going to make a shared desktop config and rely on config inheritance, but it turns out that we only support inheriting from the default config :)

clients(devtools): use the same desktop throttling as lightrider

---

clients/extension/manifest.json

We don't need it. And FF reviewers don't like the unsafe eval bit.

clients(extension): remove content security policy

---

lighthouse-core/audits/dobetterweb/charset.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/audits/dobetterweb/charset-test.js
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

**Summary**
While it would be overkill to implement full-blown HTML/HTTP parsers, by simply making the regular expressions case-insensitive we can reduce the amount of false negatives for the charset audit.
This patch also applies some drive-by nits/simplifications.
Ref. #10023, #10284.

core(charset audit): loosen CHARSET_HTML_REGEX and CHARSET_HTTP_REGEX

---

readme.md

**Summary**
This PR adds Lighthouse [lighthouse-batch-parallel](https://github.com/Carr1005/lighthouse-batch-parallel) to the list of related projects!

docs(readme): add lighthouse-batch-parallel to related projects

---

lighthouse-viewer/app/index.html
lighthouse-viewer/app/src/lighthouse-report-viewer.js

after the change the site looks like:
closes https://github.com/GoogleChrome/lighthouse/issues/10335

misc(viewer): mention other lighthouse channels

---

lighthouse-core/report/html/report-styles.css

I went with `--color-informative` which was already in use for some other links and it looks (locally) ok to me in order to fix #10363.
**Summary**
This PR styles `.lh-table-column--link a` elements with the custom color `--color-informative` instead  of the default (user agent stylesheet) color for links (see #10363 for rationale: contrast too low / a11y)
This is intended as a bugfix for #10363.
The need for this change is a better visual contrast in dark mode and respecting WCAG2.1 rules along the way.
https://www.w3.org/TR/WCAG21/#contrast-minimum
See #10363 for original issue.

report: fix link contrast issue in dark mode

---

lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
lighthouse-core/gather/gatherers/accessibility.js
lighthouse-core/test/report/html/renderer/report-renderer-test.js
package.json
yarn.lock

**Summary**
Updates axe-core==3.5.1 following its release on 2020-02-13 ([release tag](https://github.com/dequelabs/axe-core/releases/tag/v3.5.1)).

deps: update axe-core to 3.5.1

---

lighthouse-core/audits/metrics/cumulative-layout-shift.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json
proto/sample_v2_round_trip.json

@kaycebasques for determining if we should have a page for CLS specific to LH,  https://web.dev/lighthouse-cumulative-layout-shift/ ?

core(cls): add learn more link

---

docs/recipes/custom-gatherer-puppeteer/package.json

we've had this lil error for a bit. 
```
jest-haste-map: Haste module naming collision: custom-lighthouse-recipe
The following files share their name; please adjust your hasteImpl:
* <rootDir>/docs/recipes/custom-audit/package.json
* <rootDir>/docs/recipes/custom-gatherer-puppeteer/package.json
```
it doesnt hurt anybody but this gets rid of it.

misc: resolve jest-haste-map naming collision warning

---

.github/workflows/basics.yml

lol i was inspired by #10416 
I'm pretty impressed with how fast these GH action VMs spin up and run things, so I think this'll give us faster and clearer feedback on the boring but typical failures (sample-json needs updating, linting, etc)
Big benefit you don't have to scroll/search to see where the failure is: 
And this subset of our CI takes just ~5m whereas travis takes ~20min
Our travis remains our default and canonical CI..

tests: add github action w/ basic CI tasks

---

jest.config.js

this should fix the OOM that happens sometimes.
I tested this PR by commenting out `  coverageReporters: ['none'],` from jest.config.js and then running `yarn jest "byte-eff" --ci --coverage --reporters=default`
before the change i saw /test/ and fixtures/ files in the output. afterwards i didnt. seems good. 😁 
----------
apparently our negative matches stopped working at some point. my guess is via https://github.com/facebook/jest/pull/7170 when we [updated to jest 24](https://github.com/GoogleChrome/lighthouse/commit/b1d2b83bdec0090ca215fa52fa1f696f7caff12a). (march 2019)
(i didnt confirm this for sure, but it seems likely)
our coverage definitely changed when that landed....
https://coveralls.io/repos/109595/builds?page=180

tests: update coveragePathIgnore jest configuration

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/renderer/dom.js
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/pwa-category-renderer.js
lighthouse-core/report/html/renderer/report-renderer.js
lighthouse-core/report/html/renderer/snippet-renderer.js
lighthouse-core/report/html/renderer/util.js

these were flagged by some nullability closure linter and there was a request to change them to keep it happy. Since we run with `strict`/`strictNullChecks` this is a no-op in tsc land, as `null` isn't assignable to these types by default. Note that this check is just running on report files.
Not sure why it's just these return types and not other places in these same files...I assume some of their  analysis is hampered by us using tsc-isms.
cc @paulirish @exterkamp

misc: add non-null annotations to keep internal lint happy

---

lighthouse-core/audits/metrics/largest-contentful-paint.js

We copied the FCP 4000ms/2000ms median/podr numbers over to LCP as placeholders until we had HTTP Archive numbers to derive an official curve...but it turns out they're pretty much exactly right (for February 2020, they are 3980ms/1912ms).
This PR just updates the comment on the numbers to make it clear they're for real now.

core(lcp): remove todo, mark score curve points as official

---

lighthouse-core/gather/gatherers/image-elements.js
types/artifacts.d.ts

Two new flags are added to `ImageElement`s.
The first, `usesPixelArtScaling` will be used by the `ImageSizeResponsive` audit (#10460), as those images are intendedly displayed in a pixelated form, so the audit should not flag them.
Note that `image-rendering: -moz-crisp-edges;` is also an accepted value in Firefox, however in such case, the computed style will return `crips-edges`.
See https://developer.mozilla.org/en-US/docs/Games/Techniques/Crisp_pixel_art_look for more information.
The second is `usesSrcSetDensityDescriptor`. That flag will also be used by the `ImageSizeResponsive` and is required, as by the spec, the natural size of the image, is the actual size of the image divided by its density descriptor. Note that we cannot access the actual value of the density descriptor, so in …

misc: add usesPixelArtScaling flag to images

---

lighthouse-core/scripts/dogfood-lhci.sh

**Summary**
master can't pass right now because of the lhci duplicate build problem, so thought I'd update us to use the new `--ignoreDuplicateBuildFailure` flag

misc: ignore duplicate builds in lhci dogfood

---

AUTHORS
jest.config.js
lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-core/audits/image-size-responsive.js
lighthouse-core/config/default-config.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/audits/image-size-responsive-test.js
lighthouse-core/test/results/sample_v2.json
package.json
proto/sample_v2_round_trip.json

**Summary**
New audit checking visible images are big enough. This is a complement to `UsesResponsiveImages`.
Fixes #10434. Check that issue for the New Audit Proposal.

new_audit: check images are big enough

---

lighthouse-core/gather/driver.js
lighthouse-core/test/gather/driver-test.js

Removing some unused code that I found in driver.js: `getQuerySelectorAll` and `getElementsInDocument` (has the same name as a page-functions method). 
They look to be old methods that use `LHElement`. 
----------
There are a couple more LHElement functions that could be removed by updating the one place in code that they are used. Will attempt to remove those in a follow-up PR.

core: remove some dead code in driver.js

---

readme.md

**Summary**
AwesomeTechStack is for all developers and designers who want to improve their website or strive to get the best out of their new project.
With technology insights you will always know what is trending now and what would be the best tech stack to use at the moment
https://awesometechstack.com/tools/analyze/documentation/

docs(readme): add AwesomeTechStack to lighthouse integrations

---

docs/variability.md

**Summary**
Adding a separate hardware section to the variability docs to capture what we've said in a few places across miscellaneous issues.
**Related Issues**
closes #10433
ref https://github.com/GoogleChrome/lighthouse/issues/7963

docs(variability): expand on hardware recommendations

---

lighthouse-core/scripts/compare-runs.js

* `--filter` was broken from the last change
* progress bar didn't use the correct count
* allow collection to be resumed
* organize LHRs by url directory, instead of all in root directory. Simplifies programmatic consumption

misc(compare-runs): fix filter, allow for resume, reorganize output

---

lighthouse-core/report/html/report-styles.css

Fixes #9724 
Updated images below. See linked issue for before images.

report: update table and inline code formatting

---

lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js

**Summary**
the extra comments added to the smoketest by https://github.com/GoogleChrome/lighthouse/pull/10506 increased the document size which reduces the savings estimate
just adding those comments pushes the document size over another round trip to change the savings from 450 to 300 🙂
i.e. the document itself takes another round trip now so the JS finishing at 2.5s instead of 2.95s doesn't save .45s anymore, it saves 2.95s - max(2.5s, document finish time)
recent travis build failures introduced by https://github.com/GoogleChrome/lighthouse/pull/10506 (but only sometimes?)
I can't reliably reproduce the devtools node path failure locally anymore, so I'm not sure what's up with that

tests(smokehouse): loosen wastedMs for unused-javascript

---

.github/workflows/basics.yml

If lint fails, do we want the workflow to continue and run unit tests?
Or should it just immediately give the red X feedback?
I'm fine with both, just wanted to ask folks what they think.

misc(build): disable fail-fast on gh basics workflow

---

lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/metrics/first-contentful-paint-3g.js
lighthouse-core/audits/performance-budget.js
lighthouse-core/audits/timing-budget.js
lighthouse-core/computed/computed-artifact.js
lighthouse-core/computed/load-simulator.js
lighthouse-core/computed/resource-summary.js
lighthouse-core/config/budget.js
lighthouse-core/lib/asset-saver.js
lighthouse-core/runner.js
lighthouse-core/scripts/legacy-javascript/examine-latest-run.js
lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
lighthouse-core/test/runner-test.js
types/artifacts.d.ts
types/audit.d.ts
types/externs.d.ts

**breaking change (see below for details)**
fixes #9897
tl;dr: making this change now allows us to
- trust audits a little less (handy for any model of plugins)
- make audit contexts `postMessage`able, handy for an off-main-thread/extension plugin model if we choose to go in that direction
- pursue the above without having to wait for the 7.0 release, whenever that will be
The change is very small since we only have two lines of code currently modifying an audit context outside of `runner.js` :)
The only real breaking change is that rather than audits pushing to the context to get a top-level LHR warning, they return the warning in their audit `Product`. It's very possible that existing extensions use this functionality. In core, there's only one audit doing so.
Note that `readonly` is …

core(runner): make LH.Audit.Context immutable

---

lighthouse-core/gather/driver.js

it was [added](https://github.com/GoogleChrome/lighthouse/pull/1064) for an audit that was [removed](d99778b4f1eb8d353ad54dc7830d286dfe30ba3e) a while ago.

core: delete unused driver.queryPermissionState()

---

.npmignore

not a risk for real publishing, but this folder slows down `build-pack` which runs as part of `build-all`

misc: npmignore += timings-data/

---

lighthouse-core/test/lib/i18n/i18n-test.js
lighthouse-core/test/lib/i18n/swap-locale-test.js

helps check off some of #10582
Two test issues here:
1. Node 13 has a `Intl.NumberFormat` bug where a `NaN` that was stored in a property on an object will be formatted as `-NaN`, e.g. `({a: NaN}).a.toLocaleString() === '-NaN'`. This also happens in V8 7.9/8.0 (~Chrome 79 and 80) but works correctly before and after these versions.
Formatting `NaN`s isn't exactly important to our report, we added the test to exercise the corner cases and make sure they wouldn't cause a crash, so this PR adds a narrow workaround to the test that can be removed later. Try not to put `NaN`s in the report or they'll be negative for Node 13 users :)
2. The thousands separator for Spanish was removed starting in Node 13, causing the swap-locale formatted-number test to fail. Looking for NaN bugs I ran across …

tests: fix i18n-test bugs in Node 13

---

lighthouse-cli/run.js
lighthouse-cli/test/cli/run-test.js
types/externs.d.ts

**Summary**
`feature` and/or `bugfix`
Right now lighthouse supports passing multiple cli flags to chrome:
```bash
lighthouse --chrome-flags="--headless --allow-insecure-localhost"
```
However when using [`child_process.exceFile`](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) (or npm packages like `execa`) arguments get automatically escaped.
You can simply execute the following node code (given lighthouse is installed) and will see that chrome is **ignoring**  `--headless --allow-insecure-localhost`
```js
execFile("./node_modules/.bin/lighthouse", [
"http://google.com",
"--chrome-flags='--headless --allow-insecure-localhost'"
], (error, stdout, stderr) => {
if (error) {
console.error(stderr);
throw error;
}
console.log(stdout); …
```

cli: add support for multiple --chrome-flags

---

.github/workflows/basics.yml

goal: make sure the gh workflow runs when PRs come in from forks
https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
> Note: By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword.

misc(build): also run GH workflow on pull_request

---

lighthouse-core/test/audits/timing-budget-test.js

**Summary**
fixes master which accidentally broke due to bad merge with #10579
the last commit in #10579 was forever ago and so it never got reran after lantern changes got merged in that affected the value of LCP. there's no real reason it needs to assert on the changing lantern value so I converted it to use the observed value while we're at it to stay with `toEqual` instead of `toMatchInlineSnapshot`

tests: budget tests use an observed throttlingMethod

---

package.json

I've been running into this especially when I have a separate clone locally that I sometimes use.

misc(build): yarn unlink before linking

---

lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa3-expectations.js

pwa.rocks is down. Instead of trying to replace these tests, I've forked it and am hosting at https://connorjclark.github.io/pwa.rocks/

tests(smoke): fork pwa.rocks

---

lighthouse-core/scripts/compare-runs.js

misc(compare-runs): use execFile

---

.github/workflows/ci.yml

running into github api rate limiting errors when downloading protoc, which is weird because it's github making the request. Turns out we need to supply a token :)
https://github.com/arduino/setup-protoc/issues/6
Also drops CI runs on `push`

tests(ci): authenticate protoc download

---

lighthouse-core/scripts/git3po-rules/close-variability-issues.yaml

**Summary**
All ya gotta do to have the bot close these issues in the future is add "pending-close" and "variability"
Current set of issues: https://github.com/GoogleChrome/lighthouse/issues?q=is%3Aopen+is%3Aissue+label%3Avariability+label%3Apending-close
#10657

misc: close variability issues to master issue

---

lighthouse-core/test/report/report-generator-test.js

This check would we need to be updated every time an audit is added or removed. Could become a nuisance in time.

core: remove length check from csv report test

---

package.json

we should do the linking stuff first, and not in parallel with other commands
let's see if it works
fixes #10680

misc(build): fix npm link issue

---

lighthouse-core/audits/dobetterweb/charset.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json

**Summary**
Links the `charset` audit description to the new web.dev guide dedicated to that topic.
https://github.com/GoogleChrome/web.dev/pull/2771

core(charset): add description link to web.dev guide

---

package.json
yarn.lock

**Summary**
Funnily enough DevTools and PSI are bitten by this even if CLI installs aren't, bitten by our own lockfile! :)
closes #10709

deps: bump third-party-web to 0.11.1

---

lighthouse-core/audits/maskable-icon.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json

**Summary**
Links the maskable icon report UI to the new dedicated guide on the topic.
The existing link (https://web.dev/maskable-icon) was arguably good enough but this new one keeps the documentation experience consistent with the rest of the audits, provides concise directions on how to pass the audit, and also mentions the important implementation detail that Lighthouse doesn't actually do anything with the image that's specified as maskable.
* https://github.com/GoogleChrome/web.dev/pull/2811
* Staged documentation page: https://deploy-preview-2811--web-dev-staging.netlify.app/maskable-icon-audit/

core(maskable-icon): update description link to new web.dev guide

---

lighthouse-core/audits/audit.js
lighthouse-core/audits/bootup-time.js
lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/audits/mainthread-work-breakdown.js
lighthouse-core/audits/metrics/cumulative-layout-shift.js
lighthouse-core/audits/metrics/estimated-input-latency.js
lighthouse-core/audits/metrics/first-contentful-paint-3g.js
lighthouse-core/audits/metrics/first-contentful-paint.js
lighthouse-core/audits/metrics/first-cpu-idle.js
lighthouse-core/audits/metrics/first-meaningful-paint.js
lighthouse-core/audits/metrics/interactive.js
lighthouse-core/audits/metrics/largest-contentful-paint.js
lighthouse-core/audits/metrics/max-potential-fid.js
lighthouse-core/audits/metrics/speed-index.js
lighthouse-core/audits/metrics/total-blocking-time.js
lighthouse-core/audits/predictive-perf.js
lighthouse-core/lib/statistics.js
lighthouse-core/test/audits/audit-test.js
lighthouse-core/test/lib/statistics-test.js
lighthouse-core/test/results/sample_v2.json
types/audit.d.ts

In theory defining our score curves with a median and the point of diminishing returns is still a really good idea. The PoDR is a distinctive point that intuitively controls the *behavior* of the curve. It also allows us to set where to stop incentivizing improvements in a particular metric when other metrics should be prioritized instead.
However, in practice it's never been useful for communicating what our uses have wanted to know :) It doesn't correspond to a particular percentile (when the score curve is fundamentally about producing percentiles) which makes it difficult to explain. And whatever behavior might be vaguely incentivized in aggregate, when actually running Lighthouse or creating a new audit you really just want to know what's going to get you a "good" score.
This PR
- …

core(scoring): redefine log-normal curves with median and p10 points

---

build/build-smokehouse-bundle.js
lighthouse-cli/test/smokehouse/test-definitions/source-maps/expectations.js

for @paulirish 
we should probably have a test for this. just doing `node dist/smokehouse-bundle.js` would have caught this and is probably enough, given that there is already `yarn test-bundle`.

tests: use brfs when bundling smokehouse

---

lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-core/audits/byte-efficiency/offscreen-images.js
lighthouse-core/test/audits/byte-efficiency/offscreen-images-test.js

**Summary**
We decided to loosen to 3 viewports for offscreen image audit. This only made sense to me for images *below* the fold so kept our existing restrictions for above and left/right. Let me know if you disagree.
closes https://github.com/GoogleChrome/lighthouse/issues/6677 
closes https://github.com/GoogleChrome/lighthouse/issues/10471

core(offscreen-images): loosen to 3 viewports

---

lighthouse-core/audits/largest-contentful-paint-element.js
lighthouse-core/gather/gatherers/trace-elements.js

We found a more straightforward way to modify an attribute given a backend id. no need to jump through the hoops of the DOM domain.
we tried to at first, but hit a roadblock in that `DOM.setChildNodes` event never seemed to fire ...

Use Runtime.callFunctionOn to set marker attribute

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/config/default-config.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/report/html/renderer/util.js
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
lighthouse-core/test/results/sample_v2.json

linking up the web.dev scoring docs.
also small wording tweak:
> Values are estimated and may vary. The performance score is [based only on these metrics]
to 
> Values are estimated and may vary. The [performance score is calculated] directly from these metrics.
useless screenshot

report: link to updated scoring documentation

---

lighthouse-core/audits/resource-summary.js
lighthouse-core/test/results/sample_v2.json

report(resource-summary): fix size heading key

---

package.json
yarn.lock

**Summary**
Latest yargs-parser is 18.x.x we're on 7.0.0. While I think the specific "vulnerability" in yargs-parser 7 is nonsense for us, it is annoying that we get flagged as a bad actor in `npm audit` and making it easier to discover breaking changes to chromeFlags parser updates in the future would be nice (yargs-parser didn't document breaking changes from 7-13, but they do now).
EDIT: also I know that we depend on yargs *3* 😱 for our actual CLI flags, but for some reason it doesn't actually get flagged in `npm audit` either because it's *so* old it doesn't have the vuln or no one bothered to document 😆 
closes #10722

deps: upgrade yargs-parser to latest

---

lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
lighthouse-core/lib/emulation.js

https://github.com/GoogleChrome/lighthouse/issues/10741#issuecomment-626903508

core(emulation): keep DPR at 2.625 for mobile emulation

---

lighthouse-core/scripts/roll-to-devtools.sh

Runtime.js was removed.  my guess is, of all the remaining files there, shell.js should stick around for a while.

misc(scripts): fix devtools filename doublecheck

---

lighthouse-core/report/html/report-styles.css

theres a bunch of hardcoded monospace fontsizes, but that fails in devtools where we make the report-font-size much smaller.
two examples:
this normalizes all monospace font-sizes to one thing.

report: define monospace fontsize relative to report-font-size

---

build/build-dt-report-resources.js
clients/devtools-report-assets.js
lighthouse-core/report/html/html-report-assets.js

In #9758 (sept 2019), @TimvdLippe prepared us for some changes to DevTools's Runtime.
But recently (march 2020), Tim reverted those changes: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2107523  (see the diff on `front_end/third_party/lighthouse/report-assets/report-generator.js`)
So this carries over that revert diff back here.

clients(devtools): fix Runtime.cachedResources reference

---

lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
lighthouse-viewer/test/viewer-test-pptr.js

report(metrics): use css grid so metrics are aligned

---

lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/renderer/util.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
lighthouse-core/test/results/sample_v2.json
proto/lighthouse-result.proto

report: link to calculator w/ values

---

lighthouse-core/audits/metrics/largest-contentful-paint.js
lighthouse-core/audits/metrics/total-blocking-time.js
lighthouse-core/test/audits/metrics/largest-contentful-paint-test.js
lighthouse-core/test/audits/metrics/total-blocking-time-test.js

After lining up http archive mobile and desktop distributions with the Lighthouse distribution, doing some simple regressions, then crossing my eyes and transcribing cosmic ray damage to my retinas as it occurred, we have some new desktop curves for TBT and LCP.
They seem ok.
part of #9774

core: add desktop score curves for TBT and LCP

---

lighthouse-core/report/html/renderer/report-renderer.js

regressed in #10763 
this has a default value but needs to be over ridden for devtools, so it only broke there.

report: fix regression in report renderer for devtools

---

package.json
yarn.lock

taking over from #10764
pubads team released their 1.0 two weeks ago! 🎉 
And we shortly broke them! But that's now fixed: https://github.com/googleads/publisher-ads-lighthouse-plugin/pull/198 & https://github.com/googleads/publisher-ads-lighthouse-plugin/pull/199
And @jburger424 _just_ released a new version: https://www.npmjs.com/package/lighthouse-plugin-publisher-ads/v/1.1.0-beta.0
I tested this out with DevTools and we're looking great.
Thanks again @brendankenny and @jburger424

deps: lighthouse-plugin-publisher-ads@^1.1.0-beta.0

---

lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
lighthouse-viewer/test/viewer-test-pptr.js

This reverts commit d8d386dd8c7f7d585c1efd60fa73cb71bd4e64cd.
This isn't a must-have and there was two related breakages. (devtools view-trace button placement and #10774 ) The safest way to address regressions is to revert.
I'm backing this out for now so that I can tag a 6.0 from master.

report(metrics): [revert] use css grid so metrics are aligned (#10695)

---

lighthouse-core/lib/emulation.js

now matching canary's version. (my typical bump)
also made the OS versions a tad more recent. (
- my phone is android 10 but most moto g4 UAs i see are android 7.
- my desktop machine is mojave, not yet catalina. 10.14 is mojave.

core(emulation): bump chrome versions

---

lighthouse-core/audits/image-size-responsive.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/audits/image-size-responsive-test.js
lighthouse-core/test/results/sample_v2.json

**Summary**
In some contexts lighthouse uses a DPR of 2.625, which is a rather uncommon DPR, so to minimize the number of failures, we will quantize the original DPR to the lowest integer (or 1.5 if in between 1.5 and 2).
Fixes #10434 and #10802

core(image-size-responsive): quantize DPRs

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
docs/hacking-tips.md
proto/README.md
readme.md

based on the questions in https://github.com/GoogleChrome/lighthouse/pull/10662#issue-410413244
>  Quick q around the tests, typically for a new audit we have a unit test for the gatherer + audit, update the jest snapshots, then run a `yarn update:sample-json`?  Does the protobuf stuff come into play here, as in would `yarn compile-proto && yarn build-proto-roundtrip` be needed also? I also see an [Updating fixture dumps](https://github.com/GoogleChrome/lighthouse/blob/e38871621b858a755d018ea496efe0c6f0634b12/docs/hacking-tips.md#updating-fixture-dumps) doc and a `yarn update:sample-artifacts` command.
I've tried to update `CONTRIBUTING` a bit to hopefully capture that and removed some outdated advice. As with all docs updates obviously we could have much more here to help contributors, …

docs(contributing): add tips for audit and gatherer PRs

---

changelog.md

Fixes oversight in #10807 where two new contributors (both with significant contributions) weren't included in the changelog. See conversation starting in https://github.com/GoogleChrome/lighthouse/pull/10807#issuecomment-631531737.
Sorry @jayaddison and @chruxin!

misc(changelog): add missing 6.0.0 new contributors

---

readme.md

Summary
Change paid to freemium for PageSpeed Green in Lighthouse Integrations section.
Related Issues/PRs
There are no related issues/PRs

docs(readme): update PageSpeed Green description

---

lighthouse-core/audits/uses-rel-preload.js
lighthouse-core/test/audits/uses-rel-preload-test.js
lighthouse-core/test/network-records-to-devtools-log.js

**Summary**
Chrome won't reuse preload requests from other frames, so we shouldn't try to suggest them. Common example is a Wix page iframing another Wix page.
All their assets come from a shared origin (parastorage.com) but the root origins are different (customer-a.com and customer-b.com). 
fixes https://github.com/GoogleChrome/lighthouse/issues/10467

core(preload): ignore cross-frame requests

---

lighthouse-core/report/html/templates.html

Fixes a bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1086442
The `lh-tools` div that wraps the `lh-tools-button` can have a smaller width than its child when the view is squished.
Before:
After:

report: fix the width of the 3-dots menu in topbar

---

lighthouse-core/audits/legacy-javascript.js
lighthouse-core/audits/third-party-summary.js
lighthouse-core/lib/third-party-web.js
lighthouse-core/test/audits/legacy-javascript-test.js
lighthouse-core/test/lib/third-party-web-test.js

part of #10369
Still an informative audit, so no real change here.
@patrickhulce you mentioned having to write a `isThirdParty` function for a couple things. where do you want to put this fn?

core(legacy-javascript): use third-party-web for scoring

---

lighthouse-core/report/html/renderer/report-ui-features.js

**Summary**
This is a TODO cleanup form an earlier change which added `onMenuFocusOut`, at the time our TypeScript version (3.5.3) did not properly support the `focusout` event so a cast was required.
Since we have upgraded TypeScript (3.8.3) we no longer need the cast.
#10208

report: update onMenuFocusOut typing to remove FocusEvent cast

---

docs/variability.md
lighthouse-core/lib/median-run.js
lighthouse-core/test/lib/median-run-test.js

**Summary**
Brings the `computeMedianRun` logic over from lighthouse CI and spruces up the docs around running multiple times.
closes https://github.com/GoogleChrome/lighthouse/issues/10825

core(median-run): add computeMedianRun to lib

---

lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js

fixess #10734
I don't think these assertions are helping anything, so I removed all but one. I left reasoning in a comment.
For where the item became ambiguous w/o the node path, I added a `content` pattern check, which is much better.

tests(smokehouse): do not assert on flaky node path

---

docs/performance-budgets.md
lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
lighthouse-core/audits/byte-efficiency/total-byte-weight.js
lighthouse-core/audits/byte-efficiency/unused-css-rules.js
lighthouse-core/audits/resource-summary.js
lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
lighthouse-core/lib/i18n/README.md
lighthouse-core/lib/i18n/i18n.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/report/html/renderer/crc-details-renderer.js
lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/renderer/i18n.js
lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
lighthouse-core/test/audits/resource-summary-test.js
lighthouse-core/test/config/budget-test.js
lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
lighthouse-core/test/report/html/renderer/details-renderer-test.js
lighthouse-core/test/report/html/renderer/i18n-test.js
lighthouse-core/test/results/sample_v2.json
types/budget.d.ts

Chrome DevTools is changing its usage of KB (JEDEC, 1 KB = 1024 bytes) to the unambiguous KiB (IEC, 1 KiB = 1024 bytes). We want Lighthouse to be in alignment.
Some web.dev docs that need to update too:
and https://web.dev/performance-budgets-101/ (cc @khempenius)
______
We don't use `displayUnit: 'kb'` for anything. Do we want to just update all instances of it to `kib`? I imagine this would break 0 users.
I added a `title` to the byte divs ... yay or nay?

report: use KiB instead of KB

---

readme.md

**Summary**
This PR adds the [`cypress-audit`](https://github.com/mfrachet/cypress-audit) github project to the list of related projects.
The big picture:
The tools we can use nowadays to verify the quality of our applications are awesome. They help us get a huge amount of confidence about what we ship in production and alert us when some kind of regression occurs.
- [Cypress](https://cypress.io/) has made business oriented workflow verification super easy and fun
- [Lighthouse](https://developers.google.com/web/tools/lighthouse) has provided incredible tools to verify the performance of an application
- [Pa11y](https://pa11y.org/) provides multiple tool to control the accessibility state of our applications in a wonderful way
The problem is that they run in their own context and with …

docs(readme): adding cypress-audit to the related projects

---

lighthouse-cli/test/fixtures/perf/delayed-element.js
lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
lighthouse-core/audits/largest-contentful-paint-element.js
lighthouse-core/audits/layout-shift-elements.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/anchor-elements.js
lighthouse-core/gather/gatherers/trace-elements.js

**Summary**
There are a few gatherers that fail if the node ID fell out of memory. Adds a smoketest for the trace elements one since the CLS case is more common and reproducible than the LCP or anchor case.
Best repro: run on https://bonusi.soft-press.com/ to see that the category scores aren't `?` anymore
inspired by but does not address #10873 
fixes #10893

core: improve resilience of nodeId-dependent gatherers

---

lighthouse-core/report/html/report-template.html
lighthouse-viewer/app/src/lighthouse-report-viewer.js

Whenever I'm hacking on the viewer i always want this feature.  
I've also added a console.log in the viewer and the normal report.  We've had users definitely appreciate learning about this global, so I think it's valuable.

misc(viewer): expose LHR as __LIGHTHOUSE_JSON__

---

lighthouse-core/report/html/renderer/performance-category-renderer.js

In #6110 we removed this as there was already existing "may vary" text.
But then in cl/246846050 (may 2019) we updated the UI and got rid of PSI's text
So we should have restored this then, but didn't notice.

clients(psi): show disclaimer and calclink

---

package.json
yarn.lock

changes
* `6a5d0c72` flags: disable background tracing (https://github.com/GoogleChrome/chrome-launcher/pull/203)
* `d9154291` chore(deps): update typescript and types (https://github.com/GoogleChrome/chrome-launcher/pull/202)
* `88e49686` test: use strict version of assert functions (https://github.com/GoogleChrome/chrome-launcher/pull/201)

deps: upgrade chrome-launcher@0.13.3

---

lighthouse-core/scripts/legacy-javascript/run.js

context: https://github.com/GoogleChrome/lighthouse/pull/10937#discussion_r439037577

tests(legacy-javascript): exit code 1 on failure

---

lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

#10867 broke the 3p filter in two significant ways: zebra styling didn't take into account the CSS class approach we now have, and sub item rows weren't filtered w/ their 3p parent row.

report: fix zebra styling, sub item rows for 3p filter

---

lighthouse-core/test/report/html/renderer/report-ui-features-test.js

#10979 and #10978 merged too quickly :)

misc: fix merge error for subHeading -> subItemsHeading rename

---

lighthouse-core/report/html/renderer/performance-category-renderer.js
lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js

related: https://github.com/paulirish/lh-scorecalc/pull/21

report: use acronyms and round metrics for shorter calc url

---

package.json
yarn.lock

Fixes most of the URLs mentioned in #10908, but I noticed this one still errors: 99acres.com/aba-cherry-county-techzone-4-greater-noida-west-npxid-r4462
Closes #10948

deps(axe-core): upgrade to 3.5.5

---

lighthouse-core/report/html/report-styles.css

**Summary**
Bugfix: In the viewer it is currently hard to tell that 'See calculator' is a link, as it matches the same grey as the paragraph. PR removes this styling to mach other links in the audit results (light blue)
**Before**
**After**

report: don't dim disclaimer anchor links

---

.gitignore
lighthouse-core/test/test-utils.js
package.json
proto/scripts/json_roundtrip_via_proto.py

#6183 added this file and at the time it was tracked in source control
in #10557 we added the file to gitignore
now that it's ignored, seems like it can be in `dist` rather than nestled amongst tracked files.
-------
~i went with `dist` because #10994 but i suppose if we're not sharing artifacts between builds.... perhaps~ this makes more semantic sense in `.tmp` ~?~

tests: move proto roundtrip json to .tmp/

---

lighthouse-core/audits/largest-contentful-paint-element.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json

**Summary**
Makes the LCP element description make more sense.
fixes: #10977

i18n: adjust LCP element description 

---

.github/workflows/ci.yml
package.json

**Summary**
We don't run GitHub Actions on master right now which made it difficult to tell if [this failure](https://github.com/GoogleChrome/lighthouse/pull/11032/checks?check_run_id=819206666) was misconfiguration or related to the PR.
This will run our actions on master commits and all PRs with master as the base.
It also fixes the GitHub Actions failure caused by conflicting merges (https://github.com/GoogleChrome/lighthouse/pull/10995 and https://github.com/GoogleChrome/lighthouse/pull/11009)

misc: run GitHub Actions on master and PRs

---

lighthouse-core/scripts/internal-analysis/analyze-issues.js
lighthouse-core/scripts/internal-analysis/download-issues.js

**Summary**
Adds some tooling to measure our issue and PR response times. As for OKR purposes, I'm not sure we can get much better on initial response time for external issues. Our median response time is <2 hours which for a project this size across global timezones despite a mostly US team, is pretty dang low. I suspect that followup work to handle iterative responses will be where we find room for improvement.
Limitations:
- Only measures *initial* response times.
- Can't really account for situations where someone "takes over" review of a PR before the original assignee reviews. The new reviewer doesn't get credit for that review and the old reviewer gets unfairly labeled as not responding.
- Probably more.
```bash
Example Output
PRs
93.4% of PRs requested a review
72.8% of requests …
```

misc: add tools to track issue response time

---

package.json
yarn.lock

**Summary**
Lighthouse's codecov integration has been [flaky](https://codecov.io/gh/GoogleChrome/lighthouse) recently, and this is likely a result of using an old version of the codecov node uploader (3.6.5) as seen in a recent commit [here](https://api.travis-ci.org/v3/job/703537171/log.txt). This PR upgrades to the latest version (3.7.0) which, codecov support says, has a critical fix to the v4 upload path, providing more stability to the uploads.

deps: upgrade codecov to 3.7.0

---

lighthouse-cli/test/fixtures/ric-shim.html
lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js

**Summary**
The new requestIdleCallback smoke can be flaky in CI (and locally too, just rarer). Loosen the expectation quite a bit.
ref https://github.com/GoogleChrome/lighthouse/pull/11017#issuecomment-652060654

tests: relax requestIdleCallback smoke expectation

---

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
lighthouse-core/gather/connections/cri.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/page-functions.js
lighthouse-core/lib/tracehouse/trace-processor.js
lighthouse-core/test/gather/driver-test.js

We had a weak convention to annotate anything with branching/specific logic to handle new/old browsers with "COMPAT"
Having it makes it easier to take inventory of the special cases we have.
We were missing a few of these.
You'll also spot some stuff we can take action on. I've kept that out of this PR, but will followup with them.

misc: annotate version-specific logic with COMPAT comments

---

lighthouse-core/gather/fetcher.js

core(fetcher): ensure fetch doesn't cause unhandled promise

---

readme.md

**Summary**
automated-lighthouse-check.com has moved to [foo.software](https://www.foo.software). Updated the integration here accordingly.

docs(readme): update Foo integration

---

lighthouse-core/audits/seo/link-text.js

**Summary**
This change removes these Portuguese from the block list which mean "Home" or "Homepage", which seems to be a valid value for a link. I am new contributor and just signed a CLA!
This is identified from the Github issue #11026

core(link-text): removing inicio from blocklist resolves

---

lighthouse-viewer/README.md

corrected url parameter has been tested and working

docs: fix typo in viewer readme for loading json from url

---

.appveyor.yml
lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js

Fixes AppVeyor being stuck on Chrome 79 (hopefully).
AppVeyor has multiple Windows images, and most of them (including the default) are currently [stuck on Chrome 79](https://www.appveyor.com/docs/windows-images-software/#web-browsers). That seems like it can't be coincidence for the issues seen in PRs like #10976, so I assume something is breaking between downloading Chrome and chrome-launcher, and the default Chrome is being used regardless of what we try to use.
So let's just update to the latest Windows image and continue to use the default :)

tests: use latest windows image on appveyor

---

lighthouse-core/computed/metrics/cumulative-layout-shift.js
lighthouse-core/gather/gatherers/trace-elements.js
lighthouse-core/test/computed/metrics/cumulative-layout-shift-test.js
lighthouse-core/test/gather/gatherers/trace-elements-test.js
types/externs.d.ts

ref https://bugs.chromium.org/p/chromium/issues/detail?id=1094974

core(cls): manually add first shift event to score if it was ignored

---

docs/architecture.md

**Summary**
Bug fix: Apply corrections to incorrect link in architecture docs.

docs(architecture): correct link to description guidelines

---

lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
lighthouse-core/gather/gatherers/image-elements.js
types/artifacts.d.ts

**Summary**
We weren't collecting the correct `naturalWidth`/`naturalHeight` for images that use `srcset`. Added a smoketest for this and other `image-size-responsive` cases to the byte efficiency tester.
fixes #11095

core(image-elements): gather correct natural size for srcset

---

docs/readme.md

**Summary**
This PR fixes the issue in #11106 where the current programmatic use example in `readme.md` doesn't actually show log output. It also updates the description and code in the "Turn on logging" section.
#11106

docs(readme): fix logging in programmatic use code example

---

lighthouse-core/lib/page-functions.js

Fixes travis failures on master, and opens us up to land #11104 with coverage in GitHub actions

misc: ignore coverage of page-functions

---

lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-core/test/scripts/i18n/collect-strings-test.js

@exterkamp pointed out in https://github.com/GoogleChrome/lighthouse/pull/11068#discussion_r451682796 that text should never appear outside complex (`plural` or `select`) ICU argument blocks (whether string, whitespace, or other ICU arguments). Depending on the language, any text outside of the argument may also need to be part of what's changed depending on the replacement value.
This is an easy thing to catch without human review, so let's do that :)
Background docs:
- http://userguide.icu-project.org/formatparse/messages#TOC-Complex-Argument-Types
- go/icu-message-migration#message-should-not-have-text-including-whitespaces-andor-placeholders-preceding-or-following-icu-complex-syntax (just for googlers, but it's basically the same thing, just turns the "**Recommendation**" to required)

i18n: disallow invalid text outside complex ICU arguments

---

lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-core/scripts/i18n/count-translated.js

fixes the "`translation percentage calculation [brendankenny]`" part of https://github.com/GoogleChrome/lighthouse/issues/10791#issuecomment-630455884
for now just logs the percentage of messages that have been translated at the end of `collect-strings` (so also happens in `yarn update:sample-json`, etc), but we can follow up with bigger CI alerting or something in the future.

i18n: log the percentage of translated messages

---

package.json
yarn.lock

**Summary**
Updates `third-party-web` to 0.12.1
[0.12.0](https://github.com/patrickhulce/third-party-web/releases/tag/v0.12.0) brought some nice goodies, including the breaking change of removing the examples entry from the `nostats` bundle we use (should shrink bundle size a tad). We *could* hypothetically remove the try/catch since it no longer has *strict* validation of a domain existing in the string, but we still pass in some totally non-URLs that could basic basic URL validation, so I'm inclined to leave our `getEntity` as-is.
https://github.com/patrickhulce/third-party-web/issues/106

deps: update third-party-web

---

lighthouse-core/test/gather/gather-runner-test.js
types/externs.d.ts

Fixes an issue with `RecursivePartial<T>` and simplifies its implementation.
This came up when updating to tsc 3.9.7 in #11158 and I started playing with this `@ts-expect-error` (previously `@ts-ignore`):
https://github.com/GoogleChrome/lighthouse/blob/cc5c79547388282f51d1f517890e17ca71c5e0de/lighthouse-core/test/gather/gather-runner-test.js#L52-L57
`LH.Config.Json` is mostly optional by design, so it seemed like it shouldn't be too hard to make it work without the ignore (I failed, but let's ignore that, too :).
The current `RecursivePartial` was recursing into arrays and making the elements optional, which seems ok at first glance but it's almost never what you actually want. If you ask for an array with missing elements you (almost always) expect a shorter array, not a holey array …

misc: tighten RecursivePartial type

---

.github/workflows/ci.yml

part of #11194
Kind of a ridiculously small PR, but the code coverage stuff is a lot more involved.

tests: run test-viewer in github actions

---

lighthouse-core/test/lib/minification-estimator-test.js
yarn.lock

same as #10086 just 7 months later.
this gets rid of the ~last~ security advisory we have.
-------------
4 weeks back i put up #11043 which looks the same but brought up all sorts of other things. It was split into this PR, #11190 and #11191

deps(angular): update minor version of angular fixture redux

---

lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations.js

**Summary**
Updates the chromestatus expectations to the [new reality](https://github.com/GoogleChrome/chromium-dashboard/pull/936).
Alternatives Considered:
- Remove chromestatus entirely
- Replace chromestatus with another PWA
- Host the old version of chromestatus somewhere else
None of those seem that much better to me, but if one of those does to you I'd be happy to debate them in a new PR once we can safely land [our growing queue](https://github.com/GoogleChrome/lighthouse/pulls?q=is%3Apr+is%3Aopen+label%3Aland-when-ci-is-green) :)
https://github.com/GoogleChrome/chromium-dashboard/pull/936

tests: update chromestatus expecatations

---

lighthouse-core/gather/gatherers/image-elements.js

**Summary**
All in page functions need `/* istanbul ignore next */` or they will throw in CI when coverage is enabled.
Missed when I reviewed https://github.com/GoogleChrome/lighthouse/pull/11188 and not caught by CI because Travis isn't a required check and devtoolsbot autolanded it.
This should fix travis again

tests: istanbul ignore inpage function

---

lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-core/test/scripts/i18n/collect-strings-test.js

i18n: make double dollar validation less strict

---

lighthouse-core/audits/server-response-time.js

**Summary**
Just fixing a typo in a method name.

misc: fix typo in method name

---

lighthouse-core/audits/seo/font-size.js
lighthouse-core/gather/driver.js
lighthouse-core/gather/gatherers/seo/font-size.js
lighthouse-core/test/audits/seo/font-size-test.js
lighthouse-core/test/gather/gatherers/seo/font-size-test.js
types/artifacts.d.ts

Fixes #11210 (went with option `resolve many at once using push node to frontend method`)
Reduced the scope of the FontSize artifact by exporting only what we need, not an entire CrdpNode.
Test url http://misc-hoten.surge.sh/lh-ui-location-font-size/ from https://github.com/GoogleChrome/lighthouse/pull/9354 shows that results are unchanged.

core(font-size): remove deprecated DOM.getFlattenedDocument

---

readme.md

**Summary**
This PR updates the README.md adding 4 small projects I'm maintaining.
* lighthouse-viewer: lighthouse-reporter sourcecode packaged as an UMD & ESM npm package, to visualise your JSON reports. The process to copy the code from lighthouse to this package is automated.
* react2-lighthouse-viewer: This package is a React wrapper of `lighthouse-viewer`.
* svelte-lighthouse-viewer: This package is a Svelte wrapper of `lighthouse-viewer`.
* vue-lighthouse-viewer: This package is a Vue wrapper of `lighthouse-viewer`.
Add more options for visualisation of lighthouse JSON reports.
Sourcecode of the projects added: https://github.com/dvelasquez/lighthouse-viewer
**Summary**
This change just add 4 new projects to the **related projects** section.
* Repository: …

docs(readme): add related project: lighthouse-viewer

---

lighthouse-core/report/html/renderer/category-renderer.js
lighthouse-core/report/html/report-styles.css
lighthouse-core/test/report/html/renderer/category-renderer-test.js

**Summary**
This PR resolves issue [#7263 ](https://github.com/GoogleChrome/lighthouse/issues/7623) by updating the functionality of ```renderScoreGauge``` to show ```-``` in cases where all audits in a category have their ```scoreDisplayMode``` marked as ```notApplicable```. Two tests have been added to confirm the expected behavior.
Note: the screenshots below show what the dash looks like, using the plugin category as a test subject, but in actuality the plugin category will show a numerical score, not a dash, because it has no audits.
**-- Light Mode**
**-- Dark Mode**
**The previous design with `n/a` instead of `-` looked like this:**
fixes #7263

report: use dash gauge for categories with entirely n/a audits

---

lighthouse-core/audits/non-composited-animations.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/audits/non-composited-animations-test.js

Adds more failure reasons in addition to `Unsupported CSS Property`:

core(non-composited-animations): add more actionable failure reasons

---

lighthouse-core/report/html/renderer/i18n.js
lighthouse-core/test/report/html/renderer/i18n-test.js

**Summary**
This PR is a triple-down fix for https://github.com/GoogleChrome/lighthouse/issues/1056, which was partly fixed in https://github.com/GoogleChrome/lighthouse/commit/2f9ad6ffa8348f699933b211d7eb255a1b698f4a and https://github.com/GoogleChrome/lighthouse/pull/1086.
Turns out that `Intl.DateTimeFormat` itself too throws if the timeZone is invalid.
The issue itself was fixed in newer Chromium versions, as it affects eg. Node 10 but not Node 12
https://github.com/GoogleChrome/lighthouse/pull/1086
https://github.com/GoogleChrome/lighthouse/commit/2f9ad6ffa8348f699933b211d7eb255a1b6
https://github.com/GoogleChrome/lighthouse/issues/1056

core(renderer): improve the unknown timezone checks in util.js

---

lighthouse-core/audits/non-composited-animations.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/results/sample_v2.json

**Summary**
Links the *Avoid non-composited animations* audit to https://web.dev/non-composited-animations
Also fixes #11287
* https://github.com/GoogleChrome/web.dev/issues/3569
* https://github.com/GoogleChrome/web.dev/pull/3693

core(non-composited-animations): update the "learn more" link

---

lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/test/report/html/renderer/details-renderer-test.js
lighthouse-core/test/results/sample_v2.json

For #11261
Adds lh-link class to source-location render element. Needed to handle invalid URLs that didn’t create <a> elements.

report: handle invalid urls for source location items

---

lighthouse-core/gather/driver.js
lighthouse-core/lib/page-functions.js
lighthouse-core/scripts/benchmark.js
package.json

**Summary**
tl;dr - Updates the BenchmarkIndex using advice from v8 team and research in https://github.com/GoogleChrome/lighthouse/issues/9085.
See https://github.com/GoogleChrome/lighthouse/issues/9085 for the very long, full story. We unfortunately missed the boat for m86 DevTools but at least would be nice to get it in for the CLI and LightRider.
ref https://github.com/GoogleChrome/lighthouse/issues/9085

misc(benchmark): update BenchmarkIndex for m86 changes

---

lighthouse-core/computed/module-duplication.js
lighthouse-core/test/audits/byte-efficiency/duplicated-javascript-test.js
lighthouse-core/test/computed/module-duplication-test.js

avoids situations like this: 
which would then be shown oddly in the treemap app by highlighting just the big module, and the other modules are way too small to even see.

core(module-duplication): ignore smaller modules

---

lighthouse-core/audits/server-response-time.js
lighthouse-core/test/audits/server-response-time-test.js
lighthouse-core/test/results/sample_v2.json

**Summary**
Adds a details entry to show how much time was spent fetching the root document.
fixes #9671

core(response-time): add time spent to details

---

lighthouse-core/gather/gatherers/global-listeners.js
lighthouse-core/test/gather/gatherers/global-listeners-test.js

**Summary**
This is a change to the global-listeners gatherer to stop it from producing duplicate GlobalListener objects. (bugfix)
I opted for putting the change in the gatherer rather than the no-unload-listeners audit as I don't think there would be a use-case for having multiple GlobalListener artifacts with identical values. (As a sidenote I'm not sure if this is a bug with DOMDebugger or is some type of expected behaviour) 
Apologies if there are any steps that I missed and let me know any concerns or feedback you have.
#11284

core(global-listeners): dedupe duplicate events in GlobalListener gatherer

---

lighthouse-core/audits/seo/font-size.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/audits/seo/font-size-test.js
lighthouse-core/test/results/sample_v2.json

Fixes https://github.com/GoogleChrome/lighthouse/issues/9632

i18n: translate remaining strings in font-size

---

lighthouse-cli/test/fixtures/perf/preload_tester.js
lighthouse-core/audits/uses-rel-preconnect.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/audits/uses-rel-preconnect-test.js
lighthouse-core/test/create-test-trace.js

**Summary**
Filters out preconnect suggestions if the request wasn't part of the LCP graph. Given that we don't want folks to add any more than *2* preconnect links, showing a list of 40 isn't the greatest of messages to send :)
| Before | After |
| -- | -- |
|![image](https://user-images.githubusercontent.com/2301202/91089098-b2b48500-e618-11ea-9d0e-afd7292fe11f.png) | ![image](https://user-images.githubusercontent.com/2301202/91089126-bea04700-e618-11ea-86f8-8d9343083c73.png) |
closes #11283

core(preconnect): ignore unimportant origins

---

docs/throttling.md

**Summary**
Adds a CPU throttling guide with advice on how to calibrate multipliers. The provided ranges are really big but hopefully that conveys why results can be so variable ;)
ref #9085

docs: add CPU throttling guide

---

lighthouse-core/audits/seo/font-size.js
lighthouse-core/lib/i18n/i18n.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json
lighthouse-core/test/audits/seo/font-size-test.js
lighthouse-core/test/results/sample_v2.json

Fixes https://github.com/GoogleChrome/lighthouse/issues/9632
Follow up to https://github.com/GoogleChrome/lighthouse/pull/11327

i18n: add more translator strings to font-size

---

lighthouse-core/scripts/download-chrome.sh
lighthouse-core/test/chromium-web-tests/download-blink-tools.sh
lighthouse-core/test/chromium-web-tests/download-depot-tools.sh
lighthouse-core/test/chromium-web-tests/download-devtools.sh
lighthouse-core/test/chromium-web-tests/run-web-tests.sh

This is a followup from #11328 .. well, more of a disagreement. :p  
My understanding is that `set -u` is designed to error/exit whenever it encounters a variable that isn't set.
https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/#:~:text=set%20-u
http://www.bnikolic.co.uk/blog/bash-unbound-variable.html
Without it we need to _actively_ check all env vars to make sure they're set. But it's easy to miss one.
The only downside of this PR is that `Error: Environment variable DEPOT_TOOLS_PATH not set` is slightly more friendly of an error message than `DEPOT_TOOLS_PATH: unbound variable`. But they are equivalent.
@patrickhulce sgty?
( I also sprinkled in some set -x because those fetch/gclient operations are time-consuming and i wanted some visibility locally :)

tests(devtools): fail on unset/unbound env variable

---

lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js
lighthouse-core/audits/installable-manifest.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/manifest-parser.js
lighthouse-core/test/audits/installable-manifest-test.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/results/sample_v2.json

for #9683
exposes the app manifest url in the installable manifest audit

core(installable-manifest): expose app manifest url

---

lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
lighthouse-core/audits/service-worker.js
lighthouse-core/test/audits/service-worker-test.js

I was adding a final comment to #9683 about how to access the SW urls added in #11329 and realized we can flatten these audit details instead of nesting them in `details.items[0]`. Though we often use an `items` array in `'debugdata'` there's no reason we have to (many audits which use a single `items` `debugdata` element are that way for historical reasons, and it hasn't been clear whether it's worth breaking downstream scripts to simplify things in a major release).
Examples of audits using flat `details` are all the [accessibility audits](https://github.com/GoogleChrome/lighthouse/blob/22f227b5f6f042a05a6f36414aae6bab53a965af/lighthouse-core/test/results/sample_v2.json#L2263-L2271) and [`js-libraries`](https://github.com/GoogleChrome/lighthouse/blob/22f227b5f6f042a05a6f36414aae6bab53a96 …

misc: flatten new service-worker audit details

---

lighthouse-core/report/html/report-styles.css

Without an explicit width on this column with the potential for a large amount of content, there are some audit results that become unreadable.
**Summary**
This is a bugfix, as the results from some audits become unreadable depending on the content. I noticed this when examining SEO results under the audit 'robots.txt is not valid'. Lighthouse version 6.0.0. ~A width of 80% was chosen in this instance as it allows the 'Error' column to be read.~ 
**Update**: After feedback a `min-width` solution of 100px is a much better fit. 
**Before**:
**After**:
None?

report: set min-width on code table column

---

lighthouse-core/report/html/renderer/i18n.js
lighthouse-core/test/report/html/renderer/i18n-test.js

**Summary**
This is a bugfix.
About formatMilliseconds, Negative 0ms is displayed as 0ms.
In computing, some number representations allow for the existence of two zeros, often denoted by −0 (negative zero) and +0 (positive zero). 
However, in ordinary arithmetic, −0 = +0 = 0. 
https://stackoverflow.com/questions/7223359/are-0-and-0-the-same
fixes https://github.com/GoogleChrome/lighthouse/issues/11339

report: normalize -0 to 0

---

readme.md

**Summary**
Remove [PageSpeed Green](https://pagespeed.green) from Lighthouse Integrations section because the service is closing down.
There are no related issues/PRs

docs(readme): remove PageSpeed Green from related projects

---

lighthouse-core/audits/uses-rel-preconnect.js
lighthouse-core/audits/uses-rel-preload.js
lighthouse-core/lib/i18n/locales/en-US.json
lighthouse-core/lib/i18n/locales/en-XL.json

**Summary**
A few string fixes @exterkamp caught. Also found one in preload too.
fixes https://github.com/GoogleChrome/lighthouse/issues/11400

i18n: code-escape <link> in preconnect and preload

---

lighthouse-core/report/report-generator.js
lighthouse-core/test/report/report-generator-test.js

closes https://github.com/GoogleChrome/lighthouse/issues/11398
**Summary**
Added one row each for category to show `overall category score` in the output CSV report

report: show overall category scores in csv output

---

build/build-dt-report-resources.js

ref https://github.com/GoogleChrome/lighthouse/issues/11414#issuecomment-691281339
these files were added manually to our third party folder in CDT, but we destroy that folder when we roll, so we must make them.

misc(build): fix devtools tests by making empty type files

---

lighthouse-cli/test/fixtures/perf/preload_tester.js

ref the flaky smokes issue: #11341 
<details>
<summary>
basically a few of us have seen this smoke failure recently..
</summary>
```
✘ difference at uses-rel-preconnect audit.warnings.length
expected: 1
found: 2
found result:
{
"id": "uses-rel-preconnect",
"title": "Preconnect to required origins",
"description": "Consider adding `preconnect` or `dns-prefetch` resource hints to establish early connections to important third-party origins. [Learn more](https://web.dev/uses-rel-preconnect/).",
"score": 1,
"scoreDisplayMode": "numeric",
"warnings": [
"A preconnect <link> was found for \"https://fonts.googleapis.com\" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.",
"A preconnect <link> was found for \"https://fonts.gstatic.com\" but was not …
```

tests(smoke): fix preconnect flake w/ a non-locally installed font

---

build/build-bundle.js
clients/devtools-report-assets.js
lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js

This mirrors the change made in
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2398829/10/front_end/third_party/lighthouse/report-assets/report-generator.js
Note that there are additional changes to the devtools-dt-bundle.js header,
but I presume they are coming from Browserify. We could insert an
`globalThis.require=undefined` in the `BANNER` as specified in
`build-bundle.js`, but it is probably better if we fix that in a follow-up
PR.

clients(devtools): update report-generator.js to match DevTools changes

---

lighthouse-core/gather/gatherers/accessibility.js
types/artifacts.d.ts

small tweak.
we use `axeResult` in two places for two different things. I've renamed both to differentiate more clearly.
1. in the gatherer to refer to the [return value](https://github.com/GoogleChrome/lighthouse/blob/a58510583acd2f796557175ac949932618af49e7/lighthouse-core/gather/gatherers/accessibility.js#L54) of `axe.run()`. 
- axe-core calls this[ the "results object](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#results-object)", so i've added an s to here to align. 
2. the [artifacts.d.ts type](https://github.com/GoogleChrome/lighthouse/blob/a58510583acd2f796557175ac949932618af49e7/types/artifacts.d.ts#L165) that refers to an individual axe rule's results. 
- I've renamed it to `AxeRuleResult` to clarify it's just a single axe rule being described. axe-core [uses …

misc(axe): rename axe types

---

lighthouse-core/test/chromium-web-tests/download-blink-tools.sh

@adamraine ran into this.
without these checks, a second attempt would quietly skip most of this script, because there is a "cached" folder present.

tests: check for dependencies when setting up blink tools

---

lighthouse-core/lib/page-functions.js
lighthouse-core/test/lib/page-functions-test.js

made this when i was noodling on #10956  
the PR already had shared authorship, so i thought it best to just split this out separate.
ref #10914

tests(page-functions): add test for getNodePath

---

package.json
yarn.lock

3 commits, the 2nd of which is a nice quality of life upgrade for us.  makes running LH ~5s faster on my machine.
* [`08406b28`](https://github.com/GoogleChrome/chrome-launcher/commit/08406b2804c6efba7b602fb276397df00cd0041f) fix: preserve existing getInstallations output
* `f3669f45` perf: check default paths first when running on Mac (https://github.com/GoogleChrome/chrome-launcher/pull/209)
* `aef94948` docs: update defaultFlags() example for new API (https://github.com/GoogleChrome/chrome-launcher/pull/205)

deps: chrome-launcher to v0.13.4

---

build/build-bundle.js
build/build-utils.js
package.json

Saves ~32 KB in CDT bundle.
We did the same thing already for the viewer https://github.com/GoogleChrome/lighthouse/pull/9823, but the `build-bundle` never got the same treatment.
Here's what got trimmed:
```
minifying /Users/cjamcl/src/lighthouse/node_modules/axe-core/axe.min.js. saved 3.195 KB
minifying /Users/cjamcl/src/lighthouse/node_modules/js-library-detector/library/libraries.js. saved 26.963 KB
```
`axe.min.js` is quite big, and surfaced the fact that `minifyFileTransform` only worked if the amount of code fits in w/e Node decides to be the chunk size in the file streaming. Had to fix that.

misc(build): use terser on inline assets

---

lighthouse-cli/test/fixtures/byte-efficiency/tester.html
lighthouse-cli/test/fixtures/static-server.js
lighthouse-core/gather/gatherers/image-elements.js

**Summary**
A band-aid for #11450 to not set the natural dimensions if they were from a situation we know to provide incorrect natural dimensions. A proper fix for using the correct dimensions requires a much broader fixes across LH in #11454.
fixes #11450

core(image-elements): do not set untrusted natural dimensions

---

lighthouse-core/lib/page-functions.js

**Summary**
Another [v8 change](https://chromium.googlesource.com/v8/v8/+/5c0f7219bdb6793c4bb1f480f8ecce4acbb99139) introduced some unwanted variability into BenchmarkIndex. It doesn't actually affect our use case because the first 2-5 runs of BenchmarkIndex were unaffected (and ours is always just the first), but it's worth fixing and documenting if anyone ever wants to run this more frequently.
[Example page with this PR benchmark running](https://melodic-class.glitch.me/benchmark-nogc-fewer-datenow.html)
[Example page with master branch's benchmark running](https://melodic-class.glitch.me/benchmark-nogc.html)
(use Chrome Canary to see the stark difference) 
[crbug](https://bugs.chromium.org/p/v8/issues/detail?id=10954)

core(benchmarkindex): add workaround for Intel microcode fixes

---

docs/authenticated-pages.md
docs/puppeteer.md
docs/recipes/auth/README.md

**Summary**
Promised followup to #9170, adds a setCookie example and updates some of our pptr docs. @paulirish's prior PR #10277 did some of this already, so just a few more minor tweaks.
closes #11470

docs(auth): add setCookie example

---

lighthouse-core/lib/i18n/locales.js
types/externs.d.ts

bosnian and croatian are not aliases
https://unicode-org.github.io/cldr-staging/charts/37/supplemental/aliases.html
and [lingala](https://en.wikipedia.org/wiki/Lingala) isn't french.
----------
update: i'm still happy with these changes but this doc is fascinating. https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_matching.html
too bad a matching algorithm isn't available to us.

i18n: remove incorrect aliases

---

.npmignore

**Summary**
Our shiny new chromium webtests accidentally got included in our npm bundle :) I don't know if this is worthy of a 6.4.1 all by itself since installing all our dependencies takes *15 GB*, but nice to get in for sure.
**Before**
```bash
$ pkgfiles
PKGFILES SUMMARY
Size on Disk with Dependencies  ~15 GB
Size with Dependencies          ~14.7 GB
Publishable Size                ~64.4 MB
Number of Directories           1056
Number of Files                 5773
```
**After**
```bash
$ pkgfiles
PKGFILES SUMMARY
Size on Disk with Dependencies  ~15 GB
Size with Dependencies          ~14.7 GB
Publishable Size                ~16.7 MB
Number of Directories           100
Number of Files                 633
```
fixes #11511

misc: add chromium webtests to npmignore

---

lighthouse-core/report/html/renderer/i18n.js
lighthouse-core/test/report/html/renderer/i18n-test.js
lighthouse-core/test/report/html/renderer/report-ui-features-test.js

**Summary**
This changes how numbers with the '_byte_' itemType are formatted when viewed. 
Previously `2.5` and `1` when formatted with a granularity of `0.1` would be shown as `2.5 KiB` and `1 KiB`. Now they would be formatted as `2.5 KiB` and `1.0 KiB`.
This consistency can make it easier for some people when comparing sizes in a column as the decimal places will be aligned.
Fixes #11422

i18n: format bytes with consistent fractional width

---

docs/configuration.md

From my understanding of this documentation, there is a little bit more clarity which could be offered by different wording.
**Summary**
This change tweaks the wording and the type definition around the `extends` property of the configuration to explain exactly which values are allowed.
I feel that this could be useful since I am currently investigating some issues in a deployment of lighthouse and it was not particularly clear to me if our extension was valid or not at a glance.
I based this on some information I saw in #7344, including [a response](https://github.com/GoogleChrome/lighthouse/issues/7344#issuecomment-468067961_) on that issue.
There is also the (type definition)[/types/config.d.ts]. I'm trying to find the code handling this to see if any other …

docs(configuration): update some wording of the "extends" property

---

lighthouse-core/test/network-records-to-devtools-log-test.js
lighthouse-core/test/network-records-to-devtools-log.js

**Summary**
While chasing down the test issues that plagued #11410 it turned out to be a problem with how redirects were expressed in those tests (and the fact that they didn't gel with our `networkRecordsToDevtoolsLog`). I went hunting for how `networkRecordsToDevtoolsLog` did the redirects and realized we didn't have explicit tests since we do the autoverification (which is awesome feature), but thought it was a good time to add a few explicit examples.
ref #11410 
ref #11408

tests: add tests for networkRecordsToDevtoolsLog

---

lighthouse-core/report/html/renderer/details-renderer.js
lighthouse-core/report/html/renderer/element-screenshot-renderer.js
lighthouse-core/test/report/html/renderer/element-screenshot-renderer-test.js

report: do not show element screenshot if out of bounds

---

lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
lighthouse-cli/test/smokehouse/test-definitions/oopif/oopif-config.js
lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js

**Summary**
Some of the smokes have been failing the byte expectations on node 12 and pulling them up in DevTools it appears that the expectations even on node 10 were a little close to the edge already.
Also tweaked the CPU timeout because we keep hitting that in travis and we don't care about CPU activity in that smoketest at all.
This should pass every CI check we have 🤞

tests: reset smoke transferSize expectations to reality

---

lighthouse-core/audits/seo/crawlable-anchors.js
lighthouse-core/test/audits/seo/crawlable-anchors-test.js

**Summary**
An anchor with `window.open` in an onclick attribute and `mailto:` in a href attribute should be crawlable.
fixes https://github.com/GoogleChrome/lighthouse/issues/11443

core: mailto: anchor with window.open onclick is crawlable

---

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/test/audits/dobetterweb/dom-size-test.js
lighthouse-core/test/results/sample_v2.json

Fixes https://github.com/GoogleChrome/lighthouse/issues/11562

core(dom-size): remove formatNumber

---

lighthouse-core/lib/tracehouse/cpu-profile-model.js
lighthouse-core/lib/tracehouse/main-thread-tasks.js
lighthouse-core/test/lib/tracehouse/cpu-profile-model-test.js
lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js

**Summary**
The next phase of CPU profiler work got really out of hand really quickly, so stopping at a reasonable checkpoint. This PR improves the timing of sampling profiler data using other task information from a trace. The sampling profiler is still out of the normal flow of Lighthouse, so the test cases are the only actual usage.
Also a nice juicy debug function for task data which should help generate those nice "artistic" rendering of traces :)
ref #8526

core(tracehouse): use tasks to improve profiler timing data

---

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js

**Summary**
Yesterday https://github.com/chromium/chromium/commit/91d5452f4e9cca57edbf5f2a9d6b88ebc73033f8 converted mixed content warnings into upgrades by default which breaks our smoke tests. This makes us be able to land again.
Also contains a drive-by fix for a smoke test that has been failing in travis for a few weeks.

tests: update MixedContent test to match ToT

---

lighthouse-cli/test/smokehouse/report-assert.js
lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js

**Summary**
LCP in Canary has flipped to including removed elements by default.
https://chromium-review.googlesource.com/c/chromium/src/+/2480845
Long-term we should find a way to surface this element and/or potentially keep 6.x on the old LCP version, but for now we'll make PRs landable again.

tests: limit LCP element audit to m87 and earlier

---

lighthouse-core/index.js
lighthouse-core/runner.js
lighthouse-core/test/runner-test.js

**Summary**
The runner related changes for FR phase 1. See https://github.com/GoogleChrome/lighthouse/pull/11622 for how it will eventually come together. Goal here is to eliminate the reliance of the Runner on an explicit connection and abstract away the gathering.
ref #11313

core(runner): abstract gather phase out of runner

---

third-party/download-content-shell/download-content-shell.js

ref #11414 
Was 2 months old. Nothing was failing, but using an old Chromium isn't good for test validity.
Still punting on doing this in a dynamic way. Anyone know a good source to scrape this value from? One option is a shallow git copy (just the latest commit) and parse the commit message, but I think that'd be heavy duty since Chromium is so big. Maybe scrape https://chromium.googlesource.com/chromium/src.git -> click on latest commit -> parse commit position?

tests: update static content shell version

---

lighthouse-core/gather/gather-runner.js
lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js

**Summary**
Fixes a bug where non-HTML page load error would be reported for sites that redirect and resolve to a valid HTML document. The main document's mime type would be checked instead of the "final" document resolved from the redirect.
This change is needed because previously, false positive errors may be reported for valid pages that ultimately respond with HTML via redirects.
Fixes #11585
Introduced in #11042

core(gather-runner): use final document when reporting non-HTML error

---

docs/throttling.md

**Summary**
This is a documentation update. The current link on the `throttling` page links to a now-outdated version of the constants file, and I have updated that link to point to the current version (via `master` in the URL, please let me know if I should change that). I also split the links so one points to the values in use and one to the setting of the default.
I made this change because I am documenting some use of Lighthouse for @subito-it and I wanted to add a reference to the default value, and the file has been changed since the original link was written.

docs: update throttling reference

---

.github/workflows/ci.yml

Fixes broken unit tests in CI
Apparently `arduino/setup-protoc` gets the `protobuf` releases via the github API, but stops on the first page of results when looking for specific versions. The unit tests are failing because our 3.7.1 finally slipped out of the first page of releases into the second.
There's an [unmerged PR](https://github.com/arduino/setup-protoc/pull/9) that explains and fixes this (they faced the same issue for 3.6.1 back in July), so in the meantime we can use that branch.

tests: use setup-protoc bugfix branch

---

jest.config.js
lighthouse-cli/test/cli/bin-test.js
lighthouse-core/test/gather/gather-runner-test.js
lighthouse-core/test/runner-test.js

I've been complaining for a long time that jest has been automatically running all our code through babel even though we don't need any transpilation help, making debugging tests slightly more annoying.
Turns out it's really easy to turn off :)
Bonus, it saves some unit test time: on my machine about 8% wall clock time, 13% total cpu time. This is skewed by the incredibly slow `report-renderer-test`; if that test is skipped, turning off the transform makes `yarn unit-core` almost 20% shorter.

tests: remove unnecessary jest babel transform

---

.github/workflows/ci.yml
.github/workflows/devtools.yml

Context: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
I don't see any other dependency actions that need to be updated due to the looser `v*` pinning on them, but I guess we'll see.

tests: update github actions to use env files

---

lighthouse-core/report/html/renderer/report-ui-features.js
lighthouse-core/report/html/report-template.html
lighthouse-core/scripts/i18n/collect-strings.js
lighthouse-viewer/app/src/lighthouse-report-viewer.js

ref #11254, split off from #11545

report: treemap opener, ?dev for localhost viewer and treemap

---

lighthouse-core/lib/tracehouse/cpu-profile-model.js
lighthouse-core/lib/tracehouse/main-thread-tasks.js
lighthouse-core/test/lib/tracehouse/cpu-profile-model-test.js
lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js
types/externs.d.ts

**Summary**
Step 3 of ?? in the innocuous issue #8526 turned multi-quarter effort :)
This step further improves the timing data from CPU profiler samples by moving our `_findEffectiveTimestamp` improvements to a second pass that can utilize the *pair* of sampler events (which is required to understand parent/child relationships).
Next 4 steps in this saga...
- Proactively split continuous looking events
- Correctly handle negative timeDeltas
- Interpolate dropped samples
- Integrate the results into `main-thread-tasks` computed artifact
ref #8526 
Ultimately I'll want @paulirish to give this a final sign off but in the meantime I'd love for your eyes on this too @adamraine :)

core(tracehouse): improve CPU profiler timing refinement

---

package.json
yarn.lock

#9246 in june 2019 removed commitizen
nobody really used it including me (who originally added it)
this removes a remaining bit.
the PR Lint bot doesnt need any of this, but it relies on the `commitlint.config.js` and also the `.cz-config.js`

deps: remove cz-customizable as local dep

---

lighthouse-cli/test/fixtures/debugger.html
lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/expectations.js
lighthouse-core/gather/driver.js

**Summary**
Skip pauses doesn't actually skip pauses these days (maybe always?)... 😮 
see #11725 for more context
fixes #11725

core(driver): resume on debugger statements

---

.github/workflows/devtools.yml
third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run.js

Changed here: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2555060
I'd expect that change to fail this test https://source.chromium.org/chromium/chromium/src/+/master:third_party/devtools-frontend/src/test/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run.js;l=36;drc=b736005f57eccddf8dd024872552f1bfb0264682 but it didn't. @TimvdLippe I assumed `test/webtests` run in CQ, is that true?

tests: update failing trace webtest to use Tooltip module

---

lighthouse-core/config/config.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/test/config/config-test.js
lighthouse-core/test/gather/gather-runner-test.js
types/config.d.ts
types/gatherer.d.ts

**Summary (Why)**
Gatherer options as implemented today fundamentally clash with the more useful level of *artifact* options proposed by FR. They aren't being used anywhere in Lighthouse core and I doubt they ever caught on in custom config land (plugins can't define gatherers). Removing them now will ease the config transition plan with minimal cost.
**Summary (What)**
Removes support for gatherer options. We added them [three years ago](https://github.com/GoogleChrome/lighthouse/pull/4394) at the same time as audit options when we first started playing around with LR and originally planned to utilize them for scoped opportunities until we scrapped that plan before I/O that year and we never ended up using them since.
It's a breaking change because custom gatherers might have discovered …

core(config): remove gatherer options support

---

lighthouse-core/fraggle-rock/gather/driver.js
lighthouse-core/fraggle-rock/gather/session.js
lighthouse-core/gather/driver.js
lighthouse-core/test/fraggle-rock/gather/driver-test.js
lighthouse-core/test/fraggle-rock/gather/session-test.js
tsconfig.json
types/gatherer.d.ts

**Summary**
Builds on the work of #11623 #11633 #11685 to add the fraggle rock driver which is session aware. This is the thinnest implementation that will enable snapshot mode.
See #11622 and #11313 for the larger context.

core(fr): add fraggle rock driver

---

lighthouse-core/audits/accessibility/axe-audit.js
lighthouse-core/audits/autocomplete.js
lighthouse-core/audits/dobetterweb/dom-size.js
lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
lighthouse-core/audits/largest-contentful-paint-element.js
lighthouse-core/audits/layout-shift-elements.js
lighthouse-core/audits/unsized-images.js
lighthouse-core/gather/gatherers/link-elements.js
lighthouse-core/gather/gatherers/script-elements.js
lighthouse-core/test/gather/gatherers/link-elements-test.js
types/artifacts.d.ts

I was reviewing some code recently, noticed we're being very aggressive in some type casts of audit details to `/** @type {LH.Audit.Details.NodeValue} */`, removed some of them, and found a type error due to the `NodeDetails` changes in #11405 that wasn't flagged due to the casts hiding the difference between types (in this case, a `null` property in the artifact being used for an optional (but not nullable) property in the audit details).
We were using that cast because if strings are nested in an object, they're typically widened by tsc from the literal value to just `string`, which means they're no longer valid `AuditDetails` (which need a specific literal). But casts are dangerous (this is a pretty mild example of how they can go wrong), so we should avoid if we can.
There are two …

core: fix NodeDetails type mismatch

---

lighthouse-core/lib/dependency-graph/simulator/simulator-timing-map.js
lighthouse-core/lib/dependency-graph/simulator/simulator.js

**Summary**
@connorjclark I'm requesting your feedback here since you brought this up :)
There were many ways this could be done, but this felt like a decent balance between duplication in the right places, reading clarity, and type safety. I expect others might have different ideas of the tradeoffs though :)
fixes #11692

core(simulator): clearer intermediate timing types

---

lighthouse-core/test/chromium-web-tests/download-devtools.sh

locally i ended up with a stale CDT checkout that was giving me failures when running `yarn test-devtools`
this will make running  `yarn test-devtools` locally take longer, as the gclient sync/hooks take time.  however if there's been no changes to the repo since last run, it's free.
fixes #11678 
ref #11414

tests: refresh devtools checkout for webtests

---

lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js

The third-party facades smoke test is flaky in CI. The YT embed transfer size sometimes exceeds the bounds of the expectation.
Considering the test is already lenient with the number of subresources, I think it's best to make the transfer size super lenient as well.

tests: update flaky 3p facades smoke test

---

.github/scripts/git-get-shared-history.sh
.github/workflows/ci.yml

**Summary**
Master is failing CI due to some [git history changes](https://github.com/GoogleChrome/lighthouse/runs/1505055315). This reverts those changes from #11698 and just skips the check when secrets aren't available instead (same result that happens now for external contributors because the next step immediately fails).
ref #11698

misc(buildtracker): skip git deepen if no token

---

jest.config.js
lighthouse-cli/test/fixtures/static-server.js
lighthouse-core/fraggle-rock/api.js
lighthouse-core/gather/gather-runner.js
lighthouse-core/gather/gatherers/accessibility.js
lighthouse-core/gather/gatherers/gatherer.js
lighthouse-core/test/fixtures/fraggle-rock/snapshot-basic/onclick.html
lighthouse-core/test/fraggle-rock/api-test-pptr.js
tsconfig.json
types/config.d.ts
types/gatherer.d.ts

**Summary**
Builds on the work of #11623 #11633 #11685 #11742 to add the base fraggle rock runner for snapshot mode. A very basic form of snapshot mode is now runnable with this PR. See the end-to-end puppeteer tests for the example.
```js
const puppeteer = require('puppeteer')
const {snapshot} = require('lighthouse/lighthouse-core/fraggle-rock/api.js')
const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.goto('http://example.com')
await page.click('body')
const {lhr, artifacts} = await snapshot({page})
console.log('A11y score was', lhr.categories.accessibility.score)
```
See #11622 and #11313 for the larger context.

core(fr): add base fraggle rock snapshot runner

---

lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js

Example failure: 
Most of the `smoke_3_ToT` failures ive been seeing this afternoon are coming from this assertion.
-----------------
The animation reliably gets `kUnsupportedCSSProperty` (1 << 13) === 8192. (which is what we want)
Sometimes it also gets `kTargetHasInvalidCompositingState` (1 << 5) == 32. (but not always) Together they sum to 8224.
@adamraine and I have investigated `kTargetHasInvalidCompositingState` a few times and it's not actionable, in part because it shows up under very hard-to-predict circumstances.. Basically its presence is flaky
so this PR changes the smoketest expectation to handle it being there and not.
---
on the impl: i stated with /(8192)|(8224)/ but our report-assert doesn't expect to apply regexes to numbers, and I didn't want to deal with that. Overall …

tests(smoke): fix failureReasonsMask flake

---

.eslintignore

this will silence all the complaining in vscode. I can't figure out a nice way to actually turn the errors there into usable errors in `yarn lint`. Probably need to dig deeper into `@typescript-eslint/eslint-plugin`.
The alternative to completely ignoring is selectively turning off rules, as some of the remaining rules could be improvements (even if not enforced by our tests). Something like this in `.eslintrc.js`:
```js
{
files: ['*.d.ts'],
rules: {
'strict': 0,
'no-unused-vars': 0,
'no-undef': 0,
'max-len': 0,
},
},
```

misc: eslintignore .d.ts files

---

lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js

another smoke failure with ToT chrome.. this time around the new `warn-not-offline-capable`. There's an internal thread about this installability errorId. and here's the crbug: https://bugs.chromium.org/p/chromium/issues/detail?id=965802#c46
smoke failure example from #11790:
This PR doesn't do much except allow this smoketest assertion to be a bit more lenient.
fwiw i could not reproduce receiving this errorId locally

tests(smoke): handle warn-not-offline-capable in smoketest

---

build/build-pack.sh

when looking at CI logs i sometimes gotta inspect the `yarn build` output. ([example](https://github.com/GoogleChrome/lighthouse/pull/11764/checks?check_run_id=1497703846))
99% of it is all the filenames that went into the `npm pack`.  IMO these don't add value, especially not in the CI scenario.
now, no more noisy output. we just got a filename when it succeeds:
```
$ npm pack 2>/dev/null
lighthouse-6.5.0.tgz
```

misc(build): quiet the 'npm pack' command

---

.github/workflows/devtools.yml
lighthouse-core/test/chromium-web-tests/download-devtools.sh

updating this checkout everytime in GHA is proving difficult. it works locally, but for some reason errors in CI. so let's just not do it.
(before merging, verify things work by seeing GHA pass twice in a row with no code changes)

tests: do not update devtools checkout every time in ci

---

.github/workflows/publish.yml

Didn't mean to commit that "dir" change. worked without, but am surprised it breaks with it

misc: fix yarn install in nightly release

---

.github/workflows/ci.yml
lighthouse-core/scripts/dogfood-lhci.sh
lighthouse-core/scripts/github-actions-commit-range.sh
lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
lighthouse-core/scripts/test-lantern.sh
lighthouse-core/scripts/test-legacy-javascript.sh

**Summary**
None of our longer change-gated test suites have been running in GitHub Actions because we relied on `$TRAVIS_COMMIT_RANGE`. This is actually sort of a PITA to get from GitHub Actions so created a script that exports it to an env variable.
Aside: seems like there might be some overlap here with what the buildtracker git deepening script is doing?
ref https://github.com/GoogleChrome/lighthouse/pull/11767#issuecomment-741995619

tests: reenable change-related tests in github actions

---

lighthouse-core/test/chromium-web-tests/download-devtools.sh

small bugfix from #11804.  this repros reliably locally
using this pattern since we're using `-u`: http://www.bnikolic.co.uk/blog/bash-unbound-variable.html
--------
also, i added `-x` to this script as i've wanted to better understand how the output matches against the commands.  but @connorjclark if you'd rather remove that, go for it. i dun care a lot.

tests: fix unbound variable in download-devtools.sh

---

.github/workflows/publish.yml

I manually ran this action first, and know it _actually_ works now.
couple things I learned here:
* test actions in the Actions tab, using the `workflow_dispatch` or `push:` triggers, before merging
* `npm publish --dry-run` doesn't actually verify that the auth process works. wat.

misc: fix npm auth in nightly release

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-core/config/default-config.js

An alternative to #11812.
The theory is that the combo of some js and link preloading a css file is causing this load failure (see https://github.com/GoogleChrome/lighthouse/issues/11803#issuecomment-742131146). Previous to #11711 JS was blocked from running in the `redirectPass`.
Now JS is allowed, but css is still blocked from loading via `default-config`'s `blockedUrlPatterns`. Removing that one css load reliably caused ToT to "Aw, Snap!" for me locally, so we've essentially recreated that situation in redirectPass.
We can see if allowing CSS to load will go back to a bad Promise error but no Aw, Snap.

misc: temporarily allow css in redirectPass

---

lighthouse-cli/bin.js
lighthouse-cli/cli-flags.js
lighthouse-cli/test/cli/bin-test.js
lighthouse-cli/test/cli/cli-flags-test.js
lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
lighthouse-core/scripts/compare-runs.js
package.json
readme.md
tsconfig.json
types/externs.d.ts
yarn.lock

fixes #11720
Two major parts of the update:
- API updates. The biggest thing is that `.boolean()` no longer defaults to `false`, it defaults to `undefined`, while we've always relied on the default `false`. Also a bunch of other small improvements, like `.number()` and `--version` taking care of itself, etc
- Type updates. `@types/yargs` has gotten super sophisticated, accumulating type info in each step of the cli flag declarations
The combo of the two started forcing more options (e.g. `.boolean('flag').default('flag', false)` or `.option('flag', {type: 'boolean', default: false})`, then arrays+strings and choices and descriptions...I eventually just opted to switch everything over to the `options({flag1: opts, flag2: opts, ...})` format, which seems like a popular pattern looking at …

deps: update yargs to latest

---

lighthouse-cli/test/fixtures/perf/animations.html
lighthouse-cli/test/fixtures/perf/trace-elements.html
lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js

See https://github.com/GoogleChrome/lighthouse/pull/11791#issuecomment-742151090
`background-color` will have a compositor animation soon, and this will probably break our smoke tests again. Switching to `font-size` animations.

tests: use font-size for non-composited animations in smoke tests

---

lighthouse-core/audits/script-treemap-data.js
lighthouse-core/test/audits/__snapshots__/script-treemap-data-test.js.snap
lighthouse-core/test/audits/script-treemap-data-test.js

ref #11254
* `duplicationByPath` expects keys to be modules without a map's `sourceRoot`. 
* While fixing this, I also added a second fixture test using `coursehero-bundle-1`
* `coursehero-bundle-1` doesn't have a `.usage` file, so I removed `JsUsage` from the new test's artifacts. That of course error'd, since it is a required artifact. When I added an empty object instead (`JsUsage: {}`) I noticed a bug where the early bailout code https://github.com/GoogleChrome/lighthouse/blob/a589db542bc1a16baac411837bdbbc99bcd85bf3/lighthouse-core/audits/script-treemap-data.js#L170-L182 bailed out too early ... even though a map was present, it did not create a module tree. The intention was to add as much data to the root node as possible–during the original PR a refactor simplified things but …

core(script-treemap-data): fix sourceRoot & missing coverage bugs

---

docs/configuration.md
lighthouse-core/config/config.js
lighthouse-core/test/config/config-test.js
types/config.d.ts

**Summary**
Closes the loop on a few consequences @paulirish and I discussed of #11779. Breaking change to eventually allow extension of `lighthouse:mobile` and `lighthouse:desktop` but make it clearer when your `extends` property is valid.
**Before**
Any truthy value for a config's `extends` property would trigger extension of the default config.
**After**
Any value other than `lighthouse:default` for a config's `extends` property throws a fatal error.
ref #11779
https://github.com/GoogleChrome/lighthouse/issues/10910#issuecomment-644406979

core(config): only allow lighthouse:default extension

---

lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
lighthouse-core/config/default-config.js

closes #11800 now that the top-level-await chromium bug is fixed.
reverts much of #11799 but also takes into account the consoleMessages changes in #11663
also reverts #11813

tests(smoke): restore dbw_tester exception assertions

---

lighthouse-core/lib/network-recorder.js
lighthouse-core/test/lib/network-recorder-test.js

**Summary**
Ignores child frame requests for the new `isCriticalIdle` check. Solves the most important consequence of https://github.com/GoogleChrome/lighthouse/issues/11850 that will be introduced with 7.0
https://github.com/GoogleChrome/lighthouse/issues/11850

core(network): do not consider cross frame requests critical

---

lighthouse-core/report/html/renderer/element-screenshot-renderer.js
lighthouse-core/report/html/report-styles.css

this is an alternative to #11843  and #11844
(and here's the diff against #11843, which may be useful: https://github.com/GoogleChrome/lighthouse/compare/fps-tweak-viewport...fps-tweak-partytime )
okay a few things..
if our overlay element was placed higher up in the devtools DOM, `pos:abs` would work. (That's what it used there for [their equivalent "glassPane" component](https://source.chromium.org/chromium/chromium/src/+/master:third_party/devtools-frontend/src/front_end/ui/glassPane.css;l=7-16;bpv=1;bpt=0)).  
i don't see a good way to use `pos:sticky` without a nasty hack like `margin-bottom: -100vh;` to fix it [pushing down the report content](https://github.com/GoogleChrome/lighthouse/pull/11843/files#r544688266). 
`fixed` works well. DOM-wise the position of the overlay doesn't …

report: fix element screenshot position, lifecycle, styles

---

lighthouse-cli/test/fixtures/offline-ready-sw.js
lighthouse-cli/test/fixtures/offline-ready.html
lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js

in `offline-expectations.js` i revert back to the expectations we had previous to the false-positive hitting our offline-ready page ➡️  fixes #11800  
and then I add a new smoketest to make sure we reliably get the errorId if the serviceworker isn't doing offline right.➡️  fixes #11826

test: add warn-not-offline-capable smoketest

---

lighthouse-core/scripts/open-devtools.sh

(low priority) 
without the change on L17, the script errors our for me.
L25 is just making shellcheck happy
L47 i just wanted to reuse the same temporary chrome profile in these situations. @connorjclark @adamraine if the user-data-dir thang doesnt work for your workflows, no big deal. happy to add on my own. :)

misc(scripts): fix unbound variable in open-devtools

---

lighthouse-core/report/html/renderer/util.js

fixes #11873 
restored the handling for the report's "Device" string for v6.
I redid the conditionals using ternaries, but that bit has the same logic.

report: convert v6 emulatedFormFactor to v7 formFactor

---

readme.md

**Summary**
This PR updates the README.md adding a lighthouse plugin that I'm maintaining: [lighthouse-plugin-crux](https://github.com/dvelasquez/lighthouse-plugin-crux)
The main difference with the already added `lighthouse-plugin-field-performance` is that this plugin uses the CrUX API instead of the PageSpeed Insights API. The CrUX API is faster since it doesn't need to run a full Lighthouse run to return the results.

docs(readme): add plugin: lighthouse-plugin-crux

---

lighthouse-treemap/test/treemap-test-pptr.js
lighthouse-viewer/test/viewer-test-pptr.js

**Summary**
Increases the test timeout on our pptr tests that don't have an explicit one. I've only personally ran into it for treemap but conceptually same thing applies to viewer.
https://github.com/GoogleChrome/lighthouse/pull/11915/checks?check_run_id=1650996600#step:11:21

tests: increase treemap pptr timeouts
