.eslintrc, .gitignore, audits/minify-html/index.js, audits/service-worker/index.js, audits/time-in-javascript/index.js, audits/viewport-meta-tag/index.js, helpers/browser/driver.js, helpers/dom-parser.js, helpers/remote-file-loader.js, helpers/test-loader.js, index.js, lib/processor.js, package.json, test/bigrig_tests.js
Another update for #4 
This gets `npm run lint` (and `npm test`) running without error. 90% whitespace changes, with a few tweaks to the eslint rules.
Added two TODOs for @paulirish since I'm not entirely sure what's going on there and git blame blames him :)
There are remaining eslint warnings. I'll follow up in #4
=> linting fixes

.eslintrc, audits/service-worker/gather.js, audits/time-in-javascript/audit.js, audits/viewport-meta-tag/audit.js, helpers/browser/driver.js, lib/processor.js
should settle everything outstanding in #4 
- enforces line length of 80
- enforces single quotes (allows backticks as long as something is being interpolated (see https://github.com/eslint/eslint/issues/5234 for that whole debate))
- settles on `resolve`/`reject` (instead of `res`/`rej`) for Promise executor signature since that's winning the current popularity contest in the repo
=> last eslint fixes

.eslintrc
I really wanted to make 80 work, but I was having a hard time keeping things look readable and still satisfying 80.
My example in particular is the highlighted line in this block:
That line is 84 characters long, and there isn't really a proper way to shorten it. :/
So... I think the answer is yes.. but to confirm: ya'll ok with 100?
=> 100 char line length.

gatherers/js-in-context.js, helpers/manifest-parser.js, index.js, test/manifest-parser-tests.js
@paullewis 
- some changes were made to the parser to retain more information through the manifest parsing. Each node in the manifest tree retains its original raw value, the parsed value, and the "[developer warnings](https://www.w3.org/TR/appmanifest/#dfn-issue-a-developer-warning)" the spec specifies when you make a mistake, even when recovered. The spec is very forgiving, though, so I've tweaked some things to make sure they still work even while issuing a warning. The original linear `_logs` is dropped in favor of the warning being associated with the erroneous manifest entry.
- changes from above mean that at every item in the manifest you have to hit `.value` to get the parsed value of that node. Kind of annoying, open to ideas there. See changes to test for example.
- ported tests …
=> add web app manifest parsing gatherer

audits/manifest/icons-192.js, helpers/manifest-parser.js, helpers/network-recorder.js
also fix a bug where `Array.include` was being called (not yet in Node stable)
=> validate manifest colors with DevTools's color parsing code

cli.js
Also moved `Usage` to the top per common CLI convention
The `pkg` is inferred by `meow`, so no need to explicitly specify it.
=> simplify meow usage in the CLI

audits/manifest/icons-192.js, test/audits/manifest/icons-192.js
also fixes a TypeError in the icon-192 audit when a manifest has an icon with no list of sizes
=> add a few more icon-192 tests

.eslintignore, .eslintrc, audits/html/theme-color.js, extension/.eslintrc, gatherers/manifest.js, gatherers/theme-color.js, gatherers/viewport.js, helpers/browser/driver.js, helpers/element.js, index.js, readme.md, test/audits/html/theme-colors.js, test/audits/manifest/theme-color.js, test/audits/mobile-friendly/viewport.js, test/helpers/browser/driver.js, test/helpers/element.js
started with @gauntface's #79 PR as a base, and reworked with the DOM approach.
matt, would love your review on this!
=> Audit for theme-color <meta>

helpers/browser/driver.js
The big change here is that driver.connect() doesn't provide access to the cri object. 
That means all protocol work must go through driver.sendCommand, etc. This allows us to branch more elegantly between our node and extension setups.
A subsequent patch will split `browser/driver.js` into two classes, one for protocol, the other for driver. This will enable solid encapsulation such that all driving APIs don't need to differentiate between chrome.debugger and cri.
=> Only protocol layer should be accessing the cri API.

.eslintignore, audits/audit.js, audits/html/theme-color.js, audits/manifest/background-color.js, audits/manifest/icons-192.js, audits/manifest/icons.js, audits/manifest/name.js, audits/manifest/short-name.js, audits/manifest/start-url.js, audits/manifest/theme-color.js, audits/mobile-friendly/viewport.js, audits/offline/service-worker.js, audits/performance/first-meaningful-paint.js, audits/security/is-on-https.js, closure/closure-type-checking.js, closure/third_party/DevtoolsTimelineModel.js, closure/typedefs/Artifacts.js, closure/typedefs/AuditResult.js, closure/typedefs/Manifest.js, closure/typedefs/ServiceWorkerVersions.js, metrics/performance/first-meaningful-paint.js, package.json, test/audits/manifest/icons-192.js
Just on `audits/` before this PR gets unreviewable, and to check in before I keep going.
- `closure/typedefs/` - type declarations for our own types, e.g. the set of all artifacts from the gatherer stage, audit outputs, etc
- `closure/third_party` - type declarations for code from third party modules. In this PR, only a subset of `devtools-timeline-model` was required
uses gulp because we need some transformation pipeline to alter the files so we can hide node_modules from Closure, and Closure doesn't take input off of stdin, so reusing their gulp plugin.
=> add closure type checking (to audits/ only for now)

.eslintignore, helpers/extension/driver.js
We were missing `helpers/extension/driver.js` from the eslint pass, so made the `.eslintignore` more specific.
single semicolon fix to pass tests
=> be more explicit to ensure we aren't accidentally eslintignoring directories

audits/audit.js, audits/manifest/background-color.js, audits/manifest/exists.js, audits/manifest/icons-192.js, audits/manifest/icons.js, audits/manifest/name.js, audits/manifest/short-name.js, audits/manifest/start-url.js, audits/manifest/theme-color.js, cli/printer.js, closure/typedefs/Artifacts.js, closure/typedefs/AuditResult.js, closure/typedefs/Manifest.js, extension/app/scripts.babel/app.js, extension/app/scripts.babel/pwa-check.js, extension/app/styles/lighthouse.css, gatherers/manifest.js, helpers/manifest-parser.js, test/audits/manifest/background-color.js, test/audits/manifest/exists.js, test/audits/manifest/icons-192.js, test/audits/manifest/icons.js, test/audits/manifest/name.js, test/audits/manifest/short-name.js, test/audits/manifest/start-url.js, test/audits/manifest/theme-color.js, test/manifest-parser-tests.js
=> pipe manifest fetch/parse error strings up for display

audits/html/meta-theme-color.js, closure/closure-type-checking.js, closure/third_party/WebInspector.js, helpers/element.js, helpers/manifest-parser.js, helpers/network-recorder.js, helpers/web-inspector.js, test/audits/html/theme-colors.js
also puts all of the current code to get `chrome-devtools-frontend` able to be imported into lighthouse (the other place was `network-recorder.js`) into one file for easier maintenance.
fixes #92
=> pull out CSS color validator and validate <meta> theme-color

launch-chrome.sh
=> Get chromium path from env var on Linux

.travis.yml, launch-chrome.sh, test/download-chrome.sh
Follow-up to #119. Also added node version 5.0 to .travis.yml. 
I kept the `--disable-setuid-sandbox` flag because the command fails without the flag on my linux workstation. Curiously enough, travis tests [still pass if I leave out the flag](https://travis-ci.org/deepanjanroy/lighthouse/builds/120651147#L750). I'm not sure why that is the case.
=> Use launch-chrome.sh in travis tests

cli.js, index.js
=> Makes nice error message when Chrome isn't launched

launch-chrome.sh
We don't use `gpu-benchmarking` right now. And if we were to, our extension wouldn't be able to set it.
As such, let's keep it out of the flags.
=> launch-chrome: don't need gpu-benchmarking

helpers/browser/driver.js, helpers/emulation.js
Not waiting doesn't cause any issues though.
curious why is this treated as fire and forget ?
These create side-effects, shouldn't we wait for it to resolve ? (or) is it taken care by `chrome.once('ready')` ?
=> Wait for promises to resolve in device emulation

closure/closure-type-checking.js, closure/conformance_config.textproto, closure/typedefs/Artifacts.js
adds the straightforward [JS conformance tests](https://github.com/google/closure-compiler/wiki/JS-Conformance-Framework) that we probably want to follow to the closure check. Already caught one bug where I had missed one of the properties on `Artifacts`; fixed below.
Currently the conformance tests are warning only, they don't fail the compile, but we can step that up if we want. 
There is one warning generated here that I didn't fix. The checks don't like this use of [`this`](https://github.com/GoogleChrome/lighthouse/blob/843d145e0b13099bb3b34078a61930e6a37d01f9/audits/audit.js#L52) I think because of some combination of inheritance and the fact that they're static methods.
We could disable the 'unknown this' check or rearrange audit.js to be a bit simpler. I'm open to either.
=> add JS conformance tests to Closure Compiler checking

aggregators/will-get-add-to-homescreen-prompt/index.js, audits/manifest/short-name-length.js, extension/app/scripts.babel/pwa-check.js, index.js, test/audits/manifest/short-name-length.js
Starts to solve #69 with a basic assumption of 12 chars max, taken from the [old Chrome extension manifest docs](https://developer.chrome.com/extensions/manifest/name#short_name) (which presumably evolved into the format we have today).
(Also partially just learning how to write an audit).
=> added short-name-length check

gatherers/offline.js, helpers/extension/driver.js
The `const` is causing an issue because it's globally scoped, and that causes an error to be thrown. This now causes a rejection in the driver, and the offline gatherer also recovers more gracefully from such cases.
PTAL @samccone @brendankenny
=> Fixes repeat runs of the XHR

metrics/performance/first-meaningful-paint.js
The logic to get the main frame was a bit twisted before. Now we simplify and get a much more reliable accounting of frames.
* Events are in sorted order. No need to sort
* First navigationStart event will be on the main frame. When we find that, we set our mainFrame ID
* We use that to filter all metric events
=> simplify fMP metric identifying main frame

closure/closure-type-checking.js, extension/app/popup.html, helpers/traces/devtools-timeline-model.js, helpers/web-inspector.js, metrics/performance/first-meaningful-paint.js
Stomps the global. I figure:
1. We already do that in the Network Manager.
2. It only stomps the background page for the extension, and the CLI we could clean?
Generally had to do this because @paulirish's existing version relies on `vm`, which doesn't translate well if the script itself contains `fs.readFileSync` or `require`, since the former isn't supported in browserify, except via brfs, and only for string paths known at build time, and the latter only works if the module is already resolved by browserify, which undermines the sandbox.
Upside:
:shipit:
=> Allows for FMP in extension.

launch-chrome.sh
helps make #179 more obvious, as the Offline checks currently on master will always fail with a fresh profile
=> make launch-chrome script always use fresh profile

extension/gulpfile.babel.js
Broken extension build was due to chrome-remote-interface [updating their ws version](https://github.com/cyrus-and/chrome-remote-interface/commit/05319536f0ad83036da0e6b88fc41028dc6deadd). The newer version of ws [moved `bufferutil` and `utf-8-validate` to devDependencies](https://github.com/websockets/ws/commit/49b11093e9a009e5305dcde7003d3a896b2811dc), which apparently, when [combined with the conditional `require`](https://github.com/websockets/ws/blob/4263f26d4dbe27e781c41a1ddfe3dab87dd9e1dc/lib/BufferUtil.js) for them, breaks browserify. [ws issue](https://github.com/websockets/ws/issues/659) (closed as WAI)
Rather than doing fine grained ignoring, just ignoring CRI altogether, since the extension overrides any methods using it to use `chrome.debugger` anyways.
=> don't bundle CRI with extension

gather-scheduler.js
In the gatherer-scheduler refactor, this flag got lost.
=> Fixes mobile flag

helpers/traces/devtools-timeline-model.js, helpers/web-inspector.js, package.json
followup to #190 
- require `WebInspector` into `devtools-timeline-model.js`
- some rearranging within `web-inspector.js` to make imports and stubbing out more explicit. This involved pulling in contents of `devtools-monkeypatches.js` and `api-stubs.js` directly instead of requiring them from `devtools-timeline-model` to keep things a little more sane. Some of the mocked APIs were getting redefined up to four times by us (e.g. `WebInspector.moduleSetting`) and their final value depended on the order in which the mocking files were called over the entirety of lighthouse since `WebInspector` lives in the global scope. We also get some nice things out of this like a single spot to enable/disable `Runtime.experiments`.
Some changes we may want to upstream to `devtools-timeline-model`, but …
=> reorganization of devtools frontend imports and mocking

helpers/browser/driver.js, helpers/extension/driver.js
Here's a bunch of successful ACKs with empty return objects:
And here's the data coming back from more interactive commands:
Formatting bikeshedding welcome. :)
=> Log the protocol ACKs/returns 

extension/app/scripts.babel/app.js, helpers/extension/driver.js
If any unexpected detaches happen like devtools opens etc, we set appropriate state.
fixes the last of #152
=> Extension should listen for random detaches

src/lib/drivers/driver.js, src/scheduler.js
Reintroduces `WAIT_FOR_LOAD` (I know) so that we can call a run to `about:blank` and the driver will choose `Page.navigate` or `Page.reload` as it does in other cases. This will mean that the extension shouldn't get into an uncanny valley as it was before.
Fixes #229
=> Refactor driver call to about:blank for SW reload.

src/gatherers/accessibility.js, src/gatherers/gather.js, src/gatherers/html.js, src/gatherers/https.js, src/gatherers/manifest.js, src/gatherers/theme-color.js, src/gatherers/viewport.js, src/scheduler.js
Fixing #227. 
Visually compared lighthouse results on pwa.rocks before and after this change. Everything seems to be working fine.
=> Rename scheduler phases and move tasks to after profiling

.gitignore, scripts/netdep-graph-png.sh, scripts/netdep-graph.sh, scripts/netdep_graph_json.py
Output the clovis network dependency graph as json. 
Usage:
```shell
> lighthouse --save-artifacts
> CHROMIUM_SOURCE_PATH=$HOME/chromium/src scripts/netdep-graph.sh artifacts.log
> CHROMIUM_SOURCE_PATH=$HOME/chromium/src python scripts/netdep_graph_json.py
```
=> Get json network dependency graph

.travis.yml, scripts/netdep_graph_json.py, scripts/process_artifacts.py, scripts/pylint.conf
Fixes #261 
I disabled import related errors because of our sys.path.append hack before we import clovis modules. Also disabled missing-docstring because it's too much work do document every function and bad-continuation because pylint indent continuation rules make no sense to me.
=> Add pylint conf and clean up python code

cli/printer.js, src/lib/drivers/cri.js, src/lib/drivers/extension.js, src/lib/log.js, src/lib/web-inspector.js, src/scheduler.js
unrelated fixes (probably easier to look at individual commits, sorry) to things I ran into while integrating lighthouse with an existing CI:
- ~~switch back to continuous builds now that Linux dev is on m52~~
- mock out `WebInspector.ConsoleMessage` for a code path hit when resource type and mime type don't match and `WebInspector` wants to log about it
- get log levels working again. `npmlog.log` is bound to `npmlog`, so can be called independently, but the log `level` can only be set on the parent `npmlog` object, so it has to be exposed.
=> three fixes

src/lib/drivers/cri.js, src/lib/drivers/extension.js
This closes the tab on the CLI when disconnected.
I've made the disconnect method always return a promise - it doesn't need to, but feels cleaner / safer in the long run.
=> Close tabs behind you

src/lib/drivers/cri.js, src/lib/drivers/driver.js, src/lib/drivers/extension.js
also moves `evaluateAsync` to use `driver.once` instead of `driver.on` to automatically remove its event listener
=> add driver.once for single-time event listening

extension/dtm-transform.js, extension/gulpfile.js, extension/package.json
Fixes #269 by adding a browserify transform that intercepts the require for devtools-timeline-model and sets it to use the local version. Means we don't have to maintain a fork of Speedline, and when dtm has upstreamed its changes that make it friendlier to Lighthouse we can drop this transform altogether.
/cc @paulirish
=> Fixes Speedline for extension

src/audits/offline/service-worker.js, src/gatherers/service-worker.js
The check of matching registrations was naïve, and doesn't work if the provided URL isn't the root of the origin. This fixes it by getting the origin for the tested URL and uses that to filter down the registrations. It also removes the duplicated logic from the audit, which doesn't need to do the filtering again!
Fixes #272
=> Improves SW gather

cli/index.js, src/audits/security/redirects-http.js, src/gatherers/gather.js, src/gatherers/http-redirect.js, src/lib/drivers/driver.js, src/lighthouse.js, src/scheduler.js
A bunch of things:
1. Requires that #267 lands first, because it needs the Security domain enabled.
2. It's a bit ick insofar as it has to clear the backlog of Security events, so there's a fairly bleh timeout that waits up to 3 seconds to make sure we've got all the security events back.
3. It's not clear about whether we want to just trust `schemeIsCryptographic` or if we want to push on the security level to be 'secure' (which it doesn't seem to be in a bunch of cases, though why is unclear!).
4. This also includes an additional round-trip to `about:blank` and then to the HTTP version of the URL. You can't XHR the HTTP version because it triggers the Mixed Content warnings and is blocked by Chrome. We have baked in the second round trip to the scheduler to test the SW, so either we …
=> Checks for HTTPS redirect

extension/app/src/popup.js, src/lib/drivers/driver.js, src/lib/drivers/extension.js
fixes #275
So far we still require 52. However we may be able to support 51. Will require some investigation.
For this work I recommend these resources:
* history of protocol.json: https://github.com/ChromeDevTools/devtools-frontend/commits/master/protocol.json
* blame of protocol.json: https://github.com/ChromeDevTools/devtools-frontend/blame/master/protocol.json
Also driveby fixed two nitpicky issues
=> compatibility docs.

cli/printer.js, closure/typedefs/AuditResult.js, extension/app/pages/scripts/lighthouse-report.js, formatters/accessibility.js, formatters/formatter.js, formatters/partials/accessibility.html, report/report-generator.js, report/styles/report.css, report/templates/report.html, src/audits/accessibility/aria-valid-attr.js, src/audits/audit.js, test/formatter/formatter.js, test/formatter/formatters.js
Works with a11y audit atm, but this change will allow support for CRP etc.
=> Adds formatters for pretty and report outputs

src/lib/drivers/driver.js
Ran into this bug again when QAing our extension build. 
Reproduced the issue on tip of tree, chrome 52.
I'd love to diagnose further but do not have the time
=> minor: var declaration for trace result.

report/report-generator.js, report/scripts/lighthouse-report.js, report/styles/report.css, report/templates/report.html, src/aggregators/address-bar-is-themed/index.js, src/aggregators/is-performant/index.js, src/aggregators/is-secure/index.js, src/aggregators/is-sized-for-mobile-screen/index.js, src/aggregators/will-get-add-to-homescreen-prompt/index.js, src/audits/accessibility/aria-valid-attr.js, src/audits/manifest/short-name-length.js, src/audits/mobile-friendly/display.js, src/lighthouse.js
Fixes #313 
> **PWA Section**
> Will Get Add to Homescreen Prompt => User can be prompted to Add to Homescreen
Done.
> Re-sort them to match order in doc -- basically: offline, perf, secure, homescreen, splashscreen, omnibox, mobilefriendly
Done by rearraging them in `./src/lighthouse.js`; I didn't want to bake in explicit ordering at this point.
> We need descriptions for a few other aggregators:
> omnibox: The browser address bar can be themed to match your site. A theme-color [meta tag](https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android?hl=en) will upgrade the address bar when a user browses the site, and the [manifest theme-color](https://developers.google.com/web/updates/2015/08/using-manifest-to-set-sitewide-theme-color?hl=en) will …
=> Redesigns report

src/audits/performance/input-readiness-metric.js, src/lib/traces/tracing-processor.js
Followup from #309 
Moves the tracing-processor calls from input readiness metric into the existing trace-processor module
=> clean up traceviewer hankypanky

cli/index.js, module/index.js, test/module/index.js
some of the module tests meant to fail weren't testing what they were supposed to be testing: `assert.error` isn't a thing, but the exception thrown on that would be caught, and so the test would succeed. Those tests now successfully throw on success, pass on failure. Bonus: unit tests now run 10 seconds faster as the last module test doesn't run until timeout.
Also wraps the entire lighthouse module code in a Promise so any early failures (e.g. in last module test which throws a `TypeError` on attempting to set flags on a string) are actually caught in the lighthouse promise chain and not as a normal exception.
=> fix error catches in module tests

scripts/launch-chrome.sh
Just a quick fix for users with multiple Chrome Canary... I think this happened when they have Chrome Canary in `/Applications` and the not unmounted `/Volumes/Google Chrome Canary` which they used to install, like this for example - 
+ When there are multiple paths, simply choose the first1
+ Previously, the bug was that it chose all the items concatinated and the assumption was that there was only 1 Google Chrome Canary
+ (close #311) (close #339)
=> Fix Chrome canary path

src/scheduler.js, test/module/index.js
This fixes #345, at least for now.
A more future-proof solution would be to use something like this: https://www.npmjs.com/package/json-stringify-safe. Although I do wonder if we should remove the option of saving artifacts altogether.
=> Break circular ref in NetworkRequest

package.json
Was poking about on [npm](https://www.npmjs.com/package/lighthouse) and noticed these references hadn't been changed  :wave:
=> Update package.json homepage & issue URLs from Big Rig

formatters/accessibility.js, src/audits/accessibility/aria-allowed-attr.js, src/audits/accessibility/aria-valid-attr.js, src/audits/accessibility/color-contrast.js, src/audits/accessibility/image-alt.js, src/audits/accessibility/label.js, src/audits/accessibility/tabindex.js
+ Fix length for (failed on ...) messages - too long - displayed in `Nodes:`
+ Fix displaying nodes in Nodes list
Master:
This Branch:
=> Fix accessibility pretty print

extension/app/src/lighthouse-background.js, extension/app/src/report-loader.js
Use a message from results page to extension background to know it's ready. Once it is ready, respond back with results.
=> Remove timeout from report

test/src/gatherers/critical-request-chains.js
no object wrapping neccessary.
fixes #372 
use w=1:  https://github.com/GoogleChrome/lighthouse/compare/fixcritpathtests?w=1
=> fix critical path tests. 

closure/closure-type-checking.js, closure/third_party/node.js, closure/typedefs/Aggregation.js, closure/typedefs/Artifacts.js, closure/typedefs/AuditResult.js, package.json, src/aggregators/aggregate.js, src/aggregators/is-performant/index.js, src/audits/performance/critical-request-chains.js, src/audits/performance/first-meaningful-paint.js, src/audits/performance/speed-index-metric.js
@brendankenny 
This gets us up and running again, at least with warnings, not errors.
This works around [#954](https://github.com/google/closure-compiler/issues/954) in an interesting way, but I have some thoughts on fixing that properly too.
=> get closure-type-checking running again

.gitignore, .travis.yml, package.json, readme.md, test/module/index.js
also removes smoke tests from what are (ostensibly) unit tests
one issue: anything using driver.evaluateAsync is totally broken under istanbul, since it instruments the code we then send over to the page to run, which is obviously is broken in that context. Some initial efforts to fix didn't work, but not a problem with this PR since we have no test coverage on those gatherers yet :)
=> add istanbul test coverage reporting

.travis.yml, scripts/launch-chrome.sh
Fixes #378 
Unzip the folder, then check if the sandbox is named `chrome_sandbox` still, if so move it to `chrome-sandbox`. This way if things are fixed upstream then the script shouldn't cause an error later.
=> Launch Chromium without an abort

cli/printer.js, report/report-generator.js, src/audits/performance/first-meaningful-paint.js
This matches up with the impl in traceviewer: https://codereview.chromium.org/1998063002
We require layouts that have fewer than 200 invisible text characters, via `approximateBlankCharacterCount`
Also we report all fMP candidate paints in the extendedInfo.
Here's a run with https://acrobat.adobe.com/us/en/sign.html?promoid=HM85XGHT which has some nice FOIT
=> fMP metric includes new blank webfont signal

.eslintignore
`npm run lint` fails if you've run `npm run coverage` before :)
=> eslintignore istanbul coverage report

cli/index.js, src/lighthouse.js, src/scheduler.js
Another step toward #293. Try it out! e.g.
```
lighthouse --audit-whitelist=first-meaningful-paint,speed-index-metric
```
To get the audit names without going into each audit individually, use the
```
lighthouse --list-all-audits
```
cli flag to list all available audits.
Some issues:
- scoring is not what you'd expect from a whitelist right now—aggregators will have to renormalize to account for audits you didn't run—but @paulirish wants to move forward with this as-is since there are several other aggregator/formatter changes in motion requiring further changes already
- right now you can't opt out of tracing/network recording, even if no audits need them, so the first pass always runs. This could be fixed, but will need some special handling since those artifacts don't come from …
=> add audit whitelisting, eliminating page reloads if not required

src/scheduler.js
The new JS-disabled audit leaves the page inert, which is okay for the CLI as it closes the tab, but the extension does not. This PR adds a final reload to the end of the run to "reset" the page. An improvement to this would be to only do this in the extension context, or if the JS-disabled run has definitely happened.
PTAL @paulirish
=> Adds final reload

src/audits/manifest/short-name-length.js, src/audits/manifest/short-name.js, test/src/audits/manifest/short-name-length.js, test/src/audits/manifest/short-name.js
=> Fix bug when short_name is not present name is not used for audit

extension/app/src/lighthouse-background.js, extension/gulpfile.js, scripts/traceviewer-module-index.html, src/lighthouse.js, third_party/traceviewer-js/index.js
Since #414 landed the extension tries to load audits and gatherers dynamically. This makes sure that it can.
=> Fixes extension after #414

lighthouse-core/package.json
Since lighthouse only uses a simple less than test we can pull the semver version back. I'm specifically picking 4.3.3 because of other packages that I care about being locked to this, this can be technically be pulled back further.
Let me know if this is an ok thing to do.
=> relax constraint to be greater than 4.3.3.

lighthouse-core/driver/index.js, lighthouse-core/runner.js, lighthouse-extension/gulpfile.js
Original PR: #423 
+ When lighthouse is run for the first time, pass.gatherers is modified from string to require('gatherer')
+ From the second time, require(GathererClass) would become require('[object object]') and throws
+ This fix returns the original gatherer when it's already required and in memory
(Close #423)
=> Fix requiring gatherers and fix gulp watch for extension

lighthouse-core/package.json
Speed line currently includes v1.1.4 but lighthouse requires 1.0.19, make them the same here.
=> make the devtools-timeline-model version be the same as speedlines

lighthouse-core/driver/gatherers/critical-request-chains.js, lighthouse-core/formatters/critical-request-chains.js, lighthouse-core/formatters/partials/critical-request-chains.html, lighthouse-core/test/driver/gatherers/critical-request-chains.js, lighthouse-core/test/formatter/critical-request-chains.js
[@slightlyoff said](https://twitter.com/slightlylate/status/741884269144989700):
> if you have 100k of gzipped JS in your critical path, your users are gonna have a bad time
And I was like "we have a notion of critical path, why not add transfer size for the chain?"
wdyt?
=> Adds transfer size to CRC

lighthouse-core/driver/gatherers/critical-request-chains.js, lighthouse-core/test/driver/gatherers/critical-request-chains.js
XHRs are high priority ([priority doc](https://docs.google.com/document/u/1/d/1bCDuq9H1ih9iNjgzyAL0gpwNFiEP4TZS-YLRp_RuMlc/mobilebasic)), but they dont meet our definition of critical
You can see here a few oddballs like the `.json` and `api/` calls.
=> Exclude XHRs from critical chains.

lighthouse-core/driver/gatherers/critical-request-chains.js, lighthouse-core/test/driver/gatherers/critical-request-chains.js
Since #326 was fixed in chromium we can remove our hack to fix redirect priorities.
Fixes #326
=> Remove redirect hack 

lighthouse-core/lib/empty-stub.js, lighthouse-core/lib/traces/tracing-processor.js, lighthouse-core/package.json
helps with #428 
@zhaoz 
hard codes the path relative to `third_party/src/traceviewer-js`, but worth the tradeoff (and yet another incentive to fix our traceviewer import issues upstream)
=> remove empty-module as a dependency

.travis.yml
`npm run unit` is currently run twice (three times, if you count the coverage run) on travis since there is no `package.json` in lighthouse-cli/
=> remove redundant `npm run unit` in travis config

lighthouse-core/driver/gatherers/critical-request-chains.js, lighthouse-core/lib/network-recorder.js, lighthouse-core/lib/web-inspector.js, lighthouse-core/package.json, lighthouse-core/test/driver/gatherers/critical-request-chains.js
Working on #454. `lib/traces/devtools-timeline-model` unit tests are currently failing and need to be updated to match the new devtools code. Can someone confirm whether I can just change the tests, or whether we need to adapt our code elsewhere?
=> Update devtools version and resource priority handling

lighthouse-core/package.json
Now devtools-timeline-model also uses the same sub-dependency of
> "chrome-devtools-frontend": "1.0.401423",
=> bump dtm to latest. 

lighthouse-core/package.json
Updates the downstream dependency tree to match our dtm and frontend versions
Also readies us to use perceptualSpeedIndex (and passing a dtm model into speedline directly). Both of these will come later.
=> bump speedline to 0.2.2

lighthouse-cli/index.js, lighthouse-cli/test/cli/index.js
=> --list-all-audits and --list-trace-categories no longer require a url.

.eslintignore
right now `npm run lint` is running over code in lighthouse-extension/, which is fine if you've never built the extension before (like on travis, where the extension is built last), but fails if you have built it.
the extension has its own lint task anyways, and the task is run in the `gulp build` task in our travis.yml, so ignoring the whole directory is fine
=> eslintignore extension code at root level

lighthouse-cli/index.js, lighthouse-cli/printer.js, lighthouse-core/core.js, lighthouse-core/driver/drivers/cri.js, lighthouse-core/driver/drivers/extension.js, lighthouse-core/index.js, lighthouse-core/lib/asset-saver.js, lighthouse-core/lib/log.js, lighthouse-core/package.json, lighthouse-extension/app/src/lighthouse-background.js, lighthouse-extension/gulpfile.js
@paulirish @zhaoz 
reapplying #430 but avoiding the really messy rebase or merge.
Basically the same PR, changes are
- moving the url-is-http warning to core/index.js so it's logged (debug logs nothing without `debug.enable(something)` first)
- enabling extension logging to the same level npmlog had as its default
- a few log titles here and there to avoid `undefined`s in the output
the last bullet point still isn't perfect, but we can tweak in the future
=> Change logging library to debug (take 2)

lighthouse-core/lib/traces/tracing-processor.js, lighthouse-core/test/lib/traces/tracing-processor.js
This might not be exactly what we need after we figure out how we want to report Estimated Input Latency/TTI, but makes existing EIL calculations and #450 correct. I'll add a better writeup in the (in progress) design doc.
This PR makes EIL clip any tasks that overlap the edges of the window of interest. For tasks that start before the window, a shorter task is equivalent to a clipped one, so they can just be shortened. For tasks that start during (or before) the window and end afterwards, it's more complicated.
Quick representation of a **100ms window** and a **200ms task** starting at **40ms into the window**:
The intensity of the green at any point represents the time an input task queued at that moment would have to wait until it could be executed. Since the task is 200ms long, an …
=> correctly clip tasks to window given to getRiskToResponsiveness

lighthouse-core/audits/is-on-https.js, lighthouse-core/test/audits/is-on-https.js, lighthouse-core/test/core.js
fixes #479 
In #353, the `HTTPS` artifact changed to returning an object with a `value` property, but the audit was still checking if the `HTTPS` artifact was truthy or not. Since an object is always truthy, the audit was always passing.
=> fix HTTPS audit to actually fail on insecure URLs

lighthouse-core/formatters/critical-request-chains.js, lighthouse-core/test/formatter/critical-request-chains.js
=> Handle 'about:*' URLs in the CRC formatter

.gitignore, lighthouse-core/closure/closure-type-checking.js
Either node or closure mangles the error output on macOS. This is a dirty fix that saves the error log to a file so it can be examined after the run.
@brendankenny @paullewis WDYT?
=> Save closure errors to a file

_install_deps.js, package.json
in #486 we discovered that the `npm install -g GoogleChrome/lighthouse` is failing. 
It appears to fail because the postinstall script runs before the `npm --prefix` will actually work.
As a result the -core and -extension installs are a noop.
This PR changes the postinstall to use a small helper script. (It's in JS, though it would work the same in bash).
In the case that install fails, we'll see something like this in the terminal:
The user can then run that command manually, and it will work.
(I can't say I love this solution, but I cannot find another mechanism to get `npm install -g GoogleChrome/lighthouse` working.)
=> Install child folder deps through helper script

lighthouse-cli/scripts/run-smoke-tests.sh, lighthouse-cli/test/fixtures/smoketest-config.json, lighthouse-core/driver/gatherers/offline.js, lighthouse-core/lib/emulation.js
The smoketest is now massively faster. We use a custom config and audit-whitelist for our run to be super fast.
* Before: 23.7s
* After: 7.3s
-----------------------
There was flakiness with the works-offline test. As it turns out `network.enable` must be on before offline is triggered.
=> Faster smoketest. Fix Flaky works-offline gather

lighthouse-core/runner.js, lighthouse-extension/app/src/lighthouse-background.js, lighthouse-extension/gulpfile.js
The audit and gather resolving in the extension browserify was broken after the recent commits.
This fixes things.
The primary fixes are ` const config = new Config(configJSON, false);` in the extension and tweaking a `../` to `./` and vice versa. Love it.
=> Fix (and speed up) extension browserify post-config refactor.

lighthouse-core/audits/cache-start-url.js, lighthouse-core/closure/typedefs/Artifacts.js, lighthouse-core/config/default.json, lighthouse-core/driver/gatherers/cache-contents.js, lighthouse-core/test/audits/cache-start-url.js, lighthouse-core/test/driver/gatherers/cache-contents.js
I'm opting to collect the contents of the caches from the page as a gatherer and then check in the audit. It's not foolproof because of the fact that the SW could realistically rewrite the start URL to something else in the cache, but this way at least avoids making one gatherer rely on another.
=> Checks cache for start URL

lighthouse-core/driver/drivers/cri.js
Was testing out Chrome headless with Lighthouse. :)
It works except for two things.
1) It doesn't support creating new tabs. filed at https://bugs.chromium.org/p/chromium/issues/detail?id=626847
2) the devtools.screenshot trace category doesnt capture anything. (However other screenshots do work)
Anyhow, this fixes #1 by letting us fallback to reusing the same tab if the protocol wont allow us to create a new one.
=> Fallback to reuse existing tab

lighthouse-core/driver/gatherers/cache-contents.js
The `caches.open` throws an exception on HTTP, but it wasn't caught so the asyncEvaluate times out at 60s. 
you can see the 60s gap here.
Luckily we have the 60s safety catch:
```js
// If this gets to 60s and it hasn't been resolved, reject the Promise.
asyncTimeout = setTimeout(
(_ => reject(new Error('The asynchronous expression exceeded the allotted time of 60s'))),
60000
);
```
The results only had a "No" without any exception, so I'm not sure if the gather was handling this reject correctly? Might have some followup.
cc @paullewis
=> Fix cachecontents gather on HTTP pages

lighthouse-core/aggregator/aggregate.js, lighthouse-core/audits/estimated-input-latency.js, lighthouse-core/audits/first-meaningful-paint.js, lighthouse-core/config/default.json, lighthouse-core/test/aggregator/aggregate.js
A few per tests were using toFixed values (string) where the expected values were numbers. The aggregator was silently discarding them.
I have:
1. Fixed audits so they output the correct type
2. Changed the aggregator to throw on incorrect types so that we don't regress
=> Fixes scoring

lighthouse-cli/scripts/run-smoke-tests.sh
Until #518 is landed, I think we should comment out this flaky smoketest, as it's failing ~25% of the time on travis.
=> Skip offline-ready smoketest

lighthouse-core/driver/gatherers/cache-contents.js, lighthouse-core/driver/index.js, lighthouse-core/lib/log.js, lighthouse-core/runner.js, lighthouse-extension/app/popup.html, lighthouse-extension/app/src/lighthouse-background.js, lighthouse-extension/app/src/popup.js, lighthouse-extension/app/styles/lighthouse.css, lighthouse-extension/gulpfile.js
Video: https://gfycat.com/RequiredLinearDalmatian
<a href="https://gfycat.com/RequiredLinearDalmatian">
</a>
This exposes events on `log.ev` that you anyone can add listeners to. 
@crhym3 I don't think this'll give you everything you need, but maybe you can add a CLI flag to ship progress data another way?
=> Show the test progress

lighthouse-core/audits/manifest-display.js, lighthouse-core/test/audits/display.js
=> Require that a user has *any* display value set.

lighthouse-core/audits/audit.js, lighthouse-core/audits/estimated-input-latency.js, lighthouse-core/audits/first-meaningful-paint.js, lighthouse-core/audits/time-to-interactive.js, lighthouse-core/audits/user-timings.js, lighthouse-core/closure/typedefs/Artifacts.js, lighthouse-core/config/default.json, lighthouse-core/config/index.js, lighthouse-core/driver/gatherers/screenshots.js, lighthouse-core/driver/gatherers/speedline.js, lighthouse-core/driver/index.js, lighthouse-core/test/audits/estimated-input-latency.js, lighthouse-core/test/audits/first-meaningful-paint.js, lighthouse-core/test/audits/time-to-interactive.js, lighthouse-core/test/audits/user-timing.js, lighthouse-core/test/config/index.js, lighthouse-core/test/driver/gatherers/speedline.js, lighthouse-core/test/driver/index.js, lighthouse-core/test/runner.js
Config for passes now accepts a parameter `traceName` (formerly ignored parameter `loadDataName`), allowing each pass to store its own trace.
Currently, the name for the pass needed by an audit is hardcoded in the audit. This should probably be abstracted further in a future PR.
PTAL :)
=> Allow each pass to save its own trace

lighthouse-core/driver/drivers/driver.js, lighthouse-core/driver/drivers/extension.js, lighthouse-core/driver/index.js, lighthouse-core/test/driver/fake-driver.js
We reload at the end so the page doesn't have disabled JS. However we hold up reporting everything until this reload is done, which is kinda unnecessary.
This changes it (almost) to a fire-and-forget. 
The last reload will now happen in parallel with the reporting our run results.
Numbers: It makes the run from ~3-9 seconds faster depending on how long navStart to window.onload is.
It does change behavior a touch though. Typically the reload takes longer than reporting, so the program terminates a few seconds after the report is done. (once the reload/disconnect promises resolve).
Thoughts?
=> Do the last (clean-state) reload in parallel with finishing the report

lighthouse-cli/index.js, lighthouse-core/lib/log.js
When cli is run with the output directed to stdout, it may become quite inconvenient for the progress status messages to pop up on the stdout as they are being mixed with the audit formatted results.
This change makes both `status` and `statusEnd` events be emitted on `log.events`, and replaces `console.time` and `console.timeEnd` with outputting the timers using lighthouse logger, so that all timer messages go to the same place, usually stderr.
In any event, this change makes it easier to control and redirect status messages in the same way all other logging is done.
=> cli: use logger to print status messages

lighthouse-cli/scripts/run-smoke-tests.sh
This is the same as #528 but against master, as the SW smoketest still stuck on our shared port SW origin matching issue #532 
I want this in before we pull #531 again
=> smoketest: do full default run against our basic html page.

lighthouse-core/driver/gatherers/service-worker.js
SW check needs ports.
Fixes #532
=> Handles ports for SW.

lighthouse-cli/index.js, lighthouse-core/index.js, lighthouse-core/lib/environment.js
- Moved compatibility check to ./lib/environment.js so it can be re-used in
different modules
- Uses the vm module to check for the spread operator.
- Fixes #540
=> Improve check for used JS features

lighthouse-core/gather/drivers/cri.js, lighthouse-core/gather/drivers/driver.js, lighthouse-core/gather/drivers/extension.js
This started as moving the driver event handling (`on`, `once`, and `off`) to the base `Driver` class so the subclasses could share an implementation since browserify offers an `EventEmitter` polyfill. However, it turned into a refactor of the extension driver to simplify it and to make sure we remove any extension API listeners we add in setup. These are mostly separated into the two commits so it may make sense to review separately.
Earlier speculation was that some of our fleeting extension bugs are due to event listeners that are never removed since `chrome.debugger.*` persists between runs even when the debugger attachment does not. I'm seeing fewer exceptions with extension runs now, but it's difficult to tell for sure since the bugs are difficult to reproduce reliably.
=> cleanup of extension driver attachment and event registration

lighthouse-core/closure/closure-type-checking.js, lighthouse-core/scripts/run-mocha.sh, package.json
This changes a few things, but ultimately should have far more effective test output. Less noise, more signal, especially in Travis.
* Fixes missing stacks bug (described below)
* Simplify `npm run watch` to reuse `mocha --watch`
* Closure warnings not outputted on Travis
* Eslint warnings not outputted on travis
* Coverage run of mocha uses different reporter so we don't have such long travis logs
* Restore `cli-unit` test to only test those files.
A curious bug crept in that looked something like this:
```sh
mocha  */test/**  # no stack attached to exception
mocha  lighthouse-core/test/** # has full stack 
```
This PR will make sure any mocha exceptions always have complete stacks.
=> Refactor npm scripts 

lighthouse-core/lib/traces/tracing-processor.js, lighthouse-core/test/lib/traces/tracing-processor.js
Fixes one of the remaining extension issues—occasional infinite loading spinner on the report page.
The conditional for the EIL calc loop was sometimes going one higher than it should due to floating point issues. This would only affect the 100th percentile result (so wasn't used in any calculations (yet)), but would end up putting an `Infinity` in the `extendedInfo` due to a divide by 0. It then was `JSON.stringify`ed and `JSON.parse`d, which roundtrips `Infinity` to `null`, thus giving the `TypeError: Cannot read property 'toFixed' of null` exception causing the infinite spinner.
=> fix off-by-one error causing Infinity in 100% EIL

lighthouse-cli/index.js
--version returned undefined, easier to ask people what version they have of the cli
=> Fixed version argument in yargs to display current cli version

lighthouse-cli/index.js, lighthouse-cli/printer.js, lighthouse-core/gather/drivers/cri.js, lighthouse-core/gather/drivers/driver.js, lighthouse-core/gather/drivers/extension.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/lib/log.js, lighthouse-core/runner.js
Now a full run from the CLI looks like this:
This PR also removes the Timer logging, that we probably don't need anymore, as it's somewhat duplicated against the debug module's time output.
And this PR fixes marking status for audits, so they are accurate. Here's the end of a --verbose run:
Lastly, we don't want to log the trace output, so there's a little conditional for "IO.read" which is our trace.
=> Clean up CLI logging, moving protocol work to --verbose.

lighthouse-core/audits/estimated-input-latency.js, lighthouse-core/audits/first-meaningful-paint.js, lighthouse-core/audits/time-to-interactive.js, lighthouse-core/audits/user-timings.js, lighthouse-core/config/index.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/gather/gatherers/screenshots.js, lighthouse-core/gather/gatherers/speedline.js, lighthouse-core/lib/asset-saver.js, lighthouse-core/test/audits/estimated-input-latency.js, lighthouse-core/test/audits/first-meaningful-paint.js, lighthouse-core/test/audits/time-to-interactive.js, lighthouse-core/test/audits/user-timing.js, lighthouse-core/test/config/index.js, lighthouse-core/test/gather/gather-runner.js, lighthouse-core/test/gather/gatherers/screenshots.js, lighthouse-core/test/gather/gatherers/speedline.js, lighthouse-core/test/lib/asset-saver.js, lighthouse-core/test/runner.js, readme.md
Fixes #555 
With https://codereview.chromium.org/2161583004 the trace object we get is slightly different, with the trace events array as a `traceEvents` property on the object instead of as the object itself. This was causing all -1s in the performance test as they couldn't understand the updated trace format.
On the simplest level, this PR moves `artifacts.traces` from something like
```js
artifacts.traces = {
defaultPass: {
traceContents: [/* trace events */]
}
}
```
to 
```js
artifacts.traces = {
defaultPass: {
traceEvents: [/* trace events */],
metaData: { /* trace meta data */}
}
}
```
and then the rest of the PR is just fixing import and export code to handle both the new and the old trace object formats.
=> handle new trace object format

lighthouse-core/audits/cache-start-url.js, lighthouse-core/test/audits/cache-start-url.js
This may fix #557, however I was unable to reproduce the exception, even trying a manifest with "start_url: undefined` and missing the property entirely.
@surma can you try this out?
=> Fix exception on missing manifest start_url

lighthouse-core/config/index.js
alternative to #562. Followup from brendan's commit.
Motivation is mostly that it feels uncomfortable to pass the array into `cleanTrace`, have it return the object, ignore its return value, and then use the parent object next.
Work for you, @brendankenny ?
=> cleanTrace acts on the whole trace

lighthouse-core/audits/manifest-background-color.js, lighthouse-core/test/audits/background-color.js, lighthouse-core/test/audits/cache-start-url.js, lighthouse-core/test/audits/display.js, lighthouse-core/test/audits/exists.js, lighthouse-core/test/audits/icons.js, lighthouse-core/test/audits/name.js, lighthouse-core/test/audits/short-name.js, lighthouse-core/test/audits/start-url.js, lighthouse-core/test/audits/theme-color.js
In #558 we found that some tests were building mock parsedManifest artifacts incorrectly. As a result, we didn't test for a case for a found manifest but missing `start_url` and consequently threw an exception. 
This PR has two commits. The 1st commit (12bfb3a) migrates all manifest-related unit tests to properly use the manifestParser, and does not rely on mock artifact objects.
After implementing, I discovered it can be trivial to get a false negative. Many tests have only a single assertion, which is `rawValue === false`. As `rawValue` can end up as `false` for many reasons, it's not a reliable signal. For example the manifest-exists audit returned the following result:
If only looking for `rawValue === false`, then we would miss the failure is due to a JSON exception inside the …
=> Improve the robustness of the manifest unittests

lighthouse-core/gather/drivers/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/gather/gatherers/gatherer.js, lighthouse-core/test/gather/gather-runner.js
Due to the way gather-runner runs our gatherers, `gatherer.setup()` and `gatherer.tearDown()` are redundant with `gatherer.beforePass()` and `gatherer.afterPass()`, respectively. They also happen to be unused by any gatherer at this point, so removing them is super simple.
=> remove redundant gatherer lifecycle methods

lighthouse-core/gather/drivers/driver.js
this code was left over from before [`gatherRunner.loadPage`](https://github.com/GoogleChrome/lighthouse/blob/7ba883024458276a32dadcdf03db7c718f42cec4/lighthouse-core/gather/gather-runner.js#L27) always navigated to about:blank before navigating to the URL, so the logic around whether to reload or navigate now always navigates
=> delete page reload/navigate logic since we always navigate

lighthouse-core/gather/gather-runner.js, lighthouse-core/runner.js, lighthouse-core/test/gather/gather-runner.js, lighthouse-core/test/runner.js
some of this is bikeshedding to (hopefully) simplify gather-runner, but key is better defined lifecycle of gather passes. Building on #572 where redundant steps were removed, we now:
- setupDriver (begin emulation, clear caches and SWs)
- for each pass:
- create clean `options` object (in case gatherers make changes)
- call `beforePass` on gatherers
- navigate to `about:blank`
- begin tracing/network recording (if requested)
- navigate to URL, wait for load
- call `pass` on gatherers
- end tracing/network recording (if started)
- call `afterPass` on gatherers
much of this is the same, but the biggest change is that before tracing started before both `beforePass` (so all `beforePass` activity was being recorded in the trace) and before the navigation to `about:blank`, so both navigations …
=> refactor of gather-runner to clarify lifecycle

lighthouse-core/aggregator/aggregate.js, lighthouse-core/audits/time-to-interactive.js, lighthouse-core/config/default.json, lighthouse-core/test/aggregator/aggregate.js
The default config set value rather than rawValue for TTI, and while there was a check for type errors of this nature, it came after another early exit, meaning that TTI wasn't included in the report total.
This fixes the issue, and it also makes Lighthouse throw in these situations as they occur at author time when someone updates the default config etc.
=> Fixes issue with scoring

lighthouse-core/audits/manifest-display.js, lighthouse-core/closure/typedefs/Manifest.js, lighthouse-core/lib/manifest-parser.js, lighthouse-core/test/audits/display.js, lighthouse-core/test/lib/manifest-parser.js
Came up in the course of #495. To better match spec for [parsing `display`](https://w3c.github.io/manifest/#display-member):
- always fall back to `browser` for display mode (can never be `undefined`)
- always report lowercase value
=> correctly fall back on erroneous manifest display modes

lighthouse-core/config/perf.example-custom.json
This serves two purposes:
1. It's a simple but useful example of how to put together a custom config file.
2. It serves as a handy config for folks wanting to use Lighthouse for perf-only.
Usage: 
```sh
lighthouse http://theverge.com --output=json --config-path=$HOME/code/lighthouse/lighthouse-core/config/perf.json
```
=> Add custom config example: just the perf

lighthouse-core/gather/drivers/driver.js, lighthouse-core/gather/drivers/extension.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/gather/gatherers/http-redirect.js, lighthouse-core/gather/gatherers/url.js, lighthouse-core/index.js, lighthouse-core/lib/network-recorder.js, lighthouse-core/runner.js, lighthouse-core/test/gather/gatherers/url.js, lighthouse-core/test/lib/drivers/driver.js, lighthouse-core/test/runner.js, lighthouse-extension/gulpfile.js
Often from a non-extension the input URL may then be redirected. For example, there are 3 redirects if you attempt `http://aliexpress.com`: 
There's a few places where we work with the current URL, including @jeffposnick's new #578 and the [unregsw](https://github.com/GoogleChrome/lighthouse/tree/unregsw) branch. And in these cases, we want the post-redirect URL.
This PR will update `options.url` as redirects change the document location.
Additionally, we used to have a `driver.url`, but only for the chrome extension. We now drop that completely, which simplifies our URL gatherer.
=> Keep track of the document URL post-redirects

lighthouse-extension/app/manifest.json, lighthouse-extension/app/src/lighthouse-background.js, lighthouse-extension/app/src/popup.js
Saves audit list in extension
perhaps tests should be added to the extension as well?
=> Save audit list into storage so it's kept for the next run

lighthouse-cli/index.js, lighthouse-core/config/config.js, lighthouse-core/config/perf.example-custom.json, lighthouse-core/test/config/config-test.js, lighthouse-core/test/runner-test.js, readme.md
The current filterPass behavior implies that the user can leave all default core gatherers in the config and we'll remove the ones that aren't needed.
This is a bit odd as audits and aggregation sections must be correct, so we shouldn't make gatherers in particular be so forgiving.
Furthermore, the custom perf config no longer requires any core gatherers. It only needs trace & network records, which, without this PR, will end up filtering out the only pass in the config. 
Now instead of changing the config, config.js will issue warnings when gatherers are specified in the config that appear to be unnecessary. The resolution is adjusting the config.
=> filterPasses -> validatePasses

lighthouse-core/gather/gatherers/manifest.js, lighthouse-core/test/gather/gatherers/manifest-test.js
After #600, when the devtools protocol is used to fetch a manifest from a page with no manifest, the response wasn't flagged as an error by the protocol, it just has an empty url and manifest body. This PR adds a `debugString` of 'No manifest found' in that case instead of trying to `JSON.parse` the empty string and getting an error at the later manifest parser stage.
I also noticed the error messages for manifest fetching aren't very helpful (e.g. a 404 gives `"Line: 1, column: 1, Unexpected token."`), so I add the URL that devtools tried to retrieve to the `debugString` to make it easier to spot when you've messed up your manifest path.
=> properly throw debug error when page does not include manifest

lighthouse-core/config/config.js, lighthouse-core/gather/gather-runner.js, lighthouse-extension/gulpfile.js
fixes extension (currently breaking on audit `require` on master) by matching paths to what browserify expects and making sure computed artifacts are unconditionally included in bundle.
With options fix in #614, extension should be good to go again
=> fix audit, gatherer, and computed artifact browserify import

lighthouse-core/audits/audit.js, lighthouse-core/audits/critical-request-chains.js, lighthouse-core/audits/estimated-input-latency.js, lighthouse-core/audits/first-meaningful-paint.js, lighthouse-core/audits/screenshots.js, lighthouse-core/audits/speed-index-metric.js, lighthouse-core/audits/time-to-interactive.js, lighthouse-core/audits/user-timings.js, lighthouse-core/closure/typedefs/Artifacts.js, lighthouse-core/config/config.js, lighthouse-core/gather/drivers/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/gather/gatherers/gatherer.js, lighthouse-core/lib/asset-saver.js, lighthouse-core/lib/log.js, lighthouse-core/test/audits/critical-request-chains-test.js, lighthouse-core/test/audits/estimated-input-latency-test.js, lighthouse-core/test/audits/first-meaningful-paint-test.js, lighthouse-core/test/audits/time-to-interactive-test.js, lighthouse-core/test/audits/user-timing-test.js, lighthouse-core/test/config/config-test.js, lighthouse-core/test/gather/gather-runner-test.js, lighthouse-core/test/lib/asset-saver-test.js, lighthouse-core/test/runner-test.js
- always records network information (fixing #604)
- allows recording the network activity for multiple passes, paving the way for audits like #578
- warns you if your current config has conflicting names for its trace data
- renames `traceName` in config files to the more accurate `passName`
This does use the same naming method as the earlier trace bucket PR. We still need to find a different solution, but at least tracing and network will be unified again, making them easier to change together.
=> support collecting network records per pass

lighthouse-extension/app/src/lighthouse-background.js, lighthouse-extension/app/src/popup.js
cleanup of extension code, which has grown a little hairy as it has accumulated. Mostly:
- always start with a freshly parsed config.json when running lighthouse
- finish removal of audit whitelist in #608 by filtering audits in config directly before passing into LH, but make selected audit categories work again.
- `s/audits/aggregations` after #595, to reflect that it's aggregation categories being saved and loaded for the options list, not audits themselves
- added some docs so it's hopefully a little faster to find your way around in there
This PR fixes 2 bugs:
1. the audit whitelist was still being passed into the `Config` constructor. Amazingly, the browserify polyfill for `path.dirname` parses `new Set(['array', 'of', 'audit', 'names'])` as `'.'`, so this wasn't actually causing …
=> options and terminology fixes and docs added to extension code

lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/gather-runner-test.js
On master, the beginning of a pass goes:
- `beforePass()` on all gatherers
- navigate to `about:blank`, then target url
- `pass()` on all gatherers
- etc
After this PR, each pass will begin:
- navigate to `about:blank`
- `beforePass()` on all gatherers
- navigate to target url
- `pass()` on all gatherers
- etc
=> about:blank navigation moved to before gatherer.beforeClass()

lighthouse-cli/index.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/runner.js, lighthouse-core/test/gather/gather-runner-test.js, lighthouse-extension/app/src/popup.js, readme.md
the `--load-page`/`loadPage` options flag has been non-functional since at least when the config file was added. This removes the last traces of it.
Note that this is *not* the `loadPage` included in passes in the config file (that's #589)
=> eliminate non-functional loadPage cli flag

lighthouse-cli/test/fixtures/smoketest-offline-config.json, lighthouse-core/audits/service-worker.js, lighthouse-core/closure/typedefs/Audit.js, lighthouse-core/closure/typedefs/ServiceWorkerArtifact.js, lighthouse-core/gather/gatherers/service-worker.js, lighthouse-core/test/audits/service-worker-test.js, lighthouse-core/test/gather/gatherers/service-worker-test.js
moves the search for the active service worker from a gatherer to an audit so it can use the final, possibly redirected URL of the test page (as introduced in #582). When #619 lands and the SW is registered reliably before the gatherer runs, this will allow e.g. `https://www.airhorner.com` to pass the SW check.
The service worker for airhorner is at `https://airhorner.com/sw.js`, so it currently fails the same origin check with `https://www.airhorner.com`. This PR will properly take into account the redirect to `https://airhorner.com` and so the same origin check will pass.
=> move SW version test to audit to use possibly redirected URL

API-and-internals.md
I got lighthouse running on Ubuntu 16.04 server and had to make the following changes. I don't know if the current instructions are for previous versions or if they contained errors. For example, I was unable to find a reference to a package ``` chromium``` ever existing.
Changes:
- Chromium package and executable are named ```chromium-browser``` in Ubuntu 16.04. 
- setting $DISPLAY seems not to be required
- chromium has a --temp-profile flag that seems to do the same previously done manually
=> Fixed headless documentation

lighthouse-cli/scripts/run-smoke-tests.sh
because running into ports already in use is a pain:
With this, we nuke the background node server when we exit.
=> smoke test: clean up backgrounded processes.

lighthouse-extension/package.json
something changed after #613 with linting the extension that didn't manifest until today, when I deleted the travis cache for testing #632. `eslint-config-google` is unable to find the `eslint-config-xo` module that it extends, but only on the node v4 (+ `--harmony`) test machine, and only when linting the extension (not `core/` or `cli/`). This is weird because `eslint-config-google` and `eslint-config-xo` sit right next to each other in `node_modules/`, and the first is always found.
I haven't been able to figure out what's causing the issue, but this small workaround fixes it, at the expense of having a copy of `eslint-config-xo` in both the root and extension `node_modules/` directories. Happy to consider an alternative, but we can also just keep this until we hit the happy land of …
=> add explicit eslint-config-xo dep for old node

readme.md
During training we found users who could had not upgraded to latest version of Chrome. 
I've updated the readme to indicate that Lighthouse needs version 52 or later. This will help reduce issues of non-supported versions.
=> Adding notice about minimal version

lighthouse-cli/index.js
This PR adds support for batch-running multiple URLs through Lighthouse (in sequence) with minimal change to the CLI surface. 
**Usage:**
```sh
$ ./lighthouse-cli/index.js <url1> <url2> <url3>
```
**Demo:**
The approach implemented will also continue to work with parameters like `--save-assets`, outputting trace files for all runs to disk:
```sh
$ ./lighthouse-cli/index.js <url1> <url2> <url3> --save-assets
```
Happy to rewrite or add tests if needed. This seems like a useful feature to support in the CLI directly vs. building as a separate module.
If this feature is interesting, I'd be happy to follow-up with a future PR that adds the ability to accept a JSON file (or something) with a list of URLs for folks that want to run LH against a predefined collection of sites.
=> Add support for sequentially batch-running URLs

lighthouse-core/lib/asset-saver.js
Small cosmetic change here
Before and after:
```sh
paulirish.com_2016-09-14T00:46:44.232Z.html # before
paulirish.com_2016-09-14_17:46:44.html      # after
```
Uses local time zone to make it look a bit more human readable.
(Personally I don't love `.replace()`ing the toISOString, but there's actually no clean way to otherwise get yyyy-mm-dd even with the new formatting APIs)
cc @addyosmani
=> Better filenames to save to disk.

lighthouse-core/gather/computed/pushed-requests.js, lighthouse-core/test/fixtures/networkRecords-h2push.json, lighthouse-core/test/gather/computed/pushed-requests-test.js
fixes #652 
Usage in an audit looks something like..
```js
const networkRecords = artifacts.networkRecords[Audit.DEFAULT_PASS];
return artifacts.requestPushedRequests(networkRecords).then(records => {
const record = records[0];
// ...
record._url
record._startTime
record._endTime
record._duration
record._timing.pushStart
record._timing.pushEnd
record._resourceSize
```
The record object looks like this: 
Also FWIW, devtools has some [fancy handling of endTime](https://github.com/ChromeDevTools/devtools-frontend/blob/42cfb581ea5b9f2c35db3f2a606148be79d11d4f/front_end/network/RequestTimingView.js#L188-L194) that we could also do if neccessary.
R=@samccone
=> add h2 pushed requests artifact

lighthouse-core/closure/typedefs/Manifest.js, lighthouse-core/lib/icons.js, lighthouse-core/lib/manifest-parser.js, lighthouse-core/test/lib/manifest-parser-test.js
Noticed a small spec violation in our current impl.
When parsing the manifest `icons` member, [a list of icons is *always* generated](https://w3c.github.io/manifest/#dfn-steps-for-processing-an-array-of-images), it's just empty if the `icons` entry is missing or erroneous.
=> make manifest parser return empty array when icons missing or erroneous

lighthouse-core/gather/drivers/driver.js
fixes #647
cuts off load time at 25 seconds. Fixes aliexpress, which currently never reaches load and so just hangs Lighthouse indefinitely. One step to fixing #627
=> add a timeout to gotoURL to handle sites that never reach `load`

lighthouse-core/config/config.js, lighthouse-core/config/default.json
No audits require our HTML gatherer any longer 
So we're logging this warning all the time:
This PR removes it from the default config.
=> Remove html gatherer from default.

lighthouse-core/gather/computed/screenshots.js, lighthouse-core/gather/computed/speedline.js, lighthouse-core/lib/console-quieter.js, lighthouse-core/lib/traces/devtools-timeline-model.js, lighthouse-core/test/gather/computed/screenshots-test.js
When our dependencies are spitting into console.log it gets pretty ugly. In particular the "tracingstartedinpage not found" and "MSG_LOOP_STARTED already began" logs that we see.
This PR will mute the console while we're doing work inside of devtoolstimelinemodel (ours or speedlines).
If you've set `--verbose` then you'll get the messages.
Also, a driveby fix to handle `.traceEvents` as expected in our timelinemodel.
fixes #617
=> Send console.errors from devtools-frontend to --verbose

lighthouse-core/formatters/user-timings.js, lighthouse-core/test/formatter/user-timings-test.js
Before:
After: 
URL to test: `lighthouse --perf "http://output.jsbin.com/goyoridice/1/quiet"`
=> user timing CLI formatter: more concise output.

lighthouse-core/gather/computed/computed-artifact.js, lighthouse-core/gather/computed/critical-request-chains.js, lighthouse-core/gather/computed/pushed-requests.js, lighthouse-core/gather/computed/screenshots.js, lighthouse-core/gather/computed/speedline.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/computed/computed-artifact-test.js
@paulirish 
noticed a small bug in the computed artifact caching in `PushedRequests` and thought I'd just make caching taken care of automatically while I was in there.
When implementing a computed artifact in the future you just override `compute_()` and return either a Promise or the computed artifact directly and the `ComputedArtifact` base class will handle caching the response (and subsequently responding from the cache).
=> handle computed artifact caching automatically

lighthouse-core/index.js
somehow missed this when removing the `auditWhitelist`. Causing the `configPath` to be `undefined` when trying to resolve external audits (and so not finding them)
=> remove old auditWhitelist argument

lighthouse-core/audits/dobetterweb/appcache-manifest.js, lighthouse-core/config/dobetterweb.json, lighthouse-core/gather/gatherers/dobetterweb/appcache.js
R: @brendankenny @paulirish @paullewis @GoogleChrome/accessibility-admin 
Adds an initial setup for DBW®️ and a first test...which is suggesting Service Worker/Cache API over manifest.
Run: `node lighthouse-cli --config-path=lighthouse-core/config/dobetterweb.json --output=html --output-path=results.html http://webdbg.com/test/appcache/`
=> Do Better Web: initial commit

lighthouse-core/gather/drivers/extension.js
Our current `chrome.windows.WINDOW_ID_CURRENT` is pretty flaky with devtools open. 
Also, `currentWindow: true` isn't ideal:
> The current window is the window that contains the code that is currently executing. It's important to realize that this can be different from the topmost or focused window.
The `lastFocusedWindow` property is what we want, plus `windowType` lets us make sure we're not selecting a chrome app/extension. https://developer.chrome.com/extensions/tabs#method-query
R=@wardpeet
=> Improved currentTab impl

package.json
```sh
chrome-debug
chrome-debug --show-paint-rects
chrome-debug --show-paint-rects http://goat.com
```
fixes #655
=> Add `chrome-debug` binary to launch the debuggable standalone chrome

lighthouse-cli/index.js, lighthouse-core/config/config.js, lighthouse-core/test/config/config-test.js, lighthouse-core/test/fixtures/invalid-audits/require-error.js
This came from @ebidel making his own custom audits. Any errors in a custom audit (e.g. syntax error or transitive dependencies not being found) were being absorbed and reemitted as "Unable to locate audit", which is not true and confusing.
In fixing this, however, it also became clear that our audit resolution was being done in a really fragile way, so this PR changes a few things:
- Only assume we can use a core audit path to load an audit if the audit is in fact a core audit. Using this path as the default value makes for confusing error messages if the audit is never found.
- Next, attempt to `require()` in place. No one is going to specify their paths relative to `lighthouse-core/config/config.js`, but this handles the audit-in-an-npm module case by walking up and down the path …
=> clean up of extensible audit loading and error handling

lighthouse-core/config/config.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/runner.js, lighthouse-core/test/fixtures/invalid-gatherers/require-error.js, lighthouse-core/test/gather/gather-runner-test.js
cleans up custom gatherer loading as #679 cleaned up custom audit loading. Made a single method `resolvePlugin()` on `Runner` to handle this, which should also work if we have custom anything else in the future.
The only awkward part of combining the two is passing in a `category` string (right now either 'audit' or 'gatherer') which doesn't affect it functionally but it does give a nicer error message, but I think it's worth it to give the error message context of what kind of thing it was trying to load.
=> clean up and unification of custom audit/gatherer loading

.eslintrc, lighthouse-cli/test/fixtures/offline-ready-sw.js, lighthouse-core/test/aggregator/aggregate-test.js, lighthouse-core/test/audits/aria-allowed-attr-test.js, lighthouse-core/test/audits/aria-valid-attr-test.js, lighthouse-core/test/audits/background-color-test.js, lighthouse-core/test/audits/cache-start-url-test.js, lighthouse-core/test/audits/color-contrast-test.js, lighthouse-core/test/audits/content-width-test.js, lighthouse-core/test/audits/display-test.js, lighthouse-core/test/audits/exists-test.js, lighthouse-core/test/audits/geolocation-on-start-test.js, lighthouse-core/test/audits/icons-test.js, lighthouse-core/test/audits/image-alt-test.js, lighthouse-core/test/audits/label-test.js, lighthouse-core/test/audits/name-test.js, lighthouse-core/test/audits/redirects-http-test.js, lighthouse-core/test/audits/short-name-length-test.js, lighthouse-core/test/audits/short-name-test.js, lighthouse-core/test/audits/start-url-test.js, lighthouse-core/test/audits/tabindex-test.js, lighthouse-core/test/audits/theme-color-test.js, lighthouse-core/test/audits/theme-colors-test.js, lighthouse-core/test/audits/viewport-test.js, lighthouse-core/test/audits/without-javascript-test.js, lighthouse-core/test/audits/works-offline-test.js, lighthouse-core/test/formatter/formatters-test.js, lighthouse-core/test/report/report-test.js, lighthouse-core/test/runner-test.js, lighthouse-extension/app/src/report-loader.js
for some reason a bunch of the tests, and only the tests, were missing `'use strict';`. Added here and tweaked the .eslintrc to enforce it.
=> add 'use strict'; to files missing it and enforce usage

lighthouse-core/audits/dobetterweb/no-websql.js, lighthouse-core/config/dobetterweb.json, lighthouse-core/gather/gatherers/dobetterweb/websql.js, lighthouse-core/test/audits/dobetterweb/websql-test.js
R: @brendankenny @paulirish @GoogleChrome/lighthouse 
I'm not stoked on the 10s timeout for WebSQL db creation, but we need a better framework solution for https://github.com/GoogleChrome/lighthouse/issues/627.
=> DBW: add audit for no-websql

lighthouse-core/gather/drivers/cri.js, lighthouse-core/gather/drivers/driver.js, lighthouse-core/gather/gatherers/dobetterweb/websql.js
I was looking at the promise+event and promise+timeout async patterns we use in a few places with `driver.sendCommand()` and noticed that we were dropping possible promise rejections in several places (and even leaving promise chains behind completely a couple of times).
In practice, the debugger interface serializes our commands for us, so the dropped promise chains likely aren't a problem, and I have yet to see a failure on any domain enabling (though I suppose it might be hard to recognize on master when it does happen without an unhandled rejection warning), but better to have these locked down, especially since they serve as the copy/paste examples for how to use the protocol in audits, like in [#691](https://github.com/GoogleChrome/lighthouse/pull/691/files#diff-436df3e05730abbf26b50 …
=> always handle async sendCommand rejections

lighthouse-core/audits/dobetterweb/no-datenow.js, lighthouse-core/config/dobetterweb.json, lighthouse-core/formatters/partials/url-list.html, lighthouse-core/gather/gatherers/dobetterweb/datenow.js, lighthouse-core/test/audits/dobetterweb/no-datenow-test.js
R: @paulirish @brendankenny @GoogleChrome/lighthouse
=> DBW: add audit for Date.now() usage

lighthouse-core/lib/asset-saver.js, lighthouse-core/runner.js, lighthouse-core/test/lib/asset-saver-test.js
@paulirish @addyosmani 
fixes screenshots not being saved. `saveAssets` now returns a promise which makes things a bit roundabout, but there you go.
=> make asset saving use screenshot computed artifact

lighthouse-core/audits/dobetterweb/no-console-time.js, lighthouse-core/audits/dobetterweb/no-datenow.js, lighthouse-core/config/dobetterweb.json, lighthouse-core/gather/drivers/driver.js, lighthouse-core/gather/gatherers/dobetterweb/console-time-usage.js, lighthouse-core/gather/gatherers/dobetterweb/datenow.js, lighthouse-core/test/audits/dobetterweb/no-console-time-test.js, lighthouse-core/test/gather/gatherers/html-without-javascript-test.js
R: @brendankenny @paulirish @GoogleChrome/lighthouse 
- Makes article naming consistent across similar audits
- Also refactors some common code for recording function calls into driver.
Usage is much simpler now to record API calls:
```javascript
class DateNowUse extends Gatherer {
beforePass(options) {
this.collectUsage = options.driver.captureJSCalls(
'Date.now', 'window.__dateNowStackTraces');
}
afterPass() {
return this.collectUsage().then(dateNowUses => {
this.artifact.usage = dateNowUses;
}, _ => {
this.artifact = -1;
return;
});
}
}
```
=> DBW: add console.time -> performance.mark() suggestion

lighthouse-core/audits/dobetterweb/no-document-write.js, lighthouse-core/config/dobetterweb.json, lighthouse-core/gather/gatherers/dobetterweb/document-write.js, lighthouse-core/test/audits/dobetterweb/no-document-write-test.js
This PR introduces and audit that reports if `document.write()` is used anywhere on the page during the capture.
It reports the script position where document.write() was invoked.
The results when running `npm run dbw http://output.jsbin.com/cajuhoricu/1/quiet`. Peep those line numbers:
In situ:
=> DBW: Add test for usage of document.write()

lighthouse-core/gather/drivers/driver.js
when we started using `Storage.clearDataForOrigin` we inadvertently started clearing cookies as well. This means if you were testing in a Chrome where you're already logged into a site it would log you out -- annoying for afterwards, but also means you can't test pages that require you to be logged in.
This makes us now clear everything but cookies.
=> don't clear cookies for site at start of lighthouse run

package.json
[speedline 1.0.0](https://github.com/pmdartus/speedline)  doesn't depend on `chrome-devtools-frontend` any longer, which really simplifies things, since we depend on it, and so does our `devtools-timeline-model`. 
Landing this will also resolve the issues in #724
=> bump speedline to 1.0.0

lighthouse-cli/test/fixtures/smoketest-offline-config.json, lighthouse-core/aggregator/aggregate.js, lighthouse-core/closure/typedefs/Aggregation.js, lighthouse-core/closure/typedefs/Config.js, lighthouse-core/config/config.js, lighthouse-core/config/default.json, lighthouse-core/config/dobetterweb.json, lighthouse-core/config/perf.json, lighthouse-core/gather/gather-runner.js, lighthouse-core/test/aggregator/aggregate-test.js, lighthouse-core/test/config/config-test.js, lighthouse-core/test/gather/gather-runner-test.js, lighthouse-core/test/runner-test.js, lighthouse-extension/app/src/lighthouse-background.js, readme.md
Since we possibly have more dependents incoming, seems like the time to do the rename in #688. I started with some of the easier ones, separated into commits for easy review and possible cherry picking if there are objections to any particular one :)
Note that any existing config files (pwmetrics? smokehouse) will have to change
- `network` -> `recordNetwork`
- `trace` -> `recordTrace`
- `loadPage` -> 💥
- `criteria` -> `audits`
- `rawValue` -> `expectedValue`
Unit tests look good, as do runs of smokehouse, `--perf` and `npm run dbw`
#688 still open for comments on remaining possible renames
=> initial rename of config properties

jsconfig.json, lighthouse-cli/index.ts, lighthouse-cli/printer.ts, lighthouse-cli/test/cli/printer-test.js
R=@samccone
Just a small PR for me to get a better feel of the CLI in TS.
It was definitely quite nice that once the compilation succeeded everything worked. Plus, the inline errors  meant I didn't need to cmd-s that often.
@samccone question for you in this one. We have both the type alias for the strings, and then also an enum. Can we get rid of one of them?
And please feel free to go to town on this PR (or push to the branch).
=> WIP (TS): Partially refactor outputmode into real enum

lighthouse-core/test/audits/user-timing-test.js
minor, non-functional change. 
Generally we try to avoid `assert.ok` assertions, so this just makes the `audits/user-timing-test.js` a bit more rigorous.
=> tests: stronger usertiming audit assertions.

.travis.yml
This is generally the [recommended](https://www.andreagrandi.it/2014/03/02/travis-ci-org-and-coveralls-io-qa-made-easy/) [config](https://github.com/benbria/coffee-coverage/blob/master/docs/HOWTO-travisci-and-coveralls.md), anyway.
Two advantages:
1. Coveralls bugging out with `Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}` [doesnt break our build](https://travis-ci.org/GoogleChrome/lighthouse/jobs/164491870#L926).
1. We don't really want coveralls data unless the build is successful.
=> Run coveralls only after build success

lighthouse-extension/app/pages/styles/report.css, lighthouse-extension/app/src/lighthouse-background.js, lighthouse-extension/app/src/popup.js, lighthouse-extension/app/src/report-loader.js
While handlebars is generating HTML, it sometimes throws an exception. Currently that results in the spinner just spinning, though there is an error in the report.html page's console.
This PR will print the error to the screen, along with the existing results.
The results are also rendered, which is probably valuable to the user as well as to the developer for debugging the root cause.
=> Extension: Print errors thrown from handlebars

lighthouse-core/gather/gatherers/html-without-javascript.js, lighthouse-core/test/gather/gatherers/accessibility-test.js, lighthouse-core/test/gather/gatherers/cache-contents-test.js, lighthouse-core/test/gather/gatherers/content-width-test.js, lighthouse-core/test/gather/gatherers/geolocation-on-start-test.js, lighthouse-core/test/gather/gatherers/html-test.js, lighthouse-core/test/gather/gatherers/html-without-javascript-test.js, lighthouse-core/test/gather/gatherers/https-test.js, lighthouse-core/test/gather/gatherers/manifest-test.js, lighthouse-core/test/gather/gatherers/theme-color-test.js, lighthouse-core/test/gather/gatherers/viewport-test.js
Found a set of tests that weren't testing anything since anything caught by the `assert(false)` path was immediately handled by a `catch`. In most cases I just got rid of the `catch` since most of the gatherers here don't intentionally throw and so any that do *should* be caught by mocha.
No bugs caught here, just making them do what they say on the tin :)
=> fix tests which were unconditionally passing failed assertions

lighthouse-core/report/report-generator.js, lighthouse-core/scripts/build-traceviewer-module.js, lighthouse-core/third_party/traceviewer-js/ui/base/overlay.js
Two fixes in here that bring our chrome extension back into working order :)
1. With the new traceviewer build, their `base/overlay.html` has a `document.currentScript.ownerDocument` line, that throws in a background page. We're not interested in that, so we `return;` instead. (Unfortunately we've never used the `tr.isHeadless` boolean they have, because their headless involves a custom HTML parser. :)
2. Bugs about `toFixed()` have come up a few times when rendering our report. While we still want to resolve the core bugs, tanking the report seems suboptimal. So we add a safety check first.
wdyt yall?
=> Chrome extension runtime fixes

lighthouse-core/config/config.js, lighthouse-core/runner.js, lighthouse-core/test/runner-test.js
Last two unhandled rejections in our unit tests :) We were checking `doesNotThrow` on `Runner.run` when it *should* always be returning a promise (it wasn't quite, but it does now).
Also added an `Array.isArray(config.auditResults)` assertion on `Config` construction because if it's not an array (as it wasn't for one of the tests), the error manifests quite deep into the pipeline and it isn't clear what's causing it.
=> fix unhandled promise rejections in runner testing

lighthouse-core/audits/speed-index-metric.js, lighthouse-core/test/audits/speed-index-metric-test.js
Speedline was handling 3 frame traces incorrectly.
Since we fixed it and bumped to 1.0.2 (in #728) we don't need this any longer.
=> speed index: allow speedline results even if <3 frames

lighthouse-core/report/report-generator.js, lighthouse-core/report/scripts/lighthouse-report.js, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report.html
R: @paullewis @paulirish @brendankenny 
- Hides `helpText` by default when the audit rating is "good". Shows it otherwise.
- Adds a ? button to toggle help text
- Note: the HTTPs audit here does not have `helpText`, which is why nothing is showing for that failed audit :)
=> Help text toggle

readme.md
Now that our releases are more frequent and npm's version is solid enough, let's recommend installing from there, like normal people.
aye?
=> docs: favor installing stable package from npm instead of Github master

lighthouse-cli/test/fixtures/sample.json, lighthouse-core/config/default.json, lighthouse-core/test/results/sample.json
Unfunctioning is not a real word :) Came across this today while writing up an article on the LH PE tests. "still functional" flowed better than "not non-functioning".
=> Report: Replace 'not unfunctioning' with 'still functional'

lighthouse-cli/printer.js, lighthouse-cli/test/cli/printer-test.js, lighthouse-cli/test/fixtures/sample.json, lighthouse-core/aggregator/aggregate.js, lighthouse-core/test/aggregator/aggregate-test.js
fixes #761 
Details for reviewers: 
* getTotalWeight was manually turning 0 into 1, to avoid a `0/0` ==> `NaN` in the computing of `overall`. It was awkward. I've allowed them to have a value of `0`. 
* maxScore is set to 1 initially to allow `0/maxScore` to resolve to 0 and not `NaN` .
=> Fix NaN% in CLI report

lighthouse-core/config/default.json
I’ve had a few reports from Googlers of this audit incorrectly flagging when their manifest does have a valid `start_url` that’s definitely being cached in the Cache API.
After talking it over with Brendan, it appears there are known issues with this audit not being quite ready just yet. He’s happy with it being disabled in the config, so here’s that change for now ✂️ 🐐
=> Disable cache contains start_url audit in config

lighthouse-cli/chrome-launcher.js, lighthouse-core/scripts/launch-chrome.sh
Brendan and I were looking at some traces today and background pages were busy instantiating while we were tracing the page load. 
(This would add some CPU contention, but probably not anything too significant)
This PR disables Chrome extensions completely via chrome-launcher.
=> fix: disable extension system in launched Chrome instance

lighthouse-cli/chrome-launcher.js, lighthouse-cli/index.js
this moves the chrome launcher class to using `log` for logging instead of a combo of `console.log` and `process.stdout.write`.
We lose the nice `Waiting for browser.....✓` animation, but it goes so fast I don't think much is lost there. In exchange, `--quiet` works again to silence all Lighthouse output but the results. This fixes piping the output and also makes things like smokehouse reporting a lot easier to read without the launcher repeatedly interrupting.
One possible issue: if you *do* want logging from `Launcher`, you have to first set `log.setLevel('info')` or whatever, otherwise nothing is logged. Lighthouse itself handles this internally, but downstream users of the launcher (like smokehouse) will also have to manually set it if they want log messages. It does seem like the …
=> make Chrome Launcher respect --quiet

lighthouse-cli/chrome-launcher.js
[Just like the bash script](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/scripts/launch-chrome.sh#L13) we want the initial URL for our chrome instance to be "about:blank"
The chrome new tab page (NTP) uses a serviceworker and has a decent amount of network traffic and CPU load that we'd prefer doesn't interfere with our tests.
=> Open about:blank as initial URL.

lighthouse-cli/index.js, lighthouse-cli/test/smokehouse/pwa-config.js, lighthouse-cli/test/smokehouse/pwa-expectations.js, lighthouse-cli/test/smokehouse/smokehouse.js, package.json
Runs on top of the lighthouse CLI, testing the audit results of multiple sites against an expected set of results. Run it with `npm run smokehouse`
Currently takes two arguments, `--config-path`, the path to a config file that declares which audits to run, and `--expectations-path`, the path to a file with the expected results of the audits (file format found below). The arguments default to the `pwa-config` and `pwa-expectations` found here, testing some of the easier audits with boolean results. I've ported `npm run smoke` to use this test runner instead of the current bash script, but I'll put that in a followup PR.
Currently comparison with the expectations is strict equality, so doing things like checking for TTI regressions will have to wait for future updates.
=> add smokehouse, an end-to-end test runner

lighthouse-core/audits/speed-index-metric.js, lighthouse-core/test/audits/speed-index-metric-test.js, package.json, yarn.lock
Our speed index metric has been using the classic speed index.
This PR updates us to use pSI: [Perceptual Speed Index (PSI) for measuring above-fold visual performance of webpages](http://www.parvez-ahammad.org/blog/perceptual-speed-index-psi-for-measuring-above-fold-visual-performance-of-webpages)
It also bumps speedline to 1.0.3 which includes bckenny's very nice perf upgrade: https://github.com/pmdartus/speedline/pull/35
=> Adopt Perceptual Speed Index

lighthouse-core/gather/drivers/driver.js, lighthouse-core/gather/gatherers/accessibility.js, lighthouse-core/gather/gatherers/cache-contents.js, lighthouse-core/gather/gatherers/content-width.js, lighthouse-core/gather/gatherers/geolocation-on-start.js, lighthouse-core/gather/gatherers/html-without-javascript.js
_edit by paulirish_:  fixes #580
=> Migrate evaluateAsync to Runtime.evaluate(awaitPromise)

readme.md
@paulirish I thought this was a nice way to get familiar with the codebase... WDYT?
=> add getting started tip to readme

lighthouse-cli/bin.ts, readme.md
helps address situations like #827, since `--select-chrome` can sound like specifying the path directly.
Choosing a different flag name and/or being able to specify a `LIGHTHOUSE_CHROMIUM_PATH` on any platform can come later if demand warrants them.
=> clarify description of --select-chrome command line flag

lighthouse-core/gather/gatherers/manifest.js, lighthouse-core/test/gather/gatherers/manifest-test.js
fixes #819 
currently any entries in `response.errors` are treated as a failure to fetch the manifest, even though they entires in `response.errors` are parsing errors. There are some caveats here: for instance, the debugger protocol will try to `JSON.parse()` a 404 message from a missing manifest and so will report a syntax error instead of the actual 404 error.
This PR works around this by ignoring the `errors` array and looking directly at the raw `data` and `url` returned.
This isn't perfect, however. Malformed JSON, for instance, will show up as `'Unable to retrieve manifest at ${response.url}`, but there's not really any signal we can use to get around that. The debugger protocol simply won't return anything on `response.data` in that case, and so is indistinguishable from e.g. a …
=> stop interpreting driver manifest errors as failure to fetch manifest

.travis.yml
* 6.0 currently isn't being tested, since `node` alias is now v7.x. This PR includes 6
* The `node` alias is dropped in exchange for `"7"`. While we'll have to manually update this as node stable bumps, I think the improvements for readability are worth it:
=> travis: Test node 6 and 7 explicitly 

lighthouse-cli/test/fixtures/offline-ready-sw.js, lighthouse-core/aggregator/aggregate.js, lighthouse-core/audits/time-to-interactive.js, lighthouse-core/closure/closure-type-checking.js, lighthouse-core/test/formatter/formatters-test.js
The eslint results are pretty big and unwieldy.
I've +1'd the max nested callback depth in two tests and nuked a few TODOs that won't be happening for various reasons.
Still plenty of TODO warnings kept, but they're all quite reasonable, so I'm comfortable allowing them to keep bugging us. :)
=> Reduce eslint warnings.

lighthouse-core/lib/emulation.js
Somehow emulateNetworkConditions doesn't work with floats
Fixes #837
=> Math.floor network values to emulate network #837

lighthouse-core/audits/dobetterweb/uses-http2.js
=> Fixes #841. Only returns the necessary json for extendedInfo

lighthouse-cli/bin.ts
`outputMode` in this case is derived from the CLI options and ends up being a regular string.
Then it's being compared to an enum value, which in Typscript is a number by default.
This PR ensures that we compare string against string and correctly write the HTML output to disk.
Note: there are cleaner ways to deal with enums in TS which I'd be happy to help with, but for now this fixes the issue.
=> Ensure HTML is written to disk when outputMode=pretty.

lighthouse-core/lib/traces/tracing-processor.js, lighthouse-core/test/lib/traces/tracing-processor-test.js
We didn't have test coverage for this method. The assertions test the shape of the curve and that our percentiles are correct.
https://www.desmos.com/calculator/0izses21rf
=> test: add TracingProcessor tests for getLogNormalDistribution and getRiskToResponsiveness

lighthouse-core/gather/connections/extension.js, lighthouse-core/gather/gather-runner.js
this is especially important for the extension, so we aren't still on the site while trying to clear state, turn on mobile emulation (which might trigger the page to do work), etc.
separate commit to fix a typo I missed in #639 that makes the new check throw in the extension :)
=> navigate to about:blank before driver setup

lighthouse-cli/bin.ts, lighthouse-core/gather/connections/connection.js
If the result of parsing the incoming message from `json` => `pojo` contains an error, the
`result` property will not exist. This means error handling later in the program will fail since
you will not be able to access `error.code`, `error.stack` etc.
Before: (current master branch)
After:
=> Handle error messages from remote protocol correctly.

lighthouse-core/gather/connections/connection.js, lighthouse-core/lib/log.js
Verbose logging regressed a bit ago:
Strings were being spread into arrays. :)
This PR swaps out usage of `arguments` for spread args, along with some minor cleanup of the log module.
=> log.js: fix spread strings

lighthouse-core/gather/connections/connection.js, lighthouse-core/gather/driver.js
This fixes a regression we introduced in #830 
DOM agent the only domain which complains if you attempt to disable when it was never enabled.
https://cs.chromium.org/search/?q=if.*!enabled+file:%5Esrc/third_party/WebKit/Source/core/inspector/+case:yes&sq=package:chromium&type=cs
This PR permits us to ignore these errors. And it should unbreak the `master` build.
=> Recover if protocol DOM agent throws error about domain not being enabled

lighthouse-cli/bin.ts, lighthouse-core/gather/connections/cri.js, lighthouse-core/gather/connections/extension.js, lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/driver-test.js, lighthouse-core/test/gather/fake-driver.js, lighthouse-core/test/gather/gather-runner-test.js
Followup to #639. Unfortunately we don't necessarily have a tab ID (particularly in the case of the `raw` connection where Lighthouse doesn't establish the debugger connection), so we can't use the id to check against `controlledClients` of any active service workers.
However, with the change to first navigate to `about:blank` in #850, we know the current tab _can't_ be controlled by a service worker for the target URL, so we can simplify the multiple tab check to just find any service worker for the target URL with any controlled clients at all.
=> remove tab targetId dependency from multiple tab check

lighthouse-core/gather/connections/connection.js, lighthouse-core/gather/connections/cri.js, lighthouse-core/gather/gatherers/styles.js, readme.md
Where possible, avoid using anything other than Error objects when rejecting promises.
This is especially important when a receiver expects properties that only exist on
native Error objects to be present.
=> Address inconsistencies with errors raised within Promise flows.

lighthouse-core/gather/gatherers/styles.js, lighthouse-core/test/audits/dobetterweb/no-old-flexbox-test.js
=> DBW: collecting no stylesheets is not an error

lighthouse-cli/package.json
without it, npm will not automatically bundle non top-level
index.js files in a mono-repo setup such as this
re: https://github.com/GoogleChrome/lighthouse/issues/854
=> add `main` field in package.json (cli)

lighthouse-core/lib/log.js
currently breaks extension because extension then [attempts to destructure](https://github.com/GoogleChrome/lighthouse/blob/09ec5b6bd4d3361e923a867f947ce97b6642a96b/lighthouse-extension/app/src/popup.js#L58) `undefined`
=> restore log's status-event payload

lighthouse-core/lib/log.js
Small followup from #835, from @wardpeet's suggestion..
Errors are red, warnings are yellow. And the other logs will never use those colors
=> log: force red color on errors, yellow on warnings.

lighthouse-cli/chrome-launcher.ts, lighthouse-core/scripts/launch-chrome.sh, lighthouse-core/test/audits/without-javascript-test.js
=> disable Google Translate service during Lighthouse run

lighthouse-core/audits/dobetterweb/no-datenow.js, lighthouse-core/audits/dobetterweb/no-mutation-events.js, lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js, lighthouse-core/test/audits/dobetterweb/no-datenow-test.js, lighthouse-core/test/audits/dobetterweb/no-mutation-events-test.js, lighthouse-core/test/audits/dobetterweb/uses-passive-event-listeners-test.js, lighthouse-core/test/fixtures/page-level-event-listeners.json
When I ran `lighthouse-cli` from `https://www.inflearn.com/`. I found error. Sometimes err.url is undefined. so It must has protect code.
```
node lighthouse-cli --config-path=lighthouse-core/config/dobetterweb.json  https://www.inflearn.com/
```
=> Sometimes err.url is undefined. so It must has protect code.

lighthouse-core/gather/driver.js
=> Catch DOM.disable exception so it doesn't interrupt the extension.

lighthouse-core/scripts/restart-travis-builds.rb
I've been using this locally to restart travis builds a bit more easily.
It could be less hacky but it's okay for an hours effort, and definitely beats us all manually restarting travis jobs. :/
Kind of a fix/workaround for #833
I'll be running this in the short term, but I'd like to have it in the source tree
Script in action:
=> Add script for bumping Travis to restart timeout builds.

lighthouse-core/lib/log.js
The red-error-logging PR #860 broke the extension as requiring `debug/node` overrode debug's choice of log function, setting it to stderr even in the browserify build.
Interestingly the regression is rather flaky. I _think_ the order of modules in lighthouse-background hasn't been the same on every build, and when `debug/browser` and `debug/node` swapped places it went from broken to fixed.  
Anyhow, the fix is sniffing before we require, and we'll apply the same color changes to the browser while we're at it.
=> log errors as red in browser as well.

lighthouse-cli/test/fixtures/dobetterweb/dbw_disabled.css, lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js, lighthouse-core/gather/gatherers/dobetterweb/links-blocking-first-paint.js, lighthouse-core/test/audits/dobetterweb/link-blocking-first-paint-test.js, lighthouse-core/test/gather/gatherers/dobetterweb/links-blocking-first-paint-test.js
R: @paulirish @brendankenny @samccone @GoogleChrome/lighthouse 
Disabled stylesheets do not block first render, so we should leave them out. Also some renames, spacing adjustments, and code legibility changes.
=> Don't include disabled links in link-blocking-first-paint audit

lighthouse-cli/chrome-launcher.ts
"Disables installation of default apps on first run. This is used during automated testing" via http://peter.sh flags page.
Discovered during #897
=> Disable installing default apps on clean chrome install.

lighthouse-core/gather/gatherers/styles.js, lighthouse-core/lib/web-inspector.js
R: @paulirish @brendankenny @samccone 
This is a better fix for the bug found in #902. Stylesheets that can't be parsed now return an error.  Future audits may want to use this information somehow.
=> Handle CSS parse errors in stylesheet gatherer

lighthouse-core/lib/traces/tracing-processor.js
current url links to private doc which now contains only a link to the public doc
=> update EQT/EIL design doc links to latest docs

lighthouse-cli/bin.ts, lighthouse-cli/chrome-launcher.ts, lighthouse-cli/test/smokehouse/smokehouse.js, lighthouse-core/gather/connections/cri.js, lighthouse-core/index.js
fixes #833 
- commit 2fed833: as described in #833, the issue on Travis is that the initial HTTP GET request to Chrome for debugger connection information sometimes never responds. This PR adds a 10 second timeout to that request, at which point it exits the process on a special exit code
- commit 227487a: add the ability to specify a port for the debugger protocol with a `--port` flag (defaulting to the current 9222). If you specify port 0, it will pick a random open port (via the [behavior of `server.listen`](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback))
With these changes in place, smokehouse now always uses a random port for the protocol and retries launching Chrome and running Lighthouse up to three times when LH fails with that specific exit …
=> fix Travis test timeouts

lighthouse-core/formatters/partials/accessibility.html, lighthouse-core/formatters/partials/critical-request-chains.html, lighthouse-core/formatters/partials/speedline.html, lighthouse-core/formatters/partials/url-list.html, lighthouse-core/formatters/partials/user-timings.html, lighthouse-core/report/report-generator.js, lighthouse-core/report/scripts/lighthouse-report.js, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report.html
- Moved pass/fail/score from the right side to the left for better readability
- Added icons for pass/fail/help
- Added chromeless styling (based on data-report-context) for future integrations.
- Various other visual cleanups and consolidations.
**Old report:**
**New report:**
**Chromeless report:**
=> Lighthouse Report Style Refresh

lighthouse-core/formatters/accessibility.js, lighthouse-core/report/report-generator.js
#926 started causing an error in the [html formatters test](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/test/formatter/formatters-test.js#L62) when the accessibility formatter tried to use the `gt` handlebars helper but no such helper existed (in #926 that helper was put in `report-generator.js`, which doesn't run in this test). This PR moves that helper into the accessibility formatter class, which is the only place it's currently used anyways.
There are other formatters that use helpers defined in `report-generator.js`; the key difference is that the accessibility formatter calls on that helper even when run on empty input (as the test does), while the other formatters do not.
Interestingly Travis does *not* report this error in the tests. I suspect it has …
=> move `gt` handlebars helper to accessibility formatter

lighthouse-core/report/report-generator.js, lighthouse-extension/app/src/lighthouse-background.js
In the new report template, there's some switches that change the result, so that we retain our leftnav for the extension report, but in the devtools case, we slim it down.
This PR just plumbs through setting these values.
=> Generate report based on context

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.js, lighthouse-core/audits/dobetterweb/no-mutation-events.js, lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js, lighthouse-core/config/default.json, lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners.js, lighthouse-core/gather/gatherers/dobetterweb/document-event-listeners.js, lighthouse-core/test/audits/dobetterweb/no-mutation-events-test.js, lighthouse-core/test/audits/dobetterweb/uses-passive-event-listeners-test.js, lighthouse-core/test/fixtures/page-level-event-listeners.json
R: all
Fixes #858. This adds support for looking up event listeners on all DOM nodes. Previously the gatherer just returned listeners at the page level.
=> Add support for collecting event listeners across all DOM nodes.

lighthouse-core/report/report-generator.js
alternate to #936 
the issue was arrow functions don't get an `arguments` of their own. The `and` helper always skipped the loop, returned false, and so never displayed the `displayValue`.
=> fix arguments in handlebars `and` helper

lighthouse-core/audits/time-to-interactive.js
The current TTI uses our point of diminishing returns as a label, however this number (1700) currently doesn't align with the external guidance on TTI targets (5s on 3G). This PR updates the TTI target to 5000 as discussed with sir @brendankenny. 
A separate commit also adds the missing `ms` units to the report that are used in other performance metrics but not included in TTI for some reason. Two fixes for the price of one 🐦 🐦
=> Update TTI scoring label to 5000ms (matches guidance)

lighthouse-extension/app/src/popup.js, lighthouse-extension/app/styles/lighthouse.css
=> Extension: add report error button

lighthouse-core/audits/dobetterweb/no-mutation-events.js, lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js, lighthouse-core/closure/closure-type-checking.js, lighthouse-core/lib/event-helpers.js, lighthouse-core/test/fixtures/page-level-event-listeners.json, lighthouse-core/test/lib/event-helpers-test.js
R: @brendankenny @GoogleChrome/lighthouse 
- Fixes #951 
- Adds a slight refactor, removing duplicated code into lib/event-helpers.js. The single use event listener will also use this 👍 
- normals `Window` -> `window` and `#document` -> `document`. These are cleaner and more intuitive names than what the driver returns.
Before:
After:
=> Slight refactor of event listener label/code formatting. Also Fixes #951

lighthouse-core/audits/manifest-display.js, lighthouse-core/test/audits/display-test.js
fixes #933
(taking over for #950 with @ebidel's feedback incorporated)
=> only create a manifest display debugString when there is an error

lighthouse-core/gather/driver.js
we were getting multiple call sites per instrumented function (e.g. `Date.now`) since we were counting every call stack as a unique entry, instead of just every call site location. This removes the stack traces for now to work around this; #957 tracks adding them back later if they end up being needed.
=> remove stack trace from function call site entries

lighthouse-core/audits/dobetterweb/no-mutation-events.js, lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js, lighthouse-core/formatters/partials/url-list.html, lighthouse-core/lib/event-helpers.js, lighthouse-core/test/lib/event-helpers-test.js
The fix for #959 with a documented explanation of it. Tried to comment the code as much as possible :)
=> Report: group event listener extended info by call site location

lighthouse-core/audits/without-javascript.js, lighthouse-core/gather/gatherers/html-without-javascript.js, lighthouse-core/test/audits/without-javascript-test.js, lighthouse-core/test/gather/gatherers/html-without-javascript-test.js
Handles the issue with a two-pronged solution.
1. Ensure if `innerText` returns something other than a string to surface the error in the gatherer
2. Ensure the type of the resulting artifact is a string before calling `.trim`
Addresses #967
=> fix(audit/without-javascript): non-string error handling

lighthouse-extension/app/src/lighthouse-background.js, lighthouse-extension/app/src/popup.js
fixes #921 (but for real this time)
The issue was that we were correctly filtering out audits from running based on what aggregation categories were selected in the extension, but we weren't filtering out the aggregations themselves. When report time comes along, the unselected aggregations were looking for results in audits that had been filtered out, causing the error.
@pavelfeldman: This needs to happen for both the extension and worker (DevTools) versions, though, which means it needs to happen in `lighthouse-background.js`. This means a (hopefully minor) breaking change for DevTools, as it will now need to pass in a set of aggregations to run, not a set of audits.
=> filter unneeded aggregations from config before extension runs

.travis.yml
I noticed that [my PR](https://github.com/GoogleChrome/lighthouse/pull/992) was failing on node v4.xx.x on Travis CI, so I decided to look into it briefly. 
Travis-CI introduced support for Yarn recently. Unfortunately, Yarn doesn't officially support node [versions < v6.xx.x](https://github.com/yarnpkg/yarn/issues/1944#issuecomment-261696213)
**Purposed fix**
Override Travis install method to use `npm install` for node versions < v6.xx.x
=> Override travis install method to use npm for older versions of node

lighthouse-extension/app/src/popup.js
Currently the Lighthouse Extension Errors create a generic title that is too ambiguous to differentiate duplicates without actually clicking on the issue.
This PR appends the JS error to the title.
=> Improve github issue title

lighthouse-core/gather/connections/connection.js, lighthouse-core/gather/connections/extension.js, lighthouse-core/gather/driver.js
starts addressing #976
also gives slightly more context for errors like #966 (as well as a real stack trace)
Moves the extension and the raw connection to use the same error handler for messages coming back from the debugging protocol, as well as normalizing the error object fed into it. This should aid debugging. Happens to unify catching of `DOM.disable` error, instead of in separate spots for extension and CLI.
Also removes old `result.wasThrown` from extension `sendCommand`, which as discussed in #976 was doing nothing but confusing us.
=> create single path for handling errors from the protocol

lighthouse-extension/app/manifest.json
Chrome 54 is the latest stable version and is required for e.g. `evaluateAsync` as of #793
=> set extension's minimum supported Chrome to m54

lighthouse-extension/app/manifest.json
I believe the "tabs" permission is not mandatory as we already have access to the "activeTab" permission. Please consider removing it.
I've run locally Lighthouse extension without the "tabs" permission and it worked fine.
=> Remove "tabs" extension permission

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener.js
=> fix: identify rel noopener in list

lighthouse-core/audits/manifest-icons-min-144.js, lighthouse-core/audits/manifest-icons-min-192.js
This simple patch makes reading icons of sizes easier:
```diff
- Found icons of sizes: 152x152,144x144,192x192,256x256,512x512
+ Found icons of sizes: 152x152, 144x144, 192x192, 256x256, 512x512
```
=> Fix formatting nit in found sizes

lighthouse-core/audits/critical-request-chains.js, lighthouse-core/audits/user-timings.js, lighthouse-core/test/audits/user-timing-test.js, lighthouse-core/test/runner-test.js
R: @brendankenny @paulirish @patrickhulce 
Per #1069, this removes the scoring labels from the performance metrics section. 
Notes:
- The user timing metrics will always be a green checkbox.
- For critical requests, if you have more than 0, you'll always get a red x. We don't have a good story there for what to display.
=> Fixes #1069 - remove scores from perf metrics. Change to pass/fail.

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-core/audits/dobetterweb/no-console-time.js, lighthouse-core/audits/dobetterweb/no-datenow.js, lighthouse-core/gather/driver.js, lighthouse-core/test/audits/dobetterweb/no-console-time-test.js, lighthouse-core/test/audits/dobetterweb/no-datenow-test.js
R: @brendankenny @patrickhulce @paulirish 
According to  https://crbug.com/646849, eval'd script does not include the url context where the script was run. So for our callsite collector, we were throwing an error trying to parse a `.url` property that did not exist. This PR handles eval'd scripts and sets the .url to be the last entry of the stacktrace.
Example run: http://onset.github.io/lighthouse-test/
=> Fixes #1071 - handles eval'd script in callsite collector

lighthouse-cli/chrome-launcher.ts
Windows can't remove the temp directory because the node process still has the 2 log files open. By closing them right before removal we close the files.
Fixes [#1001](https://github.com/GoogleChrome/lighthouse/issues/1001)
=> Close outfile & errfile in chrome launcher before cleaning the directory

lighthouse-core/audits/user-timings.js, lighthouse-core/test/fixtures/traces/trace-user-timings.json
Don't show paintNonDefaultBackgroundColor with user timings
Fixes #934
=> fix: remove `paintNonDefaultBackgroundColor` from user timings

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/audits/dobetterweb/notification-on-start.js, lighthouse-core/config/default.json, lighthouse-core/gather/driver.js, lighthouse-core/gather/gatherers/dobetterweb/geolocation-on-start.js, lighthouse-core/gather/gatherers/dobetterweb/notification-on-start.js
=> DBW: Audit for notification permissions on start

lighthouse-core/test/audits/critical-request-chains-test.js
fixes #1099 
just needed to return the promise in the test. Another leftover failure from #1072 when perf metric scoring was changed to pass/fail, so no bug here except the need for the expectation to be updated
=> return promise in CRC test

lighthouse-core/report/scripts/lighthouse-report.js, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html, lighthouse-core/test/report/report-test.js
In the DevTools panel we can't run inline script in our iframe, so I'm moving this critical functionality to CSS. :)
That means we can simplify lighthouse-report.js considerably, and only do the `print()`.
=> move helpText toggle to pure CSS

lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html
R: @paulirish @patrickhulce @brendankenny 
This changes all the rating classes to have a single `-` prefix.
`--poor` is not a valid CSS class. See https://github.com/pagespeed/ngx_pagespeed/issues/993.
Safari before:
After:
=> Fix styling issues in Safari

lighthouse-cli/index.js, lighthouse-cli/test/cli/printer-test.js
Cheap fix, but I think we don't need anything more substantial.
fixes #1101
=> extra checks for printer.js existing.

lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html, lighthouse-core/test/report/report-test.js, lighthouse-viewer/app/index.html, lighthouse-viewer/app/src/lighthouse-report-viewer.js, lighthouse-viewer/app/styles/viewer.css
R: all
This moves the share button to the main report template, but hides it when the report context is not `data-report-context="viewer"`.
Also updates the page title when the user views a new report. Part of https://github.com/GoogleChrome/lighthouse/issues/1108.
=> Viewer: move share button to core report

lighthouse-viewer/app/src/github.js, lighthouse-viewer/app/src/lighthouse-report-viewer.js, lighthouse-viewer/app/styles/viewer.css
R: all
This disables (fades and `pointer-event: none`) the share to github button if the gist already exists on github. This will help prevent duplicates.
Part of https://github.com/GoogleChrome/lighthouse/issues/1108
=> Disable sharing button if gist is already saved

lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html
R: all
This sticks the report header to the top of the page as you scroll. I think this is a nice change to make the share/print button always visible (e.g. LH viewer, devtools).
=> Report: header sticks to top

lighthouse-viewer/app/src/lighthouse-report-viewer.js
=> Viewer: enable pasting json report on app

lighthouse-viewer/gulpfile.js, lighthouse-viewer/package.json
R: all
This removes clsoure from the viewer build process and moves to using the tsc compiler. I chose TS over babel because it produces slim output, has similar support for polyfills like closure, and we're already using it elsewhere in the project, and allows us to migrate to es6 modules and .ts over time.
Now at 6s build for prod! But again, dev is still <1s.
=> Viewer: Remove Closure

lighthouse-core/report/report-generator.js, lighthouse-core/report/templates/report-template.html, lighthouse-core/test/report/report-test.js
Our devtools integration is that the report is hosted in and iframe (with a blob url).
DevTools has a CSP policy: https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/inspector.html#L10
It prevents inline scripts from running.
That ends up throwing an error for our report. While there _may_ be some ways to handle this at a CSP layer, I'd prefer, in the short term, to make our report function without javascript.
The report only needs JS for the `window.print()` which is hidden from the devtools version (via `reportContext`).
This PR tweaks things so we don't ship a script tag to devtools; and we only ship 1 script tag to the extension.
=> don't emit script tags in devtools report.

lighthouse-cli/chrome-launcher.ts, lighthouse-cli/test/cli/chrome-launcher-test.js
The error happened outside the Promise chain and is uncatchable.
=> Eliminate errors from calling ChromeLauncher.kill() twice 

package.json, yarn.lock
Big win if you've ever seen the "Retrieving: Accessibility..." message for longer than you'd expect.
Fixes #630 
Over in https://github.com/dequelabs/axe-core/issues/240 we reported some perf issues to the axe-core team. They've now addressed them and shipped the latest version of the library. 
There were pages like [Promise | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that took A LOT of time.
* **Before: 9.6 seconds**
* **After: 1.1 seconds** 
Death to forced layouts. 😀 
------------
Also, another win I didn't expect. The awesome team at @dequelabs also changed the runtime so that it [yields to the main thread on nearly every tick](https://github.com/dequelabs/axe-core/blob/c6dc85b7fd6d7c643995ac12fb5276ea743cde74/lib/core/base/check.js# …
=> bump axe-core, as it's now 8x faster

lighthouse-cli/bin.ts, lighthouse-cli/chrome-launcher.ts, lighthouse-cli/random-port.ts, lighthouse-cli/test/cli/random-port-test.js, lighthouse-core/gather/connections/cri.js, lighthouse-core/gather/connections/extension.js, package.json
the complexity of `bin.ts` was getting a little out of hand, so this refactors to linearize the control flow and hopefully make it easier to follow and alter in the future.
This also drops support for a list of urls on the command line and goes back to one url at a time. We could easily turn it back into a `reduce` loop over urls, but it adds some complication and we never actually documented support, so...
Opinions welcome.
no longer included: ~~One big change: most of the logic moves to `lighthouse-launcher.ts` so `bin.ts` really only handles cli flags and then calls `lighthouse-launcher.ts`. Main benefit is so downstream projects can import `run()` from `lighthouse-launcher.ts` and run it (currently if you try to import `bin.ts` if you don't happen to have something in your argv [it'll …
=> bin.ts simplification refactor

lighthouse-cli/printer.ts, lighthouse-cli/test/cli/printer-test.js
R: @brendankenny @paulirish 
`{inline: true}` is leftover from a previous age. This fixes cases where the html is generated by the CLI and we got `<html data-report-context="[object Object]">` in the report.
=> Fix html report context when generated by the CLI

lighthouse-cli/bin.ts, lighthouse-cli/test/cli/bin-test.js
I noticed the CLI still mentioned the `mobile` flag. whoops.
Removed it.
Added a test to catch undocumented CLI options.
=> remove mobile cli option. add test to assert no dead cli options.

lighthouse-core/test/lib/url-shim-test.js
works around #1186 
Eventually we do want to move entirely to native node URL parsing, so we can leave that bug open to track it.
Test is arguably unnecessary (`whatwg-url` is tested using the [web platform tests](https://github.com/w3c/web-platform-tests/blob/master/url/urltestdata.json) and this is one corner case among a great many), but it's not really harmful, and it makes sure the URL shim is loading and running.
=> Remove node URL parsing while bugs are being fixed

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/fake-driver.js, lighthouse-core/test/gather/gather-runner-test.js
V8 has the property prepareStackTrace on errors where you can format a stacktrace. This only works on native errors not on custom ones.
Fixes issues like #1194
=> Fix captureJSCallUsage in the face of Error polyfills.

lighthouse-viewer/app/src/lighthouse-report-viewer.js
=> Viewer: dont check file type, try to parse json file. Fixes #1204

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js, lighthouse-core/test/audits/dobetterweb/external-anchors-use-rel-noopener-test.js
addresses #1233. See that issue for details on why we still include anchors with no `href` in the audit results.
We might want to leave that open as the reporting of links with no href leaves something to be desired (e.g. the first link in the seamless example ends up as `<a target="_blank" >... </a>` in the URLs dropdown in the report).
Not sure how to make it easier to identify the links in question without starting to write formatters for all the major frameworks, though.
=> handle anchor tags with no href in noopener audit

lighthouse-core/audits/dobetterweb/no-datenow.js, lighthouse-core/test/audits/dobetterweb/no-datenow-test.js
R: all
https://github.com/GoogleChrome/lighthouse/pull/1218 didn't fully fix the issue like we hoped. Adding extra protection in the date.now audit so we don't throw errors.
=> Fixes #1263

lighthouse-extension/app/src/popup.js
R: all
We've seen an enormous uptick in bugs lately. Including the URL in the "file an issue" template will help us reduce the back and forth for debugging. Users can remove it before they file the issue.
=> Add url to crx "file a bug"

lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js, lighthouse-core/test/audits/dobetterweb/external-anchors-use-rel-noopener-test.js
R: @ebidel 
Changes rel noopener audit to warn about all potentially violating anchor tags even when URL is malformed.
Addresses #1345
=> fix: report all indeterminable anchors

lighthouse-cli/test/fixtures/accessibility/accessibility_tester.html, lighthouse-core/audits/accessibility/aria-allowed-attr.js, lighthouse-core/gather/gatherers/accessibility.js, lighthouse-core/test/audits/accessibility/aria-allowed-attr-test.js
Switch to the new `axe.run` method which returns a promise. Now we're only running the tests that we actually audit for, instead of running the default entire axe suite. Also cleaned up a duplicate smoke test and improved the description of the aria-allowed-attr audit a bit.
=> Only run axe tests that we have audits for

lighthouse-extension/app/src/lighthouse-background.js, lighthouse-extension/app/src/popup.js
When extension popup is closed & lighthouse is still running we show the state lighthouse is running in instead of showing the startup screen.
=> Store state of lighthouse in extension while running.

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-core/audits/dobetterweb/no-console-time.js, lighthouse-core/audits/dobetterweb/no-datenow.js, lighthouse-core/gather/driver.js, lighthouse-core/test/audits/dobetterweb/no-console-time-test.js, lighthouse-core/test/audits/dobetterweb/no-datenow-test.js
R: @brendankenny
You can test against https://geda.nkenspen.de/ to trigger the `debugString` path. DBW tester won't surface it partly because of https://github.com/GoogleChrome/lighthouse/issues/1286.
=> Fixes #1282

lighthouse-core/audits/manifest-display.js, lighthouse-core/test/audits/display-test.js
Commit 98c49808 said "manifest display must be one of the 3 allowed values.", and this adds the fourth allowed value. For #495.
=> Add "minimal-ui" as an allowed display value.

lighthouse-cli/printer.ts, lighthouse-cli/test/fixtures/sample.json, lighthouse-cli/types/types.ts, lighthouse-core/aggregator/aggregate.js, lighthouse-core/report/report-generator.js, lighthouse-core/test/aggregator/aggregate-test.js, lighthouse-core/test/results/sample.json
Adds a total score field to aggregate objects and presents that
information in every output type.
Closes: #1285
This pull request is moving html output only implementation of `getTotalScore` method from `lighthouse-core/report/report-generator.js`. It was placed in `Aggregate` object to keep JSON output as simple dump of result and to be easily available for all output types.
=> Show total score in every output type

lighthouse-cli/bin.ts, lighthouse-cli/performance-experiment/server.js
Main changes:
1. Saving results as JSON instead of HTML. This can ease results comparison in Project Performance Experiment (Perf-X) #1143.
2. Save flags. Perf-X will need this to rerun the lighthouse (with some extra configurations).
3. Save file and construct report page URL in server.js instead of bin.ts. This hopefully can make bin.ts more readable and reduce coupling.
=> refactor performance experiment server

lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/fake-driver.js
Added request blocking method in Driver and it will be called during GatherRunner.setupDriver().
Blocked URLs will be passed in flags.blockedUrlPatterns. The flag is not exposed to users since copy-pasting a bunch of URLs seems inconvenient in cli. It will mainly been used by Perf-X server #1143.
=> add url blocking function to driver

lighthouse-viewer/app/index.html, lighthouse-viewer/app/src/fileuploader.js, lighthouse-viewer/app/src/lighthouse-report-viewer.js, lighthouse-viewer/app/styles/viewer.css
R: all
Part of #1283. On mobile, you'll get a url input:
On mobile/desktop, you'll be able to paste the URL of a gist. Invalid urls will cause a butter bar warning.
=> Paste/input gist URL for mobile. Fixes #1283

lighthouse-cli/chrome-launcher.ts, lighthouse-cli/printer.ts, lighthouse-core/formatters/critical-request-chains.js, lighthouse-core/lib/log.js
This is #1272 cherry picked, #1305 cherry picked and fixed.
Verified everything works on my Windows VM.
Closes #1272, closes #1305.
Fixes #1228, fixes #1261.
**Note to maintainers**: Do **not** squash the branch when merging in order to keep author information.
Oh, and merry Christmas 🎄 
/CC @Janpot to confirm you are OK with cherry picking your patch and close 1272.
=> Windows log fixes

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js, lighthouse-core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js
Attempts to reduce false positive rate for tags blocking first paint. Whitelists tags that were added via script or whose rel/async/disabled attributes indicated asynchronous behavior at any point in their lifecycle.
Addresses #1317
=> Fix: Limit false positives for async stylesheets

lighthouse-core/report/report-generator.js, lighthouse-extension/app/src/lighthouse-background.js
followup from #1163 
I was getting this guy:
1. Fixes the circular JSON issues when the result was handed around. The circular references are currently only in `artifacts.networkRecords` FWIW. All other artifacts are safe.
1.  I've also moved the stringifier in `reportException` to be our `json-stringify-safe` for good defense.
1. ~~Introduced a ` window.getLatestArtifacts` for future use by devtools, and probably the viewer/perf-server (#1163).~~
R=@brendankenny, @WeiweiAtGit
=> Exclude artifacts from result handed to extension/devtools.

lighthouse-cli/chrome-finder.ts
Experimenting with running lighthouse on https://hub.docker.com/r/justinribeiro/chrome-headless/
Running into a few issues.
=> Ignore when the which command fails

lighthouse-core/audits/first-meaningful-paint.js, lighthouse-core/test/audits/first-meaningful-paint-test.js, lighthouse-core/test/fixtures/traces/preactjs.com_ts_of_undefined.json
This is the core problem of #1253.
As @wardpeet deduced, we are hitting these because sometimes FMP trace events are added before FCP
This now allows there to be 32ms of tolerance between the two, as we found traces where FMP is just 0.7ms before FCP.
Fixes #1253.
=> Allow FMP trace event to appear slightly before the FCP

lighthouse-core/audits/dobetterweb/no-old-flexbox.js, lighthouse-core/lib/styles-helpers.js, lighthouse-core/test/lib/style-helpers-test.js
Fixes https://github.com/GoogleChrome/lighthouse/issues/768 
ISSUE:
Extend no-old-flexbox audit to include more old flexbox checks then just display: box
Extend styles helper by adding a method to add web prefixes to the propsNames
FIX:
Change how style-helper's filterStylesheetsByUsage function works by adding `propName.indexOf(item.property.name) > -1;` which will evaluate true when propName array or string contains item.property.name
Added arrays of the values that are considered old css flexbox properties
`const propsNames = [ 'box-flex' , 'box-orient', 'box-flex-group', 'display' ];
const propsValues = [ 'box', 'flexbox' ];` 
(source: [https://www.w3.org/TR/2009/WD-css3-flexbox-20090723/](url))
=> DBW: improvements to CSS flexbox audit.

lighthouse-core/scripts/run-mocha.sh, lighthouse-viewer/app/src/logger.js, lighthouse-viewer/package.json, lighthouse-viewer/test/fileuploader-test.js, lighthouse-viewer/test/test-helpers.js, lighthouse-viewer/yarn.lock, package.json
R: @brendankenny @patrickhulce 
Adds tests for viewer's `FileUploader` class. Part of #1108.
=> Viewer: Add tests for fileuploader

lighthouse-core/audits/speed-index-metric.js, lighthouse-core/test/audits/speed-index-metric-test.js
Much like the extended timing/timestamps for FMP and TTI that was added in #1152
This adds the same details for speed index, and perceptual speed index.
=> Add extended timing data to Speed Index audit results

lighthouse-core/lib/asset-saver.js, lighthouse-core/report/report-generator.js
Our data structures do not have circular references, with the exception of networkRecords.
json-stringify-safe was added (by me) to the report generator, however it's unnecessary there.
Additionally, the devtools minifier attempted to minify `json-stringify-safe` and had trouble with [the semi-colon-less code style](https://github.com/isaacs/json-stringify-safe/blob/master/stringify.js#L19). (Yes, the devtools' minifier is lame, but oh well).
👷
=> Isolate use of json-stringify-safe.

lighthouse-cli/chrome-launcher.ts, lighthouse-cli/printer.ts, lighthouse-cli/test/smokehouse/smokehouse.js, lighthouse-core/lib/log.js
Gather definitions of colors and special characters in log.js.
Closes: https://github.com/GoogleChrome/lighthouse/issues/1414
=> Refactor console special characters

lighthouse-core/gather/driver.js
We can afford to include the JS stacks now, which allows us to start attributing cost at a function level. Moreover, when you view a LH trace in timeline, having the stacks tells fleshes out the flame chart inside of "Evaluate Script" etc.
I've looked at the trace size overhead of various categories and we can trade netlog for cpu_profiler right now for free.
I profiled the load of theverge.com in three modes:
1. hi-res sampling (cpu_profiler & cpu_profiler.hires)
1. lo-res sampling (cpu_profiler)
1. no sampling (no cpu_profiler at all)
full details: https://docs.google.com/spreadsheets/d/1T_i2ikSWMH13YzqnKPfrRGjTXrs-C-98jj6x8sipfu0/edit#gid=2071721736&vpid=A6
You can see the size overhead of netlog (which we added [randomly](https://github.com/GoogleChrome/lighthouse/pull/650) without a …
=> Trace capture: include JS stacks, exclude netlog

lighthouse-cli/bin.ts, lighthouse-core/lib/asset-saver.js, lighthouse-core/test/lib/asset-saver-test.js, lighthouse-viewer/app/src/github.js, lighthouse-viewer/app/src/lighthouse-report-viewer.js
* Improved `getFilenamePrefix`.
* Using `new URL()` for the hostname.
* Fixes #1361 where inconsistent timezone used for date vs time
* Added tests for this
* Changed parameters of `saveAssets`, `prepareAssets`, and `getFilenamePrefix`
* Generally they all take the ending `results` object rather than the starting `options` object. So the URL is the finalUrl, rather than provided one. This lets use use the generatedTime, as before, we were not.
* Removed `filterForSize`. Unnecessary since the new FMP landed.
=> Asset-saver refactors

lighthouse-core/gather/driver.js
Fixes issue found by @wardpeet  in https://github.com/GoogleChrome/lighthouse/pull/1442#issuecomment-271419264
=> Remove cpu_profiler trace category

lighthouse-cli/chrome-launcher.ts
I was inspired by https://cs.chromium.org/chromium/src/chrome/test/chromedriver/chrome_launcher.cc?sq=package:chromium&dr=C&l=64 which listed a bunch of flags we aren't using yet.
I've added the ones that make sense, along with comments to explain a few.
cc @janpot.. what do you think about flipping on `ignore-certificate-errors` for everyone here? I'm okay with it if you are. :)
=> Add more chrome flags for testing.

lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html, lighthouse-viewer/app/src/lighthouse-report-viewer.js
R: @paulirish 
This also moves the copy button into the export dropdown.
=> Viewer: Tweaks for mobile UI. Fixes #1283

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js, lighthouse-cli/test/smokehouse/pwa-expectations.js, lighthouse-cli/test/smokehouse/smokehouse.js
Allows smokehouse expectations to be objects now. Smokehouse will walk the expected value until getting to any primitive leaves, comparing to the actual result at every step, failing if there is any difference. This allows for the expected value to not be complete, so it doesn't have to include noisy details (e.g. audit meta info) better checked by unit tests.
I augmented the PWA and offline smoke test expectations files, but it turns out all those older audits don't include anything that interesting in their extended info (at least compared to newer audits). `manifest-theme-color` doesn't even output what the `theme_color` actually is. We can kick off the DBW deep expectations after this PR.
Originally I planned to allow the old expectations format (if it's just a primitive value, assume …
=> update smokehouse to do deep result comparisons

lighthouse-core/audits/viewport.js, lighthouse-core/test/audits/viewport-test.js, package.json, yarn.lock
Fixes #641. and comments in it; allow a viewport to pass if it has width *or* initial-scale, and tweak the displayed error message to say this. It also allows spaces in the viewport elements, they are explicitly given in an example on e.g. https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193
=> Viewport test: accept initial-scale and allow spaces

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
=> DBW: update smokehouse tests to do deep equals

.eslintrc.js, lighthouse-cli/performance-experiment/report/injected-script.js, lighthouse-cli/test/fixtures/static-server.js, lighthouse-cli/test/smokehouse/smokehouse.js, lighthouse-core/gather/driver.js, lighthouse-core/index.js, lighthouse-core/lib/console-quieter.js, lighthouse-core/scripts/build-traceviewer-module.js, lighthouse-extension/app/src/chromereload.js, lighthouse-extension/app/src/lighthouse-background.js, lighthouse-viewer/app/src/lighthouse-report-viewer.js, lighthouse-viewer/app/src/logger.js
=> chore: fix eslint no-undef

lighthouse-core/report/scripts/lighthouse-report.js, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html, lighthouse-core/test/report/report-test.js, lighthouse-viewer/app/src/lighthouse-report-viewer.js, lighthouse-viewer/app/src/main.js, lighthouse-viewer/app/styles/viewer.css
R: @paulirish @patrickhulce @brendankenny 
This adds a button to the nav. When clicked, the local report opens the viewer ( http://googlechrome.github.io/lighthouse/viewer/) in a new tab and `postMessage`'s the report json to it. The online viewer has a `message` listener that responds and constructs the page. This functionality will encourage folks to use the online viewer (where we have save as gist, shareable links, export functionality, etc.) It may also be a solution for the DevtTools integration.
On http://googlechrome.github.io/lighthouse/viewer/, the "view online" button will be disabled:
On html reports generated by the CLI or the extension, the button will be enabled:
Security concerns were addressed in https://github.com/GoogleChrome/lighthouse/issues/1188 by removing `{{{}}}` …
=> Open in Lighthouse Viewer button

lighthouse-core/report/scripts/lighthouse-report.js
R: all
The people have spoken. They want better printing!
=> Expand report <details> on print. Fixes #1240

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/audits/unused-css-rules.js, lighthouse-core/scripts/run-mocha.sh, lighthouse-core/test/audits/unused-css-rules-test.js, package.json
* filter out duplicate stylesheets
* don't report stylesheets that have no rules
addresses #1456
=> fix: less noisy CSS unused rules

lighthouse-core/gather/gatherers/css-usage.js
=> fix: recover if protocol does not support CSS rule usage

lighthouse-cli/package.json, lighthouse-extension/package.json
lighthouse-cli: specify name and private: true.
lighthouse-extension: fix name property.
The first fixes npm install warning `> undefined prepublish`.
The second fixes `npm ERR! Refusing to install lighthouse as a dependency of itself` when doing `npm run install-cli` or `npm run install-all`.
=> A couple of package.json fixes.

lighthouse-core/report/scripts/lighthouse-report.js
R: all
This looks scarier than it is. It's a small refactor of the main report into a class. The idea is that other views can subclass the main report functionality. This is working towards https://github.com/GoogleChrome/lighthouse/issues/1166 and a cherry pick from https://github.com/GoogleChrome/lighthouse/pull/1169/files. 
Note: `class` and `=>` support is really good theses days, so not worried about any x-browser issues.
=> Factor report into class

lighthouse-core/gather/connections/connection.js, lighthouse-core/gather/driver.js, lighthouse-core/gather/gatherers/styles.js
gatherRunner, driver, and gatherers enable and disable domains at will, and we currently have no system for tracking the state of them so that they don't interfere with each other. This has happened a few times in the past and it's difficult to track down why e.g. an event never fires because someone else disabled the domain you were listening to. Most recently this came up in [#1421](https://github.com/GoogleChrome/lighthouse/pull/1421/files#diff-99ebf6049dff383295940e4dc7b63754R125) where the `styles` and `css-usage` gatherers interfere when cleaning up after themselves.
This PR tracks `enable` and `disable` commands sent through the driver, eliminates redundant calls and prevents disabling by one user of the domain if others have also enabled it but have not yet disabled it.
The second …
=> track enabled debugger domains for safe simultaneous use

lighthouse-core/audits/unused-css-rules.js, lighthouse-core/test/audits/unused-css-rules-test.js
=> fix(unused-css-rules): remove stylesheet preview for sheets with URL

lighthouse-extension/app/manifest.json, lighthouse-extension/app/popup.html, lighthouse-extension/app/src/popup.js
R: all
I'm not sure why the crx uses a persistent background page, but it doesn't need it. They are generally discouraged in favor of on-demand [event pages](https://developer.chrome.com/extensions/event_pages), which consume less memory in Chrome and are better for perf.
The changes here are mostly:
- Moving to an event page. This requires using `chrome.runtime.getBackgroundPage` which is async. I've created a promise and wrapped code that needs the background page in it.
- Moving code around (aka doing less work in `DOMContentLoaded`). We were defining a bunch of functions and delaying all work until `DOMContentLoaded`.
=> CRX: persistent background page -> event page

lighthouse-cli/test/cli/printer-test.js, lighthouse-core/formatters/critical-request-chains.js, lighthouse-core/lib/log.js, lighthouse-core/test/formatter/critical-request-chains-test.js
Now tests should pass on all platforms.
Part of the ongoing work to have tests pass on Windows.
=> Refactor critical-request-chains-test.js log code.

.travis.yml
It's listed in CLI's dependencies so this is redundant.
=> .travis.yml: remove global installation of typescript.

lighthouse-extension/app/manifest.json, lighthouse-extension/app/src/lighthouse-background.js
=> CRX: disable extensions before running lighthouse

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/audits/dobetterweb/uses-http2.js, lighthouse-core/audits/dobetterweb/uses-optimized-images.js, lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js, lighthouse-core/formatters/formatter.js, lighthouse-core/formatters/partials/table.html, lighthouse-core/formatters/table.js, lighthouse-core/report/report-generator.js, lighthouse-core/test/audits/dobetterweb/uses-http2-test.js, lighthouse-core/test/audits/dobetterweb/uses-optimized-images-test.js, lighthouse-core/test/audits/dobetterweb/uses-passive-event-listeners-test.js, lighthouse-core/test/formatter/table-formatter-test.js
R: all
This adds a new `<table>` formatter for HTML reports which increases clarity, fixes some overflow UI bugs we had with text, and will allow us to more easily add additional extended info in the future (e.g. extra properties from the gatherers, RUM data column, etc.)
An audit uses the formatter like so:
const createTable = Formatter.getByName('table').createTable;
...
extendedInfo: {
formatter: Formatter.SUPPORTED_FORMATS.TABLE,
value: {
table: createTable({url: 'URL', protocol: 'Protocol'}, resources),
results: resources
}
}
Notes:
- All the cells are `overflow: auto` so you can scroll them to reveal more of the url/code snippets
- the original `results` are also being returned in `extendedInfo` so unit testing is easier and so we have the full objects as returned by the gatherer. …
=> Add table list formatter for HTML audits

lighthouse-core/formatters/table.js
addresses #1537 
a more robust fix with tests that addresses the underlying issue can be found in #1536
=> fix(table-formatter): account for undefined values

.eslintrc.js, lighthouse-cli/test/global-mocha-hooks.js, lighthouse-core/gather/driver.js, lighthouse-core/lib/console-quieter.js, lighthouse-core/lib/log.js, lighthouse-core/report/report-generator.js, lighthouse-core/test/global-mocha-hooks.js
enabled now that we have node v6 as the baseline.
sorry @ebidel, got to it first :)
=> use rest parameters instead of arguments

lighthouse-core/gather/connections/cri.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/fake-driver.js
=> CLI: close tab when we're done with it.

lighthouse-core/report/templates/report-template.html
R: all
This was discussed at the meeting today and I wanted to see the difference. It's small change but I think it goes a lonnnnnng way to reduce the visual density of the report.
Before:
After:
=> Report: do not expand help text by default when audit is violated

lighthouse-core/formatters/partials/speedline.html, lighthouse-core/formatters/speedline-formatter.js, lighthouse-core/test/formatter/speedline-formatter-test.js
For a bit, these metrics have reported blanks: 
This was following the refactor of the speedindex extendedInfo. This PR fixes the output of CLI/HTML to correctly emit these timings.
=> Restore "first visual change" to output.

lighthouse-core/report/scripts/lighthouse-report.js, lighthouse-core/report/templates/report-template.html, lighthouse-viewer/app/src/lighthouse-report-viewer.js
R: all
This makes Viewer extend the base report class. 
Step towards https://github.com/GoogleChrome/lighthouse/issues/1166 and gives us the same print features that the core report has (namely the opening and closing of the "more information" `<details>` when printing.
=> Viewer: extend report viewer from base class

lighthouse-core/audits/first-meaningful-paint.js, lighthouse-core/audits/user-timings.js, lighthouse-core/gather/computed/computed-artifact.js, lighthouse-core/gather/computed/trace-of-tab.js, lighthouse-core/test/audits/first-meaningful-paint-test.js, lighthouse-core/test/audits/time-to-interactive-test.js, lighthouse-core/test/audits/user-timing-test.js, lighthouse-core/test/fixtures/traces/trace-user-timings.json, lighthouse-core/test/gather/computed/trace-of-tab-test.js
We often need to parse a trace and find the main thread, its navigationStart, and get our thread events available and sorted.
This PR introduces a computed artifact that can be reused across audits. It also migrates FMP, TTI, and user-timing audits to leverage it.
Reviewers: there is some noisiness in the diff that ?w=1 will nuke.
--
should fix #762
=> Introduce TraceOfTab computed artifact

lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html
R: all
This is an alternative to https://github.com/GoogleChrome/lighthouse/pull/1489.
The benefit is that it keeps the SVG unencoded (easier to maintain later) and also fixes the checkboxes in firefox. Didn't touch the Beta banner for FF. Probably not worth it.
=> Report: fix rendering issues in FF. Fixes #1124

lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js, lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js
addresses one of the failing tests in #1573 
earlier versions of Chrome apparently collect multiple network records for data URIs
=> fix(optimized-images): dedupe image URLs

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/audits/dobetterweb/no-console-time.js, lighthouse-core/audits/dobetterweb/no-datenow.js, lighthouse-core/formatters/table.js, lighthouse-core/test/audits/dobetterweb/no-console-time-test.js, lighthouse-core/test/audits/dobetterweb/no-datenow-test.js, lighthouse-core/test/formatter/table-formatter-test.js
R: all
This also ads the table heads to the pretty print output. The alignment is not great, but otherwise it's hard to know what the columns mean. Ideally, we'd bring in a CLI table formatter, but ...g3 :(
=> Move date.now and console.time audits to table formatter

lighthouse-core/audits/dobetterweb/no-old-flexbox.js, lighthouse-core/audits/theme-color-meta.js, lighthouse-core/audits/unused-css-rules.js, lighthouse-core/audits/viewport.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/gather/gatherers/css-usage.js, lighthouse-core/gather/gatherers/gatherer.js, lighthouse-core/gather/gatherers/styles.js, lighthouse-core/gather/gatherers/theme-color.js, lighthouse-core/gather/gatherers/viewport.js, lighthouse-core/runner.js, lighthouse-core/test/audits/dobetterweb/no-old-flexbox-test.js, lighthouse-core/test/audits/theme-color-meta-test.js, lighthouse-core/test/audits/unused-css-rules-test.js, lighthouse-core/test/audits/viewport-test.js, lighthouse-core/test/gather/gather-runner-test.js, lighthouse-core/test/gather/gatherers/theme-color-test.js, lighthouse-core/test/gather/gatherers/viewport-test.js, lighthouse-core/test/runner-test.js
retrying #1498 (as next step of #941), now with errors from gatherers being considered recoverable by default. If you want to stop a run, throw an error with a `fatal` property set to `true`.
Biggest benefit is that if something throws inside a gatherer that isn't something the gatherer cares about or is specifically watching for, it can just let the exception go. That means
- no more `catch` block in every gatherer
- no more `-1` artifacts...now they're just `Error` objects
- no more checking for `-1` artifacts in every audit. If one of an audit's `requiredArtifacts` is an error, the audit never runs and LH emits an error result on behalf of that audit.
First commits changes old `recoverable` infra to support `fatal`.
Other commits try switching over some of our gatherers to using this …
=> Start using errors instead of -1 for error artifacts

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js, lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js, lighthouse-core/test/audits/dobetterweb/link-blocking-first-paint-test.js, lighthouse-core/test/audits/dobetterweb/script-blocking-first-paint-test.js, lighthouse-core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js
Switches the blocking tag audits to report the maximum delay of first paint rather than a sum of the individual delays. Moves us more in alignment with the actual impact these violations have on the UX.
Also removes duplicate URLs from showing up twice to be inline with our use of "resources" and switches to table formatter.
**Before**:
**After**:
=> fix: report proper first paint delay for blocking tags audits

lighthouse-cli/performance-experiment/report/partials/config-panel.html, lighthouse-core/gather/gather-runner.js, lighthouse-core/lib/emulation.js, lighthouse-core/report/report-generator.js, lighthouse-core/report/scripts/lighthouse-report.js, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html, lighthouse-core/runner.js
Added a section at the end of the report page which shows the runtime configuration of this report (e.g. disable CUP throttling).
Screenshot [updated]:
Will add some test cases later.
=> Show runtime configuration on report

lighthouse-core/report/scripts/lighthouse-report.js, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html, lighthouse-viewer/app/index.html
R: @paulirish 
- Moves the header area back to being position fixed so the config info, url, and buttons are always visible when scrolling the report.
- This fixes some issues with the mobile view of the report introduced in https://github.com/GoogleChrome/lighthouse/commit/a5416c46c957b9f57824117bc3928c5c80fdd75e.
- Also fixes some JS issues in the Viewer after the addition of the new toggle button.
=> Report: fixes for mobile. Also make header position: fixed again

lighthouse-cli/chrome-finder.ts
=> Windows: Look into `LIGHTHOUSE_CHROMIUM_PATH` variable too.

lighthouse-core/audits/accessibility/aria-allowed-attr.js, lighthouse-core/audits/accessibility/aria-required-attr.js, lighthouse-core/audits/accessibility/aria-valid-attr-value.js, lighthouse-core/audits/accessibility/aria-valid-attr.js, lighthouse-core/audits/accessibility/color-contrast.js, lighthouse-core/audits/accessibility/image-alt.js, lighthouse-core/audits/accessibility/label.js, lighthouse-core/audits/accessibility/tabindex.js
=> add help text (and links) to a11y audits

lighthouse-core/gather/gather-runner.js
=> ignore protocol error from closing tab after Chrome has been killed

lighthouse-cli/test/cli/printer-test.js, lighthouse-core/audits/viewport.js, lighthouse-core/formatters/partials/table.html, lighthouse-core/report/report-generator.js, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html, lighthouse-core/test/report/report-test.js
BTW, this fixes a 404 link along the way (the link with the double quotes).
=> Report: Fix HTML validation errors.

lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/gather-runner-test.js
=> fix: failed loading message

lighthouse-core/audits/accessibility/axe-audit.js, lighthouse-core/formatters/partials/accessibility.html, lighthouse-core/test/audits/accessibility/aria-allowed-attr-test.js, lighthouse-core/test/audits/accessibility/aria-required-attr-test.js, lighthouse-core/test/audits/accessibility/aria-valid-attr-test.js, lighthouse-core/test/audits/accessibility/aria-valid-attr-value-test.js, lighthouse-core/test/audits/accessibility/axe-audit-test.js, lighthouse-core/test/audits/accessibility/color-contrast-test.js, lighthouse-core/test/audits/accessibility/image-alt-test.js, lighthouse-core/test/audits/accessibility/label-test.js, lighthouse-core/test/audits/accessibility/tabindex-test.js, lighthouse-core/test/formatter/accessibility-test.js, lighthouse-core/test/formatter/critical-request-chains-test.js, lighthouse-core/test/formatter/formatter-test.js, lighthouse-core/test/formatter/formatters-test.js, lighthouse-core/test/formatter/user-timings-test.js
R: all
Follow up from suggestion in https://github.com/GoogleChrome/lighthouse/pull/1598#issuecomment-276824513.
Also added html tests for the a11y formatter.
=> Remove debugString from accessibility audits + tests.

lighthouse-cli/performance-experiment/experiment-database/database.js, lighthouse-cli/performance-experiment/server.js, lighthouse-cli/test/cli/performance-experiment/database-test.js
Added some test cases for perf-x database
Also refactored the database a little bit and fixed a bug.
=> Add test cases for perf-x database

lighthouse-cli/performance-experiment/report/partials/config-panel.html, lighthouse-cli/performance-experiment/report/scripts/perf-x.js, lighthouse-cli/performance-experiment/server.js, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html
In interactive mode, the report page will be opened in the default browser. However, the interactive mode report page only works in Chrome currently.
This PR adds support for Safari and Firefox.
=> Fix some cross-browser compatibility issues

lighthouse-core/audits/manifest-short-name-length.js, lighthouse-core/test/audits/short-name-length-test.js
=> correct debugString if no manifest short_name found

lighthouse-core/audits/critical-request-chains.js, lighthouse-core/test/audits/critical-request-chains-test.js
fixes #1427 
This seems to be another one of those cases that seems impossible to happen, but happens. I couldn't repro the error with the URL in the issue.
=> fix: critical request chains error on empty

lighthouse-cli/printer.ts, lighthouse-cli/types/types.ts, lighthouse-core/aggregator/aggregate.js, lighthouse-core/audits/audit.js, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html, lighthouse-core/runner.js, lighthouse-core/test/aggregator/aggregate-test.js, lighthouse-core/test/runner-test.js
Related to #941 
Fixes #1148
Makes #1567 non-fatal again
This PR does two things
- audits can now throw non-fatal errors (like gatherers after #1560) and the `Error` object will be converted into an error result . Any audits that require artifacts from gatherers that have already been converted to using errors will get this behavior today.
- these error results are explicitly handled by `aggregate.js` instead of throwing.
I was going hold off on doing this, but it turns out to be necessary for converting gatherers to using proper `Error` objects for errors. When Runner got an error artifact, [it was outputting `-1` results from audits that depend on them](https://github.com/GoogleChrome/lighthouse/blob/4442f53cb6da4b005733674f0ae996f4c2e8a70c/lighthouse-core/runner.js#L189-L191), but …
=> add explicit result error property for erroneous audit results

lighthouse-viewer/app/src/lighthouse-report-viewer.js
For some weird reason, Firefox needs `document.body.appendChild(a)` too.
Fixes #1574.
=> Fix viewer's "Export -> Save as..." with Firefox.

lighthouse-extension/app/popup.html, lighthouse-extension/app/src/lighthouse-background.js, lighthouse-extension/app/src/popup.js, lighthouse-extension/app/styles/lighthouse.css
R: @brendankenny, all
This makes the enabling/disabling of extension before a LH run a user setting:
My worry was that some users would find the current default behavior (disable all extension before the run) unexpected and frustrating. Any extensions that don't save state when they're killed off will lose data. I suspect there are many that don't follow best practices. Instead, we're making this a setting for people to opt into.
@brendankenny I tried to move some of the bg methods into popup.html like we chatted about but it was getting trickier than it was worth. We allow the user to dismiss the popup while LH is running. It was getting gnarly to make a transient popup communicate state back to the bg page for persistence, then repopulate the UI when the user reopens the popup. I was …
=> CRX: make disabling extension during run, optional

lighthouse-core/audits/first-meaningful-paint.js, lighthouse-core/gather/computed/trace-of-tab.js, lighthouse-core/gather/driver.js, lighthouse-core/lib/traces/pwmetrics-events.js, lighthouse-core/test/audits/first-meaningful-paint-test.js, lighthouse-core/test/fixtures/traces/no_fmp_event.json, lighthouse-core/test/gather/computed/trace-of-tab-test.js
Good test page for this is https://madeby.google.com/phone/ which we always time out after 30s
fixes #1564 
--
fmpCandidate comes from `loading` trace category (for whatever reason). 
The changes in pwmetrics are for handling -1 failures a little better.
=> fMP: Use last fMPCandidate if no FMP is marked.

lighthouse-core/config/perf.json
once we have tags in the default config (#1463), we can swap to that and won't have it fall behind again.
but until then..
=> Update --perf config to latest

lighthouse-cli/printer.ts, lighthouse-cli/test/fixtures/sample.json, lighthouse-cli/types/types.ts, lighthouse-core/aggregator/aggregate.js, lighthouse-core/closure/typedefs/Aggregation.js, lighthouse-core/config/default.json, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html, lighthouse-core/test/results/sample.json
Say goodbye to these friends:
ref #332, #333
=> Remove 'Coming Soon' results from report

lighthouse-core/audits/estimated-input-latency.js, lighthouse-core/audits/first-meaningful-paint.js, lighthouse-core/audits/screenshots.js, lighthouse-core/audits/speed-index-metric.js, lighthouse-core/audits/time-to-interactive.js, lighthouse-core/test/audits/estimated-input-latency-test.js, lighthouse-core/test/audits/speed-index-metric-test.js, lighthouse-core/test/audits/time-to-interactive-test.js
@paulirish since these mostly affect FMP/TTI/speedline code you've touched recently
Eliminate some of the remaining catch statements in audits that were unaffected by migrating gatherers off -1s since they use mostly traces and network records. Technically their -1 results would keep working, but since #1591 they can just throw and Runner will take care of that properly for them.
After this and the manifest gatherer update in #1624, there won't be a single -1 result left from a gatherer or audit :)
=> use Error object instead of -1 audit results

lighthouse-cli/printer.ts, lighthouse-core/formatters/critical-request-chains.js, lighthouse-core/formatters/table.js, lighthouse-core/gather/connections/connection.js, lighthouse-core/index.js, lighthouse-core/lib/traces/tracing-processor.js, lighthouse-core/report/report-generator.js, lighthouse-core/test/audits/dobetterweb/uses-responsive-images-test.js, lighthouse-core/test/audits/speed-index-metric-test.js, lighthouse-core/test/audits/unused-css-rules-test.js
There's also `polyfillNode4Support` which I can't quite look into now. If the name is wrong, the function should be renamed otherwise cleaned up.
=> Use default args now that node 6 is required.

lighthouse-core/audits/dobetterweb/uses-optimized-images.js, lighthouse-core/audits/dobetterweb/uses-responsive-images.js, lighthouse-core/formatters/partials/table.html, lighthouse-core/formatters/table.js, lighthouse-core/gather/gatherers/image-usage.js, lighthouse-core/report/report-generator.js, lighthouse-core/test/audits/dobetterweb/uses-optimized-images-test.js, lighthouse-core/test/formatter/table-formatter-test.js, lighthouse-core/test/report/report-test.js
R: @patrickhulce all
This adds image previews to the formatter. Clicking the previews opens the full size version.
=> Add inline image preview to table formatter

lighthouse-cli/test/cli/chrome-launcher-test.js, lighthouse-cli/test/cli/index-test.js, lighthouse-core/formatters/partials/speedline.html, lighthouse-core/lib/log.js, lighthouse-core/scripts/run-mocha.sh
_Update: only dot now.. no more landing strip :(_
Using the landing strip reporter for us.  It looks like this:
Pretty nice as it gives some idea of progress through the suite.
Travis logs every screen change, so I swapped it to the `dot` reporter, which looks like this:
Errors in the suite are still reported the exact same way. It's just you see the progress differently
-----
a few other things:
* in chrome-launcher-test I silenced all the logging output (all about "waiting for browser.."
* This required changing how we tell debug() to shut up, but I like this way better
* similarly, the `pipe` change in index-test was to avoid seeing "Please provide a url" logged to terminal
* And I also nuked some unused CSS in a driveby
PTAL!
=> More concise unit test running

lighthouse-core/gather/connections/cri.js, lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners.js
this was some low hanging performance fruit discussed last week, getting all the event listeners for all nodes in the page in parallel rather than waiting on each command to finish. We aren't enabling/disabling domains or listening for events, so this should be safe.
Profile for the `EventListeners` gatherer doesn't look all that different but it does save e.g. 700ms (1300 -> 600) when running on www.chromestatus.com.
before:
after:
(purple block under 11750ms is all the commands now being sent at once. Remaining scatter of blocks is now just returning messages, not interleaved returning messages and sending messages)
=> perf: gather all event listeners in parallel

lighthouse-core/audits/cache-start-url.js, lighthouse-core/audits/manifest-background-color.js, lighthouse-core/audits/manifest-display.js, lighthouse-core/audits/manifest-exists.js, lighthouse-core/audits/manifest-icons-min-144.js, lighthouse-core/audits/manifest-icons-min-192.js, lighthouse-core/audits/manifest-name.js, lighthouse-core/audits/manifest-short-name-length.js, lighthouse-core/audits/manifest-short-name.js, lighthouse-core/audits/manifest-start-url.js, lighthouse-core/audits/manifest-theme-color.js, lighthouse-core/closure/typedefs/Manifest.js, lighthouse-core/gather/gatherers/cache-contents.js, lighthouse-core/gather/gatherers/manifest.js, lighthouse-core/test/audits/cache-start-url-test.js, lighthouse-core/test/audits/manifest-background-color-test.js, lighthouse-core/test/audits/manifest-display-test.js, lighthouse-core/test/audits/manifest-exists-test.js, lighthouse-core/test/audits/manifest-icons-test.js, lighthouse-core/test/audits/manifest-name-test.js, lighthouse-core/test/audits/manifest-short-name-length-test.js, lighthouse-core/test/audits/manifest-short-name-test.js, lighthouse-core/test/audits/manifest-start-url-test.js, lighthouse-core/test/audits/manifest-theme-color-test.js, lighthouse-core/test/gather/gatherers/cache-contents-test.js, lighthouse-core/test/gather/gatherers/manifest-test.js
Part of #941. There a lot of audits that depend on the manifest gatherer, so separated this one from #1623.
The most impactful change I made was to make the manifest gatherer return `null` if the page has no manifest as it seems appropriate to have an explicit value for this (and obviously not having a manifest is not an error).
This sticks to the minimal redundancy of `debugString`s that #1598 started: if the page has no manifest, all the manifest audits will fail with no message. If the manifest was there but invalid JSON, they will all fail but only `manifest-exists` will report the `debugString`.
There's a good bit of redundancy here. It may make sense to split these into their own `audits/` subdirectory a la `accessibility/` and do some kind of base class thing (and unify …
=> Update Manifest gatherer to use gather error instead of -1 artifact

.gitignore, lighthouse-core/gather/connections/connection.js, lighthouse-core/gather/connections/message-log.js, lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/lib/asset-saver.js, lighthouse-core/test/gather/connections/message-log-test.js, lighthouse-core/test/lib/asset-saver-test.js
=> feat: save devtools log

lighthouse-core/audits/estimated-input-latency.js, lighthouse-core/audits/time-to-interactive.js, lighthouse-core/gather/computed/tracing-model.js, lighthouse-core/lib/traces/tracing-processor.js, lighthouse-core/test/gather/computed/tracing-model-test.js
Right now we're generating a traceviewer tracingModel twice.
It's fairly expensive, so by moving it to a computed artifact, we get caching for free. Woo!
=> perf: tracingModel to computed artifact

lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/gather-runner-test.js
came up in testing 1.5.0 for release. Runs fail testing e.g. `https://example.com/#/whatever`
Testing a URL with hash content will always fail the `GatherRunner.assertPageLoaded()` check so this uses `URL.equalWithExcludedFragments` instead of strict equality testing.
=> ignore URL fragment when asserting page loaded

lighthouse-core/formatters/table.js, lighthouse-core/test/formatter/table-formatter-test.js
R: @ebidel all
Image previews were broken for URLs with `)` since markdown can't handle them
Before
After
=> fix: table formatter image preview URL encode

lighthouse-core/gather/gatherers/dobetterweb/geolocation-on-start.js, lighthouse-core/gather/gatherers/dobetterweb/notification-on-start.js, lighthouse-core/test/audits/dobetterweb/geolocation-on-start-test.js, lighthouse-core/test/gather/gatherers/dobetterweb/geolocation-on-start-test.js
=> Geolocation audit: warn if page is non-secure origin

.npmignore
leaving in `lighthouse-cli/test` for now as it's relatively small (200KB, fixtures and all) and smokehouse is really convenient for testing that the npm module works before publishing
=> ignore core and viewer tests from npm module

lighthouse-cli/performance-experiment/report/partials/config-panel.html, lighthouse-cli/test/fixtures/accessibility/accessibility_tester.html, lighthouse-core/scripts/traceviewer-module-index.html, lighthouse-extension/app/popup.html
* Use lowercase `doctype` and `charset`
* Remove unneeded closing tag from self closing tag
* Clean up inline CSS
=> Minor HTML hygiene.

lighthouse-extension/app/manifest.json, lighthouse-extension/app/popup.html, lighthouse-extension/app/src/lighthouse-background.js
Didn't remove code or html for now so we can test if this setting is impactful.
=> Hide disable extension setting

lighthouse-cli/bin.ts, lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/gather-runner-test.js
=> feat: support skipping cache and storage clear

.eslintignore, .gitignore, .npmignore, appveyor.yml, lighthouse-core/scripts/download-chrome.sh, readme.md
Fixes #1079.
**Preview**: <https://ci.appveyor.com/project/XhmikosR/lighthouse/history>
**Before merging**: one of the project maintainers needs to add AppVeyor to the repository and paste the image link so that I add it in readme.md and rebase.
=> Add AppVeyor CI support for Windows testing.

lighthouse-core/gather/connections/connection.js, lighthouse-core/gather/connections/extension.js
fixes #1696
Missed this in #1474. Simply replaces the call of `handleRawError` in `extension.js` with what it contained before removal.
=> remove handleRawError call from extension connection

lighthouse-core/formatters/partials/table.css
=> Report: fix table overflow with Firefox.

lighthouse-core/formatters/critical-request-chains.js, lighthouse-core/formatters/partials/critical-request-chains.css, lighthouse-core/formatters/partials/critical-request-chains.html, lighthouse-core/test/formatter/critical-request-chains-test.js
Some upgrades to this little guy to make it more concise.
* Put most of the details in a `details/summary` so its not too loud in the report
* The 3 "longest chain" stats from the top were looking at (potentially) 3 individual chains. I changed it to pick the winner based on total duration, and then report the req count & kb size total from it as well.
* Formatting for "initial navigation" in HTML so its clear it belongs to the ascii art.
* toLocaleString() so we have thousands separator. 
* Time durations (ms) reported with 1 decimal place. File sizes (kb) remain at 2 places.
Screenshots:
| before | after | 
|-------|----|
| ![image](https://cloud.githubusercontent.com/assets/39191/22670250/40b0fe22-ec7d-11e6-9b35-e8c7b3c35733.png) | …
=> Reformat the critical chain output

lighthouse-cli/performance-experiment/report/partials/config-panel.html, lighthouse-cli/test/fixtures/accessibility/accessibility_tester.html, lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/fixtures/offline-ready.html, lighthouse-cli/test/fixtures/online-only.html, lighthouse-core/formatters/partials/critical-request-chains.css, lighthouse-core/formatters/partials/table.css, lighthouse-core/formatters/partials/user-timings.css, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html, lighthouse-extension/app/styles/lighthouse-loading.css, lighthouse-extension/app/styles/lighthouse.css, lighthouse-viewer/app/styles/viewer.css
* use numeric values for `font-weight`
* stop using shorthands when one property is meant to change (`background`, `list-style`)
* use hex color values instead of rgb or color names when they are shorter
* use `outline: none` instead of zero
* remove duplicate property `border-radius`
* fix typo in comment
* minor HTML consistency changes
=> CSS consistency changes.

CONTRIBUTING.md, docs/architecture.md, docs/headless-chrome.md, readme.md
R: all
Also fixes #1719. 
The example is extracted and simplified from lighthouse hue lights thing I made. Happy to rework it a little, but it's pretty chill and is known to be everything you need to call LH programmatically.
=> README: Reorganization and new "Using programmatically" section

lighthouse-core/formatters/partials/table.css, lighthouse-core/formatters/partials/table.html, lighthouse-core/formatters/table.js, lighthouse-core/report/handlebar-helpers.js, lighthouse-core/test/formatter/table-formatter-test.js, lighthouse-core/test/report/handlebar-helpers-test.js
R: @paulirish all
**Before**
**After**
=> fix: clean up table styling

lighthouse-cli/bin.ts, lighthouse-core/gather/driver.js, package.json, readme.md, yarn.lock
=> feat: configurable page timeout

lighthouse-cli/chrome-launcher.ts
should deflake the appveyor tests that have been failing ~50% of the time because of this
=> fix: do not fail if chrome could not be killed

lighthouse-cli/test/fixtures/sample.json, lighthouse-core/config/default.json, lighthouse-core/report/templates/report-template.html
=> Link to PWA Checklist

lighthouse-core/config/config.js, lighthouse-core/config/default.json, lighthouse-core/test/config/config-test.js, readme.md
would address part of #1730, it's rather out there so comments and thoughts welcome on other possible approaches
usage
```
{
extends: true,
passes: [
{passName: "defaultPass", gatherers: [MyCustomGatherer]
],
audits: [MyCustomAudit]
}
```
=> feat: allow extension of default config

lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/gather-runner-test.js
addresses parts of #1730 
would be used in conjunction with #1731
usage
```
{
passes: [
{passName: "defaultPass", blankPage: "http://google.com", blankDuration: 10000}
...
]
...
}
```
=> feat: configurable blank page options

lighthouse-core/formatters/partials/critical-request-chains.css, lighthouse-core/report/styles/report.css
**before**
**after**
Now the report should be WCAG2AA valid.
=> report: Tweak colors so that we are WCAG2AA valid.

lighthouse-core/aggregator/aggregate.js, lighthouse-core/audits/dobetterweb/dom-size.js, lighthouse-core/config/default.json, lighthouse-core/formatters/partials/cards.css, lighthouse-core/formatters/partials/cards.html, lighthouse-core/report/handlebar-helpers.js, lighthouse-core/report/styles/report.css, lighthouse-core/report/templates/report-template.html, lighthouse-core/test/aggregator/aggregate-test.js, lighthouse-core/test/formatter/cards-formatter-test.js
R: @patrickhulce @paulirish 
In the act of de-cluttering, this PR addresses some of of https://github.com/GoogleChrome/lighthouse/issues/1613 and implements the proposed solution in https://github.com/GoogleChrome/lighthouse/issues/1613#issuecomment-277126590.
Now, if all audits pass, the entire aggregation is collapsed. If one or more audits fail, the aggregation is opened up.
Before:
After:
when an audit fail: 
BTW, the aggregation icons are slightly bigger than the subaudits. I thought the size difference was good but I'm happy to make them all the homogeneous. 
- Aggregations now always create an overall score. Please look over those changes as I may have missed something.
- Adds css transitions to the details dropdown.
- @patrickhulce turns out the `expectedValues`/`weights` are …
=> Report: collapse aggregations when all audits pass

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-cli/test/smokehouse/pwa-config.js, lighthouse-cli/test/smokehouse/pwa-expectations.js, lighthouse-core/gather/gatherers/dobetterweb/domstats.js
R: all
Couple of subtle edge cases found on https://www.chromestatus.com/features, which uses shadow dom and inline svg.
The first is traversing up through parent elements looking for shadow hosts / parentElements. Anchors have a `.host` property. So looking at `node.host` does not necessarily give you a shadow root :\ First time I've ran into this when working with web components!
Now we construct the depth properly:
The second issue fixed is checking `svgNode.className`. Turns out, svg nodes return a `SVGAnimatedString = {animVal: string, baseVal: string}` instead of a string. Ugh! Switched to using the `class` attr instead.
Added chromestatus.com to the smoketests.
=> DOMStat audit: fix for traversing shadow root anchor parents and svg .className

lighthouse-cli/test/fixtures/byte-efficiency/large.svg, lighthouse-cli/test/fixtures/byte-efficiency/tester.html, lighthouse-cli/test/fixtures/static-server.js, lighthouse-core/audits/byte-efficiency/uses-responsive-images.js, lighthouse-core/test/audits/byte-efficiency/uses-responsive-images-test.js
=> fix: responsive image audits for vectors and duplicates

lighthouse-core/gather/connections/extension.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/runner.js
I am hoping this will fix #1214, but since the repro is particularly tricky, we won't know until later.
I believe is ultimately a chrome bug that's behavior is here: [546696 - chrome.windows.getLastFocused returns the last opened window, not the last focused, when an extension popup is visible - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=546696#c4) but essentially its interplay between extensions with `onFocusChanged` `getLastFocused` and here, `chrome.tabs.query({lastFocusedWindow: true})`..
Of note, previous to the currentTab change in #680 I don't believe we had this bug, but we did have trouble when debugging the extension background page with a devtools window. I'm OK with regressing our developer ergonomics to get this user bug squashed. …
=> Speculative fix for getCurrentTabURL

lighthouse-core/report/styles/report.css
R: all
The report colors were recently adjusted to meet accessibility contrast for WCAG 2 AA, but the new average color is mustard and the red/green are quite deep. This PR dials them back a bit, returns the average color to an orange, but still keeps WCAG 2 AA at 18pt. I used [this](https://snook.ca/technical/colour_contrast/colour.htm) tool to verify the colors are still compliant.
The colors are from the MD color palette. 
cc @robdodson 
Before:
After:
=> Report: use accessible material colors

lighthouse-extension/gulpfile.js, lighthouse-extension/package.json, lighthouse-extension/yarn.lock
Since I [keep going on about this](https://github.com/GoogleChrome/lighthouse/pull/1756#issuecomment-281544651), I figured I'd give it a try. This is a PR against @ebidel's open PR (#1756)
Very conservative settings for the minification. And luckily, no problems with the build at all, so far. 
I also retain the lines, which makes for happier stack traces. This costs about 100K, but I think it's worth it. Kinda funny, but here's what it looks like: [screenshot](https://cloud.githubusercontent.com/assets/39191/23244855/ff8204ce-f93c-11e6-88a9-7948424f2205.png)
The filesize breakdown:
| | size | 
|-|-|
| original | 2,537,217 bytes |
| uglify (1756) | 1,725,484 bytes (32% smaller) |
| babel (this pr) | 1,828,032 bytes  (28% smaller)  |
| babel w/o lines | 1,775,509 bytes  (30% smaller)  |
so …
=> Reduce build size (via babel instead)

lighthouse-core/gather/connections/cri.js, lighthouse-core/gather/gather-runner.js
Only happens in the CLI case, so far, as thats the only place we spawn a new tab.
Fixes https://github.com/GoogleChrome/lighthouse/issues/970
In this PR:
* We move most of the impl of `CriConnection.connect` into `_connectToSocket`
* We introduce a fallback mode if the `this._runJsonCommand('new')` rejects, where we reuse the first tab available. 
* We will make sure our chosen tab is in the foreground, as well.
=> Reuse existing tab if creating new tab fails

lighthouse-core/config/default.json, lighthouse-core/config/perf.json, lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/fake-driver.js, lighthouse-core/test/gather/gather-runner-test.js
This is the approach that I ended up with after playing around a bit.
* `useThrottling` prop in the config for each pass
* if that is true and the disable CLI flags aren't set, then we'll turn it on.
* if the prop is false for a pass we'll definitely make sure throttling is off
* when `goOnline` comes back it'll restore whatever throttling should be for that pass.
* `setThrottling` method in driver does the work. the old `beginEmulation` now defers to it for some parts.
wdyt?
=> Disable throttling for non-performance passes

lighthouse-cli/bin.ts, lighthouse-cli/printer.ts
First step in closing #1739 (Is it time to deprecate the CLI report output?)
1. Adds a `--view` flag which will open the HTML report that the CLI generated in your default browser.
2. Default `output` changes from `pretty` to `none`, which means you dont get the full report flooding your terminal at the end. You _can_ re-enable it with `--output=pretty`, however. 
3. Log two little tips to stdout telling the CLI users about the change.
=> Add --view flag. Don't default CLI report to stdout.

readme.md
For a second I thought `console.err` is a thing! 
✌🏼
=> Fix typo in README: s/console.err/console.error

lighthouse-core/audits/byte-efficiency/unused-css-rules.js, lighthouse-core/audits/byte-efficiency/uses-optimized-images.js, lighthouse-core/audits/byte-efficiency/uses-responsive-images.js, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js, lighthouse-core/audits/dobetterweb/script-blocking-first-paint.js, lighthouse-core/config/default.json, lighthouse-core/config/perf.json, lighthouse-core/formatters/partials/table.html
=> Move perfy stuff into Perf Diagnostics report aggregation.

lighthouse-core/lib/asset-saver.js
Also, use lowercase hex colors and switch to the explicit `background-image` property.
=> asset-saver: specify meta charset.

lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js, lighthouse-core/formatters/partials/table.css, lighthouse-core/lib/event-helpers.js, lighthouse-core/report/handlebar-helpers.js, lighthouse-core/test/audits/dobetterweb/uses-passive-event-listeners-test.js, lighthouse-core/test/lib/event-helpers-test.js
R: @patrickhulce @paulirish 
Fixes #1781. Also put a restriction on the max-height for table cell pre tags. Without it, the cell could get hhuuuuuuge.
=> Use pre instead of inline code for listener snippets. Fixes #1781

lighthouse-core/config/default.json, lighthouse-core/config/perf.json, lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js
=> fix: deflake TTI audit by extending trace

lighthouse-core/report/handlebar-helpers.js
I introduced a boo boo for our descriptions that use markdown code snippets:
I was over cautious in adding the escape. This PR removes the addition (and we're only escaping`<pre>`).
=> Revert escaping for code descriptions

lighthouse-core/lib/url-shim.js, lighthouse-core/test/lib/url-shim-test.js
=> Rewrite chrome URLs to compare them.

lighthouse-core/report/styles/report.css
=> fixing the css bug for misaligned score badges on Firefox

lighthouse-core/formatters/partials/user-timings.html
| before | after | 
|---|---|
| ![image](https://cloud.githubusercontent.com/assets/39191/23536677/718e1b90-ff7b-11e6-882f-3466bf389684.png) | ![image](https://cloud.githubusercontent.com/assets/39191/23536684/7a9bbcd8-ff7b-11e6-859b-419d4fdfacf0.png) |
Reviewers: use w=1: https://github.com/GoogleChrome/lighthouse/pull/1810/files?w=1
=> Render usertiming in details/summary

lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/audits/byte-efficiency/unused-css-rules.js, lighthouse-core/audits/byte-efficiency/uses-optimized-images.js, lighthouse-core/audits/byte-efficiency/uses-responsive-images.js, lighthouse-core/audits/critical-request-chains.js, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js, lighthouse-core/audits/dobetterweb/script-blocking-first-paint.js, lighthouse-core/config/default.json
This is a stopgap solution until the new report design.
This changes the iconography on our boolean perf items so that we don't have a check or X next to them.
This is enabled by sendil's PR #1750 
The warning icon is gray (rather than orangeish) due to #1758.
----
i'm shipping a release and so far this is the only thing I consider a blocker.
=> Don't show ✓✘ icons on perf audit results

.gitignore, lighthouse-cli/bin.ts, readme.md
fixes #1714 
not sure what to do exactly about the path, the meaning of the `--output-path` extension starts to fall apart a bit when you have multiple files so figured I'd stick with the current paradigm.
USAGE:
`lighthouse --output html --output json --output-path foobar.html` generates
* foobar.report.html
* foobar.report.json
=> feat: support multiple output modes

lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/gather/driver.js, lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener.js, lighthouse-core/lib/element.js
Fixes issue #1802. The problem is that [getObjectProperty](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L511) rejects a null value which bubbles down into the [recoverOrThrow](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gather-runner.js#L128) function where `err = null`.
I fixed the bug by using the getAttribute function because href is also an attribute and is still available. I also caught the reject(null) from the `getObjectProperty` inside `getProperty` and resolve it with null so in the future other gatherers won't crash.
It's a pretty weird bug. Objects get collected but whenever you want to resolve the properties by `Runtime.getProperties` the object only has a `__proto__` property. My guess is that the …
=> Fixes no rel noopener when properties of anchor element cannot be resolved anymore

lighthouse-core/audits/deprecations.js, lighthouse-core/audits/dobetterweb/dom-size.js, lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js, lighthouse-core/audits/dobetterweb/geolocation-on-start.js, lighthouse-core/audits/dobetterweb/no-document-write.js, lighthouse-core/audits/dobetterweb/notification-on-start.js, lighthouse-core/formatters/formatter.js, lighthouse-core/formatters/partials/cards.html, lighthouse-core/test/report/report-generator-test.js, lighthouse-core/test/results/sample.json
R: @patrickhulce, all
https://github.com/GoogleChrome/lighthouse/pull/1821/files addressed #1820, but it did not completely address the missing formatter output. The card and urllist formatters were still being left out of the html report.
I've also added a test to make sure these special formatters that have obvious HTML hooks (things we can look for in a a test) are being caught.
=> Complete fix for #1820 - missing formatter output

jsconfig.json
Fixes some of our excludes so the typescript compiler doesn't OOM.
This restores intellisense for JS in VSCode.
Also now the extension and viewer JS files are included in intellisense. Woo.
----
protip for future me.. adding this line into typescript's `tsc.js` was pretty instrumental in figuring this out
```diff
if (hasDiagnostics) {
var memoryUsed = ts.sys.getMemoryUsage ? ts.sys.getMemoryUsage() : -1;
+           console.log(program.getSourceFiles().map(f => f.path).join('\n'));
reportCountStatistic("Files", program.getSourceFiles().length);
reportCountStatistic("Lines", countLines(program));
```
=> update jsconfig for latest typescript & VSCode

jsconfig.json, lighthouse-core/lib/emulation.js
For the past few weeks (and potentially longer..*) the screenshots we've grabbed during a trace have looked like this:
It appears this regressed during some headless screenshot work. Both webpagetest and calibre also noticed this within the last 15 days.
The fix is fairly straightforward, though not intuitive unless you sit next to the engineers who know. Luckily i do. phew. :)
[`Emulation.setVisibleSize`](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Emulation/#method-setVisibleSize) to the rescue!
Also on the bright side, Perceptual Speed Index don't appear to have been significantly affected by this regression. Because its a good metric. :)
=> Fix screenshot capture.

lighthouse-core/config/config.js, lighthouse-core/config/default.json, lighthouse-core/test/config/config-test.js, lighthouse-extension/app/popup.html, lighthouse-extension/app/src/lighthouse-background.js, lighthouse-extension/app/src/popup.js, lighthouse-extension/gulpfile.js
This PR is brings back the unmerged patch applied to enable DevTools Audits 2.0 panel integration, and then cleans things up to be less terrible.
Screenshots of what this enables:
The big change is allowing the user to select which top-level aggregations they want, rather than which 2nd-level aggregations they want. :)
Note that the config is expecting some large refactors in the near future. This PR allows the config to remain as is, but the new `Config.generateConfigOfAggregations` will be useful for the new `config.settings.only` and `config.settings.skip` options.
**Reviewers:**
* Note that `getGatherersNeededByAudits` just moved places
* `auditPathToName` is mostly moved from `lighthouse-background` to config. ish.
* The other green in config.js is indeed new, (but the majority of it …
=> Configure lighthouse run by whitelisting aggregations

lighthouse-core/audits/time-to-interactive.js, lighthouse-core/test/audits/time-to-interactive-test.js
With FMP timing available in the `TraceOfTab` computed artifact after #1549, this moves TTI calculation to using that rather than calling into the FMP audit.
Helps with #1568
=> use FMP from TraceOfTab in TTI calc

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/fixtures/static-server.js, lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js
To continue the nightmare that is the blocking stylesheets audit false positives, the last PR helped in the wild, but smokehouse added delays to *all* other blocking sheets that pushed out when our detection script could fire (thus making detection rather flaky). This is just an bad approach, and I still advocate for parsing the document we received at some point instead of all these hoops, but this will make travis more reliable for now.
Real fix should be made in protocol to add initiator information that we need.
=> test: deflake blocking links

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js, lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
unblocks adding TTI consideration to #1807 
Not quite as scary as the diff looks, just extracts the magic to a static function (which decreases indentation level) and adds tests for it.
=> test(byte-efficiency): added tests to base byte efficiency audit

lighthouse-cli/test/smokehouse/pwa-expectations.js, lighthouse-cli/test/smokehouse/smokehouse.js
adds RegExp smokehouse to boot :)
=> test(smokehouse): fix flakiness of smokehouse dom-size expectation

lighthouse-cli/types/types.ts
Since results contains 
```js
{
"lighthouseVersion": "1.6.0",
"generatedTime": "2017-03-21T07:57:38.994Z",
"initialUrl": "http://example.com",
"url": "http://example.com/",
"audits": {
...
```
it will be nice to have `initialUrl` and `generatedTime`. We wanna reuse types form `lighthouse` in scope of `pwmetrics` :)
=> Add properties to Results interface

lighthouse-core/report/scripts/lighthouse-report.js
Hi,
I apologize I mess up the git tree of the previous brunch. I just delete the older pull request and brunch, and create a new one. This one would be clear. I also improve the code to support shortcut expanding.
Thanks,
Zixu Zhao
Original request message:
did some researches of the issue: [Print ->Save as PDF : Pages truncated #1780](https://github.com/GoogleChrome/lighthouse/issues/1780), and here is my solution.
The main problem I found is, once the `window.print()` is called. The printing process will take current page height immediately. In fact, the function [ _setupExpandDetailsWhenPrinting](https://github.com/GoogleChrome/lighthouse/blob/9ac57cb05efd5b0aba6684047382fff670860ca0/lighthouse-core/report/scripts/lighthouse-report.js#L204-L221) works as expected in my tests, i.e. all …
=> Report: print doesn't cut off expanded audit details

lighthouse-core/audits/load-fast-enough-for-pwa.js, lighthouse-core/config/default.json, lighthouse-core/lib/emulation.js, lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js
Basic audit that just checks TTI value against a threshold.
Current UI is 
**Note:** I have this audit included in default.json here, but **I will remove it** _before landing this PR_. It's just there to make testing a bit easier. :)
Once landed, I will move the other perf metrics from PWA to Perf, leaving only this one in PWA.
Fixes #1831
=> Add TTI < 10s audit for PWA

lighthouse-core/audits/byte-efficiency/offscreen-images.js, lighthouse-core/audits/byte-efficiency/uses-responsive-images.js, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js, lighthouse-core/config/default.json
R: @patrickhulce, all
Bit consistency cleanup and rearranging.
- Made the offrescreen audit information to be consistent with the rest of the section.
- sentenced-cased a few audit descriptions
- related perf audits now sit together (stylesheets with css, image audits with other image audits)
- moved scored audits to top. Peeps 💘  dem scores.
Now:
=> Report: Make Offscreen images informative, consistency cleanup

lighthouse-core/gather/computed/trace-of-tab.js, lighthouse-core/lib/traces/pwmetrics-events.js, lighthouse-core/test/fixtures/traces/backgrounded-tab-missing-paints.json, lighthouse-core/test/gather/computed/trace-of-tab-test.js
Fixes #1253 (the "ts of undefined" bug)
=> Improve reliability of finding navStart

lighthouse-core/report/partials/cards.css, lighthouse-core/report/partials/critical-request-chains.css, lighthouse-core/report/partials/table.css, lighthouse-core/report/styles/report.css
R: all
Expands on https://github.com/GoogleChrome/lighthouse/pull/1851 by increasing the size of the icons to 19px to "cheat" at WCAG2AA. See https://github.com/GoogleChrome/lighthouse/pull/1851#issuecomment-285905938
Here's what everything looks like now:
Note, the score labels are set to slightly smaller than they should be but ramping them up to 19px makes them far too big. I've set them to bold 16px, which gets us pretty close.
I don't think we should spend too much more time tweaking the report if things are changing.
=> Report: increase icon size for a11y

lighthouse-core/gather/driver.js, lighthouse-core/test/gather/driver-test.js
fixes #1891
`Runtime.getProperties` returns properties that, even if they're defined [might not have a value](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#type-PropertyDescriptor). This just returns null in that case. As mentioned in #1891, I'm not really sure why no value is being returned in this particular case, since no site I've seen has demonstrated this problem before. We may want to hold off on merging until we figure out the underlying cause so e.g. we could put a link like that into the smoke tests.
Also puts any thrown errors (or rejected promises) from the promise chain starting with `this.sendCommand` back into the main promise chain.
=> handle driver.getObjectProperty results with no value property

lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/gather-runner-test.js
fixes https://github.com/GoogleChrome/lighthouse/pull/1868#pullrequestreview-28817344
=> fix: remove afterPass throttling

lighthouse-cli/compiled-check.js, lighthouse-cli/package.json, package.json
Fixes #1516
R: all
Finally getting rid of this. It's deprecated in npm 5 and we have convenient build scripts now.
=> CLI: remove npm prepublish

lighthouse-core/audits/works-offline.js, lighthouse-core/test/audits/works-offline-test.js
R: @brendankenny all
Fixes #715. I ran into this when debugging and was very confused.  Especially since the report header shows the `finalUrl` and we never tell the user there was a redirect.
https://github.com/GoogleChrome/lighthouse/issues/1917 is still open to message a top-level waring if initial url != final url.
Test with: 
```
npm run fast -- --output=html --view https://www.chromestatus.com/features
npm run fast -- --output=html --view https://www.chromestatus.com
```
=> Offline audit: add warning if initial url != final url

lighthouse-core/audits/estimated-input-latency.js, lighthouse-core/audits/time-to-interactive.js, lighthouse-core/config/default.js, lighthouse-core/gather/computed/trace-of-tab.js, lighthouse-core/lib/traces/pwmetrics-events.js, lighthouse-core/test/audits/estimated-input-latency-test.js, lighthouse-core/test/gather/computed/trace-of-tab-test.js
First round of perf metric investigation, to be judged using #1936 :) Follow-up work includes adding in network reverse search methods for comparison.
- Adds two additional TTI candidates that don't rely on visual completeness.
- First 500ms window after fMP where 90th percentile EIL is <50ms
- First 5000ms window after fMP where 90th percentile EIL is <50ms (if at the end of trace, uses a minimum window of as low as 1000ms)
- Falls back to fMP when speedline fails to find screenshots in trace.
- Adds timing data to trace-of-tab computed artifact.
=> feat(tti): increase robustness of perf metrics

lighthouse-cli/test/smokehouse/perf/expectations.js, lighthouse-cli/test/smokehouse/perf/run-tests.sh, package.json
Using a superfast local site, so we expect 100s on the scores.
Anything else I should add to the expectations?
=> Add a smoke test for perf config.

lighthouse-core/audits/estimated-input-latency.js, lighthouse-core/audits/time-to-interactive.js
filed #1960 to track the issue itself
=> fix: add more helpful error message when fMP is missing

.eslintignore, .gitignore, .npmignore, lighthouse-core/audits/time-to-interactive.js, lighthouse-core/config/plots.json, lighthouse-core/gather/computed/trace-of-tab.js, lighthouse-core/lib/traces/pwmetrics-events.js, lighthouse-core/test/fixtures/dbw_tester-perf-results.json, lighthouse-core/test/lib/traces/pwmetrics-events-test.js, plots/README.md, plots/analyze.js, plots/chart.js, plots/clean.js, plots/constants.js, plots/index.html, plots/measure.js, plots/package.json, plots/utils.js
Follow-up work:
* Do a side-by-side perf metrics comparison with a previous version of Lighthouse (allows you to easily see how a commit will change the metrics on real-world sites)
* Run this on a compute instance in Asia to test the hypothesis that the high variance for international sites is driven by network latency
Fixes part of #1924
=> Measure and visualize perf metrics

.gitignore, docs/hacking-tips.md, lighthouse-core/report/v2/report-generator.js, lighthouse-core/report/v2/report-renderer.js, lighthouse-core/report/v2/report-styles.css, lighthouse-core/report/v2/report-template.html, lighthouse-core/report/v2/templates.html, lighthouse-core/test/report/v2/report-generator-test.js, lighthouse-core/test/report/v2/report-renderer-test.js, lighthouse-core/test/results/sample_v2.json, package.json, yarn.lock
R: all
Before: 
After: 
- Expands failing audits + expander arrows
- Support for boolean audits with X/check
- Renders `optimalValue` text on audit title. Final UI we'll need to work out.
=> Report v2: check/x boolean audits, expand details failing audits, optimal val

gulp/config.js
When work precompile process that occur error. because, precompile process work html in `lighthouse-core/third_party/src/catapult/dashboard/dashboard/templates`. Catapult have not used handlebar.
=> Fixed precompile process.

lighthouse-core/report/v2/report-renderer.js, lighthouse-core/test/report/v2/report-renderer-test.js
R: all
Just support in help text / descriptions.
Will add a test once https://github.com/GoogleChrome/lighthouse/pull/1963 lands.
=> Generate DOM for markdown links in help text

lighthouse-core/audits/dobetterweb/dom-size.js, lighthouse-core/report/v2/renderer/details-renderer.js, lighthouse-core/report/v2/renderer/dom.js, lighthouse-core/report/v2/renderer/report-renderer.js, lighthouse-core/report/v2/report-styles.css, lighthouse-core/test/report/v2/renderer/details-renderer-test.js
R: all
This should wait until https://github.com/GoogleChrome/lighthouse/pull/1979 and https://github.com/GoogleChrome/lighthouse/pull/1987 land and will probably need rebasing, but review can start now. The changes are standalone from those.
=> Report v2: port over cards formatter

lighthouse-core/report/v2/renderer/details-renderer.js, lighthouse-core/report/v2/renderer/dom.js, lighthouse-core/report/v2/renderer/report-renderer.js, lighthouse-core/report/v2/report-template.html, lighthouse-core/test/report/v2/renderer/dom-test.js, lighthouse-core/test/report/v2/renderer/report-renderer-test.js
Gettin the new report going in DevTools and wanted some changes like these.
1. Since I'm subclassing, I need to pass in those subclasses.
1. Globals weren't being provided automatically. (I think because devtools uses eval?)
e.g. my subclass currently looks like (UPDATED):
Screenshot btw:
=> Adjust report-renderer init for devtools

lighthouse-core/closure/typedefs/Artifacts.js, lighthouse-core/closure/typedefs/ComputedArtifacts.js, lighthouse-core/closure/typedefs/SpeedlineArtifact.js, lighthouse-core/gather/computed/computed-artifact.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/runner.js, lighthouse-core/test/audits/estimated-input-latency-test.js, lighthouse-core/test/audits/first-meaningful-paint-test.js, lighthouse-core/test/audits/time-to-interactive-test.js, lighthouse-core/test/audits/user-timing-test.js, lighthouse-core/test/gather/computed/speedline-test.js
There's no reason that a computed artifact shouldn't be able to access other computed artifacts using the same artifact that it received. Since it can't access any new artifacts, just things based on the artifact it's already received, the cache will still work and computation of audits->requiredArtifacts->required gatherers still works.
should fulfill the needs of #2013
I've made a `ComputedArtifacts` type for this object, and had `Artifacts` extend it. Originally I was going to do that for the actual artifact object as well (make the computedArtifact object the prototype of the artifact object), but realized it wasn't necessary.
=> allow computed artifacts to request other computed artifacts

plots/metrics-per-site.html, plots/metrics-per-site.js
Based on the feedback from https://github.com/GoogleChrome/lighthouse/pull/2034, this is another take on visualizing perf metrics per site using box plots. It does a better job of showing many runs for a given site, but doesn't readily show how a particular run may affect multiple metrics (couldn't find a plotly option to do this).
**Example:**
Closes #2011
=> Plots: Visualize metrics per site with box plots

lighthouse-core/gather/gatherers/accessibility.js
@paulirish 
removes the slightly shady looking inlining of axe-core as a `Buffer` from the browserified output:
`const axe=Buffer("LyohIGFYZSB2Mi4xLjcKICogQ29weXJpZ2h0IChjKSAyMDE2IERlcXVlIFN5c3...`
and uses a regular string instead:
`const axe="/*! aXe v2.1.7\n * Copyright (c) 2016 Deque Systems, Inc.\n *\n * You...`
much more clear about what's going on there and actually saves 37KB in `lighthouse-background.js`!
may be a little faster too since it doesn't have to `.toString()` the polyfilled `Buffer`, but I don't see any measurable difference in the face of the axe testing that runs immediately afterwards :)
=> browserify axe-core as a string, not a Buffer

lighthouse-core/gather/gather-runner.js, lighthouse-core/runner.js, lighthouse-core/test/audits/estimated-input-latency-test.js, lighthouse-core/test/audits/first-meaningful-paint-test.js, lighthouse-core/test/audits/manifest-short-name-length-test.js, lighthouse-core/test/audits/splash-screen-test.js, lighthouse-core/test/audits/themed-omnibox-test.js, lighthouse-core/test/audits/time-to-interactive-test.js, lighthouse-core/test/audits/user-timing-test.js, lighthouse-core/test/audits/webapp-install-banner-test.js, lighthouse-core/test/gather/gather-runner-test.js, lighthouse-core/test/runner-test.js
very small refactor to fix something that's bothered me for a while: computed artifacts aren't part of gathering (we use them even if artifacts are provided by the config and Chrome is never run), so creating them should live in runner. Main benefit is we don't have both `runner` *and* `gather-runner` calling `instantiateComputedArtifacts`.
Also fixes a minor bug where the `computedArtifact` base class was being used as a computed artifact. Since it doesn't have a `name` property, it was showing up as `artifacts.requestundefined()` :)
originally part of #2018...but I forgot to push
=> refactor: move instantiateComputedArtifacts to Runner

.travis.yml, lighthouse-core/closure/closure-type-checking.js, lighthouse-core/closure/conformance_config.textproto, lighthouse-core/closure/third_party/commonjs.js, lighthouse-core/report/v2/renderer/details-renderer.js, lighthouse-core/report/v2/renderer/dom.js, lighthouse-core/report/v2/renderer/report-renderer.js, lighthouse-core/test/report/v2/renderer/details-renderer-test.js, lighthouse-core/test/report/v2/renderer/report-renderer-test.js, package.json, yarn.lock
@paulirish already took this most of the way there in #2002, this is just cleaning up the rest and hitting some pretty strict rules, which is nice. It has to be manually run right now (`npm run closure`)...I wasn't sure if I should enable it or not yet in CI.
Two things that might be controversial:
1) `DetailsJSON` has been flattened into basically a base class (`DetailsJSON` with a `type` and optional `text` field) and derived classes `ListDetailsJSON`, and `CardDetailsJSON` (names are terrible :). Inheritance isn't actually used, however.
Precipitating reason is that you can't do circular typedefs, so these weren't being checked at all. DevTools compilation didn't notice because it's not using the NewTypeInference engine (to be fair, we aren't either by default because of some lingering …
=> add Closure type checking for report v2

lighthouse-core/report/v2/renderer/category-renderer.js, lighthouse-core/report/v2/renderer/dom.js, lighthouse-core/report/v2/renderer/report-renderer.js, lighthouse-core/report/v2/report-styles.css, lighthouse-core/report/v2/templates.html, lighthouse-core/test/report/v2/renderer/dom-test.js, lighthouse-core/test/report/v2/renderer/report-renderer-test.js
R: all
First go at the v2 mock score badges. I'm calling these gauges. Needs to be combined with https://github.com/GoogleChrome/lighthouse/pull/2000.
Example usage: `<div class="lh-gauge" data-progress="25">`.  #wouldbeasweetwebcomponent
=> Report v2: category score gauges

lighthouse-core/runner.js
1. Add two lifecycle logs
- 'Analyzing and running audits...'
- 'Generating results...'
2. Exceptions caught in audits will log an warning to the console
- Exceptions in gatherers are already emitted, so we're good there.
1. `Loading page & waiting for onload` => `Loading page & waiting for idle`. 
- And instead of just listing gatherer classnames we add the handy text of "Collecting data for "...
screenshot: 
----
This was mostly motivated by this exception from the screenshot:
> consistently-interactive:warn Caught exception: TracingProcessor.getMainThreadTopLevelEvents is not a function
I was getting that exception, but was only surfaced in the report. On the CLI i had no idea it was happening.
=> Small status logging improvements

.travis.yml, lighthouse-cli/test/smokehouse/perf/run-tests.sh, lighthouse-cli/test/smokehouse/smokehouse.js
saves perf trace to an S3 bucket (GCS isn't supported by `travis-artifacts`)
=> ci: save perf trace to S3 on failure

lighthouse-core/gather/driver.js, lighthouse-core/test/gather/driver-test.js
Fixes #1815 where we don't wait until the service worker is active. 
Happens mostly on slow connections
not sure if I should mock and create a test for this?
=> Fix service worker gatherer by waiting for active state

.appveyor.yml
appveyor is currently disabled, so this a little moot..
but i flipped it on for this branch and it faired well (aside from TTI flakiness): https://ci.appveyor.com/project/paulirish/lighthouse/build/1010/job/5g77sw2ceq3j9m3p
appveyor setup courtesy of https://yarnpkg.com/en/docs/install-ci#appveyor-tab
=> Move appveyor to use yarn

.travis.yml
the gem install looks to take ~7s
So this isn't a _huge_ win, but it seems worthwhile.
=> Travis: cache gem install (of travis-artifacts)

package.json, yarn.lock
Should fix false positives reported in #1615
I verified that the site mentioned in https://github.com/GoogleChrome/lighthouse/issues/1615#issuecomment-286830244 is no longer failing contrast checks.
=> Bump axe-core

lighthouse-core/audits/byte-efficiency/offscreen-images.js, lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/audits/byte-efficiency/unused-css-rules.js, lighthouse-core/audits/byte-efficiency/uses-optimized-images.js, lighthouse-core/audits/byte-efficiency/uses-request-compression.js, lighthouse-core/audits/byte-efficiency/uses-responsive-images.js, lighthouse-core/audits/splash-screen.js, lighthouse-core/audits/themed-omnibox.js, lighthouse-core/audits/webapp-install-banner.js
small change so that it's more obvious when audit classes are extending subclasses of `Audit` instead of `Audit` directly.
I missed where `requiredArtifacts` were coming from in #2062 even after carefully checking all uses of the passed in `artifacts` and even double checking they were extending `Audit` and not something else. I did not, however, check the definition of `Audit` in those files :)
=> rename references to Audit subclasses for clarity

lighthouse-extension/gulpfile.js
The bug:
Found when rolling latest to devtools and running it.
Small fix. stemmed from the move of instantiateComputedArtifacts() to Runner.
=> Fix computed artifact path during browserify

lighthouse-core/report/v2/renderer/report-renderer.js, lighthouse-core/test/report/v2/renderer/report-renderer-test.js
This was mostly introduced because in the extension, we were generating the report in the background page and not the report. So errors were absorbed and harder to track down.
Now that exceptions during rendering happen right on the page itself (CLI, ext, and DT), we can remove this complexity.
=> Remove renderException

lighthouse-core/gather/computed/speedline.js, lighthouse-core/test/fixtures/traces/threeframes-blank_content_more.json, lighthouse-core/test/gather/computed/speedline-test.js
fixes #2095
See issue for background. I wish we had a sample trace to add a test for this, but I haven't been able to grab one. speedline already supports custom reference points so this should resolve the extreme case noted in #2095
=> fix: always use navStart as speedline timeOrigin

docs/recipes/gulp/gulpfile.js, readme.md
this removes a few excess lines in the readme programmatic example. Maybe arguable, but I think `skipAutolaunch` is a distraction that can be saved for those who want to go deep
=> simplify readme launcher example

readme.md
As a user it isn't immediately clear that debug-chrome needs to be run and remain open when running lighthouse cli to access an area of a site that requires a login.
=> improve instructions for running behind a login

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-core/gather/driver.js
followup to #2106. Solution there only closes the first dialog popup, but we want to always close them, including over a page reload per pass (the test site in #1939 must persist your selection somehow because it now works).
Discovered while adding a smoketest that we handle dismissing modal prompts, so PR also includes that :)
=> handle multiple javascript modal prompts

lighthouse-core/config/config.js, lighthouse-core/test/config/config-test.js
fixes #2088
needs coordination with #2062 and #2104
=> fix: only record a trace if needed by an audit

lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/audits/estimated-input-latency.js, lighthouse-core/audits/first-meaningful-paint.js, lighthouse-core/audits/speed-index-metric.js, lighthouse-core/audits/time-to-interactive.js
R: all
This has been confusing people for a while. Finally got around to address it.  Our messaging makes it seem like users should be hitting these numbers, when in fact, we want them to do better than the targets!
=> Users should strive for < target value. Not hitting it

lighthouse-core/audits/byte-efficiency/uses-request-compression.js, lighthouse-core/report/v2/renderer/category-renderer.js, lighthouse-core/report/v2/renderer/report-renderer.js, lighthouse-core/report/v2/report-styles.css, lighthouse-core/test/report/v2/renderer/category-renderer-test.js
paving the way for #2112, #2044, and splitting up the byte efficiency audits into the sparkline versions and the more aggressive "did you know" versions
basically informative audits will always look like a blue information icon and will not look like pass/fails, the score now simply controls visibility and auto-openness
=> feat: add styling for informative audits

lighthouse-cli/test/fixtures/dobetterweb/domtester.html, lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/audits/dobetterweb/dom-size.js, lighthouse-core/gather/gatherers/dobetterweb/domstats.js, lighthouse-core/test/audits/dobetterweb/dom-size-test.js
R: all
Fixes https://github.com/GoogleChrome/lighthouse/issues/1986.
=> DOMStat Audit: shadow roots don't have .classList

lighthouse-core/closure/closure-type-checking.js
we were getting unhandled rejection exceptions in closure-type-checking:
This fixes it.
=> Closure: handle rejection from stream

lighthouse-extension/app/src/lighthouse-background.js
Fixes #2124
this implements an alternate approach than what was proposed in issue.
now: artifacts are always included on the object and receiver chooses to ditch them or not.
* CLI: ditched in `bin.ts` right after `lighthouse()` completes (already implemented)
* extension: ditched in `runLighthouseInExtension` right after `runLighthouseInExtension` completes
* devtools: will be ditched before results sent into `renderReport`
=> Don't filter artifacts out of LHR

lighthouse-core/report/v2/report-styles.css
R: all
Left-aligns audits/scores to the category title and makes margins and spacing consistent. Also has a fainter border between sections.
Before: 
After:
Also reduces left padding on group audits:
Before: 
After:
=> Report: left-align audits with category title

lighthouse-core/audits/byte-efficiency/total-byte-weight.js
=> Network byte weight audit should not be informative

lighthouse-core/audits/load-fast-enough-for-pwa.js, lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js
Proposed fix for https://github.com/GoogleChrome/lighthouse/issues/2109 which ignores requests that are coming from the cache.
This fixes chromestatus.com:
Fixes https://github.com/GoogleChrome/lighthouse/issues/2109.
=> Ignore cache hits for "fast on 3g" check

lighthouse-core/report/v2/report-styles.css, lighthouse-core/report/v2/report-template.html
two things:
1. We want to reuse some of the constants in the CSS variables outside of the report.. for example: 
So I've split `lh-root` into `lh-root` and `lh-vars`, where lh-vars can be applied to a subtree anywhere you want those variables.
2. The new category gauge was getting crowded on more narrow widths:
before:
after:
=> Report css variable tweaks

lighthouse-core/audits/audit.js, lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js, lighthouse-core/audits/byte-efficiency/offscreen-images.js, lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/audits/byte-efficiency/unused-css-rules.js, lighthouse-core/audits/byte-efficiency/uses-optimized-images.js, lighthouse-core/audits/byte-efficiency/uses-request-compression.js, lighthouse-core/audits/byte-efficiency/uses-responsive-images.js, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js, lighthouse-core/report/v2/renderer/details-renderer.js, lighthouse-core/report/v2/renderer/dom.js, lighthouse-core/report/v2/report-styles.css, lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js, lighthouse-core/test/audits/byte-efficiency/uses-optimized-images-test.js
It's not very pretty but the basics are there.
* adds thumbnail renderer
* adds URL renderer (just displays as text for now)
* adds table renderer (obviously)
* introduces `AuditResult.details.itemHeaders` for the `thead` cells
screenshot, lol:
=> Report v2: Basic table formatter

lighthouse-core/audits/deprecations.js, lighthouse-core/report/v2/renderer/details-renderer.js, lighthouse-core/report/v2/report-styles.css, lighthouse-core/test/report/v2/renderer/details-renderer-test.js
=> Add line/code renderer to deprecations audit

lighthouse-core/report/v2/renderer/report-renderer.js, lighthouse-core/report/v2/templates.html, lighthouse-core/test/report/v2/renderer/report-renderer-test.js
From chats today, its non-obvious what browser the report was generated against. This adds the usera gent to runtime settings so there's not confusion.
=> Report: add user agent to runtime settings

lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js, lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js, lighthouse-core/audits/byte-efficiency/uses-optimized-images.js, lighthouse-core/audits/byte-efficiency/uses-request-compression.js, lighthouse-core/audits/byte-efficiency/uses-responsive-images.js, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js, lighthouse-core/audits/dobetterweb/script-blocking-first-paint.js, lighthouse-core/config/default.js, lighthouse-core/report/v2/renderer/category-renderer.js, lighthouse-core/report/v2/renderer/report-renderer.js, lighthouse-core/report/v2/report-styles.css, lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js, lighthouse-core/test/audits/dobetterweb/link-blocking-first-paint-test.js, lighthouse-core/test/audits/dobetterweb/script-blocking-first-paint-test.js, lighthouse-core/test/results/sample_v2.json
Changes:
* Adds group properties to performance audits
* Moves performance category closer to mocks
* Removes failure states from the byte-efficiency audits now roughly grouped as "performance hints"
~~Feedback needed to remove WIP label:~~
* ~~What to do with unoptimized resources audits that have no results? I actually like not showing them at all, but can see the confusion of where'd it go, maybe an overall passed section at the bottom?~~ 
Grouped in a passed section at bottom
* ~~We cool with the sparkline renderer living in category renderer? (I vote yes for now, but long-term likely splitting out each category to a new class since there's not much else one-off we plan to add for I/O outside performance)~~ 
This is basically regular review feedback at this point, but I'm going to …
=> feat: performance category style++ (sparklines)

lighthouse-cli/package.json, lighthouse-cli/yarn.lock
just ran into #2134 myself on a machine without yarn.
=> lock lighthouse-cli dependency versions to yarn versions

lighthouse-core/audits/audit.js, lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js, lighthouse-core/audits/dobetterweb/geolocation-on-start.js, lighthouse-core/audits/dobetterweb/no-document-write.js, lighthouse-core/audits/dobetterweb/notification-on-start.js, lighthouse-core/test/audits/dobetterweb/external-anchors-use-rel-noopener-test.js, lighthouse-core/test/audits/dobetterweb/geolocation-on-start-test.js, lighthouse-core/test/audits/dobetterweb/no-document-write-test.js, lighthouse-core/test/audits/dobetterweb/notification-on-start-test.js
didn't actually implement a URL list renderer since tables seem to be fine
=> Report: convert rest of URL list audits

lighthouse-core/report/templates/report-templates.js
Prior to this fix users would be confused why their unit tests were
failing. The error was a missing file during a require, which made it seem like
something was messed up with their local clone. Now we can throw a
useful error message.
ref #2092
=> Warn users if they have not yet generated the file.

lighthouse-cli/README.md, lighthouse-cli/package.json, lighthouse-cli/test/cli/index-test.js, lighthouse-cli/yarn.lock
Prior to this fix, the tests *had* to be run from the root lighthouse
dir, this fix makes this test more portable, so for instance you can
run the tests from within the cli folder if you wanted
ref #2092
=> Cli testing

lighthouse-cli/bin.ts, lighthouse-cli/chrome-finder.ts, lighthouse-cli/chrome-launcher.ts, lighthouse-cli/cli-flags.ts, lighthouse-cli/package.json, lighthouse-cli/printer.ts, lighthouse-cli/shim-modules.ts
To merge into the CLI PR (#2173)
* fix double devdependencies
* fix calling of clang-format (a few things)
* when wrapped to < 100 chars a few comments were wrapped which was undesirable: 
* https://github.com/GoogleChrome/lighthouse/compare/cli...cli-formattweak#diff-175d82b7239f837c6210ec1163cf38e3L88
* https://github.com/GoogleChrome/lighthouse/compare/cli...cli-formattweak#diff-a791a2f1d313777e4ac39204107d38dbL70
* https://github.com/GoogleChrome/lighthouse/compare/cli...cli-formattweak#diff-4234080a3c4293c9716cfcef55c909c8L118
=> CLI PR: Rewrap the lines to 100 char. Fix format command

lighthouse-cli/bin.ts, lighthouse-cli/chrome-launcher.ts, lighthouse-cli/manual-chrome-launcher.js, readme.md
- Provide usage examples in CLI `--help`
- Update README with latest output from `--help`
- Also changed `additionalFlags` -> `chromeFlags` so we're consistent. It's confusing that we use `--chrome-flags` in some places (LH CLI) and `additionalFlags` in other places (`chrome-debug`, `ChromeLauncher`). `--chrome-flags` better signals that these flags are Chrome specific and not Lighthouse flags.
=> README: update CLI help with latest. Give common examples

lighthouse-core/audits/load-fast-enough-for-pwa.js, lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js
R: all
This is really handy for debugging...knowing what requests failed the check.
=> Add details to "is fast on 3g" audit

lighthouse-cli/test/smokehouse/pwa-config.js, lighthouse-cli/test/smokehouse/pwa-expectations.js, lighthouse-core/audits/webapp-install-banner.js, lighthouse-core/config/default.js, lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/gather/gatherers/manifest.js, lighthouse-core/gather/gatherers/offline.js, lighthouse-core/gather/gatherers/start-url.js, lighthouse-core/test/audits/webapp-install-banner-test.js, lighthouse-core/test/gather/gatherers/manifest-test.js, lighthouse-core/test/gather/gatherers/start-url-test.js
I couldn't reuse the offline gatherer as it checks the current page from being cached by SW or not for the works-offline audit.
I added a start-url gatherer which lives in a pass other than offline as I need the manifest to work which fails if the current requested page is offline.
=> Add audit to check if start_url is cached by SW

lighthouse-core/config/default.js, lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/gather-runner-test.js
shaves off ~10s on certain sites like theverge.com
=> perf: request block stylesheets and images on redirect pass

lighthouse-core/gather/computed/computed-artifact.js
This was possible before, but much easier with computed artifacts able to call each other as of #2018.
problem:
`computedArtifacts.requestNetworkRecords(devtoolsLog)` calls `NetworkRecords.compute_(devtoolsLog)` internally. Imagine that `compute_` call takes a few promise turns internally.
Meanwhile `computedArtifacts.requestNetworkThroughput(devtoolsLog)` calls
```js
NetworkThroughput.compute_(devtoolsLog, allComputedArtifacts) {
return allComputedArtifacts.requestNetworkRecords(devtoolsLog).then(records => {
// calculate throughput
});
}
```
Computed artifacts internally cache their computed values in order not to repeat expensive calculations. In this situation, however, a call of
```js
Promise.all([
computedArtifacts.requestNetworkRecords(devtoolsLog), …
```
=> prevent computing computed artifacts multiple times due to race condition

lighthouse-cli/test/fixtures/byte-efficiency/tester.html, lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js, lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js, lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js
in the name of Operation Yaquina Bay #2146, fixes #1853 
shaves about ~25 seconds off heavy sites like cnn.com
=> perf(gatherers): skip optimization of cross origin images

lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js, lighthouse-core/gather/computed/critical-request-chains.js, lighthouse-core/test/audits/critical-request-chains-test.js
Fixes https://github.com/GoogleChrome/lighthouse/issues/1550. Hope this is still useful!
=> Remove images from critical request chains.

lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/test/gather/fake-driver.js, lighthouse-core/test/gather/gather-runner-test.js
Instead of once at the beginning, we now clear on a pass-level, but in reality this is the same as it was the first pass that we need it for.
Additionally, don't leave "disable cache" on. Just clear it and start from empty when necessary.
Cache is cleared if we're on a "perf pass" as defined by `recordTrace && useThrottling`.
_In the name of Operation Yaquina Bay #2146_. fixes #2089
------------------
From a perf perspective the wins are not as noticeable except on high-end hardware. That's because disk cache isn't really significantly faster than the network. lol. Usually pass #4 drops ~10% in duration (for google news, it was from 900ms total to 800ms total)
=> perf(gather-runner): Clear cache selectively per-pass

lighthouse-core/gather/computed/critical-request-chains.js
@paulirish Follow up PR for #2085
Figured I would add it since I suggested and had time now
=> Update: Use array of non-critical resource types

lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/audits/load-fast-enough-for-pwa.js, lighthouse-core/gather/computed/critical-request-chains.js, lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js, lighthouse-core/gather/gatherers/dobetterweb/response-compression.js, lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js, lighthouse-core/gather/gatherers/image-usage.js, lighthouse-core/lib/network-recorder.js, lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js, lighthouse-core/test/gather/computed/critical-request-chains-test.js, lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js, lighthouse-core/test/gather/gatherers/dobetterweb/response-compression-test.js, lighthouse-core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js
split from https://github.com/GoogleChrome/lighthouse/pull/2023#discussion_r114909191
=> refactor: makes non-finished network records available

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
make master green again
ref #2201
=> tests: exclude score checking and flaky link preload assertion.

lighthouse-cli/bin.ts, lighthouse-cli/cli-flags.ts
* Extract Flags interface instead of defining inline in the function defs.
* Extract bin flags into a standalone file since this is more about config and less about logic.
ref #2092
depends on 
https://github.com/GoogleChrome/lighthouse/pull/2173
=> CLI: extract bin flag def from index

lighthouse-core/closure/typedefs/AuditResult.js, lighthouse-core/config/config.js, lighthouse-core/test/config/config-test.js, lighthouse-core/test/fixtures/invalid-audits/missing-audit.js, lighthouse-core/test/fixtures/invalid-audits/missing-category.js, lighthouse-core/test/fixtures/invalid-audits/missing-generate-audit-result.js, lighthouse-core/test/fixtures/invalid-audits/missing-help-text.js, lighthouse-core/test/fixtures/invalid-audits/missing-name.js, lighthouse-core/test/fixtures/invalid-audits/missing-required-artifacts.js, lighthouse-core/test/fixtures/invalid-audits/require-error.js, lighthouse-core/test/fixtures/valid-custom-audit.js, lighthouse-core/test/runner-test.js
report v2 requires that there be audit `helpText`. This just asserts that it exists.
This could also go the other way and make it optional in report generation, but no one answered my question about it so here we are :)
=> require audit helpText

lighthouse-cli/chrome-launcher.ts
3 fixes in 3 commits, how about that.
Switch to default argument assignment.
Since we now only support node 6+ we can drop this ugly fallback.
--
Remove lossey type cast from chrome launcher.
--
Add type safety to defaults.  …
Since we now have generics in typescript, we can leverage them in our
default function to have type safety.
ref #2092
=> Launcher type improvements.

lighthouse-extension/app/manifest_canary.json, package.json
* **chrome extension canary** `2.0.0-alpha.4 2017-05-09` published: 
* https://chrome.google.com/webstore/detail/gcladjiblfghhokpimgadfdmblkocoae
* **npm prerelease** `lighthouse@2.0.0-alpha.4` shipped: 
* `npm install -g lighthouse@canary`
=> bump to 2.0.0-alpha.4

lighthouse-core/audits/time-to-interactive.js, lighthouse-core/audits/webapp-install-banner.js, lighthouse-core/test/audits/webapp-install-banner-test.js
Matches what the "Configure for a splash screen audit" does. It was confusing that the failure help text was saying the "site registers a sw", when in fact, it did not.
Also fixes https://github.com/GoogleChrome/lighthouse/issues/2189.
=> Install banner audit: failures should say what the user didnt do

lighthouse-core/report/v2/renderer/details-renderer.js
yesterday, I rolled to devtools with some LH changes that aren't yet in master here (they're in #2206)
as a result, i broke `compile-devtools`. :)
https://travis-ci.org/GoogleChrome/lighthouse/jobs/231226842#L661
This adds a stub that restores compilation while 2206 gets sorted.
=> Report: add stub for NodeDetails renderer

lighthouse-core/gather/computed/speedline.js, package.json, yarn.lock
in the name of OYB, shaves off ~4s from PSI computation (went from 5s to 1s 💣 💥 )
bonus perk: no test changes required all PSI values the same
closes #2227
=> perf: enable speedline fastMode

lighthouse-core/gather/computed/critical-request-chains.js, lighthouse-core/scripts/run-mocha.sh, lighthouse-core/test/gather/computed/critical-request-chains-test.js
Fixes #2219 Sorry it took so long!
Hope this helps :grimacing:
=> Fix: Catch all images as non-critical

lighthouse-cli/yarn.lock, lighthouse-core/audits/byte-efficiency/offscreen-images.js, lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/audits/byte-efficiency/unused-css-rules.js, lighthouse-core/audits/byte-efficiency/uses-optimized-images.js, lighthouse-core/audits/byte-efficiency/uses-request-compression.js, lighthouse-core/audits/byte-efficiency/uses-responsive-images.js, lighthouse-core/audits/critical-request-chains.js, lighthouse-core/audits/deprecations.js, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js, lighthouse-core/audits/dobetterweb/no-old-flexbox.js, lighthouse-core/audits/is-on-https.js, lighthouse-core/audits/time-to-firstbyte.js, lighthouse-core/lib/url-shim.js, lighthouse-core/report/handlebar-helpers.js, lighthouse-core/report/v2/renderer/category-renderer.js, lighthouse-core/report/v2/renderer/crc-details-renderer.js, lighthouse-core/report/v2/renderer/details-renderer.js, lighthouse-core/report/v2/renderer/util.js, lighthouse-core/report/v2/report-generator.js, lighthouse-core/report/v2/templates.html, lighthouse-core/scripts/compile-against-devtools.sh, lighthouse-core/test/audits/critical-request-chains-test.js, lighthouse-core/test/lib/url-shim-test.js, lighthouse-core/test/report/partials/critical-request-chains-test.js, lighthouse-core/test/report/v2/renderer/crc-details-renderer-test.js
This one was a real pain :) Handlebars -> real code. Ugh. FWIW, I did not attempt rewrite Paul's tree code, so please keep bikeshedding to a minimum. The helpers come from handelbars-helpers, but I've renamed them slightly.
Other things this PR does:
- Moves the url-shim's 'getDisplayName` into `Util.getDisplayName` so we can use it in report renderers.
- Pipes `_templateContext` into the details-renderer so we can use templates in that file.
@brendankenny is going to finish off the closure errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlechrome/lighthouse/2218)
=> Adds Critical Request Chain details renderer

lighthouse-core/config/plots.json, lighthouse-core/index.js, lighthouse-core/report/v2/renderer/report-renderer.js, lighthouse-core/test/index-test.js, plots/analyze.js, plots/constants.js
happy to bikeshed on the name and where it should be taken, but basically it would be nice to be able to track how long a lighthouse run takes. I was going to do it in plots/, but @wwwillchen pointed out that it's actually a generally useful thing to have in the LHR.
We could put this inside `runner`, but it's actually kind of nice to track config and connection construction too. This does ignore work done in `bin.ts`, however.
=> add lighthouse calculation time to json results

lighthouse-core/config/default.js, lighthouse-core/gather/driver.js, lighthouse-core/gather/gather-runner.js, lighthouse-core/lib/network-recorder.js, lighthouse-core/test/gather/driver-test.js
in the name of OYB, shaves off ~9 seconds from all runs with the default passes
renames pauseAfterLoad to the more appropriate networkQuietThreshold, previously the flag was for speeding up the tests and was not documented in the CLI
=> perf: make network quiet threshold configurable per pass

chrome-launcher/chrome-finder.ts, chrome-launcher/chrome-launcher.ts, chrome-launcher/flags.ts, chrome-launcher/manual-chrome-launcher.js, chrome-launcher/package.json, chrome-launcher/random-port.ts, chrome-launcher/test/chrome-launcher-test.js, chrome-launcher/test/random-port-test.js, chrome-launcher/utils.ts, chrome-launcher/yarn.lock, lighthouse-cli/bin.ts, lighthouse-cli/cli-flags.ts, package.json, plots/measure.js, readme.md
📔  note:
> This CL consists of individual commits that build on each other, each commit is an atomic unit of work to make reviewing easier, as well as the commit history understandable.
* Clean up use of any typing for chrome-finder by being smart with types. 🤔  🍎 
* Limit class interface for chrome launcher instance with private. 👮 
* Extract flags to a standalone module since it is more config than code. 🐴 
* Add missing type info for mkdirp. 🔍 
* Extract util functions to a standalone component since they are not coupled to the implementation of chrome launcher. :man_farmer: 
* make use of await / async. 😴 
* update plots to consume the new api. 📈 
* Add a new ability for the launcher to handle SIGINT 🔪 .
* launcher will now if a non-zero port is passed tried to connect to an existing …
=> ChromeLauncher v1.0

lighthouse-extension/app/manifest_canary.json, package.json
shipping these to npm & cws right now.
=> release: Tagging 2.0.0-alpha.5

lighthouse-core/audits/consistently-interactive.js, lighthouse-core/gather/computed/first-interactive.js, lighthouse-core/test/audits/consistently-interactive-test.js, lighthouse-core/test/gather/computed/first-interactive-test.js
to make these more understandable:
=> Enhance error wording around busy traces.

docs/recipes/custom-audit/custom-config.js, docs/recipes/custom-audit/package.json, docs/recipes/custom-audit/readme.md, docs/recipes/custom-audit/searchable-audit.js, docs/recipes/custom-audit/searchable-gatherer.js
adds a custom gatherer/audit to our recipes. Happy to bikeshed on all of this :)
No rush on landing this, but we'll be using a version of this at I/O, so get in comments if you want to influence what we show there :)
=> add custom audit recipe

lighthouse-extension/app/manifest_canary.json, package.json
* **chrome extension canary** `2.0.0-alpha.6 2017-05-15` published:
* https://chrome.google.com/webstore/detail/gcladjiblfghhokpimgadfdmblkocoae
* can be run alongside the 1.x extension.
* **npm prerelease** `lghthouse@2.0.0-alpha.6`
* `npm install -g lighthouse@canary`
* caution: this will replaces your globally installed lighthouse
cut from master @ 72b06e422869c62d38815330751085acb5160cd9
=> Ship new canary

lighthouse-core/audits/audit.js, lighthouse-core/audits/manual/manual-audit.js, lighthouse-core/audits/manual/pwa-cross-browser.js, lighthouse-core/audits/manual/pwa-each-page-has-url.js, lighthouse-core/audits/manual/pwa-page-transitions.js, lighthouse-core/config/default.js, lighthouse-core/report/v2/renderer/category-renderer.js, lighthouse-core/report/v2/renderer/report-renderer.js, lighthouse-core/report/v2/report-styles.css, lighthouse-core/runner.js, lighthouse-core/test/audits/manual-audit-test.js, lighthouse-core/test/report/v2/renderer/category-renderer-test.js, lighthouse-core/test/report/v2/renderer/report-renderer-test.js, lighthouse-core/test/results/sample_v2.json
Fixes https://github.com/GoogleChrome/lighthouse/issues/2059
This PR adds the notion of a "manual" audit, an audit which does not require any artifacts but renders in the report like a normal audit.  We're using @patrickhulce's awesome report grouping to group the manual audits together (below passing audits).
I chose the grey "-" instead of the blue information "i" because we need some way to distinguish these audits from normal (automated) audits run by LH. But LMK what ya'll think.
Also modernizes samples_v2.json
=> PWA Audits: add placeholders for rest of baseline checks.

lighthouse-core/audits/load-fast-enough-for-pwa.js, lighthouse-core/lib/emulation.js
Based on the work in https://github.com/GoogleChrome/lighthouse/pull/2183 which I'll land as a follow-up.
=> Update network throttling to simulate more realistic network conditions

lighthouse-cli/test/smokehouse/perf/expectations.js, lighthouse-core/config/default.js
This hides TTI from being displayed but still leaves it in the audits so it will appear in the trace if `--save-assets` and you run with the default or with `onlyAudits: ['time-to-interactive']`
=> fix: remove TTI (alpha) from performance category

.eslintrc.js, plots/ab-screenshot/screenshot-viewer.js
surprised we weren't enforcing this, but turns out it's a [TODO in `eslint-config-google`](https://github.com/google/eslint-config-google/blob/d13ead768dd81492640eeffe85c35e3eb32c5c21/index.js#L81-L82)
change is simple and supports our current usage pattern
=> update eslint `curly` rule to google js style

lighthouse-core/audits/is-on-https.js
since the change to how https is handled to support Android (#1918), chrome-extension URLs get flagged as insecure requests this considers chrome and chrome-extension schemes secure
=> fix(is-https): consider chrome:// URLs safe

lighthouse-extension/app/manifest_canary.json, package.json
* **chrome extension canary** `2.0.0-alpha.7 2017-05-16` published:
* https://chrome.google.com/webstore/detail/gcladjiblfghhokpimgadfdmblkocoae
* can be run alongside the 1.x extension.
* **npm prerelease** `lighthouse@2.0.0-alpha.7`
* `npm install -g lighthouse@canary`
* caution: this will replaces your globally installed lighthouse
cut from master @ 603c92031eaae868293d5a4300ca61703d4cc67f
=> chore: bump canary to 2.0.0-alpha.7

lighthouse-core/report/v2/renderer/category-renderer.js, lighthouse-core/report/v2/renderer/dom.js, lighthouse-core/test/report/v2/renderer/category-renderer-test.js, lighthouse-core/test/report/v2/renderer/dom-test.js
This converts markdown ticks in audit titles.
Esp. makes the a11y audits look better.
=> Convert code snippets in audit titles

lighthouse-core/audits/load-fast-enough-for-pwa.js, lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js
http://veerle.duoh.com/ used to fail the check because google analytics latency was 0 for being redirected internally to https (status code 307)
=> polish: do not fail loadfast4pwa for internal redirects

lighthouse-core/report/v2/report-styles.css, lighthouse-core/report/v2/templates.html
fixes https://bugs.chromium.org/p/chromium/issues/detail?id=723362
=> polish: sizing tweaks for extremely narrow viewports

readme.md
Adding in a link to lighthouse-cron, related project.
=> Adding lighthouse-cron to Related Projects in readme

.travis.yml, package.json
`yarn install-all` currently doesn't call `yarn install` in the base directory, so when `yarn build-all` is called, it immediately errors on `gulp: command not found`
=> really yarn install-all

.eslintrc.js
Not sure if it was left out for a reason or just missed. Google's default preset has this exact quotes setting so I think it could just be removed.
=> Fix: Allow template literals in linting

lighthouse-core/audits/is-on-https.js, lighthouse-core/test/audits/is-on-https-test.js
=> fix: do not flag blob urls as insecure

lighthouse-cli/bin.ts
Tiny nit. Since `handleSIGINT` is true by default - https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/chrome-launcher.ts#L53, so here it's not needed.
=> Eliminate number of launch arguments

lighthouse-core/config/default.js, lighthouse-core/lib/traces/tracing-processor.js, lighthouse-core/test/lib/traces/tracing-processor-test.js
fixes the `atob is not defined` error on https://plustimer.firebaseapp.com/ that results from the traceviewer trying to parse base64 encoded args embeded in a trace event used by Zone 
actually surprised we haven't run into this yet, it only happens when calling from node
also includes a drive by fix to increase the wait after load to 5250 since I've seen a couple traces where the trace ended 4999 or 4990 ms after quiet when the site was `onLoad` bound
=> polish: handle traces with base64 encoded args

lighthouse-extension/app/src/popup.js
thanks @brendankenny 
Fixes #2186
=> Add error to chrome extension when url is using the chrome protocol

lighthouse-extension/app/src/popup.js
Reusing the refactor [that's on the devtools side](https://codereview.chromium.org/2888263002/diff/50001/third_party/WebKit/Source/devtools/front_end/audits2/Audits2Panel.js).
This fixes the incorrect triple-tick we currently have (with no newlines inbetween).
It also simplifies this bit.
=> extension: Fix formatting of bug reports

lighthouse-core/gather/driver.js
~~@brendankenny has observed flakiness of TTCI and TTFI on simpler sites since we've switched to waiting on 2-quiet, my hypothesis is that under the new harsher throttling, we'll see this even more frequently because 2-idle is true as soon as we request the initial page (which if it takes too long 2-quiet could fire before we even load any other content!). Worst case sites already run up to the timeout, so this shouldn't impact them as much. Simpler sites see longer times, but that's the goal since we're ending the trace too early in some cases.~~
UPDATE: waits for DCL before listening for network idle per @deepanjanroy 's suggestion, this seems to mostly fix the issue for sites like vevo and NASA who were reaching "network idle" while the primary script request was in-flight
=> polish: listen for network idle after DCL

docs/readme.md, docs/recipes/custom-audit/readme.md, readme.md
- Updates screenshots
- moves main readme examples to docs/readme.md
- adds a "turn on logging" example to the node snippet
- Beefs up the custom audit recipe and removes dupe content from the readme
- Adds info on DevTools integration
- Adds recipe/doc links to main readme
=> Docs: update readme, add docs/readme, modernize a bit

lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
related #2217 
at some point recently the JPEG library used by chrome has changed so that the quality or file size is now much lower for the same quality setting which is causing smoke tests to fail if they don't use the cached download of Chrome (see https://travis-ci.org/GoogleChrome/lighthouse/jobs/235694158)
this bumps it to give roughly the same output as it does under Chrome stable but we should investigate this more and try to bisect for the cause or track it better
=> fix: bump jpeg quality

readme.md
Adds a "Lighthouse Integrations" section to `README.md` that mentions Calibre and WPT.
@pmeenan, I pinched this text from the WPT about page, but thought you might have some edits you'd like to see in this PR?
=> ✨ Add Calibre and WPT to Readme

lighthouse-core/gather/gather-runner.js
It is possible that we were resolving the gather chain before we had
disconnected. When manually launching and killing chrome this can race
and result in an error to the user.
This fixes that problem. \o/.
Fixes #2337
---
Test plan:
Run launcher with:
```ts
const lighthouse = require('lighthouse');
import {launch} from './chrome-launcher';
async function runLighthouse(url: string) {
const opts = {
chromeFlags: ['--headless'],
};
const chrome = await launch(opts);
const flags = {
output: 'json',
port: chrome.port,
};
const results = await lighthouse(url, flags);
process.on('uncaughtException', (e: any) => {
console.log(e);
});
await chrome.kill();
return results;
}
runLighthouse('https://example.com');
```
Without this patch, and then run it with the patch. Observe it now working.
=> 😈 Fix disconnect promise race.

lighthouse-core/gather/connections/connection.js, lighthouse-core/gather/driver.js, lighthouse-core/test/gather/driver-test.js
=> fix: always ensure tracing is off before starting

lighthouse-core/audits/load-fast-enough-for-pwa.js, lighthouse-core/audits/works-offline.js, lighthouse-core/report/v2/renderer/category-renderer.js, lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js, lighthouse-core/test/audits/works-offline-test.js, lighthouse-core/test/report/v2/renderer/category-renderer-test.js
* doesn't hide passed audits with a debug string in "passed audits" section
* only shows debug string on `works-offline` if the audit failed
* flips loadfast4pwa to pass (but still show debug string) when latencies seem unrealistic
* drive by text fix for loadfast4pwa TTI -> TTFI
=> polish: show audits with debug string, don't fail loadfast4pwa on network latencies, works-offline change

lighthouse-core/report/v2/renderer/report-renderer.js
Fixes #2320 
---
`formatNumber` returns a string value from `Number.toLocaleString`, and `math.round` can't round the number.
`math.round` receives an integer instead of a string, which makes the conversion complete, not returning `NaN`. Note that we first do `math.round` and then use `formatNumber` instead of the opposite, as prior.
--- 
Didn't change test for `Utils.formatNumber`, as I didn't touch it. Furthermore, I'd prefer a common conversion point for [this](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/report/v2/renderer/category-renderer.js#L105) in relation to the line I've changed, as we're basically doing the same thing. This ensures that scores are persistent and co-reliant.
---
=> swap math.round with util.formatNumber

lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js, lighthouse-cli/test/smokehouse/perf/expectations.js, lighthouse-cli/test/smokehouse/smokehouse.js
=> test(smokehouse): add numeric comparisons

lighthouse-cli/printer.ts, lighthouse-cli/test/cli/printer-test.js
closes #2344 and opens the door to fully remove the old report code, users who request --output html will receive the current report instead (including WPT)
=> fix: deprecate old HTML report

.appveyor.yml
We were seeing this error in the appveyor logs:
It seemed to point at this yarn bug: https://github.com/yarnpkg/yarn/issues/2591
Appveyor has an older build of Yarn on the bots by default (0.21.3), so i've installed a fresh version of yarn (>= 0.24.5) in the build script. It sorts it out.
cc @XhmikosR 
-------
As a driveby: enabled `fast_finish` which means "immediately finish build once one of the jobs fails." We wanted this for travis too, but they don't have it. odd.
------
_Update_
Two more drivebys:
1. Our OSS free plan only allows 1 concurrent job at a time. Since appveyor VMs are so slow, i dont think its worth it to always wait for 2 back-to-back builds with node 6 and node 7. So i've ditched the node7 build.
2. I enabled the ["rolling builds" …
=> Appveyor fixes: fresh yarn, only node6 build

lighthouse-core/report/v2/report-styles.css
=> Fix icons on firefox by decoding svg imgs

lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/report/v2/renderer/details-renderer.js
Currently the `total-byte-weight` audit only reports `getURLDisplayName` for URLs.
This can make it challenging to understand what resource the audit is talking about, as sites we work with include 3rd party scripts with mystery names.
Without the complete URL, it is impossible to create detailed CI tests that fail if certain resources are bigger than a threshold. In our case, we often do not control the size of all assets on the page, so we don't want to fail on the overall threshold... just thing we have control on.
This change displays the full URL.
| Before | After |
|---|---|
| ![image](https://cloud.githubusercontent.com/assets/28967/26259780/70eb320e-3c7f-11e7-8634-8e466988a467.png) | ![image](https://cloud.githubusercontent.com/assets/28967/26259887/e954d524-3c7f-11e7-852a-eaebabde …
=> Total byte audit reports full URL

chrome-launcher/compiled-check.js
When I build fail, I saw below message. I think that below comment is wrong.
```
yarn install; yarn build;
```
=> fixed incorrect comments

lighthouse-core/lib/traces/tracing-processor.js
@patrickhulce i figured i'd save you the annoyance. :)
=> rmtraceviewer branch: reduce -> for..of

.travis.yml
Just released: https://nodejs.org/en/blog/release/v8.0.0/
=> travis: include node 8.0.0

lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
@patrickhulce 
No longer the case for jpeg.
=> Update optimized-images overview jsdoc

lighthouse-core/audits/byte-efficiency/offscreen-images.js, lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/audits/byte-efficiency/uses-optimized-images.js, lighthouse-core/audits/byte-efficiency/uses-request-compression.js, lighthouse-core/audits/byte-efficiency/uses-responsive-images.js, lighthouse-core/audits/byte-efficiency/uses-webp-images.js, lighthouse-core/audits/deprecations.js, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js, lighthouse-core/audits/is-on-https.js, lighthouse-core/lib/url-shim.js, lighthouse-core/test/audits/byte-efficiency/uses-optimized-images-test.js, lighthouse-core/test/audits/is-on-https-test.js, lighthouse-core/test/lib/url-shim-test.js
extends the goodness of #2312 to all audits formatting URLs
also adds an `elideDataURI` method to url shim to prevent enormous images from filling the LHR multiple times
=> feat: tooltips for all formatted URLs

docs/readme.md
=> Updated readme to add port number when testing a site with authentication

lighthouse-core/audits/violation-audit.js
since switching to using violations, entries would appear in the table that had no actionable information, this filters those out
=> fix: hide violations with no URL information

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
A proactive commit to sort out our tests.
I'm improving the fix in #2402 and will be landing that soon
fixes #2141 
ref #2423
=> Disable the dismissJavaScriptDialogs smoketest. 

lighthouse-core/gather/connections/connection.js, lighthouse-core/lib/log.js
fixes #2321 
also observed errors in devtools when we get command callbacks for commands LH didn't send
=> fix(connection): gracefully handle missing method

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js, lighthouse-core/config/default.js, lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js, lighthouse-core/test/audits/dobetterweb/password-inputs-can-be-pasted-into-test.js, lighthouse-core/test/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste-test.js
Adresses https://github.com/GoogleChrome/lighthouse/issues/2345
=> add audit to check if paste is allowed in password inputs

lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/test/fixtures/dbw_tester-perf-results.json, lighthouse-core/test/results/sample.json, lighthouse-core/test/results/sample_v2.json
Not everyone uses dollars as their currency.
=> Fix US-centric wording

chrome-launcher/chrome-launcher.ts, chrome-launcher/package.json, chrome-launcher/test/check-formatting.sh, chrome-launcher/test/chrome-launcher-test.ts, chrome-launcher/test/random-port-test.ts, chrome-launcher/yarn.lock, lighthouse-core/scripts/run-mocha.sh
* rename TMP_DIR to a more accurate name. Since this is a private
internal value, this is non-breaking.
Fixes #2291
Ref #2092
=> Enable passing of a custom userDataDir to launcher

lighthouse-cli/test/smokehouse/pwa-config.js, lighthouse-cli/test/smokehouse/pwa-expectations.js, lighthouse-core/gather/computed/manifest-values.js
updates the PWA smokehouse run so that it runs all the latest PWA checks (and will stay current with them going forward) and updates expectations to match
=> update smokehouse PWA expectations

lighthouse-core/audits/load-fast-enough-for-pwa.js
tiny change. From
`First Interactive was found at 808.352, however, the network request latencies were not sufficiently realistic, so the performance measurements cannot be trusted.`
to
`First Interactive was found at 808.352ms, however, the network request latencies were not sufficiently realistic, so the performance measurements cannot be trusted.`
=> add units to LoadFastEnough debug string

lighthouse-core/config/default.js
`default.js` was [once](https://github.com/GoogleChrome/lighthouse/pull/1911) `default.json`, and still has the double quotes to prove it. This updates to remove those, add a license header, enable eslint, and sprinkle in some trailing commas to hopefully help with `git blame` in the future while this commit is ruining it in the present :)
Disabled `max-len` for this file because of the description strings and this is a config file, not a normal script file, but happy to turn back on if others want it.
part of #2276
=> de-jsonify default.js

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js, lighthouse-core/gather/computed/network-throughput.js, lighthouse-core/report/v2/renderer/category-renderer.js, lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js, lighthouse-core/test/gather/computed/network-throughput-test.js, lighthouse-core/test/report/v2/renderer/category-renderer-test.js
Improves the debug information when network throughput can't be computed and defaults the result to Infinity instead of 0 which makes more sense since the only use of networkThroughput is to be the divisor (the computed artifact is also used by total byte weight which makes sense to say 0 ms time and still report the byte savings)
This was affecting chrome URLs which don't have any timing information, results from before and after for `chrome://version` below (the optimized images error is for tainting canvas which apparently all chrome images do)
**Before**
**After**
=> fix: better debug message for missing network times

lighthouse-core/audits/consistently-interactive.js, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js, lighthouse-core/audits/first-meaningful-paint.js, lighthouse-core/gather/computed/first-interactive.js, lighthouse-core/gather/computed/speedline.js, lighthouse-core/gather/computed/trace-of-tab.js, lighthouse-core/test/audits/consistently-interactive-test.js, lighthouse-core/test/audits/dobetterweb/link-blocking-first-paint-test.js, lighthouse-core/test/gather/computed/first-interactive-test.js, lighthouse-core/test/gather/computed/trace-of-tab-test.js
=> refactor(trace-of-tab): return timestamps in microseconds

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js, lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/audits/critical-request-chains.js, lighthouse-core/closure/typedefs/ComputedArtifacts.js, lighthouse-core/gather/computed/critical-request-chains.js, lighthouse-core/gather/computed/network-throughput.js, lighthouse-core/gather/computed/pushed-requests.js, lighthouse-core/test/audits/critical-request-chains-test.js, lighthouse-core/test/fixtures/wikipedia-redirect.critical-request-chains.json, lighthouse-core/test/gather/computed/critical-request-chains-test.js, lighthouse-core/test/gather/computed/network-throughput-test.js, lighthouse-core/test/gather/computed/pushed-requests-test.js, lighthouse-core/test/runner-test.js
followup to #2062 and #2133 (specifically https://github.com/GoogleChrome/lighthouse/pull/2062#discussion_r113811358)
really just a convenience thing. Since computed artifacts can request other computed artifacts, callers of e.g. criticalRequestChains shouldn't have to construct networkRecords, CRC can just do it itself.
=> move computed artifacts dependent on networkRecords to devtoolsLog

CONTRIBUTING.md, chrome-launcher/.npmignore, chrome-launcher/README.md, chrome-launcher/chrome-launcher.ts, chrome-launcher/package.json, chrome-launcher/yarn.lock
For now depend on lighthouse to use the logger. Eventually I vote that we pull out logger into a standalone module to consume to in both lighthouse and in launcher. 
Fixes #2251 
Fixes #2469.
Ref #2092
=> Prep export of launcher as a standalone module

lighthouse-core/audits/accessibility/link-name.js
thanks @tinfelise for the spot!
fixes #2489
=> fix spelling of "discernible" in link-name audit

docs/architecture.md, lighthouse-core/gather/computed/trace-of-tab.js
=> docs: add trace interpretation guide

chrome-launcher/index.ts, chrome-launcher/package.json
Thx @devrelm for the suggestion
fixes #2497
ref #1773
=> improve typescript declaration imports

lighthouse-core/config/config.js, lighthouse-core/test/config/config-test.js
the path to enabling coverage by default isn't looking good, so we're gonna need a mechanism for skipping audits but including a version with them in the config :)
happy to bikeshed on naming
=> feat(config): add audit blacklist support

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/audits/is-on-https.js, lighthouse-core/test/audits/is-on-https-test.js
Fixes #2523.
Adds an additional check for the protocol/scheme. FWIW, `record.scheme` isn't populated for `blob:` urls but `.protocol` is!
=> is-on-https: check record.protocol for blob urls

lighthouse-core/scripts/generate-combined-coverage.sh, package.json, yarn.lock
Example report: https://codecov.io/gh/GoogleChrome/lighthouse/tree/8851e9313eac1c5b1f6d4369da81b2598da7100f
Still reporting to coveralls for the moment, too.
FWIW, The typescript tests in chrome-launcher arent included because of the different (`ts-node`) mocha call. cc @samccone
=> Report coverage to codecov.io

lighthouse-core/report/styles/report.css, lighthouse-extension/app/popup.html, lighthouse-extension/app/styles/lighthouse.css
It's been gone from the report for a while.
But it's remained in the popup:
This nukes it.
=> remove beta badge from extension

lighthouse-extension/app/src/popup.js
should throw a message that don't support non auditable pages like view-source, ...
Fixes #2525
Not sure it's the best solution though
=> Throw better error message when url is not auditable

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
fixes https://github.com/GoogleChrome/lighthouse/pull/2538#discussion_r123076291
JS error prevented the image from being added to the dom, so the smoketest wasn't testing anything. The expectations remain the same b/c we're ignoring `blob` urls.
=> Fix dbw tester error

lighthouse-core/gather/gatherers/dobetterweb/domstats.js
fixes #2532
the url was https://www.davidemaggio.it/ the parentNode.host of the `html` tag is the `body` tag and vice versa
=> fix(domstats): prevent infinite loop

lighthouse-cli/performance-experiment/server.js, lighthouse-cli/test/fixtures/static-server.js
1. we only allow localhost to connect to our static-server
2. extra protection of not allowing requests beyond the LH folder
=> harden security of static-server

lighthouse-core/gather/computed/speedline.js, lighthouse-core/gather/computed/trace-of-tab.js, lighthouse-core/test/gather/computed/speedline-test.js, lighthouse-core/test/gather/computed/trace-of-tab-test.js
fixes #2333. Ensures that nested trace events stay nested.
I'm loath to use the Devtools array extensions, but the easiest way to bring in a stable sort is to use the one we already pull in with `devtools-frontend`, and since it [writes it directly onto the Array prototype](https://github.com/ChromeDevTools/devtools-frontend/blob/c3d0c13c1ad36c71f2a9218d42ba3de760e5f9a3/front_end/platform/utilities.js#L549), the easiest way to use it is to just call it on the `traceEvents` array. Better than bringing in a new module, at least :S
For testing, I haven't yet been able to produce a trace that when sorted with the native v8 `[].sort` will put events from the same process and thread out of order. In #2333 @wwwillchen notes it may also rely on the poor resolution of the android timer, so I'll …
=> use a stable sort for trace events

lighthouse-core/scripts/log-travis-durations.rb
Here's the last 40 days of travis build durations:
Pretty cool data. Halfway down the X axis you'll see the variance kick off. AFAICT, this seems to be travis's fault. It starts right when the "fix appveyor" commits land on master. (around the #7972's of build numbers)  But these commits ONLY touch appveyor.yml, so they couldn't matter less to Travis. 
EDIT: i've amended the script to tag where the build is from so we can see just master branch builds too:
spreadsheet: https://docs.google.com/spreadsheets/d/197M4SRTdDbbpg4uRDCr-tI5l48L2qsAGkxIcIncKKew/edit#gid=0
cc @wardpeet
=> Add script to capture travis build durations

chrome-launcher/package.json, chrome-launcher/yarn.lock
Fixes #2568 
There's a bunch of dependencies removed from `yarn.lock` that I'm not so sure of. They may be indicative of more missing dependencies, but all of the package scripts run fine, so they may have just been extraneous packages that had yet to have been removed from the yarn.lock file.
=> [chrome-launcher]: Add missing mkdir and rimraf dependencies

lighthouse-core/report/v2/templates.html
The "Save as Gist" option was accidentally left visible in the regular report, even though it only works in viewer.
Followup to #2521
=> make save-as-gist css more specific

lighthouse-core/audits/themed-omnibox.js, lighthouse-core/test/results/sample.json, lighthouse-core/test/results/sample_v2.json
Updated description
- Lighthouse has no idea what your brand colors are - it's really just checking to see whether the address bar has been themed in any way.
Corrected reference to manifest theme color ("theme_color" vs. "theme-color")
Changes for clarity:
- I think "apply the same theme site-wide" could be misinterpreted as altering the web site appearance (vs. the browser) in some way. It's also slightly ambiguous as to whether "applying a theme" is the same thing as "upgrading the address bar", or whether it represents a larger subset of functionalities.
=> Theme Color wording fixes

lighthouse-core/report/v2/renderer/report-ui-features.js, lighthouse-viewer/app/styles/viewer.css
sorry, two last viewer flubs
1) This was an existing issue with the old viewer too: binding the `message` handler to `this` meant that a newly created function was being passed to `addEventListener`, so later attempts to remove the handler via a reference to the original, non-bound function was having no effect. Noticed when refreshing the viewer kept loading the same report as long as the triggering html report was still open in a tab.
2) save-as-gist is hidden by the CSS in the `<template>`s, which is after viewer.css in the page, so they win. This !importants it. Why does anyone let me write CSS
=> fixes viewer CSS specificity and event listener removal

docs/configuration.md
=> docs(config): add config documentation

chrome-launcher/README.md, chrome-launcher/chrome-launcher.ts, lighthouse-cli/bin.ts
To improve debugging of #2556, #2544, #2462 , this PR will log out the contents of Chrome's stderr.
It was only through this technique that I found that Chrome had a fatal crash when I was trying to run it in a docker container:
> `[0627/002609.343419:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.`
We'll see if this will uncover the travis flake (which I presume to be unrelated to `--no-sandbox`)
---------
Also in this PR: we add the `logLevel` option to chrome-launcher.
=> Log Chrome's stderr in case of failure

.travis.yml
Temporarily addresses https://github.com/GoogleChrome/lighthouse/issues/2600
I'll re-enable it once I stabilize the test
=> plots: disable flaky smoke test

lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js, lighthouse-core/audits/critical-request-chains.js, lighthouse-core/audits/deprecations.js, lighthouse-core/audits/dobetterweb/dom-size.js, lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js, lighthouse-core/audits/dobetterweb/uses-http2.js, lighthouse-core/audits/estimated-input-latency.js, lighthouse-core/audits/first-meaningful-paint.js, lighthouse-core/audits/is-on-https.js, lighthouse-core/audits/load-fast-enough-for-pwa.js, lighthouse-core/audits/speed-index-metric.js, lighthouse-core/audits/time-to-firstbyte.js, lighthouse-core/audits/user-timings.js, lighthouse-core/report/v2/renderer/category-renderer.js, lighthouse-core/report/v2/renderer/crc-details-renderer.js, lighthouse-core/report/v2/renderer/details-renderer.js, lighthouse-core/report/v2/renderer/util.js, lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js, lighthouse-core/test/audits/dobetterweb/link-blocking-first-paint-test.js, lighthouse-core/test/audits/dobetterweb/script-blocking-first-paint-test.js, lighthouse-core/test/audits/user-timing-test.js
fixes #1723
Hi, I have come across this beginner issue, did some debugging how it can be fixed and I noticed that there are already some changes introduced with #2295. I followed the pattern and used this utility helper across audits which I think required use of it. Waiting for your feedback, thanks! 😅
=> 1723 Adopt to locale string for all our number output

lighthouse-core/report/v2/renderer/crc-details-renderer.js, lighthouse-core/test/report/v2/renderer/crc-details-renderer-test.js
Children chains were using the overall `longestChain.transferSize` instead of their own size. 
Also updated the renderer test to actually be useful.
Fixes #2597
=> CRC audit: child chain renders using its own transfersize. Fixes #2597

lighthouse-core/gather/driver.js, lighthouse-core/lib/asset-saver.js, lighthouse-core/lib/traces/trace-parser.js, lighthouse-core/lib/web-inspector.js, lighthouse-core/test/lib/asset-saver-test.js, lighthouse-core/test/lib/traces/trace-parser-test.js
🚰 🚰 🚰 
----
fixes #1798, #1685 
combo effort with bckenz.
@brendankenny did the streaming writer a bit ago. and we got the parser up and running together. 
good stuff.
=> Add streaming JSON parser and writer

lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html, lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js, lighthouse-core/gather/driver.js, lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners.js, lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener.js, lighthouse-core/gather/gatherers/dobetterweb/domstats.js, lighthouse-core/gather/gatherers/image-usage.js, lighthouse-core/lib/dom-helpers.js
Fixes https://github.com/GoogleChrome/lighthouse/issues/1913
Also enables shadow dom on the rel="noopener" audit 👊
=> Remove /deep/ usage

lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners.js
When speeding up travis I found a bug when I try to load only a subset of gatherers.
=> Add DOM.enable to the event-listeners gatherers

lighthouse-extension/package.json, lighthouse-extension/yarn.lock
When extension had it's own lh-logger, it didn't share state with core's logger. With this changes,
the extension require's in core's logger.
Fixes bug introduced in #2528 
See https://github.com/GoogleChrome/lighthouse/pull/2528/files#diff-1d5287b2468c222ed5562ae5015485db
=> fix(extension): Restore status logging to extension

chrome-launcher/package.json, chrome-launcher/yarn.lock, package.json, yarn.lock
fixes #2618, https://github.com/isaacs/rimraf/issues/155, https://github.com/facebook/jest/issues/3942
I bisected and rimraf did fix this EPERM bug as of 2.3.0. it was one of these commits: https://github.com/isaacs/rimraf/compare/v2.2.8...v2.3.0
but i'm bumping all the way to 2.6.1 because why not
=> upgrade rimraf to latest

chrome-launcher/manual-chrome-launcher.js
making `chrome-debug --port=9222` work
=> launcher: support custom port via chrome-debug binary

lighthouse-core/gather/connections/connection.js
We just found a case (outside of Lighthouse) where we were getting this error:
Error: Protocol error (Network.continueInterceptedRequest): Invalid parameters
however there were extra details once `error.data` was logged as well:
Error: Protocol error (Network.continueInterceptedRequest): Invalid parameters (interceptionId: string value expected)
cc @aslushnikov
=> log protocol error data field

chrome-launcher/chrome-launcher.ts, lighthouse-cli/run.ts, lighthouse-cli/test/cli/run-test.js
Ran into this while writing https://github.com/GoogleChrome/lighthouse/pull/1832#issuecomment-313823375
If you just want the whole sequence and then want the LHR, it's really awkward. Adding this return at the end seems harmless. Sg?
----------------
Driveby fix to not log by default in launcher. Doesn't change LH usecases, just solo-launcher cases.
=> Expose LHR to modules consuming cli/run.ts

lighthouse-core/config/config.js
example config:
```js
module.exports = {
"extends": "lighthouse:default",
"settings": {
"onlyAudits": [
"is-on-https"
]
}
}
```
This ends up filtering out the defaultPass as there are no audits consuming a trace from it.
There are other ways to fix this. 
This is but one.
=> config rebuild: keep defaultPass

chrome-launcher/manual-chrome-launcher.js
```sh
❯ chrome-debug --hide-scrollbars
/Users/paulirish/code/lighthouse/chrome-launcher/manual-chrome-launcher.js:25
port = chromeFlags.find(flag => flag.startsWith('--port=')).replace('--port=', '');
^
TypeError: Cannot read property 'replace' of undefined
```
i introduced this bug in #2644. whoops.
=> fix launcher w/ arbitrary flags

lighthouse-core/config/fast-config.js
in the name of FastMode (#2703)
starting point for the FastMode config that I'll be adding to/burning down on for fast mode work
=> feat: add base fast mode config

lighthouse-core/audits/byte-efficiency/total-byte-weight.js, lighthouse-core/test/audits/byte-efficiency/total-byte-weight-test.js
AFAICT we don't record the raw number of network requests made by a page anywhere, since the total-byte-weight array of assets is limited to the top 10.
There are some interesting patterns with that number, apparently regardless of content/size of the requests (though details there may offer even more interesting stuff). The pattern doesn't end at 10, which is as far as the array length will reveal, so this keeps the raw number around in the `extendedInfo` (neatly sidestepping the central question of #2668 for now :) so the investigation can continue.
If we do record that number in the report, let me know and we can close instead.
=> track number of completed requests in total-byte-weight extendedInfo

chrome-launcher/README.md
Updated the readme to this commit https://github.com/GoogleChrome/lighthouse/commit/41df647f1b88b95980c03b2364d222a1e6804e58
I've added the deprecation note about `LIGHTHOUSE_CHROMIUM_PATH ` because it used in [other files](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/scripts/download-chrome.sh).
=> Added CHROME_PATH to readme
